### ISSUE TITLE
Bug Report: Eldar Craftworlds - (Codex 2015).catz

### ISSUE THREAD

**Issue by SweetJaysus** [BSData/wh40k-7th-edition#1003]
File: Eldar Craftworlds - Codex (2015).catz

BattleScribe version: 1.15.07

Platform: Android

Dropbox: No

Description: Farseer in the Seer Council cannot take "The Spirit Stone of Anath'lan" Remnant of Glory.

![](https://dl.pushbulletusercontent.com/i2thDP3Fsatk91T8i4wTiIiC6PMNWoR2/Screenshot_2015-05-14-13-29-58.png)

Edit: Compared to the Farseer in the Guardian Battle Host Formation.

![](https://dl.pushbulletusercontent.com/6MCWWuOlogBdyBsLzEG4O6XyaqycOwAH/Screenshot_2015-05-14-13-32-44.png)

**Comment by thebouv** [comment]
Same formation of Seer Council, but with Skyrunners, does allow you to take the Spirit Stone. Just FYI.

Don't have my codex with me but this is probably an omission to fix.  I could try later if no one else does.
