### ISSUE TITLE
Khorne Demonkin item defaults

### ISSUE THREAD

**Issue by azraelcow** [BSData/wh40k-7th-edition#1007]
Several units don't have default options set for some wargear:
- Blood Throne
- Chaos Lord
- Daemon Prince
- Defiler
- Forgefiend
- Heldrake
- Hellbrute
- Herald

**Comment by azraelcow** [comment]
Resolved in commit 227e867b94344304b11a367501fb0b18afc02f5a.

**Comment by amis92** [comment]
Writing `fixes`/`fix`/`close`/`closes` `#xyz` in commit message will automatically close mentioned issue. `Resolves` is not one of those keywords. :)

**Comment by azraelcow** [comment]
roger

**Comment by amis92** [comment]
Also, great job, thanks for nice contributions.
