### ISSUE TITLE
Imperial Knights (2015) Add 'Exalted Court of House Terryn' Formation

### ISSUE THREAD

**Issue by azraelcow** [BSData/wh40k-7th-edition#1008]

**Comment by senpai514** [comment]
Has the datasheet for this been shared anywhere?

**Comment by azraelcow** [comment]
Has been shown on BOLS and 4chan

**Comment by azraelcow** [comment]
Resolved with commit c14af7449b10e8a164c6854f6dfeffb6d7a31c01.

**Comment by senpai514** [comment]
@azraelcow could you email me the link please to legiones.astartes@gmail.com

Thanks
