### ISSUE TITLE
Renegade

### ISSUE THREAD

**Issue by ansacs** [BSData/wh40k-7th-edition#1016]
The issue with the spawn and zombies was not fixed. So I fixed the file and am attaching a drop box link with the file. 
https://www.dropbox.com/s/r9zesp21b460fih/Renegades_of_Vraks_IASoV_-_The_Lost_and_the_Damned_%282015%29.catz?dl=0

For the zombies it looks like the max in force was set to 0 for the modifier rather than -1.

For the spawn it doesn't look like anything changed. 

Thanks for all the efforts in keeping this running. 

PS if you point me to a really complete step by step on how to get these changes submitted with github without getting a "you do not have permission" I can help make some of these changes (time permitting).

**Comment by amis92** [comment]
@ansacs please find me on [Gitter](http://gitter.im/amis92) and hit me with PM so I can help you with GitHub.
