### ISSUE TITLE
Dark eldar Succubus wych weapons

### ISSUE THREAD

**Issue by LHSnow** [BSData/wh40k-7th-edition#1018]
Selecting wych weapons for the succubus marks the pistol option as an error. The splinter pistol is not replaced by the wych weapon option and it is impossible to unselect the pistol manually.

**Comment by Throtard** [comment]
There is already an option to select Pistol: None. Someone had fixed this one before me?

**Comment by LHSnow** [comment]
Updated my data files but the problem persists. (edit: sorry about broken links in the first version of this comment)

[Pistol popup](http://i.imgur.com/WLrcCUf.png)
[Versions](http://i.imgur.com/T1S9Wkl.png)

**Comment by Throtard** [comment]
My fault, the bug appears in mobile app, not in desktop version.

**Comment by Throtard** [comment]
Fixed, as a secondary effect the succubus comes without any pistol selected (and you have a warning for that), but you can put the weapons correctly.

**Comment by LHSnow** [comment]
The current version is still 12 though. Are we waiting for other fixes or has the changes not been released yet?

**Comment by Throtard** [comment]
The v13 isn't released yet. You'll have to wait a little ;)
