### ISSUE TITLE
[Space Marines ] tactical squad chainswords

### ISSUE THREAD

**Issue by mathaius90** [BSData/wh40k-7th-edition#1020]
Only the Sergeant can swap the boltgun for a chainsword, not everyone.

**Comment by senpai514** [comment]
That option is there for chapter tactics charcardons

**Comment by mathaius90** [comment]
Isn't there a way to make it a ct-bound option like special characters or bikes as troops?

**Comment by senpai514** [comment]
What platform are you using for your battlescribe?

**Comment by mathaius90** [comment]
Android and Windows. ATM I am from mobile.

**Comment by senpai514** [comment]
It should be set to be hidden by default but sometimes some mobile
platforms don't always have rules operate quite right. I'll double check
the catalogue to make sure.

**Comment by pretzalcohuatl** [comment]
new codex; even worth bother to see if this is a bug?

**Comment by Stribbs** [comment]
Some people may prefer to use 6th edition

**Comment by pretzalcohuatl** [comment]
Sounds good

**Comment by amis92** [comment]
Oh and also, @whiskeyjuvenile  - we do have that wh40k-old repo, where those deprecated files are thrown out in case anyone ever wishes to use it. :)
