### ISSUE TITLE
Chaos Space Marines - Missing Formation

### ISSUE THREAD

**Issue by cartag** [BSData/wh40k-7th-edition#1025]
Kranon's Helguard isn't included as a formation option. 

FORMATION
 •    1 Chaos Lord
 •    1 unit of Chosen
 •    1 unit of Chaos Terminators
 •    2 units of Chaos Cultists
 •    1 unit of Raptors
 •    1 Chaos Land Raider
 •    1 Helbrute

RESTRICTIONS
All units in this Formation must have the Chaos Space Marines Faction. 

SPECIAL RULES
Fear, Stubborn.
 Swarm of Phantasms: Enemy units that are within 12" of at least one unit from this Formation subtract 1 from their Leadership. Enemy units that are within 12" of at least two units from this Formation also subtract 1 from their Ballistic Skill, to a minimum of 1

**Comment by NebSeele** [comment]
I will have the formation added over the upcoming weekend.
