### ISSUE TITLE
CSM: Cult Marines and Marked HQs

### ISSUE THREAD

**Issue by Xabre1342** [BSData/wh40k-7th-edition#1029]
So I'm noticing that when you take a Sorcerer and mark it for Tzeentch, or a Lord and mark for the others, the squad leaves the Elite section... but does NOT enter the Troop section.  Deleting the marked unit does not fix it.

**Comment by NebSeele** [comment]
strange it does that. as I have just tested it (with the catalogue editor open to confirm first the modifiers work), and it still works as intended. Am I able to get the following details to work out the issue? 
1. The platform you are trying to use the catalogue on
2. The CSM catalogue version number?

If it's still not working, there should be a "Show hidden force org options entry on the no cat section, which if entered should force the hidden options to show.

**Comment by pretzalcohuatl** [comment]
Are you referring to the squad in Available Entries or in Roster Selections?  It's moving the squads from Elites to Troops properly in Available Entries, and Battlescribe doesn't support modifying a category of an entry.
