### ISSUE TITLE
Bug Report: Tyranid Children of Cryptus Shield of Baal: Deathstorm

### ISSUE THREAD

**Issue by MightyQue** [BSData/wh40k-7th-edition#1041]
I am building exactly whats in the book. I noticed all the pictures of the genestealers dont have rending claws, just scything talons. The Brood lord has the rending claws... 

When I print out the Children of Cryptus it says for genestealers 8x rending claws, 8x scything talons...  Adding Rending claws puts the total over 215.

The Psyker powers for Cryptus, the Horror and Dominion are not listed either...

**Comment by MightyQue** [comment]
Is there another place to post questions or issues with files or a way to contact who created the file ?

**Comment by Throtard** [comment]
Hello, opening issues here is the best method to give and receive feedback ;)
You should check the rules of that unit, not the photos. Besides, genestealers always have rending claws.
I'd revised the entry and everything is correct, including points cost. I'll add the powers in the next revision.

**Comment by MightyQue** [comment]
Since the Phodian Hive warriors cant be made by using the codex as they
seem special figures for the purpose of the Deathstorm box, thought the
genestealers were the same (no rending as pictured.

thanks for the reply and update...
