### ISSUE TITLE
White Dwarf content & Adeptus Mechanicus War Convocation formation

### ISSUE THREAD

**Issue by Throtard** [BSData/wh40k-7th-edition#1044]
Two fast questions:
1. As an official source, I think I should add WD rules, like exclusive dataslates, formations, etc. Is this correct?
2. If the answer to question 1 is affirmative, I'll have to create one that requires 3 detachments, each one from a different catalogue, and override costs of every upgrade and option. Any advice?

**Comment by Toreador13** [comment]
Any official source, so even if someone can get a hold of the exclusive Court Mechanicus formation we should add it. Any and all Official source material. Which could get crazy based on what GW has been doing as of late.

**Comment by Throtard** [comment]
Ok, I'll figure out how to make the formation. Thanks :)

**Comment by senpai514** [comment]
How would you propose that be accomplished?

**Comment by Toreador13** [comment]
Have to wait for someone to buy it and provide it ;)

**Comment by Kangodo** [comment]
Ever heard of tehparadox.com? They are really helpful.

Sent from my HTC

----- Reply message -----

**Comment by amis92** [comment]
Okay, I think questions answered, am closing. If needed you can always reopen.
