### ISSUE TITLE
Codex: Space Marines (2015)

### ISSUE THREAD

**Issue by senpai514** [BSData/wh40k-7th-edition#1045]
I will be getting started on the catalogue foundations setting up the shared rules and profiles and other basics that will not be changing. This is going to be a lot of work to do once I get my hands on the codex. Just wanted to give you guys the heads up that I will be taking care of it.

Codex Space Marines - SENPAI514

HQ
- [x] Captain Sicarius
- [x] Chief Librarian Tigurius
- [x] Chaplain Cassius
- [x] Sergeant Telion
- [x] Sergeant Chronus
- [x] Kor'sarro Khan
- [x] Vulkan He'stan
- [x] Shadow Captain Shrike
- [x] Captain Lysander
- [x] Pedro Kantor
- [x] High Marshal Helbrecht
- [x] The Emperors Champion
- [x] Chaplain Grimauldus
- [x] Captain
- [x] Librarian
- [x] Techmarine
- [x] Chaplain

Troops
- [x] Tactical Squad
- [x] Scout Squad
- [x] Crusader Squad

Elites
- [x] Command Squad
- [x] Honour Guard
- [x] Centurian Assault Squad
- [x] Vanguard Veteran Squad
- [x] Sternguard Veteran Squad
- [x] Dreadnoughts
- [x] Venerable Dreadnoughts
- [x] Ironclad Dreadnoughts
- [x] Legion of the Damned
- [x] Terminator Squad
- [x] Terminator Assault Squad

Fast Attack
- [x] Assault Squad
- [x] Scout Bike Squad
- [x] Bike Squad
- [x] Attack Bike Squad
- [x] Land Speeder Storm
- [x] Land Speeders
- [x] Rhino
- [x] Razorback
- [x] Drop Pod
- [x] Stormtalon Gunship

Heavy Support
- [x] Devastator Squad
- [x] Centurian Devastator Squad
- [x] Thunderfire Cannons
- [x] Predators
- [x] Whirlwinds
- [x] Vindicators
- [x] Hunters
- [x] Stalkers
- [x] Stormraven Gunship
- [x] Land Raider
- [x] Land Raider Crusader 
- [x] Land Raider Redeemer

Lord of War
- [x] Marneus Calgar

Wargear List
- [x] Ranged Weapons
- [x] Melee Weapons
- [x] Terminator Weapons
- [x] Heavy Weapons
- [x] Special Weapons
- [x] Special Issue Wargear
- [x] Dreadnought Weapons
- [x] Chapter Relics
- [x] Space Marine Standards
- [x] Space Marine Vehicle Equipment

Detachment
- [x] Gladius Strike Force

Formations
- [x] Battle Demi Company
- [x] Strike Force Command
- [x] Reclusiam Command Squad
- [x] Librarius Conclave
- [x] Armoured Task Force
- [x] 1st Company Task Force
- [x] Anti-air Defense Force
- [x] 10th Company Task Force
- [x] Storm Wing
- [x] Suppression Force
- [x] Centurion Siegebreaker Cohort
- [x] Land Raider Spearhead
- [x] Strike Force Ultra

Blood Oath Supplement
- [x] Ultramarines 1st Company
- [x] The Spear of Sicarius

Other updates
- [x] Space Marine HQ Command Tanks
- [x] Flyer Aces
- [x] St Tylus Battle Force
- [x] 1st Company Hammerfall Assault Force
- [x] 1st Company Skyspear Assault Wing
- [x] Skyhammer Annihilation Force

**Comment by amis92** [comment]
Great. May I ask you do it on a separate branch, and push regularly so as to give us a hint where are you in terms of progress etc.? That would be very helpful and much more correct in terms of git.

I want to start improving our flow here, because of the higher and higher traffic and update rates. We need to step up our game. :D

**Comment by senpai514** [comment]
how would I go about for the seperate branch? Where can I find that I info?

**Comment by amis92** [comment]
Are you using GitHub for Windows? If so, then just click where you see 'master' in upper ribbon, and there you can enter new name and 'create' it. After that 'sync' will change to 'publish' - publish and it's here on the web. Then just commit and sync just as you'd do on 'master'.

**Comment by Viper666-Qc** [comment]
This is starting to get pretty complicated with dataslate formations vs codex formations with same names but different rules..... good luck (and good job) guys !

**Comment by senpai514** [comment]
Actually it's not as bad as you think the storm wing, strike force ultra
and reclusium command squad are just new versions of the formation they
will replace the previous. None of them will be duplicated the new just
replaces the old.

**Comment by ghost** [comment]
There is an effort in progress on The Bolter and the Chainsword that could probably just use porting to the BSData version of the game system file. 
The author also indicates he is refactoring to use more shared entries.
I mention this mostly because he is already fairly far along, and in the interest of avoiding double work.
Take a look at how far he has gotten: http://www.bolterandchainsword.com/topic/309161-7th-edition-codex-battlescribe-files-v8-is-up/

**Comment by Toreador13** [comment]
Also, if you need any help I can chip in. Have the codex and time.

**Comment by amis92** [comment]
Ok so, I think we're ready to release. It's quite weird to have DAs released before even official Codex hits... But even weirder it's up before main SMs. What say ye', @senpai514 ? If you think it's ok, make a pull request (it can be done via updated GitHub for Windows app, even) and we'll do the release.

**Comment by senpai514** [comment]
@amis92 Im working some more now I want to do a couple more squads real quick especially the troops for at least CAD workability

WOOHOO Heavy Support done!

**Comment by amis92** [comment]
Sure, no prob. Make pull request when ready, no rush.

**Comment by senpai514** [comment]
@amis92 ok I have done all I have time for tonight pull request in I need to go eat something finally. I would ask when issues start coming in due to a couple units are still outstanding please allow me to resolve the issues as I will continue working the catalogue and would like to avoid double work glitching my files again from someone else unintentionally.
 Thanks

**Comment by pretzalcohuatl** [comment]
Added on Skyhammer Annihilation Force from GW Webstore exclusive.

See: http://i.imgur.com/ahoeIQH.jpg

**Comment by pretzalcohuatl** [comment]
Fixed Assault Marine Shared Entry:
1: Could select jump packs more than once
2: Sergeants could have eviscerator and bp/ccw

**Comment by senpai514** [comment]
@whiskeyjuvenile you should have contacted me before adding in anything to make surethat something you do hasn't already been done. When two people start sending commits at the same time the files tend to get scrambled and work sometimes gets lost.  Im only picky about proper coordination beacause I had expierenced this problem before.

**Comment by pretzalcohuatl** [comment]
sorry, did I screw anything up?

I'm going to be around tomorrow during daytime EST and would be happy to bang out the rest of FOC if you're not doing that, and work on some of the formations

**Comment by pretzalcohuatl** [comment]
BTW, the hybrid formation/{core/aux/command} formations should probably be moved to shared entries, with two links, as categories can be assigned to the link itself (if this works)

**Comment by senpai514** [comment]
I don't know if anything you have done will conflict. Have you checked out
the gitter chat we have?

**Comment by pretzalcohuatl** [comment]
I have now

**Comment by senpai514** [comment]
Attention all
 this catalogue has gotten glitched and locked up in my github for windows due to conflicting commits. Please do no further work until I can resolve this issue to prevent the loss of any data and work done.

(side note- catalogue authors usually have a reason for how and why they organize their entries. Changing them without notice and consent might not be appreciated.)

**Comment by Thairne** [comment]
@amis92 
What we see here is exactly the reason why I started work on the new file early.So far I think I've put about 10h into the file restructuring, fixing and incorporating the leaks.
I did a release because I redid the entire catalogue with links in mind and announced that in a popular 40k DA group to have some beta testers so we can hit a complete, stable full release when the actual codex drops.
It may be weird, but it will give us a smoother launch than otherwise :)

@senpai514 I feel with you. Keep it up, we know it's a load of work.
And honestly, if someone would screw with my catalogue without warning me at first I'd go hulksmash ;)

**Comment by thefbgnome** [comment]
Looking good... I see you have a checkbox on the captain... but captain has no options available... looking forward to having the bike entries (I play whitescars)

**Comment by senpai514** [comment]
@thefbgnome captain can take a bike. all options can be selected at the armour level then scroll down on the side to special issue wargear. Hopefully when I push the next release and update later this evening the bike squads will be done for you as well.

**Comment by LurkinLarkin** [comment]
When trying to use the Gladius Strike Force, there is no option to add HQ, Troops, FA or Heavy. The only options are (No Category), Auxiliary and Command. I am using the mobile version, haven't tried it on my Computer yet...

**Comment by senpai514** [comment]
I also have just a couple more things to do before completing functionality
on the GSF I will have them ready this evening

**Comment by senpai514** [comment]
The Gladius Strike Force is a detachment based force type different from
the standard Combined Arms Detachment which builds using HQ's and troops,
etc

**Comment by LurkinLarkin** [comment]
Cool, guessing your adding the option to add up to two Battle Demi-company's.

Keep it up dude, your doing a good job.

Cheers

**Comment by thefbgnome** [comment]
Ok Senpai514 on Capt getting bike(and other upgrades)... not intuitive... but I do see it... even so it is missing ability to upgrade to Chapter Master.

**Comment by pretzalcohuatl** [comment]
it's there, look harder (top-level option)

**Comment by thefbgnome** [comment]
Ok... found it... yeah I see the branching you did now... no wonder you dont want anyone making changes is non-standard although once I get used to it will make sense...

**Comment by pretzalcohuatl** [comment]
it's not non-standard any more now that a CM is a captain upgrade, which is important to some of the formations

**Comment by pretzalcohuatl** [comment]
Scouts missing camo cloaks, land speeder storm is 0 points

Boltgun/ccw/sniper rifle on boltgun arm of scout sgt and vet sgt have max selections 9 not 1

**Comment by pretzalcohuatl** [comment]
CAD should be fully usable as of latest commit

**Comment by senpai514** [comment]
well it will be for us right now everyone else will get it upon the next release

**Comment by pretzalcohuatl** [comment]
anyone can just download from github :)

**Comment by thefbgnome** [comment]
No we cant :) it shows ver 1 ... android and ipad cannot use the raw data... unless there is a link I cannot see?

**Comment by senpai514** [comment]
Yeah you need to go desktop first then data will be available for linked
mobile devices

**Comment by thefbgnome** [comment]
Thats what I thought me and most I know do not have this on desktop (I dont even have a desktop) no room on desk it is covered in Models ;)

**Comment by MasterCrafty** [comment]
Hi guys, just signed up to help with bug fixed, just put my whole army into CAD and found some point glitches etc.. sorry if already WIP but here you go:
- Honour guard point cost for power weapons. Should be included in base cost
- Honour guard requires a Chapter Master ( 0 allowed error pops up)
- No base cost for sternguard sarge, only costs wargear
- Vanguard options are 0 pts (relic blade, hammer, shield, fist etc.)
- SM Bikers do not default to TL Boltgun. This is fixed wargear, should not be an option (onlynscout bikes)
- SM bikers not a Fast Attack choice
- devastator ML have 0 pt cost

Cheers for the hard work guys will report more as i find them..... 

Cheers

MC

Edit. I am workibg on the Android App

**Comment by MasterCrafty** [comment]
Just in formations, no command squad option in the Demi Company.

Will you be bringing FW Characters into formations?

Ie, captain Mir'San being the 'captain' option in a demi company

**Comment by senpai514** [comment]
@MasterCrafty I have gotten those issue fixed up just should be good with next release. and for future issues you can open a new issue post.

Also FW characters will not be added into the formations. Only those models that are actually specified are allowed to be used

**Comment by MasterCrafty** [comment]
Cheers mate. Sorry if they were already reported, i'm a bit late to the
party ;)

Thanks for the update...

M

**Comment by senpai514** [comment]
actually I fixed them now from you reporting your not that late lol

**Comment by LurkinLarkin** [comment]
Hi, I'm playing around with it too. How long does it take for the new update to go up as I'm looking at the stern guard now and the sarge is still missing points...

**Comment by MasterCrafty** [comment]
Cool. Am doing some list building so will let you know if income across
more :)

**Comment by LurkinLarkin** [comment]
Also there is an alert to say you must have 4 Veterans in the squad. I've got 2x standard vets & 2x spec/heavy vets in the squad...

**Comment by senpai514** [comment]
To all please so not commit anything to the space marines. I have updates
pending but comp crashed this morn I hope to get up again right after work
and will check new issues then.

THANKS

........

**Comment by pretzalcohuatl** [comment]
refactoring per https://github.com/BSData/wh40k/issues/1108#issuecomment-114808262

e: crap, just saw your comment, sorry... :/

**Comment by amis92** [comment]
I appreciate your work, @whiskeyjuvenile, but why would you commit changes against @senpai514's clear request not to, good few hours before your commits? That's not exactly the kind of teamwork we come to expect here.

**Comment by pretzalcohuatl** [comment]
because I posted without reading

**Comment by Trigonous** [comment]
Great work! I can't believe how fast that was. A few issues I noticed:
Most land speeder weapons are 0pts
Sternguard sergeants are 0pts, should be 22pts
Vanguard sergeants and veterans have free thunder hammers, storm shields, and powerfists.

**Comment by amis92** [comment]
**Trigonous** please move that report to separate issue. I know that seems like a good place, but this issue is for general catalogue completion progress. Bugs should be reported separately. Thanks! :)

EDIT: ok, **whiskeyjuvenile** did that, see #1128

**Comment by Trigonous** [comment]
Apologies, I made a separate issue. Couldn't figure out how to tag it though

Edit: and now I see I made a duplicate, haha

**Comment by senpai514** [comment]
Well this has been a "interesting" time trying to work on files and push commits.  This is the reason I prefer to work on my own files solo. (not trying to sound unappreciative or ungrateful or anything) but we have seen a couple times lately what happens helpers collide both working on the same file, just like you cant have multiple guys trying to have the same dance partner someones toes are bound to be stepped on. 

This is not the first time I experienced it and unfortunately I'm also sure it wont be the last. that why the first around I did this a year ago: https://github.com/BSData/wh40k/wiki/Catalogue-Keepers - and maybe it can still help us, here you can see who the primary is for each army that is being worked on by somebody. that way when an issue came in you knew who would be going to take care of it; and typically in the past we would wait and the primary a chance to make his corrections the next opportunity they were online.  that way the guy that works during the morn can check on his stuff after work and knock out some updates instead of coming home and when he is online doesn't have anything left to do anymore. Plus who better to work on a particular catalogue than the one who has put untold hours into its detailing and work, not to mention we all have our different ways of creation and how we want something done. This is why respect for ones "work area", COMMUNICATION & COORDINATION should be key for allof us here to promote a fun friendly environment to do what we love.

**Comment by Thairne** [comment]
Well spoken.
