### ISSUE TITLE
[Anon] Space Wolves - include rules

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#1055]
**File:** Space Wolves - Codex.catz

**BattleScribe version:** 1.15.07

**Platform:** Windows

**Dropbox:** No

**Description:** ~~Selection rules will not show. Codex is useless when every other codex shows them but this one does not.~~ _Edit by amis92:_ Space Wolves Codex doesn't include rules yet. I'd love if you'd be so amazing to write them down to catalogue. Cheers!

**Comment by amis92** [comment]
I think thanks to @Stribbs we can close it now.
