### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by merlinbk** [BSData/wh40k-7th-edition#1064]
Hello. I would like to fix all of the descriptions in the Space Marine Codex that do not show up under Selection Rules. I would also like to make sure the Chapter Tactics descriptions show up.

**Comment by senpai514** [comment]
FYI the current space marine file that you see up will be going away soon.
That is the old 6th edition version. All that work would be for nothing.

**Comment by merlinbk** [comment]
Good point I'll wait until 7 ed is up and see if there's anything missing.

**Comment by senpai514** [comment]
Also I am the one that is writing the new space marine catalogue and
primarily works any bug fixes. That's why I replied in so that way you knew
what is currently already in progress behind the scenes.

**Comment by merlinbk** [comment]
Cool! If I see anything I'll report in. Do you have an ETA on the update?

**Comment by amis92** [comment]
How come I've missed it here. Hah. Ok well, I'll go ahead and send you an invitation, you shall accept it to join us. Then just wait until @senpai514 closes his main work part and chime in. Welcome aboard!
