### ISSUE TITLE
Sklore: 40k Orks

### ISSUE THREAD

**Issue by Sklore** [BSData/wh40k-7th-edition#107]
Hi Team, 

I have a copy of the latest Codex Orks and made a start creating a new battlescribe catalogue but it makes more sense to work as one. 

Josh

**Comment by amis92** [comment]
@Sklore please check the latest catalogue (recently refreshed) and feel free to contribute. If you're new to GitHub and/or BSData, please enjoy [Getting started](https://github.com/BSData/bsdata/wiki#getting-started) (by _me_ ;)
