### ISSUE TITLE
[Anon] Chaos Daemons (40K) - Codex Soulgrinder MoK points issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#108]
Mark of khorne on a soulgrinder is 15 points. It is suppose to be free.

**Comment by amis92** [comment]
Resolved in 1268aa6b621eff74b3c84490d8bd4ee885eae810 which was part of release [v4.1.2](https://github.com/BSData/wh40k/releases/tag/4.1.2)

It is also duplicate of #75
