### ISSUE TITLE
Necron Decurion Attachment - Missing Selection Rules

### ISSUE THREAD

**Issue by greggoman** [BSData/wh40k-7th-edition#1080]
When selecting a Decurion Detachment it does not add the following rule

Command Benefits: 
Ever living: Models in this Detachment with the Reanimation Protocols special rule receive a +1 bonus to Reanimation Protocols rolls. Models in this Detachment with the Living Metal rule ignore the effects of Crew Stunned and Crew Shaken (but still lose a Hull Point).

**Comment by Stribbs** [comment]
Its strange, the conditions were there in the file but were not showing in the catalogue editor.
Setting the conditions again looks like it fixed my local roster, let us know if v8 doesn't fix the issue.

**Comment by greggoman** [comment]
Looks like it's fixed! Ta =)

**Comment by pretzalcohuatl** [comment]
Fixed
