### ISSUE TITLE
[Anon] Necrons - Pylon update from WZ Damnos

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#110]
The pylon was updated in warzone damanos. It has lost interceptor, the flux arc was changed to 6 shot strength 6 ap 4 to d3 + 3 units and the point cost was changed to 515 points.

**Comment by Kangodo** [comment]
After some googling I found out the issue!
Apparently there is an Apoc-only Pylon and a Gauss Pylon that can be used as LoW.
I will add both to the roster :)
