### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by afraeve** [BSData/wh40k-7th-edition#1104]
Hi, I would like to join and help out. I've got good experience making BattleScribe files, not so much with GitHub.

**Comment by amis92** [comment]
Hi there, there is always a great need for the likes of you. Glad to see experienced writer come here. Please do read the wiki carefully (https://github.com/BSData/bsdata/wiki#tutorials) - there are some helpful tips to get you started with GitHub, and you can always ask us - we have chat room on gitter (login with github account). Remember to accept the invitation too. Welcome aboard!
