### ISSUE TITLE
Gladius detachment no core options

### ISSUE THREAD

**Issue by spownall** [BSData/wh40k-7th-edition#1105]
BattleScribe v1.15.07
Space Marines: Codex (2015) v1
MacOS Yosemite

In the available entries pane, under the Gladius Strike Force selection, there are only options for Auxiliary, Command, and No Category: the Core formation options seem to be missing.  No change after adding any Chapter Tactics or other formation options.

**Comment by senpai514** [comment]
Still in process for creation see #1045
