### ISSUE TITLE
Space Marine supplements

### ISSUE THREAD

**Issue by afraeve** [BSData/wh40k-7th-edition#1112]
Updated the Sentinels of Terra, Clan Raukaan, Siege Assault Vanguard and the Tyrant's Legion (the chapter support section) with the data from the new codex. Since it's a big change I've made a new branch, so interested members can give their approval or not, but we've checked them for errors & they should be good to go.

**Comment by pretzalcohuatl** [comment]
Voting wait for FAQ on these before merging.

**Comment by afraeve** [comment]
There's a few small issues with the SAV (the pdf for it has the old profile for the Ironclad Dread, points value for the Vindicator and some other quirks) but I've included an option that allows you to switch between the two settings, along with a note explaining this. I'm not sure the other files need an faq.

**Comment by senpai514** [comment]
sentinels of terra is easy for the conversion. However Clan Raukaan requires some modifications due to the change in techmarines. And yeah siege assault does need a FW update again

**Comment by amis92** [comment]
Okay, so yeah, FAQ is needed, but I think the update could be merged. It's more correct for SM 2015 than what is currently, isn't it?

**Comment by afraeve** [comment]
I've updated the description on the Siege Van 'faq', to make it clearer exactly where any conflicts have arisen. By default the file uses the codex, since the differences are really no more than an oversight, but people can switch to the pdf data if they wish to.
For Clan Raukaan, their 'Scions of the Forge' rule allows the Techmarines to be taken in both categories - there's not any wordy-trickery rules-lawyering or anything like that :)

On a side-note, I was looking at the "Book(s)" field of the file header. The complete list for this cat might look something like:
"including C:SM (2015), IA2se, IA4se, IA12, IAApoc (2013), WZ:Armageddon, plus any relevant PDFs or Dataslates"
but I felt that looked scruffy when trying to select a force in the roster editor, so I've left it blank for now. Any thoughts, and is this what gitter is for?

**Comment by pretzalcohuatl** [comment]
Wait, you're using Siege Van from IA10 not from the FW PDF?

**Comment by pretzalcohuatl** [comment]
Also your repository is private

**Comment by amis92** [comment]
He's commited the changes on SM-supplements branch in this repo, if you can't find it.

**Comment by afraeve** [comment]
I'm using the pdf - I meant that with the conflicts on things like the Ironclad profile, you can switch between the Codex (A=4) and the pdf (A=2).
