### ISSUE TITLE
Move Space Marines - Codex.cat to wh40k-old?

### ISSUE THREAD

**Issue by pretzalcohuatl** [BSData/wh40k-7th-edition#1113]
I think Space Marines - Codex (2015).cat is in usable state now.
#1045

**Comment by senpai514** [comment]
Id let it be for a week or so for transition period

**Comment by Stribbs** [comment]
having the year of publish is enough to differentiate the codices

**Comment by amis92** [comment]
@Stribbs sure, but it's what we do - after a week we remove old and place it in BSData/wh40k-old .

**Comment by pretzalcohuatl** [comment]
just as a reminder

**Comment by Thairne** [comment]
Old DA dex is due to being moved on saturday too
