### ISSUE TITLE
Warhammer40K.gst - Prefix codex-specific force types with source codex?

### ISSUE THREAD

**Issue by pretzalcohuatl** [BSData/wh40k-7th-edition#1114]
I've got no idea what codex corresponds to, e.g., "The Purge"

**Comment by senpai514** [comment]
that is for the siege of vraks.

**Comment by pretzalcohuatl** [comment]
right, but do we expect users to know all that?

**Comment by senpai514** [comment]
If they play using a certain army build then they should have the relevant rules and know what they can do.

Sent from Windows Mail

**Comment by pretzalcohuatl** [comment]
What about for people who like to screw around in battlescribe for armies they don't own yet?

**Comment by amis92** [comment]
Well, we know for sure that _soon_ (which is undefined, but still), Jon (author of BattleScribe) will push an update which will allow us to: 1. create shared rules and entries in game system file, 2. put limits on which force types can be used with given catalogue.

I'd wait and make changes after update.
