### ISSUE TITLE
Bug report: Space Marines - Codex (2015).catz

### ISSUE THREAD

**Issue by LurkinLarkin** [BSData/wh40k-7th-edition#1122]
Sternguard Vet Squad:
- Sargent points missing
- Unable to have 2x Vets & 2x Special/Heavy Vets
- Missile Launcher (F&K) no points cost and no option for flakk

**Comment by LurkinLarkin** [comment]
First time doing this. Any advice let me know!

**Comment by pretzalcohuatl** [comment]
Already fixed sergeant points pending release

I'll take care of the rest in a bit

**Comment by LurkinLarkin** [comment]
Thanks, so guess this is the right way to do it then?

**Comment by pretzalcohuatl** [comment]
Sure.  Fixed the Vets bug.  Flakk is an option for the missile launcher itself, and did work properly.
