### ISSUE TITLE
Space Marines (2015) bugs

### ISSUE THREAD

**Issue by pretzalcohuatl** [BSData/wh40k-7th-edition#1128]
From https://github.com/BSData/wh40k/issues/1045#issuecomment-115010051:

Most land speeder weapons are 0pts
Sternguard sergeants are 0pts, should be 22pts
Vanguard sergeants and veterans have free thunder hammers, storm shields, and powerfists.

note: (sgt pricing already fixed)

**Comment by Mnemonic775** [comment]
Reasonably sure this is the place for this comment, but constantly (deleted data a couple times and redownloaded) when I try to create a Formation Detachment, Bscribe locks up and becomes totally unresponsive.

Using an IPhone 6, BScribe pro if that makes any difference.

**Comment by amis92** [comment]
@Mnemonic775 :
https://github.com/BSData/wh40k/issues?utf8=%E2%9C%93&q=space+marines+crash gives a result: #1119. So the place for comment is reasonably here, but not completely. :)
