### ISSUE TITLE
Bug report: Space Marines - Codex (2015).catz

### ISSUE THREAD

**Issue by Trigonous** [BSData/wh40k-7th-edition#1129]
**File:** Space Marines - Codex (2015).catz

**BattleScribe version:** 1.15.07

**Platform:** Android

**Dropbox:** Yes

**Description:** Just a few point costs:
Most land speeder weapons are 0pts
Sternguard sergeants are 0pts, should be 22pts
Vanguard sergeants and veterans have free thunder hammers, storm shields, and powerfists.

**Comment by amis92** [comment]
So, yeah, duplicate :D #1128
