### ISSUE TITLE
Orks - Codex

### ISSUE THREAD

**Issue by katfude** [BSData/wh40k-7th-edition#113]
Blitza-bommer and Burna-bommer: file lets you take a fighter ace. Per codex, fighter ace is NOT an option.

**Comment by ghost** [comment]
Fighter Ace is an option from the Death From The Skies / Crusade Of Fire thingamyjig, along with the Special Manoeuvres rule. Not to be confused with the Dakkajet's Flyboss option (that was originally called Fighter Ace in WD390).
