### ISSUE TITLE
Detachment-specific rules

### ISSUE THREAD

**Issue by pretzalcohuatl** [BSData/wh40k-7th-edition#1130]
![Image of fix](http://i.imgur.com/ce6lQsA.png)

Catalogues needing updating:
- [ ] Space Marines (2015)
- [x] Dark Angels (2015)
- [ ] Eldar Craftworlds
- [ ] Siege Assault Vanguard
- [x] Necrons (2015)
- [x] Cult Mechanicus
- [x] Skitarii
- [ ] Blood Angels
- [ ] Imperial Knights
- [ ] Grey Knights
- [ ] Harlequins
- [x] Daemonkin
- [ ] Officio Assassinorum
- [ ] Orks
- [ ] Space Wolves
- [ ] Tyranids

Feel free to add more codex-specific detachments to this list, I'm working off the top of my head.  Inquisition and LOTD detachments not included as they don't have any detachment-specific rules.

**Comment by amis92** [comment]
Seeing as there is more and more of those thingys, I think we may create a category for all those detachment specific entries. What do we have: relics, detachment rules, detachment notes for unexecutable requirements, anything else?

**Comment by amis92** [comment]
It'd be a min 0 max 1 category added to each and every force type (well, in some it might be min 1 if it's expected to be required). Named, say, "Detachment Options"?

**Comment by pretzalcohuatl** [comment]
Detachment Rules

**Comment by amis92** [comment]
Well yeah, but relics and so on aren't rules exactly.

**Comment by pretzalcohuatl** [comment]
relics have always been shared entries, though, why would they be in the detachment itself?

like you only need the relic rules/profile/etc. if someone's actually taken the relic as wargear

**Comment by whiskeyjuvenile** [comment]
like you only need the relic rules if someone's actually taken the relic as wargear

**Comment by amis92** [comment]
I might be wrong, but I think Blood Angels and Orks have some things dependent upon detachment selected. I don't know really. Trying to be generic as possible, taking into account what Games Workshop is capable of ;) .

**Comment by pretzalcohuatl** [comment]
if something's dependent on detachment, use the modifier conditions on parent force is instance of

**Comment by Toreador13** [comment]
I agree with Whiskey, why do we really need this? You can base most of this off of the parent force to show detachment rules.

**Comment by amis92** [comment]
@Toreador13 I'm not sure if you agree with Whiskey on that, as he wants to create an entry with rules. I'm not even sure what it's all about in the first place - the "show" modifier put on the entry in picture can as well be put on rule in catalogue root.

**Comment by Stribbs** [comment]
It just looked like a nice looking spot to put detachment specific rules and/or modifiers.  Perhaps it can be expanded to set which formations one can legally bring and how many.

**Comment by amis92** [comment]
Nah, that's coming in next BattleScribe release, no need to do it twice. (talking 'bout selecting force types for catalogue).

**Comment by pretzalcohuatl** [comment]
@amis92 d'oh you're right.  nevertheless, none of the detachments have these rules

**Comment by pretzalcohuatl** [comment]
![do this](http://i.imgur.com/x6plDrm.png) 

this is what you're talking about, right?

@Stribbs points out that the catalogue editor has a bug where you don't see the conditions after you reload the catalogue in the editor

e: Upon testing, the condition is still in the .xml, but you can't see it any more

**Comment by amis92** [comment]
Damn. Good I've started work on my own catalogue editor, those bugs are killing me. Or rather, the inactivity in resolving/fixing them. :/

edit: yeah, that's what I'm talking about, of course.

**Comment by pretzalcohuatl** [comment]
fork battlescribe (defaultSelections="" would be a big help to have for instance)

**Comment by Stribbs** [comment]
they do work as intended, they'll just not show in the editor.

**Comment by pretzalcohuatl** [comment]
I'd say just leave as an entry for the time being (i.e., the way it was handled in #1131 7bc1f895e55f7039d2ed81595f7f964918f4f761) for ease of maintenance

**Comment by Thairne** [comment]
Only problem with that solution is - there is no way to automatically hide the rule/the link to the rule.
You may tell it to "show" - but it is already shown. That means you have to hide it via a "or" condition group for every other possible detachment that catalogue may be used for.
A "not instance of" would greatly help, sadly we only have the "instance of" modifier. That or the ability to hide a rule by default, just like we can with entrys by the "hidden?" checkbox.

**Comment by Stribbs** [comment]
@whiskeyjuvenile I tested using an entry with a detachment rule inside and the rule was never displayed in the View Roster output.  The decurions original method does work but has the bug where the conditions for it don't show in the catalogue editor after reloading.

That's why I closed #1131 before it could be merged as it didn't work for me.

I also don't like that using entries the person has to select the detachment as a force type and then select it again in the catalogue.

**Comment by Stribbs** [comment]
@Thairne It seems the functionality goes both ways for 'instance of'. The rule **only** shows up if the instance of is true, otherwise its hidden.  I wonder what the functionality of it is if you hide if the instance is true. (don't have time at the moment)

Adding the rule as an 'instance of' within an OR condition sounds like the logical way to do it for multiple detachments.

If there's a rule that the detachment adds to a formation you'd use an AND with instance of parent force 'detachment' and parent category 'core/auxillary/etc'.

**Comment by Thairne** [comment]
I cannot confirm that.
I've tried that and the rule showed up. I've just done a small repro and it shows up despite the condition being false. Works as far as expected with the 'show' and 'hide' modifiers. Either that or I'm still not understanding how it works...

As you can see, the testrule should only show up in a DWSF. However I still see it in a CAD. I have to specifically hide it for the other detachment types.
![untitled](https://cloud.githubusercontent.com/assets/8590840/8352803/3a16fb4c-1b38-11e5-9e84-298af43ff7f7.jpg)
![untitled2](https://cloud.githubusercontent.com/assets/8590840/8352806/3cf47af6-1b38-11e5-96c4-9210666baed2.jpg)

**Comment by pretzalcohuatl** [comment]
Did you click the hidden? checkbox on the rule itself?

**Comment by Thairne** [comment]
Gods. I'm blind. It's on the very bottom...

**Comment by pretzalcohuatl** [comment]
I didn't notice it until after @amis92 posted https://github.com/BSData/wh40k/issues/1130#issuecomment-115027454

**Comment by Stribbs** [comment]
@Thairne sorry, I forgot about it too. I must have set the hidden flag without thinking when I looked into the Necron detachment rule issue.

**Comment by NebSeele** [comment]
Khorne Daemonkin's Blood Host rules have been added now.

**Comment by pretzalcohuatl** [comment]
bump

**Comment by osyanin** [comment]
What need to add.
Dark Angels Lion's blade with free transport for two strike forces. Full company.
This way it making easier, but not fot a much different options:
https://docs.google.com/spreadsheets/d/1AR2xJJWMSiQotJYvk-b-7mNhERRVDDla_CyDRa8ZgdU/htmlview

**Comment by Thairne** [comment]
Firstly, that document is locked.
Secondly, I don't really understand what you're saying.
Thirdly, it is already in the file and working, so what is the issue?

**Comment by efalsken** [comment]
It seems like we need "not an instance of" condition. So we can put the rule there, but "hide if parent force is not an instance of `detachment type`"

**Comment by Thairne** [comment]
Or you turn around, make it hidden and only show if parent force IS instance of...

**Comment by efalsken** [comment]
You can't make rules hidden without hanging them off of an Entry item (which can be hidden).

We managed to do something similar in 40k the Tau catalog by creating a Shared Rule with a modifier to hide if parent force has 0 selections of the Hunter Cadre (currently the only possible required formation item). Then we linked the rule to the root of the catalog. This works as intended without glitching the Roster editor and without throwing obtuse errors.

**Comment by Thairne** [comment]
And that is like everyone else is doing it currently afaik :P
So there still is no need for an Not Instance Of, you, just as I said, hide the rule and show in specific conditions.

**Comment by efalsken** [comment]
Well, it didn't work for the Dawn Blade Contingent since they both shared the same "Core" formation, but didn't share any rules in common. So I've nixed the Detachment rules for both the Hunter Contingent and Dawn Blade Contingent for now. (The shared rules are still present)

**Comment by amis92** [comment]
I re-suggest creating `Detachment Options` category. We really start to need it, I think.

**Comment by efalsken** [comment]
Agreed. But it's still a hack around a Battlescribe bug.

**Comment by amis92** [comment]
Partially. I honestly think that there is a reason for that even after that bug would be fixed. There will be more additions like Farsight and Cadians, and we have a mayhem right now with Space Marines. Chapter Tactics would perfectly fit into this category.

I mean, No Category is quite random and while it is enough for us right now, it can shortly stop to.

**Comment by ddarz** [comment]
So seeing as I am working on SM right now, what's the best way to go about getting this done? :)

**Comment by efalsken** [comment]
I'm not really sure. I ended up needing to remove the detachment-specific rules from the Tau catalog since there was no way to hide/show them depending on the detachment type.

**Comment by hisop** [comment]
@amis92 Since there has been a mixed at best approach to these, should we put a request in on battle scribe? or push on with the workarounds? ether way with no consensus it feels destined to sit here...

**Comment by OftKilted** [comment]
@hisop @amis92 @efalsken Does anyone have an example of this issue up and functioning repeatedly that we can provide to @Jonskichov to help with https://github.com/BattleScribe/Alphas/issues/25

**Comment by efalsken** [comment]
I could easily produce one. the problem with leaving it in the catalog is that it ends up showing for every detachment.

At the root level: Add a rule. Check the Hidden box. Modifier: Show if Parent Force is instance of Special Detachment.

Desired behavior: The rule should be shown for the force (not the entire roster). Visible only if the detachment is one of the selected instances.

Current behavior: The rule is not shown on the printed roster.

**Comment by hisop** [comment]
Since we want this addressed in 1.16 i have tagged it appropriately.

**Comment by hisop** [comment]
Closing this, as discussed this is mostly implemented and will be reworked on an individual basis by cat editors.
