### ISSUE TITLE
Space Marines (2015) load roster bug

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#1138]
**File:** Space Marines - Codex (2015).catz

**BattleScribe version:** 1.15.07

**Platform:** Windows

**Dropbox:** No

**Description:** Space Marines - Codex (2015).  When opening this codex Battlescribe states:

Message:
There were some problems with your data files. If you continue, this may lead to crashes or other strange behaviour.

> Space Marines: Codex (2015) v4: The catalogue data file is invalid:
> model.catalogue.Condition@3ec2d2: Condition must have a child that exists
> model.catalogue.Condition@17727a6: Condition must have a child that exists
> model.catalogue.Condition@c1c9f0: Condition must have a child that exists
> model.catalogue.Condition@1badc34: Condition must have a child that exists
> model.catalogue.Condition@1093e96: Condition must have a child that exists
> model.catalogue.Condition@142e86d: Condition must have a child that exists
> model.catalogue.Condition@8187ec: Condition must have a child that exists
> model.catalogue.Condition@717716: Condition must have a child that exists
> model.catalogue.Condition@f60b98: Condition must have a child that exists
> model.catalogue.Condition@15b7c92: Condition must have a child that exists
> model.catalogue.Condition@ecc826: Condition must have a child that exists
> model.catalogue.Condition@1a2c977: Condition must have a child that exists
> model.catalogue.Condition@1d25b52: Condition must have a child that exists
> model.catalogue.Condition@a76a17: Condition must have a child that exists
> model.catalogue.Condition@1a3ce3d: Condition must have a child that exists
> model.catalogue.Condition@8c76de: Condition must have a child that exists

**Comment by pretzalcohuatl** [comment]
PLEASE DO NOT EDIT THE STACK.

**Comment by pretzalcohuatl** [comment]
So it could have something to do with modifiers.  See https://github.com/BSData/wh40k/commit/7630a258e5f0300e693446fc8ec3d990ae250260#diff-5de48b6c1c054d5ca4eab45dbbe896e6L8624

incrementChildId="6b0fb3eb-9011-0189-7741-9bb7812c1d58" in Culln referred to a non-existent ID.  

Easiest way to validate would probably be to write a parser that extracts values from 
childId incrementChildId and incrementParentId attributes on the one hand, and id attributes on the other to make sure all targets actually exist.

**Comment by pretzalcohuatl** [comment]
Also https://github.com/BSData/wh40k/commit/898ecb557d6eae32e56a1b53700af64c997f6e30#diff-5de48b6c1c054d5ca4eab45dbbe896e6L12053

**Comment by pretzalcohuatl** [comment]
It seems like there's more, though...

**Comment by whiskeyjuvenile** [comment]
Good news I'm a masochist and am currently trying to work by hand through battlescribe's source code, wish me luck

**Comment by pretzalcohuatl** [comment]
https://github.com/whiskeyjuvenile/battlescribe-tools

**Comment by whiskeyjuvenile** [comment]
I think I found it: de22-54d3-049b-e814

**Comment by pretzalcohuatl** [comment]
I think I found it, which if confirmed, is definitely an iOS bug.

**Comment by amis92** [comment]
Duplicate of #1152 (main thread now)
