### ISSUE TITLE
Space Marine HQ Command Tanks

### ISSUE THREAD

**Issue by Commisar** [BSData/wh40k-7th-edition#1139]
Hello,

I am wondering if anyone could add the Space Marine HQ Command Tanks (Warhammer World Exclusive kit) to the new Space Marine datafile.

The Rules are included in the box with the kit itself, but I have scanned them and attached them.

Thanks folks.

![rhin-page-001](https://cloud.githubusercontent.com/assets/13049171/8354239/74720510-1b3e-11e5-9025-0830b721eca2.jpg)
![rhin-page-002](https://cloud.githubusercontent.com/assets/13049171/8354243/7d870ee8-1b3e-11e5-8edc-93a959c3ae63.jpg)
![rhin-page-003](https://cloud.githubusercontent.com/assets/13049171/8354247/860fdd7e-1b3e-11e5-9aea-f7a15322ebed.jpg)

**Comment by Thairne** [comment]
- [ ] Space Marines (2015)
- [ ] Dark Angels (2015)
- [ ] Space Wolves
- [ ] Blood Angels

**Comment by senpai514** [comment]
I have this on my list at #1045 for codex space marines already

**Comment by amis92** [comment]
@Commisar - Thank you for the input, but as **senpai514** suggested, it's already on the TODO list. :)
