### ISSUE TITLE
CSM Brass Scorpion

### ISSUE THREAD

**Issue by twizted86** [BSData/wh40k-7th-edition#114]
Does anyone have the information to add a Brass Scorpion to the LOW options for Chaos Space Marines?

**Comment by amis92** [comment]
And where are rules for this?

**Comment by twizted86** [comment]
There are rules for it in the Apoc supplement Pandorax and in Forge World's newest Imperial Armour Apocalypse.

**Comment by amis92** [comment]
Are they the same? I've got only IA: Apoc (2013), is it any good?

**Comment by twizted86** [comment]
Thank you. The IA one is the better of the two, it has more filled out rules.

**Comment by amis92** [comment]
Well actually I didn't have time to rewrite rules :( sorry about that
