### ISSUE TITLE
Crusader Squads

### ISSUE THREAD

**Issue by rabidrecoil** [BSData/wh40k-7th-edition#1143]
Adding a special weapons and power/heavy weapons adds an initiate + weapon instead of just the weapon. Additionally in the case of special weapons it adds the weapon + initiate to the squad at the cost of the special weapon only.

**Comment by pretzalcohuatl** [comment]
It's intended to add an initiate and a weapon.  Check the special weapon tho.

**Comment by ysveny** [comment]
And in addition do they not count to the minimum of 5 initiates if you add an initiate with special/heavy weapon or a sword brother.

ps: much thanks for the work you do!
