### ISSUE TITLE
(Space Marines/Dark Angels) iOS crash bug

### ISSUE THREAD

**Issue by pretzalcohuatl** [BSData/wh40k-7th-edition#1152]
**IF YOU ARE READING THIS, GO HERE AND VOTE**
http://battlescribe.uservoice.com/forums/55066-general/suggestions/8545201-chrash-on-ios

My theory is that it has to do with conditions on parent force.

Space Marines (2015).cat has this line 16 times:

```
<condition parentId="force type" childId="de22-54d3-049b-e814" field="selections" type="instance of" value="1.0"/>
```

The trace in #1138 has 16 lines.

de22-54d3-049b-e814 is the ID for Gladius Strike Force in Warhammer40k.gst

I'm going to try borrowing my wife's iphone later and see what I can do...

**Comment by afraeve** [comment]
15 of those are the free transport modifiers & the last one is for Cluster Mines on Scout Bike Squads. It has an error: it should have the condition group "or", instead of "and", since the parent force can't be both at once.

**Comment by pretzalcohuatl** [comment]
I know.

**Comment by pretzalcohuatl** [comment]
My theory is that iOS Battlescribe is not handling conditions on force type correctly, leading to the crashes

**Comment by Jonskichov** [comment]
Looking into this now. Just an FYI, bear in mind that Apple take a week to "approve" app updates, so even if this turns out to be a simple fix on my end, it's still going to take a week to get the fix into the store...

Yes, this is annoying :/

**Comment by pretzalcohuatl** [comment]
Was I right?

**Comment by amis92** [comment]
Quoting @Jonskichov from #1119:

> Hey guys, just wanted to let you know what in the data is actually causing the crash:
> 
> Battle Demi Company (ID: 165d-32c9-8555-5e1c, Category ID: bf93-7277-bf48-16f7) (that's the "Core" category).
> 
> The crash is a null pointer error when you have a combined arms detachment in your roster (or any force without the Core category in it). BattleScribe is trying to get the parent Core category when validating the demi company, and of course not finding it since the CAD doesn't have one...
> 
> Why is this is only happening on iOS? No idea. It shouldn't be any different to Android or desktop. Probably something to do with the tooling I'm using when moving code to iOS.

**Comment by amis92** [comment]
Dark Angels are getting reports now.

**Comment by senpai514** [comment]
@amis92 Battlescribe v1.15.07 has fixed space marine & dark angels crashes I have tested and confirmed both catalogues do indeed work now with yesterdays update

**Comment by amis92** [comment]
Ok so it seems we have now another problem, rosters are not getting saved. But that is, I guess, another bug. Closing this.
