### ISSUE TITLE
[Anon] Bug report: Renegades__Heretics_Renegades_of_Vraks.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#1157]
**File:** Renegades__Heretics_Renegades_of_Vraks.catz

**BattleScribe version:** 1.15.07

**Platform:** Mac

**Dropbox:** Yes

**Description:** When selecting a PURGE formation from Renegades of Vraks, you should be able to add Chaos Spawn as elites without retriction. It is currently only valid in Battlescribe if you select mutant overlord as the devotion. In the book, it states they are only available through use of the master of renegades special rule, however mutant overlord is not a devotion in Vraks, and Tzeentch cannot be taken as a covenant. Emails from Forgeworld have subsequently confirmed this 'requirement' was added to the chaos spawn entry in the book in error.

**Comment by afraeve** [comment]
This has been sorted in the "Renegades & Heretics - FW.cat"

We should remove the "Renegades__Heretics_Renegades_of_Vraks.cat" file, probably along with the three original R&H files (Defenders of Vraks, Servants of Slaughter, Servants of Decay) if no-one has any objections.

**Comment by NebSeele** [comment]
The renegades of Vraks catalogue is aligned with the IA: Vraks second Edition release. Whilst the two catalogues (and the vraks SE book) DO use the IA: 13 renegades and Heretics list as the foundation, there is in fact a difference in rules, traits and upgrades that make the Vraks catalogue different from the Renegades catalogue. 

In addition off of memory the Vraks catalogue as it is now, uses the Second Edition version so all issues pertain to that book <i>(Edit: There are some issue at glance in the catalogue, such as some Tzeentch and Slaanesh items being present, but Renegades of Vraks is definitely correct layout wise)</i>. This means that there should be no reason to depreciate the catalogue.

In saying that, at present I do not have access to Vraks to fix the issues up (as opposed to IA: 13). I will probably not have access for a few more weeks in addition. If someone else can take a shot it would be appreciative.

**Comment by afraeve** [comment]
Yes, I had meant to say "this has been sorted in the Renegades of Vraks - FW - The Lost and the Damned.cat"; I fixed the spawn 3 days ago (the unit was marked as hidden). That file is complete, so it made sense to me to delete the unfinished one...

**Comment by pretzalcohuatl** [comment]
Close?
