### ISSUE TITLE
[Khorne Daemonkin] Upgrading Bloodletter to Bloodreaper With 8 Member Unit Broken in commit f73749d

### ISSUE THREAD

**Issue by mschreiner86** [BSData/wh40k-7th-edition#1158]
This commit, https://github.com/BSData/wh40k/commit/f73749df80ebf345d40286e11c445131bf2fd00d, broke the ability to have 7 Bloodletters and Bloodreaper (total unit size of 8 members).

The Bloodletter unit previously worked by considering a Bloodreaper as a separate member. Now, if you want a Bloodreaper you are forced to have a minimum unit size of 9. This goes against the KD codex which says "May upgrade one Bloodletter to a Bloodreaper"

**Comment by NebSeele** [comment]
I've released an update that should contain a fix for this issue.
