### ISSUE TITLE
C-SM: Forgeworld Chapter Tactics

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#1159]
Codex: Space Marine lacks Chapter Tactics from Forge World publications.

OP:

> **File:** Space Marines - Codex (2015).catz
> 
> **BattleScribe version:** 1.15.07
> 
> **Platform:** Android
> 
> **Dropbox:** No
> 
> **Description:** With Korvydae selected as HQ, assault Squads aren't allowed as troops choices.

**Comment by pretzalcohuatl** [comment]
Also need to have 1+ scout squad as mandatory troop choice

FW, though, so low priority

**Comment by hisop** [comment]
There are definitely FW chapter tactics so closing.
