### ISSUE TITLE
[Anon] Bug report: Renegades__Heretics_Renegades_of_Vraks.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#1168]
**File:** Renegades__Heretics_Renegades_of_Vraks.catz

**BattleScribe version:** 1.15.07

**Platform:** Mac

**Dropbox:** Yes

**Description:** Chaos Spawn are missing from Elites when you selec The Purge formation

**Comment by amis92** [comment]
~~@whiskeyjuvenile why closed?~~ Oh I see, duplicate of #1169, OP's mistake.
