### ISSUE TITLE
Orks 7th - special Ork detachments (force type) missing

### ISSUE THREAD

**Issue by amis92** [BSData/wh40k-7th-edition#118]
It needs to be added to gst

**Comment by ghost** [comment]
I've done this just now. Could you check it over, please; the gst editor is a bit finicky.

Have also updated the Ork cat so the correct gifts/gubbinz & rules show up automatically depending on the detachment type selected. Left in the option to choose either for Apoc.

**Comment by amis92** [comment]
@khambatta , What for is Space Wolves detachment if it is exactly the same as Combined arms? Or did you forget to change HQ limits? ;) Anyhoo I think it's good to go, I don't have time for it now, but you can do the release. Things work ok.

**Comment by ghost** [comment]
Oops. I had to redo the Space Wolves twice because the chart kept appearing upside down in the roster editor. Fixed now, will get the release done.
