### ISSUE TITLE
Space Marines: Can have The Armour Indominatus more than once in single force (also more than once in roster)

### ISSUE THREAD

**Issue by pretzalcohuatl** [BSData/wh40k-7th-edition#1182]
can take a captain with one and a chaplain with one

refactoring to fix

**Comment by senpai514** [comment]
Hmm that should have been throwing a flag but I realize what I missed with
that now. Should have caught that when I was creating initially

**Comment by pretzalcohuatl** [comment]
it won't without making it into a shared entry, which will be a mess given the way you have it structured

**Comment by senpai514** [comment]
yeah I realized that when I took another look. Though I have come up with a solution that should fix without any major rework

**Comment by senpai514** [comment]
Can be a simple fix with a couple modifiers

**Comment by pretzalcohuatl** [comment]
Check out https://github.com/BSData/wh40k/commit/6e3bb2b820618853477aba658168081dcbd01987 which is how they do it over in the HH catalogue

**Comment by pretzalcohuatl** [comment]
Check out #1190, let me know what you think
