### ISSUE TITLE
Remove vXX tags from catalogue title

### ISSUE THREAD

**Issue by amis92** [BSData/wh40k-7th-edition#119]
Because v1.14.03 of BattleScribe shows these automatically. Finally! ;D

Done:
- [x] Adepta Sororitas
- [x] AM Codex
- [x] AM Armoured Battle Group
- [x] AM DKoK Assault Brigade
- [x] AM DKoK Siege Regiment
- [x] AM Elysian
- [x] Blood Angels
- [x] Chaos Daemons
- [x] CSM Codex
- [x] CSM Black Legion
- [x] CSM Crimson Slaughter
- [x] Dark Angels
- [x] Dark Eldar
- [x] Eldar Codex
- [x] Eldar Corsairs
- [x] Eldar Iyanden
- [x] Fortifications & Stronghold Assault
- [x] Grey Knights
- [x] IG Apoc (actually maybe remove all IG files?)
- [x] IG Codex
- [x] IG DKoK
- [x] Imperial Knights
- [x] Inquisition
- [x] Legion of the Damned
- [x] Militarum Tempestus
- [x] Necrons
- [x] Necron Dark Harvest
- [x] Orks
- [x] Orks Dread Mob
- [x] R&H Defenders of Vraks
- [x] R&H Servants of Decay
- [x] R&H Servants of Slaughter
- [x] SM Codex
- [x] SM Siege Assault Vanguard
- [x] SM Clan Raukaan
- [x] SM Sentinels of Terra
- [x] Space Wolves
- [x] Tau Codex
- [x] Tau Farsight
- [x] Tyranids
- [x] Tyrant's Legion Defenders of Badab

**Comment by Kangodo** [comment]
I removed them from BA, Necron and SM-Codex during my latest update ;P
How do you want us to keep track? Or just fix it if we encounter it..

**Comment by amis92** [comment]
Just fix if we encounter and mention this issue, or post in here when updated something, like you've just done :)

**Comment by amis92** [comment]
Removed from Daemons and CSM.

**Comment by Kangodo** [comment]
They should be gone at Crons :/

**Comment by amis92** [comment]
Oh, right. It's Dark Harvest with it.

**Comment by ghost** [comment]
I have a DKoK Assault Brigade file, updated to the new AM codex, with the version number taken out. But I'm loathe to upload anything else with all the issues around corrupt files just now.

**Comment by amis92** [comment]
Well let's face it: the files aren't corrupted really. BattleScribe just failed on iOS. We don't really have any hint about how we can help it, so let's just do our regular business. Get it up, @khambatta , no reason to hold it from all the Android/PC users :D

**Comment by ghost** [comment]
Done.
