### ISSUE TITLE
C-SM Carcharodons Chapter Tactic support & options

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#1194]
**File:** Space Marines - Codex (2015).catz

**BattleScribe version:** 1.15.07

**Platform:** Android

**Dropbox:** No

**Description:** The option to take a squad of lightning claw terminators has been missed from space shark lists in 2015 codex

**Comment by senpai514** [comment]
see #1159 for consolidation of this general enhancement
