### ISSUE TITLE
+ Cohort Mechanicus Formation +

### ISSUE THREAD

**Issue by Flashpoint-** [BSData/wh40k-7th-edition#1198]
Cohort Mechanicus Formation
any work being done on this formation?
thank you.

**Comment by Throtard** [comment]
I don't have access to the datasheet yet, sorry. I'll include that formation as soon as possible.

**Comment by Flashpoint-** [comment]
Web Exclusive Bundle Rules
+++ COHORT MECHANICUS +++ 

FORMATION: 

1 Tech-Priests Dominus 
1 unit of Fulgurite Electro-Priests 
1 unit of Corpuscarii Electro-Priests 
1 unit of Kataphron Breachers 
1 unit of Kataphron Destroyers 
2 units of Kastelan Robots & Datasmiths 
1 unit of Skitarii Vanguard 
1 unit of Skitarii Rangers 
1 unit of Sicarian Ruststalkers 
1 unit of Sicarian Infiltrators 
2 Onager Dunecrawlers 
1 unit of Sydonian Dragoons or Ironstrider Ballistarii 

RESTRICTIONS: 

A Cohort Mechanicus must include either 3 Sydonian Dragoons or 3 Ironstrider Ballistarii 

SPECIAL RULES: 

Alpha-Primus: If this Formation's Tech-Priest Dominus is your Warlord, you can generate his Warlord Trait from the Warlord Trait table in either Codex: Skitarii or Codex: Cult Mechanicus. 

The Primus Canticle: All units in a Cohort Mechanicus have the Canticle of the Omnissiah special rule (see Codex: Cult Mechancus), even though they do not have the Cult Mechanicus Faction. In addition, if your army contains a Cohort Mechanicus, you can use the following Canticle of the Omnissiah in addition to those listed in Codex: Cult Mechanicus. This Canticle can never be used more than once in the same battle. 

BLESSING OF BINHARIC DELIVERANCE 
The unalloyed version of this famous blessing carries great power. It siphons a fraction of the Motive Force from those faithful nearby and releases it in the form of crackling electrogheists that intercept incoming shots, delivering the Omnissiah's chosen from harm. 

Units / Effect 
1-3 = All friendly models with the Canticles of the Omnissiah special rule have a 6+ Invulnerable save 
4-7 = All friendly models with the Canticles of the Omnissiah special rule have a 5+ Invulnerable save 
8 + = All friendly models with the Canticles of the Omnissiah special rule have a 4+ Invulnerable save 

The Primus Imperative: All units in a Cohort Mechanicus have the Doctrina Imperatives special rule (see Codex: Skitarii), even though they do not have the Skitarii Faction. 
In addition, if your army contains a Cohort Mechanicus, you can use the following Doctrina Imperative in addition to those listed in Codex: Skitarii. This Imperative can never be used more than once on the same battle. 

EXECUTIONER EXTREMIS (PRIMUS) 
The proscribed imperative known as Executioner Exremis drives the faithful to the absolute peak of their potential. Rumours exist that it causes subtle but irreparable damage to brain stems and circuit nests in the process, but discerning Tech-Priests judge the sacrifice worthwhile. 

Until the start of your next turn, all friendly models with the Doctrina Imperatives special rule add 3 to both their Ballistic Skill and Weapon Skill characteristics. 

+++ END OF DATASHEET +++

**Comment by Throtard** [comment]
Ok, thanks! My Google-fu had seen better times ;). I'm on it.
