### ISSUE TITLE
Codex Blood Angels - Outdated

### ISSUE THREAD

**Issue by Kangodo** [BSData/wh40k-7th-edition#120]
The Codex Blood Angels misses quite a few things.
It lacks all rules, not every character has his equipment/abilities and they have no profiles.

Librarians are have Epistolary with wrong points and every Psyker still requires codex-powers.

I am willing to fix this, but I would need to become a member.
Since I've already done all this work, I could copy-paste most of my work.

**Comment by amis92** [comment]
Added. Please don't hestitate to share your file :D
