### ISSUE TITLE
Bug Report: Khorne Daemonkin - Warlord

### ISSUE THREAD

**Issue by cartag** [BSData/wh40k-7th-edition#1204]
Warlord selection only matters for one detachment. Will still say missing Warlord if you have two CAD with Warlord in one detachment but not the other.

**Comment by cartag** [comment]
Also, selection for Warlord is a numeric counter that can be set higher than 1, rather than a checkbox.

**Comment by NebSeele** [comment]
I don't see how it would be a numeric counter as the BRB is pretty clear you MUST have 1 warlord per army/roster. As for the other issue, I will adjust as neccessary.

**Comment by amis92** [comment]
@NebSeele I think he meant that it _currently_ is _not_ a checkbox, and should be.

**Comment by NebSeele** [comment]
ahh. I'll have that fixed and posted asap.
