### ISSUE TITLE
Eldar Craftworlds - Seer Council options

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#1206]
**File:** Eldar Craftworlds - Codex (2015).catz

**BattleScribe version:** 1.15.06

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Elder craftworld does not have the programming to support a seer council (far seer or warlocks on jet bikes.  It's not even a selectable option.)

**Comment by Itsacon** [comment]
Seer council is a formation, not a unit. If you select Formation detachment for Craftworld Eldar, it shows up normally, and it has options to select between Seer Council or Skyrunner Seer Council.
