### ISSUE TITLE
Storm Eagle ROC pattern availability

### ISSUE THREAD

**Issue by ddarz** [BSData/wh40k-7th-edition#1217]
Hi,

The previous codex files allowed any chapter to have take the ROC patttern Storm Eagle, the new version locks it to the Minotaurs.

There has been some discussion about the ROC pattern being available to other chapters apart from Minotaurs. The consensus appears to be that all chapters from codex space marines can take it, unless it is a Siege assault list, in which case it is only available to Minotaurs.

This conclusion comes from the second edition of Imperial Armour 2 which states: 
'A storm Eagle Pattern Assault Gunship is a heavy support choice for a Codex Space Marines Army, and a Space Marine Siege Assault Vanguard army as described in Imperial Armour Ten: The Badab War =Part two, representing the Minotaurs Chapter'

The interpretation is that it is meant as a restriction for battles set during the Badab war.

This is further supported by the fluff description on page 135 that says: 'Used primarily by the Minotaurs and the Red Templars...' which breaks the exclusivity claim.

Thoughts? Personally I would like to see it re-added as an option for everyone again. It's by far the best pattern for a model that is not great value when compared to other flyers.

Cheers!

**Comment by senpai514** [comment]
The statement that declares who can take what is written as a continuous sentence tying both Codex Space Marines Army & Siege Assault Vanguard Army to the single restriction of representing the Minotaurs.  If it was going to have different restrictions it would be written up in different statements not in the same sentence as other units have been written with varying allowances.
