### ISSUE TITLE
iOS - Tau crash and autosave fail

### ISSUE THREAD

**Issue by yogpoz** [BSData/wh40k-7th-edition#1228]
I have the latest version of the app. App will crash at random without saving any changes made. No obvious cause

**Comment by senpai514** [comment]
@yogpoz what BS version do you have?

**Comment by amis92** [comment]
@yogpoz  can you confirm that it also happens with any other catalogues? And is that ~~newest~~_(ok I see it is newest indeed)_ BS on iOS?

**Comment by yogpoz** [comment]
It's BS 1.15.07 and it only seems to happen for the tau codex. mainly when adding new units

**Comment by amis92** [comment]
Damn. And how about SM's Gladius SF, as in #1229?

**Comment by amis92** [comment]
Oh, might it be because you try to use old roster then? Maybe with fresh roster it'll work.

**Comment by yogpoz** [comment]
Crashes seem to have mostly stopped now. However data is still not being saved. I've tested this with a fresh army list

**Comment by efalsken** [comment]
I've been testing. No problems on iPhone 6 and iPad Mini running the latest app. Please check the AppStore for updated version of Battlescribe. Possibly delete and re-download it. I've had some times in the past, using Dropbox on multiple devices can cause a conflict file, and then I have to use my PC to fix it and delete the conflicts.

**Comment by amis92** [comment]
Seems like it was fixed in some recent update.
