### ISSUE TITLE
iOS - Space Marine autosave fail

### ISSUE THREAD

**Issue by LurkinLarkin** [BSData/wh40k-7th-edition#1229]
BS doesn't save a list when using a GSF. I can build a force with no problems. I add a Battle Demi-Company, 1st Company & a librarians Conclave which I can add upgrades too but as soon as I close the roster everything reverts back the basic set up.

**Comment by senpai514** [comment]
@amis92 @Jonskichov  I tested Gladius Strike Force and CAD it creates the roster but doesn't save selected units.

**Comment by amis92** [comment]
@LurkinLarkin can you confirm that it also happens with any other catalogues?

**Comment by LurkinLarkin** [comment]
Tried a few other lists with different army's but no other problem. 
Just to confirm, the app doesn't crash.

**Comment by amis92** [comment]
And Tau as per #1228 ?

**Comment by LurkinLarkin** [comment]
No it doesn't crash

**Comment by airborn334** [comment]
Also having the issue....

**Comment by ghost** [comment]
You sure it's not saving or just saying that it has no points? My lists once saved say 0 for points but you click the list and load it and the points come back

**Comment by airborn334** [comment]
For instance, I make a 1,000 point list. (Even tried with tau, and space
marines) I finish and I'm at 997. When I back out of the list it shows like
856. Sometimes it doesn't save much at all only the HQ. If I leave
battlescribe running in the background I can still open the list and
everything is fine. If i close running apps, re-open battlescribe, it's all
gone (goes to the 856 and sometimes 90 and leaves just an HQ)

**Comment by lacyj3** [comment]
Ipad and Iphone....does it on both my devices.  

Space Marines

Same issue.....does not auto-save.

It doesn't crash, can build the force, will let you send the file but doesn't save.

**Comment by lacyj3** [comment]
I haven't tried other armies....just Space Marines.

Sometimes it will save part of the list.

As a work around....I email my list as HTML to myself.  I haven't tried emailing the Battlescribe file, but will here in a moment.

**Comment by lacyj3** [comment]
Side....note.  It may be related but its not Sync'ing with my dropbox either.

**Comment by lacyj3** [comment]
If you change the name of the force it will save...it seems.    

Create a force with a name.   Add stuff.  Then change the original name you used.  That seems to make it save.  Tried like 3 times and its seems to work as a work around.

**Comment by lacyj3** [comment]
If you email yourself the Battlescribe file.  It will load and lets you go in and out of that list.

**Comment by LurkinLarkin** [comment]
Still having the same problem as you Lacyj3, tried the name change around but doesn't work. Will try emailing it.

**Comment by efalsken** [comment]
If you have Battlescribe synced with Dropbox, log into dropbox and check for .confict files in the battlescribe data folder. delete them. Also make sure that you see only 1 .cat OR .catz file for each army. If there are extra files, then you'll see it crashing. This can happen easily if you open Battlescribe on 2 different devices at the same time.

Same thing with your roster files.

**Comment by lacyj3** [comment]
I went into Battlescribe and found many conflicts under Data.   I deleted everything in there then downloaded it all over again.

**Comment by amis92** [comment]
Seems like it was fixed in some recent update.
