### ISSUE TITLE
SM v7-veteran sergeants?

### ISSUE THREAD

**Issue by cryric** [BSData/wh40k-7th-edition#1230]
I am trying to add veteran sergeants to any of my lists and there are only options for the basic but not the veteran...on bikes, scouts, tactical, assault, etc.
Am I missing something?
Newest iOS version

**Comment by cryric** [comment]
Edit: BS: 1.15.07
SM (2015):v7

**Comment by senpai514** [comment]
You should be able to click on the sgt and choose which sgt you want to use.

**Comment by cryric** [comment]
I get the list of things a sgt can have but no option to make them a veteran.

**Comment by senpai514** [comment]
Are you on a desktop?

**Comment by cryric** [comment]
Sorry...didn't make it clear. Newest battle scribe app on iOS 8.4 (specifically iPhone 5)

**Comment by senpai514** [comment]
Ok that helps different platforms interact differently.

On iOS if you select the name of the model you can change the options. If
you select the dot on the end that should give you the option to select
other choices from the entry group.

**Comment by cryric** [comment]
Ok...the selection between the old  SM codex and the new one is a bit different. 
You are right that the "dot" allows the change...in the old codex it is a selection "off the name" of the model (not dot). That's why I couldn't do it..
thanks!!!
