### ISSUE TITLE
Codex DA 2015 - Librarian and Relic weapons bug

### ISSUE THREAD

**Issue by Itsacon** [BSData/wh40k-7th-edition#1232]
Relic weapons replace one weapon, but the Librarian in Terminator armour comes without a Storm bolter as standard (so just the Force Weapon). Rules wise, you'd have to buy a Storm bolter first if you wanted to take, for example, the Foe-Smiter and keep your Force weapon. But doing so gives an error right now, as Battlescribe sees it as the model having three weapons.

This is related to closed bug #1205, I think, which isn't properly fixed, as the Librarian still requires two weapons, despite the codex allowing just one.

Easiest way to fix it would be adding an option to the Left hand weapons called `Relic Weapon' that costs 5 points, doesn't increment the weapon count, but requires a selection from the Chapter Relics list. This allows both the option of swapping the Force weapon for a relic weapon, or adding a Relic weapon to the free hand.

**Comment by Thairne** [comment]
Thanks for the precise description! I'll see how I can fix that issue.

**Comment by Thairne** [comment]
Found another solution I like more.
I've build in a logic that increases the cost of the relics (besides Shroud and Eye) by 5 points if you do have a right hand weapon (Force) and no left hand weapon (ranged) equipped. Once you deselect your Force Weapon, price goes down again as you trade this one in for the Relic.
That way you either trade your Force Weapon or you automatically pay for the Storm Bolter you replace.
Let me know what you think of this way of handling the issue.

**Comment by Itsacon** [comment]
Seems perfect! Didn't know it was possible to change the prices on the fly like that, but that's even better than my idea.
