### ISSUE TITLE
Inquisitorial Valkyrie (FW) Wargear

### ISSUE THREAD

**Issue by Xianator** [BSData/wh40k-7th-edition#1234]
In the Inquisition roster, the Valkyrie (FW) does not have Searchlight and Extra Armour listed as standard equipment.

The Valkyrie (FW) weapon point value for the Multiple Rocket Pods is incorrect.  It should be 30 points, instead of the current 10 points.

The Valkyrie (FW) weapon point value for the Lascannon is incorrect.  It should be 15 points, instead of the current 10 points.

Source:  Imperial Armour 2 Second Edition, page 230.

**Comment by Xianator** [comment]
In the Inquisition roster, the Valkyrie (FW) does not have Searchlight and Extra Armour listed as standard equipment.

**Comment by senpai514** [comment]
It does have the profiles for the searchlight and extra armour on its entry. As with most catalogues wargear profiles are visible on the model entry when viewing your roster.

Sent from Windows Mail
