### ISSUE TITLE
No Lysander in strike force ultra

### ISSUE THREAD

**Issue by Lynkon** [BSData/wh40k-7th-edition#1249]
Captain Lysander is not selectable in either the SM or Sentinels of Terra version of Strike Force Ultra.

**Comment by senpai514** [comment]
Make sure you have imperial fists chapter tactics selected for codex space
marines. He should show up as a choice then.

**Comment by Lynkon** [comment]
Thanks. That does resolve it under SM, but he still doesn't show up under Sentinels of Terra

**Comment by afraeve** [comment]
Fixed this for Sentinels of Terra just now.
