### ISSUE TITLE
iOS - Dark Angels autosave fail

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#1254]
**File:** Dark Angels - Codex (2015).catz

**BattleScribe version:** 1.15.07

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** I build my list as per usual, however as soon as I leave it it all gets lost. Nothing seems to save bar the basic Demi company. All upgrades, auxiliary and any other force I add are lost.
Thank you for doing what you do!

**Comment by Thairne** [comment]
Hm. Seems to be iOS specific and therefore most likely a BS Bug. Maybe caused by the fix to the crashing issue on iOS?

**Comment by amis92** [comment]
Similar to #1228 and #1229. :<

**Comment by amis92** [comment]
Seems like it was fixed in some recent update.
