### ISSUE TITLE
Space Marine 7 ed - bugs

### ISSUE THREAD

**Issue by MasterCrafty** [BSData/wh40k-7th-edition#1267]
Hi guys great work on this. Many thanks. A couple of things I have noticed if you want to add them to the list - no biggies...

1 - Honour Guard champion won't let you keep bolt pistol, bolter and PW/Hammer. Unless you check 'CC Weapon' it errors telling you that you need to choose a new weapon.

2 - If i take bike squads as FA it tells me that i am not allowed to. I suspect that is because there is a HQ on a bike and they CAN be taken as troops...

3 - I made a list with FW Chapter Tactics. I notice that FW characters dont filter as well once you choose a ChapTac. Fire Hawks only have 1 character but i had 3+ options for named characters.

4 - Also a coupls of options specific to Fire Hawks. They can take jump packs for a Command Squad (35 pts) and they get the option of hand flamers in ranged weapons for 5pts.... 

Will post more if i find them. Thanks lads....

**Comment by MasterCrafty** [comment]
Also.... relic blade is still a 0pt option for a Vanguard Sargeant.....

**Comment by senpai514** [comment]
1 - Should be fixed now

2 - If an independent character is mounted is mounted on a bike the battlefield role is changed from Fast Attack to Troops, they will only be one or the other never both at the same time.

3 - You should only see 2 HQ's one is a Fire Hawk the other has no associated chapter tactic so he is able to be taken in all chapter tactics.

4 - There are many different options that are available for most all FW chapter tactics. At present nothing has been done to implement those advanced choices just yet. We know that FW is working on some updates for their rules that relate to Codex Space Marines and applicable units Im waiting to see what is released in their rules updates before delving in too far to that project.

5 - relic blade fixed as well

changes will be in next release
