### ISSUE TITLE
Dark Angels - Rules wording/clarification

### ISSUE THREAD

**Issue by lacyj3** [BSData/wh40k-7th-edition#1287]
From Battlescribe.....Ravenshield: Units within 24" of the charged unit may also fire overwatch. To fire a template weapon, they must be within 6" of the charged friendly unit.

Need to clarify that it only applies to Ravenwing units.  If taking allies it can be misinterpreted.   

Actual rule.....Ravenshied: When an enemy unit declares a charge against a
friendly unit with the Ravenwing special rule..........................

**Comment by Thairne** [comment]
BS is not supposed to replace your codex, but give you a tool to go "ah, that rule was it that did THAT!".
If unsure, always crosscheck with the Codex. Nevertheless, I'll clarify that rule a bit more. Was written with blurry leaks and no actual dex in hands ;)
