### ISSUE TITLE
Codex: Craftworld Eldar - Crimson Hunter Exarch Validation

### ISSUE THREAD

**Issue by BlakLanner** [BSData/wh40k-7th-edition#1288]
When selecting the **starcannon option** on a **Crimson Hunter Exarch**, the following validation error occurs:
**Crimson Hunter has 1 too many selections of Two Starcannons (maximum 0)** increment maxSelections by 1 if Crimson Hunter has equal 1 selections of NO CHILD.

![chevaliderr](https://cloud.githubusercontent.com/assets/12300956/8817927/237abbfa-3008-11e5-94c0-f462d6c2241f.png)

BattleScribe Pro 1.15.07, PC and Android
Codex File Version - v20
Dropbox - Yes

**Comment by ConanBigMan** [comment]
also there is no such thing as fighter ace for the crimson hunter, can you add this BlakLanner to this ticket , since it shows it on your screen shot

**Comment by BlakLanner** [comment]
The rules for Fighter Aces can be found in the Shield of Baal: Leviathan suppliment.

**Comment by ConanBigMan** [comment]
Hmm then maybe they should be a separate entry for if you add the codex of the supplement, I've never seen this supplement even - it doesn't belong in a normal game right?

**Comment by BlakLanner** [comment]
The supplement states that they can be used in normal games of 40k and has charts for all the factions that were available at the time of printing.

**Comment by BlakLanner** [comment]
The "Two Starcannon" option works correctly in the Crimson Death formation.

**Comment by afraeve** [comment]
The modifier permitting the Starcannons & the modifier incrementing the profile BS both point to invalid entry id _921e-afaa-8d83-b6c5_, instead of the Exarch id _b134-fbc0-d687-1220_.

I changed that & nothing else, but GitHub shows a huge swathe of red & green, so I've reverted my commit. I don't know what's going on there as my local copy of the file was in synch beforehand.

**Comment by amis92** [comment]
@afraeve It's possible that BattleScribe wants to update cataloue format etc. To check that, first open catalogue and save it immediately, without any changes. Then check if there are any changes in GitHub shown, if so - commit them as 'file format update' or similar, and proceed to fixing a bug.
