### ISSUE TITLE
Possible Bug:   Codex Harlequin CAD Validation

### ISSUE THREAD

**Issue by lacyj3** [BSData/wh40k-7th-edition#1294]
How to you add a Combined Arms Detachment Harlequins and make Battlescribe validate correctly the HQ option?  It keeps saying I need an HQ, but Troupe Masters act as HQ's.

My main force is Craftworld Eldar with Harlequins, but I can't seem to make the Harlie CAD validate?  

Am I missing a selection option?

**Comment by senpai514** [comment]
You can't take Harlequin’s in a CAD.

Sent from Windows Mail
