### ISSUE TITLE
Eldar Craftworlds - Codex (2015).catz - Shining spears

### ISSUE THREAD

**Issue by ConanBigMan** [BSData/wh40k-7th-edition#1296]
File: Eldar Craftworlds - Codex (2015).catz

BattleScribe version: 1.15.07

Platform: Android

Dropbox: No

Description: Shining spears may only have 8 shining spears in the squad if they upgrade one to an exarch. (i.e. 8 +1) The exarch appears as an additional squad member rather than the replacement he is supposed to be (i.e right now it is 9 + 1)

**Comment by BlakLanner** [comment]
Check your validation results.  It will show "Shining Spears has 1 too many selections from Shining Spears (maximum 9).  This how all Aspect Warrior squads behave.

**Comment by ConanBigMan** [comment]
BlakLanner - are you trying to be weird? you are making me rather annoyed - this is simply incorrect and I wish you would check this stuff, in battle scribe you are adding TEN shining spears but you are allowed 9 in a squad NOT TEN the base cost of 9 shining spears in a squad with an exarch is only 235 .. just a take a look and reopen please?

**Comment by BlakLanner** [comment]
I am not trying to be weird at all.  You are correct that you are not allowed ten Shining Spears in a squad.  While the software will allow you to add it, it also throws an error telling you that the combination is not legal.  If you click on the red exclamation point in the upper right (assuming you are using the Android version), it will list everything that is illegal about your list.  This is how every single Aspect squad works with this program.

Would it be nice if adding an Exarch to a full squad automatically removes a normal member like ArmyBuilder does?  Yes.  However, I am just a tester and not a dev so I don’t know if the software is able to do that.  Battlescribe does not prevent us from making mistakes or let us turn off our brains.  It will allow us to do things that are not strictly allowd in game, but it will at least put up an error telling us there is a problem.
