### ISSUE TITLE
Eldar Craftworlds - Codex (2015).catz - Wraithguard warlocks

### ISSUE THREAD

**Issue by ConanBigMan** [BSData/wh40k-7th-edition#1297]
File: Eldar Craftworlds - Codex (2015).catz

BattleScribe version: 1.15.07

Platform: Android

Dropbox: No

Description: warlocks are not possible to add to a wraithguard squad

**Comment by BlakLanner** [comment]
Not a bug.  There is no option to add a Warlock to a Wraithguard squad in the 7E codex and you cannot detach Warlocks from the Conclave.
