### ISSUE TITLE
Enhancement: Khorne Daemonkin - FW

### ISSUE THREAD

**Issue by cartag** [BSData/wh40k-7th-edition#1302]
There's a screengrab floating around of an email from FW stating anything from IA13 (But not IA5v2) that has MoK or DoK can be brought and has BftBG on it. Should we consider adding a FW check box like in the CSM catalogue? 

I know it's nothing official yet, but it's along the lines of what we already figured for the other formations. I can get started on putting it all in if need be.

**Comment by NebSeele** [comment]
My own email to Forgeworld on the matter is that is's largely dependent on house ruling and permission from the tournament organiser (or unbound), and that it's recommended to treat it as a chaos daemons army for intents and purposes. 

Honestly, the lack of officiality is what has stopped me adding the Forgeworld units into the catalogue as soon as the main codex entries were written, because somebody's local meta (or the tournament meta in general) is likely to strike it out on Rules as Written.

**Comment by cartag** [comment]
This was a more recent email than when we discussed this a few months back. This was a matter of days ago. That was really the only reason I was revisiting it. 

Perhaps a disclaimer would be important to add in? Less like the Show FW options, but more like Force Options (Supplement options here) from the CSM dex. Could be "Force Options (Non RAW options here)" with a check for FW. I'm just spitballing ideas here. 

Wait, why don't I just fork it and make my own for personal use. Problem solved :)

**Comment by NebSeele** [comment]
For now that might be the best idea. I will email Forgeworld again and see if the response is largely the same or if the response is different. I will likely need the response for my own local meta anyways. If the response is that MoK and DoK from IA:13 can be taken (with BftBG as the option), as well as the Infernal relics, then maybe I'll add it in.

**Comment by cartag** [comment]
I'm working on it now, and see a bit of cleanup work I can do to it. Figured if you can pawn off several small fixes that nobody but somebody looking at the back end of it could see to somebody who volunteered it would be an easy decision. 

I'll get mine finished and try to list which changes were made.

**Comment by amis92** [comment]
Maybe just make a pull request from your fork :)

**Comment by cartag** [comment]
https://github.com/cartag/apocformations/

As for the delay in this, life happened. /shrug

**Comment by cartag** [comment]
I also set the formations to have a default number of selections. Like the Gorepack adds two bikers and one khorne dog unit when selected. This happens with all mandatory units. War Engine and Lords of Slaughter formations are not affected. 

Also corrected formation from "Fists of Khorne" to "Fist of Khorne"

**Comment by amis92** [comment]
Okay, so please do the following: fork this repository, copy that updated file into your fork, sync and make a pull request. GitHub Desktop (the app) is your friend for that. :)

**Comment by cartag** [comment]
Thanks armis. This is the first collab I've done on Git. I believe now I just need to be a contributor so I can do that, is that correct? :)

**Comment by amis92** [comment]
Forking is faster on your part as no membership is required. That is the 'outside' collaboration. When you become a member, no forking is required as it's 'inner' collaboration, but it can take some time.

**Comment by cartag** [comment]
I'll just go back to square one and reevaluate what I'm doing. Something isn't working right on my end. I'll get it figured out rather than request to be walked through it.

**Comment by cartag** [comment]
I think I have it figured out now, there is a pull request waiting for somebody with write access

**Comment by NebSeele** [comment]
I cannot get the pull request to work, something about it not auto merging. Managed to get the catalogue to download so I'll override my copy of the file and sync it via the master. I need to bugfix a new issue anyways.

Edit 2: Done. It's up

**Comment by amis92** [comment]
So... closing?

also @cartag if you want to become a member, please start right there: [Getting started](https://github.com/BSData/bsdata/wiki#getting-started)
