### ISSUE TITLE
Bug - Skitarii Phosphoenix Relic

### ISSUE THREAD

**Issue by Xianator** [BSData/wh40k-7th-edition#1303]
Selecting this relic by rule replaces the model's ranged weapon.
This is not happening in the roster editor.

No warnings of having the Phosphoenix plus the standard ranged weapon appear.

In the case of a Vanguard Alpha, manually deleting the default Radium Carbine causes a validation error when also having selected the Phosphoenix..

**Comment by Throtard** [comment]
It will be fixed in next release.
