### ISSUE TITLE
Codex Space Maines - Missing Bike Squad

### ISSUE THREAD

**Issue by jurisian** [BSData/wh40k-7th-edition#1315]
There is no plain Bike Squad neither in Fast Attack nor in Troops choice.

**Comment by Itsacon** [comment]
Yes there is:

![bikesquad](https://cloud.githubusercontent.com/assets/6087018/8953405/7949d31e-35de-11e5-838c-8aa9badd4634.png)

**Comment by jurisian** [comment]
I appologize, I wasn't clear enough. In mobile version there's no choices at all. I'm using it on iPhone. At the moment Battlescribe is installing on Android. Later, I'll be able to tell if the problem is on android as well.

**Comment by jurisian** [comment]
Update:
When you select HQ choice with bike, bike squad dissapears from Fast Attack but it doesn't show up in Troops selection. 

Same thing is on Android version.

**Comment by Itsacon** [comment]
I think I've found the issue. Now to see if I can fix it.

**Comment by Itsacon** [comment]
I have pushed an update that _should_ fix the hiding/showing of bike squads based on bike mounted HQ units. Behaviour on PC is now as expected, but I can't test Android/Apple myself, so let me know if it works.

**Comment by GeneralKroll** [comment]
I've done a refresh of my data (using it on iOS) but I'm afraid it's still not working. If it's any help, it's still showing as version 11 of the codex on mine. So perhaps it's not updating for some reason. 

Also bikes should still be available as fast attack, even with an HQ selected in a bike. It's just that they CAN be taken as troops if so desired.

**Comment by Itsacon** [comment]
I'm not quite sure how the update process works, but I believe the versions supplied to the update process lag a bit behind the Git repository, so might be you're still using an old version. I've updated the revision number, maybe it works now.

Also, the text for Mounted Assault says: 

> If a unit with this special rule is chosen as part of a Detachment that contains at least one independent character with the Space Marines Faction equipped with a Space Marine bike, the unit's Battlefield Role changes to Troops.

So no, they can no longer be taken as FA, they automatically become Troops.

**Comment by GeneralKroll** [comment]
So it does haha, fair enough, I never interpreted that way before, but I guess this cuts down on bike spam. Thanks for your help, I will have a try at updating again later on.

**Comment by senpai514** [comment]
Keep in mind if a release has been done yet general users wont have the changes right away unless they download directly from github

**Comment by senpai514** [comment]
which also means that the last update I did for the bikes hadn't gone out to the public at time of report.

**Comment by Itsacon** [comment]
Completely off-topic, but what exactly triggers a public release?

**Comment by amis92** [comment]
Someone. Someone has to click it on GitHub page of repo, in top repo panel 'releases' and then 'new release'.

**Comment by Itsacon** [comment]
Bump: Can someone check of with the latest release, this still triggers on Android and/or Iphone?

**Comment by jurisian** [comment]
Strange, I remember I was typing my answer before but don't know where it is gone. Nevermind. 

As it seems, everything is fine on iPhone and Android now. There's updated version of data file in online repository which solves this issue. 

Once again, thank you for your hard work!

**Comment by Itsacon** [comment]
Glad to hear it.

**Comment by GeneralKroll** [comment]
I'm afraid this exact same problem has cropped up again. Bikes have vanished.

**Comment by senpai514** [comment]
Yeah I think I know what happened. I will be going through the file today
replacing changes I know have disappeared an should have a good release
tonight.

**Comment by amis92** [comment]
As such, reopening

**Comment by senpai514** [comment]
8abfe1f349dd8cd4acefe401447e268a8e844461
