### ISSUE TITLE
Eldar Crimson Death Validation

### ISSUE THREAD

**Issue by BlakLanner** [BSData/wh40k-7th-edition#1319]
The Crimson Death formation requires an Exarch.  Selecting the formation neither adds one nor produces an error stating that one is needed.

**Comment by amis92** [comment]
@efalsken not sure if this will be deprecated after your redo of codex, but thought you may want to have a look. If not, please close this issue.

**Comment by efalsken** [comment]
yes. Will be covered by the work on #1727
