### ISSUE TITLE
Missing Entries: Chaos Space Marines: Codex (2012)

### ISSUE THREAD

**Issue by ghost** [BSData/wh40k-7th-edition#1321]
Following units are not appearing as available entries for me:
-Chaos Space Marines
-Rhino (also not appearing as a dedicated transport upgrade for cultists)
-Predator
-Khorne Berzerkers

Plague Marines and Noise Marines not moving to troops section when Chaos Lord with appropriate mark is selected. 

Using v152 in a fresh install of Battlescribe.

**Comment by pruneface** [comment]
Yes i am also having issues with the newest version missing several units as when i try and open my main army roster it says 2758pts are removed as there are no longer part of the datafile?
Not sure what units are unavailable as i dont want to ruin my list by opening it but im sure theres some hq issues and the csm troops are not present either
As for the cultists 666luke they cant take a rhino as a dedicated transport

**Comment by NebSeele** [comment]
Yeah... the cultists have never taken a Rhino as a dedicated transport. Rhino in CSM also cannot be selected as anything BUT a dedicated transport.

As for the others... I'll fix the ones listed (and the Lord bug) now. There's probably more bugs but these ones are simple enough to fix for now.

**Comment by ghost** [comment]
Huh well there you go. Dunno why I thought they could. Thanks guys!
