### ISSUE TITLE
Can't select Chaos Space Marines as troops.

### ISSUE THREAD

**Issue by mattFllr** [BSData/wh40k-7th-edition#1326]
Hi,

Admittedly this may be user error but I can't see any way around it.

I'm unable to select basic marines as troops. When adding troops only cultists appear. I've enabled all the hidden options which shows the cult marine etc but still no basic ones.

Have I missed something?

Thanks.

**Comment by NebSeele** [comment]
Hey. I have made a commit a few days ago that should resolve the bug (as well as a few others). The fix (version 153, possibly a later 154) will be up for general release soon once the next batch release is posted. (leaving issue open until release is committed).

**Comment by senpai514** [comment]
@NebSeele release done

**Comment by mattFllr** [comment]
Thanks folks.
