### ISSUE TITLE
Skitarri Ranger/Vanguard Alpha

### ISSUE THREAD

**Issue by T-Dawg135** [BSData/wh40k-7th-edition#1329]
The Ranged Weapon section for both Alpha's has a Set Max Selections to 0 modifier without any conditions, yet has Radium Carbine set as the default selection. This creates an error as soon as the Rangers/Vanguards are added to the roster.

![image](https://cloud.githubusercontent.com/assets/10503793/9024069/5e8cb6ce-387f-11e5-8f9b-52ca7d1e8afe.png)

**Comment by Throtard** [comment]
Fixed, I forgot to put the conditions. ;)

**Comment by Flashpoint-** [comment]
This a Data Problem
BattleScribe v1.15.07
Skitarii: Codex (2015) v14 by Axis of Entropy
In the Skitarii Maniple formation, Rangers and Vanguard "still" have weapon section for both Alpha's has a Set Max Selections to 0 modifier without any conditions, yet has Radium Carbine set as the default selection. This creates an error as soon as the Rangers/Vanguards are added to the roster.

**Comment by Throtard** [comment]
Revised version is v15, it will be released in next update.
