### ISSUE TITLE
[Anon] SM - Clan Raukaan - Techmarine maxInRoster=0

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#133]
When you take Techmarines you get an error of: You can have at most 0x Techmarine in your Roster, increment max InRoster by 2 (repeating), increment maxInRoster by 3 (repeating).  This appears regardless of how many hqs you have.

You get a similar message when selecting Bikers as troops.  Happens even when you have a CM on a bike and/or Captain on a bike.

**Comment by amis92** [comment]
Yeah, both modifiers don't work. @Jonskichov I'm wondering, where would you like to collect bug reports? The forum? Mentions here? Or maybe open empty repo on GitHub just to provide issue tracker?  I read GitHub encourages such things. :) And we could easily link you to issues here.

**Comment by ghost** [comment]
I'm finding similar issues with other modifiers attached to shared entries, e.g. a Siege Vanguard army can select Sgt Chronus of Ultramarines without selecting the Ultramarines Chapter Tactic. These did function correctly when I built them.
Re-installing Battlescribe 1.14.02 gets the chapter tactic warning to work; I haven't got any older versions to check when the issue affecting the Techmarine came about.

**Comment by ghost** [comment]
Fixed with Battlescribe 1.14.05
