### ISSUE TITLE
[Anon] Bug report: Necrons - FW - Dark Harvest.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#1334]
**File:** Necrons - FW - Dark Harvest.catz

**BattleScribe version:** 1.15.07

**Platform:** Android

**Dropbox:** No

**Description:** Rules descriptions for necrons dark harvest missing.

**Comment by Kangodo** [comment]
Correct, Dark Harvest has a lot missing.
At the moment I am not interested in updating them because the entire thing is 'broken' after the latest Necron-Codex.

**Comment by hisop** [comment]
Closing this as due to the structure of the book it uses units from the necron codex mixed in this would push two sets of similar but different rules and is generally a mess so blank is the way forward until second edition rolls out.
