### ISSUE TITLE
Move Dark Angels 6th Edition Codex to old files

### ISSUE THREAD

**Issue by Thairne** [BSData/wh40k-7th-edition#1338]
I've got no clue (well, a small inkling actually) on how this works.
The old file is pretty much not needed any more in a public release, so we can move it over to the other deprecated files. If anyone that knows how to would mind...?

**Comment by Itsacon** [comment]
As you probably expected, it's quite easy: Check out both repositories, move the file from one to the other, then commit both.

**Comment by Thairne** [comment]
Yep, close ;)
Problem is I usually work with Tortoise SVN which handles some things quite different thatn Github. Fell into that trap multiple times already, so I'd rather hold back and ask and not screw things over.. again ;)
