### ISSUE TITLE
War Convocation Knights?

### ISSUE THREAD

**Issue by Xabre1342** [BSData/wh40k-7th-edition#1341]
Apologies if I didn't see this error somewhere already.  I haven't seen any FAQs to suggest it; the Imperial Knights section of the War Convocation no longer has access to the free upgrades.

**Comment by Throtard** [comment]
@senpai514, I took a quick look at your file and fixed the visibility of the knights. The "show" condition is your doing? It's brilliant! I'm modifying the war convocation and cohort mechanicus, they should look good now, thanks. 

@Xabre1342, It would be right again in next release.
