### ISSUE TITLE
[Anon] Bug report: Chaos Space Marines - 2 Heavy weapons in 20 man squad

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#1355]
**File:** Chaos Space Marines - Codex.catz

**BattleScribe version:** 1.15.07

**Platform:** Android

**Dropbox:** No

**Description:** The codex for chaos space marines allows for one heavy weapon every 10 models. There is a constant error for space marines no matter the number of models saying that heavy weapons are allowed only 0, it should be 1 for 10 units and 2 for twenty

**Comment by NebSeele** [comment]
I have provided a response for this issue in #1356 that may involve deliberation with others,

**Comment by cartag** [comment]
I would agree with NebSeele. The wording in the codex is not affected by any errata (I just checked) and it doesn't mention anything about getting an additional HW if 20+
