### ISSUE TITLE
[feature] Min/Max in unit

### ISSUE THREAD

**Issue by Nokhal** [BSData/wh40k-7th-edition#1365]
The adepta sororitas command squad is an absolute nightmare to design with the current format available to us.
Either we have to create a forest of hide conditions, or we can simply add a "max in unit" field along the Max in force and max in roster one.

**Comment by amis92** [comment]
Can you elaborate? Max in unit sound like max selections to me.

**Comment by Nokhal** [comment]
Max selection is max in current node, while max in unit would be "max in node just under the "battle formation" node.

**Comment by amis92** [comment]
Well, you can create a group to do that if I think I know what you want. Groups are useful little beasts. :)

**Comment by Nokhal** [comment]
Nope. See my sister of battle codex update. To be fair the sister of battle command squad is an incredible amount of clusterfuck conditions.

**Comment by amis92** [comment]
Really don't see a problem here. Just move all unit members into a group.

**Comment by Nokhal** [comment]
Tried, didn't succeed. The catch is that a sister carrying a banner lose her access to other gear options. And other member can't take a banner if an another sister of the squad is carrying one. Banners can be either blessed banner or Sacred banner of the order militant.

**Comment by amis92** [comment]
Have you looked at a Grey Knight Paladin squad? May help. I've spent a lot of time trying to make it usable. :D

**Comment by Nokhal** [comment]
Yes. The issue with sisters is that the squad size is fixed (5 models). Hence you shouldn't have to manually change the model number. Also, a sister can wear either a blessed banner or a sacred banner, but only one of those per squad. You would have to create selections not present in the codex (standard bearer). 
I "cheated" by creating a shared entries increasing it's maximum number in force per number of command squad in the force.

**Comment by cartag** [comment]
Why not set them up like the Bloodletter/Bloodreaper are in KDK book? We have a checkbox to "Upgrade one Bloodletter to Bloodreaper" for 5 pts.
