### ISSUE TITLE
Contemptor Pattern Dreadnought - IA2 Space Marines

### ISSUE THREAD

**Issue by lacyj3** [BSData/wh40k-7th-edition#1371]
Plasma Blaster is listed at 15 points in IA2 2nd Ed (5ed) and Battlescribe has it at 20 points.

**Comment by Itsacon** [comment]
I'll have to check at home, but I'm pretty sure it's 20 points. Graviton and melta are 15, Heavy Flamer is 10, plasma blaster is 20.

**Comment by lacyj3** [comment]
![image](https://cloud.githubusercontent.com/assets/9757195/9333736/37108dd8-4599-11e5-82ec-ec1a5a57f661.png)

**Comment by senpai514** [comment]
That page can't be from the second edition of IA2 codex black Templars was gone before they redid the book. That page looks to be from the first edition

**Comment by lacyj3** [comment]
I thought I has 2nd ed.   I'll go with what you think it is.    Let me know so I can adjust my list if its the cheaper option.

**Comment by senpai514** [comment]
You should be able to tell by the cover. Do you have the actual book or
just a pdf with all or some of the pages?

**Comment by lacyj3** [comment]
i'm at work with PDF.....my friend and I have the real book (split for costs reasons).  Just not with me.

**Comment by lacyj3** [comment]
![image](https://cloud.githubusercontent.com/assets/9757195/9334755/4cfd94e2-459e-11e5-85a8-d41df6cb55c8.png)

**Comment by Itsacon** [comment]
That's not Imperial Armour 2. That's Imperial Armour Apocalypse. And to make matters more confusing, that version has been replaced by the 2013 edition of Imperial Armour Apocalypse (which is just called Imperial Armour Apocalypse, without X edition).

Both the newer IA Apoc, and IA 2 have the plasma blaster at 20 points.

For a complete guide to the IA chronology, check [Wikipedia](https://en.wikipedia.org/wiki/Imperial_Armour).

**Comment by lacyj3** [comment]
no wonder its confusing!

**Comment by lacyj3** [comment]
![image](https://cloud.githubusercontent.com/assets/9757195/9337790/730289ac-45af-11e5-911a-61db20b29b11.png)

**Comment by lacyj3** [comment]
let me try that one.   Yep,  it's 20 points.

**Comment by senpai514** [comment]
Yeah the pdf you were looking at before is outdated.
