### ISSUE TITLE
Codex Space Marine - hide characters by chapter tactics

### ISSUE THREAD

**Issue by fjramsay** [BSData/wh40k-7th-edition#138]
This is an enhancement request. 
In the Horus Heresy Legion Battlescribe files it hides/shows the special characters based on what legion is selected.  I think that would be a great enhancement to to use Chapter Tactics to hide/unhide space marine characters.

**Comment by Kangodo** [comment]
We've had talk about that before in #124 
With HQ's that allow units as troops, etc, etc.
I personally think it's too confusing and I want to give people the option to see everything and then pick in the order they want.

I want people to look at the roster, see Telion and think: "Hey, he seems awesome. Let's select him and see what I need for that."
