### ISSUE TITLE
War Convocation Formation

### ISSUE THREAD

**Issue by Flashpoint-** [BSData/wh40k-7th-edition#1385]
BattleScribe v1.15.07
Android Note 3

Is the War Convocation Formation
Being overhauled? If not. It seems to have been deleted? 
War Convocation Formation is in the list but no files come up when selecting it, in all the portions Skitarii, Cult Mechanicus, & Imperial Knights

As always keep up the good work.
thank you for all you guys do.

**Comment by Throtard** [comment]
You have to select first War Convocation as force type. After that you have to add 3 more forces (cult mechanicus part, skitarii part and imperial knight part), selecting War Convocation as primary roster. I just created one roster in the mobile app following these steps. I know that it's a bit more complicated than usual, I hope it helps.
