### ISSUE TITLE
No ravenwing strike force option

### ISSUE THREAD

**Issue by leedstilidie** [BSData/wh40k-7th-edition#1388]
Hi. The ravenwing strike force option has gone from formations menu in dark Angels codex. Is a new one being written?There was one a few weeks ago but has vanished. Thank you.

**Comment by Itsacon** [comment]
Formations menu? Ravenwing Strike Force is not a Formation, it's a Detachment. You can select it in the `Force Type' box under`Edit Forces'.

**Comment by leedstilidie** [comment]
Sorry. Thank you.

**Comment by leedstilidie** [comment]
Sorry. Thank you.
