### ISSUE TITLE
New FW model: Space Marine Quad Morter

### ISSUE THREAD

**Issue by Thairne** [BSData/wh40k-7th-edition#1399]
http://www.forgeworld.co.uk/resources/fw_site/fw_pdfs/Horus_Heresy/RapierQuadMortar40k.pdf
- [x] DA
- [x] SM
- [x] SW
- [x] BA
- [x] Tyrant's Legion (IA09)
- [x] Siege Assault Vanguard (IA10)

**Comment by timrterrible** [comment]
I'll add this to the SM codex, not confident modifying SW/BA.

**Comment by senpai514** [comment]
Oh yeah I forgot all about this

**Comment by Flashpoint-** [comment]
Why not fix BA it says they can use them!?

**Comment by amis92** [comment]
@Flashpoint- I think you missed the point. @timrterrible just said he isn't up to it. Someone else might be, tough.

**Comment by senpai514** [comment]
I'll get them
