### ISSUE TITLE
Deathstorm drop pod update

### ISSUE THREAD

**Issue by Gorditospree** [BSData/wh40k-7th-edition#1415]
Battlescribes data on the deathstorm drop pod is still showing the old data information with its BS2 AV12 all around, special rule automated weapon and with large blast instead of the most updated rules in Imperial armour 12: fall of Orpheus

![screenshot_2015-09-06-03-58-18 2](https://cloud.githubusercontent.com/assets/14146887/9703333/6c14c26a-544e-11e5-920d-80c1df5f2eb3.png)

**Comment by senpai514** [comment]
That datasheet you included in post is not most current one to be used.

**Comment by Gorditospree** [comment]
I don't understand,  so where is the data sheet for the deathstorm drop pod from?, which  is currently being used for battlescribe?

**Comment by Gorditospree** [comment]
Both IA 12 and IA 2.2nd edition were released the same year (2013) that's the only thing I can see where you might say the rules listed above aren't current.  Other than that may I ask how did you determined which data sheet to use so I know how to explain to someone who might want to contest the rules listed above.

**Comment by timrterrible** [comment]
Was IA  2nd edition not 2014? I always take that as the latest rules for most marine stuff from FW. I believe it has the latest (30k books excluded) rules for Contemptors, I'd assume the Deathstorms are similar.

**Comment by Gorditospree** [comment]
I looked further into release dates for these books and according to wiki which isn't a strong source but could be sort of accurate, is stating IA 2.2 was released Dec 2013 and IA 12 was released may 2013. Sorry if I wasted your time.

**Comment by senpai514** [comment]
It was released towards the end of the year we didn't see scans and copies
as most folks started getting it after the new year

**Comment by timrterrible** [comment]
It's not a waste of time at all, thanks for raising the issue - it's hard to pin down the order of precedence with Forge World units sometimes. Some kind of current/non-current/trumps list from GW would go a long way..!

**Comment by Gorditospree** [comment]
Well thank you for your great work and patience.  Cheers

**Comment by senpai514** [comment]
IA2v2 should be the most current. The easiest way I knew immediately that
the sheet above was outdated was by seeing codex black Templar listed as an
army it can be taken for. I'm not home right now so I don't have acess to
any of my files at the moment.

**Comment by Gorditospree** [comment]
Oh Yea that makes sense too.  Thanks again,  the both of you
