### ISSUE TITLE
Space marine - sentinels of terra 

### ISSUE THREAD

**Issue by Maglorum** [BSData/wh40k-7th-edition#1418]
Space marine: supplement Sentinels of terra (2013)vs 36 + gladius strike force
BattleScribe version: 1.15.07

The sentinels of terra using the gladius formation, can't upgrade the tactical sergent to Tor Garadon.

Tor garadon rule say, that is squad is changed from troops to Qg as type "If you upgrade a Space Marine Sergeant to be Sergeant Garadon, his unit’s force organisation slot changes from troops to HQ", but in a gladius formation, still remain a tactical squad and so, valid as per formation requisite.

**Comment by afraeve** [comment]
Great idea, I'll upload a fix shortly.
