### ISSUE TITLE
Codex:space marines

### ISSUE THREAD

**Issue by spellbound44** [BSData/wh40k-7th-edition#1421]
After latest update, a character on a bike makes bike squad disappear from the fast attack section, but they do not appear in the troops section. (In an allied detachment)

**Comment by brothermunro** [comment]
I am also having this issue. Confirmed on Battlescribe Pro 1.15.07 (iOS) and the Space Marines Codex 2015 v14

Edit: I was using the Combined Arms Detachment

**Comment by senpai514** [comment]
Ok I'll look into this thing again and see what I can find out.

**Comment by amis92** [comment]
@spellbound44 was it also on iOS?

**Comment by spellbound44** [comment]
Yes

**Comment by brothermunro** [comment]
Thought the v15 file had fixed it, but problem persists.

**Comment by Hazy31184** [comment]
Same problem.

Bscribe v1.15.07
Samsung S6 Edge
Android v5.1.1 
Combined Arms Detachment
