### ISSUE TITLE
Combined Plasma Obliterator & Aquila Strongpoint Rules ?

### ISSUE THREAD

**Issue by Flashpoint-** [BSData/wh40k-7th-edition#1441]
Anyone have the rules for this GW exclusive Bundle !? 
Rules for them combined the Plasma Obliterator as an emplacement & Aquila Strongpoint the battlements. I heard a rumor that the rule Plasma Overheat is removed from the Plasma Obliterator when used this way as an emplacement.

**Comment by Flashpoint-** [comment]
Hey Jose,

Thanks for writing in to us! The attached file is a PDF copy of the rules for the kit you need. I hope they help!

## 

David Monroe
custserv@gwplc.com

https://goo.gl/photos/isgdBXhSaMnJdo9BA

**Comment by Flashpoint-** [comment]
Let me know if your able to see the PDF rules

**Comment by amis92** [comment]
Yup, it's visible to date.

**Comment by Flashpoint-** [comment]
Can someone add the Plasma Obliterator emplacement to the Aquila Strongpoint Rules in the Stronghold Assault book thanks.

**Comment by senpai514** [comment]
Got it done just need to sync when connected to the web again this evening

**Comment by Flashpoint-** [comment]
Is the update working I can't seem to find it?

**Comment by senpai514** [comment]
Oops forgot to add link sorry will work in next release
