### ISSUE TITLE
Dark Angels - Codex (2015): Deathwing & Fearless

### ISSUE THREAD

**Issue by firulais** [BSData/wh40k-7th-edition#1446]
The rule "Deathwing" (e.g.  Azrael) inherits the rule "Fearless". Shouldn't the rule "Fearless" be linked to Azrael?

Thx everyone for the great work of such a cool catalog for the brand new DA codex.
  Willi

**Comment by Itsacon** [comment]
If I'm not mistaken, I've included the texts for all inherited rules (fearless, hatred) into the Deathwing rule text. I felt it was cleaner that way.

**Comment by Thairne** [comment]
That's indeed the case.
Deathwing is just a combination of Fearless and Hatred(CSM). Until we can link rules to rules, adding the text to the parent rule is the way to go.

**Comment by firulais** [comment]
@Itsacon , @Thairne : you are right, it is added in the text. From the strucutre and reporting it would be clearer to have this rules listed as "inherited" rules the same way as all the other rules with the description alongside. This would be great for plannung your roster where you can see at a glance all the rules of a unit/model and not to read all the text.

@Thairne: "linking rules to rules" would be a great Feature.

**Comment by Itsacon** [comment]
Yeah, if linking rules to rules was available, I'd have done that. But now it meant adding Fearless and Hatred(CSM) to all models with Deathwing, and have the DW rule basically be superfluous. (Not to mention that the models themselves technically don't have those other rules, they only inherit them. If Deathwing got errata'd in some way, we'd have to update them all individually. Slim chance, but still something to think about)

Closing this until rules linking is available. ;-)

**Comment by firulais** [comment]
e.g. "Jink" is not listed in the data sheet for "Ravenwing Bike Squad".
It a "inherited" rules that comes from unit type "Bike".
Strictly this rule has to be linked to the unit type "Bike".

In the catalog you can find "Jink" linked to the "Ravenwing Bike Squad".
Why not with: Deathwing for Fearless and Hatred(CSM)?

**Comment by Itsacon** [comment]
That is a good point. 
So we also need a link-rule-to-unit type...

**Comment by firulais** [comment]
@Itsacon "Unit Type" is currently blank text in the profile (i'm shure you know this). How will you do a "link-rule-to-unit type" to a blank text ;-) You did/do a real great Job on the DA data catalog. Why ignoring the input for Deathwing for Fearless and Hatred(CSM) as linked rules and make it the perfect reference?

**Comment by firulais** [comment]
The entries marked with Deathwing in v23 are (just for those who are interrested):

Asmodai
Azrael
Belial
Company Master
Deathwing Command Squad
Deathwing Knights
Deathwing Terminator Squad
Ezekiel
Interrogator-Chaplain
Librarian
Venerable Dreadnought Squadron
Venerable Dreadnought

XPath Query used:

```
//entry[descendant::links/link[@linkType='rule'][@targetId = /catalogue/sharedRules/rule[@name='Deathwing']/@id]]/@Name
```

**Comment by amis92** [comment]
As it stands, in general we do not link nor mention rules coming from Unit Type. That's one of those situations where (as years have gone by) we agreed it to be common knowledge enough. I do believe we should stick to that, because:
- when an exception is made for one unit (or unit type), people are going to ask why not others
- making it for all would be absolutely overwhelming
- it's really becoming too much of a BRB copy-paste
- and we try to avoid BRB as much as possible - catalogues contain mostly info from Codex/Dataslate.

**Comment by firulais** [comment]
@amis92 Thx for clearing up this issue. So "Jink" should be deleted from the rule because  "Jink" is not listed in the data sheet for "Ravenwing Bike Squad" and comes from the unit type.

**Comment by Itsacon** [comment]
Unit type is blank? For what unit? Cause that shouldn't be.

As for the Deathwing: As Thairne said, for rules granting other rules, it's standard to add the text for those rules to the rule granting them. I had actually added them seperately to most units before realizing most other datafiles (afaik) include the relevant texts in the parent rule text.

This also helps to keep the Special Rules list shorter, and prevents repeated redirects when looking up a rule.

Rules granted by unit type are different, as unit types aren't listed seperately, so there's not place to see what rules that unit types has.

I agree that it's all a bit arbitrary, but we have to pick a method, right?

**Comment by Itsacon** [comment]
@amis92: And the plot thickens.

I honestly didn't know about that (I added the unit-type rules to the DA file). My consideration was that with the current rules, there's actually quite a lot of them, and not all of them are common knowledge. Jink & Relentless are obvious, but Hammer of Wrath is less so in my experience.

Looking at the datafiles now, I see I've not even been consistent: For the RW units, I've added Outflank, instead of including it in the Scout rule text...

Personally, I'm not opposed to adding all the relevant SRs, be it from unit type or granted by other rules. (I hate looking them up in the BRB, so having everything relevant available in my army list is nice). 

But I also think it's nice to have some sort of standard across datafiles (although my experience is that the datafiles are pretty different in style anyway, so it probably doesn't really matter)

Re-opening this for discussion.

**Comment by firulais** [comment]
@amis92 complety agree on that

> I hate looking them up in the BRB, so 
> having everything relevant available in my army list is nice

so why not: Deathwing for Fearless and Hatred(CSM)

**Comment by Itsacon** [comment]
Because I noticed other catalogues doing it this way. (and this way, looking up is even quicker)

But like I said, I already noticed I've not been consistent. The question is: which way to make it more so: add more rules, or remove rules?

**Comment by firulais** [comment]
I'm voting for "more rules" to see them at a glance like this in the roster:

> **Deathwing Terminator Squad (200pts)**
> &nbsp;&nbsp;&nbsp; 5x Deathwing Terminators (incl. Sergeant) (200pts), Terminator Armour
> _&nbsp;&nbsp;&nbsp; Deathwing, Deep Strike, Fearless, Grim Resolve, Hatred (Chaos Space Marines),_
> _&nbsp;&nbsp;&nbsp; No sweeping advances, Relentless, Split Fire, Vengeful Strike_

**Comment by amis92** [comment]
For that, I'll suggest to at least link DS, No SA and Relentless under Terminator Armour

**Comment by amis92** [comment]
Oh, and on Unit Type rules: I do agree there is more than it was (I personally forget some sometimes). And it's not the only issue we really must think about. Warlord Traits are currently mocked to be at least in some way available, but it hurts the logic sometimes. Primary detachments, Warlords, special requirements, joining catalogues into single Formation/Detachment (I'm looking at you, Mechanicus), Rules mentioning rules etc.

What's really hurting tough is that when we start linking those rules up, we may end up linking not-always-granted rules, like (just an example) Instant Death on Force weapons. The weapon has Force rule, the Force rule mentions Instant Death, and so: weapons has Instant Death linked. Most people won't bother to read that it's only granted on successful Force power casting. That's the danger I see.

With so universal in whole Game System's scale issues, I'd wait for the BattleScribe 2 data format. It's gonna be (insert Barney Stinson) Legend... WAIT FOR IT...!

**Comment by Itsacon** [comment]
Force weapons would be a case were including the linked rule in the Force text would be clearest.

As for Warlords/Primary detachment, is that even relevant anymore? In sixth, specific warlords would often grant special stuff (like using units as troops), but this has largely been phased out in favour of formations and special detachments. The only codex I can think of that still has it is CSM, but I might be wrong.

I'll get to work on adding the missing rules to the DA files.

**Comment by firulais** [comment]
@Itsacon Can I give you a hand?

**Comment by Itsacon** [comment]
Yes, you can. See if I broke anything in the datafile. I removed a lot of left-over 6th edition crud (like the old standards), and it's just possible I broke something in the process.

**Comment by firulais** [comment]
@Itsacon Great work and looks great to have all the rules at a glance! Tested it with my rosters and there were no breaks. Thx again for this great work!
