### ISSUE TITLE
Development issue

### ISSUE THREAD

**Issue by timrterrible** [BSData/wh40k-7th-edition#1462]
Hi,

Bit of a meta issue here.. 

I did a commit a couple of nights ago that did nothing but add a couple of rules profiles, yet when I pushed to github I discovered it had removed several thousand lines. I reverted the commit and vowed not to work on things tired again.

It's just happened again. I've added rules profiles to a couple of items and the git diff is showing removals of rules for Ahazra Redth, Assault Rams, all kinds of things. It's incredibly bizzare. Is this the catalogue editor re-ordering the catalogue file and github picking up the movement of lines as insertions or deletions?

**Comment by amis92** [comment]
Yup, that might just be it. If the catalogue has not been updated for some time (ie since previous BattleScribe release), it's probably that. A good advice is to save catalogue just after loading and see if there are any changes. If there are, commit them as "file format update" or so. And then proceed to do the real work & commits. :D

**Comment by senpai514** [comment]
I had to redo some things that I know where done differently to make some
of my modifiers work again. Somewhere along the line in the past month some
of my stuff was undone by something.

**Comment by timrterrible** [comment]
Very strange. I'll try doing the file format update thing as a seperate commit.

**Comment by senpai514** [comment]
Tim just be sure you have your github synced for the latest info and if you
are unsure or have questions please don't hesitate to contact me for
anything in regards to this catalogue.

**Comment by timrterrible** [comment]
I'm always pulled up to date, the catalogue editor behaviour is mysterious. Is there a way to contact you directly instead of opening issues?

**Comment by senpai514** [comment]
Legiones.Astartes@gmail.com

**Comment by amis92** [comment]
I'd much rather recommend such conversations to take place on gitter (badge+link is in README). Publicly putting up email address is not the best idea :)
