### ISSUE TITLE
Dark Angels Formations Missing. 

### ISSUE THREAD

**Issue by jjohnson667** [BSData/wh40k-7th-edition#1469]
It seems as though the Lions Blade Strike Force, Deathwing Strike Force, Ravenwing Strike Force, and 10th Company Support formations are missing from the Dark Angels formations.

**Comment by Thairne** [comment]
The first three are Detachments and not Formations.
The latter is actually not a formation.

**Comment by jjohnson667** [comment]
Thank you for the info.  I see them now in the drop down menu.
