### ISSUE TITLE
[Anon] Fortifications and Stronghold Assault not showing up

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#147]
Fortifications and Stronghold Assault is not showing up as a viable faction in battlescribe, blocking any attempt at using Fortification detachments. I don't know how to fix this, other than just ensuring that it is properly linked into the code.

**Comment by ghost** [comment]
I'm not able to replicate any error on the desktop v1.14.03 (selecting Force Type = Fortification Detachment, Catalogue = Fortifications and Stronghold Assault (2013) v2, using the Warhammer40K.gst from this site). Could you provide any more info?
