### ISSUE TITLE
Space Marine Captain with Artificer Armour

### ISSUE THREAD

**Issue by MWGNZ** [BSData/wh40k-7th-edition#1471]
If I choose a Space Marine Captain, give him Artificer Armour and then try to give him a Chapter Relic the following warning appears

Artificer Armour has 1 too many selections from Chapter Relics \* (maximum 0)
decrement maxSelections by 1 if Artificer has equal to 1 selections of Chapter Relics *

This seems to clash with the Codex.

Note that this is only a validation problem, I can still add the relics I want, there's just a warning at the end.

**Comment by Itsacon** [comment]
If you select a relic weapon, you need to deselect one of the other weapons the model has (bolt pistol/chainsword), since most relics replace a weapon on the model.

**Comment by MWGNZ** [comment]
<img width="1920" alt="screen shot 2015-09-28 at 8 07 46 pm" src="https://cloud.githubusercontent.com/assets/944167/10129631/b7d6c36c-661c-11e5-955a-6869b5c9ad1f.png">
the artificer armour is set up so that if you select a relic weapon then you can't also have a normal weapon in the same hand

**Comment by Itsacon** [comment]
From the looks of it, you're trying to take two chapter relics on one model, which is not allowed. C:SM says: "A model may replace one weapon with one of the following"

**Comment by MWGNZ** [comment]
Crap, that'd explain it. 

Thanks for your help.
