### ISSUE TITLE
Close combat weapons

### ISSUE THREAD

**Issue by Lunawolve** [BSData/wh40k-7th-edition#1474]
A Chainsword is a melee weapon not a close combat weapon? Any model in a Greyhunter pack can take a close combat weapon at 2pts but they can't take a chainsword or swap their bolt pistol for a chainsword?

**Comment by Fatno** [comment]
Chainsword and CCW are both Melee Weapons with the same profiles.

**Comment by Lunawolve** [comment]
Ok so if they take a close combat weapon for 2pts that means a knife, teeth and claws, club or a nice big chainsword. Seams a bit out of balance doesn't it. oh well I guess the pen can be mightier or just as mighty as the chainsword.
