### ISSUE TITLE
Codex Space Marines bikes missing with bike HQ

### ISSUE THREAD

**Issue by bernardlowyr** [BSData/wh40k-7th-edition#1475]
When a bike is selected by a HQ choice, the Bike Squad choice disappears entirely as it cannot be found in either the Troops or Fast Attack slot 

Also, for Carcharodons Chapter Tactics, Tactical Squads are unable to take an additional close combat weapon for +1 points, and Tyberos doesn't get his lightning claw terminator squad as Troops.

**Comment by bernardlowyr** [comment]
Also, Red Scorpions tactical sergeants are unable to become Apothecaries

Combi-plasma in the options is also misspelled as compi-plasma

**Comment by senpai514** [comment]
I have not yet begun to start incorporating FW tactic options into the main
file just yet.

**Comment by senpai514** [comment]
tested and bikes work as they are supposed to
