### ISSUE TITLE
Multi language support

### ISSUE THREAD

**Issue by firulais** [BSData/wh40k-7th-edition#1476]
The BSData/wh40k initiative is a great thing but i realy would like to have the catalogue in a native language (e.g. german).

Jon Taylor suggested: "You would be better off making separate catalogue files for the different languages. E.g. dwarfs_en.cat, dwarfs_fr.cat"
http://battlescribe.uservoice.com/forums/55066-general/suggestions/1508695-multi-language-support

For those who are interressed you can find here a demo (Dark Angels in German) of how to translate a catalog (live) online.

The translation keeps the original id's of your catalog. When using override just your data/*.cat file with the translated file. 

https://script.google.com/macros/s/AKfycbz-eOVtDFby8klQ4BS6j4ApeagdrxZiNR6m8_3TWptFZJkxQfs/exec

If you think this maybe of some interrest leave a comment.

thx, Willi

**Comment by Thairne** [comment]
Interesting! Especially the auto-translate tool.
Although I shiver at the additional effort to keep everything up to date with the translations for every language... Every little change in wording and addition will have to be added to your script tool to work properly, I assume?

**Comment by amis92** [comment]
I think this is currently un-doable and un-maintainable. It would require support od BattleScribe to properly work.

But I'll surely work on a mechanic to include it in my little project... ;P

**Comment by firulais** [comment]
Thx for the comments. Of course it's un-do-able. But with a community behind such things are possible. Depends if the need in the community is strong enough.
I'm happy with it, because i get out alway the actual index in german for DA.
There are missing some parts in the translation but it was to show that there is a way to do it and to keep the cataouges here as a basis and no need to start for ervery language a extra catalouge.
It will be less work to just translate it instead of maintaining seperate catalouges for every language.
The multilange translation service is build up in google script.

**Comment by Thairne** [comment]
Maybe if we spread the link to your tool?
Not officially support it, but make it known you can get a translation there?

**Comment by firulais** [comment]
@Thairne Great Idea. There has to be done a little bit more before it's valuealbe for spread.
At the moment it was just to show how multilanguage may be integrated into the process.
I'll try to go on with the translation tool and give you Information on updates.

**Comment by Itsacon** [comment]
Good thing to think about is what to do when different languages for a Codex have serious differences. For instance, I seem to remember that the current German Space Marine Codex omits the repair bonus for servitors. If similar conflicts (especially if the solution is less clear) come up, which codex is leading for that language of the datafile?

**Comment by firulais** [comment]
@Itsacon what codex are leading in internatinal tournament?

**Comment by amis92** [comment]
But aren't ITC using English-only rules?
