### ISSUE TITLE
[Anon] Can't add Imperial Knights to roster

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#148]
Not exactly sure how to fix it. All I know, is I can't add on my imperial knights under this section. So, hopefully this problem can be fixed. Thanks.

**Comment by Kangodo** [comment]
How do you mean exactly? The issue is unclear to me at this moment.

**Comment by amis92** [comment]
I take a wild guess: our friend is confused by the ability to choose a Combined Arms Detachment of Knights, which has no units listed.

If a Knights Detachment is taken, there is no problem.

But a problem may be of another nature of course. Just guessing.
