### ISSUE TITLE
Tau Codex Updates Questions

### ISSUE THREAD

**Issue by LockeWatts** [BSData/wh40k-7th-edition#1490]
Hi all,

Are there any plans to add the Stormsurge and Ghostkeel rules from White Dwarf to the current Tau Codexes before the new release?

**Comment by efalsken** [comment]
I suggest against it. The rules in White Dwarf are incomplete. We have no idea what "Fire Team" does, for example. If you wish to test the units with your friends, the WD rules should be enough to give you a preview. The entire army roster will need to be replaced to be accurate, judging by what happened to the Eldar, Necron and SM releases.
