### ISSUE TITLE
Codex: Necron - no Figher Ace book ref

### ISSUE THREAD

**Issue by Gergggggihad** [BSData/wh40k-7th-edition#1491]
In Necron Codex there is no book ref for Fighter Ace option on Night Scythe and Doom Scythe.

_**Original**: can you please provide the exact codex/book expansion that lists the "fighter ace" option and the page number so that it can be referenced in a game._

**Comment by efalsken** [comment]
In which army roster?

**Comment by Gergggggihad** [comment]
It is listed in the necron roster as an option for night sythe and death sythe when you are using the battlescribe app and program
Greg

Sent by Outlook for Android

**Comment by efalsken** [comment]
the latest version of the Fighter Ace rule comes from the Tyranid campaign books: Shield of Baal - Leviathan p46 (originally printed in Death from the Skies) The rule is for "all fliers" and has faction-specific random abilities. It's a great set of rules.

Most of the armies have it correctly referenced. I'll leave this ticket open for the Necron maintainers to address.

**Comment by Gergggggihad** [comment]
Unfortunately this not true in the new necron 7th addition book.

I have a bad feeling it was omitted.

Greg

Sent by Outlook for Android

**Comment by francoisbeaulieu** [comment]
It does not appear to be referenced for the Space Marines as well.

**Comment by cartag** [comment]
KDK has been taken care of.

**Comment by Gergggggihad** [comment]
Stupid question ?  KDK?

Sent by Outlook for Android

**Comment by cartag** [comment]
Khorne Daemonkin.
