### ISSUE TITLE
[Question] Dark Angels - Codex (2015): Deathwing Strike Force & Deathwing Redemption Force

### ISSUE THREAD

**Issue by firulais** [BSData/wh40k-7th-edition#1492]
Thx again for the great Dark Angels - Codex.

I try to create in BS a roster an Armee based on
Force Type: Deathwing Strike Force
that contains a
Formation Detachment: Deathwing Redemption Force

I'm just able to create both (but can't include them).
BS gives the alert:
Deathwing Strike Force must have 1 more selection from HQ (minimum 1)
Deathwing Strike Force must have 2 more selection from Elites (minimum 2)

The HQ and Elites are within the Formation Detachment: Deathwing Redemption Force.

Tips welcome how to handle this in BS.

Thx for every hint. regards, Willi

**Comment by Itsacon** [comment]
The Deathwing Strike Force and Deathwing Redemption Force are two separte entities. One is a detachment, the other is a formation. You can't have one as part of the other. The DWSF can contain HQ choices and Elite choices, it can't contain formations.

You can just pick one of them, and use that as an army.
