### ISSUE TITLE
Apocalypse formations

### ISSUE THREAD

**Issue by Lunawolve** [BSData/wh40k-7th-edition#1497]
Many Apocalypse forces don't have the Apocalypse formations

**Comment by Lunawolve** [comment]
Just wondering if people think that having the appropriate categories in the apocalypse entries like Armoured Spearheads, Battle Formations, Flyer Wings, High Commands, Massive Fortifications, Psychic Choirs, Super heavy Vehicles, Super heavy Walkers, Super heavy Flyers, Gargantuan Creatures and Flying Gargantuan Creatures would make apocalypse lists make more sense since some Apoc formations do cost points

**Comment by amis92** [comment]
Not sure if I understand, but I don't think creating specific Categories in Game System is necessary. It may be, but they're more of a special rules, aren't they?. I have no idea what point cost has to do with that, however.

**Comment by Lunawolve** [comment]
Yeah sorry if it's a bit confusing but I was asking if we should create extra categories like you said but only in the Apocalypse entry in the game system like the already existing Battle Formations. I suppose it wouldn't really matter if when we add the other Apocalypse formations we put them under the Battle formations just like the space marine company is. That way they would all be in the same place.

**Comment by senpai514** [comment]
I find it interesting that there has been a sudden influx of apoc related requests and activity lately

**Comment by Lunawolve** [comment]
Is that a bad thing?

**Comment by ghost** [comment]
@Lunawolve  +1

**Comment by hisop** [comment]
This should be on an individual basis for catalogs as they come in, if there are specific ones missing raise appropriately until then i'm closing this.
