### ISSUE TITLE
Coordinating Tau Codex Release

### ISSUE THREAD

**Issue by efalsken** [BSData/wh40k-7th-edition#1506]
Just so we don't get 30 authors stepping on each other, do we have plans for one or two authors to collaborate on it as quickly as possible after release? I can volunteer if nobody else is. I can take a day or two off of work to work on the Tau Catalog after getting my copy of the Codex.

I'm already a contributor.

**Comment by amis92** [comment]
I'm still interested in making it. I guess it'll come to who gets the codex first. But an issue to keep track of situation is a good idea. Also, certainly has to be done on a separate branch, not to stall/mixup with other bugfixes.

**Comment by efalsken** [comment]
I believe we should do like the other codexes have done. When the new codex comes out, we either rename the old one(s) or start a new data file for the new codex and mark the old one as deprecated ... to be removed 60 days after the new codex release.

I also like what a few of the other data files have done with hiding the Forgeworld units unless a "Show Forgeworld" option is selected.

One of the things I'd like to experiment with is moving the definition of the army composition into the army file instead of relying on the catalog-level detachment definitions and spamming the detachment-type box with army-specific detachments. E.g. Tau Empire - Standard Army as the army type selection, and then selecting either a CAD, Allied, Formation, or super-detachment while in the roster editor and having those make the unit selections available.

**Comment by amis92** [comment]
I have to say I strongly dislike the auto-hiding of Forge World, but alas - it's personal, so. It's also not like we have a metric ton of FW choices like SM/CSM etc.  :)

As to experimenting with moving army composition to catalogue - that's a no-no. We have BattleScribe update on horizon (well, it may be a month or half a year) which will do what you want. It'll essentially allow for definition of force types exclusive for a catalogue, in that catalogue.

**Comment by efalsken** [comment]
Ah. I see. I was unaware of the pending Battlescribe update. that will be nice. Looking forward to working with you. Is there a way to PM someone here?? Feel free to contact me on Facebook chat (same username) if youd like to coordinate effort in more detail. I'll be pre-ordering the codex on Day one and will have the Electronic version as soon as it goes on sale. I'll schedule a few days vacation from work to spend on this release, too.

**Comment by amis92** [comment]
Yeah, the update will be very nice. It's just 'coming' for sooo long :D We may chat on our gitter room https://gitter.im/BSData/wh40k - that way we do not clutter up issue, but everyone can see progress and suggest ideas. :)
