### ISSUE TITLE
Imperial Knights

### ISSUE THREAD

**Issue by Hasfodel** [BSData/wh40k-7th-edition#1513]
Hi, I've seen the Atrapos have been added, nice, but that would be cool if someone could make a few changes and fixes.
I managed to do it myself with the BS catalogue editor
But then I tried to submit it, and discovered that it was a bit complicated for me...
So, I'll let clever ppl do ;)
The issues : 
- Fix the price of the Heirlooms for the Cerastus-class Knights in the Exalted Court Formation
- Add Wargear info, rules and description for the Heirlooms
- Add rule descriptions that are missing (3 or 4 of them are still empty)

Thx :)

**Comment by senpai514** [comment]
No problem that's one of my files so I can get that stuff hooked

**Comment by Hasfodel** [comment]
Thanks ! and I forgot : 
And in the Exalter Court Formation, all knights are characters (not only warlord), the base WS/BS is at 5 for all knights, and 6 for the warlord.
The increment +1 for warlord is here for some knights ( but not all of them )

Oh and I just realised that the number of attacks of the Warden in this formation is at 5 instead of 3

**Comment by Hasfodel** [comment]
In the Skyreaper formation, the "3 knights of any type" should be an entry group instead of an entry.
Oh and in the new version, the atrapos is not listed as a lord of war! :) 

Anyway, I have my catalogue with everything clean and fixed... Maybe you could tell me how to submit it... or I can send it to you ?

**Comment by amis92** [comment]
@Hasfodel if you already have GitHub account (as you do), I suggest performing pull request. More help here: https://github.com/BSData/bsdata/wiki#getting-started - You may look at doing it as freelancer.
