### ISSUE TITLE
Kauyon: Space Marine Detachments

### ISSUE THREAD

**Issue by pretzalcohuatl** [BSData/wh40k-7th-edition#1531]
Rules have been leaked for Raven Guard- and White Scars-specific detachments

**Comment by pretzalcohuatl** [comment]
Haven't tested, please report any bugs

**Comment by afraeve** [comment]
@whiskeyjuvenile - You'll need to change the ID on one of these.

**Comment by pretzalcohuatl** [comment]
yeah, just noticed.

**Comment by amis92** [comment]
Done?

**Comment by ghost** [comment]
Looks like we're missing the formation special rules.

**Comment by ddarz** [comment]
Done and in next release!
