### ISSUE TITLE
Talon Strike Force errors

### ISSUE THREAD

**Issue by ddarz** [BSData/wh40k-7th-edition#1539]
Hi, just had a quick look at these
Some errors so far:

Chapter Relics for the captain and chaplain are in the wrong slots
Relic jump pack is listed as a weapon
Could not see the relic armour option
Also only one relic is allowed per character - as far as I know multiple relics are allowed on the same character. But only one of each as they are unique
The sniper rifle relic is not available at all as far as I could tell - it should be an option for vet. Scout Sergeants.

Also the formations should be made available to the general codex as well. Only the Talon and Scarblade detachments are exclusive. The various formations, such as the Pinion and Ravenhawk are available to all chapters

Finally a question. Will the exclusive detachments and relics be made available to Raven Guard and White scar successors such as the Mantis Warriors, Raptors and Carcharodons? Multiple emails to Forge world says it is allowed as due to them being successors, although there is as yet no FAQ yet (and it is sorely needed)

Will keep testing

**Comment by senpai514** [comment]
Formations for original codex are already being worked on.

**Comment by ddarz** [comment]
Thank you:)

**Comment by ddarz** [comment]
Another issue:
The Ravenhawk formation only accepts standard dreadnoughts as valid.
It gives an error that 1 selection of dreadnought is needed, even if an ironclad or venerable has been selected.

**Comment by ghost** [comment]
I played around with the Raven Guard detachment last night and didn't see any Formation or Detachment rules included.

**Comment by ddarz** [comment]
This has not been updated in a while, is it still planned or will it be rolled into the CSM files?

**Comment by amis92** [comment]
@senpai514 I can't find a stated reason for closing the issue. Please provide some at your convenience. ;)

**Comment by ddarz** [comment]
Hi, I think it's because all those separate catalogues are gone now!

**Comment by amis92** [comment]
Great. Didn't have time to analyze.
