### ISSUE TITLE
Would like to update Tau

### ISSUE THREAD

**Issue by kmonsvik** [BSData/wh40k-7th-edition#1541]
Hello there,

Do you guys have anybody to add the latest Tau info?
If not, I can get cracking on that.
I'm a video games programmer so I should be fairly proficient at it, technically.
If you already have somebody on the case then that is fine.

Cheers,
Kris

**Comment by senpai514** [comment]
Our Tau authors are already working on this so you know.

**Comment by kmonsvik** [comment]
Great!
