### ISSUE TITLE
Relic of the Armoury // FW-question.

### ISSUE THREAD

**Issue by Kangodo** [BSData/wh40k-7th-edition#155]
Hello people and co-editors!

In the BA-file I tried to get this "Relic of the Armoury"-thing working.
At the moment it kind of works:
It has a maxinroster of 0.
If you take your detachment as primary, it increments with 1.
If you take a Reclusiarch, it increments with 99. (This to avoid two modifiers that both set to a different number)

This allows us to take:
1 Relic in your primary detachment.
1+ Relics if you have a Reclusiarch in a secondary detachment.
1+ Relics if you have a Reclusiarch in a primary detachment.

At the moment my Relic is linked to Reclusiarch.
I would like to give this Reclusiarch a new entry named "Keeper of Relics" so everyone can easily copy my implementation of the Relic-rule and the vehicles that come with it.
Opinions?
.
.
Another question is about FW.
How do people feel about using the Hidden-option to hide/show FW-units with Space Marines?
My BA-file has 6 units already and there are tons to add.
Many players do not use FW-models/rules and this might make the lists less confusing.
I'm really thinking of adding this to my catalogue
Necrons are fine, because they hardly have any units.. But Space Marines can go up to 20 or so entries.

Greetings,

Kangodo

**Comment by ghost** [comment]
The wording of the rule in IA2 is unclear, but I think you're allowed a single Relic in a secondary detachment that doesn't have a KoR, just as with the primary detachment. That's the way I set mine up. 

I won't be hiding FW stuff.

**Comment by Kangodo** [comment]
Hmm, I read it differently because it says "in this case, the KoR must be the compulsory HQ".

The FW-Hide/Show is quite awesome.
By default it always shows the options.
If you select the entry, it still shows all options.
You really have to press hide and than it hides everything!
Kind of nice since I intend to add every single FW-unit to my list before September.

**Comment by ghost** [comment]
The problem for me is it doesn't say you must have a KoR, so I'm taking it to mean _if_ you have one, it must be the compulsory HQ.

I'm just not interested in indulging those of a narrow anti-FW mindset. And why stop there? We could do an option to hide War Zone units, or flyers, or named characters. But here we have a chance to show people that, hey, this stuff is interesting, useful and no more over-powered than anything else that's new.

**Comment by Kangodo** [comment]
Aah, I understand. We definitely need some clarification from FW.

And don't get me wrong, I'm not interested in pleasing the anti-FW mindset.
It's a matter of reality to accept that most players, despite wanting it, do not own ForgeWorld.
I own only a single Damocles Command Rhino, and all those options make it harder to build a list.

I made the change, will wait for release and then I'll ask the players how they feel about it.
And ofcourse I will share their thoughts on here.

**Comment by ghost** [comment]
Yeah, there's a few things crying out for an faq.

Daft thing is, when I built my SM file, the existing one on Randomhit had no FW units. So that meant there was one all-inclusive & one codex-only. Then when they updated it for 7th, people started adding odd bits & pieces of FW stuff to the Randomhit file.

**Comment by Kangodo** [comment]
Not just people ;) I added most of those things.
Boy that was a long time ago.. I even see they never bothered to fix that Devastator-Placeholder.

**Comment by Kangodo** [comment]
Questions answered, also changed the Devastator PH.
Worked on that a year ago, but it seems they never got updated.
