### ISSUE TITLE
Bug issue - Orks codexes: HQ/Nobz in mobs have no access to eavy armour or mega armour

### ISSUE THREAD

**Issue by happyhighfield** [BSData/wh40k-7th-edition#156]
Ork HQ (Big mek & Warboss) have no access to eavy armour or mega armour. Also Nob in ork mob have no access to eavy armour

**Comment by Kangodo** [comment]
#141 also mentions this issue.
Both my pc and HTC M8 show the option.

Where are you looking at? Can you provide a screenshot or anything?
Because it clearly says:
Must Choose 1
-'Eavy Armour
-Basic Ork Armour
-Mega Armour

**Comment by happyhighfield** [comment]
Look at it again...the problem was that I ticked the "must choose..."text, instead of the black circle behind it. Sorry for the misunderstanding!
