### ISSUE TITLE
Enhancements: Adding the Faction name prior to the Detachment name

### ISSUE THREAD

**Issue by Viper666-Qc** [BSData/wh40k-7th-edition#1566]
Please could you add the name of the Faction first to any of the Detachment in the list? The list is getting longer and longer and they only seem to be listed from the oldest to the newest release...

ex: 
Space Marines - Gladius Strike Force
Tau - Hunter Contingent

**Comment by efalsken** [comment]
Tau is already prefixed with "Tau" before the Hunter Contingent. We have very little control over the ordering of the Force names in Battlescribe. That's, I think, an open issue.

**Comment by Viper666-Qc** [comment]
Yeah I saw that Tau Hunter Contingent was already in this format. They really should all be in this format though. Who can change the names? Can you explain the issue to this person?

**Comment by efalsken** [comment]
I will raise the issue with the team. I can make this change, but should not do it without checking with a few people. I do agree.

**Comment by Thairne** [comment]
I did this once to try and order the detachment types. As we found out, it's sorted by some internal ID.
Naming the Detachments appropriatly would cause one issue through - Adeptus Mechanicus Detachments e.g. would suddenly sort before CAD when the alphabetical sorting is implemented.

**Comment by amis92** [comment]
@Jonskichov hey, is there any way for us to sort the detachments? What's the internal mechanic for sorting how they're displayed?

**Comment by Jonskichov** [comment]
Well you're not going to like it, but at the moment the sort order is just the order they appear in the game system file...

Originally this made sense since there weren't very many. Not so much nowadays...

Future update will bring the ability to only show the force types needed.

I _could_ do a quick "sort alphabetically" update I guess but you'll have to figure out a way to get the basic force types to float to the top...

**Comment by amis92** [comment]
Well that's actually good news, in a kind of way, and I think it should stay so. We can then sort it however we want, and just move things around in xml if needed.

**Comment by Thairne** [comment]
Well we could just workaround by adding an asterix \* to the front of those.
No work for Jon and works just the same.

**Comment by amis92** [comment]
What would asterisk mean?

**Comment by amis92** [comment]
I'd rather suggest introduction of naming convention, ie:
- C:AA SM - Codex: Adeptus Astartes Space Marines
- C:AA DA - Codex: Adeptus Astartes Dark Angels
- C:AM - Codex: Astra Militarum
- BRB - Big Rule Book

So that would lead to a list of force types like that:
- BRB Combined Arms Detachment
- BRB Allied Detachment
- BRB Formation Detachment
- C:AA BA Whatever Their Detachment Name Is
- C:AA SM Demi Company
- C:EC Widnrider Warhost (or what is that)
- C:Nec Decurion
- C:TE Hunter Continent

What y'all think?

**Comment by Thairne** [comment]
AN asterix would simply stringsort the entrys to the front.
So it would look like
*\* CAD
*\* AAD
*\* Formation

Deathwing Strike Force

Flesh Tearers thing

Necron Decurion

Windrider Warhost

It would add less clutter

**Comment by efalsken** [comment]
I like the idea of using BRB. But, as has been pointed out, if the listing uses the file order, we can use whatever ordering we wish. 

I think we should go with the original suggestion, but put the base rulebook detachments and unbound detachment first in the file order.

**Comment by afraeve** [comment]
It's easy enough to rearrange them in XML. A quick cut & paste might look like this:

![names](https://cloud.githubusercontent.com/assets/13020665/10967264/26e55e06-83b1-11e5-95a6-92998afb07e1.jpg)

On the naming convention - I'm not sure the BRB, S, or C: are really necessary.

**Comment by efalsken** [comment]
I think it's good enough to put the BRB stuff at the top. I don't think we
need to prefix it with "BRB", nor do the supplement detachments need "S".

On Thu, Nov 5, 2015 at 3:35 AM, afraeve notifications@github.com wrote:

> It's easy enough to rearrange them in XML. A quick cut & paste might look
> like this:
> [image: names]
> https://cloud.githubusercontent.com/assets/13020665/10967264/26e55e06-83b1-11e5-95a6-92998afb07e1.jpg
> I've tried to group things together there. Suggestions on the naming
> convention?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/BSData/wh40k/issues/1566#issuecomment-154037217.

## 

Eric Falsken
eric@everylittlething.net

"Expect everything, and anything seems nothing.
Expect nothing, and anything seems everything."
– Samuel Hazo

**Comment by amis92** [comment]
Yup. Well, I think it's settled then, no need to discuss any longer. @afraeve, would you please do the update like what you've shown, but without the prefixes? And close the issue. Let's get it done.

**Comment by efalsken** [comment]
You mean only "without the BRB and S" prefixes, right?

On Thu, Nov 5, 2015 at 2:01 PM, Amadeusz Sadowski notifications@github.com
wrote:

> Yup. Well, I think it's settled then, no need to discuss any longer.
> @afraeve https://github.com/afraeve, would you please do the update
> like what you've shown, but without the prefixes? And close the issue.
> Let's get it done.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/BSData/wh40k/issues/1566#issuecomment-154209304.

## 

Eric Falsken
eric@everylittlething.net

"Expect everything, and anything seems nothing.
Expect nothing, and anything seems everything."
– Samuel Hazo

**Comment by amis92** [comment]
Yes, that's what I meant, sorry for confusion.

**Comment by Viper666-Qc** [comment]
just put [General] or [All Faction] in front of CAD, Formation Detachment, Fortification and Allied Detachment if you want those 4 to come up first (special characters should list before letters right?)

**Comment by Viper666-Qc** [comment]
In the same manner, It would be great to find a way to put the Expansions Detachments (ie Planetstrike, Apocalypse...) at the end.

**Comment by Viper666-Qc** [comment]
The use of a 3 different symbols before all the names could do it to separate the 3 kinds (general/all faction BRB detachments vs faction-specific vs Expansions)

[ ] vs { } vs ( )

**Comment by amis92** [comment]
@Viper666 have you read the thread? BattleScribe doesn't sort it any way. It displays them in the order they are in the file. :) No reasons for symbols either then.

And I think Expansion Detachments should be first after BRB detachments. Faction-specific last, as they make up most of the list anyway.

**Comment by afraeve** [comment]
That's up now. I think the old Space Wolves Detachment is no longer valid - should we delete it?
