### ISSUE TITLE
Dark Angels - Company Master - Missing Wargear

### ISSUE THREAD

**Issue by DJammyRasta** [BSData/wh40k-7th-edition#1570]
I believe the company master should be able to take a bike or be given a jump pack.

**Comment by Itsacon** [comment]
Bike is not allowed. For models that have the option (Librarian, Interrogator Chaplain, Chaplain and Techmarine), it's listed seperately on their page.

Jump pack is allowed, and is possible in the roster (under `Unit type', when equipped with Power armour or Artificer armour).
