### ISSUE TITLE
Tyranids - Endless Swarm

### ISSUE THREAD

**Issue by Morphyum** [BSData/wh40k-7th-edition#1578]
The endless Swarm Formation was changed to 3xtermangants. Currently it is still 2x in battlescribe.

**Comment by Randobar** [comment]
we already discussed that but because of a faulty release some people still insist that 2 broods are allowed and therefore the datafile stayed that way. I once fixed it but it was reverted later.

**Comment by Morphyum** [comment]
Whats there to discuss? Even if the formation would have been 2termagants and it wouldn't have been a mistake. A newer version always overrides the old one. Therefor by patching the dataslate the old version was overridden and is not a valid formation anymore it's the same as a codex.

**Comment by amis92** [comment]
I think it should actually be fixed. Again, if need be. :)

**Comment by Randobar** [comment]
done
