### ISSUE TITLE
Dark Eldar Venoms

### ISSUE THREAD

**Issue by mrmagoo73** [BSData/wh40k-7th-edition#158]
Dark Eldar Venoms don't have the option to Buy a second Splinter Canon.  

Thank you.

**Comment by axisofentropy** [comment]
I don't see this option in the Codex or FAQ.

**Comment by axisofentropy** [comment]
Oh, now I see that the catalogue doesn't list the splinter cannon included in the Venom's default wargear.  I'll correct this.

**Comment by mrmagoo73** [comment]
Thank you sir

Sent via the Samsung GALAXY S® 5, an AT&T 4G LTE smartphone

-------- Original message --------
