### ISSUE TITLE
CSM Terminator Power Weapon Cost

### ISSUE THREAD

**Issue by Gnom3y** [BSData/wh40k-7th-edition#1596]
When taking more than 1 Terminator Squad, the point costs for Power Weapons return to 15 points per model, rather than the required 0 points per model. I attempted to submit an adjusted copy, but the upload system flagged an unknown error.

The fix is rather simple. Currently the data file states that Terminator Squads must EQUAL 1 in order to set Power Weapon points to 0, where it should state that Terminator Squads must be AT LEAST 1.

**Comment by cartag** [comment]
Confirmed working in v183.
