### ISSUE TITLE
 Deredeo Dreadnought missing Plasma Cannonade

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#1602]
**File:** Warhammer40K.gstz

**BattleScribe version:** 1.15.07

**Platform:** Android

**Dropbox:** No

**Description:** Hellfire Plasma Cannonade missing from upgrade options for Deredeo Dreadnought.

**Comment by Thairne** [comment]
Care to be a bit more specific? In which Codex is it missing?

**Comment by hisop** [comment]
After a look around This option is missing from Codex blood angels, also it has an incorrect point cost in codex space marines, i will fix it unless anyone else wants it?
