### ISSUE TITLE
Codex: Space Marines - Techmarine

### ISSUE THREAD

**Issue by francoisbeaulieu** [BSData/wh40k-7th-edition#1607]
The entry for the Techmarine does not include the "independant character" special rule like it should.

**Comment by ddarz** [comment]
As far as I can tell, all the characters have the "Infantry (Character)" tag - should we change this to "Infantry (Independent Character)" were appropriate?

**Comment by francoisbeaulieu** [comment]
Not sure. Most other examples I can see (like the Librarian) keep the Infantry (Character) type, but just add "Independant Character" to the list of special rules. Either way is fine with me.

**Comment by amis92** [comment]
@ddarz No, that surely is not valid. You just need to add a link to IC shared rule to Techmarine.
