### ISSUE TITLE
[Anon] Space Wolves corrupted file

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#161]
Hey I can't access the file in battlescribe on the iPhone 5s. The phone is updated to the latest OSX and I just tried re-installing battlescribe on the phone so it's at the latest that's on the App Store. Whenever I try to open or create a roster it tells me that it had an error opening the data and the catalogue. I should also mention that this seems to only be the case with space wolves. Please fix this soon.

**Comment by amis92** [comment]
So I guess it's only Space Wolves specific bug. Renaming. (Was for 40k.gst).

**Comment by amis92** [comment]
Merged into #160.
