### ISSUE TITLE
[Anon] Bug report: Space Marines - White Scars Scarblade Strike Force.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#1630]
**File:** Space Marines - White Scars Scarblade Strike Force.catz

**BattleScribe version:** 1.14.07

**Platform:** Android

**Dropbox:** Yes

**Description:** White scar relics options missing from relic options list

**Comment by Glodart** [comment]
File: Space Marines: White Scars Scarblade Strike Force
Platform: IPad
White scars relics are missing from the relic option

**Comment by amis92** [comment]
Discussion in #1664
