### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by ddarz** [BSData/wh40k-7th-edition#1650]
Hello!

I was hoping to join as a 40K contributor? 
Primarily to help share the workload and solve the outstanding issues faster. I have a good access to Warhammer 40K codexes and material, and I am technically proficient.

While I am an avid Battlescribe user, I don't have a lot of experience making catalogues from scratch - I am going through the guides and materials to get up to speed and my plan is to follow the established patterns where available, such as with Codex: Space Marines

Cheers!

**Comment by amis92** [comment]
Great, I hope you have fun as much as we do. Please accept the invitation and welcome aboard!
