### ISSUE TITLE
[Protocol question]

### ISSUE THREAD

**Issue by ddarz** [BSData/wh40k-7th-edition#1654]
Hello, thanks for the invite!

A quick question in order to make sure i'm following proper procedure: What are the guidelines for going ahead and making changes?

For example, the Raven Guard TSF catalogue needs some fixes - can I self assign and start correcting? Or do I need permission from the original author? 

Also is there a recommended schema? I was planning to follow the current C:SM layout. Again in the case of Raven Guard TSF, it might be easier to begin from scratch by copying the C:SM catalogue, deleting anything non-RG and adding the Kauyon formations and relics

Just wanted to check with you first - I searched but could not find the info anywhere

**Comment by ecrousseau** [comment]
(Disclaimer: I only joined very recently so I'm as much in the dark as you are)

As far as I know, you just need to check this page: https://github.com/BSData/wh40k/wiki/Catalogue-Keepers. If the army isn't listed and/or doesn't have a name next to it, just add it and/or your name and off you go.

Would it be possible to include the TSF in the main C:SM file? I was able to keep the Cadian Battle Group within the main C:AM file, which will make it easier to maintain going forward.

**Comment by ddarz** [comment]
Hi, thanks for your reply!
Indeed having it within C:SM would be great if that is an option (Wasn't  sure if it was an option)
It is a bit tricky what with the RG requirements but I will look into it! 
From working off the main catalogue, it should be doable with some creative use of conditions

**Comment by amis92** [comment]
Yup, it's not that complicated. Remember to flag/label issues you open/were opened by anon, like I've done here.

I hope you read through Developer Guidelines, most of the stuff there is all you need to know, plus the Catalogue Keepers wiki.

Also for chit-chat and help etc we have chat room (GitHub auth) on gitter, link is in README. There you can also send PMs to others (who joined the chat system) if you wish to.

**Comment by ddarz** [comment]
Thanks! :)
