### ISSUE TITLE
Adding Kauyon Formations to Codex: Space Marines

### ISSUE THREAD

**Issue by ddarz** [BSData/wh40k-7th-edition#1657]
Will attempt to add the new formations to the main file in order to simplify updates and keep the number of catalogues down

Feedback and input very welcome!

**Comment by senpai514** [comment]
@ddarz I had started adding the formations to the space marine file but my
computer is crashed and inoperable at the moment so I am limited in my
continued works.

In reference to your one comment here the other catalogues for raven guard
and white scars can not be consolidated into the main codex, but the
FORMATIONS (not core, aux,command classification) can be in the catalogue
and is what I had started.

If you have questions about the space marine file don't hesitate to ask
I'll be glad to help any questions you may have in regards to the structure
I have going in this file.

**Comment by ddarz** [comment]
Hi Senpai!

Thank you for you reply - I was hoping to communicate with you actually in order to make sure I am following your lead on the main codex!

About the kauyon formations, is it not better to have them within the main catalogue? That way the default entries that you have for the standard units can always be up to date and consistent!

I saw that you had added the separate Kauyon formations so I started by adding the pinion both as a Formation and as a Core choice with the core only available to RG and successors. 
It seems to be working nicely so far - Should it not be done like this?

I see the issue with there currently being 3 kinds of detachments: Gladius, Talon and Scarblade
Maybe it could be changed to a generic name like: "Space Marine Detachement" with the demi company core choice as default and the other options being dependent on the chosen chapter tactics?
For example the librariius conclave can be removed as a Command option when RG are chosen and so on.
Or maybe the type of SM detachment can be chosen from a list a-la Chapter Tactics, in order to populate the list correctly.

Especially seeing as it was done this way for the AM codex and that there is a big change that we will be getting for of these chapter specific detachments down the road, it may be best to avoid multiple catalogues for future proofing

But the bottom line is - your catalogue, your choice :)

**Comment by amis92** [comment]
If I can chime in - I do not know the structure of SM catalogues, but I'd vote to leave three separate detachments (force types) but maybe, as with Tau and Farsight, make their Core/Command/Aux categories with different IDs. That way you don't have to hide selections, but rather add links to allowable choices under appropriate (new) categories. I'm not sure I made myself clear.

What I hope is achievable is to merge all Space Marine list flavors, excluding those with their own codex, into single file. For now, we'll have separate force types for new detachments. That will be cleared up with new BattleScribe version, which will allow defining force types in catalogues.

**Comment by ddarz** [comment]
Yep a single file sounds ideal! I will take a look at the Tau/Farsight setup
is there an ETA on the BattleScribe update by the way?

**Comment by amis92** [comment]
No. It's a long time. Probably Q2 2016. :/

**Comment by ddarz** [comment]
Closing this as all seems well with the changes for a while now. Also new BS version is in Alpha
