### ISSUE TITLE
[Tau/FSE] Mont'ka Farsight Enclaves rules state any Tau list can be FSE

### ISSUE THREAD

**Issue by ghost** [BSData/wh40k-7th-edition#1658]
In the Mont'ka FSE rules, it states that any Tau army list can be an FSE army, so any detachment, formation, CAD, etc. can be an FSE army (not just the Dawn Blade Contingent). I don't know the best way to do this, maybe a copy of each formation but with FSE equipment and rules only or maybe a flag of some sort that changes the available signature wargear to FSE items. The FSE rules seem to be the same as the original FSE rules otherwise (don't quote me on that).

**Comment by efalsken** [comment]
Look for an update coming soon that will remove FSE as an army choice and add it as a flag on any TE force.
