### ISSUE TITLE
[Anon] Eldar - FW - Corsairs IA11SE

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#1662]
**File:** Eldar - FW - Corsairs.catz
**Description:** _IA11: Doom of Mymeara_ updates are not included. Second edition is out.
- [ ] Unit updates/deletions
- [ ] New FoC
- [ ] Formations

**Comment by efalsken** [comment]
I plan on working on this one as soon as Mont'ka is done and released.

**Comment by Nidbits** [comment]
Hi
Any ETA on the a Corsairs update?
Thanks

**Comment by efalsken** [comment]
I'm working on it now and there is someone else who says they've got something ready. We will see, probably soon.

**Comment by ajs244** [comment]
I'm sorry to be so impatient, but do you have an updated ETA?

**Comment by efalsken** [comment]
The pull request is pending now. It's being peer-reviewed by the team and will probably be released sometime early tomorrow. It's good to have a second person just give it a once-over before dozens of people start reporting the same errors. But the work on it is complete.

**Comment by ajs244** [comment]
Thank you very much, again sorry to be such a bother. Happy New year btw

**Comment by sarukai** [comment]
Will this update support just the Corsairs in their own CAD/Corsair Fleet Raiding Company FOCs, or will it also add the Pale Courts Battlehost and the other new Core/Command/Aux/Support choices to the Eldar Craftworlds Warhost?

Thank you for all your work on this!

**Comment by efalsken** [comment]
Corsairs are their own force type. I toyed with the idea of adding them within the Eldar force, but it was unnecessary.

**Comment by sarukai** [comment]
Oh I totally agree with putting the Corsairs portion in a separate catalogue. I guess I was just wondering if you were also working on the rule updates for FW models and expansion of the Craftworlds Warhost for regular Eldar (the Pale Courts Battlehost and the other new Core/Command/Aux/Support choices), or if you knew if someone else was working on them.

**Comment by efalsken** [comment]
I will probably attempt to clean up Eldar and Pale Courts next.
