### ISSUE TITLE
Missing Items- Space Marines-Kauyon

### ISSUE THREAD

**Issue by servania** [BSData/wh40k-7th-edition#1663]
When selecting any of the new white scars formations using a formation detachment from Space marines WS scarblade Strikeforce, none of the new WS chapter relics are available to take and the special rules for the formations are not listed.

**Comment by servania** [comment]
after reviewing the updated code for Codex:Space Marines(2015) I can see that the above issues were fixed. Can we have a release on this please?

**Comment by amis92** [comment]
Release will be done in some time. There is a release windows per day, so it'll be available at longest tonight.
