### ISSUE TITLE
Question - Codex: Space Marines, Damocles Command Rhino

### ISSUE THREAD

**Issue by francoisbeaulieu** [BSData/wh40k-7th-edition#1667]
Hi everyone,

I'm looking for more details into the Damocles command rhino. From what I can tell, the source is IA2 (which I don't have access to). That would make it a ForgeWorld unit, no? Is it normal that it is available for selection even if "Show FW models" isn't enabled?

**Comment by ecrousseau** [comment]
It is a FW unit. IA2 says its a 0-1 HQ choice that does not occupy a force organisation slot and is available to Space Marines, Dark Angels, Space Wolves, Blood Angels, and a couple of FW detachments.

Given the above, it probably shouldn't show up if the user hasn't selected "Show FW models".

**Comment by francoisbeaulieu** [comment]
Then I would suggest someone tag this as a bug.
