### ISSUE TITLE
Craftworld Eldar - Seer Council

### ISSUE THREAD

**Issue by lacyj3** [BSData/wh40k-7th-edition#1678]
Iphone

Seer Council doesn't allow you to add Jetbikes.

**Comment by ecrousseau** [comment]
You need to select the "Skyrunner Seer Council" option at the topmost level of the formation.

**Comment by amis92** [comment]
@ecrousseau no reason for this to stay open. Invalid, needs-faq, deprecated etc (speaking of labels) should be closed immediately after being resolved to be such.

**Comment by ecrousseau** [comment]
Ok, no worries, I can do that in future. I wanted to give lacyj3 a chance to respond if I had misunderstood the problem. Could they still do that if I've closed the issue?

**Comment by amis92** [comment]
Sure. Although I did not understand your intention.

To block responses, there is separate option 'lock conversation', not sure if it's available to non-admins (right pane, bottom).

**Comment by ecrousseau** [comment]
Cool. To clarify, I wanted to make sure to **allow** responses, not block them. Anyways, closing this one. Thanks.
