### ISSUE TITLE
Space Marines - Red Scorpions - Magister Sevrin Loth

### ISSUE THREAD

**Issue by Carlson793** [BSData/wh40k-7th-edition#1684]
Within the past week, Magister Sevrin Loth has disappeared as an option for the Red Scorpions chapter. I've double checked to make sure all data stores are up to date. Chapter Tactics is toggled to Red Scorpions, and Show FW Models has all types selected. When loading a saved roster in which he appears, BattleScribe reports an error, and Loth is absent from the roster.

Files in use are:
Warhammer 40,000 7th Edition v43 by BSData Organisation
Space Marines: Codex (2015) v34 by Thommy Abbott (Senpai514)

**Comment by Ramises** [comment]
I too have experienced the same issue. 
There is also a second option to take Commander Culln for 165 points.

**Comment by ddarz** [comment]
Fixed in v35
