### ISSUE TITLE
C:SM Captain Solaq profile and plasma typos

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#1687]
**File:** Warhammer40K.gstz

**BattleScribe version:** 1.15.07

**Platform:** Windows

**Dropbox:** No

**Description:** Shadow Captain Solaq does not have a listed numerical profile with WS, BS, and so on. His rules are all there, but no actual profile. Also, (this encompasses almost every entry in the Space Marines) combi-plasma is spelled "compi-plasma" when you go into the Sergeant's entry in a Tactical Squad, Scout Squad, Devastator Squad, and Scout Biker Squad. In addition, the Captain, Librarian,  and Chaplain HQ entries all have the same issue when you scroll down to their wargear under the Combi-Plasma option.

To reproduce: Open a new list with CAD Detachment, select whatever squad/entry you want, scroll down to the Sergeant if their is one, and find the Combi-plasma entry. For Shadow Captain Solaq, doubleclick his entry and put him in the list, then mouse over his name until it shows you the entry details and note that there is no numerical profile.

**Comment by amis92** [comment]
I'm not sure what catalogue this refers to, but implicitly, I guess it's main C: Space Marines.

**Comment by ddarz** [comment]
I don't have immediate access to the Solaq's rules, anyone got his profile handy

**Comment by Sandtiger1982** [comment]
My apologies, yes this was Codex: Space Marines but also every other related Codex to Space Marines like Codex: Space Wolves and Codex: Dark Angels
