### ISSUE TITLE
New rules for Eldar,Doom of mymeara 2nd edition

### ISSUE THREAD

**Issue by Pertruabo** [BSData/wh40k-7th-edition#1693]
Holla mates
here goes the new updated rules for ELdar FW stuff from Doom of Mymeara 2nd edition,and also some addittions to the craftworld warhost detachment .

**\* link removed ***

**Comment by MrJFC** [comment]
pertruabo, any chance of the rest of the rules for the eldar? Ie Shadow Spectres, Bel-Anath?

**Comment by efalsken** [comment]
Using this to distribute scans of the rules is against the policy of this group. I have edited to remove any links to rules. I've got the rulebook from Forgeworld and am working on it.

**Comment by MrJFC** [comment]
Awesome. Sorry if I've caused upset.

**Comment by Pertruabo** [comment]
alright,sorry If I made some mistakes.Just wanted to help you guys out
