### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by jammedmoto** [BSData/wh40k-7th-edition#1697]
Hello,
Thought I might try and help out. Haven't done this before but am definitely willing to give it a try. 
Thanks,
Brit

**Comment by amis92** [comment]
Hey there! I'll invite you - you'll receive email, please accept it.

Don't forget to follow [Dev's Guide](https://github.com/BSData/bsdata/wiki/Developer-Guide) and check out our 40k wiki, including https://github.com/BSData/wh40k/wiki/Catalogue-Keepers

Cheers!

**Comment by amis92** [comment]
@jammedmoto Invitation was drawn back, because of no response. If you're still interested, please post in this issue again.
