### ISSUE TITLE
Codex: Space Wolves Wolf Guard Pack Leader bug

### ISSUE THREAD

**Issue by Sandtiger1982** [BSData/wh40k-7th-edition#1707]
Version 1.15.07 of Battlescribe.

The Wolf Guard Pack Leader in the Scouts cannot replace both the Bolt Pistol and Bolter as there is only one Weapons list for him.

To reproduce: Open a new CAD in the Space Wolves codex, add the Wolf Scouts and a WGPL to the unit, and look at the weapons you can replace his wargear with; note that there is only one list and you cannot replace the Bolter with anything.

--Sandtiger

**Comment by penguin20000** [comment]
I'm guessing this is like this in the data file because the Wargear list says "A model may replace his bolt pistol and/or Melee weapon with one of the following:"

Therefore the original author made it so the Bolter could not be replaced?

**Comment by Sandtiger1982** [comment]
I have my 7th edition Space Wolves codex open in front of me, and here's the relevant pieces from the Wolf Scouts page regarding their Pack Leader:

May upgrade one Wolf Scout to Wolf Guard Pack Leader...10 pts
Wolf Guard Pack Leader may take items from the Melee Weapons and/or Ranged Weapons lists.
Wolf Guard Pack Leader may take Melta Bombs.

My understanding given the lists and where WGPLs can also be used (Grey Hunters, Blood Claws, etc) is that this means that any WGPL is able to use whatever weapons he wants from the Melee and Ranged Weapons lists, and there's nothing preventing the Scouts one from having an identical loadout to a Blood Claw WGPL (especially as you can equip them with whatever you want to elsewhere).

Thank you for getting this fixed. :)

--Sandtiger
