### ISSUE TITLE
Adepta Sororitas - alter special/heavy weapons to fit new format

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#1708]
**File:** Adepta Sororitas.catz

**BattleScribe version:** 1.15.07

**Platform:** Windows

**Dropbox:** Yes

**Description:** Dominion points costs have not been updated to fit the new format - special weapon points costs all need to be increased by 13 points.

**Comment by hisop** [comment]
All sisters units follow the format off add weapons cost to squad it slipped my mind to re -arrange this as there were so many other things wrong at the time i will fix this now for all squads.

**Comment by timacbest** [comment]
This also seems to have been applied to Battle Sister Squads (e.g. adding a flamer to the squad has increased from 5pts to 17pts). Should this be the case? If so, can you state a reference to the rule for the point increase?

**Comment by hisop** [comment]
You cant "add a flamer to the squad" the entry states one sister may get a special weapon and there it states one model may exchange there boltgun for x. previously you had "5 sisters with boltguns + flamer + heavy flamer" as a 5 man squad, now you have "3 sisters with boltguns + 1 sister with flamer + 1 sister with heavy flamer". the points difference is just you are buying a sister 12pts + a flamer 5pts you need to reduce the number of bolter sisters you have selected (4 by default). this is only so the squad more accurately reflects the structure in the book, it was important in some squads as special weapons models cant always take the same options. EG: "any other model may take".

**Comment by timacbest** [comment]
Thanks for the clarification Hisop. T
