### ISSUE TITLE
Black Legion Chaos Space marines

### ISSUE THREAD

**Issue by demonwalker9** [BSData/wh40k-7th-edition#1710]
Under Chaos Space Marines if using Black Legion version, Units show as having the cost of Veterans of the long war without showing it on each model.  In addition, under Plague Marines the cost for veterans isn't factoring in for any Special weapon models.

**Comment by cartag** [comment]
The Black Legion index needs a lot of work. In the short term, you can access the whole of it in the regular CSM index, just select Black Legion under force options.

**Comment by cartag** [comment]
Black Legion and Crimson Slaughter catalogs have been deprecated. Information has been rolled into main CSM catalog.
