### ISSUE TITLE
Space Marines: Sternguard special ammunition and wargear 

### ISSUE THREAD

**Issue by zackguevara** [BSData/wh40k-7th-edition#1712]
The sternguard unit profile in the Codex: Space Marines is not showing the full wargear nor the profiles for the special issue ammunition.

Also, I'm not able to select a Captain w/ Chapter Master upgrade as my warlord.

**Comment by francoisbeaulieu** [comment]
I've never noticed any HQ with a warlord option under C:SM. Are they generally implemented? Which ones work?

**Comment by zackguevara** [comment]
I know you have to designate one model as your warlord (most often hqs). In the blood Angels codex every character has the option to select warlord. 

Regarding the sternguard, would it be possible to add the profiles for the special ammunition in their unit summary similar to the way the blood Angels sternguard have theirs? Thanks for the help, you guys are awesome.

**Comment by francoisbeaulieu** [comment]
Yes, many codices have warlord selectors, but the base space marines codex does not, AFAICT. I have no idea how much work adding that would entail.

**Comment by zackguevara** [comment]
Ah I see. Well thank you for the response, and thanks for your work on the files.
