### ISSUE TITLE
Codex Space Marines - Raptor Wing 

### ISSUE THREAD

**Issue by ecrousseau** [BSData/wh40k-7th-edition#1715]
When the Raptor Wing is selected as a stand-alone formation, there is a validation error when two  Stormtalon Gunships are selected (which is the proper number for the formation).

I reviewed the datafile, and the problem is that the 'increment maxSelections by 2' modifier should be 'set maxSelections to 2' instead. The Raptor Wing entry as an Auxiliary choice has the correct modifiers.

**Comment by ddarz** [comment]
Fixed and commited
