### ISSUE TITLE
Crimson Slaughter - Vrosh Tattersoul

### ISSUE THREAD

**Issue by sevrillion** [BSData/wh40k-7th-edition#1719]
I was not able to add Vrosh Tattersoul as an HQ to a Crimson Slaughter Combined Arms Detachment. As an inexperienced user I am not sure how to resolve this?

**Comment by cartag** [comment]
The Crimson Slaughter index needs a lot of work. In the short term, you can access the whole of it in the regular CSM index, just select Crimson Slaughter under force options.
