### ISSUE TITLE
Issues in the new Corsiar data file.

### ISSUE THREAD

**Issue by athelred** [BSData/wh40k-7th-edition#1720]
Balestrike Band

Name of unit is Balestrike not Battlestike
Felarch should be able to exchange lasbalster for a heavy weapon or two of the close combat weapon list.  Currently they can only select two from the close combat list.
Corsair with Dark Lance has the wrong points cost.  It should be 25
Corsair with Shuriken Cannon has the wrong points cost.  It should be 20

Cloud Dancer Band

Felarchs should be able to take different weapons.  Currently changing on changes all of them
Felarchs can exchange their brace of pistols for 2 items from the close combat list not one.

Reaver Band

Felarch should be able to exchange the lasblaster for Splinter Rifle, Shuriken Catapult, CCW and Brace of pistols, or up to two selections from the close combat list.

Malevolent Band

The unit should be able to take two special close combat weapons per 5.  Currently it only allows one

General

The Eldar missile launcher is missing the ap for starshot missiles in all entries.
Pulsar is missing the stat line for the vampire Raider
The FIre Prism is missing its points cost.

Vyper

The points cost for the Dark Lance, Starcannon, and Eldar missle laucher are incorrect for the secondary weapon.

This is what I have found so far.  Thanks for putting this list together,

**Comment by efalsken** [comment]
That's awesome! Great finds. I've fixed them all and submitting now.
