### ISSUE TITLE
SM: White Scars Relic Issue

### ISSUE THREAD

**Issue by noobzilla99** [BSData/wh40k-7th-edition#1723]
According to the Kauyon book, any model that access chapter relics may also select from relics of chogoris (or from relics of corax) however, this is seemingly not the case for tech marines in battlescribe, and tech marines do indeed have access to all chapter relics, so they should have access to those relics like a librarian or captain.

**Comment by noobzilla99** [comment]
Excuse my writing, the first sentence should read "can access chapter relics..."

**Comment by ddarz** [comment]
Commited
