### ISSUE TITLE
Bug Report: Imperial Knights Codex / War convocation

### ISSUE THREAD

**Issue by francoisbeaulieu** [BSData/wh40k-7th-edition#1725]
BattleScribe Version: 1.15.09
Affected platform: iOS
Codex release: v14

On iOS, when creating an oathsworn or household detachment, the "war convocation" variants of the imperial knights are available for selection. On Windows, they are not; you must correctly create a war convocation detachment in order to see them.

**Comment by francoisbeaulieu** [comment]
As a side note, it would be a nice improvement for the ForgeWorld LoW units to only be visible if an option allowing FW models is turned on, as is the case for the CAD.

**Comment by hisop** [comment]
Pertaining to your side note, i cant see an option to hide or show FW for the Imperial Knights codex and a CAD is unavailable to them, i assume you are adding them to another codex that supports this, i will make a new task for adding this enhancement to codex imperial knights.

**Comment by hisop** [comment]
I will test the IOS tonight it works as expected on android as well as windows hiding the war conv.

**Comment by efalsken** [comment]
In the Tau catalog, we just mark the FW options with `[FW]` in the name of the unit so that it is clearly designated. I think that is a lot clearer and easier for the users than completely hiding it.

**Comment by ghost** [comment]
@efalsken +1.
The rationale for hiding units in the Space Marine file is that there are simply so many units. Sanitizing the Knight file for the delicate eyes of those prudish about Forge World should be outside the purview of datafile authors.

**Comment by francoisbeaulieu** [comment]
@efalsken @capitaladot 
My personal opinion: It doesn't matter wether or not you include them by default or not, but behaviour should be consistent across catalogues whenever possible.

That said, since FW units are not allowed in all tournaments, it makes sense to be able to filter them out or, at least, easily distinguish them.

**Comment by amis92** [comment]
@francoisbeaulieu consistency, or rather the lack of it, is indeed our greatest sin - it's unfortunately one we are nigh unable to eradicate, due to the huge amount of files and authors involved, timeframes of releases, age and frequency of updates etc.

I am however fully convinced that tournaments are not our target and we should not lean on their style and rulings. Forge World is as much a part of the game as any Codex or Dataslate. Not all tournaments allow Super Heavies, some impose limits etc. What we can do, is ignore them local rulings.

Keep calm and Forge World on.

**Comment by hisop** [comment]
So i added the option to show them, should i reverse this to hide them in this case?

**Comment by francoisbeaulieu** [comment]
For the "show FW", I suggest we let @senpai514 make that call.

@hisop, were you able to replicate the war convocation issue on iOS?

**Comment by francoisbeaulieu** [comment]
Bump on the original issue. @hisop, any luck reproducing on iOS?

**Comment by hisop** [comment]
@cartag Did you say that this was a battlescribe bug for IOS? and itsn't there w work around?

**Comment by cartag** [comment]
It wouldn't affect this. The issue I found was in regards to (in|de)crementing maxInForce number in the catalog but it affecting the maxInRoster number instead. Really obscure bug, I'm not surprised it wasn't noticed earlier.

**Comment by hisop** [comment]
"I've found a similar issue already where it's not "show"ing properly by criteria, it doesn't hide by default and then show when the criteria is met. Instead I have to set it to always show, but hide if this criteria is not present."

**Comment by cartag** [comment]
Ah, that one. Yeah, with that, rather than setting everything to Hide, and only "show" if it has something selected, I have to set it to show always and "hide" if something isn't present. So if "Show Forgeworld" = 0, hide FW items. It doesn't seem to do it all the time though.

**Comment by hisop** [comment]
i'l give it a go.

**Comment by senpai514** [comment]
Forget to log in for a bit and I have a lot of reading to do to catch up on
this here.

**Comment by hisop** [comment]
Problem i have here is that there is not a negative for "instance of" i cant hide them if it Isnt a war conv. unless anyone has a suggestion will have to live with the IOS bug until battle scribe fix it?

**Comment by cartag** [comment]
In 1.16 there is a new condition of "Not Instance Of," so this can be corrected when the next version is released. Until then, no sweat.

**Comment by DrTobogganMD** [comment]
@hisop You can hide it if the parent force is instance of any valid option but war convo ... Means about 4 likes of Hide If, but it does work that way.

**Comment by hisop** [comment]
@Kohato Sounds like a good idea :P go for it! haha.
