### ISSUE TITLE
Bug report: Codex: Space Marines - Centurion SiegeBreaker Cohort formation

### ISSUE THREAD

**Issue by francoisbeaulieu** [BSData/wh40k-7th-edition#1728]
BattleScribe Version: 1.15.09
Affected platforms: iOS and Windows
Codex release: v36

The Centurion SiegeBreaker Cohort formation refuses to validate. It always states "must have 1 more selections for Centurion Assault Squad (minimum 2)" no matter how many squads are selected, and no matter how many centurions are in each squad.

**Comment by ddarz** [comment]
Submitted & Committed!
