### ISSUE TITLE
Corsair Cloud Dancer Band Felarchs are wierd

### ISSUE THREAD

**Issue by athelred** [BSData/wh40k-7th-edition#1731]
The corsair Cloud Dancer Band Felarchs are behaving strangely.

There are two issues which are probably the same issue underneath.
1. If there are multiple Felarchs added to the squad changing the jetbike weapon selection of of one changes them all.

Steps to reproduce:
Add two or more Felarchs to the squad.  
Change the Jetbike jetbike weapon selection of the first one
Note that all jetbike weapons for the felarchs change to the selected weapon

Expected behavior
Each felarch should be able to select jetbike weapons independently of the rest.
1. If a felarch is added after another felarchs jet bike weapon has been changed, you get odd unintended behavior.

Steps to reproduce
Add one felarch to the unit
Change the felarchs jet bike weapon to Scatter Laser
Add another felarch to the unit.

The second felarch will be listed as having a Scatter laser and shuriken Catapults.  If you select the second felarch, the radio buttons for the jetbike weapons selection has changed to check boxes, and both Scatter Laser and Shuriken Catapults are checked.  Unselecting either of the options turns the check boxes back into radio buttons, but changing the options after that has odd effects on the initially added felarch.

Expected Behavior
Each felarch should be able to select jetbike weapons independently of the rest.

**Comment by amis92** [comment]
That's quite interesting find, I think, in context of BattleScribe bug.

**Comment by efalsken** [comment]
Not a battlescribe bug. I left accidentally left (Collective) on the Jetbike weapon choices.

**Comment by amis92** [comment]
@efalsken to me, it is a bug. But honestly, the whole "Collective" thing is a huge bug ;D
