### ISSUE TITLE
Bug Report: Farsight Enclaves Detachment, Farsight's Bodyguards

### ISSUE THREAD

**Issue by SilverStrike16** [BSData/wh40k-7th-edition#1742]
I'm pretty sure the rule for this is in the Enclaves supplement, but basically Farsight is meant to be able to take one of his Eight in the place of a normal crisis bodyguard if he chooses. Not a case of taking The Eight, but where it's him as the commander with a crisis bodyguard unit, and either the ability to make one or more of the bodyguards, say, Torchstar, or to equip them to be equivalent to Torchstar. So if I wanted, I could roll Farsight, Torchstar and O'Vesa together as the Command Contingent. Currently there is no option to make this happen, as the bodyguard entry crisis cannot select signature systems from the Tau Empire codex.

I don't think this includes the Riptide or Broadside ones, but I don't remember fully.

Hopefully that makes sense, or I'm not imagining that?

**Comment by efalsken** [comment]
You remember correctly, in the old codex you could bring "Farsight's Bodyguards" and they were known as The Eight and you could bring as many of them as you wanted. That is no longer the case after Mont'ka was released. Feel free to continue to play it that way if you wish, but GW replaced those rules with the formation now known as The Eight: the only way to get any of them is to bring all of them.
