### ISSUE TITLE
[Anon] SM Black Templar Chapter Tactics bug

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#175]
Black Templars Chapter Tactics cant take crusader squads.

**Comment by Kangodo** [comment]
My fault, will fix this in the evening.

**Comment by Kangodo** [comment]
Yes, assigned.
Better make it this weekend, found out I made some more mistakes.

In a nutshell: I changed the Chapter Tactics to include the Forge-World Chapters.
The cat-editor didn't tell me that all those models now lost their link to the Chapter Tactic (weird) and now I have to re-do them for all units that are only pickable if you have a certain Chapter Tactic.
That includes Telion, Tigerius, Crusader Squads, etc.
Mea culpa, mea maxima culpa!

When I open the catalogue now, it DOES give me those errors.

**Comment by Kangodo** [comment]
Did it right away, sorry for the inconvenience.
Also released this to the public because it was quite a big mistake.
