### ISSUE TITLE
Tau Ghostkeel Support system upgrade

### ISSUE THREAD

**Issue by warshepard** [BSData/wh40k-7th-edition#1758]
The xv-95 Ghostkeel can take up to two support systems. The Vector retro-thrusters are not listed as an option for the xv-95 Ghostkeel.

**Comment by efalsken** [comment]
As per the codex in the list of ~~Signature~~ _Support_ Systems: Vectored Retro-thrusters have a little footnote (1) which states "may not be taken by .... Ghostkeel battlesuits".

_edit: signature->support ~amis92_
