### ISSUE TITLE
[Anon] Chaos Daemons missing Uraka the War Fiend (FW) and other FW-entries.

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#176]
Uraka, the War Fiend seems to be missing from the HQ slot.

**Comment by peterlyberth** [comment]
Unable to find any stats on him.

**Comment by Kangodo** [comment]
He's in Imperial Armour: Apocalypse.
If you don't have that, I could add him. In that case you can assign this to me.

Edit: None of those are added in the current file, it seems to lack FW-units.
At the moment I focus on adding FW to Blood Angels, but I could spare some time to add a single Daemon-HQ.
