### ISSUE TITLE
Bug Report: Farsight Enclaves army, Earth Caste Pilot Array for Riptides?

### ISSUE THREAD

**Issue by SilverStrike16** [BSData/wh40k-7th-edition#1762]
Correct me if I'm wrong, but I believe I'm correct that you can take the signature system in the Farsight book earth caste array for Riptide suits? It says models with suits only, and it synergizes well with them, and the Riptide in The Eight comes with one as standard. Shouldn't we be able to select this on normal Riptides? Though only one, of course. It works fine for crisis/commander suits, but Riptides can't take it.

**Comment by efalsken** [comment]
That all changed with Mont'ka.

**Comment by SilverStrike16** [comment]
Changed with Mont'ka how? The system itself, in Mont'ka, specifies it allows rerolls for the Nova reactor on a one, which means it's basically designed with riptides in mind. Even the fluff points that way.

**Comment by efalsken** [comment]
Even if it was designed for the Riptide, the rule, as written, does not specify that the Riptide can take it. Codex Tau entry for the Riptide does not allow Signature Systems and Mont'ka rule does not contain the same phrase that Codex FSE used to. O'vesa still has an ECA, but he is the only Riptide that can use the ECA now. Until GW releases an FAQ correcting this oversight. GW official answer is "play it however you like". But the Battlescribe data files have to stay true to what is printed in the book, not to change the rules or data to reflect what people _would like_ it to be.
