### ISSUE TITLE
White Scars - Scarblade Strike Force

### ISSUE THREAD

**Issue by Eldercaveman** [BSData/wh40k-7th-edition#1788]
Hi, 2 issues I've noticed with this detachment

When building a list using this detachment no options are available when you select Librarius Conclave.

No option to add the white scars relics from the Kauyon book.

**Comment by ddarz** [comment]
Hi I'm having trouble reproducing this
Could post the exact steps you take?

For example, I make a new WS Scarblade force and choose WS tactics
Then I add a Core (which includes the kauyon formations) and a auxilliary, in this case the conclave
In the armour options for each librarian, I see selections for the relics, including the WS librarian one.
See pic
![ws](https://cloud.githubusercontent.com/assets/3519161/12455774/dd9caed2-bf94-11e5-82a3-afbbb4367839.PNG)

**Comment by Eldercaveman** [comment]
New Roster

1850 points 

Force Type WS Scarblade Strike Force

Catalogue: SM White Scars Strike Force

(No option to choose tactics. Just says Show FW in the No Categorie section)

Core: Hunting Force (Fill out all min requirements, exchange Captain for Kahn and select a command squad)

Command: Strike Force Command, upgrade to chapter master

Command: Librarius Conclave, no options

Auxillary: Speartip Strike, min requirements.

**Comment by ddarz** [comment]
Ah there's your problem
The Standalone RG and WS catalogues have been deprecated and deleted
Try deleting the catalogues and re syncing :)
The main SM catalogue has all you need!
