### ISSUE TITLE
Chaos Helbrute Champion

### ISSUE THREAD

**Issue by Hiskrtapps** [BSData/wh40k-7th-edition#1803]
With solution of the ticket https://github.com/BSData/wh40k/issues/1786 now one Hellbrute in the Helfist Murderpack formation is recognized as Hellbrute Champion.

But it is not possible at the moment select the Helbrute Champion as army Warlord.
I think warlord selection is missing.

It is possible to add it?

Thank you
Giampaolo

**Comment by cartag** [comment]
It'll get added, for right now just pretend there's a checkbox you checked.

**Comment by cartag** [comment]
There will likely be a bit of a delay as I'm working on alpha testing the new version of BS.

**Comment by cartag** [comment]
Try setting it as your Primary Detachment. If you select that, you should be able to set it as Warlord.

**Comment by Hiskrtapps** [comment]
Sorry Cartag but I don't know how to set the formation as Primary Detachment.
Where can I found the option?

Giampaolo

**Comment by cartag** [comment]
That's my own damn fault for putting in the modifier but not testing to make sure everything else is there. It'll have to wait for the next version.

**Comment by Hiskrtapps** [comment]
No problem! I can wait without any problem.
:)

Thank you for your work!
