### ISSUE TITLE
Bug report: Chaos Space Marines - Codex.catz

### ISSUE THREAD

**Issue by Crystal1985** [BSData/wh40k-7th-edition#1813]
**File:** Chaos Space Marines - Codex.catz

**BattleScribe version:** 1.15.07

**Platform:** Windows

**Dropbox:** No

**Description:** Points/Equipment issues
1. Noise Marines Champion
   Selecting a power weapon costs 15 points, selecting the specific type of power weapon adds an additional 15 points for a total of 30 points. The total cost should be 15
2. Havocs
   Including flakk missiles counts as an additional heavy weapon for the unit instead of an option for Missile launcher
3. Chaos Space Marines Troops
   Profile does not include frag and krak grenades

**Comment by cartag** [comment]
4 - Noise Marines not including frag and krak grenades
