### ISSUE TITLE
Bug Report - Orks: Codex (2014) - Zhadsnark's warbikers

### ISSUE THREAD

**Issue by francoisbeaulieu** [BSData/wh40k-7th-edition#1817]
Platform: iOS, PC

Roster doesn't validate when using Zhadsnark Da Rippa + Zhadsnark's Warbikers (Troops) in a Combined Arms Detachment. It does validate when using them in an Ork Horde detachment.

warning given: "Combined Arms Detachment has 2 too many selections of Zhadsnark's Warbikers. (Maximum 0)

**Comment by afraeve** [comment]
It works as expected for me. There's nothing attached to the units which is affected by the choice of detachment either. So long as Zhadsnark is your warlord, you may take his Warbikers.

**Comment by francoisbeaulieu** [comment]
You hit the nail on the head; I had neglected to select Zhadsnark as my warlord. Mind you the validation message was quite cryptic...
