### ISSUE TITLE
Blood angel codex (2014) missing shared rules

### ISSUE THREAD

**Issue by u02dah4** [BSData/wh40k-7th-edition#1821]
[Blood_Angels_Codex_(2).zip](https://github.com/BSData/wh40k/files/114847/Blood_Angels_Codex_.2.zip)

Catz file with shared rules added in zip.

**Comment by amis92** [comment]
I'm sorry, but it is not the correct way to send contributions. Please either use GitHub pull requests, or try to use web upload through http://battlescribedata.appspot.com/#/repo/wh40k (it doesn't always work)
