### ISSUE TITLE
Eldar Craftworlds: Warp Hunter Squadron (FW)

### ISSUE THREAD

**Issue by Itsacon** [BSData/wh40k-7th-edition#1824]
The Warp Hunter currently only allows for a single Warp Hunter (should allow up to three).

It also has the wrong point cost. Is 145, should be 185 per Warp Hunter.

**Comment by hisop** [comment]
I believe All of the IA12 stuff is being updated currently by @efalsken as part of a complete re-do of craft-worlds eldar. So this isnt a bug it is just the old details yet to be updated.

**Comment by hisop** [comment]
#1727

**Comment by efalsken** [comment]
duplicates #1727
