### ISSUE TITLE
Eldar Craftworlds: Eldar Wraithseer (FW) 

### ISSUE THREAD

**Issue by Itsacon** [BSData/wh40k-7th-edition#1825]
This model has the wrong point costs for most weapons. They should be:
D-Cannon: 60 (currently 40)
Missile launcher: 25 (currently 30)
Scatter laser: 15 (currently 20)
Shuriken cannon: 10 (currently 15)
Starcannon: 15 (currently 20)

The stats are also wrong, they should be:
WS4, BS4, S8, T8, W4, I4, A3, Ld10, Sv3+/5++
(currently 5,4,10,8,4,4,3,10,3+/5++)

And finally it should have the Independent Character SR.

**Comment by hisop** [comment]
I believe All of the IA12 stuff is being updated currently by @efalsken as part of a complete re-do of craft-worlds eldar. So this isnt a bug it is just the old details yet to be updated.

**Comment by hisop** [comment]
#1727

**Comment by efalsken** [comment]
duplicates #1727
