### ISSUE TITLE
NEW- Dominus Maniple Formation - Start Collecting! Skitarii Box

### ISSUE THREAD

**Issue by Flashpoint-** [BSData/wh40k-7th-edition#1826]
Hello, 
Anyone working on or add the Dominus Maniple Formation yet when can it be added do you guys have the rules for it, I do if you need them. Keep up all the good work you guys & gals. Everyone is doing an outstanding job at keeping up on the rules it's really great  thank you!

**Comment by hisop** [comment]
Hello, unfortunatly i don't have the rules at the moment, lately i have been looking after skitarii and cult mechanicus. feel free to email me the details at hisop@hotmail.co.uk and i will add them today :) (it is against the rules to post them here i believe).

**Comment by Flashpoint-** [comment]
Dominus Maniple - 1 unit of Vanguard (and Vanguard only, so no Rangers here), 1 unit of Dunecrawlers, 1 Tech-Priest Dominus.

Special Rules:
Targeting Data Upload: At the start of your shooting phase, pick an enemy unit within 18" and line of sight of the Dominus. For the rest of the shooting phase, units from this Maniple have their weapons become Twin-linked against the enemy unit you picked.

**Comment by francoisbeaulieu** [comment]
Hmmm, so the kit and the formation combine models from both Adeptus codices. War convocation as well... I wonder if they mean for the codices to be combined into a single catalogue? It would allow for a CAD including Skitarii, which is not currently possible AFAICT. (No Skitarii HQs, right?)

**Comment by hisop** [comment]
Yeah, they are releasing a book combining both + some extras. will make my life easier... http://natfka.blogspot.co.uk/2016/01/full-admech-codex-incoming-new-flyer.html

**Comment by Flashpoint-** [comment]
Can't we just make this a formation on it's own?
Attached to Mechanicus Codex because the formation is called ( Dominus Maniple Formation )

**Comment by OftKilted** [comment]
This was added as a Skitarii formation, as all the troops/models other than the HQ (which Skitarii don't really have) are Skitarii.

**Comment by Flashpoint-** [comment]
Is this available yet or is there a particular way to find this formation?

**Comment by cartag** [comment]
It's been added, there's just not been a release push for it yet. You don't need to create any more issues requesting it.

**Comment by Flashpoint-** [comment]
Sorry about that team

**Comment by OftKilted** [comment]
@Flashpoint- The formation can be viewed on IOS devices as a Formation when using the Skitarii codex. (IOS has a bug that doesn't properly hide items that are hidden by default.)

**Comment by Flashpoint-** [comment]
Cool thank you :)
