### ISSUE TITLE
Imperial Strongpoint missing from Fortifications and Stronghold Assault

### ISSUE THREAD

**Issue by mdmagnusson** [BSData/wh40k-7th-edition#1834]
The "Imperial Strongpoint" does not show up in the "Fortifications and Stronghold Assault - Fortification Detachment". Was there before, not sure when it broke but does not appear with the latest data files.

**Comment by OftKilted** [comment]
Able to Replicate:
Fortification Detachment > Fortifications and Stronghold Assault (2013)

No 'Imperial Strongpoint', just an 'Aquila Strongpoint' (Was the wording changed?)

**Comment by francoisbeaulieu** [comment]
No, they are different things. An imperial strongpoint is a sort of formation of fortifications; You can build it here by selecting each piece independently. I also think there used to be a catalogue entry for it, but I don't see it anymore. I may be remembering wrong...

**Comment by penguin20000** [comment]
It's a unit/formation of buildings in the stronghold book. It's definitely not in the data files as I checked before assigning it to myself.

I'll get it added at some point soon

**Comment by francoisbeaulieu** [comment]
@penguin20000 please see https://github.com/BSData/wh40k/issues/1806. I'm pretty sure it was there before, I remember seeing it and I make reference to that it this issue...

**Comment by penguin20000** [comment]
Strange, I'll take a look at the history for the catalogue see if i can see where/why it vanished.
