### ISSUE TITLE
Question/possible bug report - Space Marines Codex - Various

### ISSUE THREAD

**Issue by francoisbeaulieu** [BSData/wh40k-7th-edition#1840]
Hi,

When selecting the Red Scorpions chapter tactics, I can't seem to find a way to apply the "Purity above all" rule and select a Narthecium for my tactical squad sergeants. The "Feels no pain" special rule does not appear either. Anyone know if this is implemented?

Furthermore, I have noticed that when selecting an apothecary for a command squad, that the rules for "Feels no pain" are also not listed in the special rules section. 

Also, if I select "The Armour Indomitus" for a space marine librarian, it does not appear in it's profile and the associated rule is not indicated anywhere.

Tested on PC and iOS versions.

**Comment by francoisbeaulieu** [comment]
Just tested the new catalog, and there are two issues:

1- Selecting the narthecium does not add the description of the  "Feels no pain" special rule to the special rules section, whether you select it for the Apothecary or the RS tac sarge.

2- This was to be expected; on iOS, due to the known "hide/show" bug, the narthecium is shown for all tac sarges, not just Red Scorpions.

**Comment by ddarz** [comment]
Just to double check before I work on this, is there a "best practice" to tie the rule to the profile?
Thanks:)

**Comment by hisop** [comment]
Use the "if "chatpter tactics red scorpions = 0 hide" otherwise it will break on IOS as the hide then show breaks its better to show then hide >.<

**Comment by ddarz** [comment]
Hello
I have fixed point 2 above, but not sure about point 1. What's the best way to add a rule entry to the profile of a piece of wargear (e.g. the Narthecium or the omniscope)

**Comment by DrTobogganMD** [comment]
@ddarz - What's still broken for this - you mentioned your pull was a partial fix.

**Comment by ddarz** [comment]
Hi
It's not broken per se, just haven't fixed point one from the above comment - namely how to add a rule entry to a piece of wargear, in this case Feel No Pain to the Narthecium
otherwise it's quite functional

**Comment by DrTobogganMD** [comment]
The correct way would be to have a shared entry linking to the Narthecium and the FNP rule, but the way C:SM is set up, that's not possible right now.  It's something i'm working on fixing in the overhaul I'm doing (Cleaning up and optimizing).

For now I just added it to the Sergeant's entry when selecting it.  Pushing that now along with another fix to bikes I forgot earlier today.
