### ISSUE TITLE
Bug Report: Chaos - Khorne Daemonkin.catz

### ISSUE THREAD

**Issue by rarisnrovers** [BSData/wh40k-7th-edition#1842]
Chaos Lord has default toughness 5 instead of 4. Looks like the Juggernaut of Khorne upgrade has no condition on the T+1 for select and is being applied all the time.

**Comment by OftKilted** [comment]
The profile being referred to is the wrong profile and is the Chaos Lord (Chaos Bike) profile. (The bike gives you the +1 toughness) If you select 'Chaos Bike' as 'Special Issue Wargear' it then removes the +1 toughness, and gives the standard 'Chaos Lord' profile.

**Comment by rarisnrovers** [comment]
Shouldn't that be the opposite then? Why would chaos lord without bike have 5, then you add the bike to get back to 4?
When you add Chaos Lord from roster shouldn't it be standard infantry version?

**Comment by OftKilted** [comment]
Yep, it should be the opposite. It's a check reverse @cartag can take a quick peek at it. Shouldn't be hard to fix.

**Comment by rarisnrovers** [comment]
Awesome, so right bug wrong reasoning. Thanks for the info!

**Comment by cartag** [comment]
I'm showing default Chaos Lord as being T4, with bumping to T5 if it has either 1 chaos bike or 1 juggernaut. What version of the data file are you running? V51 should has the proper T listed.

**Comment by rarisnrovers** [comment]
I'm on BS 1.15.07 Khorne Codex V51. Adding Chaos Lord from Codex: Khorne Daemonkin - CAD

**Comment by rarisnrovers** [comment]
![chaoslordbug](https://cloud.githubusercontent.com/assets/17150817/12932449/a81d4746-cf37-11e5-9eb0-7bc215e853d0.JPG)

**Comment by cartag** [comment]
I just deleted my data file for KDK and resynced from the repo and it's not showing T5 by default, but T4 and no bike.

![image](https://cloud.githubusercontent.com/assets/4388344/12932597/bee22c40-cf40-11e5-8d2a-78754ba427f4.png)

**Comment by rarisnrovers** [comment]
Looks like a delete and sync does the trick. Not sure why it wouldn't pick up the changes from a normal sync. Does it only do incremental updates based on v# on the .catz? Maybe an update without an incremented version?
At any rate it's fixed now, thanks for the help.

**Comment by cartag** [comment]
There wasn't any incremental version uploaded, what happened was I uploaded v52 and never noticed that I didn't increment the version number. So the next version being uploaded will be v53 instead. My mistake.
