### ISSUE TITLE
Codex:Chaos Space Marines - Chosen are selectable as troop choices without Abaddon in a primary detachment

### ISSUE THREAD

**Issue by OftKilted** [BSData/wh40k-7th-edition#1845]
p.92 "In a primary detachment that includes abaddon units of chosen are troop choices instead of elite choices." 
Validated with Crimson Slaughter 'Selection' and 'Vanilla' selection. 
Selecting the Black legion supplement may also allow chosen as 'troops'.

**Comment by cartag** [comment]
I'm trying it right now and the only way Chosen are showing as troop choices are if Abaddon is in the roster or if it's Black Legion. What version of the data file are you using?

**Comment by OftKilted** [comment]
Are you working in 1.16, or 1.15?

**Comment by OftKilted** [comment]
Looks like I had old data :+1: 
I'm unable to reproduce after updating.

**Comment by cartag** [comment]
I keep my data separate, 1.15 for production, 1.16 for dev. Anything mentioned on this repo is going to be production data, 1.15.
