### ISSUE TITLE
[Anon] Farsight Enclaves - Commander Team SigSystems

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#185]
Hello.

FARSIGHT’S COMMANDER TEAM > Options & Equipments > Signature Systems

Allowing to both Farsight Enclave Supplement and latest GW FAQ, Crisis in FARSIGHT’S COMMANDER TEAM pick their signature systems from Tau Empire Codex, not Farsight Enclave Signature Systems.
The latest data files does not allow this, and force to use Enclave Signature Systems.

**Comment by amis92** [comment]
Right now I can't check what really is the problem, but Farsight's Commander Team has no choice at all. They just _have_ Sig. Systems from Tau Codex.

**Comment by Kangodo** [comment]
He is probably talking about the Bodyguards.
According to the book: 
"Any character in your army that may select Signature Systems may not select from those
listed in Codex: Tau Empire, but may instead select from the Signature Systems of the
Farsight Enclaves (opposite), at the points cost shown."
It seems like that Signature System only applies to characters and Riptides.

Which means that Bodyguards should have access to the normal signatures.

**Comment by amis92** [comment]
I don't feel there is anything but cheating in this interpretation. Clearly having both grups available in one detachment isn't intended. I don't want to play with RAW vs RAI. I'm feeling responsible for this catalogue, and it's easy enough to modify on your own. I won't change it until some Amendment is made.
