### ISSUE TITLE
Pinion Battle Demi Company missing Scouts

### ISSUE THREAD

**Issue by Ramises** [BSData/wh40k-7th-edition#1850]
Hello in both iOS and Android versions of BS Pro the formation Pinion Battle Demi Company for a standard Space Marine chapter using any Chapter Tactics other than Raven Guard is missing the select any combination of 1-5 Scouts or Scout Bikes.

Thanks for your time and I really enjoy your work.

**Comment by OftKilted** [comment]
The Pinion Battle Demi-Company is explicitly a 'Raven Guard' formation.

**Comment by ddarz** [comment]
Will double check if the pinion can be taken outside of a talon strike force. if so it can be taken with other tactics i think?

**Comment by Ramises** [comment]
In Kauyon, page 214. 
I see where my confusion comes from.
The formation section of that page states that any Space Marine chapter may use the formations.

**Comment by OftKilted** [comment]
Ahh, I don't have that page. Just the formation. Interestingly there are multiple non RavenGuard SM commanders that can be taken as HQ as part of the formation.

**Comment by Ramises** [comment]
So I can assume then that the Detachment is unique to the given Chapter, And the formations are universal with Codex Adeptus Astartes

**Comment by OftKilted** [comment]
Let's let @ddarz look into it. Especially given the minor restrictions on the formation.

**Comment by ddarz** [comment]
bingo! tsf exclusive, pinion no. will fix!

**Comment by Ramises** [comment]
TSF?

Damn I need to learn these acronyms :(

**Comment by OftKilted** [comment]
Ravenguard Talon Strike Force

**Comment by ddarz** [comment]
Fix done, let me know if anything else comes up :)
