### ISSUE TITLE
Codex Astartes: Librarious Conclave 

### ISSUE THREAD

**Issue by Ramises** [BSData/wh40k-7th-edition#1851]
I ran into an issue where I was able to select Magister Sevrin Loth in Chief Librarian Tigerus stead. 
Is this intentional? 
Rules as written only Tigerus is eligible for the Librarious Conclave.
I hope this is intended :)

**Comment by ddarz** [comment]
Were red scorpion tactics chosen?

**Comment by Ramises** [comment]
Yes, Red Scorpions were selected

**Comment by ddarz** [comment]
Hmm, that sounds as intended - based on FW responses that allow FW characters to take appropriate slots. Loth is a librarian, so sounds about right.
As it is not RAW in the GW codex, make sure your group is cool with it first I'd say :)

(Keep in mind that GW will never acknowledge and FW character in a GW publication. An official word has to come from FW. So Caveat emptor )
