### ISSUE TITLE
[Join Request] Request to assist with catalog building/correction

### ISSUE THREAD

**Issue by OftKilted** [BSData/wh40k-7th-edition#1854]
I have prior experience with catalog building (BS v1.13) And would like to assist.

**Comment by hisop** [comment]
-I vouch for @OftKilted he has been contributing, and is going to go over the DE bugs i temporarily assigned to myself.

**Comment by amis92** [comment]
I think I remember @OftKilted back from randomhit forums, but I may be wrong. :)
