### ISSUE TITLE
[Anon] Adepta Sororitas Repressor extra armour

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#186]
Repressor extra armor is listed as costing 15 points. It should be 10 per the IA 2 second Ed book.

**Comment by Sandy756X** [comment]
This has come up before.  The page on Forgeworld's site still lists it as being 15 points.  

http://www.forgeworld.co.uk/Downloads/Product/PDF/r/RepressorFAQversion1P.pdf

**Comment by Viper666-Qc** [comment]
the pdf faq is outdated. IA2v2 is the good one.

**Comment by amis92** [comment]
@Millicant I think that's true what **viper666** said. That pdf was made as an update to 6th ed, 2 years ago. IA2 SE is newer indeed. Of course that's poor maintenance on FW's part, nonetheless Extra Armour should be 10pts.

**Comment by nekogunner** [comment]
Sorry, I originally submitted this report. Forgot to follow up until now. :-)

The IA2 SE is newer and states on page 239 that it is 10 points.

Forgeworld seems to not take down many of their PDF rules/updates when they become outdated.
