### ISSUE TITLE
The Blackmanes - Free Drop Pods

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#1870]
**File:** Space Wolves - Codex.catz

**BattleScribe version:** 1.15.07

**Platform:** Windows

**Dropbox:** No

**Description:** Wulfen - Wulfen have the option to take a Stormwolf as dedicated transport. This is missing in their entry.

Formation: The Blackmanes - Any unit that has the option to take a drop pod can do so for free, only paying for upgrades. Points are not being deducted from the list when you add drop pods to units that are able to take them.

**Comment by MasterSlowPoke** [comment]
I fixed the dedicated transport issue. However, I'm not too sure how to do The Blackmanes drop pods. I can't find a way to set a modifier that applies only when it's taken in a certain formation.

**Comment by JusticarGames** [comment]
I'm new to this, but I've updated my data this morning and do not see a option to take a transport for the Wulfen if this fix has already been applied.

**Comment by MasterSlowPoke** [comment]
We haven't done a release since the issue has been raised - the fix is in the code line and will be in the next release. I just want to see what other bugs shake out.

**Comment by JusticarGames** [comment]
Awesome, I figured that is how this worked. I will keep messing around with list/formations and report things as they are needed. You guys are awesome!

Just for clarification the formation allows any unit that can take a drop pod for dedicated transport, may do so for free..only paying for upgrades (beacon, etc).
