### ISSUE TITLE
Space Wolves - Missing Profiles

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#1873]
**File:** Space Wolves - Codex.catz

**BattleScribe version:** 1.15.07

**Platform:** Windows

**Dropbox:** No

**Description:** Wulfen does not show model stats, or Stormfang Autolauncher stats.

**Comment by Raek0ne** [comment]
Same issue, screenshots attached
![wulfen](https://cloud.githubusercontent.com/assets/17262819/13065330/4ae789a0-d429-11e5-9396-9c8cb8e52b78.png)
