### ISSUE TITLE
Succubus cannot select Djin Blade or Wych Weapons

### ISSUE THREAD

**Issue by phantam23** [BSData/wh40k-7th-edition#1876]
The Succubus is unable to select the Djim Blade or Wych Weapons as it states that she has too many melee weapons. She cannot unselect pistols or melee weapons to rectify this.

**Comment by hisop** [comment]
I would delete your data and do a full update in (v19) DE there is an option to remove the weapon:
![image](https://cloud.githubusercontent.com/assets/7855347/13075907/825b59b6-d4a6-11e5-82eb-0ed29128189d.png)

**Comment by phantam23** [comment]
That's odd. I don't have any such option even after redownloading multiple times. If it makes a difference I'm using the mobile version.

**Comment by hisop** [comment]
Ahh i see on android, it has filtered out the option as the "none" selection is not enforced, looking at it now. platform makes a massive difference due to the UI change. :)

**Comment by hisop** [comment]
I can fix this but it means that at default, the succubus will have no weapons, causing a validation error until you add some. is that acceptable to you?

**Comment by hisop** [comment]
Found an alternate method i will re-do this now. thanks goes to  @cartag

**Comment by phantam23** [comment]
Hi there. Sorry to say but there still doesn't seem to be an option to remove weapons.
Thanks alot.

**Comment by amis92** [comment]
@phantam23 that's 'cause there has not been any release since fix. So you'll have to wait a bit more 'till we release next fix batch. :)
