### ISSUE TITLE
Space Wolves - Missing Datasheets

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#1881]
**File:** Space Wolves - Codex.catz

**BattleScribe version:** 1.15.07

**Platform:** Mac

**Dropbox:** Yes

~~**Description:** Hello, Spacewolves , the only Core Choice in the the Wolf Claw Strike Force is "The Blackmanes". Is there a bug, or are the other Core Choices simple not Ready yet ? :)~~

**Comment by OftKilted** [comment]
Able to replicate in IOS with current catalog

**Comment by MasterSlowPoke** [comment]
Added the missing core choices. Still missing Krom, the new Iron Priest, and need to move Herald Deathwolf to Shared entries so he's a choice for the Greatpack/Deathwolves.

**Comment by dragongame** [comment]
Some advantages are also still missing, see #1898

**Comment by Gnofry** [comment]
~~Auxiliary choices are not implemented completely. Some are not created (The Curseborn, Fangs of the Tempest) and others are not linked to the auxiliary type (Spear of Russ, Wolfkin, etc.).~~

**Comment by hisop** [comment]
Will strike-though as i work.

**Comment by hisop** [comment]
rest will be handled in #1901
