### ISSUE TITLE
Datasheet Space Marine HQ Command Tanks

### ISSUE THREAD

**Issue by Flashpoint-** [BSData/wh40k-7th-edition#1883]
I can't find this formation I have the PDF to put the rules up if you need it let me know.
Thanks all keep up the great work!

**Comment by penguin20000** [comment]
The command tanks appear under the HQ section for a regular Combined Arms Detachment. Not sure if it has the correct formation rules though.

**Comment by hisop** [comment]
@Flashpoint- if you send the rules in question to me at hisop@hotmail.co.uk i will check but otherwise im not sure what exactly you are referencing.

**Comment by penguin20000** [comment]
@hisop they're already there i believe under HQ in the CAD

I think all the rules are attached, I'll dig my datasheet out and check.

**Comment by hisop** [comment]
Closing this if there is no rules provided to contradict the way it is handled now.
