### ISSUE TITLE
Dominus Maniple Formation - from the Start Collecting! Skitarii Box

### ISSUE THREAD

**Issue by Flashpoint-** [BSData/wh40k-7th-edition#1884]
MISSING FORMATION
Can't we just make this a formation similar to the War Covocation Formation?
Attached to Mechanicus & Skitarii Codex because the formation uses units from both Codex.

Rules -
Dominus Maniple - (SKITARII) 1 unit of Vanguard (and Vanguard only, so no Rangers here), 1 unit of Dunecrawlers, (MECHANICUS) 1 Tech-Priest Dominus.

Special Rules:
Targeting Data Upload: At the start of your shooting phase, pick an enemy unit within 18" and line of sight of the Dominus. For the rest of the shooting phase, units from this Maniple have their weapons become Twin-linked against the enemy unit you picked.

**Comment by cartag** [comment]
This has been added. Issue #1826 has been resolved, you'll have to wait for the next release.
