### ISSUE TITLE
Bug Report: Chaos Space Marines - Codex.catz

### ISSUE THREAD

**Issue by Dragonan** [BSData/wh40k-7th-edition#1889]
**File:** Chaos Space Marines - Codex.catz

**BattleScribe version:** 1.15.07

**Platform:** Android

**Dropbox:** No

**Description:** Typhus's special ability "Destroyer Hive" is worded in a confusing way, using "models" in place of "units". This wording made it seem that the ability does N wounds to each model, not N wounds in total. Here's a corrected version, with the wording from the real print codex:

> Once per game in any assault phase Typhus can use the hive instead of attacking.
> At the start of Typhus's initiative step, place a Large Blast marker over Typhus (doesn't scatter). 
> All ~~models~~ **units** suffer a number of hits equal to the number of models **from their unit that are** at least partially covered by the template.
> These hits are S4 AP2 and Ignores Cover. This attack does not affect Typhus.

**Comment by hisop** [comment]
I can confirm the wording.
