### ISSUE TITLE
Plague Ogryns

### ISSUE THREAD

**Issue by BennScottHill** [BSData/wh40k-7th-edition#1890]
Hi new to this, 
I noticed that plague ogyrns are no-where in the list I have, maybe I've missed it or done something wrong.
In the Apocalypse II book with their rules, it states that they can be in a renegades army (obvs) but also can be in a chaos space marines army if they have 1 squad of plague marines.

**Comment by hisop** [comment]
The apocalypse 2 book has been superseded by IA:13 The lost and the Damned. And also there is an alternate lost and the damned list in The new Seige of Vraks 2015. "Plague ogryns no longer exist and are now "Renegade Ogryn Brutes" dedicated to nurgle.

**Comment by BennScottHill** [comment]
Ah shit, been meaning to get that new book ....Ok thanks a lot

**Comment by hisop** [comment]
No problem.

**Comment by hisop** [comment]
If you want to "compare" the lists provided in the two sources i listed above email me at Hisop@hotmail.co.uk and i will help you out.
