### ISSUE TITLE
Astra Militarum - Codex.catz

### ISSUE THREAD

**Issue by peterprogrammer** [BSData/wh40k-7th-edition#1893]
Noticed minor point value issue with the Astra Militarum - Company Command.

When selecting the Company Command squad, if you add Camo Gear (for veterans)  or Carapace Armor (also for veterans) the points are listed at 10Pts each. Since this is only for the veterans and not 
the commander himself, it should be 8Pts. (2pts per equipment x number of veterans which is 4)

If it matters, I selected the "Combined Arms Detachment"
Thanks.

**Comment by ecrousseau** [comment]
I can't replicate this. Both of the choices are set to "2 points per selection of Veterans" rather than a fixed value - are you sure you haven't added additional veterans to the squad?

**Comment by peterprogrammer** [comment]
Actually, it appears someone fixed the issue within 2 hrs of my posting the above issue.
Awesome response time folks... I'm very impressed...
This issue can be closed.
Thanks.

**Comment by cartag** [comment]
The Astra Militarum data file hasn't been updated in 10 days. I'm guessing your device updated the data within two hours of you posting.
