### ISSUE TITLE
Astra Militarum: add  The Armoured Shield Formation

### ISSUE THREAD

**Issue by Thairne** [BSData/wh40k-7th-edition#1908]
Said formation is currently missing from the file. Comes with the new Start Collecting! Astra Militarum box.
Can provide the Formation Datasheet if necessary.
I got a friend into playing 40k and, ofc, want to get him to use Battlescribe too, so missing that formation is a bit cumbersome when getting him to understand the game at all.
If there is no current maintainer for the file, I can do it myself, but I'd figure I'd ask first.

**Comment by hisop** [comment]
Feel free to do it yourself, or email the data to me at hisop@hotmail.co.uk and i will do so.

**Comment by Thairne** [comment]
Mail was sent!

**Comment by hisop** [comment]
Does it specify the battle tank? or can it be any leman russ?

**Comment by cartag** [comment]
If it's like the Khorne Daemon one, it has to be the battle tank. The KD SC box has a Blood Throne which could be built as a Skull Cannon. The Warscroll Battalion states it has to be the Blood Throne.

**Comment by hisop** [comment]
the scroll states "Leman russ" there is no such tank there is a "leman rus battle tank" a "Leman russ Vanquisher" etc etc
![image](https://cloud.githubusercontent.com/assets/7855347/13400090/17d9d556-defe-11e5-8447-aff7c9156675.png)

**Comment by cartag** [comment]
My mistake. Can you tell I don't play IG? I'd say any Leman Russ would work in that case, given how it's worded.

**Comment by hisop** [comment]
I agree, the gitter is less unanimous. :P
