### ISSUE TITLE
Crisis Suits should require Bonding Knife in an FSE detachment.

### ISSUE THREAD

**Issue by DrTobogganMD** [BSData/wh40k-7th-edition#1910]
When using FSE option, the Tallissa bonding knife rule populates, stating all units that can take bonding knife, must do so.

This enables a clause in the shared entries of troops that make Bonding Knife required.  This clause is not present in Crisis suits.  Meaning that after choosing FSE - Crisis Suits as troops do not require Bonding Knife when they should.

**Comment by DrTobogganMD** [comment]
#1905 is the related pull request that I thought would fix this.

**Comment by efalsken** [comment]
Thanks. I reviewed it closer and after reproducing the issue described above, approved the Pull Request. The terminology of the raw XML threw me off.

**Comment by DrTobogganMD** [comment]
Ah, np - I could've explained it better in my pull as well - thanks for
taking another look! :)
