### ISSUE TITLE
[Anon] Bug report: Chaos Daemons

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#1911]
**File:** Warhammer40K.gstz

**BattleScribe version:** 1.15.07

**Platform:** Android

**Dropbox:** Yes

**Description:** MurderHorde formation has no restrictions on the Herald of Khorne in regards to taking a Blood Throne. 
Currently I am forced to take a Blood Throne when I should be able to take either a Blood Throne or Juggernaut

**Comment by Ramises** [comment]
I am curious as well. 
I've run into the same issue.
I should be able to take either of the mounts for a Herald of Khorne

**Comment by OftKilted** [comment]
I'm unable to replicate the issue in v45. (Chaos Daemons)
(Formation -> Murderhorde, Herald of Khorne, both juggernaut and throne are available.)
Are you attempting to take both the Murderhorde AND the gorethunder battery? If so, you should be taking Forcetype: Chaos CD Daemonic Incursion.
If you don't select the incursion, the formation won't reconcile the requirement for the throne in the gorethunder battery and the 'choice' for the murderhorde.
Taking both the murderhorde and the gorethunder battery is a full daemonic incursion and will give you additional benefits. 
![murderhorde](https://cloud.githubusercontent.com/assets/17132967/13271779/392663fc-da65-11e5-87f9-50f3c8ee1ffd.png)

**Comment by cartag** [comment]
This is an unfortunate bug while waiting on the 1.16 version to come out. The easy answer is like @OftKilted said. If you're going to include the Gorethuder Battery and the Murderhorde, bring it as the special daemon formation. You get the bonus rules that way too at zero point cost.

**Comment by cartag** [comment]
Rectified in BS2 prep file. Closing here.
