### ISSUE TITLE
[Join Request] for data files development and editing

### ISSUE THREAD

**Issue by SuperPranx** [BSData/wh40k-7th-edition#1919]
Hi guys,

I started playing Warhammer40K almost a year ago and BattleScribe has been very, very, helpful. However, I realize that without the data files that you maintain here none of that would be possible.

I've found myself wanting to do a change or a fix on more than one occasion and since I'm a software developer I think I won't have too much trouble getting the hang of how the data files function.

I might not be able to work on this too often, but I'd like to help maintain what has become an integral part of my gaming life.

Thanks,
SuperPranx

**Comment by hisop** [comment]
I can vouch for @SuperPranx he has been contributing.

**Comment by amis92** [comment]
Oh, how did that get lost on me?

Always glad to welcome such great promising people :) Welcome aboard!

Just don't forget to accept the invitation, and I believe you've already gone through BSData/bsdata/wiki and stay in touch on gitter, so that's that :)
