### ISSUE TITLE
[Anon] Tau Kroot default weapon bug

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#192]
The "Kroot" troop choice is supposed to comes with the "Kroot Rifle" by default. But the warning dialog ask to select a "Kroot Rifle" for each model and there is no way to select it. This should not be an option. Thanks.

**Comment by amis92** [comment]
Just checked, working correctly on v1.14.04b. Just after installation of 1.14.05b : behaves correctly too.

Please check if new version doesn't fix it. It's possibly a bug in BattleScribe, and that you report it, means you use iOS most probably. So, you need to be patient.

**Comment by Jonskichov** [comment]
I'm unable to reproduce under 1.14.05 either.

iOS is now up to date (as of last week) so shouldn't be a problem there either.

**Comment by amis92** [comment]
Seems like BS update fixed it. Closing
