### ISSUE TITLE
Space Wolves - Vindicator vehicle options are a bit wrong

### ISSUE THREAD

**Issue by SuperPranx** [BSData/wh40k-7th-edition#1928]
Vindicator should be able to take both Dozer Blade and Siege Shield.

Dozer Blade increases front armor by one and allows re-rolls of Dangerous Terrain tests.
Siege Shield lets the Vindicator automatically pass Dangerous Terrain tests.

**Comment by SuperPranx** [comment]
Will this be fixed or is there some errata that says you must choose either DB or SS?

**Comment by hisop** [comment]
I thought your pull fixed this, sorry my bad :P you are correct both can be taken.

**Comment by SuperPranx** [comment]
No problem. I'll fix it if I have the time later this evening, if someone doesn't beat me to it :)
