### ISSUE TITLE
Codex: Space Wolves update

### ISSUE THREAD

**Issue by Kangodo** [BSData/wh40k-7th-edition#193]
Their codex needs to be updated. 
Do we edit the old one or create a new?

Anyway, here we can mention what everyone is working on.

**Comment by amis92** [comment]
I think before the new BattleScribe with entries in game system is released it's better to upgrade. We'll need to write new ones either way.

**Comment by ghost** [comment]
I'm about half-way through it now. HQ's, profiles, vehicles are done - it won't take long to sort the units, so it should be ready tomorrow. 
Should I give it a new cat id, or leave it the same so that it overwrites the old file?

**Comment by Kangodo** [comment]
My vote: New Cat-ID, so we can give people some time before we remove the old Codex (maybe in a month or so).

Yeah, I tried to work on it this evening.
But I'd have to say that the SW-set up is quite difficult. Wanted to change Logan but didn't even know where to start!
Could you perhaps sync some of the changes already done for reviewing?

**Comment by ghost** [comment]
I've put it up now. Had to rename the old one - sorry.

**Comment by Kangodo** [comment]
Thanks!
Weird, my Battlescribe keeps giving a typo in "minimum X", saying minimium.
I don't have the supplement, but already added the Wolves Unleashed Detachment to the gts.
So now we need the new Detachment, update the Revision and it's ready.

Would be useful if BS allowed us to give rules with the Detachments, so the printout might say "Objective Secured". Might be an idea for a feature BS-update.

**Comment by amis92** [comment]
@Kangodo share such ideas in [BattleScribe's UserVoice](http://battlescribe.uservoice.com/forums/55066-general). You can of course link to this discussion to support your idea, and maybe gain a few votes from us. :D

**Comment by ghost** [comment]
That's everything from the Codex complete; just leaves the big Apoc formations need doing. The logic involved in making the Grey Hunters show the correct defaults & allow all their legal combos (& keep it reasonably tidy) is a complete pain, so be aware if you make any changes.

Hey @Kangodo, I've set it to display the rules like "Jarl of Russ" if you select a Wolves Unleashed detachment. Can do the same for CAD & Allied detachments.

**Comment by Kangodo** [comment]
Thanks, that's a nice workaround!
I see what you mean, that will take some time.

I do have some difficulties with the Detachments.
I've made them exactly like the CAD, etc, but for some reason it doesn't list them in the right order in the  Roster-editor.
And when I'm in the GST-editor, it randomly changes all orders whenever I click anything.
Would you perhaps have some time to see if you get the same errors?

Edit: The Apoc Formations should be doable, but they'd be a lot easier if all units were shared entries.
Especially now that Formations are more and more common, I think that would be the best way to create all codices. It's what I will do with the next BA-release.

**Comment by amis92** [comment]
about Formations and Shared Entries:
Yeah, that's what I've been doing with Tau for some time. Makes Formations much easier. However sometimes it gets in the way of pure copy-pasting, because for example I have some formations that say 3-man XV88 team, and that's a modification undoable from Link-SharedEntry perspective :(

**Comment by Kangodo** [comment]
Thank you @khambatta 
Can I ask how you did that?
I have no idea what went wrong, I entered them in the right order.

**Comment by ghost** [comment]
Yeah, last time I added a detachment I think I re-did it 4 times before I got a handle on it - the Categories show up in the order they're created, not the order they appear when you look at the editor - so you have to name them when you add them, rather than adding all & then naming.

**Comment by Kangodo** [comment]
Thanks, now I understand. Could have sworn I added them in the right order..

Do you think you did nearly everything? I think it might be time to release this.

I checked the entries and they all seem to be in order.
My only feedback would be about Grey Hunters, they are very confusing.
I could try to make a clean version next Tuesday and add them as Grey Hunter - Test, so you can decide which version you want.

Good work!

**Comment by ghost** [comment]
I'm working on the apoc stuff now, so we should be able to do the release tomorrow.

I think I can move the plasma pistol to simplify the Grey Hunters. The problem with the SW units is you can put all the upgrades on a single guy; they're not like Marines, or IG, where it limits you to one per model. That means you can end up with a squad of ten separate 'characters' that each need to be configured individually when making up a roster...

I'm also looking at shifting their "Pack" group to Shared Entry Groups - if it works.

**Comment by ghost** [comment]
That's complete now. I'm slightly concerned about the file size, as that kinda thing has been an issue in the past. If we get complaints, I reckon I'll have to pull those Apoc formations back out, since they account for 25%

Moving the Grey Hunters' group to Shared Entries did not function - modifiers don't like being there. I also tried building the unit with a "Grey Hunter w/ Plasma Pistol", but it just multiplies the number of variables for the other upgrades. All the other units seem fine.

**Comment by dattanchu** [comment]
Fantastic work. I am checking it out right now. Can we submit a request to have the old one pulled?

**Comment by amis92** [comment]
@dattanchu Yes I think it's good idea. Those who did have will still have it, and new downloads will be lighter. No reason really to leave it.

I've put up and issue for it and more: #201.

**Comment by dattanchu** [comment]
@khambatta I see that Drop Pod is not in the Fast Attack slot.

**Comment by Kangodo** [comment]
"Drop pods missing from fast attack slot. Power armour wolf guard jump packs and bikes wrong cost"
From #203

**Comment by dattanchu** [comment]
Iron Priest missing as well.

**Comment by ghost** [comment]
I've added the Drop Pods to fast attack now. The wolf guard jump packs and bikes are the correct cost, at 3pts and 7pts per model, so no change required.

Iron Priest is in the elites section.

**Comment by Kangodo** [comment]
Codex is added and people continue to make new issues, so I can close this.
