### ISSUE TITLE
[Anon] Grey Knights Coteaz missing?

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#194]
I could not find an entry for Inquisitor Coatez, in the HQ section of this codex.

**Comment by amis92** [comment]
Indeed quite hidden. Coteaz is available as a sub-choice in Inquisitor HQ choice.

**Comment by Kangodo** [comment]
Does this mean the question/issue is answered?

**Comment by amis92** [comment]
Yes, I think. Close it next time you get here. I'll leave it open until then.

**Comment by peterlyberth** [comment]
Lets close it. 
Grey knights get a new dex in a second and inq wont be part of it.
(Can I close it?)

**Comment by Kangodo** [comment]
No! You cannot.
_mwuahahah_

**Comment by peterlyberth** [comment]
:)
