### ISSUE TITLE
Space Marines captain relic sword.

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#1942]
**File:** Officio Assassinorum Dataslate (2014).catz

**BattleScribe version:** 1.15.07

**Platform:** Android

**Dropbox:** No

**Description:** missing upgrade to Space marine Captain. info page in 2015 codex states "a chapter master in power OR terminator Armor may replace his power sword with a Relic Blade "  10 PTS.  upgrade is present on power armor but not on terminator option.

**Comment by hisop** [comment]
So this bug if for codex space marines and not officio assasinorium?
