### ISSUE TITLE
[Anon] Multi force crash

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#195]
Whenever I try to make an army list with the Siege Assault Vanguard list as a main detachment or allied detachment in conjunction with another list, the program immediately errors out as soon as I try to edit anything. This happens with a number of other lists too but this one most consistently.

**Comment by amis92** [comment]
This indeed is a confirmed bug in BattleScribe. Already reported, I'm not sure if it wasn't fixed in v1.14.05.

**Comment by Jonskichov** [comment]
This was fixed in 1.14.05 and the fix is now available on all platforms (Android/iOS and desktop).

**Comment by amis92** [comment]
Seeing as it's fixed, closing.
