### ISSUE TITLE
Grey Knights weapons points

### ISSUE THREAD

**Issue by leonk70** [BSData/wh40k-7th-edition#1954]
The points for the grey knights is way off. It says on the data file that the daemon hammer is 30pts. However the codex says that it is only 10. As with the halberd. The data file says 22 pts. But the codex says it is only 2. Can we fix this?

**Comment by Jbat360** [comment]
.... That is the cost for the whole power armoured  marine + weapon..

**Comment by hisop** [comment]
@Jbat360 is correct...
