### ISSUE TITLE
[Join Request] Request for Rights for merges

### ISSUE THREAD

**Issue by DrTobogganMD** [BSData/wh40k-7th-edition#1955]
I've committed and requested multiple pulls recently and decided I would like to actually join in on the maintenance and development of the 40k catalogs.  I play Tau and Necrons so would know the most in those codexes, but also have constant exposure to Space Marines, Tyranids, Skitarii, and soon to be Ad-Mech and Orks.

**Comment by efalsken** [comment]
He's good guy in the Tau forums.

**Comment by amis92** [comment]
Always glad to welcome such great promising people :) Welcome aboard!

Just don't forget to accept the invitation, and I believe you've already gone through BSData/bsdata/wiki, so that's that :)
