### ISSUE TITLE
[Skitarri] Dominus Maniple Change

### ISSUE THREAD

**Issue by DrTobogganMD** [BSData/wh40k-7th-edition#1957]
There is valid argument that the Dunecrawler should be allowed to buy more than 1 model in the unit.  #1953 discussion in comments and Gitter shows that Formations reference Army Unit Entries, and the Unit Entry for a Dunecrawler says it can purchase more - even though the Formation states "1 Dunecrawler"

This (and likely all other Start Collecting boxes) is likely a case of GW's inconsistent wording and should be played as loosely as possible until an Official FAQ is given.  If the maintainer agrees I will commit and make a pull request.

**Comment by Thairne** [comment]
IF this should be done,  it should contain rule implemented as a RAI warning to warn the user that there is an ambigous rule.
We don't want someone to show up at a tournament and get accused of an illegal list.

**Comment by DrTobogganMD** [comment]
I'd be in favor of closing this issue entirely and changing a entries in other catalogs to match RAW.  @hisop is discussing this in chat today along with @OftKilted regarding 2 similar entries in the Necron catalog.

**Comment by kombatrok** [comment]
I'm not able to pull up the formation. Has the release with it not been pushed yet?

**Comment by OftKilted** [comment]
@Thairne @Kohato From a discussion perspective, if we're leaving it with that as an 'Option' including a set of notes talking to the issue would be good. (Similar to how the discussions have worked associated with taking multiple 'Artefact' type items for some of the other catalogs.

@kombatrok The Dominus Mantiple, as currently implemented is a formation available in the Skitarii catalog. For this discussion, none of the changes being discussed have been pushed.

**Comment by kombatrok** [comment]
@oftkilted I'm not able to pull it up on android or PC as a formation detatchment under Codex Skitarii... only 4 formations are listed and it isn't one.

**Comment by OftKilted** [comment]
On IOS: Formation Detachment > Skitarii Codex v21 > there are 7 formations listed. (Battle Mantiple, Battle Mantiple (War Convocation) Cohort Mechanicus, Dominus Mantiple, Ironstrider Cavaliers, Sicarian Killclade, War Cohort.

**Comment by kombatrok** [comment]
On Android and PC: Formation Detatchment > Skitarii Codex v21 only the following are available as options: Battle Maniple, Ironstrider Cavaliers, Sicarian Killclade, War Cohort.

**Comment by OftKilted** [comment]
Based on your description of your issue (which is separate from the issue being discussed), that is likely the show/hide bug from v1.15 rearing it's head that will be resolved when v1.16 is released.

**Comment by DrTobogganMD** [comment]
Closing this issue - Dominus Maniple will be left as is.
