### ISSUE TITLE
[Anon]Inquisition - Dataslate update

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#196]
Dataslate was updated, 
Valkyrie point cost is now 125, but the lascannon now costs 10 pts, rocket pods 10 pts and the sponson heavy bolters cost 20 pts.
Inquisitors now must select from the following disciplines: Daemonology(Santic), Divination, Pyromancy, Telekinesis and Telepathy.
Psykers now must choose from Daemonology(Santic), Divination, Pyromancy, Telekinesis and Telepathy Disciplines.  (The former power is now removed)
I think that was all.

**Comment by Kangodo** [comment]
Changed it, finally got access to the updated version :)
Only thing I am not sure on are the Valkyrie-options, they are from IA2 but do not appear in the updated Dataslate.
I will just leave them in for now.
