### ISSUE TITLE
Enhancement: Add Strike Force Daggerfist Formation Space Wolves - Codex

### ISSUE THREAD

**Issue by Gnofry** [BSData/wh40k-7th-edition#1968]
The Space Wolves Daggerfist Formation is one of those crazy things that would be fun for most people to play around with in the list builder. Please add whenever convenient.

![daggerfist](https://cloud.githubusercontent.com/assets/17345182/13541323/90c476f0-e229-11e5-8213-6b493613b582.jpg)

**Comment by DrTobogganMD** [comment]
I'll add this sometime today - Thanks for the dataslate source.
