### ISSUE TITLE
Codex Space Wolves 2014 Long Fangs

### ISSUE THREAD

**Issue by SilverSnakes** [BSData/wh40k-7th-edition#197]
Heavy Weapons costs are too high they should be 
Heavy Bolter 10pts
Multi-Melta 10pts
Missile Launcher 15pts
Missile Launcher w/ Flakk 25pts
Plasma Cannon 15pts
Lascannon 20pts

**Comment by ghost** [comment]
The costs are correct - Long Fangs are 15pts each.

**Comment by SilverSnakes** [comment]
Oh wow I'm sorry they added the cost of the long fang and the heavy weapons together I see now. Anyways I'm sorry for the trouble, but very thankful for the hard work you as well as others have put into the program.
