### ISSUE TITLE
Bug Report: Space Wolves Codex. The Blackmanes Formation Error

### ISSUE THREAD

**Issue by Gnofry** [BSData/wh40k-7th-edition#1970]
The squad of scouts is not optional, it is actually required for this formation. The 0-1 Wolf Scouts should be changed to a mandatory 1 unit of Wolf Scouts.

**Comment by DrTobogganMD** [comment]
Confirmed - Blackmanes requires 1 Scout unit, not 0-1.  Also - Veterans should be 1 required, not 0-1.

Changing both.
