### ISSUE TITLE
[Bug Report] Space Marines: Codex (2015) v50

### ISSUE THREAD

**Issue by Taturo2552** [BSData/wh40k-7th-edition#1975]
Named Characters don't appear in the selections anymore when selecting the appropriate Chapter Tactics.

For Example, if I select Imperial Fists, Darnath Lysander does not appear as an HQ option.

This applies to all Chapter tactics, including the Forgeworld ones.

**Comment by Gnofry** [comment]
Which platform is this on? Using PC I am seeing appropriate behavior.

![image](https://cloud.githubusercontent.com/assets/17345182/13555418/f7e8646c-e38d-11e5-97c5-ac69ac46e915.png)

![image](https://cloud.githubusercontent.com/assets/17345182/13555420/042b48ac-e38e-11e5-9290-ece896fc16cd.png)

![image](https://cloud.githubusercontent.com/assets/17345182/13555424/15fa6cf2-e38e-11e5-86b3-696f69d40df4.png)

**Comment by Taturo2552** [comment]
Oh this is weird, I just started up Battlescribe again and now that issue is gone. No idea what caused this, as I can't reproduce it.

**Comment by Gnofry** [comment]
Might have your data files updated? I pulled the most recent ones before testing.

**Comment by DrTobogganMD** [comment]
Tagging as un-reproducible - works fine on iOS as well.
