### ISSUE TITLE
Space Wolves - Bug in BattleScribe with roster rules modifiers

### ISSUE THREAD

**Issue by SuperPranx** [BSData/wh40k-7th-edition#1980]
How to reproduce:
1. Add Company of the Great Wolf detachment to your force roster;
2. Click "View Roster" to confirm that the CotGW rules are there;
3. "Edit Forces" and add The Wolves Unleashed detachment to the forces;
4. Add any unit to any list;
5. Click "View Roster" and you will only see the TWU roster rules;
6. Switch the places of 1 and 3 to get the reverse results.

My guess would be that BS goes through all the detachments and applies the same rules. The conditions and modifiers from the last one added are the ones that will remain, regardless of the needs of the separate detachments.

Another issue is that the 'show' modifier for the CotGW roster rules doesn't work for the other formations, like Arjac's Shieldbrothers, that have the CotGW entry. The only reason why the Kingsguard special rule is mentioned in the special rules (not the roster rules) is because the WGT have the rule themselves, not to mention that it's a separate rule with no contents.

I'd like to hear your ideas about the problem. Should we solve it now, wait for the BS v1.16, or leave it like it is?

Proposed solution: Add the Special Rules of the formation to the CotGW catalog entry, present in the formations from the supplement, checking that each of the formations gets the right rules. Alternatively we just add a link to the rules with a show modifier in the formations and hope this doesn't get overridden by the next detachment in the force roster.
We currently can't do anything about the detachments bug, since it depends on the BS logic/behavior.

**Comment by SuperPranx** [comment]
This will wait for BattleScribe v1.16 to come out and will remain as it is, for the moment.

**Comment by afraeve** [comment]
I had a look at this with the Orks and Death Korps Siege lists; the same issue affects them all. Noticed that it only occurs if you add a second detachment from the same file as the first, whereas taking an Ork Horde with a SW wolves unleashed, for example, does not have a problem.

> Another issue is that the 'show' modifier for the CotGW roster rules doesn't work for the other formations, like Arjac's Shieldbrothers, that have the CotGW entry.

The rules for the Champions of Fenris Formations are all linked directly to those formations. The 'show' modifier you're looking at relates to Unbound lists & Apocalypse.

**Comment by SuperPranx** [comment]
There is actually an 'or' condition for the show modifier that says it should appear if there is a CotGW entry in the formation, but this just doesn't work.

EDIT: When using a different catalog they stay because they are parsed once for each detachment of the SW catalog, so it would make sense that any other catalog used wouldn't have any effect on the SW detachments/rules.

**Comment by hisop** [comment]
This needs to be tested against 1.16.
