### ISSUE TITLE
Skitarii Dominus Rangers option.

### ISSUE THREAD

**Issue by ghost** [BSData/wh40k-7th-edition#1981]
I received another response after contacting GW about why I received a card that stated Rangers with Dominus Maniple (they are all over the box!). They then sent me back "Dominus_Maniple_AMENDED.pdf" - showing rangers with this message below it.

"Thank you for your email and our product team have been working on this to give you an appropriate answer. 

Although you could assemble them as Rangers and still use the rules (it would be a cold opponent but who said you couldn't!), we are amending this formation in all future reprints and here is the formation sheet with the Ranger information.

Hope this helps.

Kind regards,

Severine
Customer Service"

This leads me to believe it is in fact rangers as it says amended in the PDF?

Would it be okay if we have a Rangers option on the Dominus Maniple until it is further disproved?

Heres a threads with updates on the issue, other people now saying all new cards are indeed rangers
https://www.reddit.com/r/Warhammer40k/comments/454sn5/can_anyone_who_has_a_dominus_maniple_formation/

Thanks
M

**Comment by DrTobogganMD** [comment]
Can you please attach the email and/or pdf from GW?

**Comment by ghost** [comment]
[Dominus_Maniple_AMENDED.pdf](https://github.com/BSData/wh40k/files/163090/Dominus_Maniple_AMENDED.pdf)

Heres the PDF they sent me. Email is pasted from above. Can make that into a PDF if you want it

**Comment by DrTobogganMD** [comment]
Interesting - Thanks Tyther.

**Comment by ghost** [comment]
![gwemail1](https://cloud.githubusercontent.com/assets/17256111/13601091/66c5c1a2-e525-11e5-8c7d-0490ad5f6f29.jpg)

Here's the email for timestamps etc

Thanks
Matt

**Comment by hisop** [comment]
This is difficult, We have a policy of not using emails from GW as FAQ's as for one we have before seen conflicting emails from different customer support staff and rules teams at GW, and fake emails made by people. i am not insinuating you would or have done that btw. this is more of a policy thing and i know it is frustrating. In the meantime we are discussing this and i will keep this bug updated.

I appreciate your effort here and if you need this i can provide yourself with a cat that will allow both/rangers. i wont publicly change this atm, as the rules people have would seem to conflict with BSData and we would get reports about that.

Like i said we are discussing and we may change our mind (or GW will ERRATA).

Thank you,
Hisop.

**Comment by ghost** [comment]
Sure thing, hopefully they actually make an official announcement, as the wording of that email almost completely contradicts the fact it says "AMENDED" on the PDF card they sent me. A personal .catz file would be really great to use for compiling my own lists. Thanks Hisop and Kohata!

**Comment by hisop** [comment]
You want just rangers yeah?

**Comment by ghost** [comment]
Yeah that would be perfect

**Comment by hisop** [comment]
Drop me an email at hisop@hotmail.co.uk and i will send it over.

**Comment by amis92** [comment]
Is there a big deal involved in creating second formation with [AMENDED] tag, and have both available?

**Comment by hisop** [comment]
Its not a hassle, i will go with the consensus of the authors, it was more a principle thing, like are we going to make two of everything GW clarifies in an email?

**Comment by amis92** [comment]
Yeah. True that. Tough call actually. Here however it's being said they amended this already in some newer runs.

**Comment by hisop** [comment]
This situation is pretty unusual as people have both sets of rules and GW does not want to rule either invalid, thus for now i will implement both.

**Comment by Thairne** [comment]
Can't you "just" do the treatment as seen in the Gladius where you can choose either of assault squads or assault cents?
That should solve the issue nicely. A RAI warning implemented as a rule to notify the user of the discrepancy and everything is covered.

**Comment by RandomCognition** [comment]
Hi, have literally just bought the start collecting: Skitarii box today and the detachment rules included show Rangers rather than Vanguard so looks like the amendment has made it out to retail now.

**Comment by Flashpoint-** [comment]
Hey guys can you please change the data format for the Dominus Maniple. Android users can't see it I contacted Jon Taylor doesn't seem like there's going to be an update anytime soon so can you please change the format so that the Android users could use this formation thank you

**Comment by DrTobogganMD** [comment]
FAQ for Admech/Skitarii confirms both options are legal to use.

**Comment by Flashpoint-** [comment]
Yes the FAQ you can use either Rangers or Vanguard
can you make two formations
Dominus Maniple (Rangers)
Dominus Maniple (Vanguard)
And make it visible for Android users
Thanks guys keep up the good work :)
