### ISSUE TITLE
Bug Report: Space Wolves Fangs of the Tempest auxiliary

### ISSUE THREAD

**Issue by Gnofry** [BSData/wh40k-7th-edition#1986]
The Fangs of the Tempest needs to be updated/fixed. You are allowed to choose 1 Stormfang Gunship or Stormwolf via the codex. Currently the data file forces you to take a Stormfang Gunship and allows you to also take a Stormwolf. 

Suggested bug fix:
The "minselections" of the Stormfang Gunship entry should be set to 0 so that the formation does not force that selection.
The links to the Stormfang and Stormwolf should be in an entry group that allows one selection from the entry group.

Suggested typographical edit:
"Fangs of the tempest" should be changed to "Fangs of the Tempest".

**Comment by SuperPranx** [comment]
The Stormfang will be set to min 0, but I'll also have to make the Stormfang entry in Wolfguard Stormforce a group entry with min/max 1 and a Stormfang by default (you wouldn't be able to choose anything else anyway).
