### ISSUE TITLE
Codex Space Marines: Red Scorpions, Veteran Sergeant Haas missing

### ISSUE THREAD

**Issue by emann1850** [BSData/wh40k-7th-edition#1987]
Can veteran sergeant Haas be added to the Red Scorpions forgeworld roster?

Thank you-

**Comment by hisop** [comment]
IA II Te Aphelion Project Vol 4 Second edition for the rules.

**Comment by ddarz** [comment]
Haas has been added :)

**Comment by emann1850** [comment]
Hi - thank you for adding Haas - but I cannot find him in the roster. He should be a Red Scorpion sergeant option for Sternguard?
Maybe I'm looking in the wrong place or there is a filter I need to flag?
-Erick 

```
On Sunday, March 27, 2016 8:37 AM, ddarz <notifications@github.com> wrote:
```

 Haas has been added :)—

**Comment by ddarz** [comment]
Hmm it works for me
Combined ops detachment, Chapter tactics = Red Scorpions
Add sternguard unit
Haas is there under the sarge options

Let me know if it doesnt work
I assume you are using data files straight from github right?

I did forget to add a cost though, whoops!

**Comment by ddarz** [comment]
Yep it seems to be working, added his cost as well
