### ISSUE TITLE
[Anon] Space Wolves - Codex weird filename

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#199]
The file's name of the latest version is a bit buggy: Space Wolves - Codex 140812001825320.catz

**Comment by amis92** [comment]
That surely isn't fault on our part. File name like that are probably your Operating System's invention. Maybe check if there wasn't another old file with the same name?

You can ask, providing more details, and I will try to answer it, however it's not a wh40k repo issue, so I'll close it (you can still write here).

**Comment by ghost** [comment]
It's possible this was caused by the 2009 & 2014 files both being named "Space Wolves - Codex.catz"
