### ISSUE TITLE
Lord of the Fang has false error

### ISSUE THREAD

**Issue by adoliver** [BSData/wh40k-7th-edition#1995]
In the SW Wolf Claw Strike Force under Lord of the Fang, any of the character selections should be valid. The roster is showing an error if Ulrik the Slayer is not chosen. "Lord of the Fang must have 1 or more selections of Ulrik the Slayer, Wolf Priest (minimum 1)"

All the correct Lord selections are available, the warning logic is simply incorrect.

Battle scribe v1.15.7
Data updated 3/10
![tmp_12105-screenshot_20160310-2329501112969922](https://cloud.githubusercontent.com/assets/2785019/13695962/149e4d0a-e718-11e5-97ee-0e10b94d65e7.png)
![tmp_12105-screenshot_20160310-2329371040205015](https://cloud.githubusercontent.com/assets/2785019/13695968/18ef5aa2-e718-11e5-983f-8d2b6d9ed4ef.png)

**Comment by SuperPranx** [comment]
Already fixed and will be available in the next release.
