### ISSUE TITLE
Space Wolves - Re-work Strike Force Daggerfist

### ISSUE THREAD

**Issue by SuperPranx** [BSData/wh40k-7th-edition#2000]
Currently the Kingsguard rule they have doensn't increase the WS of the Wolf Guard and Wolf GUard Terminators by 1 in the profile. Since the logic required to do this with the default WG and WGT profiles can't be done, due to the current way BattleScribe handles things, they need to have actual entries in the formation, instead of links to the shared entries.

You can see how this is done in the "Wolf Guard Thunderstrike" formation with the addition of a link to the Kingsguard (Collective) directly in the WG model entry. The WG and WGT profiles have conditional modifiers to increase their WS in case this entry is found in the direct parent.

**Comment by cartag** [comment]
You'll be able to set the condition to Ancestor in 1.16 and resolve the issue once and for all. Just so this can be added to the list of things being taken care of with the new version.

**Comment by DrTobogganMD** [comment]
This is already done for the Great Wolf detachment, We can set it to + if Direct Parent is equal to the formation name instead of the force type.
