### ISSUE TITLE
Remove deprecated files

### ISSUE THREAD

**Issue by amis92** [BSData/wh40k-7th-edition#201]
I hereby put under discussion an idea to remove catalogues which have got new versions. Namely:
- [x] Imperial Guard - Apocalypse (does Astra Militarum contain all Apoc units?)
- [x] Imperial Guard - Codex
- [x] Imperial Guard DKoK Assault Brigade
- [x] Space Wolves - Codex (2009)

If there are any I missed, please say so.

**Comment by Kangodo** [comment]
I agree that we need to remove old and outdated codices when we have a newer version.
For Space Wolves I would wait a month or so, because not everyone has the new Codex yet.

It's what I plan to do with the Necron and BA-releases: Make a duplicate, give it another ID/title and include that for a month.

**Comment by ghost** [comment]
Astra Militarum doesn't contain all Apoc units - I was worried about the file size on mobile devices, but if it's not been an issue for anyone, I can copy them across some time next weekend.

**Comment by Viper666-Qc** [comment]
I think you should merge all mising the Imperial guard Apoc units in the Astra Militarum codex. Anyway, if we don't select the "Apocalypse" Forces, those apocalypse unit only won't show right? 

Is there a reason the old Imperial Guard - Codex is still up?

**Comment by peterlyberth** [comment]
Out with the old. In with the new. Let people post bug report and data for units they are missing.

Or put them in a seperate folder for now and watch the reaction. That way we can always roll back.

**Comment by katfude** [comment]
Why don't we make a Legacy codex repo that we can move the files to? That way, anyone with old codexes can still enjoy your fine work and the can enjoy their antiquated armies.

**Comment by amis92** [comment]
There is a mechanism we could use. We actually use it constatly: releases.

For each release, you can add any file: zip, exe, whatever you wish. That's what I've done for 6th ed files. You can find them by following the link in README.

But how should it work? I mean, what would be in the legacy one? Only deprecated ones, or both old and new?

---

Another way: separate repository.

I could create repo wh40k-old. We'd copy there catalogues to be deleted (so when a new one comes in). Not a bad idea, @katfude . :)

**Comment by amis92** [comment]
Ok, so I created new repo: https://github.com/BSData/wh40k-old

There we'll move old files. Ok?
