### ISSUE TITLE
Bug report: Dark Eldar

### ISSUE THREAD

**Issue by deldarius** [BSData/wh40k-7th-edition#2011]
I can't select a court of the Archon without taking up an HQ slot. The No Force Slot choice flags up as "1 too many selections of Court of the Archon."

Thanks for the data!

**Comment by OftKilted** [comment]
Unable to replicate.
CAD
Took 1x court of archon
1x archon
Only flags were missing troop choices

**Comment by OftKilted** [comment]
Court of the archon is available as a "no force org slot" and also available as an HQ choice.

**Comment by deldarius** [comment]
Thanks for the quick reply, Oftkilted. However, I'm trying to use the no force org slot but still getting the error message. I've just created a new roster, chosen a CAD, took 1 Archon, 1 Court of the Archon and 2 troops. The only error flag reads:

"Dark Eldar: Codex (2014) (Combined Arms Detachment) has 1 too many selections of Court of the Archon (maximum 0)..."

If it's not a bug you can find, would I need to delete and reinstall the app? I don't really want to lose all my rosters if possible. 
(BTW, are you Scottish? Me too!)

**Comment by OftKilted** [comment]
Can you grab me a screenshot of your CAD and another of the error?

**Comment by OftKilted** [comment]
If you don't use the "no force org slot" version and instead use the version under HQ, do you see the same error?

**Comment by deldarius** [comment]
Yes, same error. How do I send you the screenshot?

**Comment by hisop** [comment]
can just paste in images here.

**Comment by hisop** [comment]
no response, thus i'm closing.
