### ISSUE TITLE
Space Wolves - Wolf Scouts weapon selection bug/improvement

### ISSUE THREAD

**Issue by SuperPranx** [BSData/wh40k-7th-edition#2014]
How to reproduce:
1. Use CAD (for example) and add Wolf Scouts;
2. Increase their Sniper Rifle selections to 5 (without changing anything else);
3. Increase the number of Wolf Scouts in the unit;
4. For every Wolf Scout you add, BattleScribe adds 2 Bolters.

**Comment by afraeve** [comment]
> without changing anything else

I don't want to state the obvious, but you have to decrease the Bolters they come with when you increase the Sniper Rifles.

**Comment by SuperPranx** [comment]
That would be fine if, when I add just one Scout, I end up with 6 Bolters and 5 Sniper Rifles. However, I end up with 7 Bolters and 5 Sniper Rifles. If I add another one I now have 9 Bolters and 5 Sniper Rifles.  When I get to the full 10 Scouts, BattleScribe says they have 15 Bolters and 5 Sniper Rifles. The issue is not that I want them to reduce automatically, but there is a bug which gives every new Scout you add two Bolters instead of one. Under these circumstances it occurs, with other numbers of Bolters and Sniper Rifles it might not. I also haven't tested the behavior for other weapons than the Sniper.

It goes without saying that you would have to reduce the number of Bolters manually. That's how I've always done it :)

**Comment by afraeve** [comment]
I'm getting a different result: if I take at least 1 Bolter (& 4 Snipers, for example) then the additional Scouts appear as normal, but if I reduce the Bolters to 0 (& 5 Snipers), then the extra Scouts show up with no weapon at all.

**Comment by SuperPranx** [comment]
It's a bug with how BS interprets the data. The only way to resolve this without a BS bugfix would be to un-check the "collective" checkbox on the weapon choices, but that would cause every Wolf Scout to be it's own entry in your roster effectively forcing you to manage each one separately.

**Comment by DrTobogganMD** [comment]
No further bugfixes for BS are on the way until 2.0 and there is no easy way to fix this without managing each wolf scout alone.  Doing that effectively would also introduce another iOS bug with increment/decrement - we'll re-assess this once we get to 2.0.  As this is a fixable bug when list building it's not entirely a priority to fix until we get the new build.  Closing this issue for now.

**Comment by DrTobogganMD** [comment]
Nvm, was given a good way to fix this - fixing.
