### ISSUE TITLE
Chaos Space Marine Black Legion Supplement not available on PC (SOLVED)

### ISSUE THREAD

**Issue by FawkesLOL** [BSData/wh40k-7th-edition#2017]
I have noticed that when I use the android app I am able to create lists from the Chaos Space Marines: Black Legion Supplement, but the data file is not available on my pc when I go to access.

I have checked the data on my mobile phone and it shows the following information:
http://battlescribedata.appspot.com/repos/wh40k/index.bsi and when I go to verify my data on the pc version it is the same address yet does not provide the black legion codex.  I would just like to know if this is intentional or an error on my part somehow.

Thank You!

**Comment by OftKilted** [comment]
The black legion supplement and the Crimson slaighter supplements are now sub components of the standard Chaos Space Marine codex.

**Comment by OftKilted** [comment]
To access it select "no category" then select "force options (supplement options here)" and the black legion supplement will be available there

**Comment by FawkesLOL** [comment]
Thank you very much!
