### ISSUE TITLE
Curseborn formation drop pod is free when taken with Blackmanes

### ISSUE THREAD

**Issue by evilmerlin** [BSData/wh40k-7th-edition#2018]
The Curseborn formation currently has the drop pod option for free when taken in a Wolf Claw Strikeforce with the Blackmanes. That is not supposed to be the case. The free drop pods only apply to models in the Blackmanes formation.

**Comment by SuperPranx** [comment]
The rules were wrong as they were set up. Additionally there were also a bunch of problems with other units like the Long Fangs choice of a WGPL.
