### ISSUE TITLE
Bug Report: Eldar Lynx Points Cost/Slot

### ISSUE THREAD

**Issue by sanguine8082** [BSData/wh40k-7th-edition#2024]
I noticed with the latest version of the Craftworld Eldar Codex, the Lynx is not listed as a Heavy Support. According to the latest update from IA11, the Lynx is a heavy support with a sizable point reduction and the loss of the Eldar Titan Holofields.  

Version 22 of the Eldar Craftworlds Codex.

**Comment by efalsken** [comment]
duplicates #1727
