### ISSUE TITLE
Ravenguard Bladewing Assault Brotherhood - Sergeant Load Out Bug/Problem

### ISSUE THREAD

**Issue by Ametarim** [BSData/wh40k-7th-edition#2038]
Space Marines: Codex (2015) - SM RG Talon Strike Force

Within the chapter tactics for Raven Guard, with a 'Pinion Battle Demi-Company' taken, and an added 'Bladewing Assault Brotherhood' - In any Assault Squad of the Bladewing Assault Brotherhood, you are not able to take a Sergeant and a Jump Pack, instead they are both listed in the 1 selection box for the Sergeant resulting in you to be not able to take the jump pack.
![codex bug](https://cloud.githubusercontent.com/assets/18098786/14065043/3dc635c0-f461-11e5-9587-4774a1d496f2.JPG)

**Comment by ddarz** [comment]
Should be fixed now
Let me know if any issues crop up
