### ISSUE TITLE
[Anon] CSM / Eldar squad size error

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#204]
It is telling me that too many noise marines have blast masters (2) in my 10 man squad (including the champ) the codex and 7th ed f.a.q both say in the squad numbers 10 or more then 2 may b given blastmasters. A similar problem exists in the eldar file: it won't allow minimum squad sizes with an exarch upgrade, instead counts the exarch as an additional model. I hope this helps. If anything I have written above is unclear I can b reached by email : Iain.a@hotmail.com

**Comment by amis92** [comment]
I think now by #183 closed, it's done too.
