### ISSUE TITLE
[Anon] AM Codex - Command Squad armor

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#205]
Company command squad doesn't charge the full 8 points for carapace armor if the medic upgrade is selected only 6.

**Comment by ghost** [comment]
I'm not able to duplicate any problem with the medic. Note that the heavy weapon team counts as only 1 model, so you'd only be charged 6pts if you've selected that.

**Comment by amis92** [comment]
Possibly it was a BS bug.
