### ISSUE TITLE
Trouble saving a roster (MT combined detach, INQ inq detach, IK knight detach)

### ISSUE THREAD

**Issue by Viper666-Qc** [BSData/wh40k-7th-edition#206]
When trying to save this roster (see the attachment), it pops an error that I can't save it with the following reason - "Selection must have a category that exist"

Roster is "valid" with no message. Using the latest .cat for the 3 codice and the latest desktop version of Battlescribe.

![roster saving bug](https://cloud.githubusercontent.com/assets/7775774/3902020/8633618a-22b6-11e4-8da6-3defc1dd4a6b.jpg)

**Comment by ghost** [comment]
It looks like the problem was in the Land Raider, so I've updated that. I can't see anything in the Knights, so let us know how that works out.

**Comment by amis92** [comment]
Knights aren't complicated, and there was only one error. Fixed.
