### ISSUE TITLE
Bug report Eldar Craftworlds - Codex (2015).catz: Autarch

### ISSUE THREAD

**Issue by Owlsbane** [BSData/wh40k-7th-edition#2064]
File: Eldar Craftworlds - Codex (2015).catz

BattleScribe version: 1.15.07

Platform: Windows

Dropbox: No

Description: In roster statistics the Autarch does not count as a model

**Comment by efalsken** [comment]
Will not fix. Unfortunately Battlescribe can classify as a model or as a unit, but not both.
