### ISSUE TITLE
Bug report Eldar Craftworlds - Codex (2015).catz: Wraithguard

### ISSUE THREAD

**Issue by Owlsbane** [BSData/wh40k-7th-edition#2068]
File: Eldar Craftworlds - Codex (2015).catz

BattleScribe version: 1.15.07

Platform: Windows

Dropbox: No

Description: In the Roster Selection Pane, the information shown is incorrect. It shows the gear and the models at the same depth in the tree, instead of the 5 Wraithguard first and then their weapons as a branch to them

**Comment by efalsken** [comment]
Will not fix. It's unfortunate Battlescribe Bug.
