### ISSUE TITLE
Bug report Eldar Craftworlds - Codex (2015).catz: Lots of small things

### ISSUE THREAD

**Issue by Owlsbane** [BSData/wh40k-7th-edition#2076]
File: Eldar Craftworlds - Codex (2015).catz

BattleScribe version: 1.15.07

Platform: Windows

Dropbox: No

Description: Half of these are typos, the rest mostly easily corrected database entry mistakes. Small amount is probably working as intended due to limitations of BattleScribe. @efalsken Apologies for the dump, and once again thank you for your time and effort in bringing these lists to us.

1] Star Engines [vehicle upgrade] - Typo, 'making a' should be 'moving'
2] Strafing Run [special rule] - Typo, look for 'alse' in the last line

3] Spectre Holo-Field [FW] - This is a problem with the IA11 list, you use page 135 for your description of the Spectre Holo-Field, but the same rule on Irillyth's page states explicitly it does not stack with any other cover saves (page 139). How to handle this?
4] Irrylith [FW] - Warlord Trait: Twilight Terror has a typo at the end of the first sentence, should be 'he has joined' instead of 'has has joined'
5] Bel-Annath - Typo in his Disciplines description, it has Promancy instead of Pyromancy

6] Corsair Prince [FW] - If choosing the First Prince option Collector of Ancient Treasures are you then meant to be able to choose every optional item that this unlocks, or just one? Another case of least restrictive interpretation?
7] Corsair Prince [FW] - The First Prince option Traveller of Forgotten Paths has some typo's in its Multiphase Key Generator description. Look for abilikty, mode (instead of model) and Mehap (instead of Mishap).
8] Corsair Prince [FW] - The First Prince option Wielder of Profane Powers has two typos. In the title it says Weilder, in the main text look for lest (least).
9] Wild Psyker Perils table - Typo in option 1, look for remainer. Typos in option 2-3, look for caesses, is has joined (it has joined).
10] Corsair Jet Pack [FW] - Typo, it has Felach instead of Felarch in its description
11] Shadowwave grenades [FW] - Typo in heading, it has Shadowweave (this one is weird, it shows correctly on for instance the Corsair Ghostwalker Band but with the typo on the Corsair Void Dreamer)
12] Corsair Reaver Band [FW] - Does not count as a unit in the statistics. If five models take a Corsair Venom as a Dedicated Transport that counts as a unit but not as a model, if six or more models take a Corsair Falcon instead then that doesn't count as either (nice work with switching the dedicated transport option depending on the amount of models taken!)
13] Corsair Kinetic Shroud [FW, vehicle upgrade] - Two typo's, look for vehilce and Invulneravle
14] Corsair Voidstorm Band [FW] - Their statline has 5+ save, should be 4+
15] Corsair Wasp Squadron [FW] - They do not count as a unit within the statistics. Also, with multiple models in the unit their weaponchoice is linked so that you can't outfit them individually
16] Corsair Balestrike Band [FW] - Their models are not counted within the statistics
17] Corsair Lynx [FW] - Star Engines vehicle gear option is numerical instead of binary. Does not count as model in the statistics
18] Corsair Night Spinners [FW] - They do not count as a unit in the statistics
19]Corsair Night Spinners/Fire Storm/Fire Prism Squadron [FW] - THe Shuriken Cannon option has a cost of 0, it should be 10
20] Corsair Vampire Raider [FW] - Does not count as a model in the statistics

21] Lord of the Undying Host [FW] - Special rule typo, it says 'Wisdom from Behind the Veil' but should read 'Beyond'. Also, the first line of the description has 'I' instead of 'If'
22] Shadow Spectres Shrine [FW] - It has 'Shadow Spectre Shrine' as its title, it should be 'Spectres'. Also, it allows you to add Shadow Spectre units even though the Formation consists of three units, period. The models in the units aren't counted in the statistics. There is no warning when you take more than the maximum of ten models for a unit
23] Khaine's Hawks Squadron [FW] - This entry is confused. It has Nightwing Interceptors that hold Nightwings. You can add Nightwing Interceptors and/or you can add Nightwings to an Interceptor group. Possible solution: Only have one Nightwing Interceptors group in the Formation, remove the Add Nightwings Interceptors button. The models are not counted in the statistics
24] Fires of the Phoenix [FW] - Remove the Add Phoenix Bombers button, remove one Phoenix Bombers entree, add a Phoenix to the other Phoenix Bomber entree. The models do not register as unit or model in the statistics
25] Fist of Vaul [FW] - Same as Khaine's Hawks Squadron, really, except unit count is too high in this Formation due to the use of two Warp Hunters groups instead of one group with two Warp Hunter models. Model count is correct
26] Hornet Swarm [FW] - Same as above
27] Wasp Phalanx [FW] - Same as above
28] Skyhunter Squadron [FW] - Does not count as a unit in the statistics. 
29] Skyreaver Raiding Echelon [FW] - It has the 'Orbital Reavers' special rule as 'Orbital Reserves'
30] Hornet Squadron [FW] - Starcannon has a cost of 0, should be 5 
31] Lynx [FW] - Lynx Pulsar (Salvo) statline has 48" range, should be 24". Starcannon has a cost of 0, should be 5
32] Cobra [FW] - D-Impaler should be standard wargear, instead it is a numerical choice. Starcannon has a cost of 0, should be 5
33] Scorpion [FW] - Starcannon has a cost of 0, should be 5
34] Nightwing [FW] - Holo-fields is a numerical choice, it should be binary. Nightwing models do not appear on the statistics overview
35] Phoenix Bombers [FW] - Do not show as unit or as models on the statistics overview
36] Warp Hunter Squadron [FW] - Shuriken Cannon has a cost of 0, should be 10
37] Wraithseer [FW] - Typo in Wraithseer Power: Foreboding-Aether Shock, it misses a space, look for witha. The Sunder special rule printed with the Wraithseer differs in its wording from the Sunder description on page 225. It says "This weapon may re-roll any failed Armour Penetration rolls it makes", on page 225 it says "...any Armour Penetration rolls". Since you also chose to keep the difference between the Craftworld version of Disperse and the page 225 version I was wondering why the different treatment?
38] Wasp Assault Walker [FW] - Wasp Jump Pack special rule, small typo. Missing space between third and forth word, it has 'beused'
39] Phantom Titan [FW] - It does not show as a unit or a model on the statistics overview. Cloudburst Missile Launcher has a typo in its name in the statline, it says Cloudburrst. Eldar Titan Holo-Field and Phantom Missile Launcher are standard wargear but they have numerical selectors.

40] Guardian Battlehost - There is a button to add Guardian Defender squads, but you can only have three squads in the Formation (is this to allow people to add a unit when they accidentally remove one?)
41] Windrider Host - On the righthand pane it has a typo, 'Vyper Squadron - 1 rrequired'. There is a button to add Windrider squads, but... (see above)
42] Guardian Stormhost - There is a button to add Storm Guardian units, but...
43] Seer Council - Special rule Psychic Might has a typo, look for 'Warp Carge'. Has a button to add more Farseers but...
44] Dire Avengers Shrine - The Formation is missing its special rules
45] Crimson Death - There is a button to Add Crimson Hunters, but...

Bonus:
46] Shining Spears - Exarch's weapon choice is confusing, is it not possible to just have Laser Lance, Star Lance and Power Weapon (without the differing flavors) as round bullit choices, pick one?

47] How come some weapon special rules (for instance Bladestorm) are always mentioned as a characterspecific special rule, but other weapon-related special rules (such as Armourbane) are not?

**Comment by efalsken** [comment]
@Owlsbane: its seriously scary how many of these bugs you've found. Great attention to detail!

**Comment by efalsken** [comment]
In battlescribe, an entry can be a Unit or a model. Since Model Count is mostly useless in 40k (as written) and Unit counts are useful for victory points in half of the missions, we default to leaving ambiguous single-model-units as units. (like single-model vehicles and characters)

**Comment by efalsken** [comment]
23 and 24: these formations are 2-3 squadrons, but each squadron can take a variable number of squadron members. This is the intended behavior. Sorry, Battlescribe doesn't deal with formations very well right now. Many improvements are coming in the next major battlescribe release.

**Comment by efalsken** [comment]
Formations aren't handled very well right now in Battlescribe. We have to do it as "choice groups" so that the Formation required selections are selected by default. Unfortunately, this means that you get the extra "add" button.

**Comment by efalsken** [comment]
In an effort to not have to re-type the entire 40k base rulebook's special rules section, we only put the rule text for the less common rules. Players need to read the rulebook and know their rules. these datafiles shouldn't be everything needed to play. And if we tried to provide a complete set of rules, GW would come down on us.

**Comment by Owlsbane** [comment]
I realize some of the items I mention are probably functions of the way BS works, but I wasn't sure so I decided to mention them anyway. Hope you don't mind. I understand the limitations better now and it seems that the next version of BS will remove some of these concerns.

Re: 23 and 24, I don't think that is what Imperial Armour vol. 11 2nd edition is saying. It has:
Khaine's Hawks Squadron: Formation - 2-3 Eldar Nightwings (so not Eldar Nightwing Squadrons). Also, the restriction below that says All Nightwings bought as part of this Formation form a vehicle squadron and must take the same upgrades. So the whole Formation is one squadron, period.
Same goes for Fires of the Phoenix and other Formations.

The whole 'unit/model in the statistical overview' thing isn't of much concern, true. But since there are enough units that seem to get these values right I thought it might be worthwhile mentioning the ones that didn't. I couldn't see any pattern that would explain the exclusion of some units/models over others and thus wasn't sure if they were oversights or just not worth the bother ;) I won't mention them again!

It took me a while before I understood what you were trying to say with your last remark (apart from the obvious, I understand why the brb special rules aren't in the catalogue and I agree). I solely play Eldar so it didn't really register with me that Bladestorm and such are Codex-specific rules and only these weapon rules get mentioned with any other unit-specific special rules. They were just part of the basic game to me!

**Comment by efalsken** [comment]
Dire Avenger Shrine has no special rules. It's just "oh so you want more Dire Avengers..." It's an organizational unit in the Craftworld Warhost that isn't a proper Formation.
