### ISSUE TITLE
eldar craftworld: windrider warlock able to select jetbike options

### ISSUE THREAD

**Issue by plebicidal** [BSData/wh40k-7th-edition#2090]
windrider warlock should not have access to jetbike special weapons as per rulebook.
![image](https://cloud.githubusercontent.com/assets/18018035/14413902/6de31ea6-ffcb-11e5-95e5-d732d6fb5a83.png)

**Comment by efalsken** [comment]
That's a tricky one, because it says "any Windrider". And the "Windrider Warlock" has "Windrider in its name".

**Comment by plebicidal** [comment]
Windrider <> windrider  warlock.
Just the same as an SM squad sergeant cant take a special or heavy weapon
etc.

**Comment by cartag** [comment]
Agreed, @plebicidal. If it was meant to include the Warlock it would say "Any model may exchange..."

**Comment by OftKilted** [comment]
Is the 'Windrider Warlock' the 'Champion/Sgt/Squad Leader' equivalent? That appears to be implied from the line right above 'Psyker:'

**Comment by efalsken** [comment]
ah. ok. Will make that change as soon as I am done working with the BS Alpha currently on my system.
