### ISSUE TITLE
Skitarii Rangers/Vanguard Special Weapons bug

### ISSUE THREAD

**Issue by amis92** [BSData/wh40k-7th-edition#2092]
Not sure if bug, but I took it from here:
https://www.facebook.com/groups/2206945593/permalink/10156793603905594/

Pic: 
![image](https://cloud.githubusercontent.com/assets/2671396/14474438/5f23ea66-00fd-11e6-8c27-934e4a2b43b6.png)

**Comment by OftKilted** [comment]
I can duplicate the issue in IOS and in production, but the file appears to be correctly linked.
Flagging @Jonskichov

**Comment by OftKilted** [comment]
![skitarii bug](https://cloud.githubusercontent.com/assets/17132967/14477923/4883e996-00df-11e6-9bfc-988c4d9c059b.png)
![skitariicatalog](https://cloud.githubusercontent.com/assets/17132967/14477975/c1a33750-00df-11e6-88c4-f6ccc7902c1a.png)

**Comment by amis92** [comment]
OP's additional comment:

> Only does it on the battle maniple not Skitarii maniple I noticed too
