### ISSUE TITLE
Enhancement: Space Marines - Codex (2015) - Imperial Space Marine Addition

### ISSUE THREAD

**Issue by ddarz** [BSData/wh40k-7th-edition#2094]
Will add the option to take a single imperial space marine and his rules (the 30th anniversary model), in any compatible squad.

Suggestions very welcome!

**Comment by francoisbeaulieu** [comment]
The stat line appears to be very standard for a tactical marine. Perhaps you could get it done quick and dirty by creating his wargear kit as a relic, limited to one per army and available to all applicable units?

## 

François Beaulieu (iPhone)
(514) 667-0691 x2061

**Comment by ddarz** [comment]
Was thinking of creating him as an entry, with a modifier that will decrease the maximum selections of normal marines by 1
Will consider the relic approach, thanks!

**Comment by afraeve** [comment]
Is he 0-1 per army, or can you put 1 in every unit? There was a full 'Mega Shock Squad' of 9 originally.

**Comment by francoisbeaulieu** [comment]
The profile says "unique" and "replace one space marine".

## 

François Beaulieu (iPhone)
(514) 667-0691 x2061

**Comment by cartag** [comment]
I think it'll be easiest to make a separate entry for it, then link to it with a max of 1 per roster. Link to it in any unit that has a model named "Space Marine" and call it good.

**Comment by DrTobogganMD** [comment]
Might be easiest to make a no force org unit for it. Limit to one per army. And just let players specify which model it is. A lot less linking involved. 

~Earl

**Comment by francoisbeaulieu** [comment]
Won't that make it harder to enforce the "replacement" of the model in the inheriting unit?

**Comment by afraeve** [comment]
I went ahead & integrated him into the supplements. It's more awkward than you'd think.

**Comment by ddarz** [comment]
Just uploaded the first version of this, working for tacs, assaults and devs
Please let me know if there are any issues

Any consencus on whether he can replace a "Veteran"?

**Comment by francoisbeaulieu** [comment]
A strict reading of the rule would indicate that you cannot.

**Comment by ddarz** [comment]
Yeah, shame that
I'd be tempted to accept the implied "Veteran Space Marine" and add the option
After all, the idea is to leave the policing up to the players and be permissive

**Comment by afraeve** [comment]
The veteran is a bit of a stretch, but I'd allow him as an Initiate in a Crusader squad.

**Comment by francoisbeaulieu** [comment]
I'd tend to agree; anything that doesn't have the exact same stat line as the imperial space marine is probably not meant to be allowed.

**Comment by francoisbeaulieu** [comment]
@ddarz has the commit been published yet? I can't seem to find it in the tacs.

**Comment by francoisbeaulieu** [comment]
Has anyone heard from ddarz recently? A few outstanding items left hanging.

**Comment by ddarz** [comment]
Hi mate, sorry for the silence, I have been moving so had no internet till this Monday
And between waiting for the new version of Battlescribe and not having the newest books, I have fallen behind
What have I missed and How would you like to proceed? :)

**Comment by ddarz** [comment]
Just checked and the change has indeed been committed. 
He is available for the Tacs, the devs, and the assault squads

There is a checkbox at the top of the selections :)

**Comment by francoisbeaulieu** [comment]
No worries, just checking that you were ok!
Yeah, for some reason, I needed to delete all data files and refresh in order to see the check box. Also, on iOS, I'm not seeing his weapon profiles when he's selected.

**Comment by ddarz** [comment]
Hmm, actually neither do I on desktop... Could it be due to how he is set up?

He is a share entry, with entries below him for his wargear etc.
Then the relevant squads have him as a linked entry

Gonna test a few things

**Comment by ddarz** [comment]
Ok this was a bit more complicated than it seemed. It may be a BS bug or it was not done as intended.

I created a new group selection in each compatible squad, named "special models". This currently holds only the imperial marine. When he is chosen, he takes up the spot of a normal marine. And his profile shows properly

So this decrements the min and max selections of marines in that squad by 1. And he costs as much as the marine he replaced.

Please try it and let me know if it is acceptable!

**Comment by francoisbeaulieu** [comment]
That seems to work great! Thanks @ddarz

**Comment by ddarz** [comment]
Good to hear! Cheers

**Comment by francoisbeaulieu** [comment]
Darn, found another bug with it; adding the imperial space maribe doesn't seem to increment the count of space marines, which generates an error if you select 2 heavy and/or soecial weapons for a full tac squad. Unless this was intended? Though I remember nothing in the rules directly indicates that it counts as one of the special weapon selections.

**Comment by DrTobogganMD** [comment]
The marine is supposed to replace any single marine in your list, so if you replaced a special weapon dude with him, he'd count I suppose ... but nobody should ever do that.

If @ddarz doesn't have a fix ready for this I'll take a look and throw one in.

**Comment by ddarz** [comment]
Argh... this guy is a lot of trouble for a free model
This one is tricky, the way the tacs (and all the others i guess) are set up is that the special and heavy weapon choices are actually 'marines with a special/heavy weapon'. So they count against the 9 marine limit.
I'll have a think about it, anyone got any suggestions?

**Comment by ddarz** [comment]
argh, this imperial marine guy is so much trouble
And codex space marines has so many weird arbitrary limitations - one heavy and one special but only if 10 men.... Codex adherence...
Anyway, i uploaded a fix, give it a try :)

**Comment by DrTobogganMD** [comment]
As i'm doing the 2.0 re-write I'll see if there's any better way to code him in.  I'm hoping I can.

**Comment by ddarz** [comment]
Sounds good :)

**Comment by Uxion** [comment]
Question, but is the ImpSM supposed to cost 14 points to take?

**Comment by francoisbeaulieu** [comment]
It's free to replace an existing space marine, but you do need to pay the base 14 pts for that marine. That's what those 14pts represent.

**Comment by Uxion** [comment]
Ah, so that is what it meant. I assumed incorrectly that BS took it as an upgrade.
