### ISSUE TITLE
Imperial knights Renegade

### ISSUE THREAD

**Issue by Drachnyen** [BSData/wh40k-7th-edition#2101]
GW just released a new set that include Renegade Imperial knights
(Battle Brothers of CSM and Daemons!)

Need to be added
- Forsworn Detachment
- Imperial Knight Renegade

Thanks,

**Comment by OftKilted** [comment]
This is not an "imperial knight option" it is an alternate force with a "different" codex.

As a side note: the formation and rules have not yet been officially published but are in queue for release at that time. Thank you for your understanding.

**Comment by Drachnyen** [comment]
Yup, its a new faction!

The Imperial Knight Renegade kit (including its rules inside the box) was released last weekend, what do you mean by not officially published?

**Comment by Thairne** [comment]
They were put up for preorders.
Noone has those rules in hand yet, besides some leaked pictures.

**Comment by Drachnyen** [comment]
Ahhh.  I understand, my bad.

Friend of mine visited GW yesterday and was talking about them,  thought they were was already available.

Thanks guys :)

**Comment by cartag** [comment]
Update your data files, it's already in. :)

**Comment by Drachnyen** [comment]
Woah.  You rock @cartag 

Thanks

**Comment by cartag** [comment]
If you can't find it, there's a detachment called "Chaos RK Forsworn Knight Detachment" for the Renegade Knights. They can't be brought as CAD since there's no HQ or Troops, can't be brought as AD either. If anybody reading this looks for them in the CSM file you're gonna have a bad time :+1:
