### ISSUE TITLE
Request for Enhancement - Add Ordinatus Sagittar and Ordinatus Ulator to C:Cult Mech and C:Skitarii

### ISSUE THREAD

**Issue by w0lfang** [BSData/wh40k-7th-edition#2103]
Just wondering if there is any plans of adding this two to the cult mechanicus and skitarri lists sonce they can be taken as low.

Thank you.

**Comment by OftKilted** [comment]
"The Mechanicum Ordinatus Sagittar is a Lords of War choice for Mechanicum armies in Horus Heresy games. **It can also be taken as a Lords of War Choice by Adeptus Mechanicus: Cult Mechanicus and Skitarii armies in games of Warhammer 40,000** using the rules found in The Horus Heresy: Mechanicum – Taghmata Army List." https://www.forgeworld.co.uk/en-WW/Mechanicum-Ordinatus-Sagittar

"The Mechanicum Ordinatus Ulator is a Lords of War choice for Mechanicum armies in Horus Heresy games. **It can also be taken as a Lords of War Choice by Adeptus Mechanicus: Cult Mechanicus and Skitarii armies in games of Warhammer 40,000** using the rules found in The Horus Heresy: Mechanicum – Taghmata Army List." https://www.forgeworld.co.uk/en-WW/Mechanicum-Ordinatus-Ulator

Recommended to be added to the Skitarii and cult mechanicus catalogs as LoW and flagged for ForgeWorld with the book source of the 'Horus Heresy: Mechanicum - Taghmata Army List'
