### ISSUE TITLE
[Anon] Bug report: Space Marines

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#2110]
**File:** Warhammer40K.gstz

**BattleScribe version:** 1.15.09

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** The RAven Guard Talon Strike Force isn't an option in the catalogue.

**Comment by cartag** [comment]
Under Force Type select "SM RG Talon Strike Force"
