### ISSUE TITLE
SM: Sternguard heavy weapons not counted for squad size

### ISSUE THREAD

**Issue by LHSnow** [BSData/wh40k-7th-edition#2112]
Error is reported as "Sternguard Veteran Squad must have two more selections of Veteran (minimum 4)", when picking a sergeant and two heavy weapon veterans.

**Comment by LHSnow** [comment]
Addidition to the description: while also selecting the two regular veterans, so 1sgt+2vet+2hvy

**Comment by Randobar** [comment]
1sgt+3vet+1hvy also gets the error. hvy/special weapon sternguard dont count for unit size

**Comment by DrTobogganMD** [comment]
Tested on Windows and IOS - Cannot replicate. Are you still getting this error? If so, what OS.  I'll leave this open for 10 days otherwise and then close the issue as no longer needed.

**Comment by Randobar** [comment]
I do not get it anymore (PC - Windows)
