### ISSUE TITLE
Eldar Craftworlds: Striking Scorpion Exarch:missing options

### ISSUE THREAD

**Issue by jonnybex** [BSData/wh40k-7th-edition#2114]
There are no options for the Striking scorpion Exarch's Biting blade or Scorpions claw.
should be able to exchange shurican pistol for scorpions claw @30pts
or/ swpat the scorpion chainsword for a biting blade @5pts

Scorpions claw stats: Str x2 AP2 Melee, Range 12 Str 4 AP5 Assault 2 , Bladestorm
Biting Blade Str+2 AP4, melee 2handed

**Comment by TheRedViking** [comment]
The option to do this is a choice in the sword and weapon section
