### ISSUE TITLE
Chaos Khorne Daemonkin. Multiple Artifacts on Daemon prince

### ISSUE THREAD

**Issue by jonnybex** [BSData/wh40k-7th-edition#2115]
The list will not show as valid if you select more than one Artifact of Slaughter for a daemonprince
for example..  bloodforged armor and the axe of ruin.
it is allowed to select multiple artifacts of slaughter for a daemonprince..   just not multiples of the SAME artifact through the army list.

**Comment by cartag** [comment]
No, you can only have one artefact per model. Closing as invalid.
