### ISSUE TITLE
[Anon] Bug report: Space Marines

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#2116]
**File:** Warhammer40K.gstz

**BattleScribe version:** 1.15.09

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Battlescribe (ios) lists Hunting Force, Pinion Battle Demi-Company and Stormlance Battle Demi-Company as Core options for a SM Gladius Strike Force using Ultramarines Chapter Tactics, in addition to a regular Battle Demi-Company.  I have read the Angels of Death supplement and have not seen anything there that specifies that these formations can be a core force in a generic Space Marine Gladius Strike Force -- but maybe I am missing something.  Is this an accepted change in the rules or an extrapolation from the Anges of Death update? Thank you.

**Comment by DrTobogganMD** [comment]
Duplicate of #2117 ... well I guess 2117 is the duplicate, but I'll use that as the tracker.
