### ISSUE TITLE
Home-brew - Ork Codex Update for 7th Ed.

### ISSUE THREAD

**Issue by Space0din** [BSData/wh40k-7th-edition#2127]
I'd like to ask a huge favor of a lot of people: would you guys be willing to host a catalogue for us that is an edit or rebalance of the regular one?

I've been posting the "Codex Orks (2016) 7th Edition Update" around and found no mean demand for it. A small team of us rebalanced the Ork codex to bring it in line with 7th Edition codexes, having inferred that the release (and its supplement) were works of lazy ignorance at best. While technically it qualifies as homebrew, I can assure you that our catalogue is far from wishlisting fan-bloat that I've come across in a search for an alternative to the official product, if that's a consideration.

I understand that this is sort of the repository for official Games Workshop codex releases and such, and I get that--but I believe that the codex re-work that I've collected is simply superior in design and balance to the official material, and I would like to offer this mostly-GW Ork codex alongside the all-GW Ork codex in the repository. And to be fair, take a look at the official release: could I really have done worse than the mooks who looked at a Gorkanaut battling an Imperial Knight and thought, "that smaller one ought to be able to stomp the bigger one?"

This request is pretty audacious, I'll admit freely--take a look at the entries and tell me to eff right off, if you feel like it--but consider that nobody will be losing anything if you accept our request to host the project's final product. I can be reached at [herpderpspam catcher at g mail.com]. Thanks!

**Comment by cartag** [comment]
My understanding for this has been that we just host official stuff. We don't work ITC rules into the files either. If you make a repo for it you may be able to get it hosted on the housing site as a separate army (technically) as a work around.

**Comment by Space0din** [comment]
OK; that would involve just uploading the .cat file, or just making a repo with it and the 40k .gst, yes?

Or should I just send you the .catz?

Thanks for your help & response, btw.

**Comment by Space0din** [comment]
Apparently I'm having trouble with repos; will try a few things if I can't just send you the catalogue file.

**Comment by amis92** [comment]
Okay so the official stance here (I'll take the privilege of admin hat) is, no fan-made/unofficial stuff in main repo.

Which means there is absolutely nothing preventing creation of separate repository like 40k-fanmade, with stuff like Angry Marines etc.

There are some technical difficulties, however. To make the repository appear in (and be downloadable from) Appspot site, a gst file has to exist. So you either:
1. Create (copy) 40k gst for the new repo and re-target the fanmade catalogues; that will prevent combining detachments from official and unofficial catalogues and also make it a separate game system entry in BattleScribe roster editor.
2. Don't create gst; that prevents (currently) from automatic download through BattleScribe data manager and exploration through AppSpot site by interested parties. Essentially it'll be just on GitHub instead of DropBox or another hosting service.
3. Create some placeholder game system to make it discoverable and indexable and available on AppSpot site and ignore it completely down the road; it'll add this position into player's Roster Editor game system choice list.
4. Update AppSpot web app to enable some other configuration which will make discovering no-gst-including repos possible.

As I'm not sure which is best (except 4. but we have no resources to take care of that), I leave this up to discussion.

**Comment by Space0din** [comment]
Huh...I have the .gst & all, but would like it to be usable alongside other codices, like Renegade Knights & other allied lists. I assume this would have to be done under the same game system, so maybe have a separate forked 40k repository that includes all the regular codices from the standard one (ideally they could update with them), plus fandexes?

This would involve making a separate repository that updates with yours but also features fandex options. I also assume this would necessitate someone maintaining it & filtering which fandexes make it in (if anyone else has even made a BS fandex file).

The way I have it working now is the same .gst with only our Ork codex sits in Dropbox by way of my home computer, & BS updates from it & your repo. This makes it so it just appears alongside the normal list of codices in the Roster Editor, but on desktops only--doesn't take for android or iOS devices, probably because the public link is only to the .bsi, but allows no access to the rest of the files they need to pull to run correctly.

Thanks for everything, btw. I can't code for squat & know jack about GitHub, but I'll help however I can.

**Comment by afraeve** [comment]
A second repo with the same gst seems ok to me. We would just need a suitable naming convention so users can tell them apart. Off the cuff, something like "Orks - Homebrew - Space0din.catz", or "Orks - Fandex - YourNameHere.catz".

The obvious concern is that the devs would need to know not to make changes to the gst.

**Comment by OftKilted** [comment]
A completely separate repository (much like the WH40K-HoR-Killteams repo) off the base of BSData would be the best recommendation. (Something like WH40K-Homebrew-Fandex-Codexes perhaps?)

@afraeve "The obvious concern is that the devs would need to know not to make changes to the gst." Are we talking about the standard WH40K gst? or the GST in the Fandex repo?

**Comment by afraeve** [comment]
The fandex repo would have to be forbidden from making changes to the gst.

**Comment by OftKilted** [comment]
Making changes to the GST in the main WH40K repository? or the GST in the fandex repo?

If an 'official catalog WH40K' gst is updated, someone would want/need to update the fandex gst to keep in sync.

Alternatively, If we give the fandex gst a new guid, it's a non-issue. The fandex group could do what they wanted/needed to do. However, that would inhibit them from being able to use the normal WH40K gst. (This would be the number 1. option that was suggested above. Easiest, but limits the ability to use the catalogs easily with other catalogs. (Allies etc would have to be in secondary lists.)

Nominally, the 'fandex/homebrew' gst would mean that they can stay where they are forever. As they have their own 'meta' to work within. They don't have an 'official codex' that they have to fix their catalog to.

**Comment by afraeve** [comment]
> Making changes to the GST in the main WH40K repository? or the GST in the fandex repo?

If both groups use the _same_ gst.

**Comment by amis92** [comment]
Well I think I could talk to @Jonskichov to make a little update to appspot app and go with option 4.

That way we have single gst and we allow optional/additional catalogues to be hosted without messing up things for people not interested.

**Comment by Space0din** [comment]
Here's a link to the BSR, if that's what's eventually needed:
https://www.dropbox.com/s/tq162lrlggtvxnt/Orks.bsr?dl=0

Below are the links to all of the files I used & produced (.catz, .gstz, etc.)
https://www.dropbox.com/s/14degcc5mt83huy/index.bsi?dl=0
https://www.dropbox.com/s/xojl1jigna3sz5r/index.xml?dl=0
https://www.dropbox.com/s/73wi3ylrugbh2kh/Orks%20-%20Homebrew%20Codex%20-%207th%20Ed.%20Update%20%282016%29.catz?dl=0
https://www.dropbox.com/s/7oftfcdvdxsu4vz/Warhammer40K.gstz?dl=0

**Comment by Space0din** [comment]
OK lads, I have the definitive, balanced, complete version of the codex up (v4) in PDF form. I'll be punching in edits to the BSR soon, at which point I'll update my own repo and such.

I still apparently lack some fundamental understanding, though, of how the index files interact with github repos. I guess I have to host the .bsi here, but host links to it somewhere else? Can't find any other x-factors for why my iOS device can't access the files when I update them.

**Comment by amis92** [comment]
We haven't yet done anything in this matter. Refer to new issue BSData/bsdata#112

For now, I'm closing this issue, it'll be revisited when we have progress there.

For questions and chatter how things work, please check out our (quite active) [Gitter channel](https://gitter.im/BSData/wh40k).
