### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by Space0din** [BSData/wh40k-7th-edition#2128]
Drafted the Orks: Homebrew 7th Ed. Codex Update (2016)

Looking to see if I can get the .cat hosted as a separate army on the main page, or to be directed to where it can be done. Thanks.

**Comment by amis92** [comment]
I'll have an eye on issue #2127 and see what we decide upon.

**Comment by amis92** [comment]
As per #2127, it won't be hosted in this repo for sure, so I'm closing this issue.
