### ISSUE TITLE
[Anon] Bug report: Officio Assassinorum Dataslate (2014).catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#2135]
**File:** Officio Assassinorum Dataslate (2014).catz

**BattleScribe version:** 1.15.07

**Platform:** Windows

**Dropbox:** No

**Description:** Officio Assassinorum - shows validation errors that can't be removed when using this force as an ally (requests that you add an HQ choice when there are no HQ choices for this dataslate)

**Comment by hisop** [comment]
"As an ally" - you cant use an allied detachment for Officio Assassinorum Dataslate, you can only use an allied detachment if you have HQ and troop selections. you need to use the appropriate formation type : 
![image](https://cloud.githubusercontent.com/assets/7855347/15045706/f4ad6066-12d3-11e6-8a05-85ef5be4c654.png)
