### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by SentryTheDefiant** [BSData/wh40k-7th-edition#214]
Hello,
My name is Justin. I'm new to GitHub, but not the BSCatEditor. I play Eldar, and Dark Angels, and would like to help with upkeep on those files as well as be able to handle requests from other factions that arise on the BSData G+ page.

**Comment by amis92** [comment]
Invitation sent. Welcome!

**Comment by SentryTheDefiant** [comment]
Thanks so much! I can't wait until I can really start contributing. I may need some handholding on the github aspect of it, but it sounds like a really powerful system, and I can't wait to use it.
