### ISSUE TITLE
Flyer profile separation from Vehicle profile type

### ISSUE THREAD

**Issue by amis92** [BSData/wh40k-7th-edition#2140]
The aim of this enhancement is that because of the new Death from the Skies ruleset we have to accommodate some new stats for Flyers. After a discussion on Gitter the team has agreed to rewrite all profiles of Flyer vehicles as a separate Profile Type with additional characteristics.

In effect, Flyers won't show up in profile summary of Vehicles, instead they'll get their own profile table in roster view.

The work that has to be done:
- [x] Create XSLT to use with [BS-xml-resharper tool](https://github.com/amis92/bs-xml-reshaper);
- [x] Add new Flyer ProfileType to Game System;
- [x] Rewrite Flyer profiles as new ProfileType in all catalogues simultaneously (using the tool mentioned earlier) - this will change ProfileType of Flyer profiles and create new empty (N/A) characteristics for them: Combat Role, Pursuit, Agility;
- [x] ~~Fill those new characteristics for every Flyer that has them in Death from the Skies.~~

That should be enough. Any thoughts?

**Comment by cartag** [comment]
If you haven't added the Flyer profile I can update it, upload GST, and send you the UID.

**Comment by cartag** [comment]
Flyer profile - 3a08-ea03-a598-8615
BS - 9878-e3f6-b7b4-7225
Front - 3a4e-bc1d-4a12-7176
Side - 3a08-ea03-a598-8615
Rear - a4cb-791a-6a75-4e4a
HP - 3a08-ea03-a598-8615
Type - eb65-838c-8eaa-8b5d
Combat Role - d477-c087-173f-9f1c
Pursuit - e04d-332e-8b52-0071
Agility - ae34-f5c0-19af-4883

Uploading shortly.

**Comment by amis92** [comment]
Thanks for reference, but I've got'em from gst you've pushed. And safer that way, seems you got Side ID wrong. :D

Now, the XSLT is ready and works as expected. Available here https://gist.github.com/amis92/5a35e345c43a12557571cf5ff6e2a211

**Comment by amis92** [comment]
Okay, I've also updated the reshaper tool while at it. It's now even easier: Just copy the .exe and .xsl into folder full of catalogues and run. :D https://github.com/amis92/bs-xml-reshaper/releases/latest

**Comment by amis92** [comment]
Well, that means we need only the last thing: fill the profiles according to the book. That should be another issue.
