### ISSUE TITLE
Bug Report: Eldar Craftworlds - Codex(2015)

### ISSUE THREAD

**Issue by Belgarath81** [BSData/wh40k-7th-edition#2141]
The seer counsel formation lacks the ability to put the entire formation on jetbiks.

**Comment by efalsken** [comment]
The seer council is a formation of multiple units. Each unit has the option to take a jetbike separately. Go into each unit and you will see the Jetbike option. You are not required to take the Jetbike for every unit in the formation, each is optional.

![image](https://cloud.githubusercontent.com/assets/253640/15119655/cbac6784-15c6-11e6-8612-457b62d014f3.png)

**Comment by Belgarath81** [comment]
My apologies. Turns out I was using the wrong eldar codex. I thought the v22 was the more up to date one.
