### ISSUE TITLE
Fill new Flyer characteristics from 'Death from the Skies'

### ISSUE THREAD

**Issue by amis92** [BSData/wh40k-7th-edition#2143]
Flyer profiles were rewritten to accommodate for these new characteristics as per #2140.

Now we need to put actual values instead of N/A

That's up to you guys, I'm done for now :)

_edit: checklist from @Kohato's comment_
- [x] Adepta Sororitas
- [x] Astra Militarum
- [x] Blood Angels
- [x] Chaos - Khorne Daemonkin
- [x] Chaos Daemons
- [x] Chaos Space Marines
- [x] Cult Mechanicus
- [x] Dark Angels
- [x] Dark Eldar
- [x] Deathwatch
- [x] Eldar Craftworlds
- [x] Grey Knights
- [x] Harlequins
- [x] Imperial Knights
- [x] Inquisition
- [x] Legion of the Damned
- [x] Militarum Tempestus
- [x] Necrons
- [x] Orks
- [x] Skitarii
- [x] Space Marines
- [x] Space Wolves
- [x] Tau
- [x] Tyranids

**Comment by afraeve** [comment]
Modifiers linked to these profiles need reset - it looks like just the field where you select BS/Armour/Type/etc.

**Comment by efalsken** [comment]
I just updated profiles and units for Tau and Eldar. I added a shared rule for the Wing Leader, but did not actually add it to the new wings, since IMHO it applies only to a Death From the Skies mission/campaign.

**Comment by DrTobogganMD** [comment]
Agreed on Wing Leader.  Added Units/Wings to C:SM today.

**Comment by tag8833** [comment]
I've got Orks done.

**Comment by DrTobogganMD** [comment]
Added Necrons.

**Comment by DrTobogganMD** [comment]
Adding a Checklist for us so we can quickly add the remaining ones if we have time.

_checklist moved to top ~amis92_

**Comment by amis92** [comment]
Okay, I marked Cult Mechanicus, Deathwatch, Harlequins, Imperial Knights, Legion of the Damned, Skitarii and Tyranids, 'cause they have no flyers.

**Comment by hisop** [comment]
Inquisition done, Sisters flyers are N/A GK done.
