### ISSUE TITLE
Space Marines Angels of Death Items

### ISSUE THREAD

**Issue by DrTobogganMD** [BSData/wh40k-7th-edition#2146]
Are the Angels of Death relics and chapter tactics going to be added to the SM Codex prior to the 2.0 update or is the codex on freeze until then?

**Comment by cartag** [comment]
As it stands right now, the person who's been updating C:SM hasn't been on since December. I don't know if anybody else has taken it up.

**Comment by penguin20000** [comment]
I believe this is already being discussed in #2105 fyi ;)

**Comment by DrTobogganMD** [comment]
Closing as duplicate while I work on #2105
