### ISSUE TITLE
Sternhammer Strike Force

### ISSUE THREAD

**Issue by SpearofDorn** [BSData/wh40k-7th-edition#2152]
The Sternhammer is missing some elements (Mostly Auxiliary choices):

Specifically:

Core - 
Centurion Siegebreaker Cohort

Auxilliary - (First three are from Angels of Death)
Skyhammer Orbital Strike Force
Skyhammer Annihilation Force
Raptor Wing
The rest aren't formations, just units:
Devastator Squad
Centurion Assault Squad
Centurion Devastator Squad
Vindicators (Listed as "Line Breakers")
Thunderfire Cannons (Listed as "Ordnance")
Ironclad or Contemptor Dreadnoughts (Listed as "Siege Ancients")

Also, the Sternhammer does not get the Centurion Siegebreaker Cohort as an Auxilliary choice.

Thanks for all the work you do.

**Comment by DrTobogganMD** [comment]
This is part of the Angels of Death enhancements.  The new detachments aren't 100% functional yet. They are currently being worked on in #2105
