### ISSUE TITLE
Bug Report: Space Marines, Forgeworld chapter tactis

### ISSUE THREAD

**Issue by tag8833** [BSData/wh40k-7th-edition#2154]
Silas Alberec shows up as an HQ choice for marine chapters using the Raptor chapter tactics on Battlescribe.  Mr. Alberec is actually an Exorcist.

**Comment by afraeve** [comment]
Alberec is available to all, just like a vanilla Captain, 'cos Exorcists don't have their own Chapter Tactics.

I was wondering if I should've included him in the Clan Raukaan & Sentinels of Terra files.

**Comment by DrTobogganMD** [comment]
Closing this bug - Confirmed, Exorcists Chapter tactics are simply whatever tactics the player chooses, so Silas is available to all.
