### ISSUE TITLE
On Space Marines "Angels of Death". If you select a chapter you do not get access to Legion Specific (i.e. Iron Hands) Chapter Relics

### ISSUE THREAD

**Issue by lhavoc1** [BSData/wh40k-7th-edition#2168]

**Comment by DrTobogganMD** [comment]
Known - Been working on that fix next :) Hopefully soon.

**Comment by pc0r31lly** [comment]
I cant even find Angels of Death? How do i access it???

**Comment by DrTobogganMD** [comment]
The formations are rolled into the base marine codex.  the detchments are selected when adding a force.

Relics aren't quite done yet - today perhaps.

**Comment by pc0r31lly** [comment]
Ah right, in the standard marine codex i cant see the unit updates (terminator captain, contemptor dread, catarpractii terminators, stormhawk interceptor)

Have these just not been updated yet?

**Comment by pc0r31lly** [comment]
Thanks for the quick reply btw :-)

**Comment by DrTobogganMD** [comment]
AOD/DftS is fully implemented as of my commit an hour ago - but the appspot repository hasn't been updated yet so you won't see those until it is.

**Comment by pc0r31lly** [comment]
thanks a lot for your help mate, much appreciated
