### ISSUE TITLE
Land raider limited to only 1 per roster

### ISSUE THREAD

**Issue by peterlyberth** [BSData/wh40k-7th-edition#217]
Adding more than 2 Landraiders gives an error.
It seems like you are only able to add 1 land raider of each type to the roster.

**Comment by amis92** [comment]
I found it, probably. For some reason there are modifiers on links to Land Raider dedicated transport option in Terminator Squad/ Terminator Assault Squad. They set maxInRoster to 1. I know not any rule saying anything like that.

**Comment by peterlyberth** [comment]
That was it.
Corrected the error and made a pull request.

**Comment by amis92** [comment]
Cool. You can also close issues from commit title, for example adding "closes #xx" the commit (after upload) will close the issue automatically.

**Comment by peterlyberth** [comment]
Nice. I'll try to remember that!
