### ISSUE TITLE
Hi setting up 40k repository for Battle Scribe  thanks

### ISSUE THREAD

**Issue by Steven-Kamalabaskaran** [BSData/wh40k-7th-edition#2170]

**Comment by cartag** [comment]
What are you asking exactly?

**Comment by amis92** [comment]
http://battlescribedata.appspot.com/#/repos
1. Download BattleScribe (link in website linked above)
   2a. On mobile click on Warhammer 40k in the above website; that'll download .bsi file and BattleScribe will add that repo to Manage Data list.
   2b. On PC right-click on Warhammer 40k link in website above, click `Copy link` or similar, and paste it in Manage Data screen of BattleScribe, and click Add.
2. Click `Update Data`.

If you asked for something else, please respond with a little bit more precise description of your problem.
