### ISSUE TITLE
Correction to Angels of Death Suppliment IF Sterhammer Stike Force

### ISSUE THREAD

**Issue by TDog117** [BSData/wh40k-7th-edition#2171]
For the IF Sternhammer Strike Force, both the Battle Demi Company and the Centurion seigebreaker cohort formations are both core choice options for the formation.

Also missing from the Auxiliary options are the formations: Strike Force Ultra, Skyhammer Orbital Strike Force, Skyhammer Annihilation Force and Raptor Wing.

And the Sternhammer only auxiliary formations: Devastators, Centurions, Line Breakers, Ordnance and Siege Ancients

**Comment by DrTobogganMD** [comment]
This has been fixed in #2162 and is waiting for a repository update.
