### ISSUE TITLE
Bug Report Codex: Space Marines

### ISSUE THREAD

**Issue by TDog117** [BSData/wh40k-7th-edition#2183]
When selecting a raptor wing formation
'Raptor Wing\* must have 1 more selections of Stormtalon Gunship (minimum 2) set minSelections to 2

There is no option for a second Stormtalon and when you duplicate it:

'Raptor Wing \* has 1 too many selections from Stormtalong Gunship (maximum 1)

**Comment by DrTobogganMD** [comment]
Confirmed and fixed - closing with future pull.
