### ISSUE TITLE
Angels of Death - Contempter Dreadnought

### ISSUE THREAD

**Issue by merlinbk** [BSData/wh40k-7th-edition#2185]
Has anyone put in the Contemptor Dreadnought, updated the Terminator Captain, or added Cataphractii/Terminators into the Space Marines?

**Comment by DrTobogganMD** [comment]
Duplicate of #2182 

Should be fixed by end of day.

**Comment by merlinbk** [comment]
Was this fixed? I updated my data and I still don't see it.

**Comment by hisop** [comment]
The fix has not been made public yet. i will push at the end of today.
