### ISSUE TITLE
Add thunderhawk interceptor (new flier for SM)

### ISSUE THREAD

**Issue by arabviking** [BSData/wh40k-7th-edition#2195]
Hey

I see you haven't added the unit profile of the new Thunderhawk interceptor yet, it is from the new death from the skies supplement. It can be added as a fast attack option for regular space marines. Not sure about BA/SW/GK etc.

**Comment by DrTobogganMD** [comment]
Confirmed - forgot this one when I added flyers yesterday.  I'll add it tonight.
