### ISSUE TITLE
White Scars Relic Issue

### ISSUE THREAD

**Issue by yabooz21** [BSData/wh40k-7th-edition#2202]
I am unable to access the librarian only relic: Mantle of the Stormseer through the librarius conclave formation. I am able to access some of the Chogoris relics but I am unable to access the Mantle. Am I missing something or is it just an issue that needs to be fixed? Thank you.

**Comment by DrTobogganMD** [comment]
Do you have White Scars Chapter Tactics selected?  It will not show unless you do.

**Comment by yabooz21** [comment]
Yes, I do. I have the hunter's eye equipped to one of them but I can't access the mantle.

**Comment by DrTobogganMD** [comment]
What version codex? I'm not sure if my latest changes have been pushed yet.

**Comment by yabooz21** [comment]
The relics were updated in Kauyon and the new angels of death codex but I am accessing it through the Space Marine 2015 Codex. I have access to 4 of the relics from the Chogoris list but I do not have access to The Mantle of the Stormseer or The Banner of the Eagle. Also, when I select the Chapter Relics, it gives me the generic Space Marine relics from the 2015 SM Codex.

**Comment by DrTobogganMD** [comment]
Alright, sounds like the changes haven't been pushed to appspot yet.  I've implemented DftS and AoD as of last Friday.  Once the catalogs get wrapped up again you should see the rest of the relics.

The current codex version is 63.  You can check the one your device has by going to Add Force. The version numbers are at the tail end of the Catalogue you select.  If C:SM isn't 63 then you'll need to wait until we roll up the changes (usually once every week or two)

**Comment by yabooz21** [comment]
Thank you very much.
