### ISSUE TITLE
Space Marine Bike squads disappear completely when Character selected with bike

### ISSUE THREAD

**Issue by athelred** [BSData/wh40k-7th-edition#2212]
Issue:

Bike squads in the space marine v. 63 data file disappear completely when you select a space marine bike as an option for a HQ choice.  When the bike option is de-selected the reappear as a fast attack choice

Expected behavior:

Bike squads should disappear as a fast attack choice, and appear as a troops choice when a HQ choice selects a Space marine bike as a wargear choice.

**Comment by DrTobogganMD** [comment]
Confirmed - When attempting to fix the show/hide bug in iOS I flipped a conditional.  This is now fixed and will be pushed today.
