### ISSUE TITLE
Weapon relics not available for Iron Hand characters

### ISSUE THREAD

**Issue by athelred** [BSData/wh40k-7th-edition#2214]
Issue:

A character with the Iron Hands Chapter tactics cannot select the mindforge stave (librarians), Axe of Medusa, or Betrayer's bane as weapon options.  The three non-weapon relics are selectable as expected.

Expected Behavior:

The weapon relics should be selectable as a replacement for the characters CCW\Bolt Pistol.

This also applies to the other chapter specific relics.

**Comment by DrTobogganMD** [comment]
Same issue as #2213 at the root. Closing this issue and will work on it from 2213.
