### ISSUE TITLE
Correction Codex: Space Marine Sternhammer Strike Force 

### ISSUE THREAD

**Issue by TDog117** [BSData/wh40k-7th-edition#2225]
When using the Sentinels of Terra codex option the "Devastators" Auxiliary when picked includes a drop pod that cannot be removed or changed and adds no additional cost to the unit.

**Comment by DrTobogganMD** [comment]
Wasn't Sentinels of Terra rolled into the Angels of Death supplement?

**Comment by DrTobogganMD** [comment]
It also appears that the Sentinels of Terra book does not allow you to use it along with another supplement - so using it with a Sternhammer would not be allowed:

"Note that you can only use the options from one codex supplement when choosing a detachment."
p121 of the digital codex.

**Comment by DrTobogganMD** [comment]
Sentinels of Terra's force does not allow the use of Sternhammer. Closing the issue.
