### ISSUE TITLE
[Bug] Codex: Space Marine - White Scars missing relics

### ISSUE THREAD

**Issue by Uxion** [BSData/wh40k-7th-edition#2228]
File:Space Marines - Codex.catz

BattleScribe version: 1.15.07

Platform: PC/Windows

Description: 
White Scars relics unavailable:
- Glaive of Vengeance
- Scimitar of the Great Khan

**Comment by DrTobogganMD** [comment]
Issue fixed in #2219 - not yet pushed to main repo. Should be soon-ish.
