### ISSUE TITLE
[Bug] Space Marine Codex: Bike squad does not show up for Troops choice when HQ takes bike

### ISSUE THREAD

**Issue by Uxion** [BSData/wh40k-7th-edition#2229]
File:Space Marines - Codex

BattleScribe version: 1.15.07

Platform: PC/Windows

Description: 
When a HQ model takes a bike, the Bike Squad option from the Fast Attack disappear, but doesn't appear in the Troops category.

**Comment by DrTobogganMD** [comment]
Issue fixed in #2227 - not yet pushed to main repo. Should be soon-ish.
