### ISSUE TITLE
C:SM - Add Captain Centos

### ISSUE THREAD

**Issue by DrTobogganMD** [BSData/wh40k-7th-edition#2245]
![captain-centos-rules](https://cloud.githubusercontent.com/assets/16939161/15756617/a51af2de-28c7-11e6-8ec2-e1a27b46abf3.jpg)

Opening the issue to remind myself to add him this weekend.  According to GW's FB response - he is a free upgrade to any captain and comes with fixed wargear - IE: not allowed to take upgrades.

![captain-centos-how-to-filed-rules-pdf-gw-472x199](https://cloud.githubusercontent.com/assets/16939161/15756717/1c3c3ddc-28c8-11e6-9da7-be4c36274cc4.jpg)

**Comment by Shiney1965** [comment]
Hi - thank you for this. I was wondering if could you also add the 30th Anniversary Space Marine as a space marine upgrade option at some point?  It has its own rules but can substituted for any space marine for the same points (if you have the model). Thanks

**Comment by DrTobogganMD** [comment]
The marine is already present in the file :)

**Comment by Shiney1965** [comment]
Thanks for letting me know but I'm not able to find the option for the 30th Anniversary marine  I'm using the Apple iOS version of BS at the moment. Can you tell me where to find the if ease or option for the marine?  Thanks

**Comment by DrTobogganMD** [comment]
He's listed as an upgrade under "Special Models" of any tactical squad or assault squad.

**Comment by Shiney1965** [comment]
Maybe it's an iOS issue but on the iPhone app I don't see "special models" anywhere for tac or assault squads. I have version 1.15.09 which seems to be the current version. The data file is version 44 for WH4k 7th edition. Thanks

**Comment by DrTobogganMD** [comment]
What version of C:SM? Current that was pushed to appspot is 67.

On Sat, Jun 4, 2016 at 1:01 PM, Shiney1965 notifications@github.com wrote:

> Maybe it's an iOS issue but on the iPhone app I don't see "special models"
> anywhere for tac or assault squads. I have version 1.15.09 which seems to
> be the current version. The data file is version 44 for WH4k 7th edition.
> Thanks
> 
> Sent from my iPhone
> 
> > On Jun 4, 2016, at 12:17 PM, Earl Bishop notifications@github.com
> > wrote:
> > 
> > He's listed as an upgrade under "Special Models" of any tactical squad
> > or assault squad.
> > 
> > —
> > You are receiving this because you commented.
> > Reply to this email directly, view it on GitHub, or mute the thread.
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> https://github.com/BSData/wh40k/issues/2245#issuecomment-223769419, or mute
> the thread
> https://github.com/notifications/unsubscribe/AQJ4mSQQB_CLnUrc7SO7prgDPq-YmkHbks5qIb1ugaJpZM4Is2xv
> .

## 

~
Earl Bishop
815-405-7187

**Comment by francoisbeaulieu** [comment]
It works on iOS. You may need to delete all data files and re-download them. I had to do just that to get it to show up.

## 

François Beaulieu (iPhone)
(514) 667-0691 x2061

**Comment by Shiney1965** [comment]
I'll try that thanks.

**Comment by Shiney1965** [comment]
That worked, got it now. Thanks!
