### ISSUE TITLE
GST SM: Scarblade Force Bug - No Command Allowed

### ISSUE THREAD

**Issue by wm95414125** [BSData/wh40k-7th-edition#2254]
White scars scar blade strike force says you cannot take a strike force command as a command formation, when this is allowed in the e-book codex

**Comment by DrTobogganMD** [comment]
What OS/Codex version are you on? It is set to be allowed for all except Anvil Strike force.

**Comment by wm95414125** [comment]
Version 1.15.09 of BattleScribe and v67 of the codex (updated it just before I posted). I have the SM WS Scarblade Strike Force with chapter tactics white scars and one Core and one Auxiliary selection. Then I add strike force command and it says I have too many selections from Command.

**Comment by DrTobogganMD** [comment]
Confirmed - not an issue with C:SM, issue with GST. Will fix tonight.

**Comment by wm95414125** [comment]
Awesome - thanks mate
