### ISSUE TITLE
[Anon] Bug report: Chaos Renegade Knights.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#2258]
**File:** Chaos Renegade Knights.catz

**BattleScribe version:** 1.15.07

**Platform:** Windows

**Dropbox:** Yes

**Description:** Chaos Renegade Knights v2 by cartag gives no option for selections under Formation Detachment.  Should allow the Forsworn Knight Detachment listed on page 5 of the Imperial Knights Renegade box set supplement.

**Comment by cartag** [comment]
That's not a formation, it's a detachment. If you scroll down farther than Formation Detachment you'll see it listed as Chaos RK Forsworn Knight Detachment, or something to that effect.
