### ISSUE TITLE
Salamander Relict Nocturnes Fury

### ISSUE THREAD

**Issue by Samueras** [BSData/wh40k-7th-edition#2262]
Angels of Death page 95 states that Noctunes Fury may only be taken by a model that may take items from the Special Weapons list. Replaces that model’s boltgun. So Every Tactial Troop should be able to take it but HQ like the Captain etc. because they can't take Special Weapon normaly. I think the Best Soultion would be to Integrate it to the Special Weaponslist instead of the Nomal Chapter Relict List.

**Comment by DrTobogganMD** [comment]
Fixed in #2253 - not yet pushed to appspot
