### ISSUE TITLE
Space Wolves - Wolf Guard Thunderstrike formation TH/SS Terminator

### ISSUE THREAD

**Issue by SuperPranx** [BSData/wh40k-7th-edition#2263]
When adding a TH/SS terminator, the Thunder Hammer requires that you add it separately and is not included by default for some reason.

**Comment by DrTobogganMD** [comment]
I don't have the SW file handy to look at but you could make it the default selection for 0 points on an entry group of possible weapons.

**Comment by DrTobogganMD** [comment]
Looks like this is only the case for the leader.  The normal guys don't have it as a choice - it's just a link to the profile.  Fixing it now.
