### ISSUE TITLE
Space Marines - Iron Hands - Mindforge Stave

### ISSUE THREAD

**Issue by Salrantol** [BSData/wh40k-7th-edition#2268]
The ordinary option for Librarians to take Relics in the current setup is to replace their ranged weapon. The Iron Hands relic "The Mindforge Stave," however, replaces the Force Weapon. With the current setup, you can't select The Mindforge Stave and a normal Ranged Weapon option, but, per Angels of Death, that's what the model would be equipped with?
Should we move it into the Force Weapon entry group?

I guess this is more of an etiquette question, since I'm the new guy around here--how much are we expected to discuss changes before we make them? If I see something like this, do I just move it and say "Look! I fixed it!" or do I post something like this looking for feedback beforehand?

**Comment by Salrantol** [comment]
Left open only for etiquette question.

**Comment by DrTobogganMD** [comment]
I did minimal implementation for the Angels of death relics as I'm rewriting the entire catalog for 2.0. Feel free to fix for this and submit a pull request. I'll check it out and merge. 

~Earl

**Comment by DrTobogganMD** [comment]
As for etiquette, yea we discuss changes here and in gitter. Catalog keepers are supposed to make sure their catalog is maintained but do not own it outright. So if you have fixes you can make go ahead and I can look at the merge request to make sure it doesn't conflict with other things. Just make sure you get the latest cat file from github before you make changes. 

~Earl

**Comment by amis92** [comment]
@Salrantol I think that this issue was actually closed by b23520dc0b997e70a3f56d85222347487b5a0daf.

Please remember to either mention issue number in commit message, or like I've done here, mention commit sha in comment before closing. :) Keep up the good work, I'm just trying to help you better collaborate here ;)
