### ISSUE TITLE
Space Wolves - Wolf Scout weapons not in the model's entry

### ISSUE THREAD

**Issue by SuperPranx** [BSData/wh40k-7th-edition#2270]
The way it's displayed now, the only place that a Bolt Pistol/CCW/Sniper is mentioned is in the Weapons table, not in a model's profile. Now, I understand that all the scouts have pistols, but the way it is now is unclear. Implied weapon profiles lead to confusion. Having it next to the scout's name is fine for differentiation purposes, but it should also be listed for the model's entry.

**Comment by amis92** [comment]
@Salrantol if you close an issue that's not labeled as invalid, unresolved, deprecated etc, you should provide a reason for it. Right now there is no hint as to whether it was resolved and if so, how.

A good read through [Development cycle wiki](https://github.com/BSData/bsdata/wiki/Developer-Guide#development-cycle) will help with it, take a closer look on bullet points 4 & 7.

Just a friendly reminder :)

**Comment by Salrantol** [comment]
Well, I put "Closes #XXXX" in my update text, but for some unknown reason it didn't close the issue.

**Comment by SuperPranx** [comment]
And it still works the same. The weapons don't appear in the model entries... just in the table.
I'll fix it. I'm already half-way through.
