### ISSUE TITLE
Space marines - Terminator captain options point cost

### ISSUE THREAD

**Issue by Pathdoesnotexist** [BSData/wh40k-7th-edition#2276]
File: Codex (2015) v67 by Earl Bishop

BattleScribe version: v1.15.07

Platform: Win

Dropbox: No

Description: Wrong point cost for sm captain in all types of terminator armor:
Storm bolter arm:
-Lighting claw 15 // Right cost is 10
-Thunder hammer 15 // Right cost is 25
Power weapon arm:
-Thunder hammer 25 // Right cost is 15

**Comment by francoisbeaulieu** [comment]
While we're at it, on iOS, a captain in terminator armour has an empty chapter relics list.

**Comment by Pathdoesnotexist** [comment]
On Windows too
