### ISSUE TITLE
Space Wolves: Codex (2014) v3 - Relics of the Fang

### ISSUE THREAD

**Issue by Xianator** [BSData/wh40k-7th-edition#228]
Helm of Durfast & The Wulfen Stone should both be able to be chosen as Wargear for one character.

Affected units:  Wolf Lord, Wolf Guard Battle Leader, Wolf Priest, Rune Priest.

**Comment by ghost** [comment]
No; a model can only have one relic. The difference with the Helm, Stone & Armour is that the character keeps their original weapons.

**Comment by Xianator** [comment]
The codex does not restrict characters to a single relic...  the only restriction is that each relic can only be selected once in an army.

**Comment by coruptcopy** [comment]
Didn't we already discuss this one last night? :-p It doesn't say "only"
one weapon may be replaced, so shouldn't you be able to replace any weapon
for a Relic, hence if you have 2 weapons or want a Relic that doesn't
require you to replace a weapon, you can take 2 or possibly even more
Relics. That's my reading but again, this is debatable. See #230 and
dakkadakka for more discussion.

The codex does not restrict characters to a single relic... the only
restriction is that each relic can only be selected once in an army.

**Comment by Xianator** [comment]
Codex: Space Marines has Chapter Relics which are written in the same manner and the BattleScribe roster allows for multiples to be taken on a Space Marine Captain.

**Comment by coruptcopy** [comment]
Wording for Relics is the same in CSM, Dark Angels, and Space Marines. So
again, I think you're right. You should be able to take more than one per
model. The Ork codex is worded differently: "A model can take one of the
following," so can a warboss take two different Gifts of Gork and Mork?
Makes me wonder, since other options on the Orks say: "A model can take up
to one of each of the following." This makes me sad for my Orks, but I'm
off topic. :-p

**Comment by Xianator** [comment]
I can only imagine the time and effort that goes into putting together an army list tool like this.  So, thanks for the care and attention being put into this.

**Comment by coruptcopy** [comment]
Ditto. You guys are amazing. I've only worked on a few catalogs and you
guys always beat me to it and make it much cleaner than I could. Bravo. :-D
keep up the amazing work.
