### ISSUE TITLE
Captain Centos

### ISSUE THREAD

**Issue by SirLNK** [BSData/wh40k-7th-edition#2291]
Please include Captain Centos (from the 100th store opening) as an option under Space Marines: Codex (2015) - SM Gladius Strike Force - Core - Battle Demi Company*(350pts)-Captain option as well as a general option for space marines.  I've attached the stat sheet that he came with to help.

[Captain Centos and Imperial Space marine 2016 Data Slates.pdf](https://github.com/BSData/wh40k/files/316653/Captain.Centos.and.Imperial.Space.marine.2016.Data.Slates.pdf)

**Comment by DrTobogganMD** [comment]
He's already present in the file as a normal Captain Upgrade - The various AoD formations aren't set up in the most logical way so I'll have to copy him over there. I'll get it done this week.

**Comment by DrTobogganMD** [comment]
Actually - I added him as a "No Catagory" option for 0 points as he is a free upgrade.  I'm re-writing C:SM for 2.0 and have him implemented fully as he should be.  Too much duplicate work to implement into the cluster that is C:SM's datafile when I'm overhauling it anyway.

You can just add him as No Category and then specify which captain he is replacing in your army.

**Comment by SirLNK** [comment]
Thank you!

Date: Wed, 15 Jun 2016 11:20:52 -0700

**Comment by DrTobogganMD** [comment]
Looks like he is not showing in Gladius though.  Fixing now.

**Comment by DrTobogganMD** [comment]
Ok pushing a fix later tonight ... Apparently I can't upload a new cat file right now.  The dirty fix will be as follows - so you know.

First, you need Ultramarines Chapter Tactics for him to show.  In CAD he'll be in "No Force Org Slot", in Gladius, he'll be in No Category.  Don't ask why - the whole cat file is a big mess.  It'll be prettier soon.

**Comment by SirLNK** [comment]
I don't know if you get thanked by anyone, but I want to say that I really appreciate the time and hard work you guys put into this program.  You ARE appreciated!!!

Get Outlook for Android

On Wed, Jun 15, 2016 at 11:33 AM -0700, "Earl Bishop" notifications@github.com wrote:

Ok pushing a fix now.  The dirty fix will be as follows - so you know.

First, you need Ultramarines Chapter Tactics for him to show.  In CAD he'll be in "No Force Org Slot", in Gladius, he'll be in No Category.  Don't ask why - the whole cat file is a big mess.  It'll be prettier soon.

---

**Comment by DrTobogganMD** [comment]
Thanks :) We hope you'll like 2.0 when it drops. Jon has some really nice enhancements that lets us data guys streamline the codexes a good bit.

I was able to get a change uploaded but the diff file is 14,000 line changes ... so something done goofed.  I'll re-attempt it tonight.  For now, centos works fine in CAD as long as you select Ultramarines Tactics.
