### ISSUE TITLE
Mindforge Stave points error

### ISSUE THREAD

**Issue by Salrantol** [BSData/wh40k-7th-edition#2293]
Whichever idiot did the totally awesome implementation of the Mindforge Stave as a Force Weapon option had the totally moronic oversight of forgetting to put the point cost in.

**Comment by francoisbeaulieu** [comment]
@Salrantol you realize that everybody can read these comments, right?

**Comment by Salrantol** [comment]
Yes. I was also the idiot who forgot the points.
