### ISSUE TITLE
PC - Slow, Hanging Up, Black Screen, etc, etc

### ISSUE THREAD

**Issue by JusticarGames** [BSData/wh40k-7th-edition#2295]
Came on here to see if anyone has made a post regarding this. I've never had any actual problems with the program it's self as far as how it runs and such but ever since the last update this thing is slow,  hanging up quite frequently to the point to where it just black screens and has to catch up to function again. This happens when just doing your typical task, selecting units, formations, codices, etc, etc. Something seems broken somewhere.

This is happening on both my home computer and on a different computer, both are Windows OS.

Help :-)

**Comment by hisop** [comment]
Battlescribe update or BSData update? if its a battle scribe problem i will direct you to the right location.

**Comment by DrTobogganMD** [comment]
Also - in what codex are you working in. Multiple or just 1?

**Comment by JusticarGames** [comment]
Sorry for the vague report, was at work. The problem is with Battle Scribe while using it to make Warhammer 40k list. I currently make list for Space Wolves and Tau.

I have been experiencing small delays while making multiple list while selecting units, wargear or any type of options that require you to click something. Literally just the small actions required to make a list are being delayed.

The hard hang ups seem to happen when Adding multiple formations, combined arm detachments to my list. When you click add and then select whatever you want it sometimes takes 5+ seconds for that specific formation and/or detachment to generate and appear. Sometimes when doing this the entire program goes BLACK. I would have to estimate the longest hangup I've had so far until the program recovered was probably 15 seconds.

As I said in my OP this is happening on two computers so I figured I should make a post about it. I'll monitor this throughout the day to provide any other feedback if needed.

**Comment by DrTobogganMD** [comment]
Hmm, possibly catalog based ... Space wolves is nearly the size of C:SM and is very clunky as a result.  Tau however is not. That's a normal sized cat file.

What BS version are you using, and have you wiped/reinstalled recently?

**Comment by JusticarGames** [comment]
BS v1.15.07

I'll uninstall/wipe when I get home and see how things go. Thanks for the info guys.

**Comment by DrTobogganMD** [comment]
Yea, you're current.  That behavior is indicative of a lot going on in the background.  Like, you'd see it when enabling FW models in C:SM because of how many items are being unhidden.

But on a catalog like Tau ... there should be no reason for that.  Not that I'm calling your computer a potato, but next time you get it to happen, check your processes.  Is Java spiking at the hangs?
