### ISSUE TITLE
GK & Inquisition APoc formations & Fighter Aces

### ISSUE THREAD

**Issue by Gary-B2** [BSData/wh40k-7th-edition#23]

**Comment by Gary-B2** [comment]
Fighter Aces - Storm Raven & Valkyrie
Super-heavy Flyers rules - Thunderhawk
Fear, Invincible Behemoth

Apoc formations
Brothers of the Flame
Dreadknight breathren
Extermination Force
Librarius
Both Thunderhawk versions

Warzone: Pandorax
Marauder Bomber
Assassinorum Murder Squad
Warhound Hunting Pack

Warzone: Damnos
Land Raider Spearhead

Warzone: Damacles
Armoured Vanguard Squadron

Warzone: Armageddon
Warhound Scout Titan
Reaver Battle Titan

Grand Master, Inquisitors & Libraians list correct mastery lvl 
for options chosen.

Moved to Shared entries
Land Raiders
Stormraven Gunship

**Comment by Gary-B2** [comment]
I will get the Fighter Aces updated to Inquisition tomorrow.

There are several Apocalypse Formations that are Fortifications
I was thinking rather than adding them to each Codex as apprppriate i might add them to the Fortification catz.

What do you think?

Fortifications
Warzone: Damnos
Wall of Martyrs Defense Strongpoint
Firestorm Nexus

Apocalypse GW
Grand Redoubt

**Comment by ghost** [comment]
Those are in the 'Fortifications and Stronghold Assault' file :)

**Comment by Gary-B2** [comment]
Ok. Closing this.
