### ISSUE TITLE
Chaos Space Marines 

### ISSUE THREAD

**Issue by TyzenNova** [BSData/wh40k-7th-edition#2305]
Hey guys, obliterators have Power Fists on the Codex, they do not here on BattleScribe.
Chosen with Veterans of the Long War get their Ld to 11, that's not correct, should be fixed too. 

Thanks for this great app!

**Comment by cartag** [comment]
Update your data files, the Obliterator shows up with a power fist. 

![image](https://cloud.githubusercontent.com/assets/4388344/16172165/b9cf8b16-353f-11e6-87e0-66c03cd576fc.png)

Corrected issue with VotLW with next update.
