### ISSUE TITLE
Eldar Corsairs

### ISSUE THREAD

**Issue by TyzenNova** [BSData/wh40k-7th-edition#2306]
Hi guys.
Almost all the corsair units have Brace of Pistols, they do not have them in BattleScribe.
Similar situation with the Shadowwave and Plasma grenades, most of them have them, but they do not have them on their profile in BattleScribe.

Thanks in advance!

**Comment by amis92** [comment]
@martijndoornik did your commit resolve this issue? If so please close it, if not please write what remains to be done.
