### ISSUE TITLE
Forces

### ISSUE THREAD

**Issue by Restkastel** [BSData/wh40k-7th-edition#2307]
When I tried to use this in the current version of battlescribe, the different armies all showed up, however all of them also came up with "No force Types...." in the forces area.

**Comment by SuperPranx** [comment]
Which codex were you using?
Can you be a bit more specific about what you did exactly, step by step?
If you have have a screenshot, please add it to the issue.

**Comment by amis92** [comment]
Umm isn't that expected? That's our category for units that _do not take Force Org slot_, hence the name.

**Comment by DrTobogganMD** [comment]
No amis - he's saying that when adding a force, he has the dropdown for catalog, but no force type drops down to choose from.

@Restkastel try purging and re-adding data.  Sounds like the GST didn't download correctly.
