### ISSUE TITLE
Codex: Blood Angels Dreadnought Attacks Errata

### ISSUE THREAD

**Issue by Gnofry** [BSData/wh40k-7th-edition#2309]
It is very soon, but I figured I would get the issue up right away. GW published an official errata to increase the base attacks of all dreadnoughts by 2.
![13445767_1635011190152847_4104911159854085936_n](https://cloud.githubusercontent.com/assets/17345182/16214740/68716726-3729-11e6-82bd-53d47a87086a.jpg)

**Comment by DrTobogganMD** [comment]
Duplicate of #2308
