### ISSUE TITLE
[Anon] Same IDs problem

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#231]
When trying to do a 40k 7th edition army the dystopian wars fleet lists are listed instead of 40k army lusts

**Comment by amis92** [comment]
That is quite interesting turn of events. Could you please provide more details, like saying army list = catalogue or roster? That has to be something with identical IDs of catalogues/rosters like those in dystopian wars...

**Comment by amis92** [comment]
Moved to #246
