### ISSUE TITLE
Codex: Grey Knights Dreadnought Attacks Errata

### ISSUE THREAD

**Issue by Gnofry** [BSData/wh40k-7th-edition#2310]
It is very soon, but I figured I would get the issue up right away. GW published an official errata to increase the base attacks of all dreadnoughts by 2.

![13445767_1635011190152847_4104911159854085936_n](https://cloud.githubusercontent.com/assets/17345182/16214757/8de1e03a-3729-11e6-8a22-3eea22b2205c.jpg)

**Comment by DrTobogganMD** [comment]
Duplicate of #2308
