### ISSUE TITLE
Terminator Captain Can only take Chapter Specific Relics

### ISSUE THREAD

**Issue by stewartianj** [BSData/wh40k-7th-edition#2311]
When using imperial fists chapter tactics, the captain unit, when equipped with terminator armour, cannot take relics from codex space marines, only the chapter specific relics from the angels of death supplement that do not replace a weapon.  

To reproduce:
- Created a roster, add a CAD using SM codex (v67)
- add imperial fists chapter tactics
- add a captain.
- set the captain to wear terminator armour
- you lose the ability to take chapter relics from codex adeptus astartes, and can only use chapter specific relics from the angels of death supplement, 

If i don't take terminator armour I have the option to take relics from both books.  I tried using Iron Hands chapter tactics and I received the same behaviour, albeit with that chapters specific relics instead.

**Comment by DrTobogganMD** [comment]
![image](https://cloud.githubusercontent.com/assets/16939161/16227321/98a65e8c-3775-11e6-819f-e68be8659bf3.png)

Cannot reproduce on PC - what OS are you on?

**Comment by Salrantol** [comment]
This was fixed not long ago, might it just not have been published yet?

**Comment by DrTobogganMD** [comment]
That'd be it. User is on V67 - you just pushed V79.
