### ISSUE TITLE
Start collecting skitarii formation

### ISSUE THREAD

**Issue by GFiredrake** [BSData/wh40k-7th-edition#2321]
When I add this formation it gives a unit of skitarii Rangers when the data card says that it's skitarii vanguard

**Comment by DrTobogganMD** [comment]
The default is a unit of rangers - you can choose to replace them with vanguard.

Two versions of the data card were published.  GW has said that both versions are allowed.  Official FAQ/Errata is expected with the final drafts of the faqs they're working on onw.
