### ISSUE TITLE
Skitarii War Cohort

### ISSUE THREAD

**Issue by dabrown** [BSData/wh40k-7th-edition#2322]
Skitarii War Cohort currently populates a Sicarian Infiltrator and Rustalker unit for each battle maniple. Rulebook reads as "Infiltrator, or, Rustalker" under Battle Maniple Formations.

**Comment by DrTobogganMD** [comment]
Formation is correct as is.  1 Vanguard, 1 Ranger, 1 Ruststalker, 1 Infiltrator, 1 Dunecrawler, and 1 unit of either walker variant.

![image](https://cloud.githubusercontent.com/assets/16939161/16467912/1e415ff2-3e0f-11e6-8755-4fd88e372180.png)

However, it appears that Dunecrawlers are not limited to 1 unit.  Fixing that.

**Comment by DrTobogganMD** [comment]
Closed via https://github.com/BSData/wh40k/commit/2172167d3c6059094b95dcf8a20d5a0ad6fa0ecd
