### ISSUE TITLE
Codex: Space Marines - ISM30 in Skyhammer Annihilation Force

### ISSUE THREAD

**Issue by francoisbeaulieu** [BSData/wh40k-7th-edition#2325]
Hi,

The assault and devastator squads in the Skyhammer Annihilation Force do not offer the option to replace a space marine with the 30th aniversary imperial space marine. (On iOS at least.)

**Comment by DrTobogganMD** [comment]
It is present under Special Models under the Assault and Devastator squads.  Works on IOS and PC for me.  Try purging and re-downloading data?

**Comment by francoisbeaulieu** [comment]
Yup, that did it. Sorry for filing without checking that.
