### ISSUE TITLE
Missing Imperial Fist chapter relics from Angel of death

### ISSUE THREAD

**Issue by shardqc** [BSData/wh40k-7th-edition#2330]
It is not possible at the momment to view or select chapter relics of the Imperial Fist from the Angel of Death supplement

**Comment by Salrantol** [comment]
I have no problem with this. Have you updated your data file? Do you have Chapter Tactics: Imperial Fists selected for the Detachment in which you are trying to select the relic?

**Comment by shardqc** [comment]
yes did both,In the Angel of death supplement it states that these relics are available to any space Marines forces in the Gladys time fore however I can't select them

**Comment by shardqc** [comment]
yes did both,In the Angel of death supplement it states that these relics are available to any space Marines forces in the Gladius strike force however I can't select them, In the stern hammer I am able to,
