### ISSUE TITLE
Space Marines & Space Wolves Roster Error

### ISSUE THREAD

**Issue by JusticarGames** [BSData/wh40k-7th-edition#2332]
Can anyone else confirm that Battle Scribe v1.15.07 on Windows will not load the following codices/formations in one single roster??

Combined Arms Detachment - Space Wolves
Formation - Space Wolves
Formation - Space Marines

I am able to load all of these perfectly fine on my phone, a Samsung Galaxy S7 Edge (android os). When I try to do this on my PC it just hangs up and I have to force close from the task manger, when I do this and relaunch the program it wipes out the 40k data files.

I noticed that while in the task manger the Battle Scribe icon blinks from the BS icon to the Java icon. My java is updated.

**Comment by DrTobogganMD** [comment]
Both work fine for me on Win 10.

**Comment by JusticarGames** [comment]
You loaded all three of those at the same time? Not individually, sorry for not stating that.

**Comment by DrTobogganMD** [comment]
Yep: 
![image](https://cloud.githubusercontent.com/assets/16939161/16655317/5bb9bce2-441f-11e6-873f-7446397e7fe9.png)

Try reinstalling and purging data files?

**Comment by JusticarGames** [comment]
Uninstalled, deleted everything from my documents/user of the pc, reinstalled. Problem is still here.

What else can I do?

**Comment by DrTobogganMD** [comment]
It's rather odd that it wipes your data files when it happens ... try on a 2nd machine - see if it's reproducible with your install?

**Comment by JusticarGames** [comment]
This is happening on 3 different computers that I've personally been on and I just had a friend try it on his machine, hes running Win10 just like you and wasn't able to load it up either. What the hell!!

**Comment by DrTobogganMD** [comment]
I was able to partially reproduce on another Win10 machine (with much higher specs interestingly enough).  Making a new roster from scratch with Formation SW, then Formation, SM, then CAD SW, with no changed name and 0 points causes the app to hang.  It will hang for roughly 30-45 seconds before it loads the entries on the left hand window.

This is highly likely because Both SM and SW are horribly bulky and optimized as well as your standard government budget meeting - something I'm personally fixing in 2.0 (SM and SW, not the budget - sorry)

How long have you left the app sitting?  What are the exact steps you are using to produce this.

**Comment by JusticarGames** [comment]
Alright just uninstalled on my personal desktop at home then reinstalled. This machine far exceeds requirements to run this program. i7 OCd 4.2GHz, 16GB RAM, 256GB SSD, 980 TI, Windows 7..all the typical gaming stuff.

Step 1 - Click New Roster
Step 2 - Name Roster & Set Point Value
Step 3 - Click Add, Combined Arms Detachment, Space Wolves, Click Ok
Step 4 - Click Add, Formation, Space Wolves, Click Ok
Step 5 - Click Add, Formation, Space Marines, Click Ok
Step 6 - Look at screen and make sure everything is there. Click Ok
Step 7 - Cry because nothing happens

Roster screen has been frozen for like 5 minutes now.
![bsbug](https://cloud.githubusercontent.com/assets/17251427/16673123/59e524e2-4479-11e6-9a30-bd2cededd51b.jpg)

**Comment by DrTobogganMD** [comment]
Yep, those steps lock it up too on mine.  Editing an existing roster does not do it though - try that as a work around until 2.0 I guess.

Edit: If I press cancel on the edit rosters part, it loads 2 of the 3.

**Comment by JusticarGames** [comment]
Alrighty. Thanks for the help and feedback!

**Comment by DrTobogganMD** [comment]
Yea. Sorry it can't be more :/ those are the biggest and one of the other biggest catalogs that we have. I'm cutting down the size of both in 2.0
