### ISSUE TITLE
Re introduce iyanden suppliment

### ISSUE THREAD

**Issue by plebicidal** [BSData/wh40k-7th-edition#2333]
As per GW FAQs, iyanden is indeed still a valid suppliment.

![13600014_1643607522626547_8460183477443253439_n](https://cloud.githubusercontent.com/assets/18018035/16643598/6d13fa54-4459-11e6-9b71-d8a3a0b95430.jpg)

**Comment by efalsken** [comment]
Please resubmit when the FAQ is final. It is still available in the "historical" branch, if you really want to use it.
