### ISSUE TITLE
Chosen Missing from chaos space marines vanilla and chrimson slaughter Elite Choice

### ISSUE THREAD

**Issue by bninassi** [BSData/wh40k-7th-edition#2337]
All is in the title, you can't pick chosen for vanilla chaos spaces marines or chrimson slaughter chaos spaces marines anymore (should be in elite choice) for the Allied or Combined Arms Detachement or  => something broken ?

**Comment by cartag** [comment]
Nice catch. If you have a force of Black Legion in as well it hides them as an Elites choice. I need to correct the hide criteria. If you don't have a BL force in your roster, they show appropriately.
