### ISSUE TITLE
CSM Black Legion formation : Hounds of Abaddon should have mark of khorn for free

### ISSUE THREAD

**Issue by bninassi** [BSData/wh40k-7th-edition#2338]
The chaos lord, spaces marines, bikers, raptors and warp talons of the Hounds of Abaddon CSM Black Legion formation must have mark of khorne and should have it for free according to the rules.

**Comment by cartag** [comment]
This may be one that we need to wait on BS2 for, given the catalogue changes being put into place with it. I'll try it for 1.15, but I remember having issues with this one in particular. 

Actually, check the rule for The Hounds of Abaddon. It states it will not be implemented until BS 2.0.
