### ISSUE TITLE
[Anon] Bug report: Officio Assassinorum Dataslate (2014).catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#2352]
**File:** Officio Assassinorum Dataslate (2014).catz

**BattleScribe version:** 1.15.07

**Platform:** Windows

**Dropbox:** Yes

**Description:** Codex is also out of date. I have the new one, and will be glad to create a new file.

JGBloody@gmail.com

**Comment by DrTobogganMD** [comment]
Feel free to submit a pull request for the file, otherwise if you can provide the updated codex, we can make the changes.  You can send both codexes to iam@earlb3.com if you want.

**Comment by DrTobogganMD** [comment]
No response or file sent.
