### ISSUE TITLE
DE purge coterie Trueborn

### ISSUE THREAD

**Issue by capnpetey** [BSData/wh40k-7th-edition#2353]
In the purge coterie, the data file is not allowing Trueborn to be selected as a Warrior option.

**Comment by Aaronspec** [comment]
Correct me if I'm wrong or missing something.

Dark Eldar Purge Coterie is a starter collection formation for the Dark Eldar. This formation requires 1 Archon, 1 unit of Kabalite Warriors, 1 Radier, 1 unit of Reavers. It does not follow a the usual formation or detachment set up. So in turn, you can not have Kabalite Trueborn. But this formation is missing its special rules. The Special Rule for this formation is as follows: Marked for Death: Such is the power at their disposal that, with but a simple gesture, an Archon can order the swift demise of those that displease them. At the start of each friendly turn, pick an enemy unit within line of sight of the Archon. All other units from the Purge Coterie have the Preferred Enemy special rule against the unit you picked until the start of your next turn.

**Comment by capnpetey** [comment]
Yes, it is the start collecting set.
That special rule is correct.

In the DE Codex Trueborn is an upgrade option for Kabalite Warriors.  As
written, it causes the Warriors to become an Elites choice instead of
Troops.  But in this case, the formation does not care that they become
Elites, just that they are Kabalite Warriors.  In the datafile Warriors and
Trueborn are separate units, but in the codec they Trueborn is just an
upgrade option for standard warriors.  This was likely done that way to
ensure that Trueborn Warriors were listed as an Elite choice.
The other DE formation gets around the problem by making you choose 6
"kabalite units" plain Warriors, or Trueborn.

**Comment by Toreador13** [comment]
Fixed in Version 25
