### ISSUE TITLE
Updated FW rules for Death From The Skies

### ISSUE THREAD

**Issue by Drachnyen** [BSData/wh40k-7th-edition#2354]
Hello,

Forgeworld just released their update for Death from the skies. 

Includes the missing stats for agility and pursuit but also has new rules and revisions for some existing units.

https://www.forgeworld.co.uk/resources/fw_site/fw_pdfs/Warhammer_40000/Death-from-the-Skies.pdf

**Comment by efalsken** [comment]
Tau is done and pushed.

**Comment by DrTobogganMD** [comment]
Space Marines is done.

**Comment by Drachnyen** [comment]
_cough_ @cartag _cough_ Hellblades/Hell Talons _Cough_  ;)

**Comment by cartag** [comment]
They're already updated for BS2 prep work, I'm getting it implemented into the 1.15 files right now... well, not right now, because I'm typing this instead.

Never interrupt the genius at work! :stuck_out_tongue:

**Comment by afraeve** [comment]
Death Korps, Elysians, Renegades, ABG, SAV, Sentinels of Terra, Clan Raukaan & Tyrant's Legion all done. 

(We've left the original entries for Thunderbolts & Lightnings in place since it's not really clear whether or not these are valid.)

**Comment by DrTobogganMD** [comment]
The old entries are invalid.

"The following Flyers have entirely re-written profiles instead of simple rules updates, whether to cope with out-of-date rules or more extensive alterations to their existing rules. In all cases, these profiles are considered to override those found in Forge World publications which pre-date the release of Death from the Skies"

**Comment by tag8833** [comment]
Orks are Done.  Warkopta may need additional work if we decide to give it Flyer Wings.

**Comment by martijndoornik** [comment]
Craftworld Eldar are done. Will soon do the Eldar Corsairs and the Dark Eldar ones.

**Comment by ghost** [comment]
@martijndoornik Eldar Corsairs are now done, but I'll leave Dark Eldar to you.

**Comment by ghost** [comment]
- [x] Dark Eldar
- [ ] Thunderbolt rules and profiles
- [ ] Lightning rules and profiles

**Comment by ghost** [comment]
@martijndoornik some dude on Facebook asked to have Dark Eldar done, and I was bored, so I did.

**Comment by DrTobogganMD** [comment]
FW Profiles are added where appropriate
