### ISSUE TITLE
New FW Tau flyer: Barracuda AX-5-2 Multi-role fighter

### ISSUE THREAD

**Issue by Alvirulan** [BSData/wh40k-7th-edition#2356]
Hello,

Forgeworld released today a new Tau flyer.
Please find below link to its rules datasheet:

https://www.forgeworld.co.uk/resources/PDF/fw_warscrolls//Tau%20Barracuda%20AX%205%202%20Exp%20Rules.pdf

**Comment by efalsken** [comment]
I've pushed the update. It will go live with the next release.
