### ISSUE TITLE
Air Superiority Detachment Does Not Show Flyer Wing for DE, AM, Inq on Android

### ISSUE THREAD

**Issue by Lynkon** [BSData/wh40k-7th-edition#2357]
I don't see Flyer Wing options for Dark Eldar, Astra Militarum, or Inquisition in the Air Superiority Detachment on Android.

**Comment by IronWulfen88** [comment]
nor on the Space Wolves

**Comment by GenWilhelm** [comment]
Current Progress:
- [x] Dark Eldar
- [ ] Astra Militarum
- [ ] Inquisition
- [ ] Space Wolves

**Comment by GenWilhelm** [comment]
As far as I am aware Inquisition may not take Flyer Wings.

Other than that, there is new issue to overhaul the Flyer Wings as per Death from the Skies: #2470.

**Comment by amis92** [comment]
@GenWilhelm thanks for opening that catch-all issue. In such a case, this should be labeled duplicate and closed as such. I'll leave that to you.

**Comment by amis92** [comment]
Oh also, @GenWilhelm: really amazing job with closing all those issues! Please consider joining [group chat at gitter](https://gitter.im/BSData/wh40k) ;)
