### ISSUE TITLE
Space Wolves - FW Land Raiders shouldn't have the option to take a Dozer Blade

### ISSUE THREAD

**Issue by SuperPranx** [BSData/wh40k-7th-edition#2366]
The Land Raider, Land Raider Crusader and Land Raider Redeemer are all missing the Dozer Blade upgrade option. They all have "Land Raider STC Upgrades", which is the most probable place to look for the bug.

**Comment by DrTobogganMD** [comment]
Dozer Blades are not allowed on Land Raiders of any type:

![image](https://cloud.githubusercontent.com/assets/16939161/17181959/8bcec9f4-53e7-11e6-930e-9f75c5d51b89.png)

**Comment by SuperPranx** [comment]
Sorry, didn't check the footnotes...
Would't this mean that Dozer Blade needs to be removed for the FW Land Raiders as well?
At the moment LR Achilles, LR Helios and LR Proteus all have the option to take a Dozer Blade, according to BattleScribe.

**Comment by DrTobogganMD** [comment]
I _Think_ so - I'll check my 2.0 Space Marines and see if they have it.  It's defined in IA2 what their options are.
