### ISSUE TITLE
[Anon] Bug report: Space Marines IC Dread has no ranged weapons on fist options.

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#2368]
**File:** Warhammer40K.gstz

**BattleScribe version:** 1.15.07

**Platform:** Mac

**Dropbox:** No

**Description:** Thanks so much for all you do! One issue and one question to flag up:

Issue: In Space Marines Codex (2015), Ironclad Dreadnought is missing ranged weapons on its chain fist, seismic hammer and power fist. See hardback codex p.146.

Question: In Space Marines Codex (2015), why do no independent characters appear? I'm using Crimson Fists so have to get Pedro Kantor from Sentinels of Terra supplement instead.

**Comment by francoisbeaulieu** [comment]
Named characters only appear if you select the corresponding chapter under chapter tactics.

**Comment by DrTobogganMD** [comment]
Actually no issue here. Chainfist has weapon choices present.

![image](https://cloud.githubusercontent.com/assets/16939161/17373754/43c0b3f6-596f-11e6-9956-a28f5f4ba835.png)
