### ISSUE TITLE
KDK - Rules Corrections

### ISSUE THREAD

**Issue by Critacal** [BSData/wh40k-7th-edition#2371]
1. Kytan daemon Engine can replace a Lord of Skulls as an option this makes it available as a war engine option for those who use the Blood Host detachments

"In addition, it may be selected instead of Khorne Lord of Skulls in any detachment where such a war machine is available "
file available below
direct link https://www.forgeworld.co.uk/resources/PDF/Datasheets/Kytan.pdf
1. Chaos Lord in terminator Armour shouldn't be limited to artefacts of slaughter weapons being on his power weapon arm as the entry does not specifically state which arm these weapon options are limited to so players can i.e take Goredrinker with a power sword without having to pay extra 12pts for the power weapon.
2. Hellbrutes will have 4 attacks as per the Warhammer 40,000 facebook posted picture of the draft of chaos errata 
   file available below
   direct link https://www.facebook.com/Warhammer-40000-1575682476085719/photos/?tab=album&album_id=1576243776029589
3. Chaos Decimator Daemon engine Soulburner Petard has a blank AP value.

Thank you for taking the time to read these issues I apologise if any prove to be incorrect and thank you again for the hard work for making these files and correcting the errors.

![chaos errata](https://cloud.githubusercontent.com/assets/12483879/17244103/0eb34c14-5578-11e6-8969-f670768c7315.jpg)
[Kytan.pdf](https://github.com/BSData/wh40k/files/390231/Kytan.pdf)

**Comment by cartag** [comment]
1) Kytan is currently able to be selected as part of War Engine aux choice. Make sure you have "Show Forgeworld" selected.

1, 2E) I'll get this corrected.

2) Fix already up, just hasn't been released yet

3) I'll get this corrected as well.
