### ISSUE TITLE
Gaining access to push changes

### ISSUE THREAD

**Issue by ghost** [BSData/wh40k-7th-edition#2377]
Hi,

I've added a load of the rules descriptions to my copy of the catz files. I was wondering if I could commit the changes with your permission?

Mark

**Comment by DrTobogganMD** [comment]
You'll want to do a pull request using .cat files, not .catz - we cannot view the diff if you upload catz files.

**Comment by cartag** [comment]
If it's the rules from the BRB, they'll be included by default once BS2 comes out. We're already working on it.

**Comment by DrTobogganMD** [comment]
No response regarding request - closing issue.
