### ISSUE TITLE
No Painmob formation for orks

### ISSUE THREAD

**Issue by mifth** [BSData/wh40k-7th-edition#2379]
Hi.

I found that there is no Painmob formation for orks. Could you add it, please?

Formation:
One painboy
One unit of boyz
One unit of nobz
One Deff Dread

Pila on da pain!: once per battle, at the start your movement phase, an Ork Painmob can Pile on da pain....
https://m.reddit.com/r/Warhammer40k/comments/47h7rq/new_ork_formation_the_painmob/

**Comment by tag8833** [comment]
It is there.  Are you sure you have the latest data file?   Update your data, and check again.

**Comment by mifth** [comment]
I have android device. And i installed this data http://battlescribedata.appspot.com/repos/wh40k/index.bsi
I udated it.
There is no painmob formation.

**Comment by tag8833** [comment]
It shows up fine on my Android device.  Are you sure you setup the Force right?   You need a "Formation" Detachment from catalog "Ork Codex (2014) v60".

**Comment by mifth** [comment]
Aaaaa, i had to choose formation detachment.
Sorry and thanks a lot!
