### ISSUE TITLE
Dark Eldar roster request

### ISSUE THREAD

**Issue by Glyss** [BSData/wh40k-7th-edition#238]
Urien Rakarth - Master Haemonculus: 1) Wracks are Troops choices in a detachment that includes Urien Rakarth. 
2) Any unit of Grotesques in the same detachment as Urien Rakarth can be upgraded from Strength 5 to Strength 6 at the cost of +5 points per model. 

Asdrubael Vect - The Dias of Destruction (dedicated transport): The Dias is able to take all upgrades a Raider can take, but no option to choose these upgrades currently exists in BaatleScribe.

Reaper (Forgeworld model) - Heavy Support choice - 135 Points

BS 4
Armour
Front 11
Side 11
Rear 10 
HP 3

Unit composition - 1 Reaper
Unit type - Vehicle (Skimmer, Fast, Opened-Topped)
Wargear - Storm vortex projector,  Enhanced aethersails
Special Rules - Night vision,  Aerial assault

Options
The Reaper may take any of the following:
Shock prow - +5 points
Torment grenade launcher - +5 points
Retrofire jets - +5 points
Chain-snares - +5 points
Grisly trophies - +5 points
Envenomed blades - +5 points
Night shields - +10 points
Flickerfield - +10 points

Storm vortex projector (blast/ beam)

Blast - 24" S5 AP4 Heavy 1, haywire, pinning, large blast

Beam - 36" S7 AP3 Heavy 1, haywire,  kill shock, concussive

Wyches entry does not allow for a choice of below 5 models per unit.  This does not allow for a 'special weapon' or 'Hekatrix' option in a small transport choice. 
Could you pretty please allow for a minimum unit choice of 3 instead of 5.

Thanks for taking the time to read this.

**Comment by amis92** [comment]
So to sum up:
- Wracks as Troops with Urien Rakarth
- Grotesques S+1 upgrade with Urien Rakarth
- Dias of Destruction upgrades
- Add Reaper [FW] to Heavy Support
- Fix Wyches model choice

**Comment by Glyss** [comment]
Yes.

In short =P

**Comment by axisofentropy** [comment]
On 08/18/2014 06:36 AM, Glyss wrote:

> Asdrubael Vect - The Dias of Destruction (dedicated transport): The Dias
> is able to take all upgrades a Raider can take, but no option to choose
> these upgrades currently exists in BaatleScribe.

This is still in dispute.  The 6th edition FAQ said it could not take
upgrades.  There's more (bad) discussion here:
http://www.dakkadakka.com/dakkaforum/posts/list/360/596855.page

**Comment by Glyss** [comment]
It states in the codex that apart from its increased armour and that Vect must start on it with 9 other models "other than this, it is treated exactly as a Raider"

A Raider has all Wargear options such as Flickerfield and Night Shields. 

I'm not sure what there is to debate?

But I'm going to jump into the fray anyway.

**Comment by Glyss** [comment]
Ahh bugger, knocked send by accident. 

I didn't realise it was FAQ'd in 6th, as I didn't see anything about it in 7th FAQ.

That's really odd to leave out the new FAQ. Perhaps they're not addressing it due to the new codex coming soon?

**Comment by Glyss** [comment]
Wow that was really quick and will make life a whole lot easier for DE rosters.

Thanks heaps Amis92! =D
