### ISSUE TITLE
Death Masque Harlequins

### ISSUE THREAD

**Issue by Marina42** [BSData/wh40k-7th-edition#2388]
The option to use the special units in any formation (i.e. use Inriam's Spectre wherever one could use a Death Jester) and the formation need to be added.

**Comment by DrTobogganMD** [comment]
`This is not how formations work.  Named HQs are not allowed to be substituted in formations at will.  The formation specified which models can be used. Unless there is an exception listed in the formation (Such as battle demi company for Space Marines, allowing named captains)`

**Comment by DrTobogganMD** [comment]
Nevermind - I see the Death Masque Rules now :)  I'll try to get them added, I'm not sure if we have anyone specifically on harlequins.

**Comment by Marina42** [comment]
Great! kudos for being fast and awesome :)

**Comment by moonlightcheese** [comment]
The formations from the Death Masque rules are not available as individual formations.  They are only available in the Death Masque Detachment.  Is this by design?  I would like to be able to include the individual formations in my list.

**Comment by Marina42** [comment]
There's only one formation in the Death Masque, The Coherian Host. 

The rest are units, not formations, and they can substitute their unit type in any detachment/formation. 

i.e. If you wanna add Inriam's Spectre to your army, just add a Death Jester. There's the option to add a Death Jester or Intiam's Spectre
