### ISSUE TITLE
Imperial Knights - Household Detachment - Lord Baron bonus missing

### ISSUE THREAD

**Issue by Drachnyen** [BSData/wh40k-7th-edition#2390]
Hello,

Selecting a Lord Baron (warlord) in Household detachment should increase the unit WS and BS by 1 and should modify its type to Super-heavy Walker, Character)  (Page 98)

Thanks,

**Comment by Drachnyen** [comment]
Thanks for be update!

I beleive  same behavior with the Baronial Court. 

Did you have a chance to fix it as well?

**Comment by GenWilhelm** [comment]
No, I haven't made any changes to the Baronial Court. I will add it to the conditions tonight, so it will probably be fixed with next release.

**Comment by Drachnyen** [comment]
Cool Thanks
