### ISSUE TITLE
Inquisition - Ordo Malleus Inquisitor has no weapons

### ISSUE THREAD

**Issue by Drachnyen** [BSData/wh40k-7th-edition#2391]
Hello,

Ordo Malleus Inquisitor has no weapons. 
Also missing the "Weapons" box that allows you to modify weapon loadout.

**Comment by GenWilhelm** [comment]
The weapon options change depending on his armour selection. Therefore the weapon options have to be listed under his armour.

![malleus weapons](https://cloud.githubusercontent.com/assets/22036809/18507642/1aca965e-7a69-11e6-85be-e54dc159da64.png)

For future reference, any selection in **bold** has additional options.
