### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by Tordokdur** [BSData/wh40k-7th-edition#2392]
Hi, i am new to GitHub and creating battlescribe catalogues but i´m good in programming and like to help creating a cataloguefile for the new Deathwatch Codex.

greetings
T.

**Comment by amis92** [comment]
Hello, @Tordokdur. Please accept the invitation in the email or on the [BSData organization webpage](https://github.com/BSData). Welcome aboard!

Don't forget to read through [Wiki pages](https://github.com/BSData/bsdata/wiki), there are some useful guides, especially [Developer Guide](https://github.com/BSData/bsdata/wiki/Developer-Guide).

Also join our team in Gitter chat room (GitHub login): [![Join the chat at https://gitter.im/BSData/wh40k](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/BSData/wh40k?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

Cheers!

PS Regarding Deathwatch, please try to coordinate efforts through Issues and Gitter, it seems there is high interest in this one.
