### ISSUE TITLE
Codex: Blood Angels - Formations (the usual)

### ISSUE THREAD

**Issue by Kangodo** [BSData/wh40k-7th-edition#240]
Hello colleagues!

I've entered the Blood Angel Formations in the .cat
But now I have the Category-bug..
Does anyone have a script to fix this? Because I still don't get how it works.

**Comment by amis92** [comment]
Script: https://raw.githubusercontent.com/amis92/bs-xml-reshaper/master/removing-non-root-categoryIds.xsl

Program: https://github.com/amis92/bs-xml-reshaper/releases/latest

Ask further if you are stuck.

**Comment by amis92** [comment]
However beware, it removes category from anything _not_ being root level.

That means, if you have any links with unassigned category (it can happen - BattleScribe uses then category of Entry you linked to) the units appear as No Category! :)

**Comment by Kangodo** [comment]
Thank you! Luckily it didn't break anything.
But that does explain why Obyron suddenly lost his Category when I used that on Necrons.
