### ISSUE TITLE
SM Codex: Strike force command

### ISSUE THREAD

**Issue by superdefra** [BSData/wh40k-7th-edition#2403]
Strike force command ain't selectable in the formation list.
Any change to get it fixed?
Appreciate that.

**Comment by cartag** [comment]
I don't think Strike Force Command is a formation unto itself, it's just a Command choice for a Gladius Strike Force. Kinda like how Lord of Slaughter or War Engine are choices for the KDK army but not actual formations.

**Comment by amis92** [comment]
It's not a formation, as @cartag said. Formations must have a dataslate which would specifically mark it as a formation (with Formation icon). As it is, it's just a Command choice for Gladius SF.

Remember, not every choice for the "Decurion style" detachments must be a Formation. It's in third paragraph of `Choosing an army` (Codex: SM just over Gladius):

> The Gladius Strike force [...] has a Force Organisation Chart whose slots are a combination of specific Fomations and **Army List Entries** instead of Battlefield Roles.

_emphasis added_

**Comment by superdefra** [comment]
Thank you very much

Inviato da Libero Mail per iOS

domenica 21 agosto 2016, 22:43 +0200 da notifications@github.com  notifications@github.com:
