### ISSUE TITLE
Codex Deathwatch Veterans unit comp error

### ISSUE THREAD

**Issue by gungagreg** [BSData/wh40k-7th-edition#2415]
The Veteran unit and the kill teams that use veterans have an issue with the veteran unit composition.  The code is requiring two basic veterans even if you already have a total of five.  For instance, you add a watch sergeant and four vets with Heavy weapons.  That is a legal unit by the codex but the battle scribe roster still shows an error saying two vets are required.  Seen it in the Aquilla kill team and the basic veterans, assuming it exists elsewhere.

Thanks!

**Comment by flakpanda** [comment]
Fixed

**Comment by flakpanda** [comment]
Closed #2415
