### ISSUE TITLE
[Anon] BattleScribe bug: Multiple files of the same name

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#242]
Okay, so i have the app on my tablet and it just kinda forgot the Astra militarum file or something. Any time I try to use the app for 7th edition 40k or says there are multiple file of the same name. How do I fix this?

**Comment by Kangodo** [comment]
By clearing all the files and redownloading them.

**Comment by Kangodo** [comment]
No response, so I guess it's solved.
