### ISSUE TITLE
Bug Report: Death Watch Codex - Purgatus Kill Team & Terminator bugs

### ISSUE THREAD

**Issue by Melkavar** [BSData/wh40k-7th-edition#2422]
Purgatus kill team does not include the required unit of Terminators.

Additionally, the options for Terminators are incorrect.  Cyclone missile launcher should not be included in the same list as the double lightning claws or thunder hammer and storm shield, as these options are not mutually exclusive with one another.  The cyclone missile launcher should be included in the list of heavy weapon options, along with the heavy flamer and assault cannon.

**Comment by flakpanda** [comment]
Fixed

**Comment by flakpanda** [comment]
Closed #2422
