### ISSUE TITLE
Space Marines: Add Deathwatch Strike Team Apoc Formation

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#2424]
**File:** Deathwatch - Codex.catz

**BattleScribe version:** 1.14.07

**Platform:** Android

**Dropbox:** No

**Description:** Could you add the Deathwatch Strike Team back in please? I know apocalypse isn't popular everywhere, but we used this formation.
Also, I think Squad Galatael may be selected as part of it, in place of one of the units.

**Comment by flakpanda** [comment]
I will when I can get the information. I do not have a copy of the book available to me at the moment.

**Comment by flakpanda** [comment]
Due to the Deathwatch Strike Team formation not using any of the new datacards from the Deathwatch codex, it will not be included into the Deathwatch catalog. However, it will need to be added into the Space Marines catalog as this formation uses Space Marine datacards.
