### ISSUE TITLE
Deathwatch Black Spear Strike Force should be Force Type in gst

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#2428]
**File:** Warhammer40K.gstz

**BattleScribe version:** 1.14.07

**Platform:** Windows

**Dropbox:** No

**Description:** The new Black Spear Strike Force from Deathwatch is missing.

**Comment by flakpanda** [comment]
It is listed under a formation detachment for them rather then the normal
listing.

**Comment by cartag** [comment]
It should be made as its own detachment, not just under "Formation Detachment." For each force that has its own Decurion style detachment, they get their own specialized detachment in the roster.

**Comment by flakpanda** [comment]
I agree. I did not create the deathwatch catalog.
