### ISSUE TITLE
Deathwatch Codex - Vanguard Veterans

### ISSUE THREAD

**Issue by Leadpocalypse** [BSData/wh40k-7th-edition#2431]
Hello, 

Never posted on here before so I hope this is the correct way to submit a bug.

**Battle scribe v1.15.07
Deathwatch V8**

**Vanguard Veterans** have no option to choose **Hand Flamer** or **Inferno Pistol**.

**Comment by flakpanda** [comment]
Fixed. Will push out with next release.

**Comment by flakpanda** [comment]
Closed #2431
