### ISSUE TITLE
Iron hands dreadnaughts

### ISSUE THREAD

**Issue by Redryad** [BSData/wh40k-7th-edition#2432]
While working on an a Iron Hands combined arms detachment only the contemptor dreadnaught was listed under heavy choices. March of the ancients makes all dreadnaughts a heavy choice for an iron hands detachment.

**Comment by GenWilhelm** [comment]
March of the Ancients is a supplement rule from the Clan Raukaan supplement. As such, only Clan Raukaan detachments may take Dreadnoughts as Heavy Support choices.

**Comment by Redryad** [comment]
Page 88 of angels of death lists it as a iron hands special rule
