### ISSUE TITLE
Space Marines - Legacies of Glory on Flyers

### ISSUE THREAD

**Issue by thughestamu** [BSData/wh40k-7th-edition#2433]
There seems to be no option to give legacies of glory to flyers.  I tested a bunch of other vehicles and they  all have the option to give a legacy.  Unless I am way off my rocker and flyers can't take legacies I would say that this might need an update.

**Comment by DrTobogganMD** [comment]
2.0 Release is immanent - followed shortly after by a re-write of Space Marines: Codex.

I _think_ I caught all the valid vehicles for Legacies of glory (there was a few in 1.15 that were missing too)

**Comment by DrTobogganMD** [comment]
Fixed in 2.0
