### ISSUE TITLE
CSM - Crimson Slaughter Possessed should have the Slave to Voices SR

### ISSUE THREAD

**Issue by thejughead** [BSData/wh40k-7th-edition#2435]
When selecting Crimson Slaughter forces option.  The Possessed unit should not have the Vessels of Chaos rule, but should have the Slave to the Voices rule.

**Comment by cartag** [comment]
Nice catch

**Comment by cartag** [comment]
Currently working on updating with leaks for the Traitor's Hate book. This fix will be included in that release.
