### ISSUE TITLE
Csm and chaos daemons list mistake

### ISSUE THREAD

**Issue by bigandyclark** [BSData/wh40k-7th-edition#2443]
Hey guys, the spined chaos beast is currently and elite choice in the chaos space marine list and the giant chaos spawn is a heavy support choice in the chaos daemons list. This should be the other way around.

**Comment by cartag** [comment]
Per IA13, page 201, Spined Chaos Beast is an Elite choice for CSM and CD, and Giant Chaos Spawn is a Heavy Support choice for CD. Everything is set up correctly.
