### ISSUE TITLE
Bug report: Deathwatch - Codex.catz

### ISSUE THREAD

**Issue by Randobar** [BSData/wh40k-7th-edition#2445]
The "Stategium Command Team" is a legaö Core Choice for a "Black Spear Strike Force" but does not appear, yet.

**Comment by flakpanda** [comment]
I need more details than this. I cannot replicate the problem. It appears
as a core choice in iOS, Android, and mac.

**Comment by Randobar** [comment]
I dont get it on PC. 
My current Version of the Data File is v10, 

currently i seem to be unable to update on PC and Android.

**Comment by flakpanda** [comment]
Update your data files. Current version is v11

**Comment by flakpanda** [comment]
You also might have to wait til 5cst. I know appspot updates the files
about every 4 hours.
