### ISSUE TITLE
Deathwatch Bug: Watch Company

### ISSUE THREAD

**Issue by ChthonicKnight** [BSData/wh40k-7th-edition#2446]
I have v11
A revision needs to be made for entry - Watch Company to allow the addition of squads of veterans rather than single veterans.
Attached a revision that I've just copy/pasted the squad entries from the BSSF into the Watch Company to fix. I've also modified certain kill team entries to not include default weapon settings when adding the team to the list and added default weapon selections to: Veteran, Vanguard Veteran, and Terminator, so it doesn't throw a bunch of errors when adding these teams to your list.
[Deathwatch - Codex.zip](https://github.com/BSData/wh40k/files/454162/Deathwatch.-.Codex.zip)

**Comment by flakpanda** [comment]
Thanks for catching the vet unit error in the watch company. The reason there is no default selected weapons for them is if you select LCs/THSS/HTH you cannot deselect anything to remove the “to many weapons selected” error.
