### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by geobak84** [BSData/wh40k-7th-edition#245]
I would like to join.

**Comment by amis92** [comment]
Added = invited! Welcome aboard!

**Comment by amis92** [comment]
You have one week to accept the invitation, after that I'll delete the invitation and you'll have to re-apply.

I hope you understand - I'm doing organisation cleanup :)

**Comment by amis92** [comment]
@geobak84 You have one week to accept the invitation, after that I'll delete the invitation and you'll have to re-apply.

I hope you understand - I'm doing organisation cleanup :)
