### ISSUE TITLE
CSM - Traitor's Hate

### ISSUE THREAD

**Issue by cartag** [BSData/wh40k-7th-edition#2450]
Listing an issue to get it added to (hopefully) prevent multiple requests for it.

**Comment by Drachnyen** [comment]
Nice job Cartag!

Marry me! ;)

**Comment by cartag** [comment]
Don't thank me yet, I'm not happy with its implementation but it's close enough for government work.

**Comment by Drachnyen** [comment]
Hey @cartag,

I see the new individual formations under "formations" but I can't find the overall Decurion.

**Comment by cartag** [comment]
`<insert Jedi mind-trick here>`
(Refresh, it's working)
`</jedi mind trick>`
