### ISSUE TITLE
Eldar Craftworlds Striking Scorpion Exarchs missing upgrade option

### ISSUE THREAD

**Issue by mangekyou80** [BSData/wh40k-7th-edition#2452]
Good Morning!

The upgrade options to give a Striking Scorpion Exarch the Scorpion's Claw and/or the biting blade is missing from the upgrade options. 

Thanks!

**Comment by GenWilhelm** [comment]
Because of the way the Striking Scorpion Exarch can buy wargear you have to go into "[Sword and Weapon](https://i.imgur.com/cQQ065A.png)" to find them.
