### ISSUE TITLE
No Category - Show FW Models

### ISSUE THREAD

**Issue by etalon** [BSData/wh40k-7th-edition#2457]
I try to build up an eldar army with forgeworld units, but BattleScribe keeps saying (No Category) >"Show FW Models". I had a look in my repo files and the FW Models are included, but I can't select them in my pc software. Is it a BattleScribe or a DataFile Problem? Any help is appreciated. Thanks.

**Comment by cartag** [comment]
In the Eldar file, after you select Show FW Models, you then have to select that item and check off which sections you want to see. It looks like it's set up different than other files are in that regard, but they are still there.

**Comment by etalon** [comment]
You mean HP, Elites, Fast Attack,Heavy Support? I can select them, but nothing below appears. Made a Screenshot of my problem.
![screenshot160909 003](https://cloud.githubusercontent.com/assets/8570866/18397004/8a4874d4-76c6-11e6-946c-df7010a53938.png)

**Comment by cartag** [comment]
Scroll down farther in the left hand column. The top section won't be listed, as it's formations just for their specialized detachment. FW models can't be brought as part of the decurion formations, with few exceptions.

**Comment by cartag** [comment]
![image](https://cloud.githubusercontent.com/assets/4388344/18397062/c07de5b8-7683-11e6-864a-c1048f94f6b0.png)

![image](https://cloud.githubusercontent.com/assets/4388344/18397082/cd327c42-7683-11e6-9f3b-461ca7b794e2.png)

**Comment by etalon** [comment]
D'oh! Now I got it. Now I just have to find the cobra...
Thanks a lot.
