### ISSUE TITLE
Cataphracti terminator options are insufficient to specify model weapons

### ISSUE THREAD

**Issue by Shiney1965** [BSData/wh40k-7th-edition#2458]
When listing the cataphracti terminators on iOS there is an option to exchange power claws for power fist or both weapons, but no way to specify whether you are using one or two claws.  Also when you substitute power fist for power sword on sergeant it adds the fist but leaves the sword.  It would be better if we can specify exactly which weapons we are using. I don't know if this bug also appears in other versions -- his is iOS only.  Thanks.

**Comment by Shiney1965** [comment]
I meant lightning claws where I said power claws

**Comment by GenWilhelm** [comment]
It's not an iOS issue, the Cataphractii Terminator Squad has been lazily implemented.

Took less than an hour to rebuild it:
http://i.imgur.com/wsHDp48.png

~~Unfortunately I'm only an amateur and not part of the actual team.~~

**Comment by Shiney1965** [comment]
Thank you.  Maybe the developers will implement your code if you send it in?
