### ISSUE TITLE
Add Games Workshop Kill Team detachment

### ISSUE THREAD

**Issue by lordofhyphens** [BSData/wh40k-7th-edition#2459]
Would be nice to at least have the detachment basics, if not checking for the other restrictions in the detachment (no 2+, no fliers, etc). 

Book is available on Blacklibrary.com and the older EPUB (for which the detachment specifics did not change) is likely still findable.

**Comment by flakpanda** [comment]
Added. Closes #2459

**Comment by lordofhyphens** [comment]
Thanks!
