### ISSUE TITLE
Death from the Skies overhaul

### ISSUE THREAD

**Issue by GenWilhelm** [BSData/wh40k-7th-edition#2470]
- [x] Astra Militarum
- [x] Militarum Tempestus
- [x] Space Marines
- [x] Blood Angels
- [x] Grey Knights
- [x] Dark Angels
- [x] Space Wolves
- [x] Chaos Space Marines
- [x] Khorne Daemonkin
- [x] Dark Eldar
- [x] Eldar
- [x] Necrons
- [x] Orks
- [x] Tau

Above are all the factions that may take a Flyer Wing. We need to go through and ensure each of them can select any of their Flyers as a Flyer Wing, as per the restrictions in Death from the Skies (page 104). We also need to make sure all of the Wing Leader benefits are listed (pages 76-83).

**Comment by tag8833** [comment]
Orks can take Flyers as a wing.   I haven't added the Wing Leader benefits.  I'll do that tomorrow.

**Comment by Lynkon** [comment]
Please add Militarum Tempestus to this list.

**Comment by cartag** [comment]
CSM has been set up to allow the flyers that can be brought in flyer wings to do so. I added the detachment in the first place.

**Comment by afraeve** [comment]
Are we saying that essentially any aircraft (not just the ones we have specific datasheets for) can be taken in a Flyer Wing?

**Comment by DrTobogganMD** [comment]
No. I don't know why these were updated as such. Only dfts and the fw sheet are eligible for flyer wings

This includes flyers in the Death from the Skies book, and in the PDF here: https://www.forgeworld.co.uk/resources/fw_site/fw_pdfs/Warhammer_40000/Death-from-the-Skies.pdf

No other flyers are allowed Wings.

**Comment by cartag** [comment]
Only the vehicles that are said by GW or FW to allow Flyer Wings are eligible to be taken that way.

**Comment by amis92** [comment]
@GenWilhelm ?

**Comment by GenWilhelm** [comment]
A Flyer Wing may be taken either from a datasheet that allows it to be upgraded to a Wing, or as a formation that defines itself as a Wing.

**Comment by cartag** [comment]
And not all flyers have datasheets that allow themselves to be taken as Flyer Wings.
