### ISSUE TITLE
CSM Raptor Talon Formation

### ISSUE THREAD

**Issue by Dyemor** [BSData/wh40k-7th-edition#2472]
The Chaos Lord in the Raptor Talon formation should have the Jump Pack as a free and/or compulsory option.

**Comment by cartag** [comment]
Read the Chaos Lord Restriction rule in BS. 

> This Formation's Chaos Lord must be equipped with a jump pack at no additional points cost.
> 
> THIS WILL BE IMPLEMENTED IN BS 2.0

It does not do anything to change stats when taking a jump pack. It's already set up and working in the BS2 file, it is more involved in this.

**Comment by cartag** [comment]
Screw it, I won't have to do upkeep on this file for much longer anyways, I'll just make a ton of different copies of the Chaos Lord entry, one for each formation.

**Comment by Dyemor** [comment]
Thanks.
