### ISSUE TITLE
Bug report: Codex Space Marines

### ISSUE THREAD

**Issue by katfude** [BSData/wh40k-7th-edition#248]
When selecting 2 Crusader squads and equipping 1 Initiate with a Power Fist in both squads, it is flagged as illegal. The message is:

Crusader Squad has 1 too many selection of Power Fist (maximum 1)
Crusader Squad has 1 too many selection of Power Fist (maximum 1)

It appears the appropriate modifiers and conditions are wrong, as it is restricting the entire detachment to 1 Crusader Squad Power Fist total.

Also: If you take 2 Crusader Squads and equip only one of them with a Heavy Weapon, you get the following error.

All Crusader Squads must have the same number of selections from Initiate Heavy Weapon
All Crusader Squads must have the same number of selections from Initiate Heavy Weapon

**Comment by Kangodo** [comment]
For some reason their heavy weapons were marked as collective, which shouldn't be there.
