### ISSUE TITLE
Angel's Blade Supplement

### ISSUE THREAD

**Issue by GenWilhelm** [BSData/wh40k-7th-edition#2488]
- [x] Update Codex: Blood Angels profiles.
- [x] Add new Detachments.
- [x] Add new Formations.
- [x] Add new Relics.

**Comment by amis92** [comment]
Honestly I don't get it. You've created an issue with a checklist (which is all checked as done?) but issue is not closed, neither are there any commits referencing it.

BTW your latest contributions are many and awesome! Great to have you on board! :)

**Comment by GenWilhelm** [comment]
I always forget to do something... Usually it's not increasing the version number but apparently today it's not referencing issues. And yeah, the issue isn't closed because I'm still chasing a bug in the Relics department and didn't want to open a new issue.

Commits in order:
- [Updated Profiles](https://github.com/BSData/wh40k/commit/ab197b2dad81e4351d42f115db4c64a2a85ed30d)
- [New Formations](https://github.com/BSData/wh40k/commit/53a2fd401baf6784939752972d5086ce5f9b0f2d)
- [New Detachments](https://github.com/BSData/wh40k/commit/ae46230353e3ffe9c3ddcae65c9aceb5feaa160b)
- [New Relics](https://github.com/BSData/wh40k/commit/4f8d27565eb192de2ff1c3a6a96a95f8a362f4d5)
