### ISSUE TITLE
Bug Report: Space Wolves: Codex (2014) v5 - Wolf Guard Terminators - Heavy Weapon Validation

### ISSUE THREAD

**Issue by Xianator** [BSData/wh40k-7th-edition#249]
It appears that the requirement for having 5 Wolf Guard Terminators in the unit to be eligible for the first heavy weapon is not being checked.

**Comment by Xianator** [comment]
Also seeing a formatting bug that WG Terminators with TH+SS and Pair of Wolf Claws models do not appear in Bold on the roster.

**Comment by ghost** [comment]
The 5-for-a-heavy-weapon was awkward to fix - the obvious routes didn't throw up a warning - but I've checked all the combinations I could think of & it seems to be sorted now.

The bold text (or lack of it) isn't a bug - it signifies items you can drill into for further options, e.g. to swap the weapons.
