### ISSUE TITLE
Tau Dawn Blade not validating for bonding knife. 

### ISSUE THREAD

**Issue by SSSlippy** [BSData/wh40k-7th-edition#2496]
Anything from the farsight enclave book is required to have the bonding knife if it can take one.

**Comment by GenWilhelm** [comment]
Can you provide more details: What version of BattleScribe are you on? What platform are you on? Is it an issue with one particular unit or all units?

**Comment by SSSlippy** [comment]
This is on PC.  I have attached a picture to show that there is no validation error.  This seems to be for all the units.
![error](https://cloud.githubusercontent.com/assets/22452849/18842728/109c48f6-83e4-11e6-9456-f32f92670ea7.PNG)

**Comment by GenWilhelm** [comment]
Have you selected the 'Farsight Enclaves' supplement under (No Category)?

**Comment by SSSlippy** [comment]
I did not.  This forces the validation.  My mistake.
