### ISSUE TITLE
Dark Angels codex

### ISSUE THREAD

**Issue by DarkAngelsPumbaa** [BSData/wh40k-7th-edition#2505]
The Codex are unable to download. Battlescribe error:
Details:
Errors occurred updating data files from repositories

> https://github.com/BSData/wh40k/blob/master/Dark%20Angels%20-%20Codex%20(2015).cat: Error updating from repository https://github.com/BSData/wh40k/blob/master/Dark%20Angels%20-%20Codex%20(2015).cat: net.battlescribe.a.c.e: Data file is too old and is no longer supported (null)
>     at net.battlescribe.desktop.b.j$1.a(BattleScribe:63)
>     at net.battlescribe.desktop.b.j$1.doInBackground(BattleScribe:40)
>     at javax.swing.SwingWorker$1.call(Unknown Source)
>     at java.util.concurrent.FutureTask.run(Unknown Source)
>     at javax.swing.SwingWorker.run(Unknown Source)
>     at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
>     at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
>     at java.lang.Thread.run(Unknown Source)

**Comment by GenWilhelm** [comment]
Battlescribe can't handle just an individual codex, it needs additional information about the game system  (Detachments, Unit types, etc.), which are handled in separate files.

These easiest way to get everything you need is in the complete package:

> https://battlescribedata.appspot.com/repos/wh40k/index.bsi

**Comment by GenWilhelm** [comment]
This has been inactive for a while, so we're assuming the issue has been resolved.
