### ISSUE TITLE
Necron catz file - conclave of the burning one

### ISSUE THREAD

**Issue by casperionx** [BSData/wh40k-7th-edition#2512]
Conclave of the burning one should be a transcendent c'tan as per the draft faq. At the moment the only options are the two unique c'tans.

**Comment by DrTobogganMD** [comment]
FAQs are in Draft and not final yet.  Once they are final, any necessary changes will be made.  Only the changes deemed Errata apply to current rulesets.

**Comment by casperionx** [comment]
At the very least transcendent c'tans need to be an option for the conclave of the burning one.

**Comment by cartag** [comment]
@casperionx no, it doesn't. The formation, RAW, states "C'tan Shard," not "C'tan." We try to keep BS RAW, not RAI. Once the FAQ is finalized then it will be changed.
