### ISSUE TITLE
Genestealer Cult - Purestrain Genestealer unit profile correction

### ISSUE THREAD

**Issue by gwinkleman** [BSData/wh40k-7th-edition#2517]
Looks like the Purestrain Genestealers currently have 2 base attacks (like Tyranids), where the Genestealer Cult Codex has Purestrain Genestealers with 3 base attacks.

**Comment by gwinkleman** [comment]
@GenWilhelm, I updated my data repositories but I'm still not seeing the fix. Is there something else that I need to do so that I can see the correction?

**Comment by GenWilhelm** [comment]
The fix hasn't been released yet, so updating won't pull it from the repository.
If you can't wait for the next release you can manually download the Genestealer Cults .cat file and replace your local version with it.
