### ISSUE TITLE
encountering error while syncing

### ISSUE THREAD

**Issue by senpai514** [BSData/wh40k-7th-edition#252]
first off thanks for letting me join. I watched the video tutorial last night and I followed right along with each step for my initial setup. I started off with a simple update to make sure everything was being done right and had no problems until I went to sync. I get this error message:

Failed to sync this branch - You might need to open a shell and debug the state of this repo.

I then noticed I got new uncommitted changes, a us.stackdump and a .gitignore

Please help me resolve this issue.

**Comment by Kangodo** [comment]
It apparently happens when Github updates itself or something?
My solution was to copy the files I've changed to a folder.
Then remove wh40k from my list, clear all the files and re-add it.
And then I would copy the changed files back into the map.

**Comment by senpai514** [comment]
I removed and tried to reclone with fresh files made the change, saved and tried to sync still get error and the us.stackdump

**Comment by senpai514** [comment]
I see the status access violation in the stackdump does that indicate a lack of proper access or permissions to do said action

MSYS-1.0.12 Build:2012-07-05 14:56
Exception: STATUS_ACCESS_VIOLATION at eip=68086014
eax=68570000 ebx=000057AC ecx=000015EB edx=00000000 esi=00000000 edi=68570000
ebp=0028FE48 esp=0028FE3C program=us
cs=0023 ds=002B es=002B fs=0053 gs=002B ss=002B
Stack trace:
Frame     Function  Args
0028FE48  68086014  (68570000, 00000000, 000057AC, 00000004)
0028FE98  68001CB0  (006F2A9C, 00000001, 0028FEE8, 680044EA)
0028FEE8  680045C7  (00000000, 00000000, 0028FF28, 004082F0)
0028FF08  68004C5F  (004042C8, 00000000, 00000000, 00000000)
0028FF28  68004C98  (00000000, 00000000, 00000000, 00000000)
0028FF58  00408200  (004042C8, 00000000, 00000000, 00000000)
0028FF88  0040103D  (7EFDE000, 0028FFD4, 771C9F72, 7EFDE000)
0028FF94  7566338A  (7EFDE000, 7524A621, 00000000, 00000000)
0028FFD4  771C9F72  (00401000, 7EFDE000, 00000000, 00000000)
0028FFEC  771C9F45  (00401000, 7EFDE000, 00000000, 78746341)
End of stack trace

**Comment by amis92** [comment]
It is quite so. Seems like the folder in which you work doesn't have proper access permissions, as in, the program GitHub doesn't have permissions to write into it. Which is weird, because you _do_ the cloning to this folder.

**Comment by amis92** [comment]
Found this: http://stackoverflow.com/questions/17249780/github-github-for-windows-on-every-commit-generates-us-stackdump

**Comment by senpai514** [comment]
I read that in the link and it doesn't really tell me anything as I don't quite understand what its telling  you to do.

**Comment by senpai514** [comment]
I also notice an permission denied line as my repo finishes being cloned as well
![photo](https://cloud.githubusercontent.com/assets/8508947/4014015/8bcaaec4-2a1c-11e4-9f2a-e7b69bd9ba53.PNG)

**Comment by amis92** [comment]
First I would reinstall GitHub. Seem like a pretty f****d up installation. Otherwise follow steps from the answer. I can rewrite them here for your convenience.

**Comment by senpai514** [comment]
I have reinstalled the desktop app a couple times no change tried using a different location to clone to no change. could use some help with the steps from the answer

**Comment by senpai514** [comment]
looks like I am good to go I did a system restore tried an install again and it looks like I am up and running after conducting a small add to test sync. Thanks for the time trying to help fix this.
