### ISSUE TITLE
Tau Dawn Blade Contigent

### ISSUE THREAD

**Issue by ghost** [BSData/wh40k-7th-edition#2520]
When creating a Dawnblade Contingent for a Tau army, crisis battlesuits are not available under troop choices. Dawn Blade Contingents are only available under Farsight Enclaves, which allows crisis suits to be taken as a troop choice. This happens even with Farsight Enclaves being selected under category. Thank you.

**Comment by DrTobogganMD** [comment]
Dawn Blade is a decurion style force and does not have troop choices.

Crisis suits as troops are available in a CAD when selecting Farsight Enclaves in the "No Category" slot.
