### ISSUE TITLE
Kill Team rules in existing catalogues

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#2535]
**File:** Warhammer40K.gstz

**BattleScribe version:** 1.15.09

**Platform:** Android

**Dropbox:** No

**Description:** Hi! Can ad a slot specialization on kill team roster plz?

Thairne: added List to OP for tracking
- [x]   Adepta Sororitas
- [x]   Astra Militarum - Codex
- [x]   Blood Angels
- [x]   Chaos - Khorne Daemonkin
- [x]   Chaos Daemons
- [x]   Chaos Space Marines - Codex
- [x]   Cult Mechanicus
- [x]   Dark Angels
- [x]   Dark Eldar - Codex
- [x]   Dark Eldar - Haemonculus Covens
- [x]   Deathwatch - Codex
- [x]   Eldar Craftworlds - Codex
- [x]   Genestealer Cults - Codex
- [x]   Grey Knights
- [x]   Harlequins
- [x]   Inquisition
- [x]   Legion of the Damned
- [x]   Militarum Tempestus
- [x]   Necrons - Codex
- [x]   Orks - Codex
- [x]   Skitarii
- [x]   Space Marines
- [x]   Space Wolves
- [x]   Tau - Codex
- [x]   Tyranids

I think we can focus on these. Adding niche things like Elysians.. a niche of a niche of a niche...

- [x]   ~~Adeptus Custodes~~ Per the Burning Of Prospero Dataslate, 1 squad is 260pts and all have 2+ saves!
- [x]   Astra Militarum - FW - Armoured Battle Group
- [x]   Astra Militarum - FW - Death Korp of Krieg Assault Brigade
- [x]   Astra Militarum - FW - Death Korp of Krieg Siege Regiment
- [x]   Astra Militarum - FW - Elysian Detachment D-99
- [x]   Astra Militarum - FW - Elysian
- [x]   ~~Chaos Renegade Knights~~ I think not... :smile:
- [x]   Eldar - Corsairs
- [x]   ~~Fortifications and Stronghold assault~~ Per the FAQ, you can't have an army of fortifications...
- [x]   ~~Imperial Knights~~ Seriously!? :smile:
- [x]   Necrons - FW - Dark Harvest
- [x]   ~~Officio Assassinorum~~ Each Assassin is Approx. 140 pts, 4 models min in Kill Team at 200 pts!
- [x]   ~~Orks - FW - Dread Mob~~ CAT is deprecated
- [x]   Renegades & Heretics - FW
- [x]   Sisters of Silence
- [x]   ~~Space Marines - FW - Siege Assault Vanguard~~ No-one cares 
- [x]   ~~Tyrant's Legion - FW - Defenders of Badab~~ No-one cares

**Comment by amis92** [comment]
Honestly I don't believe we are able to successfully launch any kind of Kill Team repo, nor is it a good idea to add clutter into the main repo. There are no volunteers, and I don't think current maintainers are all so interested in developing two catalogues concurrently. The fan-kill team (HoR KT) is only a single-person effort and it doesn't do well I think.

If we gather a dedicated group of people, then maybe. Until then, it's unviable IHMO.

**Comment by efalsken** [comment]
The new version of Battlescribe should allow us to do this with minimal effort. Let's put it on a list once we make the cutover.

**Comment by alphalas** [comment]
if people are still interested i can try to see what i can get rolling.

**Comment by amis92** [comment]
I think that first we need a month at least to stabilize (debug) the 2.0 version of files. It's the lowest priority, I think.

**Comment by Thairne** [comment]
Just a FYI - I added Kill Team Specialists to my DA Codex a few weeks ago.
It really is not much work. I included the specialst Entry Group into the GST, so all one needs to do is link the Entry Group to the entries that are viable for a Kill Team detachment - done.
Rest is taken care of via the detachment and constraints in the SEG.

**Comment by FarseerVeraenthis** [comment]
That's cool, do we need a tracking list to keep track of which cats have been updated?  The same as the conversion to 2.0 list...

**Comment by Thairne** [comment]
Can't hurt tbh...

**Comment by Thairne** [comment]
- [ ]   Adepta Sororitas
- [ ]   Astra Militarum - Codex
- [ ]   Blood Angels
- [ ]   Chaos - Khorne Daemonkin
- [ ]   Chaos Daemons
- [ ]   Chaos Space Marines - Codex
- [x]   Cult Mechanicus
- [x]   Dark Angels
- [ ]   Dark Eldar - Codex
- [ ]   Dark Eldar - Haemonculus Covens
- [ ]   Deathwatch - Codex
- [ ]   Eldar Craftworlds - Codex
- [ ]   Genestealer Cults - Codex
- [ ]   Grey Knights
- [ ]   Harlequins
- [ ]   Inquisition
- [ ]   Legion of the Damned
- [ ]   Militarum Tempestus
- [ ]   Necrons - Codex
- [ ]   Orks - Codex
- [x]   Skitarii
- [ ]   Space Marines
- [ ]   Space Wolves
- [ ]   Tau - Codex
- [ ]   Tyranids

I think we can focus on these. Adding niche things like Elysians.. a niche of a niche of a niche...

**Comment by tag8833** [comment]
I've got Orks Done.

**Comment by FarseerVeraenthis** [comment]
That should be Deathwatch & Eldar Craftworlds done :smile:

**Comment by FarseerVeraenthis** [comment]
Seriously, whoever setup the Specialists as a shared entry in the GST deserves a medal...!!
Makes it so much easier to implement the Kill Team rules in the CAT's...

**Comment by Thairne** [comment]
I'd be happy with some kind of trophy I can place next to my models :P

**Comment by FarseerVeraenthis** [comment]
@cartag can you put the kill team in the Chaos CAT's please :smile:

**Comment by FarseerVeraenthis** [comment]
I just added the Kill Team selections to Space Marines... So if/when the CAT breaks, you know why...
Only a couple more to go :smile:

**Comment by alphalas** [comment]
so the two remaining are the two red-headed stepchildren nobody wants eh? lol

**Comment by Thairne** [comment]
Honestly. I think we can just ignore those things.

**Comment by cartag** [comment]
Much like actual red headed step children.

**Comment by FarseerVeraenthis** [comment]
All done then 😀 hurrah!!
