### ISSUE TITLE
BS 2.0 GST/Catalog Format

### ISSUE THREAD

**Issue by DrTobogganMD** [BSData/wh40k-7th-edition#2548]
With the immanent arrival of BS 2.0 the GST is being updated.

We have integrated all BRB special rules, Psyker Powers, and Fortifications into the main GST.  This will allow you to take these items out of the catalog files themselves to improve performance and save duplicated work.

2.0 also allows us to have Force types added directly to the catalogs. This will improve user experience by eliminating the myriad of useless force types.  When implemented, for example, you will only see CAD, Formation, Allied force, and Decurion when making a Necron list.

CAD, Formation, and Allied Force will remain in the GST, while the codex specific forces should be moved into their respective codex files.  I've added a list of our Catalog files.  Necrons, Space Marines, CSM, and Khorne have all been completed as part of our attempt to prep for this update. Once Jon presses the big red button we will be able to back up the current repo and merge the updated cat files.
- [x]   Adepta Sororitas
- [x]   Astra Militarum - Codex
- [x]   Astra Militarum - FW - Armoured Battle Group
- [x]   Astra Militarum - FW - Death Korp of Krieg Assault Brigade
- [x]   Astra Militarum - FW - Death Korp of Krieg Siege Regiment
- [x]   Astra Militarum - FW - Elysian Detachment D-99
- [x]   Astra Militarum - FW - Elysian
- [x]   Blood Angels
- [x]   Chaos - Khorne Daemonkin
- [x]   Chaos Daemons
- [x]   Chaos Renegade Knights
- [x]   Chaos Space Marines - Codex
- [x]   Cult Mechanicus
- [x]   Dark Angels
- [x]   Dark Eldar - Codex
- [x]   Dark Eldar - Haemonculus Covens
- [x]   Deathwatch - Codex
- [x]   Eldar Craftworlds - Codex
- [x]   Eldar - Corsairs
- [x]   ~~Fortifications and Stronghold assault~~ Move to GST
- [x]   Genestealer Cults - Codex
- [x]   Grey Knights
- [x]   Harlequins
- [x]   Imperial Knights
- [x]   Inquisition
- [x]   Legion of the Damned
- [x]   Militarum Tempestus
- [x]   Necrons - Codex
- [x]   Necrons - FW - Dark Harvest
- [x]   Orks - Codex
- [x]   Orks - FW - Dread Mob
- [x]   Renegades & Heretics - FW
- [x]   Renagades of Vraks - FW - The Lost and the Damned
- [x]   Renegades Heretics Renegades of Vraks
- [x]   Skitarii
- [x]   Space Marines
- [x]   Space Wolves
- [x]   Tau - Codex
- [x]   Tyranids
- [ ]   Tyrants Legion - FW - Defenders of Badab

**Comment by tag8833** [comment]
I've got the direct conflicts in the Ork Codex resolved.  I still need to optimize it and create the detachments.

**Comment by amis92** [comment]
Also for reference, when upgrading please take a look here: #2698

**Comment by FarseerVeraenthis** [comment]
Are these to be ticked off once their "Decurion" style formation is moved from the GST to the CAT??
If so, several more can be ticked and we can all feel great for making awesome progress...
As I see it, the only formations still left in the GST that should be moved are Space Wolves, the "AM Cadian Battlegroup", the Eldar Corsair Fleet Raiding Company, and whatever CAT the "SAV Siege Assault Vanguard Detachment" should be in...
Or is there more to it than that??

**Comment by cartag** [comment]
Siege Assault Vanguard is from IA:10 I think. Paging @Kohato to add to SM file. 

As for ticking them off, I think they should be once they've been finalized for BS2.

**Comment by DrTobogganMD** [comment]
Siege Assault Vanguard requires a whole new army list unfortunately as it is a 6th Ed book.  Until Badab is reprinted in 2e I think it's best to Leave SAV as it's own.  I'll move it into the SAV cat file though!

**Comment by FarseerVeraenthis** [comment]
who checks them??
I think Craftworld Eldar and Deathwatch will be ready with my latest two commits...

**Comment by Relorian** [comment]
Any plans to get the Astra Militarium special rules in?   Is there a way i can help possibly by typing them up?  Also could assist with Sisters of Battle and Inquisition in that way as well if needed/wanted

**Comment by alphalas** [comment]
1, race special rules don't go in gst 
2, which rules?
3, considering I'm going to be ripping them all apart soon I'd rather you not.

**Comment by alphalas** [comment]
I do appreciate the offer though

**Comment by Thairne** [comment]
Tyrant's Legion does not show an error and noone seems to want to touch a thing that basically nobody seems to use anymore... So....
