### ISSUE TITLE
Bug Report: Skitarii - Codex.catz

### ISSUE THREAD

**Issue by OtterlyOlive** [BSData/wh40k-7th-edition#2550]
**File:** Skitarii - Codex.catz

**BattleScribe version:** 1.15.07

**Platform:** Desktop

**Description:**
In the AdM Adeptus Mechanicus War Convocation, when choosing War Gear for the Ranger Alpha, it is not possible to choose a weapon from the Melee Weapons list, as it is hidden.

**Comment by Thairne** [comment]
1.15 will no longer be supported.
I'll take a peek if this issue remains after I update the file to 2.0.

**Comment by OtterlyOlive** [comment]
Gotcha, thanks!

**Comment by Thairne** [comment]
At first this is not the case...
However, it seems to be by design if you choose the phase taser relic. I don't have the codex with me, but I think it's a "trade-in" thing that happens here.

**Comment by OtterlyOlive** [comment]
Well caught! 👍  It was indeed the phase taser relic.

Though the rulebook, as I far as I can see, does not speak about a "trade-in" happening.

**Comment by laurent-conte** [comment]
you can't have 2 melee weapons at the same time on the alpha, same thing happen if you choose the phosphoenix pistol, u can have only one pistol.

**Comment by Thairne** [comment]
So that settles it ;)
