### ISSUE TITLE
Space Marines - Tactical Sergeant can take Narthecium?

### ISSUE THREAD

**Issue by Zuldarok** [BSData/wh40k-7th-edition#2557]
Is it correct that sergeants can grant the unit feel no pain at no cost? It is currently listed as an option in the sergeants wargear.

**Comment by Salrantol** [comment]
Check the conditions. It IS an option for Red Scorpions from Forge World. 

Sent from Yahoo Mail on Android 

  On Sat, Oct 29, 2016 at 2:26 PM, Zuldaroknotifications@github.com wrote:  
Is it correct that sergeants can grant the unit feel no pain at no cost? It is currently listed as an option in the sergeants wargear.

**Comment by francoisbeaulieu** [comment]
It's only possible for the red scorpions chapter. It's displayed for all on iOS due to a known hiding bug. Is this the case for you?

## 

François Beaulieu (iPhone)
(514) 667-0691 x2061

**Comment by Zuldarok** [comment]
It is showing up when I make a raven guard list. On both android and windows.

**Comment by francoisbeaulieu** [comment]
Are you on an iOS device? (iPhone or iPad?)

## 

François Beaulieu (iPhone)
(514) 667-0691 x2061

**Comment by Zuldarok** [comment]
No iOS. Android and windows.

**Comment by Zuldarok** [comment]
Also when you make a SM list, it makes cypher and a techmarine mandatory when making a CAD.

**Comment by francoisbeaulieu** [comment]
Which version of Battlescribe are you running? 

## 

François Beaulieu (iPhone)
(514) 667-0691 x2061

**Comment by cartag** [comment]
If you're running BS2 and using this repo, there may be errors currently. The files that should be used with BS2 will be uploaded later tonight.

**Comment by Zuldarok** [comment]
This is all in BS2

**Comment by DrTobogganMD** [comment]
Fixed in 2.0

**Comment by francoisbeaulieu** [comment]
Not seeing the option to add the Narthecium to Red Scorpions Tac sergeants anymore. Has this fix actually broken it?

**Comment by francoisbeaulieu** [comment]
The Narthecium does show up in the roster view, as if it was auto-selected by selecting the RS chapter tactics. Is this what was wanted?

## 

François Beaulieu (iPhone)
(514) 667-0691 x2061

**Comment by DrTobogganMD** [comment]
I think that's what I'd intended. I'll double check when I'm free. Went on a bug fixing spree and then got busy - cleared out a good chunk we had though.

**Comment by francoisbeaulieu** [comment]
I don't think this is correct. The rule only applies to tac sq sergeants and it currently displays for any formation that selects RS chapter tactics, even if it doesn't have a tac squad.

Also, a user may elect to not select the narthecium even if he has a tac squad, because he may not have a physical model equipped with one.

--
François Beaulieu (iPhone)
(514) 667-0691 x2061
