### ISSUE TITLE
general github for windows issues

### ISSUE THREAD

**Issue by senpai514** [BSData/wh40k-7th-edition#256]
just got this pop up failed to create commit with options that say open git shell and cancel. what do I do?

**Comment by Kangodo** [comment]
Does it work now?
I have this once every three weeks, no idea why.
Usually solve it by re-starting Github.

**Comment by senpai514** [comment]
I figured out the commit issue by deleting the index.lock file

**Comment by senpai514** [comment]
but then had the debug the state of this repo error again when I tried to sync the next update and now I cant even clone the repo it says check internet connection.

**Comment by senpai514** [comment]
ok an update for you guys it appears my COMODO has been my primary culprit with blocking all the incoming and out going processes so it seems that if I turn off any system protection programs while Im working I should have no problems.

**Comment by amis92** [comment]
Really glad you found the issue. That's why I hate these "protecting" programs. Cheers!

**Comment by senpai514** [comment]
yeah now if all goes well I can crank out these updates and really help out.

**Comment by Kangodo** [comment]
Glad to hear it!
What Codices are you probably going to focus on?
You don't have to focus on one, but I pay more attention on Necrons and Blood Angels since that are my armies.

**Comment by senpai514** [comment]
I am a Ultramarine player so I am going to start there and update the dataslates and IA2 second edition vehicles especially since I own most of them. as well as all the LOW too then I can help push some of the tanks that are available to all to the other power armour codices.

I have electronic copies of about every current rulebook in use from GW and FW in my google drive I can share access with you guys if you need or have been waiting for a certain publication to update entries

**Comment by Kangodo** [comment]
Ah, that is great! Space Marines are probably the biggest Codex and they receive too little attention.
My Blood Angels-file has most IA2 units in there, so you could copy-paste most stuff.
The only issue is that the links would stop working, that's something that you'd have to do over.
The Space Wolves also has some great stuff, like all Legacies of Glory. I copied them over to my Blood Angels and it saved me a lot of work.

**Comment by ghost** [comment]
Hi @senpai514 - do you have the Red Scorpions info from IA4 2nd ed? I'm adding their relics to the Siege Vanguard list, but the characters need updating, too.

**Comment by senpai514** [comment]
@khambatta that just came out so I don't have a copy of that just yet. getting the IA's in pdf is hard sometimes
