### ISSUE TITLE
[Anon] Bug report: Dark Angels - Warhammer40K.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#2571]
**File:** Warhammer40K.gstz

**BattleScribe version:** 2.00.02

**Platform:** Android

**Dropbox:** No

**Description:** Dark Angels Chapter Master has missing Artificer Armor option.
All IC's missing Terminator Armor option.

**Comment by Thairne** [comment]
All options are there in desktop version on either the CM for Artificer or TDA for Librarians or others.
Does not look a data file problem to me and rather like a BS Bug. Mobile versions are notorious for this type of behavior.

**Comment by Thairne** [comment]
![bs](https://cloud.githubusercontent.com/assets/8590840/19905106/9eabfa80-a075-11e6-833b-4eb0298440e2.png)
