### ISSUE TITLE
Chaos Space Marines - Veterans of the Long War

### ISSUE THREAD

**Issue by CorvaVespera** [BSData/wh40k-7th-edition#2572]
In the BattleScribe Data, Veterans of the Long War is listed as having new cost, but in the codex it has a variable point cost depending on the unit - 1/model for Chaos Marines, Chaos Bikes, and Havocs; 2/model for Chosen and Raptors; 3/model for Warp Talons, to list some examples.

**Comment by cartag** [comment]
With how it's laid out in the editor, it _should_ be working, I'm trying to figure out why it's not.

**Comment by Jonskichov** [comment]
Fixed an issue where instanceOf conditions on shared items wouldn't work. Not sure if this is related.

Fixed in: 
Desktop 2.00.05
Android 2.00.10
iOS 2.00.07 (currently awaiting review, should be out tomorrow)
