### ISSUE TITLE
Skitarii minimum selection

### ISSUE THREAD

**Issue by laurent-conte** [BSData/wh40k-7th-edition#2580]
Any Skitarii project will either request 3 selections of battle maniple (like formation detachment, Cohort mechanicus, war convocation...) 1 ruststalker and 1 infiltrators.

This is related to already made ticket for Cult mechanicus: [Anon] Bug report: Cult Mechanicus Codex 2015.catz #2570

**Comment by Thairne** [comment]
Was just fixed with my 2.0 rework for the Skitarii. v32 helps.
