### ISSUE TITLE
Genestealer Cult BS2.0 Constraint error

### ISSUE THREAD

**Issue by Gnofry** [BSData/wh40k-7th-edition#2582]
I noticed that the catalog update list shows GC updated, however Ghosar Quintus Broodkin still has the 'min requirement in force 1' which throws an error in a Formation Detachment. Also, I don't know how far along you are making so that "Necrons only show CAD, Allied, Formation, Decurion", but GC still has all of the options for all the other Force Types.

**Comment by GenWilhelm** [comment]
Ghosar Quintus Broodkin was rolled into the main file for Genestealer Cults with the initial release of their codex - if you still have the option to select Ghosar Quintus Broodkin as a separate catalogue, please refresh your data: https://battlescribe.net/?faq=refreshData

The only error I am seeing when selecting a Formation detachment is "Formation Detachment must have 1 more selection from Formation", which is the standard restriction and easily resolved by adding a Formation to the roster.

The other Force Types you are seeing are from catalogues that haven't been updated to BS2 yet, so their unique Force Types haven't been moved out of the main 40k game system file. This is an issue for all catalogues and will resolve itself once all updates have been completed.

If this doesn't resolve your issue please reply here giving specific details on how to reproduce the error, as well as the platform you are experiencing them on.
