### ISSUE TITLE
tyranid's monsterous creatures not showing rule from main rule book

### ISSUE THREAD

**Issue by Xephrim** [BSData/wh40k-7th-edition#2583]
Monstrous creatures should have the smash rule from main 40k rule book,  not seeing this reflected in tyranid data file.   this is a issue where codex is still 6e and has not been update to 7e..

**Comment by Randobar** [comment]
Will not have time for this during the next 2 weeks.

**Comment by Randobar** [comment]
Thanks for solving that.
