### ISSUE TITLE
[Space Marine] Lucius Pattern dreadnought drop pod costed incorrectly.

### ISSUE THREAD

**Issue by athelred** [BSData/wh40k-7th-edition#2590]
In the current space marine codex (v2 as of the time of this writing), the Lucius Pattern dreadnought drop pod is costed at 65 points.  The most recent 40k reference to the drop pod I can find is from IA2 2nd edition which has the cost as 50 points.

**Comment by DrTobogganMD** [comment]
This is a tough call.  IA: Apoc (c2013) lists it as 65 points.  IA2 2nd ed (c2013) lists it as 50.  I think what i'll do is mark it as 50 points and modify to 65 if "Show Apocalypse Entries" is checked.  Does that sound reasonable from an end user view?

**Comment by athelred** [comment]
That will work if you separate show Forgeworld from show apocalypse.  They are currently a single selection.

I know that the drop pod was listed as 50 points prior to the update (not conclusive, but indicative), and I think IA2 2nd ed is the most current, but I could be wrong.  Looking at various forum posts from the time seem to indicate this.

I love Forgeworld models, but man are their rules a sewer at times.

**Comment by DrTobogganMD** [comment]
Yea, Making sense of their rules sometimes is a nightmare. I'll take a look around to see what I can find on which may be the "Correct" before I make any changes.

**Comment by DrTobogganMD** [comment]
Yea, I can't find shit on which to use. IA Apoc 2013 came out in June of that year. I'm assuming IA2-2nd came out in Late November of that year from what I can find.

So we'll go with the most recent source. I'll change it to 50.
