### ISSUE TITLE
[Anon] Bug report: Tyranid Hive Fleet missing

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#2597]
**File:** Warhammer40K.gstz

**BattleScribe version:** 2.00.04

**Platform:** Android

**Dropbox:** No

**Description:** I cannot locate the Tyranid Hive Fleet Detachment in this version.

**Comment by Gnofry** [comment]
Looks like it was removed from the 40k data file and was not added into the Tyranids data file. I am not finding it in either location.
