### ISSUE TITLE
Quota over run again on 40K files. 

### ISSUE THREAD

**Issue by Toreador13** [BSData/wh40k-7th-edition#26]
I was talking about this earlier, and it seems to happen very infrequently. Problem with this is that it backs up all of my datafiles, and when the feed errors, I have no catalogues without trying to go back through the backup directory and pull a version of each back out. Kind of a pain. I never ran out of space on the ftp, but some months it was getting quite a bit of usage and I was getting warnings from my provider. Not sure if I can pull up any history on that anymore, as it's total usage for the site. 

![quota](https://cloud.githubusercontent.com/assets/6875311/2773671/25320380-caa2-11e3-82bd-a7f65b765bcf.jpg)

**Comment by Jonskichov** [comment]
I've moved this issue to the bsdata repo as it's a site-wide issue.

See: https://github.com/BSData/bsdata/issues/29
