### ISSUE TITLE
Bug report: Space Marines - Codex.catz 

### ISSUE THREAD

**Issue by Sentenal** [BSData/wh40k-7th-edition#2600]
Terminator Captains can upgrade to Cataphractii Terminator Armour for free.  Currently BS is saying it costs 20 points to upgrade your Terminator Captain into Cataphractii armour.

It also allows you to make your Cataphractii Terminator Armour Captain into a Chapter Master, which is illegal.

**Comment by DrTobogganMD** [comment]
100% right. Thanks for the catch! This is a complete re-write so little things like this get by.  No clue why I put 20pts for the cata armor.

Fixed in the next push (30~m or so away)
