### ISSUE TITLE
Bug report: Chaos Space Marines - Codex.cat

### ISSUE THREAD

**Issue by Tordokdur** [BSData/wh40k-7th-edition#2612]
**File:** Chaos Space Marines - Codex.catz

**BattleScribe version:** 2.00.01

**Platform:** Windows

**Dropbox:** No

**Description:** CSM Dataslate entries are not available if "Show Dataslate entries" is selected. Appears in Allied Detachment and CAD. (Be'lakor and others are not shown, same with Forgeworld)

**Comment by rypake** [comment]
I'm having a similar issue on the android phone. On the previous version of Battlescribe, forge world options for vanilla csm and the different supplements were showing just fine. But with the new version, and even after deleting and redownloading the new data files, the forge world options are not showing up no matter what I try. I've tried with vanilla csm in a CAD formation and in other formations.
