### ISSUE TITLE
Genestealer Cults errors out when creating formation rosters

### ISSUE THREAD

**Issue by ResidentSteve** [BSData/wh40k-7th-edition#2613]
Also errors out when trying to create cult insurrection.

Either quits to roster creation screen or crashes battlescribe.

**Comment by GenWilhelm** [comment]
What version of BattleScribe are you using, and on which platform?

**Comment by ResidentSteve** [comment]
2.00.04 on Android

**Comment by GenWilhelm** [comment]
Okay, I've just tested and it's working on my end. Is it when you're creating the roster or adding specific selections?

**Comment by ResidentSteve** [comment]
At Roster creation. Attempts to create then dumps back to roster create after awhile

**Comment by GenWilhelm** [comment]
I've just had a play around and it crashes for me if I'm running the BattleScribe app in "Low memory mode". Is this setting enabled for you?

**Comment by ResidentSteve** [comment]
I do indeed. Just tried in normal mode and it loads fine!

**Comment by GenWilhelm** [comment]
Okay, thanks for the help diagnosing that. I'll take a deeper look into it when I get some time this evening.

**Comment by GenWilhelm** [comment]
This issue has been resolved by the release of 2.00.07.
