### ISSUE TITLE
Officio Assassinorum detachment

### ISSUE THREAD

**Issue by Marina42** [BSData/wh40k-7th-edition#2621]
No unit can be selected in the detachment.

**Comment by francoisbeaulieu** [comment]
I can reproduce this on iOS, but only if the OA detachment is added to an existing roster. If I create a new roster for it, I can select units just fine.

## 

François Beaulieu (iPhone)
(514) 667-0691 x2061

**Comment by Thairne** [comment]
Is a "problem" with BS.
If you save the roster and reload it, everything will be fine.

**Comment by DrTobogganMD** [comment]
Fixed with latest BS build. IOS will still be broken until new IOS build is pushed.
