### ISSUE TITLE
Eldar Craftworlds - Warlock Stats not showing when running Seer Council

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#2625]
**File:** Eldar Craftworlds - Codex (2015).catz

**BattleScribe version:** 2.00.01

**Platform:** Windows

**Dropbox:** No

**Description:** When running the Seer Council the statline for Warlock (or Warlock Skyrunner) doesn't show up in the roster view, only the Farseer stats show up.  If the Warlock Council is selected separately the Warlock stats show up with no issues.  Thanks!

**Comment by FarseerVeraenthis** [comment]
I tried this on Version 2.00.04 and couldn't replicate the problem. However, I did notice there were some errors with how the validation was built, so I made some updates and now - with a software update and a data purge - this problem should be fixed.
