### ISSUE TITLE
Orks: Big mek shokk attack gun

### ISSUE THREAD

**Issue by mifth** [BSData/wh40k-7th-edition#2635]
Hi,
 Big Mek has shokk attack gun roll result (2d6). Could you add it when we print the roster, please?

Roll Result
1,1 Boom! No shot is fired. Remove the Mek as a casualty.
2,2 Oops! The opponent may choose the target of the shokk attack gun this turn,
and place the Large Blast marker. The target can be a unit on the same side as the
Mek.
3,3 Gah! Resolve the shot upon the nearest unit to the target that is not locked in
combat, be it friend or foe.
4,4 Sploosh! Resolve the attack upon the target, but use the small blast marker. Any
hits are resolved at Strength 6 AP6.
5,5 Zoink! No shot is fired. Immediately place the Mek in base contact with the
closest model or point on the target unit, and treat them as being locked in combat.
5,6 Bzzap! Only the model under the template hole is hit, but the shot is Strength
10.
6,6 Krakoom! When resolving this shot, the shokk attack gun has the Vortex
special rule.

**Comment by tag8833** [comment]
Absolutely.  I'll get it done next week.  I'm also adding full text for a number of rules.

**Comment by mifth** [comment]
Thanks a lot beforehand.

**Comment by tag8833** [comment]
Data file updated, ready to release.
