### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by FarseerVeraenthis** [BSData/wh40k-7th-edition#2638]
Hi, I'd like to help maintain the WH40k Battlescribe Data Files.

I mostly play Eldar, but I'm starting a Deathwatch army and I've noticed a couple of minor issues with the data files since the update of Battlescribe.

I love Battlescribe, I think it's a great program and very helpful, so I'd like to continue using it. If that means fixing things myself then so be it, I'm sure I have the computer knowledge to edit things properly without making a mess of things!!

Cheers,
Simon Porter

**Comment by amis92** [comment]
Hello, @FarseerVeraenthis. Please accept the invitation in the email or on the [BSData organization webpage](https://github.com/BSData). Welcome aboard!

Don't forget to read through [Wiki pages](https://github.com/BSData/bsdata/wiki), there are some useful guides, especially [Developer Guide](https://github.com/BSData/bsdata/wiki/Developer-Guide).

Also join our team in Gitter chat room (GitHub login): [![Join the chat at https://gitter.im/BSData/wh40k](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/BSData/wh40k?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

Cheers!
