### ISSUE TITLE
Orks: Ghazghkull Thraka invul 2+

### ISSUE THREAD

**Issue by mifth** [BSData/wh40k-7th-edition#2649]
Hi,

Ghazghkull has invul 2+ during waagh. Could you add it to his statistics, please?

Text from codex:
Prophet of Gork and Mork: If Ghazghkull is your Warlord, he gains a 2+ Invulnerable save on any turn he calls a Waaagh! This invulnerable save lasts until the start of his next
turn. In addition, Ghazghkull and all other models in his unit that are equipped with mega
armour can Run on a turn he calls a Waaagh! despite having the Slow and Purposeful special
rule (which is conferred by wearing mega armour).

**Comment by tag8833** [comment]
I will add the text to the rule.  I don't really want to change his profile because it only happens on the turn he declares a WAAAGH

**Comment by mifth** [comment]
Thanks a lot. It happens also only if he is a warlord.

**Comment by tag8833** [comment]
Data file updated, ready to release.
