### ISSUE TITLE
Missing Options

### ISSUE THREAD

**Issue by ThunderCrash42** [BSData/wh40k-7th-edition#2650]
Sternguard squads don't have a option for heavy flamers and assault squads have the wrong wargear listed

**Comment by DrTobogganMD** [comment]
Sternguard has the option for a heavy/special troop who has access to a heavy flamer. Edit: I see it's hidden, fixing - I had an and/or swapped. Fixed in next push.

What do you mean about assault squads.

**Comment by ThunderCrash42** [comment]
assault squads are chainsword/bolt pistol but they're shown as Boltgun/bolt pistol
