### ISSUE TITLE
Only 2 forces can be added

### ISSUE THREAD

**Issue by AngelofGlory** [BSData/wh40k-7th-edition#2651]
Hi,
I'm not sure if this is a problem of BS2 or the datafiles but I can only add 2 forces. When I try to add a third force BS does nothing for a while. Then sometimes it crashes sometimes the 3. force is shown when I click "Edit Forces" in the popup but not in the "Roster Selections" view. I'm also not able to delete the 3. force. I get the popup asking if I really want since all data in this force will be deleted but when I confirm with "yes" nothing happens. The force is still shown in the popup under "Forces"

Sometimes also the "Cancel" Button disappears when trying to add a force.

**Battlescribe:** v2.00.02
**System:** Windows 10
**Dropbox:** Yes

I have made some screenshots at least showing the effect that the cancel button disappeared.
![picture 1](https://cloud.githubusercontent.com/assets/23257335/20001731/cb2bba1e-a27d-11e6-9be2-adea0fe9bfa5.jpg)
![picture 2](https://cloud.githubusercontent.com/assets/23257335/20001733/cb2bd24c-a27d-11e6-8855-eaac38c1b7d2.jpg)
![picture 3](https://cloud.githubusercontent.com/assets/23257335/20001732/cb2bc9aa-a27d-11e6-95ca-08690d5ecd81.jpg)

**Comment by DrTobogganMD** [comment]
I cannot replicate using the latest install.  Can you please re-install Battlescribe from the website and download fresh data manually from this repo and try to replicate?

**Comment by AngelofGlory** [comment]
Hi Kohato,

I already did before I posted.
This is the current link for BS from BS page: http://battlescribe.net/files/BattleScribe_2.00.02_Setup.exe  (downloaded today morning German time). I saw a lot of People having v2.00.06 but when I go to download Windows Version I only get v2.00.02.
This is the link from where I get my data: http://battlescribe.appspot.com/repos/wh40k/index.bsi (downloaded today morning German time), data files Show me "Warhammer 40,000 7th Edition v4" when I create a new roster.

**Comment by DrTobogganMD** [comment]
There was a newer version generated when you open the roster editor - it prompts to auto update.

**Comment by AngelofGlory** [comment]
![picture4](https://cloud.githubusercontent.com/assets/23257335/20017298/4475396e-a2c3-11e6-85d7-541bf24c1741.jpg)
![picture5](https://cloud.githubusercontent.com/assets/23257335/20017299/44771eb4-a2c3-11e6-8dbc-a5ea5ba470a1.jpg)

My Settings are "use Standard update channel" -> there it comes "no update found". Shell I use Alpha or beta channel?

**Comment by DrTobogganMD** [comment]
This should be fixed with our latest push.
