### ISSUE TITLE
Tau Piranha formation error

### ISSUE THREAD

**Issue by thejughead** [BSData/wh40k-7th-edition#2656]
Defaults to 2 formation leader units.

**Comment by efalsken** [comment]
I looked at this and can find no cause for it. Maybe @Kohato can figure it out. I did clarify the listing in my current PR.

**Comment by Gnofry** [comment]
It's really weird, but the issue goes away if you remove the constraint on 1-5 in parent from the TX4 Piranha shared entry and add one to the TX4 Piranhas shared entry underneath the Members selection group.
