### ISSUE TITLE
Space Marine Gladius and Chapter Tactics issues

### ISSUE THREAD

**Issue by AveryKess** [BSData/wh40k-7th-edition#2658]
SM Gladius Strike Force showing incorrect requirements. 
Does not give transports for free if properly built Gladius.  
Carcharodons chapter tactics does not add the ability to buy ccws for tac squads (BSv1 did)

**Comment by DrTobogganMD** [comment]
Gladius gives free transport if using the "Battle Company" core choice.

I'll take a look at Carchardons.

**Comment by AveryKess** [comment]
![gladuisissue](https://cloud.githubusercontent.com/assets/11638573/20012447/3c0ae42c-a27d-11e6-8053-590f23036d83.jpg)

I can't seem to get the Gladius to work

**Comment by alphalas** [comment]
take one Battle Company as opposed to the double demi.

**Comment by AveryKess** [comment]
One Battle Company does not appear to be an option.  Also, if this is a Gladius Strike Force formation, The Core and Auxiliary options are wrong.

**Comment by alphalas** [comment]
Purge data and reload.
![img_0078](https://cloud.githubusercontent.com/assets/15703066/20013966/8447ce2c-a28b-11e6-8032-153677002498.PNG)

**Comment by AveryKess** [comment]
ok, the Space Marine: Codex v7 actually loads (v5 wasn't loading)

**Comment by francoisbeaulieu** [comment]
As of codex v9, choosing ultramarines chapter tactics doesn't allow you to swap the captain for Sicarius or for a company champion, or the chaplain for Cassius. It does allow captain Centos, which I don't think is valid.

**Comment by DrTobogganMD** [comment]
Centos is an odd bird. He's, per GW, a wargear upgrade to any captain in the army.  As he's a wargear upgrade and not a model replacement, he would still be valid for gladius.

I agree I seem to have omitted sicarius or cassius somehow though - fixing.

**Comment by francoisbeaulieu** [comment]
While you're at it, the sergeants for assault and devastator squads are throwing errors for not having their default weapons auto-selected. They need to be manually selected and appear to be the only ones that do that.

**Comment by AveryKess** [comment]
Carchardons tactics still not adding ability to purchase close combat weapons on tactical squads in Space Marines: Codex v9

**Comment by DrTobogganMD** [comment]
This has been pushed out to appspot. You may need to purge and redownload data.
