### ISSUE TITLE
Bug Report and possible improvements: Codex Space Wolves 2014

### ISSUE THREAD

**Issue by Viper666-Qc** [BSData/wh40k-7th-edition#266]
1. "(NO Category)" option should be deleted as there's already a "NO Force Org Slot" available and it's empty anyway
2. HQ options: Their weapon load out options can be accessed only from there Armour option. Maybe it should be easier and more clear to separate both the armour options and the weapons options. Also, the weapon options should only be check marks instead of "How many?"...I don't see anybody giving twice the same weapon to a character except for specialist weapons.
3. Troops: Could the Chainsword option be placed at the same place as the bolt pistol and bolter options?

**Comment by ghost** [comment]
1. The 'No Category' option is displayed by the program; there's nothing I can do about that.
2. The different armour types have 3 or 4 different sets of the 22 weapons options & the two sets of relics. Having those listed alongside the armour choices & other gear, all tied together with additional modifiers determining what can be taken with each suit, on top of the modifiers to reduce the count for paired weapons and the ones controlling the relic goups... You're talking about roughly 58-62 items in one menu on the Wolf Lord; plus the end-user then has to read & understand the warning messages that'd pop up when they select an invalid combo.
   As it stands, there's no confusion about what you can select, and all the legal combinations are allowed.
3. If you put the Chainswords in the same place as the other weapons, then the squad appears as 5-10 separate models on the roster editor - you'd have to drill into each one to equip them individually, multiplying the user input by the same amount just to set up a single squad. (Look at the TWC for an example of this - I didn't like it there either, but that unit's weapon options made it the most easy-to-understand solution). I don't know precisely what effect this would have on the Grey Hunter's special weapons, but it would probably take a boatload of modifiers to make work. There are approx. 78 different weapon combinations!

Sorry if this reply was a bit lengthy :) There's been a lot of feedback on previous files that's gotten incorporated into this, plus the practicalities of having to make the thing work & be maintainable.

**Comment by amis92** [comment]
1. The 'No category' showing up is because there is a hidden Champions of Fenris Option sitting there. Which I don't have any idea what for it is.
2. It is possible to unnest weapons and hide/show them depending on which armour is chosen.
3. I won't comment, I have no idea.

**Comment by Kangodo** [comment]
1. There is a hidden entry there that shows itself when you make an Apocalypse-list.
   There is also a difference between 'no category' and 'no force org'.
   In BA - for example - I've put an option there to show/hide FW-models, so the slot itself is quite useful since you can put options there that always need to be shown on top.
2. Khambatta is right.
3. He is right again! I've had the same issue with GK's and Stormbolters so I added an entry called 'Each model has a Storm Bolter' to the unit.

**Comment by Xianator** [comment]
Two plasma pistols on a character is a possible option, so having a single weapon of each type being available is incorrectly limiting.

**Comment by Kangodo** [comment]
@khambatta 
On point 3 I've found something interesting which I didn't know.
You can add a Chainsword and make it collective, then it won't give you separate models in the editor!
Amis is working on GK's now, and if he is done I will see if I could do that with the Storm Bolters.

**Comment by ghost** [comment]
That would add a Chainsword to every Grey Hunter in the squad.

**Comment by Kangodo** [comment]
That should tell you how much I understand from Space Wolves :)
Well, at least that bit of information is useful for my future work!

**Comment by evilmerlin** [comment]
The cost of a Storm Shield for the Wolf Guard Battle Leader is incorrect. It should be 25pts rather than the current 15pts.

**Comment by ghost** [comment]
The Wolf Guard Battle Leaders can also take Melee weapons, which includes the Storm Shield at 15pts for power armour & 0pts for terminator armour. Duplicate of #306.

**Comment by amis92** [comment]
Ok I think this issue is over-extended in topic. The original post was answered and decided to not be acted upon. Closing.
