### ISSUE TITLE
Khorne Daemonkin formation/options/points value missing.

### ISSUE THREAD

**Issue by MFenris** [BSData/wh40k-7th-edition#2661]
I'm not sure if anyone is still updating the "old" battlescribe, but this might help both versions.

in khorne daemonkin, under formations, the "war engine" formation is missing. I can only take it as part of a blood host detachment.

When running the "fist of khorne" formation, the bezerker champion seems to get free power weapons, when they should be 15 pts a pop.

When selecting power weapon options for any champion or character who can take them, the power lance is also missing. Its there in codex: chaos marines datafiles, just not khorne daemonkin.

Also, I've noticed some forge world units being options, such as the kytan, blood slaughterers, and decimator, but it lacks other options, like the brass scorpion some dreadnaughts, and some named khorne daemons.
I understand forge world options aren't exactly explicit in how you can take them in khorne daemonkin, but forge world has released emails saying they can take any unit with an option of "mark of khorne" "daemon of khorne" "daemon knight of khorne" or "dedication of khorne" in some way. And it made me wonder if the files could be updated to change according to that, or if battlescribe only updated with hard published allowances. The most reasonable argument for updating these is that there exist blood oath formations that have allowances for many of these units, such as daemon lords and daemon engines.

Any feedback would be greatly appreciated.

**Comment by cartag** [comment]
1) War Engine isn't a formation, it's an Aux choice. Working as intended. 

2) This will be updated.

3) Will be updated as well.

4) Will be updated, but not how you want it to. FW units by default cannot be brought. The only models that RAW state can be brought in a KDK army outside of a formation are the Kytan, FW Knights, and Samus. There has been no official release stating others can be brought in a KDK army list. The ones that can be brought in the Blood Oath formations that are not listed above do not have BftBG either. They only are considered to have it for the purpose of Blood Tithe generation, and do not gain any benefits chosen when cashing them in.

**Comment by MFenris** [comment]
So, if the war engine "auxiliary" isn't a formation, then the "lords of slaughter" option shouldn't be selectable by  battlescribe either. Seeing as its a command option, and not a formation by your standards. 

This is actually an amusing thing, because other than the two data sheets for War engine and Lord of slaughter being absent from the book, there isn't really a difference between them and other formation options that exist.  Perhaps some clarification would be helpful as to why one gets in and the other doesn't, when there isn't much difference between the two?

As for  forge world options, in the data files for battlescribe currently, the blood slaughterer of Khorne and the decimator daemon engine already exist as elite and heavy support options for a CAD detachment. Is this an error, then? And the games workshop official facebook draft says to assume all models in a hellforged hunting pack have the bftbg rule. Is that not official enough to include the rule with the formation?

**Comment by cartag** [comment]
Lord of Slaughter isn't a formation either, but a Command choice for the Blood Host detachment. There isn't a data sheet for them, that's what makes them just a choice, not a formation. Formations have data sheets that specify they're a formation, what units have to be taken as part of it, and any special rule the formation gets. War Engine and Lord of Slaughter have neither of those things. Those aren't my standards, they are what the choices are, RAW. Formations have the following icon in their datasheet, specifying that they are a formation.

![image](https://cloud.githubusercontent.com/assets/4388344/20027113/982b6e68-a2d0-11e6-81b2-5af57f9c7154.png)

The Blood Slaughterers, Decimator, etc were listed in error, and have been removed. The official FAQ draft says to assume they have BftBG for the purposes of Tithe generation, but does not go so far as to say they gain the benefit as if they had BftBG special rule. 

![image](https://cloud.githubusercontent.com/assets/4388344/20027085/ebabdd58-a2cf-11e6-9011-46d67a16a719.png)

**Comment by cartag** [comment]
Removed as individual choices that is, they are still selectable in the HHP formation.

**Comment by MFenris** [comment]
Thanks for the quick and clear answers. Good to know you guys are on the ball about these things. Sorry if I seemed curt with you, (looking back at my reply I can see  it being read in negative tones) I was looking through my codex and brb and it wasn't 100% clear. Thanks again. Keep up the good work.

**Comment by cartag** [comment]
No problem, it's not anything I've not answered several times before :) GW doesn't make it as clear as they could with what is and is not a formation, so there's some confusion at times. Thanks for the catches with the issues! They've been updated, there should be a release soon (if there hasn't been already) that will push the changes through.

**Comment by MFenris** [comment]
Awesome, sorry I forgot to also mention..
When running the hellforged hunting pack, it gives an error message that I can't take the brass scorpion because it's hidden. Even when "show forge world" is selected.

I believe those are all the issues I've ever found with the kdk datafile. (The only other mistake I found was corrected in previous  updates with rhinos and combi weapon prices) thanks!

**Comment by cartag** [comment]
That will be corrected as well, I took out the "Show FW" display restriction, since it will only hide four things by default now.
