### ISSUE TITLE
Handling of Detachments vs Factions

### ISSUE THREAD

**Issue by Viper666-Qc** [BSData/wh40k-7th-edition#267]
It's getting pretty crowded in the Force Type as we find every possible detachments from every codice/dataslates/supplements.

Is their any way it could be improved?

I see the Parent Force section is always limited to "Roster". Could we use this for different 40k game system like Standard game, Apocalypse, Zone Mortalis, Planetstrike, Kill team and Spearhead. Using this section could allow to reduce the number of detachments available in the Force Type section.

ex:

Parent Force: Zone Mortalis
Force Type available: Attacker, defender, combattant

Parent Force: Planetstrike
Force Type : attacker, defender

Parent force : Standard Game
Force type: any standard game detachment available (excluding those mentioned above)

Also, could it be possible to choose the Catalogue "before" choosing the Force Type in a way that it would limit the number of detachment available?

ex:
Catalogue: Space Wolves codex 
Force Type available: CAD, Space wolves detachment, Company of the Great Wolf, Wolves Unleached, Allied detachment

Catalogue  Imperial Knight
Force Type: Imperial Knight Detachment

This last thing would be great because right now, for example, you can select a Inquisitorial Detachment with the Chaos Space Marine codex and once you fill an HQ slot with a CSM HQ, the detachment is valid.....

**Comment by Kangodo** [comment]
Unless I am wrong, that "issue" has more to do with Battlescribe then the data-files.
Questions like that can be directed to: http://battlescribe.uservoice.com/forums/55066-general

**Comment by Viper666-Qc** [comment]
Ok I'll try there Thx

**Comment by amis92** [comment]
It's been under discussion here: [BSData/bsdata#39](https://github.com/BSData/bsdata/issues/39).

The last four-five comments are mentioning allowing only specific Force Types to be chosen fo a given Catalogue.

It's coming, guys, but we have to wait. Patience is our friend.

Also, commenting there stating support for this idea may make @Jonskichov more sure it's good and needed badly. :)

**Comment by amis92** [comment]
@Viper666 _Roster_ is a root. Like, it defines that it's roster, and not a catalogue object. We can't state what kind of roster it is. So, no.

But your second idea is most probably going to happen, as stated above.
