### ISSUE TITLE
Elder Wraithseer Psychic powers incorrect.

### ISSUE THREAD

**Issue by Nick-Kinsella** [BSData/wh40k-7th-edition#2670]
The powers used in Battlescribe listed have been taken from Imperial Armour Apocalypse 2nd edition p59. 

This has since been superceded by an FAQ release from Forgeworld https://www.forgeworld.co.uk/resources/fw_site/fw_pdfs/Warhammer_40000/Psykers.pdf

It should now read as follows:

Foreboding (Warp Charge 1)
The Wraithseer invokes the terror of death upon the lesser species, 
clouding their minds with dread.
Foreboding is a nova power, except that it targets any one enemy unit 
within 18". The target unit must make an immediate Pinning test at -2 to 
their Leadership.

Enliven (Warp Charge 1)
The Wraithseer enlivens the Eldar spirit stones around him, bringing them 
fresh vigour and life.
Enliven is a blessing that targets a single friendly Wraithlord or 
Wraithguard squad within 12” of the Wraithseer. Whilst this power is in 
effect the target unit gains the Fleet special rule.

Deliverance (Warp Charge 1)
The fates are marshalled to protect the Wraithseer and its charges.
Deliverance is a blessing that targets a single friendly Wraithlord or 
Wraithguard within 6” of the Wraithseer (the Wraithseer may be chosen 
as the target of this power). Whilst this power is in effect the target unit 
gains the Feel No Pain (4+) special rule.

Thanks for all the work on this file. It's brilliant.

**Comment by Nick-Kinsella** [comment]
Correction. It's Imperial Armour Apocalypse 2nd edition (2015) p213 

Apologies for any confusion.

**Comment by efalsken** [comment]
Correct. The text which is there is current as of the latest IA Mymeara book (Dec 2015).
