### ISSUE TITLE
Bug Report: AM - Death Korps of Krieg Assault Brigade

### ISSUE THREAD

**Issue by ThomasEll** [BSData/wh40k-7th-edition#2671]
The following are incorrectly set to have a minimum value:

- Thunderbolt
- Lightning
- Griffon Heavy Mortar Carrier
- Hydra Flak Tank
- Avenger Strike Fighter
- Leman Russ Forward Command Tank
- Minotaur Artillery Tank
- Dominus
- Reaver Battle Titan
- Warhound Titan
- Praetor
- Warhound Titan (Duplicate?)
- Crassus
- Crassus (Duplicate?)
- Dominus
- Cypher
- Hellhound
- Imperial Navy Thunderbolt (DftS) 
- Imperial Navy Lightning (DftS)
- Death Rider Squadron

Default Infantry Platoon size is set to 15 guardsmen, however max is 9

Engineer Squad is in Troops as well as Elites (should only be in Elites)

Death from the Sky fliers marked as Fast Attack instead of Heavy Support

Leman Russ Executioner Plasma Cannon is marked as having Get's Hot (which it doesn't in the codex)

**Comment by alphalas** [comment]
the DFTS flyers are FA - hence why there's an entry for the DFTS flyers and the codex flyers.

closed by #2739
