### ISSUE TITLE
Imperial Knight War Convocation no options

### ISSUE THREAD

**Issue by SSSlippy** [BSData/wh40k-7th-edition#2676]
On mobile ADM war convocation knight has no knights to select. Also seems like allied and oathsworn have the same issue.

**Comment by Thairne** [comment]
The other detachments have been fixed, however I can see them just fine in the War Conv. Detachment.

**Comment by SSSlippy** [comment]
It seems to linked to the detachments and is why I mentioned it. Seems to be all fixed now. Thank you.
