### ISSUE TITLE
Imperial knights - missing from detachments

### ISSUE THREAD

**Issue by francoisbeaulieu** [BSData/wh40k-7th-edition#2677]
Battlescribe 2.0
Platform: iOS

I realize this is probably just because the catalogue hasn't yet been fully converted to 2.0, but or posterity:

1- No knights are selectable for Oathsworn and Household detachments.
2- All knights (including FW) are there for formations, but they all have a few errors. Specifically, (so far) they all come with 2 melee weapons preselected when only one slot is available, and the word "gauntlet" is misspelled.

**Comment by Thairne** [comment]
I've made a few corrections that should help.
I'm not sure I caught everything, so if you see something else let me now

**Comment by SSSlippy** [comment]
Household detachment does not have any unit options still.

**Comment by francoisbeaulieu** [comment]
Same here on iOS; codex v4 still shows no units for household or oathsworn detachments.

**Comment by Thairne** [comment]
That would most likely be since it's not released yet and fixed in v5.

**Comment by francoisbeaulieu** [comment]
Hi @Thairne,

Sorry, I had noticed the version number jumping from v2 to v4, so I assumed it had been released. Thanks for the work on this!

**Comment by Thairne** [comment]
Nah :)
First we gotta work on it, commit it to the master, draft a release to make it public AND wait for appspot to catch up on it. So usually it takes a bit till it arrives in the "outside" world ;)
