### ISSUE TITLE
Eldar Craftworlds - Guardian Battlehost doesn't get free weapons platform

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#2680]
**File:** Eldar Craftworlds - Codex (2015).catz

**BattleScribe version:** 2.00.02

**Platform:** Windows

**Dropbox:** No

**Description:** Guardian Battlehost: does not get "Our time of need"-bonus: free weapons platform

**Comment by FarseerVeraenthis** [comment]
They should do... I was looking at this last night, I have an update to finish so I'll work through it and go from there.

**Comment by FarseerVeraenthis** [comment]
This should be fixed on the next update of the data files
