### ISSUE TITLE
Assassins dataslate improper formation

### ISSUE THREAD

**Issue by katfude** [BSData/wh40k-7th-edition#269]
1st issue: Eversor assassin is spelled "Everson"

2nd issue (major): The .gst file needs a new detachment for this dataslate. Currently, this is marked as a "Fortification" detachment, but no options to add units appear if taken as such. I can only seem to get models to appear to be added to my list when taken as a combined arms detachment, which creates a myriad of list legality problems.

Recommended fix: add a Officio Assassinorum Detachment to the .gst file allowing for 1 Elite selection only. Set the .cat file to this new detachment.

**Comment by amis92** [comment]
I think the second is solved, just not released yet. Sync your master branch.

**Comment by katfude** [comment]
Thank you, you're correct. Went ahead and blasted that typo since it was so small.
