### ISSUE TITLE
CSM CAD requirement error

### ISSUE THREAD

**Issue by ZaLordDresden** [BSData/wh40k-7th-edition#2696]
Whenever I try to build a chaos space marine combined arms detachment since the new version of Scribe released, it tells me that I must have two Warhound Titan choices in the Lord of War section.

**Comment by cartag** [comment]
Purge your data files and redownload the files.

**Comment by ZaLordDresden** [comment]
I purged my data files and my roster, started completely fresh, and it made
no change. still has two entries in the exceptions, each saying I must have
a selection of Chaos Warhound Titan.

**Comment by cartag** [comment]
What is the version number of the CSM file? What platform are you running it on (iOS, Android, PC)?

**Comment by cartag** [comment]
The reason I ask is that this was an error with the old BS 1.15 files when trying to use them in BS2. Since the updated files have been copied over, this issue doesn't exist any more. So either you didn't delete the existing data files and redownload them, or you redownloaded the wrong ones.

**Comment by ZaLordDresden** [comment]
I'm running on Android 6.0.1

It's the CSM file within the 40k file updated Nov 5, 2016.

It says v2.

If this is the wrong one, could you do me a solid and point me toward the
newest file?

Thanks.

On Nov 7, 2016 11:51 PM, "cartag" notifications@github.com wrote:

The reason I ask is that this was an error with the old BS 1.15 files when
trying to use them in BS2. Since the updated files have been copied over,
this issue doesn't exist any more. So either you didn't delete the existing
data files and redownload them, or you redownloaded the wrong ones.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
https://github.com/BSData/wh40k/issues/2696#issuecomment-259045248, or mute
the thread

**Comment by cartag** [comment]
That shouldn't be possible. Below is the entire listing for the Warhound, and there are no minimum requirements on it. On your device what version of the file does it say you're running? 

![image](https://cloud.githubusercontent.com/assets/4388344/20087363/0ef5fc78-a535-11e6-98e8-5ee901a13f42.png)

**Comment by ZaLordDresden** [comment]
Inside the app, in the roster details, it says v206

**Comment by cartag** [comment]
That means you didn't purge your data.

**Comment by ZaLordDresden** [comment]
My apologies. I thought I had, but had forgotten about the option in the
menu.

Thanks for persisting through my fumbling.

-Edward
