### ISSUE TITLE
Bug Report - Space Wolf Codex

### ISSUE THREAD

**Issue by JonnyRuriki** [BSData/wh40k-7th-edition#2700]
When I create a Formation detachment, it says that I must have 1  or more selection of "Grimnars War Council, Wolf Guard Thunderstrike, Wolf Guard Void Claws, Arjac's Shieldbrothers, Kingsguard Stormforce, and Bretheren of the Fell-Handed, and Grimnar's War Council" even when I dont have any formation added to the list yet

**Comment by alphalas** [comment]
Duplicate of #2631
