### ISSUE TITLE
Bug Report - Imperial Knights formations

### ISSUE THREAD

**Issue by Sentenal** [BSData/wh40k-7th-edition#2707]
None of the Imperial Knight formations show up under the Force Organization screen.  There are other formations, just none for IK.  Error is showing on the mobile version, if that matters.

**Comment by Thairne** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/8590840/20104969/3d4002a4-a5d0-11e6-9ad0-984695cd3cf3.png)

They are there, at least on desktop. Some are erroneous as I just saw, but they are there.

**Comment by GenWilhelm** [comment]
I believe @Sentenal was referring to the 'Household' and 'Oathsworn' detachments that seem to have been omitted from the GST in the initial BS2 release.

**Comment by Thairne** [comment]
Well they got, as everything else, transferred into the .cat and are there for the taking.
