### ISSUE TITLE
Space marine gladius strike force captain options

### ISSUE THREAD

**Issue by Cancleout** [BSData/wh40k-7th-edition#2714]
the captain option in the gladius strike force throws out an error if you select the chapter master upgrade to the captain.
![1](https://cloud.githubusercontent.com/assets/10332712/20114646/af378c76-a5ba-11e6-95d5-60902d192dc2.png)
and it should not
![2](https://cloud.githubusercontent.com/assets/10332712/20114661/c0a3684a-a5ba-11e6-8acf-b65ca26436f6.png)

**Comment by DrTobogganMD** [comment]
The FAQs are not set in stone yet and are still Draft.  Once the Final version gets released - changes like this will be made.
