### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by raptor1770** [BSData/wh40k-7th-edition#2719]
The recent update seems to have broken many rules for my army Space Wolves. I would like to use my programming knowledge to help fix it.

**Comment by alphalas** [comment]
as soon as @amis92  approves you, be my guest - join us over on gitter and we can fill you in.

**Comment by amis92** [comment]
Hello, @raptor1770. Please accept the invitation in the email or on the [BSData organization webpage](https://github.com/BSData). Welcome aboard!

Don't forget to read through [Wiki pages](https://github.com/BSData/bsdata/wiki), there are some useful guides, especially [Developer Guide](https://github.com/BSData/bsdata/wiki/Developer-Guide).

Also join our team in Gitter chat room (GitHub login): [![Join the chat at https://gitter.im/BSData/wh40k](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/BSData/wh40k?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

Cheers!
