### ISSUE TITLE
(Bug) imperial knights relics & modifiers

### ISSUE THREAD

**Issue by Hasfodel** [BSData/wh40k-7th-edition#2728]
There is no possibility of taking relics for formations
And is it possible to add a modifier for the formations and warlords ?
Like +1 bs and ws for everyone in the "exalted court" formation and +2 for the boss

**Comment by Thairne** [comment]
Ah hell.. this is war convo all over again.
If only the instance of force modifier would work from shared entries...

Yes, it basically is possible. In reality however, a bug in Battlescribe makes that rather hard.
I don't think I want to clone every entry in the catalogue for that just to change a profile.
The printout will need to be corrected until I can do that efficiently in the file.

**Comment by Hasfodel** [comment]
For the modifiers it's not so important but I can't add relics and so I don't have the correct point value for my roster, 
Can you do something for this ?

**Comment by francoisbeaulieu** [comment]
@Thairne, you might want to take that up with @Jonskichov. Sounds like a good idea for improvement.

**Comment by Thairne** [comment]
Yeah, I've added the relics. I cannot however hide them where not applicable - like the oathsworn detachment.

@francoisbeaulieu jon is aware of the issue. I'm waiting for a fix, since this would greatly clean up the War Convocation. Setting points to 0 depending on force would be a great help.

**Comment by francoisbeaulieu** [comment]
@Thairne, I realize you can't hide them, but can you make it throw a validation error when it's not a legal choice?

**Comment by Thairne** [comment]
nope, I simply cannot make it dependent on force because it just does not work.
I have no way to check for that unless I copy the entire thing, use it specifically with relics and then use that entry in formations and the household detachment.
Which is a really cumbersome way of doing it.

**Comment by Thairne** [comment]
The bug has been fixed in BS.
Heirlooms now will hide in War Convo and oathsword detachments.
I'll have to read through the knight dex and find all those different modifiers, but they CAN be done now!

**Comment by Hasfodel** [comment]
Woha perfect 👌🏻

**Comment by Flashpoint-** [comment]
Hurrah Hurray! Thank you

**Comment by Thairne** [comment]
Resolved this morning.

**Comment by Hasfodel** [comment]
Resolved in v2004 ?
Because in v2003 relics don't appear on FW knights (in the exalted court at least)

**Comment by Thairne** [comment]
Jup, 2004. I'll have to rework the FW Knights tomorrow morning (so it might be 2005 for FW Knights), I just had time to go through the standard Knights and make the Baron and the Exalted Court actually require the stuff that it does. Stressful day at work, But it's now just copy/pasting stuff over to them.
Profiles will also be modified for Lord Barons and High Kings/Princeps accordingly.
