### ISSUE TITLE
Space Wolves - Grey Hunter Weapon Selection Issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#2729]
**File:** Space Wolves

**BattleScribe version:** 2.00.07

**Platform:** Android

**Dropbox:** No

**Description:** There seems to be an issue with the weapon selection for the grey hunter squad (I'm unsure of any other squads affected such as bloodclaws) 
The error button lights up stating that there are too many bolt pistol / bolter selected when in fact the correct amount is selected as per the rules in the codex.

**Comment by raptor1770** [comment]
I fixed the Grey Hunter squad. Im going to work on Blood Claws next.

**Comment by Nerosolja** [comment]
Not fixed

**Comment by amis92** [comment]
This was already released so @raptor1770 can you re-check?
