### ISSUE TITLE
Harlequin Masque Detachment requirements 

### ISSUE THREAD

**Issue by hieronymouse** [BSData/wh40k-7th-edition#2743]
0-2 Fast Attack slots only allows for 1 Starweaver to be taken. Should be 2 Starweavers.

**Comment by hieronymouse** [comment]
More specifically, the Masque detachment allows for 0-2 Fast Attack slots, which may be filled by Starweavers or Skyweavers.

Selecting 2 Starweavers currently gives a "Fast Attack has 1 too many selections of Starweaver (maximum 1)" error.

**Comment by Marina42** [comment]
Solved. 

But the Detachment requires exactly 2 Fast Attack slots, not 0-2.

**Comment by hieronymouse** [comment]
Whoops, yes 2 FA mandatory. Thanks!
