### ISSUE TITLE
Bug Report: Space Marines

### ISSUE THREAD

**Issue by Gnofry** [BSData/wh40k-7th-edition#2746]
As of C:SM 2004 Pedro Kantor is incorrectly listed under Imperial Fists chapter tactics (as in he appears only when IF is selected). He is actually a Crimson Fist model and should appear under those chapter tactics.

**Comment by Gnofry** [comment]
Completely incorrect, although it is very strange that Crimson Fists has a chapter tactic in the Data File with them not having Chapter Tactics in the Codex.

**Comment by DrTobogganMD** [comment]
As stated on Page 82 of AoD, BT and CF have their own Warlord Traits and are not allowed to roll on the IF trait table.  This is segregated in the CAT file by giving them their own Chapter Tactics selection (whose actual bonus rules mirror IF).  So while they don't have separate Chapter Tactics, I added the choice in there to keep unity in the method of hiding Warlord Traits and other chapter specific things.
