### ISSUE TITLE
Space Marine Ironclad dreadnought bug

### ISSUE THREAD

**Issue by rsochia** [BSData/wh40k-7th-edition#2754]
Left hand choices:
Powerfist w/built-in heavy flamer shows the storm bolter in the printout
Powerfist w/built-in storm bolter shows the heavy flamer in the printout

Right hand choices:
chainfist does not show any choices for built in weapons. chainfist can have built-in melta gun or built-in heavy flamer

**Comment by rsochia** [comment]
just a note I am able to fix bugs like this that I have found on my local copy I just don't know how to go about submitting the bug fixed file. If you even would want me to.

**Comment by DrTobogganMD** [comment]
Fixed the mixed profiles - but the profile does not state the chainfist has any built in option. The Chainfist bit itself has no weapon on it aside from the chainfist.

http://megabitzshop.com/bilder/produkte/gross/Warhammer-40k-Bitz-Space-Marines-Ironclad-Cybot-Kettenfaust_b3.jpg

**Comment by rsochia** [comment]
The model build instructions give you the choice of the melta or heavy flamer. and here the model is pictured with the chainfist and the melta directly from games workshop website.

https://www.games-workshop.com/resources/catalog/product/600x620/99120101076_SpaceMarineIroncladDreadnoughtNEW05.jpg

**Comment by rsochia** [comment]
and if i use the same logic you used and reference the same bits website you did then the seismic hammer should not have weapons either.
http://megabitzshop.com/bilder/produkte/mini/Warhammer-40k-Bitz-Space-Marines-Ironclad-Cybot-Seismischer-Hammer_b3.jpg

but it does. the codex specifically states the chain fist just replaces the seismic hammer not the weapon as well.

**Comment by DrTobogganMD** [comment]
Fair enough! I'll get it changed.

**Comment by rsochia** [comment]
Thank you. And like I said before I have done enough programing in the past and have played with the data file creator enough to understand the layout you have in the data files to make bug fixes like this on my own. But I do not know how to upload those fixes here.

**Comment by rsochia** [comment]
The chain fist w/heavy flamer does not show the chain fist or heavy flamer weapon profiles in the roster print out. All the other weapon options show the weapon profiles correctly.
