### ISSUE TITLE
Space Marines - White Scars

### ISSUE THREAD

**Issue by radionausea** [BSData/wh40k-7th-edition#2758]
Not able to upgrade the captain to Kor'sarro Khan in the Gladius Strike Force, battle company formation. (Chapters tactics have been selected)

**Comment by DrTobogganMD** [comment]
In what choice are you referring to. The Battle Demi Company or the Strike Force Command?  If you mean the Battle Company (the free transport option), then he is not listed because he is not a valid choice.  A Battle company is formed when the two demi-companies contain a Captain and a Chaplain.

**Comment by radionausea** [comment]
It was the battle company (free transport) formation, yes. 

I thought that he is a valid choice as he's a captain, specifically captain of the third company.

**Comment by DrTobogganMD** [comment]
He is a valid option for a single Demi Company or a Strike Force Command or Reclusiam Command Squad. But per the Company Support rule (shown here), a Battle Company is only formed when the demi companies have a Captain and a Chaplain.

The subtext for including Khan (and the others), indicates they replace the captain/chaplain.

![image](https://cloud.githubusercontent.com/assets/16939161/20245962/3e5bd19a-a972-11e6-80a2-cc1885d178c4.png)

**Comment by francoisbeaulieu** [comment]
That's a pretty strict reading of that rule. After all, is chaplain Cassius not "a chaplain"? Is Kor'sarro Khan not "a captain"? I always read that as you need one of each type...

**Comment by DrTobogganMD** [comment]
The rule is worded using proper names for the two units, which would indicate the specific Captain and Chaplain, rather than a generic captain and chaplain.  We've always tried to be RAW when issues like this come up.  I've posed the question to GW, as they're pretty responsive these days.

**Comment by alphalas** [comment]
The official replacement options 
- Jon[K]

**Comment by radionausea** [comment]
Khan has been valid as an option in the Battle Company at tournaments.  He was a valid option in the battlescribe 1 data as well.  I've yet to encounter anyone who has read this as strictly as you...

**Comment by DrTobogganMD** [comment]
Yep, I'll get it changed here today or tomorrow.

**Comment by radionausea** [comment]
Any joy with this?

**Comment by DrTobogganMD** [comment]
Work has been a bitch. I'm working on bugs today though - pretty much going down the list
