### ISSUE TITLE
Eldar Craftworld Warhost not showing Forgeworld Formations

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#2759]
**File:** Eldar Craftworlds - Codex (2015).catz

**BattleScribe version:** 2.00.08

**Platform:** Android

**Dropbox:** No

**Description:** Eldar Craftworld Warhost does not have option for using Forgeworld formations.

**Comment by FarseerVeraenthis** [comment]
I know what the problem is here!! I imagine they're not linked to the correct "Core", "Command" or "Auxiliary" choice to show up - the same as before when nothing showed up for the Craftworld warhost...
I'll look into it :smile:

**Comment by FarseerVeraenthis** [comment]
Right, I got them to show, but it's not ready because I need to hide them unless "show Forgeworld" is selected..
Further tidying to do 😄

**Comment by cartag** [comment]
Should the FW formations be listed in it? I mean, should they be Aux/Core/Command choices? Not all formations will fit into their decurion.

**Comment by DrTobogganMD** [comment]
Does the new Mymera modify the warhost? If not, then FW formations should not be allowed in.

**Comment by efalsken** [comment]
I'll be able to fix this tomorrow.

**Comment by FarseerVeraenthis** [comment]
@efalsken do you wanna take this over then...?

**Comment by amis92** [comment]
Do we really need show/hide forgeworld in Eldar? I mean, they gain a few units but it's not like it's overwhelming...

**Comment by FarseerVeraenthis** [comment]
There are quite a few additional formations from Mymeara and the Craftworld Warhost looked rather untidy last night, hence why I didn't upload it...
There is show/hide in the Dark Eldar list already...

**Comment by amis92** [comment]
And that I too have no idea what for. I guess guys just went a little too crazy after gaining that Hidden modifier. :<
