### ISSUE TITLE
Eldar Craftworlds - Dark Reaper upgrade calculation issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#2761]
**File:** Eldar Craftworlds - Codex (2015).catz

**BattleScribe version:** 2.00.05

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** When selecting a unit of Dark Reapers with Exarch and upgrading the unit to add starshot missiles in a combined arms detachment BattleScribe counts the exarch as a model even if you do not select a reaper missile launcher for the exarch.

For example 3 dark reapers upgraded with starshot missiles with exarch with Tempest launcher should only charge 24pts not 32pts

The calculation is correct in the Aspect Host Formation just not in the CAD

**Comment by FarseerVeraenthis** [comment]
I'll have a look at this when I look at the Forgeworld Detachment issue.
