### ISSUE TITLE
Bug Report - Space Marines - Chapter-specific detachments

### ISSUE THREAD

**Issue by francoisbeaulieu** [BSData/wh40k-7th-edition#2762]
Chapter-specific detachments, like the Imperial Fists' Sternhammer Strike Force, currently allow any chapter tactics and chapter-specific characters to be selected.

You might want to restrict the chapter tactics to the specific chapter and restrict the characters usable in the locally redefined formations like the Strike Force Command.

**Comment by francoisbeaulieu** [comment]
Also, the Sterhammer currently requires at least 2 aux choices with a single core, while the rules indicate 1-10 per core. I have not checked the others yet...

**Comment by francoisbeaulieu** [comment]
Command choices also not properly limited per core in Sternhammer.

**Comment by DrTobogganMD** [comment]
Yep - this was bumped by 1 in the conditionals - fixing.

As for restricting tactics to the detachments, they should be hidden correctly if you choose a tactics choice - which is required in the detachments.
