### ISSUE TITLE
Space Marines - Relic Selection Issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#2767]
**File:** Space Marines - Codex (2015).catz

**BattleScribe version:** 2.00.08

**Platform:** Android

**Dropbox:** No

**Description:** Relics are divided into ranged and melee, and divided between the arms accordingly. Eg. Shooting relics replace shooting weapons, melee relics replace melee weapons. This disallows a storm shield or power fist to be used with melee relics, or dual pistols to be used. These are all legal combinations of weapons, but they aren't able to be used in the new format you are using for the relics.

**Comment by FarseerVeraenthis** [comment]
This is not a problem in the most recent file, you can select both ranged and melee weapons for either hand and a Storm Shield is counted as Wargear. 
Therefore you can have a Storm Shield with a melee relic or dual pistols.
