### ISSUE TITLE
Space Marines - Named Characters & Relic Selection

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#2768]
**File:** Space Marines - Codex (2015).catz

**BattleScribe version:** 2.00.08

**Platform:** Android

**Dropbox:** No

**Description:** Crimson Fists do not have access to Imperial Fists relics, or to Pedro Kantor.

**Comment by DrTobogganMD** [comment]
So Pedro is an odd bird. He is listed with IF chapter tactics in the codex. This means that he cannot be taken in a Crimson Fists detachment.  I realize this is ass backwards as he is the CF chapter master.  

![image](https://cloud.githubusercontent.com/assets/16939161/20283419/9e2608b8-aa7e-11e6-9360-042495327d4e.png)

As for Relics - Angels of death states that only units in Imperial Fists detachments may take IF relics.  Successor Chapters count as coming from their parent in terms of rules only - as shown here in the SM Codex: 

![image](https://cloud.githubusercontent.com/assets/16939161/20283523/f9f996a0-aa7e-11e6-8819-9a92f910eab2.png)

This may be harsh RAW - but it is still fairly clear RAW.

**Comment by francoisbeaulieu** [comment]
But there are no crimson fists chapter tactics defined in the codex. Wouldn't the rule you quoted mean that he is a crimson fists but draws on the chapter tactics of his parent chapter? 

## 

François Beaulieu (iPhone)
(514) 667-0691 x2061

**Comment by alphalas** [comment]
Nor in Angels of Death - CF and BT only get warlord traits, everything else is still IF

**Comment by DrTobogganMD** [comment]
CF draw on the Chapter Tactics rules of the parent chapter. Not the restrictions.

Pedro is not listed in any source as having Crimson Fists tactics. He is 100% Imperial Fists according to printed rules.  The question then becomes, can successor chapters take parent chapter relics and can successor chapter tactics units mix with parent chapter tactics units.  In both cases, the answer would be no according to the printed rules.

**Comment by francoisbeaulieu** [comment]
I don't know about the relics, but according to the codex, there is no such thing as a crimson fists detachment, or chapter tactics (crimson fists). It was made up for Battlescribe and is just a copy of the imperial fists chapter tactics. Check with GW; this can't be what was intended for Pedro. By all accounts, when the crimson fists chapter tactics were added to BS, Pedro should've had his chapter tactics changed to match.

**Comment by DrTobogganMD** [comment]
What is intended and what is are two different things.  RAW, Pedro is IF and is IF Chapter Tactics, therefore is not allowed in a detachment with models pulled from the Crimson Fists chapter tactics.  Should this have been changed in Angels of Death? Probably.

RAW, Pedro can only be taken in detachments with other Imperial Fist models.
RAW, IF relics can only be taken by models taken in a detachment with Imperial Fist chapter tactics.

If you can find any instance of GW Print or response that Crimson Fist Chapter Tactics (and Black Templar by association) are allowed to take IF relics, then I can change that. Same with pedro.  As it stands no detachment can have units chosen from multiple chapters. That is clear as day in the SM Codex.

**Comment by alphalas** [comment]
@kohato, I'm looking at Angels of Death - there is no Crimson Fists Chapter tactics - warlord traits yes, but they are still IF - so unless I'm missing something this whole argument is moot. Of the two, only BT actually have chapter tactics other then IF.
- Jon[K]

**Comment by francoisbeaulieu** [comment]
Don't want to beat a dead horse here, but even RAW, the rules you quoted are clear: ALL Crimson Fists will have the Chapter Tactics (Imperial Fists) rule, and therefore can only be taken in Imperial Fists detachments. That means that Crimson Fists detachments essentially don't exist; they are all Imperial Fists detachments. That might suck from a flavour point of view, but RAW that means that CF and IF both have access to Pedro Kantor and to IF relics.

**Comment by DrTobogganMD** [comment]
Yep, I had a discussion with another user on FB regarding this. Came to the agreement that Successor chapters all have access to proginator relics, but NOT named characters as named characters are named in their title to a certain chapter.

So pedro would not be eligible to be in the same detachment as Lysander as they are from different chapters.

If we said pedro could be in an IF force as well as a CF force - that'd be the same as allowing Khan to lead a detachment of Mantis Warriors, which he cannot.

Bah, screw it - i'm convinced - I'll be opening up all named characters to their successors as well.

**Comment by francoisbeaulieu** [comment]
We might want to remove the "invalid" tag from this, since it's been decided this needs fixing. Wouldn't want this closed by mistake...

**Comment by FarseerVeraenthis** [comment]
So, that didn't quite go to plan...

**Comment by FarseerVeraenthis** [comment]
Looks like I also missed some successor chapters...
