### ISSUE TITLE
Space Marine Ironclad Dreadnought Bug

### ISSUE THREAD

**Issue by rsochia** [BSData/wh40k-7th-edition#2777]
The chain fist w/heavy flamer does not show the chain fist or heavy flamer weapon profiles in the roster print out. All the other weapon options show the weapon profiles correctly.

**Comment by DrTobogganMD** [comment]
Code and output are fine on my copy - what version SM file are you running

**Comment by rsochia** [comment]
it was version 2006.

**Comment by rsochia** [comment]
2007 works fine now
