### ISSUE TITLE
Dark Angels Veteran Sargeant Question

### ISSUE THREAD

**Issue by mschreiner86** [BSData/wh40k-7th-edition#2782]
I'm playing around with the Dark Angels right now to create a list and noticed something about the Veteran Sargent, it adds a new line to the roster view instead of replacing the Sargent (see attached image). The codex says "May upgrade the Space Marine Sargent to a Veteran Sargent". Is the additional line the intended behavior?

For reference, I'm using the latest that's on github (cloned repo locally) and not what's on appspot. Current head is 1821336.

![image](https://cloud.githubusercontent.com/assets/7573662/20316421/be0f7630-ab2f-11e6-8403-32ebb7ecd70a.png)

**Comment by Thairne** [comment]
Ah yes I see.
That is, again, a bug with BS 2.0.
It works that way... if you check a Vet Sarge it is supposed to hide the profile of the standard Sarge and show you the Vet Sarge profile. 
Currently, BS simply ignores the hiding of the old profile.
This affects many a thing and quite honstely slowly drives me mad.

**Comment by Thairne** [comment]
My bad. Not caused by the bug, but my own incompetence.

**Comment by mschreiner86** [comment]
Just synced and confirmed it's working now. Thanks @Thairne !

**Comment by Thairne** [comment]
You're welcome :)
