### ISSUE TITLE
Space Wolves - Blood Claw Weapon Issue & Great Wolf Detachment Problem

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#2783]
**File:** Space Wolves - Codex.catz

**BattleScribe version:** 2.00.09

**Platform:** Android

**Dropbox:** No

**Description:** I was trying to edit some of my Space Wolves lists on the new battlescribe, when I noticed that, first, my blood claws, no matter how I kitted them out, never had the right number of pistols and close combat weapons, either too much or not enough. I checked online to see if there was an update that said they could no longer hold chainswords and bolt pistols. I couldn't find any such change, much to my relief. I thought it was a hiccup with the data transfer from Old battlescribe, so I deleted all my old lists on the new battlescribe and tried to make a new one. I encountered the same problem. That wasn't the only issue. I put a company of the great wold detachment, and it doesn't display any Relics of the Great Wolf, upgrades that come with the formation. So I am completely unable to make a functioning list.

**Comment by Nerosolja** [comment]
There is still a problem with the pair of wolf claws selection also. It doesn't register as filling two weapons. It keeps asking to select on more weapon. The mentioned issue above is also for the grey hunters. The issue above and The pair of wolf claws issue keeps getting closed and claimed resolved but no resolution.

**Comment by alphalas** [comment]
1, purge data and redownload 

2, appspot might not have the newest release - clone from github to verify 
- Jon[K]

**Comment by GenWilhelm** [comment]
I can confirm:
- Relics of the Great Wolf do not appear correctly.
- Selecting a Pair of Wolf Claws for a Wolf Lord does not decrease the required number of weapon selections.

I cannot replicate the Blood Claws/Grey Hunters weapon selection issue, if you are still experiencing this please provide the file version you are using (this should look like v200X) and steps to reproduce the error.
