### ISSUE TITLE
Eldar Craftworlds - Scorpion Claw Cost Incorrect

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#2785]
**File:** Eldar Craftworlds - Codex (2015).catz

**BattleScribe version:** 2.00.09

**Platform:** Android

**Dropbox:** No

**Description:** A striking scorpion exarch should be able to get a claw at 30 points

**Comment by FarseerVeraenthis** [comment]
It is 30 points for me...
