### ISSUE TITLE
Dark_Eldar_Codex_(2014).catz - Kill Team not working correctly

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#2792]
**File:** Dark_Eldar_Codex_(2014).catz

**BattleScribe version:** 2.00.09

**Platform:** Android

**Dropbox:** No

**Description:** Unfortunately when building a roster for killteam it ommits the options for specialists

**Comment by FarseerVeraenthis** [comment]
Kill team is not finalised yet :smile:

**Comment by FarseerVeraenthis** [comment]
Please refer to #2535
