### ISSUE TITLE
Space Marines Warhound uses Horus Hersey rules.

### ISSUE THREAD

**Issue by GenWilhelm** [BSData/wh40k-7th-edition#2795]
The Warhound Scout Titan currently has "God-engine" and "Towering Monstrosity" from "HH: Volume 5" listed under its special rules.

It is also listed at 750 points, while in War Zone Armageddon it is only 720.

**Comment by DrTobogganMD** [comment]
Yep, that was my *bad* choice. I had thought I read the HH:5 rules were usable in 40k as they added some neat rules for the various titans.  I was wrong.
