### ISSUE TITLE
Chaos Space Marines - incorrect point cost for VoTLW for Chosen

### ISSUE THREAD

**Issue by Drachnyen** [BSData/wh40k-7th-edition#2809]
Hello,

New BS fixed the veterans of the long war point issue.  Good work team!

I did find an incorrect value for Chosen. 
For a squad of 5 Chosen,  the VotLW should cost 2 points per model for a total of 10 points. 
BS charges 12 points.    I don't know where the extra 2 comes from.  

Thanks.

**Comment by cartag** [comment]
I'm not able to duplicate this. Can you screenshot the roster editor so I can see what it shows?

**Comment by cartag** [comment]
I think I was able to narrow it down... were you bringing a Dreadclaw? If not, I found another bug. Go me lol.

**Comment by Drachnyen** [comment]
Hey @cartag,

Yes, they had a Dreadclaw as dedicated transport.    

Here is screenshot 
![img_1309](https://cloud.githubusercontent.com/assets/16340056/20435539/7e66e98a-ad7a-11e6-8a79-3a8bfa5de287.PNG)

**Comment by cartag** [comment]
Take of the dreadclaw and look, it should be 10 points. Update incoming tonight

**Comment by Drachnyen** [comment]
Quick find!  Thanks in advance. :)
