### ISSUE TITLE
Space Marine Master of the Forge Upgrades

### ISSUE THREAD

**Issue by senpai514** [BSData/wh40k-7th-edition#281]
Just wanted to get your takes on this situation before I make the changes.  A MotF is standard bolt pistol/bolter for weapons and has access to melee and ranged weapons lists. the pistol can be swapped no problem but for the other arm to upgrade a weapon another step is involved which requires a second point cost.  he may replace his pistol and/or bolter for a power axe. Once he has the axe he is now in possession of a melee weapon which meets the requirements to now take another item from the melee or ranged lists. So he can get another item but it will cost 15 points more than the usual.
Im looking to see what the best way to accomplish this would be so suggestions would be welcome as this affects several catalogues.

**Comment by amis92** [comment]
Simple solutions are best. I think making a separate list is a better way here (so you can assign costs appriopriately etc).
- Bear in mind _simple_ is meant as simple for end user. Catalogues can be complicated inside, that's not _that_ important.

**Comment by senpai514** [comment]
my thoughts are 2 list (entry group) for the options:
Pistol arm - everything costs the same.
bolter arm - available upgrades after taking power axe just have the extra 15 points added in to their cost to account for the first stage upgrade.

Only thing is that users might not recognize why the points are different so would be good for those of us that work the files to know that isn't actually a points error.

**Comment by amis92** [comment]
Well then maybe a short notice in title of nested entry group that contains only those upgrades exchanged-with-axe-on-the-fly. So in "Bolter arm" group you'd have another Group called, say, "Take Power axe and exchange immediately for:"

**Comment by senpai514** [comment]
I see what your saying yeah I should be able to make that work. thanks for the input.
