### ISSUE TITLE
Bug report: Space Marines - Codex (2015)

### ISSUE THREAD

**Issue by dogrizz** [BSData/wh40k-7th-edition#2817]
**File**: Space Marines - Codex (2015).catz
**BattleScribe version**: 2.00.10
**Platform**: Android
**Dropbox**: Yes
**Description**: There is no way to choose Chapter Tactics in Kill Team Detachment.
There is validation error about choosing Specialist though no way to choose them is availible,

**Comment by DrTobogganMD** [comment]
That's because Kill Team isn't yet implemented for Space Marines - just added in the GST.  I'll get it tied up soon.

**Comment by dogrizz** [comment]
Cool, Just reported it as the first thing is a regression (prior to 2.00.0 gst contained chapter tactics for space marines). The second one just supprised after update :)
