### ISSUE TITLE
War Convocation for Cult

### ISSUE THREAD

**Issue by ResidentSteve** [BSData/wh40k-7th-edition#2826]
Cult Mechanicus does not require electro priest selections - they're currently set to mandatory

**Comment by Bparks1983** [comment]
That doesn't seem to work though, selecting Battle Congregation doesn't provide the free upgrades that the War Convocation gives.

**Comment by Thairne** [comment]
THat's because you need to select the War Convocation (Cult). Instructions are provided in all 3 involved files on how to build it.

**Comment by Bparks1983** [comment]
My data files must not have been updating properly, it works now.  Although the Knight Crusader upgrade to the Rapid Fire Battle Cannon w/ Heavy Stubber still costs 5 points (this only seems to be a problem with the Crusader).

**Comment by amis92** [comment]
@Bparks1983 that'd qualify as another issue - please check if it's not already opened and if it's not, open a new one. :)
