### ISSUE TITLE
Black Crusade - Chaos Warband - Chosen cannot select Dreadclaw as dedicated transport 

### ISSUE THREAD

**Issue by Drachnyen** [BSData/wh40k-7th-edition#2827]
Hello,
Chosen cannot add a Dreadclaw as dedicated transport in a black crusade - Chaos warband detachment 

![img_1311](https://cloud.githubusercontent.com/assets/16340056/20457983/4b783fb4-ae66-11e6-81fc-4379307164c2.PNG)

**Comment by cartag** [comment]
Did you add "Show Forge World" to your roster?

**Comment by Drachnyen** [comment]
Oh dang. Newbie mistake.  My bad.  Please ignore !

**Comment by cartag** [comment]
In the CSM file, FW upgrades are hidden by the Show FW option as well as units :)

**Comment by Drachnyen** [comment]
I did find something else. 

When I did add Forgeworld and added the Dreadclaw, I'm seeing -2 points to veteran of the long war!

I'm suspecting something similar to https://github.com/BSData/wh40k/issues/2809

**Comment by Drachnyen** [comment]
![img_1314](https://cloud.githubusercontent.com/assets/16340056/20460099/94c73cd4-aea6-11e6-8195-1293f35f5ea0.PNG)

**Comment by cartag** [comment]
This should decrement by 2, not set to -2. I wonder why it's not working...

**Comment by Drachnyen** [comment]
Should also be free since it's a Black Crusade Detachment
This happens if you add the Dreadclaw.   Otherwise it's working fine

**Comment by cartag** [comment]
THAT'S the problem!

**Comment by cartag** [comment]
Thanks :)

**Comment by Drachnyen** [comment]
Also, legacies of ruin seem to be missing in black crusade detachment. (With Forgeworld selected)

Can u see them?

**Comment by cartag** [comment]
LoR are showing up for me, on tanks and walkers. Right now it's only showing on those two types mainly, I need to go in and research in depth and make a different Entry Group for each type.

**Comment by Drachnyen** [comment]
Forget the legacy issue.  Working for me now
