### ISSUE TITLE
Bug report: Space Marines

### ISSUE THREAD

**Issue by francoisbeaulieu** [BSData/wh40k-7th-edition#2836]
BS2.0 for iOS.

Almost all Space Marines detachments (at least) incorrectly show the god-engine special rule in the roster view. CAD also shows "Ideal mission commander" twice.

**Comment by DrTobogganMD** [comment]
Yea, I'm not sure what happened there. An ID must have gotten switched at some point.

**Comment by francoisbeaulieu** [comment]
Combined Arms Detachment still showing "Ideal mission commander" twice at the top of the section in the roster view.
