### ISSUE TITLE
Chaos Space Marines - Predators and Vindicators Squadrons

### ISSUE THREAD

**Issue by Cultist40k** [BSData/wh40k-7th-edition#2840]
Right now the combined arms detachment for chaos space marines doesn't give options for vindicator and predator squadrons.

The Traitor's Hate supplement updated the rules to the codex as a whole (pg 112). They should have the option to have up to three vehicles with the linebreaker bombardment or killshot special rules when three are taken.

It should work exactly like it functions within the Fist of the Gods formation in Battlescribe.

**Comment by cartag** [comment]
Grrr, I'd made the entries just didn't link them right. It'll be updated.
