### ISSUE TITLE
Chaos Space Marines - Sorcerer Weapon Selection Validation Issue

### ISSUE THREAD

**Issue by francoisbeaulieu** [BSData/wh40k-7th-edition#2843]
BS2.00.07 on iOS

CSM codex catalogue v2004

When adding a sorcerer to a CAD, you immediatly get a validation error saying that it has too many selections of close combat weapons (2).

**Comment by cartag** [comment]
It's set up properly, it looks like something may be borked on the BS side of things. Here's how it's set up in the file. 

![image](https://cloud.githubusercontent.com/assets/4388344/20526319/c29c7b84-b080-11e6-9fe0-2339a7d7e81a.png)

**Comment by cartag** [comment]
This will be changed in a huge patch when Traitor Legions comes out. TL will be included in it.
