### ISSUE TITLE
Space Marines - Siege Assault Vanguard - Carcharodon Tactical Squad Missing CCW Option

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#2846]
**File:** Space Marines - Codex (2015).catz

**BattleScribe version:** 2.00.12

**Platform:** Android

**Dropbox:** No

**Description:** Carcharodon tactical squad doesn't have the option to add a ccw for 1 point per model, they should be able to take both bolter and bolt pistol + the chain sword for an additional

**Comment by FarseerVeraenthis** [comment]
I have just checked, please select Carcharodon Chapter Tactics and then you can choose to have 14 point tactical marines or 15 point marines with extra weapons.
