### ISSUE TITLE
Chaos Space Marines - Kytan as an option for Trinity of Blood

### ISSUE THREAD

**Issue by Cheexsta** [BSData/wh40k-7th-edition#2853]
The Kytan datasheet says that it can be used in any detachment in place of a Lord of Skulls. It should therefore be an option for the Trinity of Blood formation when Forgeworld units are enabled.

**Comment by cartag** [comment]
It is an option for the Trinity of Blood when FW units are enabled.

**Comment by Cheexsta** [comment]
Oops, mustn't have checked it before the most recent couple of updates. Thanks!

**Comment by cartag** [comment]
There's not been any updates made to the Kytan recently at all. Maybe you were using the files that were here before we uploaded the v2000 files?
