### ISSUE TITLE
War convocation Imperial Knight causes crashes on mobile

### ISSUE THREAD

**Issue by SSSlippy** [BSData/wh40k-7th-edition#2856]
Trying to add the detachment causes an instant crash on mobile.

**Comment by SSSlippy** [comment]
Updated the app today with the latest iOS update. 

No longer able to create any army with war convocation. Press the checkbox and it reloads the same screen

**Comment by Thairne** [comment]
Definately not a data problem.
Wrong place to report, try Battlescribe Uservoice ;)
