### ISSUE TITLE
Skitarii and Cult Mechanicus cannot pick a warlord

### ISSUE THREAD

**Issue by SSSlippy** [BSData/wh40k-7th-edition#2859]
Have no option to pick a warlord.

**Comment by SSSlippy** [comment]
Cult Mechanicus cannot take a warlord still.

**Comment by SSSlippy** [comment]
Dont know if its going to be possible but war convocation will have an issue due to the fact that its multiple armies.

**Comment by Thairne** [comment]
Cmon now.
Now we're entering REALLY REALLY picky territory, aint we?
It would be possible if Warlord becomes an entry in the GST.
Tbh I consider the entire "warlord" thing already to be superfluous and hardly worth of data support.
