### ISSUE TITLE
Updating older catalogues for the latest battlescribe

### ISSUE THREAD

**Issue by peterlyberth** [BSData/wh40k-7th-edition#286]
I have some older(6 month) catalogue file for the Heralds of Ruin kill team extension. The problem is that they are made for an older version of the gamesystem.

Is there anyway to simply update the files or do I have to start over again?

The files can be viewed here:
https://www.dropbox.com/sh/w0h93kt5wd7vf7p/AAC6SdGTNa_BaHlD7NGl4ydpa?dl=0

**Comment by amis92** [comment]
Ok I want to help, but you're asking for two different things:
- in title you say about latest BattleScribe. I'm not sure, but I think it's enough to open and save the files in latest version to "update" them.
- in comment you say about updating to the Wh40k 7th ed gst. To achieve this, follow steps described here: https://github.com/BSData/wh40k/issues/55#issuecomment-44529999

**However**, I strongly recommend you to rethink why do you want to put HoR as a part of Standard 40k Game System. My arguments against:
- Number of catalogues would possibly double
- no real connection with any Force Types
- no connection with standard 40k in terms of catalogue inter-connections
- as far as I understand it needs fully separate catalogues - that's the strongest argument

So, besides using the same profile types, I see no connection in terms of "data". Am I right?

If so, give me a sign and I will create appropriate (separate) repository for you. How dou you want to call it? `wh40k-hor-killteam`/`wh40k-heralds-of-ruin-killteam`/something else?

**Comment by senpai514** [comment]
One thing I have a problem with is adding an unofficial non-gw rule set and army lists to our 7th edition system folder where we are tying to keep things updated and bug free so folks can make legal army lists.  not that I am against community rules but mixing them in can make things confusing especially potential mix ups with the actual kill team. Before this I never heard of HOR

**Comment by amis92** [comment]
Wait what.

I am saying exactly that. Let's create separate repository and separate game system for HoR KT.

Then, I think the easiest way would be to follow these steps:
- copy 40k gst
- immediately re-generate ID for it
- remove obsolete Force Types (all of them I think?)
- for each catalogue:
  - copy from wh40k
  - manually edit gameSystemId in xml (paste the new one you generated in second step)
  - apply changes specific to HoR KT, such as remove formations and Apoc units (that'll cut half of weight ;) ), add special rules etc.

So, what should we call this new repo?

**Comment by amis92** [comment]
Well so I took liberty of providing you guys with an empty repo: https://github.com/BSData/wh40k-heralds-of-ruin-killteam

@peterlyberth @senpai514 :
Clone it and fill it! Good luck!
