### ISSUE TITLE
Eldar Craftworlds - Support Weapon Calculation

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#2865]
**File:** Eldar Craftworlds - Codex (2015).catz

**BattleScribe version:** 2.00.12

**Platform:** Android

**Dropbox:** Yes

**Description:** There is a problem with the Vaul Support battery. I just added two more units to the battery but its not counting their weapons.

**Comment by FarseerVeraenthis** [comment]
what do you mean by "it's not counting their weapons"??
Each support weapon is 30 points, with a vibrocannon OR a Shadow Weaver. The only option that costs points is the D-Cannon.
I've just created a list on Android and the only minor problem I've found is that if you choose D-Cannons then change the number of models in the unit the calculation doesn't update. This is overcome by checking and unchecking the D-Cannon option...
