### ISSUE TITLE
Space Marines Stormhawk Interceptor Missing Assault Cannons

### ISSUE THREAD

**Issue by FastWalker0** [BSData/wh40k-7th-edition#2867]
The Stormhawk Interceptor is equipped with 3 types of weapons.  It is missing its twin-linked, wing-mounted Assault Cannons.  They are the same Assault Cannons as on the Stormtalon.  Stats are as follows:

**Name:**  Assault Cannon
**Range:**  24"
**Strength:**  6
**AP:**  4
**Type:**  Heavy 4, Rending , Twin-Linked
**Ref:**  BRB

**Comment by FarseerVeraenthis** [comment]
They are present in File Version 2009, to be released shortly.
