### ISSUE TITLE
Contemptor Dreadnought Dedicated Transport missing Drop Pod

### ISSUE THREAD

**Issue by FastWalker0** [BSData/wh40k-7th-edition#2868]
The Contemptor Dreadnought's Dedicated Transport section is empty.  You should be able to select Drop Pod for 35 points.

**Comment by DrTobogganMD** [comment]
![image](https://cloud.githubusercontent.com/assets/16939161/20579707/ece6be72-b193-11e6-8384-fb7c565470a5.png)

Contemptors are not allowed a dedicated transport.  You can take one for them as a normal slot.

**Comment by FastWalker0** [comment]
Ah, I stand corrected.  Sorry about that.

Looks like I will have to take a Drop Pod in a Fast Attack FoC slot for my Contemptor Dreadnought.

Thanks and Happy Thanksgiving.

**Comment by alphalas** [comment]
Or take a FW contemptor
- Jon[K]
