### ISSUE TITLE
Chaos Space Marines - Legacies of Ruin not working

### ISSUE THREAD

**Issue by Cheexsta** [BSData/wh40k-7th-edition#2869]
Tried to add a Legacy of Ruin to a Chaos Land Raider, getting an error that 0 are allowed. Forgeworld has been selected as an option, the army size is over 1k pts.

Using v2004 of the CSM datafiles.

**Comment by cartag** [comment]
Does the Land Raider have Daemonic Possession?

**Comment by Cheexsta** [comment]
No upgrades other than the Legacy. The specific one I'm trying to add is First War of Armageddon, if that helps.

**Comment by cartag** [comment]
What platform are you using? On iOS and Desktop I've confirmed it's working. Is the army size over 1000 points, or is the Army List roster limit 1k+ points? If the limit is -1, it will not adjust the number allowed.

**Comment by Cheexsta** [comment]
Using Android. The roster is 16k+, but set to -1 limit. I already tried changing the limit to 17k, error still persists.

Tried loading one of my 1850 lists and added the Legacy to one of the vehicles in that, still getting the error.

**Comment by cartag** [comment]
Interesting. Try new roster, 1850 point limit, CSM CAD. I'll do the same on iOS and PC, add "Show Forgeworld" and a Land Raider, then add that one LoR, nothing more. Just to limit variables to it.

**Comment by Cheexsta** [comment]
Error still persists:

"Chaos Land Raider has 1 too many selections from Legacies of Ruin (Tanks) (maximum 0)"

**Comment by cartag** [comment]
Can you share it as a Battlescribe file and email it to bstest@cartag.org?

**Comment by Cheexsta** [comment]
Done.

**Comment by cartag** [comment]
You had your points limit set to -1

**Comment by cartag** [comment]
![image](https://cloud.githubusercontent.com/assets/4388344/20582570/6cdb7432-b19f-11e6-95de-84491c67a3c8.png)

**Comment by cartag** [comment]
The points limit shown above needs to be set at 1k+, however big your roster is going to be. That is what sets the limit on how many Legacies you can include.

**Comment by Cheexsta** [comment]
Oops, forgot to set that. Sorry!

Adding the points limit didn't fix the issue straight away - I had to remove and re-add the Legacy as well. Doing the same to my existing roster worked as well.

Thanks for the help!
