### ISSUE TITLE
Chaos Space Marines - Terminator suggestion

### ISSUE THREAD

**Issue by Cheexsta** [BSData/wh40k-7th-edition#2870]
Hi guys,

I'm finding the process of selecting weapons for my Chaos Terminator units to be very tedious. To add weapons to the unit, you have to add each weapon option to a specific model, then go to the next model and do the same, and so on. The resulting roster ends up being extremely long as it dedicates 2 lines to each Terminator within each unit.

Much more preferable would be like with Chosen, i.e. you can add X number of combi-weapons to the unit, etc.

**Comment by cartag** [comment]
The terminators are set up like that because they are as customizable as champions in normal units. Given the different configurations of them, this is really the best way to do it. I've tested other methods of implementation and they weren't any better.

**Comment by Cheexsta** [comment]
Individual models might be, but it becomes very cumbersome to set up when creating a unit of more than a few models, especially on mobile where you have to equip one model, go back, go into the next model, equip it, go back, etc. 

Add to that the new Terminator Annihilation Force where you could have several such units, and equipping the whole formation becomes an exercise in tedeum.

And then the roster output shows the individual models with all their gear, which just takes up an incredible amount of space.

Much better IMHO to equip the unit with 4x combi-meltas, 2 pairs of lightning claws, 2 chain fists, a heavy flamer, etc.

**Comment by cartag** [comment]
The other reason is that there are different costs per arm for different weapons. I've got enough on my plate right now with implementing Traitor Legions, I'm not taking this on too.
