### ISSUE TITLE
Eldar Craftworlds - Striking Scropion Exarch Missing Options

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#2872]
**File:** Eldar Craftworlds - Codex (2015).catz

**BattleScribe version:** 2.00.12

**Platform:** Android

**Dropbox:** No

**Description:** Striking Scorpions Exarch has only one Weapon Option (2x Chainsabre).

**Comment by FarseerVeraenthis** [comment]
Select Striking Scorpions,
check box for an Exarch,
tap on Exarch to open options,
Standard weapons are "Sword & Weapon";
     Tapping the radio button opens the option to exchange both for 2 x chainsabres
     Tapping the "Weapon - 1 required: Sword and Weapon" area opens another window which gives you choices for which Sword you would like (Chainsword or biting blade) and whether you want to stick with the shuriken pistol or upgrade to a Scorpion's claw.

Therefore, all options are available and this bug is invalid.
