### ISSUE TITLE
Deathwatch Blackspear auxiliary and kill team issues.

### ISSUE THREAD

**Issue by Lysere** [BSData/wh40k-7th-edition#2873]
The armor option for the Deathwatch Blackspear auxiliary slot is missing from the options.

Also for Aquila kill teams (and perhaps others) it defaults to two teams of veterans rather than the one it's supposed to be.

**Comment by flakpanda** [comment]
- [x] Fix armor link for BSSF
- [x] Fix default entries doubling

**Comment by flakpanda** [comment]
The doubling of certain entries is currently a battlescribe bug.

**Comment by Lysere** [comment]
Wasn't aware, I'll keep an eye out.

**Comment by FarseerVeraenthis** [comment]
Since default selections are causing trouble, the CAT has been changed so that veterans are not a default selection but an error is thrown if you do not select one squad of veterans.
This covers the issue in my opinion.
