### ISSUE TITLE
Eldar Craftworlds - Dark Reaper Starshot Missile Upgrade Calculation Incorrect

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#2878]
**File:** Eldar Craftworlds - Codex (2015).catz

**BattleScribe version:** 2.00.12

**Platform:** Android

**Dropbox:** No

**Description:** Dark reapers upgraded shot is not 72 points per model. Needs fixed please.

**Comment by FarseerVeraenthis** [comment]
Drat!! I made a change which worked nicely on Desktop, seems like it didn't work out quite how I planned on Android... I thought I checked it on my phone... Anyway, I think I know what the problem is, I'll try to have a look this evening :smile:
