### ISSUE TITLE
Eldar - Corsairs - Felarch Weapon & Raider Detachment Problems

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#2879]
**File:** Eldar - Corsairs (2015).catz

**BattleScribe version:** 2.00.07

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Says there is a problem with these files when using raider detachment. Also felarch says too many weapon options error when replacing standard equipment with a pistol and power weapon etc.

**Comment by FarseerVeraenthis** [comment]
- [x] Raider Detachment Issue

- [x] Felarch Weapon Issue

**Comment by FarseerVeraenthis** [comment]
As a point of note, the issues with the detachment might be due to limitations of the iOS implementation. This issue has been seen on some of the other CAT's as well.
It does work on desktop but will occasionally crash BattleScribe - I don't know why...
