### ISSUE TITLE
Obsidian Knight

### ISSUE THREAD

**Issue by senpai514** [BSData/wh40k-7th-edition#289]
@Kangodo I saw your commit for this knight and last I knew his datasheet is an apoc datasheet as it is published in an Apocalypse Warzone and not available in regular games. As far as I know (unless I'm missing something) that book would need an errata saying that model is playable in a Codex: Imperial Knight army.

**Comment by Kangodo** [comment]
Ah yes, I see.
I'm unsure how to deal with this.. Maybe turn him into a Battle Formation so it's Apocalypse Only?

**Comment by amis92** [comment]
More like Legendary Unit :)

**Comment by senpai514** [comment]
Just about to say the same
