### ISSUE TITLE
Just upgraded to 2.00

### ISSUE THREAD

**Issue by lhavoc1** [BSData/wh40k-7th-edition#2890]
Trying to load a data file for 40k but when I try to update it in BattleScribe 2.00 it pulls up a bubble that just says "one or more file errors have occurred" and I cannot save a list. What am I doing wrong?

**Comment by FarseerVeraenthis** [comment]
did you create the roster in v2.00 or are you trying to import it from v1.15??

I'm not sure if rosters generated in the previous version can be loaded in the new version, so you might have to rebuild them from scratch...

**Comment by Thairne** [comment]
They can't.

**Comment by FarseerVeraenthis** [comment]
Therefore, @lhavoc1 you'll have to redo the list from scratch...

**Comment by lhavoc1** [comment]
But I can't even create a list in 2.00! It won't save for some reason. This is on the iPhone, the new desktop seems to be working alright. Could it just be because I haven't purchased it yet?

Get Outlook for iOS




On Mon, Nov 28, 2016 at 5:14 AM -0800, "Simon Porter" <notifications@github.com> wrote:












Closed #2890.

**Comment by Thairne** [comment]
Nah purchasing does not affect that. It only enables a few features and removes the ads.
Looks like BS is a bit buggy..
You could try to get a clear way to reproduce it, write that down and submit a bug report at battlescribe's uservoice page.
If it works with desktop it'S not an issue with the data...

**Comment by lhavoc1** [comment]
All I get is a multiple error message that "one or more errors have occurred" and it won't save anything even though I put together a perfectly legitimate list.

Get Outlook for iOS




On Mon, Nov 28, 2016 at 9:45 AM -0800, "Thairne" <notifications@github.com> wrote:












Nah purchasing does not affect that. It only enables a few features and removes the ads.

Looks like BS is a bit buggy..

You could try to get a clear way to reproduce it, write that down and submit a bug report at battlescribe's uservoice page.

If it works with desktop it'S not an issue with the data...

**Comment by amis92** [comment]
@lhavoc1 first off, did you try to purge the data first? If so, the problem may also arise if you use Dropbox sync, it's quite buggy right now. Else than that, talk with BS developer.

**Comment by lhavoc1** [comment]
I go to app spot and try to load the Warhammer 40,000 or the Battlefleet Gothic data and I get the same error message. The data set doesn't appear on the screen, but I know it's in there. Because I can build a list, but then I get the error message again. How do I do a "hard" purge of the data?

Get Outlook for iOS




On Mon, Nov 28, 2016 at 10:20 AM -0800, "Amadeusz Sadowski" <notifications@github.com> wrote:












@lhavoc1 first off, did you try to purge the data first? If so, the problem may also arise if you use Dropbox sync, it's quite buggy right now. Else than that, talk with BS developer.

**Comment by amis92** [comment]
https://battlescribe.net/?faq=dataProblems

and there is linked https://battlescribe.net/?faq=refreshData

**Comment by lhavoc1** [comment]
Deleted all the data and attempted to reload Warhammer 40,000 data. Same error message.

Get Outlook for iOS




On Mon, Nov 28, 2016 at 10:46 AM -0800, "Amadeusz Sadowski" <notifications@github.com> wrote:












https://battlescribe.net/?faq=dataProblems


and there is linked https://battlescribe.net/?faq=dataProblems#
