### ISSUE TITLE
Space Marines - Contemptor Dreadnought Missing

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#2893]
**File:** Space Marines - Codex (2015).catz

**BattleScribe version:** 2.00.13

**Platform:** Android

**Dropbox:** No

**Description:** Sorry to bring it up again since there were already 2 Issues closed with the problem.
There is still no FW Contemptor Dreadnought in the elites section. There was an Issue where the Mortis was missing. That one is fine and dandy but the normal Contemptor the one with the FW weapon Options (e.g. conversion beamer) is missing. I read on the last closed issue that this was fixed. After purging and redownloading my data 3 times and de- and reinstalling my battlescribe updating it 2 times to be sure I can still say the entry is missing.

Sorry for not commenting on one of the old issues but since im not registered and rarely frequent the site I had to open a new one.

**Comment by FarseerVeraenthis** [comment]
It appears you need to select "Red Scorpions" Chapter Tactics.
I've no idea if this is correct or not, but I can confirm that when Red Scorpions Chapter Tactics are selected, the Contemptor will appear.

**Comment by francoisbeaulieu** [comment]
That doesn't match what IA2 specifies:
<img width="561" alt="screen shot 2016-12-15 at 4 46 47 pm" src="https://cloud.githubusercontent.com/assets/12718495/21243306/45a485ae-c2e6-11e6-964d-e9834d7e79a5.png">

**Comment by FarseerVeraenthis** [comment]
Cool :-) then it should be a fairly easy fix :-)
