### ISSUE TITLE
New fortifications in planetary onslaught

### ISSUE THREAD

**Issue by Joshua137** [BSData/wh40k-7th-edition#2899]
In the new Planetary Onslaught book, it appears that the Shrine of the Aquila, Manufactorum, Basilica Administratum, and Sanctum Imperialis are all able to be purchased as a fortification

**Comment by fejjn** [comment]
Any news on this? Id very much like them aswell..

**Comment by FarseerVeraenthis** [comment]
Yes, it is on the list, although I don't think anyone has officially taken ownership of doing the update yet...
