### ISSUE TITLE
Duplicate file ID - heralds of ruin eldar

### ISSUE THREAD

**Issue by ghost** [BSData/wh40k-7th-edition#290]
Look like there are two copies of the HoR Eldar: same id, different names.

**Comment by Kangodo** [comment]
I changed the ID so I can actually open the roster editor.
But it's still unclear why the HoR-Kill team is in the 40k section.

**Comment by peterlyberth** [comment]
My fault.
Couldnt remove the file, after I uploaded the damn thing.

The HoR system is in the 40k section for the same reason escalation and other expansions are:-)

**Comment by Kangodo** [comment]
I can remove the file if you want, just give me the name of it and I will delete it.

#286 should be read, we think it's better to create a new repository for this.

**Comment by peterlyberth** [comment]
Didnt see that, sorry.

Let me read through it, but just delete the kill team files, so they dont clutter things up, untill we/I figure out how to do it:-)
