### ISSUE TITLE
windriders min unit error

### ISSUE THREAD

**Issue by plebicidal** [BSData/wh40k-7th-edition#2900]
Where windrider unit includes warlock & winderiders reduced to 2, error is displayed:
"Windriders must have 1 more selections from Members - 3 to 10 (minimum 3)"
Warlock should count towards unit members.

**Comment by FarseerVeraenthis** [comment]
That's not correct. The Warlock is an additional model, not an upgrade to an existing Windrider. 
The unit composition calls for 3 Windriders, and the Warlock has a unit type of Windrider warlock, which doesn't count.
Note that this does mean that you can have 10 Windriders and a warlock for a unit of 11 models.
