### ISSUE TITLE
Space Marines - Angels of Death Relics Missing

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#2903]
**File:** Space Marines - Codex (2015).catz

**BattleScribe version:** 2.00.08

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Relics from Angels of Death Space Marine supplement appear to be missing.

**Comment by FarseerVeraenthis** [comment]
The Armour Indomitus, Shield Eternal, Primarchs Wrath, Burning Blade, Teeth of Terra, and the Standard of the Emperor Ascendant are present.
Which ones are missing??

**Comment by FarseerVeraenthis** [comment]
I'm pretty sure they're all there...
I'm closing this one and rolling it into #2768

**Comment by FarseerVeraenthis** [comment]
The complete list is as follows:
Imperial Fists;
- The Banner of Staganda
- The Angel of Sacrifice
- The Spartean
- The Bones Of Osrak
- The Eye of Hypnoth

White Scars;
- The Banner of The Eagle
- Scimitar of The Great Khan
- The Glaive of Vengance
- Wrath of the Heavens
- Mantle of the Stormseer
- The Hunter's Eye

Iron Hands;
- The Axe of Medusa
- The Mindforge Stave
- Betrayer's Bane
- The Gorgon's Chain
- The Ironstone
- The Tempered Helm

Raven Guard;
- Swiftstrike & Murder
- Raven's Fury
- Ex Tenebris
- The Armour of Shadows
- The Raven Skull of Korvaad

Salamanders;
- Drake-Smiter
- Wrath of Prometheus
- The Salamander's Mantle
- The Tome of Vel'Cona
- Vulkan's Sigil
