### ISSUE TITLE
Renegades & Heretics.cat Errors

### ISSUE THREAD

**Issue by mynameislouie** [BSData/wh40k-7th-edition#2905]
Loading Renegades & Heretics.cat in BattleScribe v2.00.05 gives the following errors:
[Pastebin Link](http://pastebin.com/bSdmzU0n)

**Comment by GenWilhelm** [comment]
"Renegades & Heretics: IA13 (2014)" is an obsolete file that is not compatible with BattleScribe 2.0.
The current (and only) R&H file is "Renegades & Heretics: IA13 / IA:SoV" (this should be at least version 2000).

If you are seeing more than one Renegades & Heretics catalogue please refresh your data files:
https://battlescribe.net/?faq=refreshData

**Comment by radionausea** [comment]
I've deleted and cleared, redownloaded my data several times now (android), there's still three different versions of the R&H list visible

**Comment by GenWilhelm** [comment]
@radionausea the current version of the R&H file is "Renegades & Heretics: IA13 / IA:SoV v2003". If you're using that one all should be well.

As for the other files not being removed, that is strange. What version of BattleScribe are you using?
If you delete your data without redownloading, then go back to the roster menu does it let start a new roster, or does it say you have no files?

If we can't get this resolved I'll raise it with the BS dev to see if it is a bug with the app itself.
