### ISSUE TITLE
Chaos Space marines - Add wrath of Magnus dataslates and formations 

### ISSUE THREAD

**Issue by Drachnyen** [BSData/wh40k-7th-edition#2910]
Just gonna drop this here ;)

Thanks in advance @cartag

**Comment by Drachnyen** [comment]
Decurion : Grand Coven
Core: war Cabal
Core: Sehkmet Conclave 
Command: Rehati War Sect
Command: Arhiman's exiles
Command: Lord of the Legion
Aux: war coven
Aux:  Tzangoor warheard 
Aux: Daemon engines 
Aux: Legion Armory
![5a8ce317-a498-4b77-92e1-73632637bb8a-12575-00000b9c10024b3f_tmp](https://cloud.githubusercontent.com/assets/16340056/20713577/d1b2751a-b616-11e6-97f3-a56d4705441a.png)
![c987405e-0b8f-487a-9886-c67f3478afbb-12575-00000b9c13dcd7dc_tmp](https://cloud.githubusercontent.com/assets/16340056/20713579/d1ca3b5a-b616-11e6-93c8-308f20eab8f9.png)

**Comment by cartag** [comment]
Already in progress, but thanks for making it an issue so nobody else does.
