### ISSUE TITLE
Tau - Crisis Suit Elite/Troop Choice Issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#2913]
**File:** Tau - Codex (2015).catz

**BattleScribe version:** 2.00.05

**Platform:** Mac

**Dropbox:** No

**Description:** When using the Tau Dawn Blade Contingent, Crisis suits remain elite choices - while per the rules (Mont'a), they should become troop choices.
Even with the Farsighted enclaves activated, etc this doesn't change.

**Comment by Bparks1983** [comment]
It only applies to a stock detachment, combined arms, allied, etc.  When you build a Hunter Contingent inside of a Farsight list, the Hunter list specifies the units you can take by name, not by type.
