### ISSUE TITLE
Space Marines - Gladius Strike Force / Battle Company Missing Named Characters

### ISSUE THREAD

**Issue by TheRedViking** [BSData/wh40k-7th-edition#2927]
Can not select a named captain ie Vulcan hestan as the captain of a demi company in the battle company formations  ie the free transport core choice

**Comment by FarseerVeraenthis** [comment]
yes, you can.
You need to select Salamanders Chapter Tactics and he will appear - as if by magic :smile:

**Comment by TheRedViking** [comment]
Bit sure what is wrong on my end then, is the current version of the file v10?  I still do not have an option to replace the captain  in the battle company (free tansport) formation, the battle demi company works as it should for me.

**Comment by FarseerVeraenthis** [comment]
Right, you can select him in a single demi-battle company, but when you load a demi-battle company inside a Gladius Strike Force he doesn't show...
This is a bug, sorry for closing the ticket prematurely!!
I believe this is a fairly simple issue with the hide/unhide criteria, so I call @Kohato to fix this with his BSData ninja skills...!!

**Comment by GenWilhelm** [comment]
@TheRedViking in response to your question, the current version for Space Marines is v2008.
I suggest you update your data files!

**Comment by FarseerVeraenthis** [comment]
Try again with v2009
