### ISSUE TITLE
Space Marines - Dreadnought Attack Value Issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#2928]
**File:** Space Marines - Codex (2015).catz

**BattleScribe version:** 2.00.05

**Platform:** Windows

**Dropbox:** No

**Description:** Space Marine dreadnoughts, as far as I know, have 4 attacks not 6. From memory, there was an update/FAQ that granted two extra attacks to dreads from old codices to bring them up to date with "generic" SM dreads that have 4 attacks. This applied to dreads, ironclads & venerable. 

I have the latest battlescribe and the latest SM data (v2008)

**Comment by francoisbeaulieu** [comment]
Yup, that errata doesn't seem to apply to the SM codex.
![image](https://cloud.githubusercontent.com/assets/12718495/21210824/65d0062c-c24c-11e6-9323-161d699e5924.png)

**Comment by FarseerVeraenthis** [comment]
Wow, so in the version of the Space Wolf Codex I'm looking at Bjorn and Murderfang have 4 attacks already - so they will have 6... but the standard dreads will have 4, per the Space Marine codex.
Hopefully I'll have time to look at this tonight, it shouldn't be too tricky to fix... \famous last words

**Comment by DrTobogganMD** [comment]
Yep. I messed up. Sm dreads are at 4. Sw dreads are also 4 except bjorn and murderfang who have 6 now

~Earl Bishop
815-405-7187
