### ISSUE TITLE
Ork Waaagh! band missing gretchin

### ISSUE THREAD

**Issue by SSSlippy** [BSData/wh40k-7th-edition#2930]
The formation requires one unit of gretchin.

**Comment by tag8833** [comment]
I'm adding as a personal reminder to this that the Wargear selections for the Green Tide and Ork Warband need the same treatment that I had to give the wargear selection for all of the other entries for Ork Boyz.

**Comment by tag8833** [comment]
The Kustom Wazmob also needs constraints fixed.   

I'll get all these items addressed on Friday.
