### ISSUE TITLE
eldar - autarch spectre jetpack option missing

### ISSUE THREAD

**Issue by plebicidal** [BSData/wh40k-7th-edition#2934]
When a unit of shadow spectres are included in a force, autarch should have access to a spectre jetpack

![image](https://cloud.githubusercontent.com/assets/18018035/20818827/7ae6803a-b884-11e6-8030-61ed8db05cd1.png)

**Comment by FarseerVeraenthis** [comment]
Thanks for the garb, I'll see if I can add this when I update for the Dire Avenger Shine issue #2941
