### ISSUE TITLE
Eldar Craftworlds - Dire Avenger Shrine Missing from Craftworld Warhost

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#2941]
**File:** Eldar Craftworlds - Codex (2015).catz

**BattleScribe version:** 2.00.05

**Platform:** Windows

**Dropbox:** Yes

**Description:** Dire Avenger Shrine is missing from the Auxiliary choices of the 'E Craftworld Warhost' Force Org

**Comment by FarseerVeraenthis** [comment]
Those naughty rascals!! I'll try to sort this out this week...
