### ISSUE TITLE
CSM - Add Traitor Legions Info

### ISSUE THREAD

**Issue by cartag** [BSData/wh40k-7th-edition#2943]
Posting this before somebody else has a chance to helpfully suggest I add it.

**Comment by Drachnyen** [comment]
Beat me to it ;)

**Comment by cartag** [comment]
Wasn't meant to be a challenge, I know enough to add books when they come out.

**Comment by Drachnyen** [comment]
Hey @cartag,

My comment above was meant as a joke.
I am sorry if you felt offended and I apologize.

Your contributions are awesome, and your work on the CSM stuff is much, much appreciated
