### ISSUE TITLE
Blood Angels - Battle Demi-Company Command Selection

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#2944]
**File:** Blood Angels - Codex (2014).catz

**BattleScribe version:** 2.00.08

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** When creating a Battle Demi-Company list: you must select command squad or furioso dreadnought

If you select furioso dreadnought  you get 2 errors
Must have selection command squad (minimum 1)
And
To many selections from furioso dreadnought  (maximum 0)

**Comment by GenWilhelm** [comment]
This is because you have a Captain selected.
In the Battle Demi-Company you must select a Captain and Command Squad; or a Chaplain and Furioso Dreadnought.

Perhaps this could be improved for better clarity.
