### ISSUE TITLE
Chaos Space Marines - Knight Legacy Access Issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#2945]
**File:** Chaos Space Marines - Codex.catz

**BattleScribe version:** 2.00.13

**Platform:** Android

**Dropbox:** No

**Description:** [FW] Chaos Knight Paladin and [FW] Chaos Knight Errant
Are currently being given access to "Legacy of Ruin (Walkers)"
As they are Superheavy vehicles, they should instead have access to the more expensive "Legacies of Ruin" as implemented by the Chaos Fellblade and Chaos Warhound Titan, which among others are implemented correctly.

**Comment by cartag** [comment]
This will be changed in a huge patch when Traitor Legions comes out. TL will be included in it.
