### ISSUE TITLE
Chaos Space Marines - List Creation Issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#2947]
**File:** Chaos Space Marines - Codex.catz

**BattleScribe version:** 2.00.09

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** okay so since the new wrath of magnus book and the new models i got rid of the old battlescribe and replaced it with the updated one. so as i was to make a list for the Thousand Sons it wouldn't let me create the list. i tried a couple of times and it still wouldn't let me creat the list i want to make.

**Comment by ghost** [comment]
Clarification in what kind of list you're trying to make would help determining what's up  I think. What detachment is causing issues and what is specifically wrong with it?

**Comment by cartag** [comment]
This will be changed in a huge patch when Traitor Legions comes out. TL will be included in it.
