### ISSUE TITLE
Chaos Space Marines - Astral Grimoire Issue

### ISSUE THREAD

**Issue by ghost** [BSData/wh40k-7th-edition#2948]
File: Chaos Space Marines - Codex.catz
BattleScribe Version: 2.00.05
Platform: Windows
Description: The Thousand Sons Artefact "The Astral Grimoire" shows up as an option for kitting out normal chaos sorcerers when using non-Thousand Sons detachments, this appears to be the only case of TS artefacts appearing in non-TS character equipment options.

**Comment by cartag** [comment]
I'm unable to duplicate this. The restrictions on it are the same as they are for the Scrolls. Did you have it set to TS then switch to a different option? That's the only thing I can come up with.

**Comment by ghost** [comment]
Nope, I was working with TS detachments previously, but to make sure I just made a new roster using Codex: CSM and a formation detachment with infinite points, selected Hidden units and Datasheets but left it unchecked, selected force options and checked Black Legion, then added a Cyclopia Cabal to the roster. Upon which the Astral Grimoire appears to be listed as the first item under Chaos Artefacts except with a box and arrow instead of the usual checkbox to show how many of which you want to take (You can make this # as high as you like without popping an error and it uses 30 points for each one).

**Comment by cartag** [comment]
This will be changed in a huge patch when Traitor Legions comes out. TL will be included in it.
