### ISSUE TITLE
Space Wolves - Weapon Selection Bugs

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#2950]
**File:** Space Wolves - Codex.catz

**BattleScribe version:** 2.00.09

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Space wolf file v2012 has bugs on all the units weapons numbers. If you have a 5 man squad and try to add weapons to them any thing you add over 2 weapons gives you the message that you are over your limit. So 5 men may have up to 10 weapons but will only let you have 2. This appears to be with all the space wolf squads. Troops, elites. Etc......

**Comment by FarseerVeraenthis** [comment]
The latest version on Github is v2013. Try that...
