### ISSUE TITLE
Tyranids - Tyrannocyte Max Selection Issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#2951]
**File:** Tyranids - Codex.catz

**BattleScribe version:** 2.00.13

**Platform:** Android

**Dropbox:** No

**Description:** Says I can't use more than one tyrannocyte in the no force org' slot.  Rules state I can take more than one drop pod.

**Comment by Randobar** [comment]
should be done now. but did not test it

**Comment by FarseerVeraenthis** [comment]
That seems to work now on Desktop at least. The update will be caught in the next release (if not already 😄 )
