### ISSUE TITLE
CSM Thousand Sons - Exalted Sorcerer not available as HQ choice in a CAD

### ISSUE THREAD

**Issue by Drachnyen** [BSData/wh40k-7th-edition#2952]
In a Thousand Sons detachment, exalted Sorcerer should be a possible HQ choice in a CAD. 

Currently, it is not possible to select one. 

![img_1337](https://cloud.githubusercontent.com/assets/16340056/20869133/00ebdd22-ba3a-11e6-9d17-a337f7a9d094.PNG)

**Comment by DrSentryy** [comment]
Was this issue fixed

**Comment by FarseerVeraenthis** [comment]
Not yet.
There is a big update planned after the release of Traitor Legions at the weekend, so check back next week :smile:

**Comment by cartag** [comment]
This will be changed in a huge patch when Traitor Legions comes out. TL will be included in it.
