### ISSUE TITLE
Chaos Space Marine - Sorcerer equipped with Force Sword and Bolt Pistol generates error

### ISSUE THREAD

**Issue by Drachnyen** [BSData/wh40k-7th-edition#2953]
Hello,

I am getting a validation error when equipping a Sorcerer with a Force Sword and a Bolt Pistol. 

![img_1338](https://cloud.githubusercontent.com/assets/16340056/20869201/7143f590-ba3b-11e6-9d2d-65f6e96f91fe.PNG)

**Comment by cartag** [comment]
This will be changed in a huge patch when Traitor Legions comes out. TL will be included in it.
