### ISSUE TITLE
CSM Thousand Sons - unable to create Grand Coven detachment 

### ISSUE THREAD

**Issue by Drachnyen** [BSData/wh40k-7th-edition#2954]
Hello,

Unable to create a Thousand Son Grand Coven detachment on iOS. 

When selecting detachment and pressing check to create it, the app loads a bit then goes back to detachment creation screen.  

![img_6523](https://cloud.githubusercontent.com/assets/16340056/20870071/08ceda5c-ba4f-11e6-83f0-5ae323a2668f.PNG)
![img_6524](https://cloud.githubusercontent.com/assets/16340056/20870072/08dd18a6-ba4f-11e6-8a16-7949558a21db.PNG)

**Comment by cartag** [comment]
This will be changed in a huge patch when Traitor Legions comes out. TL will be included in it.
