### ISSUE TITLE
Space Wolves - Missing Force Rules when using more than one detachment/formation

### ISSUE THREAD

**Issue by SuperPranx** [BSData/wh40k-7th-edition#2956]
When you have two (or more) forces in your roster e.g. Space Wolves CotGW Detachment and a CAD, the Force rules include only the rules for the last of these forces. This is an old bug and has been present for a very long time, even in the time of BattleScribe v1.x.

**Comment by GenWilhelm** [comment]
Related to 56e4090fc5ed497fda13c039404b361065df2241.
