### ISSUE TITLE
Unable to use BattleScribe for Space Marine Forces

### ISSUE THREAD

**Issue by candidgamera** [BSData/wh40k-7th-edition#2957]
I've updated my laptop copy to the 2.00.05.60 - which doesn't work. I can't open my old rosters, or create new rosters, because I get an error saying that the Space Marine file is missing or corrupted if I try to open an old one, and if I try to create a new one, it doesn't appear in the list of rosters to select. 

I've tried 1.15 with the legacy archive on a different PC - that doesn't allow me to open my old rosters, nor does it allow me to create new rosters.  (When I try to add a force, the Force Type drop-down says 'No force types..') Trying to open old ones gives Java error spew. 

I'm completely unable to use Battlescribe as a result. Please advise.

**Comment by GenWilhelm** [comment]
Unfortunately, due to the extensive changes made to the data format in BattleScribe 2, most rosters made in 1.15 are not compatible with the current version of BattleScribe. These rosters should still work in BS 1.15 with the appropriate data files, but will have to be remade in order to be updated for 2.0.

For both of the issues described I would first suggest you purge any existing data files in order to download a fresh set - https://battlescribe.net/?faq=refreshData

**Comment by candidgamera** [comment]
I did try that as an initial troubleshooting step on the version 2 installation. The error persisted. Is there anything else I can try?

However, a complete data purge and reload from the archive has got 1.15 working for me again, so there's that at least!

**Comment by GenWilhelm** [comment]
I just want to confirm, when you start a new roster is the selected game system "Warhammer 40,000 7th Edition v2012"?
If so, when you open the list of catalogues are most of them v2000 or higher?

**Comment by candidgamera** [comment]
I will verify that when I get home at 4:30PM, but I believe that was correct.

**Comment by candidgamera** [comment]
I think it is working now. I may have missed deleting a file in the data
root directory.. settings.xml. Though I may also have just been thrown by
the fact that the Marine codex is no longer labelled with the year of
publication, but a version number that is suspiciously close to the year of
publication of the previous codex.

**Comment by FarseerVeraenthis** [comment]
Sounds like you're making progress :+1:
