### ISSUE TITLE
CSM Thousand Sons - Scarab Occult Terminators Wargear Issue

### ISSUE THREAD

**Issue by skaigh** [BSData/wh40k-7th-edition#2958]
For Scarab Occult Terminators, when equipped with Heavy Warpflamers or Soulreaper Cannons, no weapon profiles are generated.

Edit: Have tested, and this occurs on Windows BS v2.00.05.60 and Android v2.00.13.

![scaraboccterm](https://cloud.githubusercontent.com/assets/24393115/20893845/399ed7a8-bae1-11e6-92f1-af9668f7b7eb.png)

**Comment by cartag** [comment]
This will be changed in a huge patch when Traitor Legions comes out. TL will be included in it.
