### ISSUE TITLE
CSM Thousand Sons - Rubric Marine Wargear Issue

### ISSUE THREAD

**Issue by skaigh** [BSData/wh40k-7th-edition#2964]
Wrath of Magnus: Rules lists Rubric Marines as having Inferno Boltguns, but database shows standard Boltguns.

CSM v2006

**Comment by cartag** [comment]
They are listed with the Inferno Bolts profile as well, it wasn't updated yet from old profile to new. It still has the requisite information though.

**Comment by cartag** [comment]
This will be changed in a huge patch when Traitor Legions comes out. TL will be included in it.
