### ISSUE TITLE
Deathwatch - Deathwatch Shotgun Missing

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#2970]
**File:** Deathwatch - Codex.catz

**BattleScribe version:** 2.00.13

**Platform:** Windows

**Dropbox:** No

**Description:** There is no option for the deathwatch shotgun for the veterans in the deathwatch codex.

**Comment by FarseerVeraenthis** [comment]
Whoops! I don't know where that's gone then... If @flakpanda doesn't get there first I'll take a look later.

**Comment by FarseerVeraenthis** [comment]
On Android the Deathwatch Shotgun is in the Special Weapons section.
I cannot check on Desktop at the moment but I'm fairly certain the option is present in file version 2014.

**Comment by FarseerVeraenthis** [comment]
Yup, it's there, Deathwatch Shotgun is the second selection down in the Special Weapons Section
