### ISSUE TITLE
Space Marines - Bike Squad Issue

### ISSUE THREAD

**Issue by zuriel42** [BSData/wh40k-7th-edition#2973]
Selecting the Bike Squad as part of a fast attack choice in a Combined Arms Detachment or as a fast attack unit in a Battle Demi-Company while no HQ choice has a Space Marine bike selected causes a warning that bike squads are invalid as a fast attack choice when using the mobile app.

Steps to reproduce (Combined Arms):
Create new Combined Arms list using Space Marine Codex (2015)
Add HQ (Captain, Chaplain, or Librarian) - No upgrades
Add 2 tactical squads to troops - no upgrades
Add Bike Squad to fast attack.
Only invalid error showing should be that bike squads are invalid fast attack choice.

**Comment by FarseerVeraenthis** [comment]
@Kohato I'm sorry, I don't understand the "Set Hidden to True" criteria you've used in the CAT, so I'll leave this one...

**Comment by FarseerVeraenthis** [comment]
Although, I noticed one set of conditions is set to "or" and the other is set to "and". I changed the second to "or" so that might fix the problem magically :smile: 
Try v2009 when released...
