### ISSUE TITLE
Chaos Space Marines - Raptor Talon Missing From Black Crusade Detachment

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#2974]
**File:** Chaos Space Marines - Codex.catz

**BattleScribe version:** 2.00.05

**Platform:** Windows

**Dropbox:** No

**Description:** Chaos Space Marine Black Crusade Detachment missing Auxiliary Choice Raptor Talon.

**Comment by cartag** [comment]
This will be changed in a huge patch when Traitor Legions comes out. TL will be included in it.
