### ISSUE TITLE
Bug Report - Grey Knights: Codex (2014) v3 - Relics Of Titan

### ISSUE THREAD

**Issue by Xianator** [BSData/wh40k-7th-edition#298]
A character is not able to take more than one relic in this version of the roster.

**Comment by amis92** [comment]
As settled in #282, specifically [here](https://github.com/BSData/wh40k/pull/282#issuecomment-53694369), it's correct.

**Comment by Xianator** [comment]
The wording in the GK codex is different than in Space Wolves.  So yes, it is one per model in codex Grey Knights!  Sorry for the trouble.
