### ISSUE TITLE
Space Wolves - Wolf Claw Strike Force Issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#2982]
**File:** Space Wolves - Codex.catz

**BattleScribe version:** 2.00.29

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Not letting me make a wolf claw strike force list.

**Comment by FarseerVeraenthis** [comment]
I found when I tried this last night on Desktop that it does take a little while to load.
Perhaps try again but give it some extra minutes to work itself out...

**Comment by FarseerVeraenthis** [comment]
Please update Battlescribe and download the latest data.
The Space Wolves CAT has recently been overhauled so this should be fixed.
