### ISSUE TITLE
Bug Report: Space Marines - GSF Battle-Company Chaplain

### ISSUE THREAD

**Issue by francoisbeaulieu** [BSData/wh40k-7th-edition#2984]
BS2.00.09 for iOS
Space marines codex v2008

When selecting a full battle company, demi-company #2 has two selections for chaplain. The first is auto-selected but you get a validation error until you also select the second and its points are counted twice.

![image](https://cloud.githubusercontent.com/assets/12718495/20968978/e5d6446a-bc54-11e6-97ad-64e6faf5f52c.jpeg)

**Comment by FarseerVeraenthis** [comment]
See #2860
This is a duplicate issue.

**Comment by francoisbeaulieu** [comment]
Sorry, looked through the list but somehow missed that one.

--
François Beaulieu (iPhone)
(514) 667-0691 x2061
