### ISSUE TITLE
Space Wolves: Collective Shared Entries Causing Problems

### ISSUE THREAD

**Issue by Jonskichov** [BSData/wh40k-7th-edition#2986]
There are several shared selection entries with "collective" ticked, which are causing trouble.

An example is the storm shield. Because it is collective, when you select one for a Thunderwolf Cavalry, it also gets selected for the other Cavalry models - they should be able to select them individually.

**Comment by GenWilhelm** [comment]
The Space Wolves catalogue is in a bit of a state at the moment, as it didn't receive the full 2.0 overhaul that most of the other big files have had. I've been patching things up while the main keeper is away, but it seems the problems run deep.

The specific issue with Thunderwolf Cavalry storm shields has been resolved, and should be out with tonight's release. If you have any other examples, I'm more than happy to resolve them before we get the catalogue updated.

While we have your attention, I hope you don't mind me asking what the best channel is for us data editors to contact you on regarding issues with the app itself. I know myself and a handful of other members of the team have run into problems that we are unsure whether we are able to resolve or not.

Cheers!

**Comment by FarseerVeraenthis** [comment]
That would explain what the "Collective" checkbox does though... I'll bear that in mind for future!!

**Comment by Jonskichov** [comment]
@GenWilhelm No problem :)

Uservoice is best for bug reports right now, I'm trying to get it all organised under there. I'm working on going though engine fixes right now.
