### ISSUE TITLE
[Anon] Bug report: Astra Militarum - FW - Armoured Battle Group.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#2988]
**File:** Astra Militarum - FW - Armoured Battle Group.catz

**BattleScribe version:** 2.00.05

**Platform:** Windows

**Dropbox:** No

**Description:** Needs to be updated for 2.00.05  
Too many units are showing up as being needed to be chosen

**Comment by FarseerVeraenthis** [comment]
Please refer to #2548

**Comment by alphalas** [comment]
I'll get this fixed.

**Comment by alphalas** [comment]
Update data - fixed the next release.
