### ISSUE TITLE
Renegades & Heretics - Force Org Issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#2992]
**File:** Renegades & Heretics.catz

**BattleScribe version:** 2.00.13

**Platform:** Android

**Dropbox:** No

**Description:** Too many force org requirements when making a combined arms detachment.

**Comment by FarseerVeraenthis** [comment]
which requirements do you think are too many??

Also, do you have the latest data? Which file version are you working from??

**Comment by GenWilhelm** [comment]
This sounds like you are using an older version of the file. Please confirm you are using Renegades & Heretics v2000 (or higher).

If you are seeing more than one catalogue for Renegade & Heretics please refresh your data, as these are older, obsolete files.
https://battlescribe.net/?faq=refreshData
