### ISSUE TITLE
Space Wolves - Thunderwolf Cavalry Issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#2996]
**File:** Space Wolves - Codex.catz

**BattleScribe version:** 2.00.09

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Thunder wolf Calvary when you select a storm shield for one Calvary it puts a shield on the other Calvary in the unit. The unit leader works fine but the other calvary when you add a shield is affected.

**Comment by FarseerVeraenthis** [comment]
Please update your data files because this has been fixed, at least on Android for file version 2014.
Refer to #2971
