### ISSUE TITLE
Eldar - Corsairs - Force Org Chart Missing

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#2998]
**File:** Eldar - Corsairs (2015).catz

**BattleScribe version:** 2.00.13

**Platform:** Android

**Dropbox:** No

**Description:** Cannot find corsairs alternate force org chart. The individual components can be found in a formation detachment, i just cant find the whole chart.

**Comment by FarseerVeraenthis** [comment]
When creating a roster you need to use the EC Corsair Fleet Raiding Company [FW] detachment. This includes all the options per the Force Org Chart from IA 11: Doom Of Mymeara.
