### ISSUE TITLE
Astra Militarum: Codex

### ISSUE THREAD

**Issue by Stegadons** [BSData/wh40k-7th-edition#30]
Incorrect points cost for Bullgryn unit entry (equals cost for one Bullgryn), when added to roster cost goes up to reflect cost for unit.

**Comment by ghost** [comment]
That's not an error, it's just the way the program displays things. When you select the unit, it shows the correct points cost.

**Comment by Stegadons** [comment]
Actually it's the way catalogue are made (program just displays catalogue data) It can be made to display correctly even in selection pane.
We can discuss if changes are needed or we can leave it as it is (I don't care much, since I don't play Guard, just sometimes I want things to be done correctly)

**Comment by ghost** [comment]
Where a unit contains an entry group with 'min selections = 2' for example, but all the individual entries in that group are 'min selections = 0', then the Roster Editor left-hand column does not include the cost of the selections from that entry group to the points value it displays. When you add the unit to you roster, then the points cost of the default selection is added to your total. It's the way the program works.
To have it show the points you suggest, you would need to separate the troops from their weapons, then add a 'set-min-selections-if' modifier to the weapons. Alternatively, you would have to nest the weapon option within the troops. The former means doubling the number of selections a user has to make when building their roster, the latter adds nested entries which can be frustrating for mobile users.
The file was designed to minimise click-count, warning messages and the rest to make it more end-user friendly.

**Comment by Stegadons** [comment]
Ok, you made the point.
