### ISSUE TITLE
Grey Knights: missing profiles for basic members

### ISSUE THREAD

**Issue by Xianator** [BSData/wh40k-7th-edition#300]
When doing a mouse-over and in the roster summary the unit stat lines for models that are not characters are not being displayed.  This may be how things are handled as standard, but it appears to be a bug to my sensibilities.  

I would expect that the unit should provide two stat lines for each unit - one for the basic model and one for the character.  I would expect that the roster profile summary would include the stat line for the standard model in each unit as well.  Perhaps single-spaced above the unit character.

Eg: When doing a mouse-over on the Interceptor Squad, only the stat line for the Justicar is listed.

---

As an aside: on the subject of mouse-over pop ups, is there a way to toggle/disable these pop ups in BattleScribe itself?  They can be very intrusive when list building and get in the way.  Possibly add displaying the unit summary as a right-click option for the unit? If there is one feature I'd like to see, this would be it.  The pop-ups are super handy when you want to see them, but the rest of the time they are very annoying!  :)

**Comment by amis92** [comment]
That's indeed a bug. I'll fix it immediately.

As for **pop-ups**: no way to disable them. For a feature requests, use [BattleScribe's UserVoice](http://battlescribe.uservoice.com/forums/55066-general).

**Comment by Xianator** [comment]
That link didn't seem to work...

**Comment by amis92** [comment]
Link corrected. Sorry. :)
