### ISSUE TITLE
CSM - Tzaangor Warhead - possible to Compress print roster?

### ISSUE THREAD

**Issue by Drachnyen** [BSData/wh40k-7th-edition#3005]
Hello,

Currently, every single models of Zaangors are listed On a separate line.  Making the printed version of the roster combersome.  (See screenshot)

Is it possible to reduce the number of lines? Ex: Zaangors x10 

![img_1350](https://cloud.githubusercontent.com/assets/16340056/21016196/bb4e10ae-bd32-11e6-8778-bac24e2c137b.PNG)

**Comment by cartag** [comment]
Already fixed in upcoming release

**Comment by Drachnyen** [comment]
Thanks @cartag
