### ISSUE TITLE
Renegades and Heretics CAD - Arch Demagogue

### ISSUE THREAD

**Issue by radionausea** [BSData/wh40k-7th-edition#3006]
Version 2005 
Android

I'm not able to make the arch Demagogue my warlord nor select a devotion.
I've tried using both of the imperial armour variants with the same issue

**Comment by GenWilhelm** [comment]
Because of how devotions work in the Renegades & Heretics faction, there is a separate entry for if you want your Arch Demagogue to be your Warlord, called "Renegade Command Squad (Warlord)".

It should be available to any detachment except the Allied Detachment.

**Comment by radionausea** [comment]
It is, yes, thanks for that
