### ISSUE TITLE
Grey Knights: Dreadknight profile modifier for teleporter

### ISSUE THREAD

**Issue by Xianator** [BSData/wh40k-7th-edition#301]
When adding the Personal Teleporter upgrade, the unit type should become Jump Monstrous Creature (Character).

**Comment by amis92** [comment]
1. Please don't contain everything in title, it's nonsense. Title should be as short as possible.
2. Great catch, thank you! :)

**Comment by Xianator** [comment]
Thanks.  I'll keep bug titles short and sweet going forward.
