### ISSUE TITLE
Chaos Space Marines - Raptor Talon Formation Missing

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3011]
**File:** Chaos Space Marines - Codex.catz

**BattleScribe version:** 2.00.09

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** I apologize if this is a duplicate. It appears that the Raptor Talon formation is not available in the lformation detachment for CSM

**Comment by FarseerVeraenthis** [comment]
Is this a similar issue #2974 ??
