### ISSUE TITLE
Chaos Daemons - iOS fails to create Pandamoniad Roster

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3012]
**File:** Chaos Daemons (40K) - Codex.catz

**BattleScribe version:** 2.00.09

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** Trying to made a daemons list in the pandamoniad, fails to make the roster

**Comment by FarseerVeraenthis** [comment]
Is this linked to #2979 ??
