### ISSUE TITLE
[QA Test] Chaos Space Marines

### ISSUE THREAD

**Issue by GenWilhelm** [BSData/wh40k-7th-edition#3016]
Note: This is a QA test for an upcoming release, NOT the currently available catalogue.
-
- [x] Selecting Alpha Legion does not move Chosen to Troops.
- [x] Selecting Black Legion does not move Chaos Terminators to Troops.
- [x] Selecting Death Guard in Force Options does not force you to take a Mark of Nurgle.
- [x] Selecting Death Guard does not move Plague Marines to Troops.
- [x] Selecting Death Guard does not allow you to take a Plague Colony formation.
- [x] Selecting Emperor's Children does not force you to take a Mark of Slaanesh.
- [x] Selecting Emperor's Children does not move Noise Marines to Troops.
- [x] Selecting Emperor's Children does not allow you to take a Kakophoni formation.
- [x] Selecting Iron Warriors does not move Obilterators and Mutilators to Troops.
- [x] Selecting Night Lords does not move Raptors to Troops.
- [x] Rubric Marines are available as Troops without selecting Thousand Sons/Sorcerer with MoT.
- [x] Selecting Word Bearers does not move Possessed to Troops.
- [x] Selecting World Eaters does not move Khorne Beserkers to Troops.
- [x] Plague Colony does not enforce 1 Lord or Unique Character.
- [x] Noise Champion does not have a boltgun, Noise Marines do not have bolt pistols.
- [x] The Hounds of Abaddon (see comment).
- [x] Black Legion Speartip should have The Bringers of Despair, and not have Lords of the Black Crusade or Daemon Engines.
- [x] Black Crusade Detachment is showing Core options from other detachments, and is missing several Auxiliary choices.
- [x] Legions Detachments should not have Daemon Engines as Auxiliary.
- [x] Iron Warriors' Strongholds of Chaos is missing almost all fortifications and has no minimum constraint.
- [x] World Eaters Butcherhorde should have Trinity of Blood as Auxiliary.
- [x] Tzaangors are not collective and have a typo in their weapon replacements.
- [x] Exalted Sorcerer is not available as HQ.
- [x] Warpbreacher's profile has a typo in the last line.
- [x] Bolts of Ecstatic Vexation's profile has a typo in the name.

**Comment by skonk** [comment]
Black Legion - The Hounds of Abaddon formation, all models that can have Mark of Khorne must take it but it becomes free. This has a note saying it won't be implemented until BS 2.0 and is still charging for the mark.

**Comment by skonk** [comment]
Black Legion - Lords of the Black Crusade is showing as a Command option as well but this is not an option that appears in this detachment (Lord of the Legion is also there and is correct).
