### ISSUE TITLE
Space Wolves - Wolf Guard Terminator Weapon Selection Issues

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3017]
**File:** Space Wolves - Codex.catz

**BattleScribe version:** 2.00.13

**Platform:** Android

**Dropbox:** No

**Description:** Wolf Guard Terminators - having added the unit, error message stated too many selections from weapons. Had not yet made changes. upon check error caused by grouping terminators, coffee believes making weapon selection for one model. However also receive error when less than ten weapon selections made.

**Comment by IronWulfen88** [comment]
im having that same issue
