### ISSUE TITLE
Tyranids - Wrecker Node Formation Bug

### ISSUE THREAD

**Issue by Randobar** [BSData/wh40k-7th-edition#302]
The Wrecker Node Formation should include 3 Broods of Carnifexes, not only 1

**Comment by Randobar** [comment]
2nd Error. Tyrant Node has to include 3 Guards, not only 1.

**Comment by Randobar** [comment]
Did the fix but i guess someone needs to grant me the rights to commit it directly.

**Comment by amis92** [comment]
Yeah, that would be correct. Inviting you now.

**Comment by Randobar** [comment]
Thanks. And done...

still not 100% sure how to use git but i think i did not mess up to much.

**Comment by amis92** [comment]
Good job, it seems.
