### ISSUE TITLE
Eldar Craftworlds - Aspect Host

### ISSUE THREAD

**Issue by GenWilhelm** [BSData/wh40k-7th-edition#3027]
The Aspect Host formation is not enforcing it's restriction that each unit must include an Exarch.

**Comment by FarseerVeraenthis** [comment]
What do you mean by not enforcing it? On Android it throws a validation error if an exarch is not included, until the double default issue is fixed I don't think default selection is a step forward...

**Comment by GenWilhelm** [comment]
I'm not getting any errors on Android or Windows.
On a side note, Dire Avenger Shrine has the same bug.

**Comment by FarseerVeraenthis** [comment]
Firstly, I'm on file version 2010, I assume the same for you?
Secondly, is this as part of a Craftworld Warhost or a Formation Detachment??
As far as I can see, the validation error is thrown in the Warhost but not the Formation for some reason...

**Comment by GenWilhelm** [comment]
Yep, v2010.
I was using the Formation Detachment. The fact it's working for one force and not the other is very telling. It's probably checking for an instance of a link, rather than an entry.

**Comment by FarseerVeraenthis** [comment]
Cheers @GenWilhelm that should make it easier to figure out when I look at the file :smile:
