### ISSUE TITLE
Eldar Formations (broad issues, mostly The Doom of Mymeara-related)

### ISSUE THREAD

**Issue by Owlsbane** [BSData/wh40k-7th-edition#3028]
Eldar cat v.2010
BS v2.00.05
Windows 10

Under Formation Detachments force organization I found the following issues:
1 - Wraith Construct. This is not a stand-alone Formation but always part of an Eldar Craftworld Warhost as found in Codex Eldar: Craftworld. It can already be found as such under the Eldar Craftworld Warhost force organization in BS.
2 - Pale Court Battlehost (FW) ~~and Mymeara Guardian Battlehost (FW)~~*. These are also not stand-alone Formations but can only be taken as core of a Battlehost. They can already be found as such under the Eldar Craftworld Warhost force organization in BS. This is different from the Guardian Battlehosts that can be found as stand-alone Formations in the Codex Eldar: Craftworld. The Doom of Mymeara however does not list its Battlehosts as stand-alone Formations, so...
3 - Cloudstrike Squadron is not a Formation but a special rule that comes into play when you choose to take three Falcons in one squadron/unit.

Now for a couple of Formations that all suffer from the same issue. I'll write the first one out in full, then list the other Formations that share this issue. Look at Skyhunters Squadron (FW) for how it's supposed to be.
4 - Fires of the Phoenix (FW). Formation states "2 Eldar Phoenix Bombers" and "All Phoenix Bombers bought as part of this Formation form a vehicle squadron and must take the same upgrades", but in BS this is interpreted as 2 squadrons/units of Phoenix Bombers.
5 - Fist of Vaul (FW). 2-3 Warp Hunters.
6 - Khaine's Hawks Squadron (FW). 2-3 Eldar Nightwings.
7 - Wasp Phalanx (FW). 3-6 Wasp Assault Walkers. I think this Formation best illustrates why these Formations can't be talking about units but are talking about individual models.

Thanks for all the hard work people have been putting into these databases and of course to Jon for creating BS itself. You guys are wonderful!

* Crossed out Mymeara Guardian Battlehost because of this little piece of confusion on page 177 of The Doom of Mymeara: "The following Formation details the typical structure of a Mymeara Guardian Battlehost and may be used as a Core choice in any Warhost constructed using the rules presented in _Codex: Craftworlds_, **as well as in other armies using the standard rules for Formations**." Bold added for emphasis. My bad.

**Comment by FarseerVeraenthis** [comment]
I'll have a look and see what's going on...

**Comment by FarseerVeraenthis** [comment]
Time for a checklist;

- [x] "Wraith Construct" is not a formation. Should not appear when building a Formation Detachment.
- [x] Pale Court Battlehost can only be used within a Craftworld Warhost Detachment. Should not appear when building a Formation Detachment.
- [x] "Cloudstrike Squadron" is not a formation.
- [x] Fires of the Phoenix formation construction incorrect.
- [x] Fist of Vaul formation construction incorrect.
- [x] Khaine's Hawks Squadron formation construction incorrect.
- [x] Wasp Phalanx formation construction incorrect.

I'll try to get these done this week.

**Comment by FarseerVeraenthis** [comment]
The Cloudstrike Formation is an Apocalypse Formation of 3-5 Falcons.
Hilariously, it is also a special rule for a squadron of 3 Falcons from Codex: Eldar Craftworlds....

**Comment by Owlsbane** [comment]
I was not aware, I don't own the Apocalypse book and I did not expect that! One down ;)
