### ISSUE TITLE
Chaos Space Marines - Artifacts

### ISSUE THREAD

**Issue by galvorbak99** [BSData/wh40k-7th-edition#3031]
**File:** Chaos Space Marines - Codex.cat v.2009
**BS Version:** v2.00.05
**Platform:** PC
**Dropbox:** No
**Issue:** Chaos Lords and Daemon Princes are unable to take both an artifact weapon and a non-weapon artifact.

**Comment by cartag** [comment]
Working as intended given updated wording in Traitor Legions.

**Comment by Drachnyen** [comment]
GW final FAQs also confirms this. 

"Q: How many relics/artefacts can a single model be equipped with?
A: A model can only be given a single relic or artefact unless specifically noted otherwise."

https://www.warhammer-community.com/2016/11/22/warhammer-40000-rulebook-final-faq/
