### ISSUE TITLE
Enhancement: Add Source to Formations

### ISSUE THREAD

**Issue by Viper666-Qc** [BSData/wh40k-7th-edition#3032]
Could it be possible to add the Source Reference for every formation?
It would help a lot in order to find them quickly on paper/digital now that almost every armies have multi-source contents (codex, codex supplement, campaign book, expansion book, dataslate, white dwarf exclusive datasheet, bundle exclusive datasheet)... (a bit like Blood of Kittens Codex Compendium)

**Comment by amis92** [comment]
@Viper666 Great idea, but could you list specifically which catalogues are missing? Engaging each and every one maintainer will be difficult :)

**Comment by Viper666-Qc** [comment]
well none of the catalogue seem to have the Formation source reference.....some get references for Wargear, units or rules but not for Formations

**Comment by Viper666-Qc** [comment]
the source of the formations & detachment should be right next to their name actually....and not optional like the other book references

**Comment by FarseerVeraenthis** [comment]
While that sounds like a great idea, the names would become either very long, or include an abbreviation that could be tricky to unravel...
As a simple example, the Eldar Craftworld Warhost detachment name could become; "E Craftworld Warhost - C:EC" or "E Craftworld Warhost - Codex: Eldar Craftworlds". If you didn't know the range of books (particularly when you consider Forgeworld) very well, the abbreviations would be useless and the text extremely long...

I agree that it is helpful to include it somewhere within the file, but I disagree it should be in the title of the particular formation / detachment. 
Also, to be completely rigidly correct, you should already own the book that contains the formation you want to use in Battlescribe, so the reference shouldn't be essential...

**Comment by alphalas** [comment]
I'm with farseer on this - direct referencing is hardly essential, and especially unwieldy and impractical to be put in the name of the formation.

**Comment by GenWilhelm** [comment]
I agree with the above, editing the name of the formations is too cumbersome.

However, the book reference could be included just below the name of the formation (where the rules currently appear), which is already possible with stylesheets. Perhaps it's a feature we could request - to have that option on the roster viewer.

If this becomes a thing it would require us to update the appropriate attributes in each formation so they all have book and page references.

**Comment by Viper666-Qc** [comment]
I didn't mean "directly" in the name of the formation in the app...
but directly under/after the name in print layout

**Comment by amis92** [comment]
Ok, little self-advertising here: https://battlescribe.uservoice.com/forums/55066-general/suggestions/6312936-enhance-the-role-of-book-field

That could help very well with what you guys point out as a problem: imagine Books as declared entities. They could have more fields, like release year, abbreviation, full title, publisher etc etc., and you could include a list of used books (with abbreviation-full name dictionary).

Then in the roster only abbreviations could be used.

Upvote please? :D

**Comment by FarseerVeraenthis** [comment]
per the discussion here and on Gitter, catalog owners are reminded to try and include the source when adding formations to CAT's.
