### ISSUE TITLE
Chaos Space Marines - Crimson Slaughter Formations & Relics Missing

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3039]
**File:** Chaos Space Marines - Codex.catz

**BattleScribe version:** 2.00.05

**Platform:** Windows

**Dropbox:** No

**Description:** I was trying to build a load out of Crimson Slaughter, and was unable to find their formations and relics.
In googling around for longer than I care to admit, all I found several articles that made it sound like that CSM supplements such as theirs were all rolled together, possibly under the black legion.
Are the Crimson Slaughter somewhere in this file? Do you where to fine their data?
Thank you

**Comment by GenWilhelm** [comment]
Under "Uncategorised" add one "Force Options (Supplement options here)".
Then, in the new entry, select "Crimson Slaughter" from the list of supplements.
