### ISSUE TITLE
Anvillus / Kharybdis pattern dreadclaw drop pod in 40k CSM

### ISSUE THREAD

**Issue by direhippo** [BSData/wh40k-7th-edition#304]
My understanding, at least according to the Forge world beta documentation, was that the anvillus and dreadclaw drop pods were supposed to be able to be used as Fast Attack and Heavy Support selections, respectively, in the Chaos Space Marines Army List in addition to their HH slots. If so, could these also be added to the CSM files for selection, much as the the other forge world entries have been added?

**Comment by senpai514** [comment]
The Kharybdis yes most definitely will be added. However I can not add the Anvillus pattern with out seeing a datasheet classifying it for 40K use. I know it was said it was going to get playability for 40k but need to see it in order to add it.
