### ISSUE TITLE
Skitarii - Skitarii Maniple Warlord USR Not Showing

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3043]
**File:** Skitarii - Codex.catz

**BattleScribe version:** 2.00.05

**Platform:** Linux

**Dropbox:** No

**Description:** The Skitarii Maniple confers the 'Prefered Enemy' USR to the warlord (if the warlord is part of the detachment). This is not represented in the roster.

**Comment by alphalas** [comment]
As far as I know, There is no good way to an implement this in BS

**Comment by cartag** [comment]
If you have a Warlord entry that is referenced, link to Preferred Enemy USR, set to hidden, and unhide if Ancestor instance of Skitarii maniple.

**Comment by alphalas** [comment]
Can you attach rules to the warlord selection? So if I have an Inqisitor as my WL, he would then get that?

**Comment by alphalas** [comment]
Oh, I completely misread that - don't mind me
