### ISSUE TITLE
Eldar - No Iyanden Supplement

### ISSUE THREAD

**Issue by Miyth** [BSData/wh40k-7th-edition#3045]
Adding this as a note since this is the most readily updated data out there! 

Although the Iyanden supplement has been errata-ed to 7th edition, no iyanden wargear is available.

**Comment by FarseerVeraenthis** [comment]
Was the data there before, but has gone missing during the transfer to BS2.0??
I'll try to find the Iyanden Book and see what's missing...

**Comment by Miyth** [comment]
Cool, thanks!

I don't think the iyanden data was ever added. I've seen similar requests made as bug reports on BattleScribe incorrectly asking for the data back in July -- just looks like nobody followed through on submitting a request here.

**Comment by efalsken** [comment]
At the time when I did the BS data files for Codex Craftworlds, Iyanden was not compatible with the new codex and the GW FAQ had not yet clarified the position. There are a few small irregularities or incompatibilities and a few points of ruling that will need to be argued and clarified. Battlescribe team has chosen to support current codex releases only. Iyanden is not available on the GW web store and is no longer in distribution and as such is no longer supported by this battlescribe team.
