### ISSUE TITLE
Imperial Knights - Missing Info on Knight Selections

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3046]
**File:** Imperial Knights - Codex (2015).catz

**BattleScribe version:** 2.00.13

**Platform:** Android

**Dropbox:** No

**Description:** Missing knight info on unit selections.  I am unable to assign specific units

**Comment by Thairne** [comment]
I don't get it. 
What exactly seems to be the problem?

**Comment by Thairne** [comment]
No reply from Anon, closing.
