### ISSUE TITLE
data roster issues

### ISSUE THREAD

**Issue by IronWulfen88** [BSData/wh40k-7th-edition#3048]
Ever since I got the new battlescribe a pop up has shown up no matter what army saying there are problems with one or more files needed for the Rosters. Even on rosters where I have found no issues when checking using my codex. Is this normal?

**Comment by cartag** [comment]
Can you screenshot it so we know what the error is?

**Comment by IronWulfen88** [comment]
![15420775_1269239733155912_1760511401190687682_n](https://cloud.githubusercontent.com/assets/22039355/21128618/93bd528e-c0ca-11e6-93ae-87df6d3c34fb.jpg)

**Comment by IronWulfen88** [comment]
that is what shows up everytime no matter the list I make.

**Comment by cartag** [comment]
That happens even if you create a new list in the app right then?

**Comment by IronWulfen88** [comment]
yep. I just started making a blood angels list for a future army I am gonna build and it comes up.

**Comment by IronWulfen88** [comment]
and it comes up every time I open one of my rosters

**Comment by GenWilhelm** [comment]
When was the last time you purged and re-downloaded the data files?
If it was a while ago, you may still have legacy files that are causing this warning.

**Comment by FarseerVeraenthis** [comment]
One last question - are you linked to Dropbox??

**Comment by IronWulfen88** [comment]
I purged last night and redownloaded the datta files. adn I am not sure if I am linked to drop box. How should I check fro that on my samsung tab E?

**Comment by FarseerVeraenthis** [comment]
to check if you're linked to DropBox, tap the three horizontal lines to access your data links, if you're not linked to dropbox there will be a little dropbox symbol next to the refresh symbol. When you are linked I don't think the symbol shows but I had to unlink because it is dog slow at the moment...

**Comment by IronWulfen88** [comment]
okay I will take a look
