### ISSUE TITLE
Space Wolves - Delayed Roster Creation, Error On Opening

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3053]
**File:** Space Wolves - Codex.catz

**BattleScribe version:** 2.00.09

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** When opening or creating a new roster with space wolves data it takes forever to open and then it says there is an error with the data. This does NOT happen with other army data like astra militarum

**Comment by alphalas** [comment]
which version of the sw data are you trying to load?

**Comment by FarseerVeraenthis** [comment]
Space Wolves just had a major update. Please refresh your data and try again because this shouldn't be a problem now.
