### ISSUE TITLE
Eldar Craftworlds - Data File Error When Creating Roster

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3058]
**File:** Eldar Craftworlds - Codex (2015).catz

**BattleScribe version:** 2.00.13

**Platform:** Android

**Dropbox:** No

**Description:** When creating Eldar Craftworlds - Codex roster there is message poping up: "There are problems with one or more of data files needed for this roster. You should notify the author of the data files to let them know about the issue". So i'm notifying you. No profiles for many weapons and equipment.

**Comment by FarseerVeraenthis** [comment]
What file version are you using?

**Comment by FarseerVeraenthis** [comment]
I just created a new CAD list and had no problems.
File Version v2012, Battlescribe Version 2.00.14 on Android.
Please ensure you have updated Battlescribe and are using the latest data.
