### ISSUE TITLE
Warhammer40K - problems with data files

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3059]
**File:** Warhammer40K.gstz

**BattleScribe version:** 2.00.13

**Platform:** Android

**Dropbox:** No

**Description:** Whenever I try to make a list or view a old list it says "there is a problem with one or more of the data files for this roster. You should notify the author of the data files to let them know about this issue.
You can continue but you may find that you are missing options or that some things won't work as expected".   What happens is when i go to view my created list it does not show any of the units information. Just names and points cost.

**Comment by FarseerVeraenthis** [comment]
When you say "old list" do you mean from the previous version of battlescribe? If so, those files don't work in the new version of battlescribe...

**Comment by IceJaxson** [comment]
My apologies for not being more specific. What I ment by old list was a list I had already made in the new version a few days ago.

**Comment by FarseerVeraenthis** [comment]
Which army exactly? It might be a case that the data was updated and it broke your list...

**Comment by IceJaxson** [comment]
I went through each army in the Warhammer 40,000 list and each army gave me the same message Everytime i tried to make a list with it.

**Comment by FarseerVeraenthis** [comment]
Have you purged your data? i.e. deleted all the data files and re-downloaded them??

**Comment by IceJaxson** [comment]
Multiple times

**Comment by FarseerVeraenthis** [comment]
Since this doesn't seem to be a global problem, that sounds like an installation issue or something... Battlescribe has been updated recently, is it still a problem? 
Could you post a screen shot??

**Comment by IceJaxson** [comment]
It is still a issue yes. How would I post a screen shot exactly? Do I have to be on a actual computer?

**Comment by cartag** [comment]
Posting them to imgur may be the easiest solution.

**Comment by FarseerVeraenthis** [comment]
Are you still getting the error message?
Could you post a screenshot?

**Comment by IceJaxson** [comment]
Yes I'm still getting the message. Sorry for not responding. I will post a screen shot soon of the error message and what exactly happens

**Comment by FarseerVeraenthis** [comment]
Has this fixed itself yet?

**Comment by IceJaxson** [comment]
Yes it has. Forgive me for taking so long to respond. It was not a error on your part. The App was in low memory mode which made nothing appear when I would go view the list I made. My apologies for the inconvience 

    On Wednesday, January 4, 2017 11:41 PM, Simon Porter <notifications@github.com> wrote:
 

 Has this fixed itself yet?—

**Comment by FarseerVeraenthis** [comment]
That's cool 😎 I'm just glad it's fixed and working properly now :smile:
Thanks for the update, always nice to know when an issue can be closed because it has been fixed!
