### ISSUE TITLE
Codex: Eldar Craftworlds and Kill Team Detachment request

### ISSUE THREAD

**Issue by Owlsbane** [BSData/wh40k-7th-edition#3061]
I know there are limitations to implementing KT lists in BS, but I figured it can't hurt to ask the following:

When choosing to edit a KT Detachment for Eldar Craftworld, I get to choose from the Elites, Troops and Fast Attack entries since those are the only ones allowed according to KT rules. Would it be possible to further limit choice within those categories?

So, you are not allowed to take Flyers in KT, all Flyers could be removed from Fast Attack. Also, combined F/S/R armour can't be more than 33 points. A Wave Serpent has 34 so it should be removed as well.

Hmm, that's it, really.

**Comment by FarseerVeraenthis** [comment]
*waves hand sheepishly*
My fault, I didn't hide them when I added the links to Kill Team Specialists.
Next time I'm working on the CAT I'll fix this issue as well...
(Can anyone tell I'm a bit new at this...?)

**Comment by Owlsbane** [comment]
Heh, doing better than I would. All effort is much appreciated!
