### ISSUE TITLE
Death Guard mark of nurgle and Veterans of the Long War

### ISSUE THREAD

**Issue by Nibodhika** [BSData/wh40k-7th-edition#3063]
As stated in the rules of the Forces of the Death Guard units that can take the Mark of Nurgle MUST do so, I had to manually assing the mark of nurgle to my forces.

But the biggest problem here is "All units that can do so must be upgraded to Veterans of the Long War, at no additional points cost.", Some units (Like The Dark Apostole of The lost and the Damned) already have this free (but not pre-selected), but others like the Chaos Lord or Chaos Space marines in the Chaos Warband still have a cost of 5pts to get the Veterans of the Long War trait.

**Comment by GenWilhelm** [comment]
Have you selected "Death Guard" from the "Force Options" entry?

**Comment by radionausea** [comment]
It's definitely free cocktails if you select Death Guard from Force Options.

I do agree that having the mark and VotLW preselected where it's a mandatory choice anyway would be a huge help.

**Comment by alphalas** [comment]
It was a concious decision made to bring it in line with c:SM datafile since now c:csm has almost as many options

**Comment by Nibodhika** [comment]
Sorry (still getting used to Battlescribe), I hadn't selected the Death Guard force option, and since the Dark Apostile had free the veterans of the long war I tought it was an issue with the others (but just checked the codex and Dark Apostiles can pick Veteran of the long war for free).

**Comment by radionausea** [comment]
(you can tell it's Christmas time when my phone automatically inserts cocktails after the word free)
