### ISSUE TITLE
Space Wolves - Wolf Guard Terminators Missing Heavy Flamers

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3066]
**File:** Space Wolves - Codex.catz

**BattleScribe version:** 2.00.05

**Platform:** Windows

**Dropbox:** No

**Description:** Space Wolves Wolf Guard Terminators do not have the option of taking Heavy Flamers only option for Assault Cannon

**Comment by GenWilhelm** [comment]
Wolf Guard Terminators do not have access to Heavy Flamers.
Please check the most recent codex.
