### ISSUE TITLE
Space Marines  - FW LoW shown as Apocalypse-only

### ISSUE THREAD

**Issue by francoisbeaulieu** [BSData/wh40k-7th-edition#3067]
iOS
BS2.00.09
SM Codex v.2008

I notice that the Fellblade, Cerberus, Typhon and Thunderhawk are shown as (Apoc) only choices under Lord of War. I realize that showing FW and Apoc choices are controlled by the same roster option and this may have been done for expediency, but I think it may lead to misunderstanding as, according to the official errata for IA2, they are legal selections in non-apocalypse games:

https://www.forgeworld.co.uk/resources/fw_site/fw_pdfs/Warhammer_40000/Imperial_Armour_Volume_Two.pdf

Can this be made clearer in the roster?

**Comment by francoisbeaulieu** [comment]
The Thunderhawk Gunship is also allowed for Space Marines, as per the Escalation book.

--
François Beaulieu (iPhone)
(514) 667-0691 x2061

**Comment by francoisbeaulieu** [comment]
@FarseerVeraenthis, you missed one. Do you need me to open a new issue?

**Comment by FarseerVeraenthis** [comment]
The pdf linked previously does not include the gunship, only the transporter...

**Comment by francoisbeaulieu** [comment]
That's correct, the Forgewold rules were expanding upon the escalation rules, which state:

![image](https://cloud.githubusercontent.com/assets/12718495/21294148/61ef5444-c504-11e6-91f9-f14b3b1cc310.jpeg)

**Comment by FarseerVeraenthis** [comment]
Righto then :-) I don't have escalation, so thanks for the screen grab :-) next time I'm in the CAT I'll get this fixed!
Cheers!
