### ISSUE TITLE
Space Marines - Bikes as troop choice

### ISSUE THREAD

**Issue by francoisbeaulieu** [BSData/wh40k-7th-edition#3069]
iOS
BS2.00.09
Codex v.2009

Selecting a space marine bike for an HQ no longer unhides bikes as a troop choice in a CAD.

**Comment by FarseerVeraenthis** [comment]
This is related to #2973 
I was looking at it last night and because there are so many different options with different chapter tactics and so on it is quite complicated in the CAT... I'll have another go and see if I can figure it out :smile:
