### ISSUE TITLE
Adepta Sororitas - Double Entry on Default Selections

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3071]
**File:** Adepta Sororitas.catz

**BattleScribe version:** 2.00.09

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** The Squad are showing double bolt pistols and bolter, whenever squad is selected.

**Comment by FarseerVeraenthis** [comment]
I think this is a Battlescribe Bug although @alphalas can have a nose and see if it is anything in the data...

**Comment by Owlsbane** [comment]
This was a Battle Scribe bug in 2.00.05, it was resolved in 2.00.06 and we're up to 2.00.07 now. I encountered it while checking SoB for the KT rules, then it disappeared when I updated my BS to 2.00.06.

**Comment by alphalas** [comment]
I'm still seeing it in iOS interestingly enough

**Comment by amis92** [comment]
@alphalas is this resolved on iOS too now?

**Comment by alphalas** [comment]
Should be after the release I made last night
