### ISSUE TITLE
Chaos Space Marines - Iron Warrior Grand Company Issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3072]
**File:** Chaos Space Marines - Codex.catz

**BattleScribe version:** 2.00.50

**Platform:** Windows

**Dropbox:** No

**Description:** Isue not resolved in  V2010
missing Favored of Chaos formation in Iron Warrior Grand Company (p89 codex supplement traitor legions)

**Comment by cartag** [comment]
The hell? I thought I fixed that...
