### ISSUE TITLE
Chaos Space Marines - Vrosh Tattersoul Lost in the Warp

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3073]
**File:** Chaos Space Marines - Codex.catz

**BattleScribe version:** 2.00.14

**Platform:** Android

**Dropbox:** No

**Description:** Hello. After update 2.00.14 vrosh tattersoul does not appear in hq choices for chaos space marines. I used to select chaos space marines then select hidden units and dataslates and then vrosh would appear as an hq choice. Thank you in advance for your help and this app is great

**Comment by FarseerVeraenthis** [comment]
CSM had a big update the other day... You probably need to select the correct "Chapter Tactics" to have him appear...
@cartag this one for you I think :smile:

**Comment by cartag** [comment]
Make sure you have options selected like in the image below and you'll see him. He is only allowed in Crimson Slaughter or Vanilla CSM forces. Any traitor legion limits what unique characters are allowed. He's not allowed in any of them.

![image](https://cloud.githubusercontent.com/assets/4388344/21282037/9f24c102-c3ae-11e6-9ecc-d14297936373.png)
