### ISSUE TITLE
C:IA - Add Faction Aeronautic Imperialis

### ISSUE THREAD

**Issue by alphalas** [BSData/wh40k-7th-edition#3076]
- [x] Add Force "Imperial Navy Section"

- [x] Add Unit "Officer of the Fleet"

- [x] Add Unit "Valkyries"

**Comment by Viper666-Qc** [comment]
I think you should add those Forgeworld units to the Aeronautica Imperial;is (Imperial Navy) Faction. Forgeworld always identified them as Imperial navy units and separated them from the Imperial Guard Faction in every on their IA books. 

Thunderbolt Fighter
Lightning Strike Fighter
Aquila Lander
Arvus Lighter
Vulture Gunship
Vendetta Gunship
Valkyrie Sky Talon Transport
Marauder Bomber
Marauder Destroyer
Avenger Strike Fighter

**Comment by alphalas** [comment]
Until FW states that, in an official document, I'd rather not.
