### ISSUE TITLE
C:IA - Deathwatch

### ISSUE THREAD

**Issue by alphalas** [BSData/wh40k-7th-edition#3079]
- [x] Add Force "Deathwatch Kill Team"

**Comment by Flashpoint-** [comment]
Has Codex Imperial Agents been added to Battlescribe yet?

**Comment by Thairne** [comment]
We are in the progress of doing just that.

**Comment by alphalas** [comment]
We're working on it - it's all additions to existing cats, save for Areonautica and Astra Telepathica- sisters, GK, and assassins are done - I think @farseerveraenthis has been busy with Eldar bugs - I'm doing telepathica, aeronautic, then inq.

**Comment by Flashpoint-** [comment]
Cool thanks everyone is doing a great job thanks for all the hard work you guys & gals do Happy Holidays!

**Comment by FarseerVeraenthis** [comment]
Deathwatch has just been updated :-)
