### ISSUE TITLE
Add Sevrin Loth for red scorpions: Space Marines - Codex.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#308]
in HQ choises, Magister Sevrin Loth of the Red Scprpions is missing

**Comment by Kangodo** [comment]
Doesn't he have new rules in IA4-second edition?

**Comment by ghost** [comment]
Nope. There're new rules for Haas and the 'Captain' version of Culln, as well as a new Dreadnought and some upgrades you can take instead of relic blades. The other Red Scorpions characters & things stay the same.

**Comment by senpai514** [comment]
Solomon Lok was the only character in IA 4 when it first came out. I think the majority of them are all from the badab war books. it would be nice to see the new book though
