### ISSUE TITLE
C:IA - Grey Knights

### ISSUE THREAD

**Issue by alphalas** [BSData/wh40k-7th-edition#3080]
- [x] Add Force "Deamonhunter Strike Force"

**Comment by khelemvor** [comment]
Greetings. First time trying to get involved in this, but I tried adding the Daemonhunter Strike Force on my computer. It's my first attempt at such a revision, and I'm currently treating the 1 Troop or 1 Fast Attack as an exclusive or which I can change if you'd want. I'm not sure how to go about submitting the revisions to you though. Any guidance on the next step would be wonderful, and I look forward to hopefully helping if I can.
Thanks,
Inquisitor Ezekiel Kaine, Ordo Malleus

**Comment by alphalas** [comment]
Actually, I have a file open currently to add the force, if you refer to #3080 - I appreciate the effort though.

**Comment by FarseerVeraenthis** [comment]
Hey @khelemvor , if you want to get involved, read the wiki here https://github.com/BSData/wh40k#overview
Although,  Alpha has this in hand I think 😀
