### ISSUE TITLE
C:IA - Inquisition

### ISSUE THREAD

**Issue by alphalas** [BSData/wh40k-7th-edition#3083]
- [x] Add Force "Inquisitorial Representative"
- [x] Create New Unit "Acolytes"
- [x] Create New Unit "Daemonhost"
- [x] Create New Unit "Jokaero Weaponsmith"
- [x] Add Formation "Inquisitorial Henchmen Warband"
- [x] Add Hidden unless Malleus unit "Grey Knight Terminator Squad"
- [x] Add Hidden unless Hereticus unit "Adepta Sororitas Battle Sisters Squad"
- [x] Add Hidden unless Xenos unit "Deathwatch Veterans"

**Comment by khelemvor** [comment]
Digital versions of Codex: Inquisition is still for sale on Games Workshop. The iOS version received an update this weekend, but no noticeable changes occurred compared to prior version. I am not sure how this will affect the removal of units such as the Razorback and the Inquisitorial Henchman Warband unit vs the formation.

**Comment by alphalas** [comment]
As I see it, since the unit is identically named to the formation, one should be considered as replacing the other.

**Comment by francoisbeaulieu** [comment]
I'm trying to find an online reference, but apparently, GW made it clear during a conference this morning that IA does not dupercede the old codexes and that no models have been removed.

**Comment by alphalas** [comment]
Well that's aggravating then if true

**Comment by khelemvor** [comment]
Additionally, by the logic that removes Servo Skulls from the Inquisitors, Rhinos, Razorbacks, and Drop Pods would no longer be dedicated transport options for Deathwatch Veterans.
(Imperial Agents was not the best designed release as it already needs FAQ and Errata)

**Comment by alphalas** [comment]
fair point - so i'll omit the deletions.

**Comment by francoisbeaulieu** [comment]
They announced a new St. Celestine model with new rules to be released in a supplement in early January, so she's defibitely not removed by IA.

**Comment by alphalas** [comment]
*mutters to self* probably so drastically changed that for our purposes she should be deleted *

**Comment by gargoyleking** [comment]
Sorry to intrude.  I have been working on bringing some stuff from the Codes.  I've been using the existing data files and while in general there aren't many issues, I have noticed one or two things that don't match.  One is the points cost for power armor on an inquisitor is 3 pts, not 8.  Not sure what else could be different, but you may want to do a separate entry for C:IA.

**Comment by alphalas** [comment]
We got it under control- creating a new separate cat will probably cause more problems then solve. We're just gunna have C:IA tags on everything and do it that way in the Inq cat.

**Comment by ThomasEll** [comment]
There's quite a lot of small differences though between the two books. Wouldn't having duplicate entries with different statlines in the same CAT file just cause even more problems?

**Comment by alphalas** [comment]
Unless people are ignoring tags or hide conditionals, no

**Comment by gargoyleking** [comment]
The easier you make it for people to find, the better.  With the new Battlescribe setup the first thing you see is which codec you're going off of.  If you hide this in something from a previous codex nobody will know that it's even gotten an update.

**Comment by alphalas** [comment]
Which is why you turn it on or off first thing, like SM or CSM

**Comment by ThomasEll** [comment]
This seems like it would be very confusing to find. Are all the formations in C:IA going to be placed into the Inquisition CAT as well? Because that seems like it would just create even more confusion. For example, why is someone going to look in the Inquisition Codex CAT file to find a formation for AdMech?

Surely it just makes more sense to have Codex: Imperial Agents as it's own CAT file, so that people who are looking to add a single formation from it can easily work out where it is going to be?

**Comment by alphalas** [comment]
We split C:IA across the native cats of the factions - if you want to discuss it further take it to Gitter plz

**Comment by hisop** [comment]
@alphalas is Force "Inquisitorial Representative" added correct to Inquisition codex? it does not seem to appear for me as an option for force org?

**Comment by alphalas** [comment]
It is on my local copy - I'm committing today (hopefully) to get it up - I didn't want to commit a incomplete cat.

**Comment by hisop** [comment]
ahh i thought that may be the case, no worries, i will look forward to it.
