### ISSUE TITLE
Space Wolves - database performance slow

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3087]
**File:** Space Wolves - Codex.catz

**BattleScribe version:** 2.00.15

**Platform:** Android

**Dropbox:** No

**Description:** Space wolves database is slow. It works slower comparely to Dark Angels or Dark Eldar. Application needs more time to open or create roster.

**Comment by FarseerVeraenthis** [comment]
Which file version are you talking about?

**Comment by WeBerion** [comment]
I use latest available version. I provided few measurements and SW database 1.5 times slower than DA

**Comment by alphalas** [comment]
It might not be latest- please provide version number of SW cat - otherwise best we can tell you is there's not really anything we can do - perhaps you need to clear cached data on your device?

**Comment by WeBerion** [comment]
Current version on my device is 2016. I'll provide more checks and update this thread.

**Comment by FarseerVeraenthis** [comment]
Linked to #3053 for i-Devices

**Comment by FarseerVeraenthis** [comment]
@WeBerion how is the performance of the latest file? The most recent version is now v2017.

**Comment by WeBerion** [comment]
@FarseerVeraenthis , seems now it indeed works faster. Thank you!

**Comment by FarseerVeraenthis** [comment]
I appreciate the thanks, but these should be directed toward @GenWilhelm for the legwork :smile:
I'm also very glad it runs faster now!
