### ISSUE TITLE
Eldar Craftworld cat v2014 - collection of issues

### ISSUE THREAD

**Issue by Owlsbane** [BSData/wh40k-7th-edition#3089]
Windows 10
Battle Scribe 2.00.07
Codex Eldar: Craftworlds (2015) v2014

Checked all units using Unbound army. Found the following issues. Some typo's, some suggestions and some bugs. Hope this helps, @FarseerVeraenthis .

Typo's:
- [x] Wildfire Special Rule: '...on a roll of 6...' should be '...on a roll of 4+...'. Also, the last 'the' is spelled as 'he'
- [x] Bel-Annath [FW]: His Psychic Disciplines description has "...the Rules of Faith...", should be "...the Runes of Faith..."
- [x] Spiritlink Special Rule: The description begins with "Spritlink...", should be... ;)
- [x] Wraithblades: Their Ghost Axe profile has a typo: Under Type, it has "Unweildy", should be "Unwieldy". Then it will also show up as Special Rule on the roster I guess
- [x] Banshee Mask: It has a typo in its description ("casuses" instead of "causes")
- [x] Swooping Hawks: Intercept special rule typo. It has "...it moved ofter that thurn...", it should read "...it moved over that turn..."
- [x] Wave Serpent: Serpent Shield has a typo, it says "...or side armouyr...", it should read "...or side armour..."
- [x] Revenant Titan [FW]: Typo in Sonic Lance's Soundquake special rule: It says "...Hull Points in the attack..." and it should read "...Hull Points if the attack..."

Suggestions:
- [x] Remove the option to choose between four different Power weapons. The Codex only states that the model can choose a Power weapon, no need to offer options that only differ aesthetically and aren't named in the Codex anyway. You can find these with the Autarch, Dire Avenger Exarch and Swooping Hawk Exarch
- [x] Striking Scorpion Exarch: His weapon selection seems a bit convoluted because it is split in two. Can they be integrated onto one page?
- [x] Why not combine Warlock Conclave and Warlock Skyrunner Conclave? Is it because you can't remove Fleet from the Skyrunner Conclave? If not possible, have both of them work the same way, now one uses a counter and the other uses '+Add' buttons.

Issues:
- [x] Autarch: His options to take two weapons is a bit messed up. The Codex states "May take up to two weapons from the following list", meaning maximum of two different entries in total, but you can't choose an entry twice. This makes sense of the dual choices in there, namely "Avenger shuriken catapult or lasblaster" and "Deathspinner or fusion gun". If you are allowed to choose an entry twice then the 'or' in those options is nonsensical
- [x] Autarch: Has a T4 as Infantry, should be T3
- [x] Baharroth: Unit Type is Jump Infantry, not Infantry
- [x] Jain Zar: She misses the Remnant of Glory: Mask of Jain Zar 
- [x] Wraithseer [FW]: It's Ghostspear weapon has the Special Rule Sunder. The explanation of that Special Rule is different on the Wraithseer's profile page (pg 213) than it is on the overview page (pg 225). On the Wraithseer's profile page it states "This weapon may re-roll any failed Armour Penetration rolls it makes." The other page has "A weapon with this special rule may re-roll all Armour Penetration rolls." In BS the Ghostspear refers to the second explanation (yay FW!)
- [x] Howling Banshee Exarch: Make Power Sword and Shuriken Pistol (no extra cost) standard selection please and remove the (None) option
- [x] Howling Banshee Exarch: The War Shout Special Rule only applies to the Howling Banshee Exarch in this unit, but it is given to the whole unit
- [x] Fire Dragon Exarch: Dragon's Breath Flamer has an empty profile. It solely refers to the brb, but perhaps it can link to the actual entry in the brb instead?
- [x] Wasp Assault Walkers [FW]: Start out with one Wasp Assault Walker selected instead of none please
- [x] Dire Avenger Exarch: When choosing the Diresword it has under Type the special rule Soulrazor. On the roster this special rule does not appear in the Selection Rules section
- [x] Phoenix Bombers [FW]: Start out with one Phoenix Bomber selected instead of none please
- [x] Dark Reapers: Starshot Missiles don't show up with a profile on the roster when selected by the squad. It does show up when selected by the Exarch
- [x] Dark Reaper Exarch: Make Reaper Launcher with Starswarm missiles (no cost) standard selection please and remove the (None) option.
- [x] Dark Reaper Exarch: On the roster, special rule Fast Shot does not show up as belonging to the Exarch (or anyone really), but it is present under the Selection Rules
- [x] Dark Reaper Exarch: On its profile it does not say Infantry (Character), just Infantry
- [x] Falcon: Please set it's standard Primary and Secondary weapon to Shuriken Cannon and Twin-linked shuriken catapult respectively, and remove the (none) options
- [x] Warp Hunters [FW]: Start out with one Warp Hunter selected instead of none please
- [x] Cobra [FW]: D-Impaler has a counter next to it, but it is mandatory and you can only have one
- [x] Scorpion [FW]: Starcannon says (no cost), but it costs 5 points according to The Doom of Mymeara
- [x] None of the Twin-linked weapons have Twin-linked as Special Rule under Type on their profiles. This causes Twin-linked not showing up under Selection Rules on the rosters or on the profiles of the weapons themselves. Affects Twin-linked Bright Lance, Twin-linked Starcannon, Twin-linked Eldar Missile Launcher, Twin-linked Scatter Laser, Twin-linked Shuriken Cannon, Twin-linked Avenger Catapult, Twin-linked Shuriken Catapults, Twin-linked Death Spinner, Twin-linked Pulsar, Twin-linked Phoenix Missile Launcher, Twin-linked Pulse Laser. These are all Twin-linked in name only, but they lack the special rule.

All units with multiple models have a maximum number and give a warning in BS when you use a counter and that number is surpassed. But some units don't allow you to take more than the maximum flat out, the counter just stops at the maximum. It would be nice to have consistency across the cat concerning interface-stuff like this.
The units that don't enforce limits are: Warlock Conclave, Warlock Skyrunner Conclave, Fire Dragons, Wraithguard, Rangers, Storm Guardians (although the special weapons Guardians are limited!), Windriders, Shadow Spectres, Shining Spears, Swooping Hawks, Warp Spiders, Dark Reapers and Vaul's Wrath Support Battery
The units that do enforce a maximum limit are: Howling Banshees, Striking Scorpions, Wraithblades, Dire Avengers and Guardian Defenders

*Edited, added minor issue regarding Dragon's Breath Flamer

**Comment by FarseerVeraenthis** [comment]
Well, that ought to keep me busy...

**Comment by FarseerVeraenthis** [comment]
One comment about power weapon selection, there is a difference between a sword (S user, AP3), axe (S +1, AP2, unwieldy), maul (S +2, AP4, concussive), and Lance (S +1/user, AP3/4), these differences are stated in the back of the codex as well, so the option will stay. :smile:

**Comment by Owlsbane** [comment]
I give. Really weird the way GW set this up in their Codex, but I can see the 'logic' behind it, or behind putting it like this in BS.

**Comment by FarseerVeraenthis** [comment]
~~WRT the Ghostspear - there is another weapon that has the "Sunder" special rule - the Titan Cloudburst Missile Launcher. On this weapon's oage it states "may re-roll all AP".
Therefore, 2:1 for "all" means I'll leave it as "all" for now.~~
Update to "A weapon with this special rule may re-roll any failed Armour Penetration rolls."

**Comment by FarseerVeraenthis** [comment]
Right, that's all of them done, apart from the Warlock Skyrunner Council. 
Which is a bit of a pain in the backside to fix but I'll have ago when I have more time.

Also, I didn't manage to make all the units enforce a maximum limit on the spinner because of the way each model is selected. There might be another way to do this, but I've not figured it out yet...!

**Comment by Owlsbane** [comment]
Brilliant work, thanks for checking them all out!

**Comment by FarseerVeraenthis** [comment]
Right, so they're all done. The Warlock Conclave is now much tidier 😄 
However, the requirement for all members of a Seer Council to take jetbikes, if one takes a jetbike, is not enforced by validation errors 😢 
For now, we'll see who reports a bug, but it is tidy and works cleanly atm...
