### ISSUE TITLE
Instant crash (major issue)

### ISSUE THREAD

**Issue by Vulkan1** [BSData/wh40k-7th-edition#3095]
App instantly crashes when adding forces or looking at old lists. This is happening to 8 or so in my gaming group. This is on the old BattleScribe. I know it's the repository as it happened after updating the data. It was working perfectly before.

**Comment by FarseerVeraenthis** [comment]
The previous version is not supported, upgrade to V2.0 and you should have no trouble.
Otherwise you'll need to check you've linked to the old data rather than the new data because the new files do not work with the old version of battlescribe...

**Comment by Vulkan1** [comment]
Where can I get the old data?

**Comment by Owlsbane** [comment]
You can find it [here](https://github.com/BSData/wh40k/releases/tag/v4.18.7).

It's dead though, won't receive any updates like the batch of new rules that appeared in the Traitor Legions and Codex: Imperial Agents.
