### ISSUE TITLE
Eldar Craftworld cat v2014 - Formations - Collection of issues

### ISSUE THREAD

**Issue by Owlsbane** [BSData/wh40k-7th-edition#3097]
Windows 10
Battle Scribe 2.00.07
Codex Eldar: Craftworlds (2015) v2014

Checked all Eldar Formations. Found the following issues. Some typo's and some bugs. No rest for the wicked, @FarseerVeraenthis!

Typo's:
- [x] Gemini Revenant Squad: Typo in the Mindlink special rule, it says "...during the shoooting phase..."
- [x] High Council of Iyanden: Typo in Silvereye's Foresight, it says "...Pecise Coordinates..."
- [x] Shadow Spectre Shrine: Typo, it has "...of an Exarchthat is..."
- [x] Windrider Host (Apoc.): Typo in Tornado of Blades, it says "...penetrating hitwhen resolving..."

Issues:
- [x] Dire Avenger Shrine: This Formation is limited to 1 Exarch, but when more than one is chosen BS does not issue a warning
- [x] Farseer Council: Why not preselect the minimum of 5 Farseers that this Formation needs?
- [x] Guardian Stormhost: The special rule Bring Forth the Torch is not enforced within BS. So when you choose to give a Storm Guardian one of the optional weapons BS does charge a points cost. 
- [x] Guardian Stormhost: Storm Guardians. The maximum of the Flamer and Fusion options isn't enforced correctly. The restriction is 2 in total, not 2 of each.
- [x] Hornet Swarm [FW]: Very funky. In Roster Selections it says 3x Hornet. BS gives the warning "3x Hornet has 4 too many selections from Weapons - 2 required (maximum 2)". So somehow it doesn't show three separate Hornets but says that one Hornet entry counts as three. That's where the warning comes from, because BS sees it as just one Hornet. When you add Hornets using the counter the warning increases with two for each Hornet added.
- [x] Mymeara Guardian Battlehost [FW]: Fortress of Discipline lets BS give a warning that it "must have 1 more selections of Wasp Assault Walkers [FW] (minimum 1)" when you choose two or more War Walker units.
- [x] Mymeara Guardian Batllehost [FW]: Fortress of Discipline, the Wasp Assault Walkers unit is preselected but empty. Either preselect it with one unit, or do not preselect it at all in the Roster Selections.
- [x] Shadow Spectre Shrine: Only one of the Shadow Spectre may have an Exarch, but BS does not provide a warning when two or more are selected
- [x] Skyhunter Squadron [FW]: The upgrades aren't linked across the squadron
- [x] Skyreaver Raiding Echelon [FW]: The Formation Restrictions aren't visible on the roster (or anywhere, really). Also, note that the last restriction "This Formation may not include more Vaul's Wrath Support Batteries than it does Guardian Defender Units" simply means that you always need to take a minimum of one Guardian Defender Unit. This isn't enforced in BS at the moment.
- [x] Windrider Host: Adding more than three units of Windriders does not result in a warning from BS that you are exceeding the maximum allowed  number of units
- [x] Windrider Host (Apoc.): The units that are mandatory are not preselected when choosing this Formation
- [x] Windrider Host (Apoc.): The resriction that you need a minimum of seven units is not enforced, BS does not warn you when you have less than seven units. Perhaps this restriction can be placed in the area where you pick the units (you know, on the right, what's that panel called anyway?)

Have fun ;)

**Comment by FarseerVeraenthis** [comment]
I don't know what you mean...!! I think we should just ban Forgeworld and Apocalypse and all these problems would go away :+1: 
I'll get onto these when I can, some of them are limitations due to my skill with Battlescribe, but I'll get into it and see what I can do :smile:

**Comment by FarseerVeraenthis** [comment]
Right, that's a few of those crossed off... I hope I've not made too horrible of a mess in the CAT, I'm not happy with how I had to enforce the Dire Avenger & Shadow Spectre Shrine "max 1 Exarch" conditions, but they should work now...
