### ISSUE TITLE
One or more errors reading catalog files

### ISSUE THREAD

**Issue by Rhynok** [BSData/wh40k-7th-edition#3100]
I keep getting this even after delete my data files and it does it when trying to put in a new one

**Comment by FarseerVeraenthis** [comment]
Which version of Battlescribe are you using?

**Comment by Rhynok** [comment]
2.00.11 that's the most up to date I can seem to get

**Comment by FarseerVeraenthis** [comment]
on which platform?

**Comment by Rhynok** [comment]
iOS

**Comment by FarseerVeraenthis** [comment]
Could you post a screen shot of the error?
Also, please check you're linking to the latest data, all the CAT file revisions should be in the 2,000 range.

**Comment by Rhynok** [comment]
Fixed it by deleting the app and reinstall it
