### ISSUE TITLE
New Roster: AM Cadian Battle Group showing everywhere

### ISSUE THREAD

**Issue by Viper666-Qc** [BSData/wh40k-7th-edition#3101]
When creating a new roster, the AM Cadian Battle Group is showing on the Force Org choices of every catalogues

**Comment by FarseerVeraenthis** [comment]
This means that this formation needs to be moved to the Astra Militarum CAT and removed from the GST.
This is how all the formations used to be represented though so it's not all bad if there's only one out of place!!
