### ISSUE TITLE
Chaos Space Marines - Artifact Selection Issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3113]
**File:** Chaos Space Marines - Codex.catz

**BattleScribe version:** 2.00.15

**Platform:** Android

**Dropbox:** No

**Description:** Issue with selecting chaos artifacts when using chaos lord and sorcerer. Cad Crimson Slaughter Chaos Lord can not take blade of relentless. Sorcerer in allied detachment can not take the burning burning brand artifact. Thanks again :)

**Comment by alphalas** [comment]
make sure you have Crimson Slaughter selected as a force option.
