### ISSUE TITLE
Space Wolves - Wolf Guard Terminators Missing Heavy Flamer Option

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3116]
**File:** Space Wolves - Codex.catz

**BattleScribe version:** 2.00.08

**Platform:** Windows

**Dropbox:** No

**Description:** Space Wolves codex.  Wolf Guard Terminators do not have the option to choose Heavy Flamer as a special weapon option.  Assault cannon is an option, as well as the rest of the choices.  If it is one of the pre-built formations from Stormclaw then its listed.

**Comment by Fatgoatee** [comment]
I requested this fix about a week ago and found out that it was discarded with the reason that they don't get a heavy flamer.  I request you take a look at the codex again and ensure that you have the latest edition.
Considering the entry to purchase a heavy flamer is right above the option for the assault cannon and the cyclone missile launcher.

Thank you

**Comment by FarseerVeraenthis** [comment]
In Codex: Space Wolves - Wulfen Edition, Wolf Guard Terminators do not have the option to purchase a Heavy Flamer.
This release is newer/more recent than the standard Space Wolves Codex.

**Comment by alphalas** [comment]
https://flic.kr/p/P8qWEE

https://flic.kr/p/QmuzXf

From Space Wolves - Wulfen Edition.

Heavy Flamers are Dreadnought only now.

**Comment by Fatgoatee** [comment]
So what about the Iron priest?  You have both the elite version from the original codex and the HQ entry that is in the Wulfen edition in the data file.  Yet the elite version of the iron priest is not in the wulfen edition of the codex.   Think it might just be a misprint then?

**Comment by alphalas** [comment]
And GW clarified that the Elite iron priest is grandfathered in. So no, I believe it is intentional
