### ISSUE TITLE
Adepta Sororitas - Ministorum Delegation

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3122]
**File:** Adepta Sororitas.catz

**BattleScribe version:** 2.00.16

**Platform:** Android

**Dropbox:** No

**Description:** There is an issue with the "Ministorum Delegation" detachment. In Codex: Imperial Agents, you are restricted to only taking a Ministorum Priest (or Jacobus) as your HQ, and may take 0-1 Elites, but are not required to. However, the Battlescribe data allows any HQ to be chosen, including Celestine, and also requires that an Elites slot must be chosen. The HQ slot should be restricted, and the Elites choice should be optional.

**Comment by tag8833** [comment]
I've got this fixed.
