### ISSUE TITLE
Lone wolves bug

### ISSUE THREAD

**Issue by IronWulfen88** [BSData/wh40k-7th-edition#3127]
I just entered a lonewolf into the company of the great wolf detachment and it says there is one too many lonewolves.

**Comment by GenWilhelm** [comment]
What platform are you seeing this on?
What file version are you using?
Are there any additional steps you took to produce the error?

**Comment by IronWulfen88** [comment]
im using the current data version since I updated just yesterday and im using a samsung tab e with version 2.00.18. I didnt do anything different than I did the last time I made a Company of the great wolf detachment. I added the lonewolf from the elite section and gave it it's weapons. however I just checked this morning and it looks like the problem has been fixed.
