### ISSUE TITLE
Adeptas Sororitas v2006 - Collection of issues

### ISSUE THREAD

**Issue by Owlsbane** [BSData/wh40k-7th-edition#3131]
Windows 10
Battle Scribe 2.00.08
Adeptas Sororitas v2006

Per request from @alphalas , I checked every unit using an Unbound army list then I checked the Formations. Took me a while to get the feel for the codex and for the way it was implemented. Some things may still be because of me misreading/misunderstanding the intent of the codex/cat.

 Units:
- [x] Canoness: Eviscerator costs 30 points, not 25
- [x] Ministorum Priest: Laspistol is not default choice.
- [x] Ministorum Priest: Is the Eviscerator in the Melee Weapons list Canoness only? I can't make out if it has note 1 or note 2 next to it. Anyway, Eviscerator costs 30 points, not 25
- [x] Ministorum Priest: Shotgun costs 1 point, is not for free
- [x] Uriah Jacobus: Typo in Protector of the Faith, has "...per its bestiary entry." but should read "...per its Army List entry."
- [x] Battle Sisters: BS does not give a warning when selecting more than 20 Sisters
- [x] Repentia Squad: The Mistress of Repentance has two Neural Whips as option, they should be standard equipment
- [x] Repentia Squad: The Mistress of Repentance does not have the option to buy Melta Bombs, but she should have
- [x] Sororitas Command Squad: BS does not give warning when more than 5 models are in this unit, something that happens automatically when picking a Celestian upgrade like Hospitaller or Standard Bearer
- [x] Sororitas Command Squad: When taking a Celestion Standard Bearer or a Celestian with Simulacrum Imperialis that Celestion looses the ability to pick any wargear. Why not do it like with the Celestian Squad?
- [x] Sororitas Command Squad: Whole unit misses frag and krak grenades
- [x] Sororitas Command Squad: Why not give Hospitaller the Chirurgeon's Tool as standard equipment instead of an option?
- [x] Sororitas Command Squad: Why not give Dialogus the Laud Hailer as standard equipment instead of an option?
- [x] Sororitas Command Squad: Melee Weapon selection is at squad level, should be at individual Celestion level (like the Heavy, Ranged and Special weapons)
- [x] Arco-Flagellant: They have two Arco-flails as option, these should be standard equipment
- [x] Crusaders: Their weapon choices should be standard equipment
- [x] Death Cult Assassins: They have two Power swords as option, these should be standard equipment
- [x] Celestian Squad: BS does not give a warning when selecting more than 10 Celestians
- [x] Celestian Squad: Their Attack characteristic is 4, it should be 2
- [x] Dominion Squad: The individual models should be called Dominions, not Battle Sisters
- [x] Dominion Squad: BS does not give a warning when selecting more than 10 Dominions
- [x] Dominion Squad: It says "One Battle Sister May:" and then allows you to pick a Special Weapon and/or a Simulacrum Imperialis. This should be split into two, with one saying "One Dominion may take:" for the Simulacrum Imperialis and "Four other Dominions may take:" for the Special Weapon
- [x] Seraphim Squad: They have two Bolt Pistols as option, these should be standard equipment
- [x] Seraphim Squad: Change the "Two Seraphim May:" and then the weapon options into an option to take Seraphim with either 2 Hand Flamers or two Inferno Pistols in their profile.
- [x] Sororitas Rhino: The first Storm Bolter as option costs 5 points, it should be standard equipment (at no cost, obviously)
- [x] Sororitas Rhino: It misses Searchlight and Smoke Launchers equipment
- [x] Sororitas Rhino: It misses information on Transport Capacity, Fire Points and Access Points
- [x] Sororitas Rhino: It misses the Repair special rule
- [x] Immolator: It misses Searchlight and Smoke Launchers equipment
- [x] Immolator: It misses information on Transport Capacity, Fire Points and Access Points
- [x] Immolator: Twin-linked Heavy Flamer should be standard equipment
- [x] Vehicle Gear list: Laud Hailer costs 5 points, should be 10
- [x] Retributor Squad: The individual models should be called Retributors, not Battle Sisters
- [x] Retributor Squad: BS does not give a warning when selecting more than 10 Retributors
- [x] Retributor Squad: It says "One Battle Sister May:" and then allows you to pick a Special Weapon and/or a Simulacrum Imperialis. This should be split into two, with one saying "One Retributor may take:" for the Simulacrum Imperialis and "Four other Retributors may take:" for the Heavy Weapon
- [x] Exorcist: It misses Searchlight and Smoke Launchers equipment
- [x] Penitent Engines: Misses Type Vehicle (Walker) on profile

Formations:
- [x] Ecclesiarchy Battle Conclave: BS does not give a warning when taking more than one Ministorum Priest or when taking a Ministorum Priest as well as Uriah Jacobus
- [x] Ecclesiarchy Battle Conclave: The Formation profile does not show the Formation restriction, namely that "All models in the Formation form a single unit."
- [x] Purge Squadron/Repentant Host/The Angelic Host: These share many issues, but this one is the most important. First solve this, then the rest can be checked. Example, Purge Squadron has in Roster Selections the ability to take Immolators and Retributor Squads. These give a warning when exceeding their limits, which is correct. However, these options are completely void within Roster Selections, except for the ability to select 'real' units when focussed on. There are no limits on how many of these units can be selected. For some of these units you pay double the points cost because you pay for them on both levels.

Good luck!

**Comment by tag8833** [comment]
I made a pretty good Dent in these.  Didn't quite get to the old formations.  I'll look at them later if it is still an issue.
