### ISSUE TITLE
Eldar Corsairs [FW] cat v2002 - Collection of issues

### ISSUE THREAD

**Issue by Owlsbane** [BSData/wh40k-7th-edition#3134]
Windows 10
Battle Scribe 2.00.08

Eldar Corsairs v2002

Checked all Corsair units in an Unbound list, found mostly typo's but also some real issues. Also checked the Corsair Fleet Raiding Company force org. chart and found only one typo :)

Typo's:
- [x] Corsair Prince: Typo in Corsair Combat Drug, it says "...effects of the rule..." where it should be "...effects of the result..."
- [x] Corsair Prince: Typo in Multiphase Key Generator under Traveller of Forgotten Path, it says "...3" of the mode." where it should be "...3" of the model."
- [x] Corsair Prince: Typo in Wielder of Profane Powers, it has as title "Weilder of..."
- [x] Wild Psyker: Typo in Soul-wracked, it has "The cruel ceasses..." where it should be "The cruel caresses...", also "...any unit is has..." where it should be "any unit it has..."
- [x] Corsair Jet Pack: Typo in its description, it has "...has the unit typer..." where it should be "...has the unit type..."
- [x] Tanglefield Grenades: Typo in Tanglefield special rule, it has "...with this specialrule..."
- [x] Dissonance pistol: Typo in Vibro-pulse special rule, it has "...with this specialrule,"
- [x] Brace of pistols: Typo in its description, it has "...to be represended on..."
- [x] Shadowfield: Typo, it is consistently referred to as Shadow Field, it should not have that space in between
- [x] Corsair Void Dreamer: Typo in Soul-wracked, it has "The cruel ceasses..." where it should be "The cruel caresses...", also "...any unit is has..." where it should be "any unit it has..."
- [x] Corsair Baron: Typo in Soul-wracked, it has "The cruel ceasses..." where it should be "The cruel caresses...", also "...any unit is has..." where it should be "any unit it has..."
- [x] Corsair Malevolent Band: Typo in Curse of the Void special rule, it has "...a Corsair Melevolent Band..."
- [x] Twin-linked Shuriken Catapult: It has a typo in its name, it says "Twin-linked Shruiken Catapult"
- [x] Coterie Specialisations: Typo in Head Takers, it says "...for the ruration of..."

Issues:
- [x] Corsair Prince: Reaper of the Outer Dark does not have a description of Rage in its profile
- [x] Corsair Prince: It has the option to buy a Power Weapon, but there is no option to choose which of the four Power Weapons you want (like in the Craftworld cat)
- [x] Corsair Reaver Band: The Corsair Felarch has a Sv of 4+ on his profile, this should be 5+
- [x] Corsair Reaver Band: The Corsair Felarch has access to the Flamer, Fusion Gun, Shredder and Blaster options but only Corsairs are allowed to take these
- [x] Corsair Cloud Dancer Band: Felarch has the choice between a Brace of Pistols or up to two choices from a range of hand weapons. This is not set correctly
- [x] ~~Corsair Voidstorm Band: Felarchs can be added through "+ Add" buttons, but with other units you can do it through counters.~~ The latter option is easier to use, can it be changed in this instance? Unfortunately not, this is because each Felarch has the option to choose 2 additional weapons, so their loadout can be selected individually, and this is what causes the "+ Add" buttons to appear.
- [x] Corsair Voidstorm Band: The Armour section is wrong. The choice should be between Heavy Mesh Armour and Voidplate Harnesses. Void Hardened Armour is an add-on and does not replace anything
- [x] Corsair Malevolent Band: The Special Weapons options aren't limited to 1 per 5 Malevolents, BS does not provide a warning when exceeding the limit
- [x] Corsair Vyper Squadron: Under Secondary Weapon, Starcannon has no cost, it should cost 5 points
- [x] Corsair Nightwing: Move Fighter Ace from individual model up to unit level. Should only allow one per squadron as well*
- [x] Corsair Phoenix: Move Fighter Ace from individual model up to unit level. Should only allow one per squadron as well*
* Fighter Ace is actually one model per roster, so if possible BS should check for multiple instances of Fighter Ace in the whole list
- [x] Corsair Balestrike Band: The Corsair Felarch has a Sv of 4+ on his profile, this should be 5+
- [x] Corsair Lynx: The following Secondary Weapons have no cost, they should cost 5 points each: Dark Lance, Starcannon and Bright Lance
- [x] Corsair Warp Hunter Squadron: Under Secondary Weapon Shuriken Cannon is free, it should cost 10 points

Happy Holidays!

**Comment by FarseerVeraenthis** [comment]
The Typos are done, and I've made some comments on some of the other bugs in the checklist.
