### ISSUE TITLE
Chaos Khorne Daemonkin - issue loading roster

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3136]
**File:** Chaos Khorne Daemonkin.catz

**BattleScribe version:** 2.00.19

**Platform:** Android

**Dropbox:** No

**Description:** When  loading a list for kdk, it seems to take a while and I keep getting an error message that some of the data is corrupted and may not work. Tried updating, tried uninstall/reinstall.

**Comment by FarseerVeraenthis** [comment]
Is this when making a new list or trying to open an old one??
