### ISSUE TITLE
CSM - Be'lakor not available as HQ choice in Crimson Slaughter detachment 

### ISSUE THREAD

**Issue by Drachnyen** [BSData/wh40k-7th-edition#3139]
Hello,

Be'lakor is not an HQ option for a Crimson Slaughter detachment. 

Option for dataslate is enabled. See screenshot 
![img_1400](https://cloud.githubusercontent.com/assets/16340056/21487386/bcd55d9e-cb95-11e6-85c2-ff1a9d7fc11d.PNG)

Thanks

**Comment by Drachnyen** [comment]
Did you have a chance to look into this @cartag ?

**Comment by cartag** [comment]
It'll get fixed, hakuna your tatas.

**Comment by Drachnyen** [comment]
Thanks @cartag :)
