### ISSUE TITLE
CSM - too many legacies of ruin selected is back

### ISSUE THREAD

**Issue by Drachnyen** [BSData/wh40k-7th-edition#3140]
Hello,

This issue was fixed and is back, we have a small regression somewhere. 

Getting too many legacies of ruin selected, maximum is 0 when assigning a legacy to my sicaran tank

Points is set to 1850 and a single legacy was selected. 

![img_1401](https://cloud.githubusercontent.com/assets/16340056/21487434/a77d45b4-cb96-11e6-916d-42af846b9518.PNG)

**Comment by oroberts42** [comment]
I also see this for a multi formation and CAD CSM list, 1500, Relic Sicaran with a Legacies of Ruin.

**Comment by Drachnyen** [comment]
Hello,

Update of BS 2.00.14 seems to have fixed this issue. 

Thanks

**Comment by FarseerVeraenthis** [comment]
Fabulous, I love it when problems fix themselves :smile:

**Comment by cartag** [comment]
It was broken through no fault of my own and resolved without me doing anything. My favorite kind of bug.

**Comment by oroberts42** [comment]
Yep, cool. BS release notes say:
2.00.14
Fixed incorrect roster errors for constraints based on points limit.
