### ISSUE TITLE
Lonewolf issue back

### ISSUE THREAD

**Issue by IronWulfen88** [BSData/wh40k-7th-edition#3141]
Im using my computer to back up my files with its battlescribe. I just got the new version v2.00.09 and the issue with the Lonewolf not getting the other power weapon options is back.

**Comment by GenWilhelm** [comment]
What version of the file are you using?

**Comment by IronWulfen88** [comment]
Im using the latest version of 2.00.10 on my toshiba laptop. And I just updated the files the yesterday. Its fixed on the tablet version but not the computer version. .
