### ISSUE TITLE
Transports not free in complete Gladius Strike Force with full Battle Company

### ISSUE THREAD

**Issue by Shiney1965** [BSData/wh40k-7th-edition#3144]
Hello: I just started using BS 2.0 on iOS. I loaded a brand new Space Marine Codex dataset from github and built a GSF but I am being charged points for vehicles for the BC units that should be free in that formation.  I am sure all the elements of the GSF are there and the ultramarines combat doctrines are selected.  Is this a bug or something I am missing?  Thanks.

**Comment by FarseerVeraenthis** [comment]
Works for me on Desktop...
When you say "built a GSF" - on desktop you simply select the battle company formation and the correct units are selected automatically...

**Comment by Shiney1965** [comment]
You have to choose an Auxiliary Formation, which I did. I did not try this on desktop only new BS on iOS, which I just downloaded today. Works fine in the old Battlescribe.

**Comment by DrTobogganMD** [comment]
Did you select the one that says "Free Transports" for your core?

**Comment by FarseerVeraenthis** [comment]
Right, so in the new exciting world of Battlescribe 2.0, you create a new roster, and then add a SM Gladius Strike Force to it by scrolling to the bottom of the forces list, then you can add a core choice (which in your case is the Battle Company) and then transports are free...
I actually don't have a iOS device, but I've checked on Desktop and Android and they're definitely there...

**Comment by Shiney1965** [comment]
Farseer: I did exactly what you said and the transports are not free in iOS. But the comment by Kohato doesn't make sense to me -- I don't see anything that says free transports just SM Gladius Strike Force. But I'll look again.

**Comment by DrTobogganMD** [comment]
Purge Data, Reload. 

There are 2 core choices. Battle Demi Company and Battle Company.  I did it this way for ease of coding.  It is MUCH cleaner to make a new Core choice that combines two demis and offers free transports than to code the conditionals in the book.

**Comment by Shiney1965** [comment]
I see it now .. sorry not sure why I didn't see that before you're right. Thank you and Never mind.

**Comment by DrTobogganMD** [comment]
No issues. Some people are still on a pre 2.0 version. So purge and reload is usually easiest.

**Comment by Shiney1965** [comment]
Thanks .. I see that now. Didn't see it at first for some reason. Thanks for the help!
