### ISSUE TITLE
Deathwatch - BS Not Counting Heavy Thunder Hammer for Vanguard Veterans Correctly

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3157]
**File:** Deathwatch - Codex.catz

**BattleScribe version:** 2.00.20

**Platform:** Android

**Dropbox:** No

**Description:** When selecting weapons for a Vanguard Veteran, if you give him a Heavy Thunder Hammer, it still has an error and says "Vanguard Veteran must have 2 more selections from Choose 2 (minimum 2)". You shouldn't need that when you select the HTH because it replaced es all of your weapons. Thank you!

**Comment by FarseerVeraenthis** [comment]
As far as I can see the datafile is setup correctly... therefore, this might be a Battlescribe bug - but I really hope not!!

**Comment by alphalas** [comment]
I can confirm it's a thing on iOS

**Comment by FarseerVeraenthis** [comment]
that completes the trio then, since I checked both Android (per the report) and Windows...
