### ISSUE TITLE
[Anon] Duplicate IDs

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#316]
Details:
More than one catalogue found with the same id.

> /Users/KY/BattleScribe/data/Warhammer 40,000 7th Edition: More than one catalogue found with the same id.
>     at data.CatalogueData.a(Unknown Source)
>     at data.CatalogueData.readCataloguesFlat(Unknown Source)
>     at gui.rostereditor.CatalogueLinkDialog.a(Unknown Source)
>     at gui.rostereditor.CatalogueLinkDialog.<init>(Unknown Source)
>     at gui.rostereditor.RosterForceDialog.c(Unknown Source)
>     at gui.rostereditor.RosterForceDialog.c(Unknown Source)
>     at gui.rostereditor.RosterForceDialog$4.actionPerformed(Unknown Source)
>     at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
>     at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2341)
>     at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
>     at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
>     at ch.randelshofer.quaqua.QuaquaButtonListener.mouseReleased(QuaquaButtonListener.java:110)
>     at java.awt.Component.processMouseEvent(Component.java:6516)
>     at javax.swing.JComponent.processMouseEvent(JComponent.java:3320)
>     at java.awt.Component.processEvent(Component.java:6281)
>     at java.awt.Container.processEvent(Container.java:2229)
>     at java.awt.Component.dispatchEventImpl(Component.java:4872)
>     at java.awt.Container.dispatchEventImpl(Container.java:2287)
>     at java.awt.Component.dispatchEvent(Component.java:4698)
>     at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
>     at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)
>     at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
>     at java.awt.Container.dispatchEventImpl(Container.java:2273)
>     at java.awt.Window.dispatchEventImpl(Window.java:2719)
>     at java.awt.Component.dispatchEvent(Component.java:4698)
>     at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:735)
>     at java.awt.EventQueue.access$200(EventQueue.java:103)
>     at java.awt.EventQueue$3.run(EventQueue.java:694)
>     at java.awt.EventQueue$3.run(EventQueue.java:692)
>     at java.security.AccessController.doPrivileged(Native Method)
>     at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
>     at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
>     at java.awt.EventQueue$4.run(EventQueue.java:708)
>     at java.awt.EventQueue$4.run(EventQueue.java:706)
>     at java.security.AccessController.doPrivileged(Native Method)
>     at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
>     at java.awt.EventQueue.dispatchEvent(EventQueue.java:705)
>     at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
>     at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
>     at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:154)
>     at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:182)
>     at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:221)
>     at java.security.AccessController.doPrivileged(Native Method)
>     at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:219)
>     at java.awt.Dialog.show(Dialog.java:1082)
>     at java.awt.Component.show(Component.java:1655)
>     at java.awt.Component.setVisible(Component.java:1607)
>     at java.awt.Window.setVisible(Window.java:1014)
>     at java.awt.Dialog.setVisible(Dialog.java:1005)
>     at gui.rostereditor.RosterEditorFrame.f(Unknown Source)
>     at gui.rostereditor.RosterEditorFrame.h(Unknown Source)
>     at gui.rostereditor.RosterEditorFrame$10.actionPerformed(Unknown Source)
>     at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
>     at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2341)
>     at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
>     at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
>     at ch.randelshofer.quaqua.QuaquaButtonListener.mouseReleased(QuaquaButtonListener.java:110)
>     at java.awt.Component.processMouseEvent(Component.java:6516)
>     at javax.swing.JComponent.processMouseEvent(JComponent.java:3320)
>     at java.awt.Component.processEvent(Component.java:6281)
>     at java.awt.Container.processEvent(Container.java:2229)
>     at java.awt.Component.dispatchEventImpl(Component.java:4872)
>     at java.awt.Container.dispatchEventImpl(Container.java:2287)
>     at java.awt.Component.dispatchEvent(Component.java:4698)
>     at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
>     at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)
>     at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
>     at java.awt.Container.dispatchEventImpl(Container.java:2273)
>     at java.awt.Window.dispatchEventImpl(Window.java:2719)
>     at java.awt.Component.dispatchEvent(Component.java:4698)
>     at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:735)
>     at java.awt.EventQueue.access$200(EventQueue.java:103)
>     at java.awt.EventQueue$3.run(EventQueue.java:694)
>     at java.awt.EventQueue$3.run(EventQueue.java:692)
>     at java.security.AccessController.doPrivileged(Native Method)
>     at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
>     at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
>     at java.awt.EventQueue$4.run(EventQueue.java:708)
>     at java.awt.EventQueue$4.run(EventQueue.java:706)
>     at java.security.AccessController.doPrivileged(Native Method)
>     at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
>     at java.awt.EventQueue.dispatchEvent(EventQueue.java:705)
>     at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
>     at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
>     at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
>     at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
>     at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
>     at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

**Comment by amis92** [comment]
Thank you. This is unfortunately resolvable only through BattleScribe data wipeout (delete all of them) and re-downloading data.

Also duplicate of #246.
