### ISSUE TITLE
Tau - Targeted Reconnaissance Cadre

### ISSUE THREAD

**Issue by thebiggeordiegeek** [BSData/wh40k-7th-edition#3160]
This formation is missing from the data files.

I have scanned the formation dataslate and uploaded it to Dropbox here (https://www.dropbox.com/s/h4h0ja207ev8kb8/Dataslate%20-%20Tau%20Empire%20-%20Targeted%20Reconnaissance%20Cadre.pdf?dl=0) so that it can be used to add the formation into the database.

**Comment by thebiggeordiegeek** [comment]
For some reason this isn't showing up as an option for me yet?

**Comment by cartag** [comment]
There hasn't been a release pushed since the code was updated. Patience, young Padawan.

**Comment by thebiggeordiegeek** [comment]
Ah and there was me thinking I was doing something wrong!
