### ISSUE TITLE
Inquisition - Codex Outdated?

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3161]
**File:** Inquisition - Codex.catz

**BattleScribe version:** 2.00.12

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** It's outdated. Imperial Agents changed a number of things, such as 2 pt carapace and 5 pt power armor, a new detachment, and ability to take sisters/GK/etc.

**Comment by alphalas** [comment]
We're working on it - however since C:Inquisition ePub is still available from BL, the changes in C:IA will only be able to be taken in the new detachment, you will still have option to take the old stuff in the old detachments

**Comment by alphalas** [comment]
Ref #3083 for further info.
