### ISSUE TITLE
CSM - Obliterator Weapon table issues 

### ISSUE THREAD

**Issue by Drachnyen** [BSData/wh40k-7th-edition#3167]
Hello,

Just noticed two issues with the obliterator weapon table:

1.  Assault Cannon weapon profile is missing
2. Heavy stubber should not be in the list of available weapons. 

Thanks in advance

**Comment by Drachnyen** [comment]
Anyone had a chance to look into this ?

**Comment by cartag** [comment]
Let me drop everything and cater to you, oh impatient one.

**Comment by Drachnyen** [comment]
Lol.  No need.  Just that it wasn't assigned yet.  Was worried it fell through a crack.

Keep up the good work, it's not urgent

**Comment by cartag** [comment]
I know it's not urgent, trust it will get done. If it's here, it will be done. That's all there is to it. No need to continually follow up. I've stopped what I'm doing and am working on this now, so you'll get your update.

**Comment by cartag** [comment]
There. It's done. I'm going back to my weekend now.
