### ISSUE TITLE
Space Marines - Tyberos missing orbital bombardment

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3176]
**File:** Space Marines - Codex (2015).catz

**BattleScribe version:** 2.00.21

**Platform:** Android

**Dropbox:** No

**Description:** Tyberos is missing the Orbital Bombardment special rule

**Comment by FarseerVeraenthis** [comment]
Tyberos The Red Wake does not appear to have this rule in Imperial Armour 10.
Please provide a screenshot and I'll incorporate it :smile:

**Comment by alphalas** [comment]
https://www.forgeworld.co.uk/resources/fw_site/fw_pdfs/Warhammer_40000/Forge_World_Space_Marine_Badab_Characters_V2.pdf

**Comment by FarseerVeraenthis** [comment]
I've seen it, I'll include it when I fix the Relics...
