### ISSUE TITLE
Deathwatch - include squad Crull where necessary

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3177]
**File:** Deathwatch - Codex.catz

**BattleScribe version:** 2.00.13

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** Each Kill Team formation should be able to take squad crull (as it meets both the validations for furor and purgatus KTs) - also the only kill teams that can take squad galatael are the Aquila and the Dominatus.

**Comment by FarseerVeraenthis** [comment]
fyi Anon, I am working on sorting this out - there has been a problem with editing the CAT that I've finally figured out how to correct...
Hopefully this will be finished and uploaded this week :smile:
