### ISSUE TITLE
Tau Empire - Missing Tidewall formations

### ISSUE THREAD

**Issue by Bparks1983** [BSData/wh40k-7th-edition#3179]
File: Tau Empire: Codex (2015) v2005

BattleScribe version: 2.00.21

Platform: Android

Dropbox: No

Description: Not all Tidewall formations listed in the Formation detachments. Tidewall Defence Network, Tidewall Gunfort and Tidewall Rampart are missing (only showing up in CAD and unbound lists).  Tidewall Counterstrike Cadre is still listed in the formation detachments correctly.

**Comment by alphalas** [comment]
They are not Formations, rather they are Fortification Networks. No error, data is correct.
