### ISSUE TITLE
Blood Angels Death Company weapons issues

### ISSUE THREAD

**Issue by IronWulfen88** [BSData/wh40k-7th-edition#3185]
The choices for left hand bolters and bolt pistols as well as the right hand chainswords are missing. along with the left hand infernus pistol, hand flamer and plasma pistol options.

**Comment by alphalas** [comment]
It's actually set up that way due to how the options to take weapons are laid out in the codex. Theoretically, it shouldn't be Left/right, but chainsword/bolt pistol.

**Comment by alphalas** [comment]
https://flic.kr/p/QhvWWq For reference.

**Comment by IronWulfen88** [comment]
okay thankyou
