### ISSUE TITLE
Imperial Navy Assets removed from Adepta Sororitas 

### ISSUE THREAD

**Issue by Commisar** [BSData/wh40k-7th-edition#3189]
Hi
Unless I'm being really dense I can't find a way to add Avenger Strike Fighters or Arvus Lighters to my sisters of battle army.

Should be able to according to Imperial Armour Aronautica

Which, I realise has been mostly superseded, but is still the most recent rules for these particular models which are still on sale.

**Comment by alphalas** [comment]
Update your data - release went out last night that fixed
