### ISSUE TITLE
Dark Angel Terminator Sargent Upgrade Incomplete

### ISSUE THREAD

**Issue by jujubes55** [BSData/wh40k-7th-edition#319]
The Deathwing Terminator Sergeant should be able to switch his weapons to the Lightning Claws or Thunder Hammer/Storm Shield. "Any Model May replace all of his weapons with-"

**Comment by Thairne** [comment]
While annoying, it is not a bug Ruled As Written.
The Codex states that "any model can exchange it's stormbolter and powerfist with yaddayadda", the sergeant however does not have a powerfist and therefore is not eglibile for the exchange.
The FAQ give no permission for this, either.
