### ISSUE TITLE
Blood Angels quickview issues

### ISSUE THREAD

**Issue by IronWulfen88** [BSData/wh40k-7th-edition#3192]
The stats and rules for Death company chaplains and Astorath the Grim do not show up. Im still checking other units but so far these two are the only ones I have found so far.

**Comment by FarseerVeraenthis** [comment]
They show for me on Android... 
Which platform are you using?

**Comment by FarseerVeraenthis** [comment]
checked on Windows too, they appear to be working perfectly well to me...
