### ISSUE TITLE
Tyranids - Special Rules Missing

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3199]
**File:** Tyranids - Codex.catz

**BattleScribe version:** 2.00.21

**Platform:** Android

**Dropbox:** Yes

**Description:** When selecting units from the Tyranid list, several units do not list out their rules with their selection under their names. 
The rules are listed out ino the Selection rules, but there is no way of know which one of the rules apply to the different units.

This applies to several units, genestealers, pyrovores, lictors, pyrovore, venomthrope, termagaunts, etc etc., gargoyle

It appeared to be only a select few, but now it appears to be more than this list.

This worked fine in the prevous Battlescribe.

**Comment by FarseerVeraenthis** [comment]
This is likely because the Tyranid CAT has not been upgraded to BS2.0 format yet, I don't know who will fix it because @Randobar who is the keeper on the Wiki has been quiet of late...

**Comment by GenWilhelm** [comment]
This can be controlled by your local settings (when viewing a roster, tap the cog icon at the top).
In order for units to show individual wargear and rules you need to be showing Full output (not Minimal).

**Comment by Randobar** [comment]
@FarseerVeraenthis i´m still around for bugfixes and updates.

**Comment by FarseerVeraenthis** [comment]
@randobar good to know! As it turned out I should have read a little further before deciding it could be a data issue...
