### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by Stegadons** [BSData/wh40k-7th-edition#32]
I am working on revising current Codex: Space Marines catalogue. 
My main goals are:
- create as much shared entries/groups/profiles/rules as possible to avoid data duplication 
- update references in every entry/rule/profile 
- create modifiers and conditions to make profiles more dynamic
- revise current selection system where necessary

**Comment by amis92** [comment]
Welcome aboard :)

**Comment by amis92** [comment]
Oh, and @Stegadons, please look here: https://github.com/BSData/wh40k/issues/24 and discuss what will you do, to not double the work being done.
