### ISSUE TITLE
Space Wolves - Relic Selection Issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3201]
**File:** Space Wolves - Codex.catz

**BattleScribe version:** 2.00.21

**Platform:** Android

**Dropbox:** No

**Description:** For the relics from the Champions of Fenris list, some weapons are outside the weapon selection screen, requiring too many selections of weapons per character. Nit picking really, keep up the great work!!

**Comment by GenWilhelm** [comment]
Okay so I went and looked this up and I cant find anything to suggest that any of the Relics of the Great Wolf (except Morkai's Claws) replace the model's existing weapons. Morkai's Claws specifically state:

>Morkai’s Claws are a pair of unique wolf claws that replace all of a model’s ranged and
Melee weapons.

This makes me think the non-replacement of the model's stock weapons is intentional, and the relic weapons are therefore additional to any other weapon selections. Can anyone else confirm this, or am I doing my usual trick of missing a crucial piece of information?

**Comment by IronWulfen88** [comment]
I have been having trouble with the space wolves relics myself. I refreshed the data and it started working again. The relics I chose werent sticking to the unit I had them on. Odd thing though is I used to be able to put the relics on my wolfguard pack leaders too and now I cant.

**Comment by GenWilhelm** [comment]
>The relics I chose werent sticking to the unit I had them on.

If you're talking about weapon relics, the most likely cause of this is that weapon selections are tied to the armour selection. So if you change which armour a character is using, their weapons are reset to the default for that armour.

---
>I used to be able to put the relics on my wolfguard pack leaders too and now I cant.

I just had a skim through the codex and I can't find any WGPLs that can take items from the relics list, Battle Leaders can but not Pack leaders. Perhaps they were able to in an older version of the codex (before CotW maybe?).

**Comment by IronWulfen88** [comment]
Oh thats right. Dang I gotta find my codex again. Thanks for checking on that. And I looked into the armor thing and I found that part too.

**Comment by FarseerVeraenthis** [comment]
@GenWilhelm, referring to your earlier comment;

> Okay so I went and looked this up and I cant find anything to suggest that any of the Relics of the Great Wolf (except Morkai's Claws) replace the model's existing weapons. Morkai's Claws specifically state:

>>Morkai’s Claws are a pair of unique wolf claws that replace all of a model’s ranged and
Melee weapons.

>This makes me think the non-replacement of the model's stock weapons is intentional, and the relic weapons are therefore additional to any other weapon selections. Can anyone else confirm this, or am I doing my usual trick of missing a crucial piece of information?

The crucial piece of information you are missing is on the Wargear list, I'm looking at the Wulfen Edition Codex and it says;
"Relics of the Fang; A model can replace one weapon with one of the following"
The only ones that this doesn't apply to are indicated directly - i.e. Helm of Durfast has a 6 after it and the footnote says "does not replace one of the character's weapons"

Take a look at the SM CAT if you want to see one way of implementing the Relics, I've not looked at the SW CAT so I can't comment how to implement it there, but from the bug rep it does look like this needs a tweak.

**Comment by GenWilhelm** [comment]
I agree that's the case for Relics of the Fang, and that's how it currently works for those relics, but the relics in question are Relics of the Great Wolf from the Champions of Fenris supplement.

**Comment by FarseerVeraenthis** [comment]
Cool, I don't have a copy of that book, is there not the same sentence in that wargear list too...?

**Comment by GenWilhelm** [comment]
Not that I can see, that's why I was asking if I'd missed anything obvious 😄

**Comment by FarseerVeraenthis** [comment]
Hahaha! I :love: geedubs...

**Comment by Bparks1983** [comment]
The digital version only has the "replace" wording under Morkai's Claws.

**Comment by FarseerVeraenthis** [comment]
Is it the case that the OP is actually asking for the option to take two weapons AND a Relic of The Great Wolf without an error triggering...??

**Comment by GenWilhelm** [comment]
>[...] take two weapons AND a Relic of The Great Wolf without an error triggering.

This is already the case.

I think this discussion has gone on long enough, and we haven't found any reason to change it from the way it currently is,
