### ISSUE TITLE
Codex Adepta Sororitas vs Codex: IA Sisters

### ISSUE THREAD

**Issue by Viper666-Qc** [BSData/wh40k-7th-edition#3206]
I see the Codex Adepta Sororitas codex have been modified with everything that changed from the Codex IA. Do you know if the AS digital Codex have been modified exactly as the army list from the Codex: IA? 

Because if not, If I'm taking a CAD of AS, units like Arco-flagellants, Death Cult Assassins & Crusaders should still be in an Battle Conclave and not separate units like in C:IA (for the Vestal Task Force & Ministorum Delegation)

**Comment by alphalas** [comment]
We are going to roll back the old conclave along with the formation version- however, I would think that the formation actually is better then the old conclave, imo.

**Comment by Viper666-Qc** [comment]
I don't see a problem to change it as long as the actual digital codex is changed too.... 
I do find the new Ministorum Delegation better too than a battle conclave except in the tournament scene, it takes a slot for the maximum of Detachments allowed. 

Anyway, this whole situation with a unit with different profile depending of the sources (Astra Militarum psykers & techpriests vs IA ones, Inquisition & Adepta Sororitas vs IA ones) is getting ridiculous....
