### ISSUE TITLE
Deathwatch - Hilarious RAW Selection Options

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3209]
**File:** Deathwatch - Codex.catz

**BattleScribe version:** 2.00.14

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** A Deathwatch Veteran with a two-handed Heavy Weapon (e.g. Infernus Heavy Bolter) has the validation error "... must have 1 more selections from Choose 2 (minimum 2)".

Is this correct? I can silence it by selecting a chainsword and/or bolt pistol, but haven't they given those up for the heavy weapon?

**Comment by FarseerVeraenthis** [comment]
Hahaha! You know, I was looking at this last night, a veteran only has to give up his boltgun for a heavy weapon, therefore he can exchange his chainsword for pretty much anything else... As a ridiculous example, you could technically have frag cannon welding Veterans with storm Shields...
Having said that, they cannot take bolt pistols, and there is an update pending for the Deathwatch CAT as soon as I finish it :-)

**Comment by FarseerVeraenthis** [comment]
In answer to your question, yes, this is correct!
