### ISSUE TITLE
Orks - Shoota Upgrade Cost Issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3210]
**File:** Orks - Codex.catz

**BattleScribe version:** 2.00.21

**Platform:** Android

**Dropbox:** No

**Description:** When you are adding shootas to a mob of boys, it charges you per model in the unit instead of just the boys who will have shootas. For example you're charged for a big shoota and a shoota when you add it to the mob. You should not be charged for the shoota for the model you paid for the big shoota upgrade or nob upgrade etc.

**Comment by tag8833** [comment]
Based on common sense you are correct, but if you take a close look at the rules you will see that you must 1st upgrade to a shoota before you can upgrade to a big shoota or nob.

It is stupid.  Truly insane, but it is how the rules are written.
