### ISSUE TITLE
Dark Eldar - Supplement - Haemonculus Covens - squad selection issues

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3211]
**File:** Dark Eldar - Supplement - Haemonculus Covens.catz

**BattleScribe version:** 2.10.65

**Platform:** Windows

**Dropbox:** Yes

**Description:** 1) When select haemonculus, there is an error where i cannot select 2 haemonculus. it mentioned too many HQ slot of haemonculus being selected.

2) cannot select wrack more than one, there is an error, too many unit of wrack being selected.

**Comment by FarseerVeraenthis** [comment]
I can't see why those limits have been imposed, so I have removed them.
