### ISSUE TITLE
Inquisition - HQ Slot Issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3212]
**File:** Inquisition - Codex.catz

**BattleScribe version:** 2.10.65

**Platform:** Windows

**Dropbox:** Yes

**Description:** 1) The HQ slots is limited to one only, where as it should be 1HQ compulsory, and 1HQ more as optional. please rectify this problem

**Comment by tag8833** [comment]
The old inquisition detachment works fine.  There are 2 HQ slots.  Only 1 is required.
