### ISSUE TITLE
Space Marines - Pedro Cantor MIA

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3215]
**File:** Skitarii - Codex.catz

**BattleScribe version:** 2.00.14

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** When selecting Crimson Fists for Chapter Tactics, Pedro Kantar does not appear as an HQ choice. All other chapters appear to work fine

**Comment by FarseerVeraenthis** [comment]
I think this is related to #2768 which I'm in the process of trying to fix...
