### ISSUE TITLE
Space Marines - points cost issues

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3217]
**File:** Space Marines - Codex (2015).catz

**BattleScribe version:** 2.00.10

**Platform:** Windows

**Dropbox:** No

**Description:** Unit Point Costs Incorrect:

Shadow Captain Solaq is listed as 160pts, should be 130pts.
Land Speeder Darkwind is listed as 95pts, should be 75pts.

**Comment by FarseerVeraenthis** [comment]
Done, file version 2016 or later will include this fix.
