### ISSUE TITLE
Fire Raptor Gunship in CSM and Suppliments, Apoc Formation queries

### ISSUE THREAD

**Issue by NebSeele** [BSData/wh40k-7th-edition#322]
Hey. Is it possible to have the Fire Raptor added to the CSM repository (as well as supplements as I use?

Forgeworld currently has them listed as experimental (for csm now anyway, the loyalists had theirs added to Imperial Armour 2 2nd Edition) on the models page, and I intend to use a fire raptor when I get a copy of the model. 
While I can add a few entries to the catalogue myself, it does get overwritten every time there is an update so it is handy if it was added on the official file.

On an aside, as I intend to do a separate file for the apoc formations as local meta I play allows for the ones not heavily reliant on Apoc exclusive rules> I am aware it's not the same and personally agree, but some of the formations for chaos do look like they can be used without too much effort to patch the rules.

Would it be possible to upload the formations file here or would it be more efficient to roll it in the CSM/Black Legion/Crimson Slaughter and Daemons catalogues?

**Comment by amis92** [comment]
Wait, aren't these formations currently in catalogues? If they aren't, maybe just add them instead of creating new catalogues. As Battle Formations of course. If you want to add them to your rosters, just either use Apoc detachment, or unbound. :)

**Comment by NebSeele** [comment]
I am currently in the process of editing my local catalogue to add the battle formations, as well as probably move things around to better accommodate the formations and units without too much doubling up on certain entries.

I will add the Fire Raptor at the same time. When it's done I will probably need some help in uploading it here.

**Comment by amis92** [comment]
Cool. But are you editing the catalogue of your own, or the one from here?

You know, the earlier you start collaborating with us here, the easier it will be :) Did you check out Getting Started? There's a video tutorial there which explains it pretty well.

**Comment by NebSeele** [comment]
Originally I was going to write my own, however looking at what's involved with writing it from scratch I decided to modify the currently existing one. For the most part I had been doing it locally based on personal needs for local tournaments so I have picked up a few things slowly.

I was reading through the get started, I will give the vids a watch though :)

**Comment by NebSeele** [comment]
After watching the video tutorial and altering my local cat file to see how the file would work, Is it possible to get dev approval for github for the csm catalogue?
