### ISSUE TITLE
Add Enginseer and Servitors to Cult Mechanicus

### ISSUE THREAD

**Issue by ResidentSteve** [BSData/wh40k-7th-edition#3225]
Hello,

As of Codex Imperial Agents the Enginseer is a HQ with Cult Mechanicus faction and the Servitors are Elites choices. Could somebody kindly add to the Cult Mech lists, please?

**Comment by alphalas** [comment]
Update your data - I believe that was done a few comits ago

**Comment by ResidentSteve** [comment]
Definitey not in version 2008 I'm afraid - not on the PC so I can't check if it's just hidden either - sorry!

**Comment by Thairne** [comment]
The formation was added.
As of yet, Enginseer is only a possible HQ for the Grand Convocation which we do not have decided to how to implement it yet.

**Comment by ResidentSteve** [comment]
Ah, but because he's now faction Mechanicus, he should be available anywhere, CAD, formation, whatever. It's no different from if he'd been added as part of a Mechanicus dedicated supplement

**Comment by Thairne** [comment]
Fall of Cadia isn't even available in the most FLGS or GW Shops.

Give us some time... But if you have a source for me to work on until my FLGS stocks it...

**Comment by alphalas** [comment]
He actually has a point - we came to a similar conclusion with the inq stuff from C:IA - it's a HQ w/ faction CM - it can be used anywhere

**Comment by Thairne** [comment]
I'm not saying he doesn't have a point - im just saying that I need a source to work from :) A Rnd comment on here does not suffice to change the BSData.


Aaaand I noticed that I are actually in possession of C:IA.

**Comment by ResidentSteve** [comment]
Sure, I understand your reservation to alter the files.
The evidence I present is Codex Imperial Agents. It provides a datasheet for Servitors and Enginseers, lists their faction as Cult and battlefield roll.
The conclusion I have drawn is that as a Mechanicus unit, they should be available to the Cult Mech list.

**Comment by Thairne** [comment]
And they will be. You totally are right, the icon etc. is there.
There is just that trap that neither the HQ nor the servitors do only have the canticles in the Congregation Detachment.
