### ISSUE TITLE
Triumvirate Formation, Relics and entries

### ISSUE THREAD

**Issue by Thairne** [BSData/wh40k-7th-edition#3229]
We need to add those things into the GST.
The best solution I think is to add the entries for the 3 new HQ's, the relics, and the formation into the GST and hide them by default.
Then everyone that needs it can link it into their own CAT, unhide if certain criteria are met (or simply by default) and done, basically just like we did with Kill Team.

I for one will take care of the AdMech Relics, Cawl, and the formation once I have a source to work with.
Also my usual 4 catalogues.

Feel free to add your CAT's and your progress to this list.
Add to GST;
- [x] Cawl
- [x] Celestine
- [x] Greyfax
- [x] Triumvirate Formation
- [x] AdMech Relics
- [x] Ecclessiarchy Relics

Include Fall of Cadia into the following CAT files;
- [x] Skitarii
- [x] CultMech
- [x] Imperial Knights
- [x] Dark Angels
- [x] Space Wolves
- [x] Blood Angels
- [x] Grey Knights
- [x] Deathwatch **NB: Validation Incomplete**
- [x] Astra Militarum
- [x] Sisters of Battle
- [x] Inquisition
- [x] Space Marines **NB: Validation Incomplete**

Create detachment:
- [x] Castellans of the Imperium
- [x] Grand Convocation

**Comment by DrTobogganMD** [comment]
Has hide then show been fixed on ios? In BS1 that did not work - you had to show then hide.

**Comment by Thairne** [comment]
I have no idea, I don't own an iOS device either.
It's just the way one should implement things with the smallest chance to screw up :)

**Comment by DrTobogganMD** [comment]
Unless it isn't fixed then it screws up a good portion of the user base :p. 

~Earl Bishop
815-405-7187

**Comment by Thairne** [comment]
Someone with a fruity device should check ;)

**Comment by alphalas** [comment]
What am I checking with my fruits?

**Comment by Thairne** [comment]
hide an entry
then use a modifier to show it again
and see if it works on a fruity device

**Comment by alphalas** [comment]
yup my chamber militants work on fruits.

**Comment by Thairne** [comment]
That's fruity news!

**Comment by Thairne** [comment]
Cmon guys, get to work.. I've already done everything, you just need to link and show :P

**Comment by hisop** [comment]
@Thairne does this mean we need to wait until Castilians of the imperium will work for a bug to be resolved?

**Comment by Thairne** [comment]
Kind of, yes.
It seems like the entire constraints sets that work in "Roster" do not trigger and break the modifier.

**Comment by FarseerVeraenthis** [comment]
so I have literally dropped the triple threat and their flashy toys into the Wolves, Marines, and Deathwatch codecs - the validation is not complete for what replaces what and limits and so on but people can select them for now...
When I have more time I'll go through the book and figure out how to implement the validation rules properly, as well as checking out some of the other CAT's to see how they have been implemented there as well.

Shall we close and re-open for my validation or just leave this one open??

**Comment by CrusherJoe** [comment]
Does this mean you should be able to select Celestine et. al. in a Codex: Space Marines CAD? Because if you're supposed to be able to...you can't -- at least after updating data files from within BS.

Also...if this is the wrong place to report this make this comment, I apologize in advance.

**Comment by GenWilhelm** [comment]
@CrusherJoe, it was in at some point, but it seems to have gone AWOL. I'll get them back in tonight,

And yes, since this issue is still open, it's fine to comment in here.

**Comment by samaca** [comment]
While making a War convocation i noticed that the new arcana mechanicum are not free when they should be.

**Comment by Viper666-Qc** [comment]
About those 3 multi-factions detachments / formations: 
Castellans of the Imperium
Grand Convocation
War Convocation

Would it be easier to create 2 new Catalogues (Castellans of the Imperium, Adeptus Mechanicus (combined)) just like the new Ynnari Aeldari catalogue?

**Comment by alphalas** [comment]
No - FW options would make those files unloadable on anything but pc due to size

- Jon[K]

**Comment by Viper666-Qc** [comment]
You mean the FW units (Astra Militarum & Space Marines)?
You can't add FW units to those detachments right? (apart for the Cerastus Knights as LOW) 

The Space Marines options would still make it too bloated?
And there's no FW options for the Adeptus Mechanicus apart the FW Knights....

**Comment by alphalas** [comment]
Upgrades and dedicated transports - we would have to add practically the entire SM cat to it.

**Comment by Viper666-Qc** [comment]
Ok so a Castellans catalogue seems a no go but why not for a combined Adeptus Mechanicus? the 3 codice entries together still seem less than the SM ones with FW stuff

**Comment by alphalas** [comment]
You'd have to ask @thairne about that

**Comment by alphalas** [comment]
However this is a discussion best left to the Gitter.

**Comment by Viper666-Qc** [comment]
Well, you may still think about those kind of catalogues for the future because it seems it's the new GW way and when (well...if) FW will update its stuff for the Eldar to include it for the Ynnari, you'll get the same problem then

**Comment by alphalas** [comment]
As I said, please take this line of discussion to the Gitter chat

**Comment by KealL** [comment]
I'm not sure the FW knights would be a valid option. It's not like it's "a AM/SM LOW" it is specifically these LOW:, A, B, C etc

**Comment by KealL** [comment]
@alphalas 
how do I join a gitter chat?

**Comment by GenWilhelm** [comment]
@KealL https://gitter.im/BSData/wh40k

**Comment by Randobar** [comment]
should the latest BS Update make this possible to solve?

**Comment by alphalas** [comment]
If you want further updates please join us on Gitter

**Comment by KealL** [comment]
Grand Convocation doesn't seem to be working, i i load it via Cult it shows only cult units, if i show by Skitarri it shows only skitarri and lists the three imperium heroes

**Comment by alphalas** [comment]
You have to load both halves at the same time - you can't load one or the other

**Comment by KealL** [comment]
okay, then the validations don't work and Celestine and Greyfax need removing

I've added  skitarri units but it still says I need 4 troops

**Comment by alphalas** [comment]
Did you check the troops box that shows up on the squads?

**Comment by Thairne** [comment]
Cawl, Celestine and Greyfax ain't working yet for validation purposes. Didn't figure out a way yet to make them work elegantly. Still, getting it out there in that state seemed to be prudent.

Also, it only works with .13 and up.

**Comment by Thairne** [comment]
With the other issue open... we can finally put FuC to rest.
