### ISSUE TITLE
Id like to write up the old squats files for warhammer 40k [Join Request]

### ISSUE THREAD

**Issue by SamuraiJordan** [BSData/wh40k-7th-edition#3236]
Howdy,
Id like to learn how to edit these files, on my own but help is appreciated, and get the old squats information up to date and added to my own personal and public data file repository for battlescribe.
Thank you,
Jordan

**Comment by FarseerVeraenthis** [comment]
If you've ended up here then you're well on the way... 
As a suggestion, open the data editor, open one of your existing CAT files and have a play.
Once you understand how it works you should be able to start writing a new one for the Squats.
If you need help, I suggest joining the chat on gitter, then you can speak to people directly...

**Comment by cartag** [comment]
Squats would not be added to this though. You can do your own repo, but this one is just for RAW, only legal units in them, nothing fan made.

**Comment by amis92** [comment]
@SamuraiJordan as **cartag** said, we surely won't host these files here in this repo, but you might want to keep going with it and keep an eye on https://github.com/BSData/bsdata/issues/111
