### ISSUE TITLE
Great Unclean One limited to 1, 40k chaos daemons

### ISSUE THREAD

**Issue by gwarsh41** [BSData/wh40k-7th-edition#324]
When creating a Chaos daemons combined arms detachment with 2 greater unclean ones. There is an alert that greater unclean ones are limited to a maximum of one.

**Comment by amis92** [comment]
Hmm interesting, always thought it's unique. Turns out it's not! :)

**Comment by Thairne** [comment]
Fixed. No more limitations on the dude that needs a bath!

**Comment by senpai514** [comment]
@Thairne I need this commit so I can work on the demon codex. have you pushed it up?

**Comment by Thairne** [comment]
My apologies.. Wasn't aware I had to sync the change after comitting. Did so, should be in the repository now.
