### ISSUE TITLE
Belisarius Cawl Not Available

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3241]
**File:** Skitarii - Codex.catz

**BattleScribe version:** 2.00.22

**Platform:** Android

**Dropbox:** No

**Description:** Belisarius Cawl should be available as an hq in all armies of the imperium

**Comment by FarseerVeraenthis** [comment]
Thank you for your helpful insight.
Please let me remind you that the data authors are volunteers who don't get paid and don't work for games workshop, therefore, we only have the rules when everyone else gets them, and we spend our personal time to update the files.
Additionally, Fall of Cadia contains a number of very complex formations which are currently nearly impossible to implement "properly" in battlescribe... 

Please be patient.
Refer to #3229.
