### ISSUE TITLE
Chaos Space Marines - Roster Creation Problem

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3244]
**File:** Chaos Space Marines - Codex.catz

**BattleScribe version:** 2.00.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Cannot make CHaos Space Marine lists. After selecting detachment, even unbound, program says "creating roster" and just spins.

**Comment by alphalas** [comment]
Purge data and re download- might be a local memory issue on your device
