### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by Thairne** [BSData/wh40k-7th-edition#325]
Hi,

I'd like to contribute to the Battlescribe 40k data files. While I'm mostly focusing on Dark Angels myself, once I get a hang of how this works I will try and keep other armies updated from issues I see.
I'm a software dev (and totally unfamilliar with GitHub and the workings of it, I use Subersion with a Tortoise Client) so I guess I will work it out in time ;)

**Comment by amis92** [comment]
Hi,
invitation sent. If you use Tortoise, AFAIK there is Tortoise Git - however I think for what we do here, GitHub app is just... better suited (less options, but all we need). Welcome!

**Comment by Thairne** [comment]
Thanks for the welcome, I experimented a bit with my own branch and I think I get the basics. Now on to work ;)
