### ISSUE TITLE
Space wolves wargear issue

### ISSUE THREAD

**Issue by WeBerion** [BSData/wh40k-7th-edition#3260]
Option "Pair of wolf claws" is missing in melee weapon section for thunderwolf cavalry

**Comment by FarseerVeraenthis** [comment]
I'm not convinced Thunderwolf cavalry can take a pair of Wolf claws... how can you ride a Wolf without hands...?
Anyway, I'm not the rules God and if you can justify it then I'll put the option back in...

**Comment by alphalas** [comment]
![img_0367](https://cloud.githubusercontent.com/assets/15703066/22083673/20a3dcee-dd9b-11e6-8812-c3a31d039418.PNG)
![img_0368](https://cloud.githubusercontent.com/assets/15703066/22083674/20afc69e-dd9b-11e6-8a0c-a40cb1e09be0.PNG)

No, wolves may not have twin claws

**Comment by FarseerVeraenthis** [comment]
Further to discussion on Gitter, this will option be reinstated shortly...
