### ISSUE TITLE
Space Wolves - Thunderwolf Cavalry Issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3261]
**File:** Space Wolves - Codex.catz

**BattleScribe version:** 2.00.23

**Platform:** Android

**Dropbox:** No

**Description:** Thunderwolf cavalry pack leader still forced to take ranged weapon.

**Comment by FarseerVeraenthis** [comment]
This is fixed in file version 2023.
Please update your data.

**Comment by jbickb** [comment]
I'm on 2024 and the pack leader still cannot sekect none on his bolt rangedcweapon

**Comment by FarseerVeraenthis** [comment]
Hmmm... Pesky Wolves! I'll have a look, I suspect it is to do with the way the pack leader is equipped...

**Comment by GenWilhelm** [comment]
This was fixed in de1b34bb97e9f3f9596e03bdfdfb05a1d93c8075.

**Comment by jbickb** [comment]
So it is fixed for the base calvary, but the pack leader still cannot get rid of his  bolt pistol as of version 2024

**Comment by GenWilhelm** [comment]
Correct, the commit referenced above is for v2025. It will be out with the next release, probably tonight or tomorrow.

**Comment by jbickb** [comment]
Ah my bad I misunderstood. Thanks man!
