### ISSUE TITLE
Chaos Space Marines - Start Collecting Box Formation Missing

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3262]
**File:** Chaos Space Marines - Codex.catz

**BattleScribe version:** 2.00.23

**Platform:** Android

**Dropbox:** No

**Description:** I can't find the Start Collecting box formation under Chaos Space Marines

**Comment by FarseerVeraenthis** [comment]
What is it called?

**Comment by GenWilhelm** [comment]
It's called Wrathborn. It's the very last entry under Formations.
