### ISSUE TITLE
Inquisition - Henchmen Base Cost Issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3268]
**File:** Inquisition - Codex.catz

**BattleScribe version:** 2.00.23

**Platform:** Android

**Dropbox:** No

**Description:** Base cost of the inquisitorial henchmen warband should be 12p ( 1 unit of 3 acolytes, 4 points each) instead of 24

**Comment by kuraudo** [comment]
OP here (I didn't remember I had an account, duh), for clarification I'm talking about the formation in C: IA
Cheers!

**Comment by FarseerVeraenthis** [comment]
I looked at the data but I really don't understand why the points are all crazy...
@alphalas put the formation together so perhaps it's best for him to have a look...

**Comment by kuraudo** [comment]
If you select the same item ( ihw) in a CAD, the default base cost is 0 but it changes to 24 in a formation detachment. Maybe it's related

**Comment by alphalas** [comment]
I'll have a look at it when I can
