### ISSUE TITLE
Cawl Missing from Cult Mech

### ISSUE THREAD

**Issue by noobzilla99** [BSData/wh40k-7th-edition#3269]
I realize that you guys are working on this issue with the Fall of Cadia entirely, but just a heads up that Cawl is missing from the Cult Mechanicus catalog for CAD's, Battle Congregations, War Convo's, etc, etc...

The work you guys do is appreciated! :D

**Comment by Thairne** [comment]
No he's not.

![grafik](https://cloud.githubusercontent.com/assets/8590840/22110902/b7c66ba6-de5d-11e6-9917-296005a0365e.png)

**Comment by noobzilla99** [comment]
I have a mobile version, and he is not showing up, despite that I have the v2009 version of CM.

![photo jan 19 10 41 19 am](https://cloud.githubusercontent.com/assets/16530180/22115837/24dd08be-de34-11e6-8068-d7b93fc10b2b.png)
![photo jan 19 10 41 56 am](https://cloud.githubusercontent.com/assets/16530180/22115838/24e23dca-de34-11e6-9c4a-7b5f2565a38b.png)

**Comment by FarseerVeraenthis** [comment]
He's not showing on Android either :-(

**Comment by Thairne** [comment]
ah not that again.
HE is default hidden and is being shown in the respective cats.
Since it works on desktop and this issue FEELS VERY FAMILIAR *grunt*.... BS Bug.

**Comment by Thairne** [comment]
we had it confirmed however that hide, then show works on iOS...
The other HQ's are not there either.
The condition works in principle, so something breaks it on mobile V's. What that is however..
The implementation is very simple and works on desktop.

**Comment by noobzilla99** [comment]
What's odd is that he shows up in the skitarii cad tho

**Comment by Thairne** [comment]
the implementation is exactly the same... WEll, except for a condition, which neither celestine nor greyfax have.

**Comment by FarseerVeraenthis** [comment]
What's funny is that none of the three show up for Cult Mech when you try to build a CAD...

**Comment by Thairne** [comment]
and what makes you "die with laughter" is that he DOES show up in Skitarii... when NOTHING visible is different!

**Comment by SSSlippy** [comment]
This seems to work on iPhone app and works on PC version for me.  Had to delete my data files and download a new copy to get it to work on PC.

**Comment by Thairne** [comment]
This is getting weirder and weirder..

**Comment by Thairne** [comment]
Wait. Could it be that I simply forgot to increment the version number?

**Comment by Thairne** [comment]
So I bit the bullet, installed BS on my phone and tried a CAD.
Cawl is there.
Likely a non-incremented version no. on my part.
