### ISSUE TITLE
Deathwatch - Librarian missing Bolt Pistol Option

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3274]
**File:** Deathwatch - Codex.catz

**BattleScribe version:** 2.00.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Lib no longer have option to select a Bolt Pistol.

**Comment by FarseerVeraenthis** [comment]
I think I know what's happened here, his weapon selection is linked to a Selection Group which used to include the bolt pistol, but no longer does...
I'll try to fix it later this evening.
