### ISSUE TITLE
The new Foc stats.

### ISSUE THREAD

**Issue by MidnightFrawg** [BSData/wh40k-7th-edition#3275]
I have downloaded battle scribe on my Iphone and PC. On the Iphone The new Foc characters Saint  Celestine, and and Belisarius cawl show up on my phone but not inquisitor greyfax, On the pc, I only get Belisarius cawl. Am I doing something wrong? Is there something I need to be doing for them to show up? I have the Warhammer 40k filed installed.

**Comment by alphalas** [comment]
What catalog were you using?

**Comment by MidnightFrawg** [comment]
I looked to see the catalog I was using. I realizes I didn't have the index.bsi that was in front of my face, Thank. I just had the Warhammer40K.gstz

**Comment by MidnightFrawg** [comment]
I do want to know though If there is way to save your roster between your phone and computer.

**Comment by MidnightFrawg** [comment]
wonder why it shows celestine and grefax under Mechanicus.

**Comment by francoisbeaulieu** [comment]
Through the built-in Dropbox integration.

--
François Beaulieu (iPhone)
(514) 667-0691 x2061

**Comment by MidnightFrawg** [comment]
Thanks fan for the reply.
