### ISSUE TITLE
Bug report: Space Wolves - Codex.catz - Long Fangs

### ISSUE THREAD

**Issue by christhack12** [BSData/wh40k-7th-edition#3277]
The Long Fang Ancient has to swap his Chainsword for any special weapon in the current data file where as in the rules he can take a special weapon in addition to his bolt pistol and chainsword.

**Comment by FarseerVeraenthis** [comment]
No, he cannot.
The "Special Weapons" entry in the Wargear list specifically states that "A model may replace his Melee weapon or his boltgun with one of the following".
He does not have a boltgun to replace with a special weapon, therefore, he must replace his chainsword.
