### ISSUE TITLE
Space Marines - Roster opening issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3282]
**File:** Space Marines - Codex (2015).catz

**BattleScribe version:** 2.00.10

**Platform:** Android

**Dropbox:** No

**Description:** Opening any Roster from the Blood Angels, Adeptus Sororitas, or Space Marine codex, or with any of the new formations from the chaos space narines supplement returns the same error: Theres a problem with one or more of your datat files.
All thr units seem to be in there appropriate places, but when I view the roster, no profiles or stats appear. 

Ive already tried, re installing bscribe. Ive already tried purging data and redownloading, and ive already tried updating the data files....

**Comment by FarseerVeraenthis** [comment]
where did you get the Rosters from??
If they're from BS 1.15 - they won't work.
If you already created them in BS 2, it might be because the CAT's have been updated and things in the data have moved.

Please try a brand new roster from scratch.

Also, my Android BS version is 2.00.23...

**Comment by alphalas** [comment]
also make sure your android device is not running BS in "Low memory Mode", that has caused issues before.

**Comment by FarseerVeraenthis** [comment]
No reply from Anon, closing.
