### ISSUE TITLE
Sanguinary guard death masks

### ISSUE THREAD

**Issue by IronWulfen88** [BSData/wh40k-7th-edition#3290]
There is no option to choose how many death masks the squad can get. Just a box to check to outfit the whole squad. Can we have it to where it has a number selector like the weapons.

**Comment by ChristianStiehl** [comment]
The option for Death Masks is for the entire squad only. Either all have them or none do, not a bug.

**Comment by IronWulfen88** [comment]
in the codex it says you can take a death mask for one point a model not that the whole squad had to take it.

**Comment by alphalas** [comment]
![img_0411](https://cloud.githubusercontent.com/assets/15703066/22172011/a7b454e0-df6a-11e6-96c1-3302cc3b9fb0.PNG)
Pretty clear there.

**Comment by Flashpoint-** [comment]
Nice find !
