### ISSUE TITLE
Orks - Shoota Upgrade Cost Calculation Issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3292]
**File:** Orks - Codex.catz

**BattleScribe version:** 2.00.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** When issued «shootas for mob» to «Boyz», their value more. The program considers not only the Boys, but Nob and Boys with a heavy weapon.
thx

**Comment by tag8833** [comment]
That is how the codex rules have it.  It sucks, but that is on GW.
