### ISSUE TITLE
Bug issues: Fortifications/ Stronghold Assault/ Planetary Onslaught

### ISSUE THREAD

**Issue by TDog117** [BSData/wh40k-7th-edition#3293]
This is actually 3 issues.
Firstly: 
As of the release of Planetary Onslaught, on page 78 under the faction sub-header it makes clear reference that fortifications can be taken in any detachment.

The only way to do that in battlescribe right now is to take fortifications as an unbound option, which is essentially wrong.

I know before battlescribe had a work around using a fortification detachment, it actually might be worthwhile to reintegrate that.

Secondly:
When I take a fortification via the unbound option, it makes the list invalid because it tells me I haven't included all the fortifications available in the list to my army.

Thirdly:
The list for fortifications in unbound has a double entry for the following:
Aegis Defense Line, Aqulia Strongpoint, Fortress of Redemption, Honored Imperium, Imperial Bastion, Plasma Obliterator, Primus Redoubt, Promethium Relay Pipes, Skyshield Landing Pad, and the Void Shield Generator

![battlescribe_errors_01](https://cloud.githubusercontent.com/assets/9887552/22174622/fc7e2078-dfb0-11e6-95ab-5649513ea1b3.jpg)

**Comment by DrTobogganMD** [comment]
As for your First Point, that is incorrect. Re-read that page.  In fact, here's the note you reference:

![image](https://cloud.githubusercontent.com/assets/16939161/22174667/9a9b7056-dfa9-11e6-8e8a-03db1ae9c70c.png)

You failed to read the top of the page though:

![image](https://cloud.githubusercontent.com/assets/16939161/22174675/b679c822-dfa9-11e6-8db1-e0ae52fbee7f.png)

Fortifications use a fortification slot on the Force Org Chart.  If your Detachment doesn't allow them, you don't get them. End of story.

With Planetary Onslaught we modified the detachments that allow fortifications to include a single slot for them.

Points 2 and 3, your data is duplicate/corrupt - purge and reload data.
