### ISSUE TITLE
Bug issue: Pedro Kantor MiA from the strikeforce command option in a sterhammer strikeforce

### ISSUE THREAD

**Issue by TDog117** [BSData/wh40k-7th-edition#3294]
I believe this post is going to probably be redundant as I've seen similar issues with Pedro being MiA from IF related things has been an ongoing issue.

In this instance, I've taken a sterhammer strike force, added the IF chapter tactics, and added a strikeforce command option to the list.

Going through the available option for characters to use from the list Pedro isn't available, but Lysander is.

I have attempted to see if this changes if you take the CF chapter tactics option instead, but no difference, save for that Lysander no longer shows up either and the list becomes invalid because it requires the Sternhammer strikeforce to use IF chapter tactics.

I believe part of this issues stems from the recent addition that made there be both IF and CF chapter tactics options in battlescribe. 

It probably needs to be removed and CF and IF brought back under being IF chapter tactics alone.

With the release of Angles of Death, the only thing that CF's got to make them unique is that they now have their own warlord traits table, which if you're using CF's they're supposed to roll on rather than the IF chapter tactics table that was also in Angels of Death. They're still IF's and should have access to the sternhammer, with Pedro being a stikeforce command choice in it.

For people wanting to use the CF warlord traits, it should be a sub header under the warlord traits tab, rather than chapter tactics.

![battlescribe_errors_02](https://cloud.githubusercontent.com/assets/9887552/22174787/6ff034c6-dfb4-11e6-983e-0760a355b07c.jpg)

**Comment by Randobar** [comment]
Sadly Pedro is not a valid Commander for a Sternhammer. He was left out from the selection in angels of death, for some reasons only GW knows (i guess Obsec Sternguard Spam with massive rerolls)

**Comment by amis92** [comment]
I think that means we can close it.
