### ISSUE TITLE
Deathwatch - Error with Veteran Squad Number

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3299]
**File:** Deathwatch - Codex.catz

**BattleScribe version:** 2.00.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** In the Deathwatch codex entry for Veterans it states that the starting squad size is 5 Veterans and that you can add an additional 5 Veterans giving you a maximum squad size of 10 Veterans. Your data file shows an error when you try to add more than 5 Veterans.

**Comment by flakpanda** [comment]
I cannot reproduce the error. Please make sure you have the most recent
versions and reload the data. If error persists, please reply with a screen
cap.

**Comment by FarseerVeraenthis** [comment]
I can't reproduce this on Android either

**Comment by FarseerVeraenthis** [comment]
I can't reproduce this on Desktop either...
Purge and reload.
