### ISSUE TITLE
Space Marines - Terminator Points Cost Issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3316]
**File:** Space Marines - Codex (2015).catz

**BattleScribe version:** 2.00.10

**Platform:** Windows

**Dropbox:** No

**Description:** The Battlescribe entry says a Terminator with a heavy weapon is 45 points. In the codex, each Terminator is 35 points. There is no extra point cost for the Terminator itself, only the weapon.

**Comment by FarseerVeraenthis** [comment]
which file version are you on?
I'm looking at 2018 and they are only 35 points.
Purge and reload (once I've released it later tonight of course).
