### ISSUE TITLE
Inq - Sororitas rhino

### ISSUE THREAD

**Issue by deanofcool** [BSData/wh40k-7th-edition#3317]
Acolytes are listed with no weapons as default, and should be las pistol and chain sword. 
Acolytes with special weapons only have single weapon choice, when should be able to change either for anything, e.g. Melta and boltgun.
Acolytes armour is 2 for carapace and 5 for power, and inquisitors are 3 for power. 
Rhinos are now soriatas rhinos and as such have shield of faith special rule (6+ inv).
Vehicles have searchlights at no additional cost and additional storm bolters now cost 5. 
Perhaps some other points have changed too, will get back to you with more if I find em. Thanks.

**Comment by amis92** [comment]
@alphalas reason?

**Comment by alphalas** [comment]
We were discussing on Gitter - determined it was a combination of old data and slight opperator error.

**Comment by deanofcool** [comment]
Operator error? There is no operator error. The problems are still there.

Dean

**Comment by FarseerVeraenthis** [comment]
Even with file version 2016?

**Comment by deanofcool** [comment]
Yep. Let me straighten the record. I select the listing for C:IA. Then in elites there are entries for acolytes, and for warband. The values in acolytes are accurate for troops but not vehicles. But you can't add jokaero etc because it's just acolytes. And the entry for warband has joakaero etc as options, but values are all wrong. In both instances razorbacks are still listed, and they are both C:IA listings. I'm not wrong. Files have updated, now says 2016.

**Comment by FarseerVeraenthis** [comment]
Righto, per Gitter convo, I'll try and look into it tonight and provide some clarity :smile:

**Comment by deanofcool** [comment]
Cheers:)

**Comment by alphalas** [comment]
@deanofcool if you can hop on Gitter I'll explain how to fix the issue

**Comment by alphalas** [comment]
Alright, here's how you get the C:IA Warband, which is different from the inquisition Warband.

First, add a new force - 
![img_0422](https://cloud.githubusercontent.com/assets/15703066/22302471/f31b1b54-e2fc-11e6-9bca-fd6c5f7e4731.PNG)

Make sure you select the formation detachment.
![img_0423](https://cloud.githubusercontent.com/assets/15703066/22302495/11e4d926-e2fd-11e6-912e-65e4db7018c7.PNG)

You'll then see this warband in the formation selection slot. When you open it, it'll look like this:
![img_0424](https://cloud.githubusercontent.com/assets/15703066/22302529/35fa5192-e2fd-11e6-9c83-690e27c3375e.PNG)

All options are there - and if you select the correct type of inquisitor you'll even see the option for you to select a chamber millitant squad.

Just to confirm, this is the acolyte's loadout option from that selection 
![img_0426](https://cloud.githubusercontent.com/assets/15703066/22302615/7c679608-e2fd-11e6-886b-57e97be8222c.PNG)

And the dedicated transport options 
![img_0427](https://cloud.githubusercontent.com/assets/15703066/22302624/8c393992-e2fd-11e6-814c-a7f3cabc6cd1.PNG)

As you can see, it's all there.

**Comment by deanofcool** [comment]
Yep, got that, it helps a lot thanks, but vehicle storm bolters are still listed as 10pts not 5, and searchlights as 1pt instead of no cost.

Dean

**Comment by alphalas** [comment]
That is resolved in v17 or 18, don't remember which

**Comment by deanofcool** [comment]
And on other listing storm bolters come up as no cost, which is fine by me, but not my group;)

**Comment by deanofcool** [comment]
How do you upload image and I'll show you.

**Comment by alphalas** [comment]
On iOS? Click on github where it says attach files by drag and drop or by selecting them

**Comment by deanofcool** [comment]
Dean

**Comment by deanofcool** [comment]
Click on GitHub where?

**Comment by deanofcool** [comment]
Did you get image?

**Comment by alphalas** [comment]
![img_0428](https://cloud.githubusercontent.com/assets/15703066/22304841/2d79e014-e307-11e6-95aa-03cd89b91b13.PNG)
Click the hyperlink there

**Comment by deanofcool** [comment]
![img_4132](https://cloud.githubusercontent.com/assets/25331277/22305719/7738f622-e334-11e6-8a0a-b969dca4e7ee.PNG)

**Comment by alphalas** [comment]
Yeah that'll be fixed in the next release

**Comment by deanofcool** [comment]
![img_4133](https://cloud.githubusercontent.com/assets/25331277/22307319/68d25744-e33a-11e6-8466-d3cae4862104.PNG)

**Comment by deanofcool** [comment]
Here's the one from the acolytes listing

**Comment by alphalas** [comment]
Hmm that's funky

**Comment by ghost** [comment]
I spoke to you, alphalas, over twitter and on gitter. This is the same issue I encountered but I want to add some more.
I'm using the non-C:IA henchman band selecting the Inquisitorial Detachment (Inquisition Codex 2013 v2016)

1) When you select acolytes and give them an acolyte weapon such as a bolter for 1pts from the acolyte armory it should replace either a chainsword or laspistol
2) When selecting an acolyte with an inquisitorial armory item, it should also replace either a laspistol or chainsword
3) It should be possible for an acolyte to take a weapon from the acolyte armory and another from the inquisitorial armory, replacing both the chainsword and laspistol. For example an acolyte with a powerfist AND a bolter
