### ISSUE TITLE
Khorne Daemonkin - Missing FW Units

### ISSUE THREAD

**Issue by Guardbuddy** [BSData/wh40k-7th-edition#3319]
Problem: Khorne Daemonkin is missing a couple of units from FW.  They were confirmed to be usable as long as it is Khorne alligned/had the ability to take Mark of Khorne.

Units:
-Greater Brass Scorpion
-Blood Slaughterer of Khorne

**Comment by cartag** [comment]
No, there has been zero confirmation from FW regarding them in a KDK army outside of Blood Oath formations. Closing.
