### ISSUE TITLE
Where did the stronghold assault fortifications go?

### ISSUE THREAD

**Issue by aDarKy** [BSData/wh40k-7th-edition#3321]
Hi,

Where did the stronghold assault fortifications go? Doesn't seem to be available anymore.

**Comment by alphalas** [comment]
They are now built-ins for the detachments that can take them

**Comment by aDarKy** [comment]
Does that mean if I run two formations for example emperors wrath and
emperors blade; I cannot bring a standalone Aegis defence line?
I think I know what the answer is but just wanted to clarify

**Comment by FarseerVeraenthis** [comment]
If there is not a fortification slot in the formation then no :-)

**Comment by alphalas** [comment]
Which is exactly rules as written
