### ISSUE TITLE
space wolves terminator issue

### ISSUE THREAD

**Issue by IronWulfen88** [BSData/wh40k-7th-edition#3329]
The heavy flamer option for the termies is missing and accordign to the wulfen edition of the codex which I have in front of me right now and the latest faqs they should still get it. Im currently waiting for a reply from GW through my local warhammer shop just to be certain.

**Comment by alphalas** [comment]
Evidence of this? I'm looking at the FAQ now.

**Comment by alphalas** [comment]
Because I have a copy of wulfen edition right now and there is no option for HF for the terminators

**Comment by IronWulfen88** [comment]
one moment I have to send the pic to my computer

**Comment by cartag** [comment]
I see the option for them to take a heavy flamer in the first version of the codex, but not the Wulfen edition. It's since been updated, no heavy flamer allowed on heavy weapon option, just replace Storm Bolter with assault cannon or take a cyclone missile launcher.

**Comment by IronWulfen88** [comment]
WS	BS	S	T	W	I	A	Ld	Sv	Unit Type	Unit Composition	
				Wolf Guard Terminator	4	4	4	4	1	4	2	9	2+	Infantry	2 Wolf Guard Terminators	Wolf Guard	4	4	4	4	1	4	2	9	2+	Infantry (Character)	1 Wolf Guard Terminator LeaderTerminator Leader
			
		
		
			
				WARGEAR:
				Terminator armour
				Storm bolter
				Power weapon
			
		
		
			
				WOLF GUARD TERMINATORS

**Comment by IronWulfen88** [comment]
One sec it's not loading

**Comment by IronWulfen88** [comment]
![screenshot_20170126-202324](https://cloud.githubusercontent.com/assets/22039355/22357338/59038cd6-e405-11e6-9d11-8847caebf32f.png)

**Comment by IronWulfen88** [comment]
This is from the one I bought today

**Comment by alphalas** [comment]
And it's the ePub?

**Comment by IronWulfen88** [comment]
yes I bought it from black library

**Comment by FarseerVeraenthis** [comment]
Naughty little puppies...

**Comment by GenWilhelm** [comment]
It would be nice if GW were a little more transparent with this type of thing...

**Comment by IronWulfen88** [comment]
okay my local warhammer shop checked into it and the heavy flamers are still good to go on wolf guard termies he says after checking with GW

**Comment by DrTobogganMD** [comment]
"My Local Shop" isn't exactly a reputable source :/ Post to FB - see what they say.

**Comment by Gnofry** [comment]
Okay, so this is a bit silly. It is ridiculously obvious that this is a mistake by GW, the weapon option is in the current kit. The updated ePub lists the HF as being an option, the physical codex that they still sell lists it as being an option. It should be an option in the datafile. 

Whichever author changed it based on their epub should simply redownload the codex, check to see that it has been corrected, and change the datafile.

**Comment by alphalas** [comment]
While I mostly agree with you, gnofry, we do have some SOPs we are to adhere too. Some of us newer guys might not see the point, but that's why we still have the old pros like Amis.

**Comment by Gnofry** [comment]
Alright, let me reformat this.

1) Data author purchases Codex: Space Wolves Wulfen Edition v1
2) Data author makes changes to the datafile based on Codex: Space Wolves Wulfen Edition v1
3) Codex: Space Wolves Wulfen Edition v1 has mistakes and is updated to v2 by GW
4) Data author is notified of the update by a Github issue
5) Data author downloads Codex: Space Wolves Wulfen Edition v2
6) Data author makes changes to the datafile based on Codex: Space Wolves Wulfen Edition v2

It shouldn't be a question of SOPs or talking to GW, its literally do the same thing as you did before, but with the updated version.

**Comment by IronWulfen88** [comment]
ill post to facebook to check this out but ive talked to several of my buddies across the space wolves forums and they say they have that option in their volumes. Ill get back to you all as soon as possible when I get an answer.

**Comment by IronWulfen88** [comment]
okay I havent gotten word back from GW but what I can tell from all the space wolves players I have talked to here in Tennessee and from what Mik at my warhammer shop said after talking to them the wolf guard termies are still able to take the heavy flamer. but I did come accross something interesting after a a conversation with one individual. apparently the wulfen edition has some issues with some epub readers and looses some data. He had to try a few before it worked right. might want to check into that a bit more that could be the issue.

**Comment by Ragnarok2070** [comment]
When will this issue be resolved. If you have a hard copy of the codex or the most recent Games Workshop digital copy, the heavy Flamer option for Wolf Guard in Terminator armour has not changed, for every 5 models in a squad, 1 may replace it's storm bolter with an Assault Cannon or Heavy Flame Thrower. Can this issue please get fixed.
