### ISSUE TITLE
Cult Mechanicus - Cawl as HQ, Archana Mechanicums Wargear Missing

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3336]
**File:** Cult Mechanicus Codex 2015.catz

**BattleScribe version:** 2.00.10

**Platform:** Windows

**Dropbox:** No

**Description:** When creating a formation with cawl as an HQ (such as a Conclave Aquisitorius) the archana mechanicums from the fall of cadia books are not available as choices for the other hq's.

**Comment by FarseerVeraenthis** [comment]
aaaahhh.... does this mean Cawl is now showing in Cult Mech though...??

**Comment by Thairne** [comment]
On windows he always did

**Comment by Thairne** [comment]
This issue seems to be, again, a BS bug concerning the selections in Roster Mechanic.
It shows in some cases but not in others, where reading the implementation should work in both ways.

We already have a bug reported that could very well fix this issue.

**Comment by Thairne** [comment]
<--- stupid

**Comment by Thairne** [comment]
Fixed (and forgot the closes again)
