### ISSUE TITLE
Pelstat Alpha Galvanic Caster ranged weapon missing

### ISSUE THREAD

**Issue by laurent-conte** [BSData/wh40k-7th-edition#3338]
It is not a big bug: the Alpha Pelstat comes with a Galvanic Caster by default but we can't select it in the ranged weapon list (we can with rangers and Vangards Alpha for their respective standard weapons).

**Comment by FarseerVeraenthis** [comment]
edited - oh, Forgeworld, yeah these guys are nasty...
