### ISSUE TITLE
Eldar Corsairs - Issues with Cloud Dancer Felarch Weapon Selection

### ISSUE THREAD

**Issue by jpazdera** [BSData/wh40k-7th-edition#3343]
I noticed two issues with the Cloud Dancer Felarch rules for Eldar Corsairs. 

First, Cloud Dancer Felarchs are allowed to exchange their brace of pistols for up to two hand weapons, while they are currently listed as only being able to take 1 hand weapon in Battlescribe.

Second, dissonance pistols actually cost 15 points each for Cloud Dancer Felarchs. They are currently listed as costing 10 points. Although all other dissonance pistols in the army cost 10 points each, the Cloud Dancer Felarch must instead pay 15.

Both rule corrections come from page 165 of the Doom of Mymeara book.

**Comment by FarseerVeraenthis** [comment]
Hmmm... which file version are you using??
On Android, in v2004, the Felarch can take 2 weapons once he has given up (deselected) his brace of pistols, this is as per the Book. It is stated at the top of the selection area "1 required", but this is as a minimum, it could be re-worded to make this clearer but the validation is correct.
I will update the cost of the Dissonance Pistol.

**Comment by jpazdera** [comment]
Ah, I must have missed that it updates when you remove the brace of pistols. My mistake!

Thanks for updating the Dissonance Pistol.
