### ISSUE TITLE
Deathwatch - Dedicated transports missing from Watch Company Formation

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3344]
**File:** Deathwatch - Codex.catz

**BattleScribe version:** 2.00.24

**Platform:** Android

**Dropbox:** No

**Description:** Watch Company formation with veteran selection should be able to take drop pods
as drop pods are a dedicated transport option for them.

**Comment by FarseerVeraenthis** [comment]
Argh!! I know what has happened here, I'll try and have a go at it this week...
