### ISSUE TITLE
Imperial Knights: Heirlooms / Relics selection issue

### ISSUE THREAD

**Issue by Bparks1983** [BSData/wh40k-7th-edition#3359]
File: Imperial Knights: Codex (2015) v2008

BattleScribe version: 2.00.24

Platform: Android

Dropbox: No

Description: Knights selecting either Ravager or The Paragon Gauntlet do not have their melee weapon replaced or the option to remove them, leading to an error of too many weapons.  Also, Ecclesiarchy Relics are displayed by default, even when St. Celestine is not present.

**Comment by Thairne** [comment]
Sounds easy enough, but requires an entire rework on how weaponry on all knights are implemented and in consequence some bloat in the file...
But I managed.
