### ISSUE TITLE
Adeptus Astra Telepathica - Celestine & Geminae Issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3363]
**File:** Adeptus Astra Telepathica.catz

**BattleScribe version:** 2.00.24

**Platform:** Android

**Dropbox:** Yes

**Description:** Celestine seems to have reverted to her pre fall of cadia version. Plus there is no option for her Geminae Superior.

**Comment by pretzalcohuatl** [comment]
Wrong catalogue.  "Saint Celestine" is as-printed in codex/pre-FoC.  "Celestine, The Living Saint (FoC)" is the FoC profile.

However, both units have a model Saint Celestine with composition 1 (Unique) so I guess that's "you can't take both" by RAW.
