### ISSUE TITLE
Tau - Fusion Blade Cost Issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3364]
**File:** Tau - Codex (2015).catz

**BattleScribe version:** 2.00.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Fusion blades for farsighted enclaves is 30 pts in the codex supplement and it shows 50 pts on BattleScribe

**Comment by pretzalcohuatl** [comment]
rev. 2007 has the twin-linked fusion blaster purchased as part of the fusion blades.  this is silly.
