### ISSUE TITLE
Space Marines - Stormlance BDC transports wrong

### ISSUE THREAD

**Issue by pretzalcohuatl** [BSData/wh40k-7th-edition#3370]
Can't take drop pods, and requiring rhino/razorback not enforced (should also enforce no 7-man squads in razorbacks due to "must be embarked" rule but that might be too much to ask)

**Comment by francoisbeaulieu** [comment]
For the 8+ squads in razorbacks, as someone here pointed out to me a while ago, there is no rule that says you must embark or deploy in your dedicated transport; it only says no one else can deploy in it. So, RAW, a 10-man squad CAN take a Razorback as it's dedicated transport. It just can't embark in it.

**Comment by FarseerVeraenthis** [comment]
The restrictions in the Stormlance state all non-vehicle units not equipped with jump packs or bikes must start the game embarked on a rhino or razorback. Implementation could be tricky but it definitely should be looked at...

**Comment by francoisbeaulieu** [comment]
Details, details... ;-)

**Comment by pretzalcohuatl** [comment]
either way, drop pods shouldn't be an option
