### ISSUE TITLE
All 6 inquisitor entry's missing force sword

### ISSUE THREAD

**Issue by u02dah4** [BSData/wh40k-7th-edition#3375]
Inquisitors should be able to take a force sword for free if they are a psyker but the option is missing

**Comment by pretzalcohuatl** [comment]
it's not missing though?

**Comment by pretzalcohuatl** [comment]
![image](https://cloud.githubusercontent.com/assets/12982372/22707533/119e140c-ed41-11e6-9987-353db27dc4cb.png)

**Comment by pretzalcohuatl** [comment]
![image](https://cloud.githubusercontent.com/assets/12982372/22707761/d5fedb9c-ed41-11e6-8a0a-64c05677e7b2.png)
![image](https://cloud.githubusercontent.com/assets/12982372/22707796/f371cfc2-ed41-11e6-98a4-1eb1470a3da2.png)

**Comment by u02dah4** [comment]
My apologies didn't realise that it appeared when psyker mastery l1 was selected as an option 

However it is still not appearing in
Ordo Xenos inquisitor C:IA
Ordo Hereticus C:IA
Battlescribe (android) 
Yet clearly from your database screenshot it's there

**Comment by GenWilhelm** [comment]
The option was there but the logic that shows/hides the selection was incorrect, so it would never be shown on the two entries that you mentioned.

This has been fixed in the above commit (c4e8723e5ba17bdb1a10f0ce6d7a9ad3ae2bac65).
