### ISSUE TITLE
Inquisition - Leading whitespace in "Lord of Formosa" rule

### ISSUE THREAD

**Issue by francoisbeaulieu** [BSData/wh40k-7th-edition#3377]
Minor issue, I know. Causes sorting issues in the rules section.

I've attached a fix. Revision number NOT incremented.
[Inquisition - Codex.cat.zip](https://github.com/BSData/wh40k/files/759291/Inquisition.-.Codex.cat.zip)

**Comment by alphalas** [comment]
copy-paste artifact - i'll fix it.
