### ISSUE TITLE
Corsair Reaver Bands Unable to Take Transports

### ISSUE THREAD

**Issue by WyldhuntX** [BSData/wh40k-7th-edition#3379]
BattleScribe version: 2.00.24

Platform: Android

Dropbox: No

Description:It seems that corsair reaver bands are unable to take transports. The button to select one appears on the unit's entry, but the list of vehicles never appears.  This is occurring in both a CAD and in a Corsair Fleet Raiding Company Coterie.    I've not checked to see if it's happening in other types of detachments or formations.

**Comment by GenWilhelm** [comment]
The Reaver Band specifies it may take a Venom if the unit numbers exactly 5 models, or a Falcon if the unit numbers more than 5.

Is the list empty even after you add 5 or more models to the unit?

**Comment by FarseerVeraenthis** [comment]
Per Genwilhelm's comment, this works perfectly for me on Android if the correct number of members are selected for the squad... 
Please try again and report back :smile:
