### ISSUE TITLE
Blood Angels 10th company ambush force

### ISSUE THREAD

**Issue by Flashpoint-** [BSData/wh40k-7th-edition#3381]
Blood Angels Scout Bike Squad points cost incorrect show 74 points. Should be 54 points.
Thanks guys keep up the good work!

**Comment by Flashpoint-** [comment]
![screenshot_20170208-071838](https://cloud.githubusercontent.com/assets/10366677/22737437/111e9c82-edd1-11e6-836f-ddf6702b2559.jpg)

**Comment by Flashpoint-** [comment]
Sorry guys I think the mandatory cluster bombs is why the points difference.
Sorry for the inconvenience caused.

**Comment by GenWilhelm** [comment]
No worries!
