### ISSUE TITLE
Eldar - Corsairs - Can't take double weapons

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3386]
**File:** Eldar - Corsairs (2015).catz

**BattleScribe version:** 2.11.00

**Platform:** Windows

**Dropbox:** No

**Description:** Please, undo the recent change that limits an amount of similar weapons Corsair Prince (and other HQs probably) can take. The book says "any of the following" as opposed to "any one of the following" used for shields and jetbike/jetpack. AKA Prince with 2 Fusion pistols is perfectly legal (and can use both because of gunslinger), but recent change made it imposible to make such selection. Thank you.

**Comment by FarseerVeraenthis** [comment]
Hmmm... I don't remember why that was changed, possibly an oversight as part of the improvements to weapons selection in general.
I'll have a look, it should be a fairly straightforward fix. (Famous last words)
