### ISSUE TITLE
Cerastus Knight-Castigator

### ISSUE THREAD

**Issue by Kangodo** [BSData/wh40k-7th-edition#339]
We finally have the PDF for the new knight, I've already added him to Blood Angels.
http://www.forgeworld.co.uk//Downloads/Product/PDF/C/Castigator.pdf

**Comment by senpai514** [comment]
I saw @khambatta did a batch of armies earlier and I got the remaining Imperial armies including main entry in Codex Imperial Knights with appropriate modifiers for allowances. So The Castigator should now be fully updated in all appropriate catalogues.
