### ISSUE TITLE
Imperial Fists Chapter Tactics

### ISSUE THREAD

**Issue by Captain-Joystick** [BSData/wh40k-7th-edition#3391]
Using mobile, selecting IF chapter tactics unlocks devastator centurions as elites and assault centurions as fast attack, this is actually an effect of Sentinels of Terra supplement.

**Comment by francoisbeaulieu** [comment]
It's also included in the angels of death supplement. The question is: what's your point? 

All current Space Marines supplements and dataslates have been rolled into the SM catalog. (It's the only viable way to do it.) If you don't own a book and don't want to use rules from that book, you don't have to. The catalog is still valid, unless I'm missing a detail.

**Comment by DrTobogganMD** [comment]
Read your supplements. This is not an issue.

**Comment by Captain-Joystick** [comment]
Sorry guys, I reread it and found it right there. No idea how I missed it the first time.
