### ISSUE TITLE
Astra Militarum - Fall of Cadia Relic Question

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3396]
**File:** Astra Militarum - Codex.catz

**BattleScribe version:** 2.00.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** New FOC Relics not showing as an option for Lord Commissars or Company Commanders when Triumvirate of the Imperium included in the army roster.
This is in Cadian Detachment.

**Comment by alphalas** [comment]
Because it's CAD or allied only.

**Comment by KealL** [comment]
The rules say that the relics can be taken by someone in an ARMY that contains Bel or Celestine. They themselves can be added only to other factions via CAD or Allied detachment but the relics do not follow that restriction.

So a list that includes the Triumvirate of the Imperium or includes Celestine or Crawl in anyway should permit any body that can normally take relics to take the new ones.

**Comment by DrTobogganMD** [comment]
You are correct KealL, We've added it to our ever growing list of Fuck Fall of Cadia.

**Comment by FarseerVeraenthis** [comment]
Refer also #3401
