### ISSUE TITLE
Lord of War Force Type

### ISSUE THREAD

**Issue by Sandy756X** [BSData/wh40k-7th-edition#34]
In my personal version of the 40k Game System I have incorporated the Force Type of "Lord of War" in addition to the normal HQ, Fast Attack, etc...  This seems a significantly simpler solution to the addition of Escalation, Knights, and similar to WH40k.  As a result, the "Lords of War" detachment can be created, with 0-1 Lord of War slots for Escalation.  

Expanding - this leads to cleaner systems for Knights, the specific Age of Darkness detachments in the Horus Hesery books, and others I'm sure.  

Side note - I am brand new to Github so if I'm doing this wrong... please let me know.  :)

**Comment by amis92** [comment]
Yeah, but this cleans systems, leaving checks unsupported. I mean it surely would be simpler, but it wouldn't provide expected checks, ie whether we don't have too many Lords of War Detachments. I know, it sounds stupid in this case...

But there are many examples where it would be thousands times easier and cleaner to just leave something unchecked.

Another thing is what people are used to. Changing this could lead to chaos as it's now been like that for a while.

What I think might be a good idea, is to rebuild our game system using nested force types. I haven't really looked into this, but I believe it would look something like:
- Regular FOC
  - Primary Detachment
    - Hq
    - Elites
    - etc.
  - Allied Detachment
- Spearhead FOC
  - etc...
- Imperial Knights FOC

This could go long way towards simplyfying our system. And I think it's worth looking into.

Thank you @Millicant , you've raised pretty important issue. Let the discussion begin.

What do y'all think?

**Comment by Sandy756X** [comment]
Hey Amis,

So I did exactly that in my own 40k GameSystem.  I had nested Force Orgs and it was... okay.  One of the catches is that the nested ones have to be named differently from each other - you can't have an "Allied Detachment" in both the "Primary" and the "Age of Darkness" detachments, for instance.  I solved this by using the parent's name as a prefix.  ie - "Age of Darkness: Lord of War."

However, I also had significantly fewer Force Orgs in my own files than the public one  - I only concerned myself with what I played.  

I see this going one of two ways:
1. With so many flavors of FOC, nesting them would make the interface a LOT cleaner and typically easier for those looking to add the common stuff.  Namely things like add an allied detachment, a Lord of War, or Fortification detachment. 
2. If I may be so bold, I feel Jon's design philosophy is "provide the structure, not the restrictions."  While this is much to my chagrin at some points (I REALLY REALLY REALLY want the ability to  HIDE/rename/etc entries!!) it means that he intends for the project to err on the side of allowing illegal lists.  I would suspect he would prefer allowing any detachment to be paired with any other, leaving it up to the user to follow the guidelines.  

Ultimately, my vote is against nested FOCs.  As I said, I tried it.  It was a pain, did not provide the checks that you'd think it would (doesn't act quite the same way as the catalogue editor - more finicky) and ultimately prevents users from doing things "outside the box" in terms of basic force structure.  

---

Either way, I am in favor of a major cleanup of the primary 40k gamesystem file.  This may be another issue entirely but here are some things I did in my own GameSystem that I'd like to propose:
- Eliminate unnecessary/redundant FOC options.  I'm looking at you Knights.
- Consolidate Force Types.  Only the basic are really necessary and the rest should be structured around that. HQ, Fast Attack, Troops, Elites, Heavy Support, Lord of War, Fortification.  The rest is chaff and should be re-integrated another way.
- Eliminate unnecessary Profile types and options.  This one was a doozy for my own files but super worth it.  The only necessary profiles (as I see it) are: Unit, Vehicle, Walker, Wargear, Weapon.  As long as Unit, Vehicle, and Walker include the "Type" sub-category that covers everything else (ie Jump Infantry, Super-heavy Walker, Transport, Infantry (Character), Fast, Tank, Skimmer, etc...).  Additionally, and this is just a pet peeve of mine, the Page sub-category in profiles is unnecessary and redundant.  If users want references, they can select them in the view. If not, they are now forced to have them anyways due to the profile structure.  

I think that's it.  I may start a new issue for this so the discussion and continue in an organized fashion.  

Thanks for reading,

Jordan

**Comment by amis92** [comment]
Well I see. I could possibly agree, but I just didn't try these nested things, so I'll take your word for it.

I'm all for cleanup and consolidation. All these points in the last part are valid in my opinion. Re-raise these in #38 . Cheers!
