### ISSUE TITLE
Space Marines - Fall of Cadia Relic Question

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3401]
**File:** Space Marines - Codex (2015).catz

**BattleScribe version:** 2.00.24

**Platform:** Android

**Dropbox:** No

**Description:** The artifacts given by Cawl and company work army wide meaning I can take the artefacts in a different detachment from the one I take Cawl in. This is not currently possible it seems in battlescribe.

**Comment by FarseerVeraenthis** [comment]
refer to #3396

**Comment by GenWilhelm** [comment]
Closed by 907307ef2566d6fedebf192b8b9b2963900a4e88.
