### ISSUE TITLE
Space Marines - FW Chapter Masters in Honour Guard Question

### ISSUE THREAD

**Issue by pretzalcohuatl** [BSData/wh40k-7th-edition#3404]
Why are FW chapter masters a selection option in honour guard?

**Comment by francoisbeaulieu** [comment]
Because the badab update allows them?

**Comment by DrTobogganMD** [comment]
I ... actually can't find shit about Badab allowing CMs in an Honour Guard, just that they allow you to TAKE an honor guard that doesn't count as a slot. 

Do you have a page referencing taking CM's in an honor guard @francoisbeaulieu ?

If not, I'm not really sure how they got in there.

**Comment by francoisbeaulieu** [comment]
You're right that the sentence isn't as clear as it could be. Honour Guards are meant to include chapter champions, not masters so I guess this was misread when implemented and the CM isn't meant to be part of the honor guard itself.

**Comment by DrTobogganMD** [comment]
Yea, I'm guessing I just copy-pasted one too many places! I'll get it removed from Honor Guard

**Comment by DrTobogganMD** [comment]
Closed via a commit I can't link -.- Dammit.  It'll be fixed on next release (tonightish)
