### ISSUE TITLE
Tau Empire : Error message when selecting Fusion Blades

### ISSUE THREAD

**Issue by Alvirulan** [BSData/wh40k-7th-edition#3406]
In  Farsight Enclaves Combined Arms Detachment, whenever I select a Fusion Blades for my Commander I have the following error message in the console: "XV8 Commander Crisis Suit has 1 too many selections of Fusion Blades (maximum 0)"

**Comment by GenWilhelm** [comment]
The Fusion Blades are only available to a commander with a twin-linked fusion blaster.

Perhaps the modifier for this should be reversed so T/L fusion blaster becomes Min 1 when you select Fusion Blades, rather than the current max 0 on Fusion Blades when you don't have a T/L fusion blaster.

**Comment by KealL** [comment]
Would having two options work?

One that's "Twin-Linked fusion blaster" and one that's "Twin-Linked fusion blaster with fusion blades"

**Comment by GenWilhelm** [comment]
That would work yes, but it comes down to the matter of style. I personally prefer having all the relics in one group, so it's obvious they're unique.

Also we don't want to move entries if we can avoid it, since doing so removes them from any saved rosters.
