### ISSUE TITLE
Inquisition - Acolyte Selection Question

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3409]
**File:** Inquisition - Codex.catz

**BattleScribe version:** 2.00.24

**Platform:** Android

**Dropbox:** Yes

**Description:** the acolytes section in the (C:IA) is strangely organised. within each acolyte multiple acolytes can be added/ mystic can be added. can this interface be streamlined so that within each acolyte there is simply a choice of wargear and yes/no mystic option that locks out the wargear. ALTERNATIVELY if the mystic is the problem just have the mystic be separately addable in units main menu(UI level where you can buy a transport) and have each individual acolyte go strait to their equipment.

**Comment by alphalas** [comment]
It was organized that way because you have the unit of acolytes, where you can buy 1-10 acolytes, and each acolyte can be upgraded to a mystic.

**Comment by cartag** [comment]
Why not set it up where Acolyte/Mystic is a 1-10 group, defaulted with one Acolyte, and have them listed as separate entities in that group (think like regular infantry with champion). Would save a lot of code for showing and hiding war gear. If it's already that way I apologize, just throwing out ideas.
