### ISSUE TITLE
Craftword Eldar possible bug.

### ISSUE THREAD

**Issue by IronWulfen88** [BSData/wh40k-7th-edition#3410]
Making a big eldar list again. and for some reason this time it says the max number of formation detachments is  1 in the list errors part. Is this a bug or have the rules changed and I missed it.?

**Comment by GenWilhelm** [comment]
It was changed to be more inline with the rules (ie. each Formation is a separate detachment). However after some discussion we have reverted the change due to performance concerns with lots of Forces.

You can safely ignore the error for now - it should resolve itself with the next release.

**Comment by IronWulfen88** [comment]
Okay thanks
