### ISSUE TITLE
Adepta Sororitas - Command Squad Issues

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3414]
**File:** Adepta Sororitas.catz

**BattleScribe version:** 2.00.24

**Platform:** Android

**Dropbox:** No

**Description:** Command squad is not an elite choice, it's HQ but doesn't take up an HQ slot and rhinos can take an extra storm bolter it currently is only allowing one.

**Comment by GenWilhelm** [comment]
An additional storm bolter is available under "Vehicle Equipment".

**Comment by KingmanHighborn** [comment]
You can select a storm bolter from the vehicle equipment section but it gives you an error that the rhino can't take it.

**Comment by alphalas** [comment]
I believe this is one of the very few instances of something changed in C:IA  from the Codex

**Comment by KingmanHighborn** [comment]
Apparently the change of the command squad is, but it's still not letting me select a 2nd storm bolter and that still is legal even with C:IA, which should be its own dog anyways.

**Comment by GenWilhelm** [comment]
The 2 issues fixed in the above commit should available with the next release (Adepta Sororitas v2017).
