### ISSUE TITLE
Tempestus - Formations

### ISSUE THREAD

**Issue by KealL** [BSData/wh40k-7th-edition#3415]
In all three Tempestus formations the Commissar is compulsory not optional and is limited to 1.

Currently in the data file commissar is not auto added, is optional and allows more than one to be added to the formation.

- [x] Airborne Assault Formation

- [x] Ground Assault Formation

- [x] Hellrain Brigade

**Comment by GenWilhelm** [comment]
Closed by a46815c11720dd47ef2b7ccbe202cf0d7e7777f3.
