### ISSUE TITLE
Ynnari Windrider upgrade error

### ISSUE THREAD

**Issue by grimmjowespada** [BSData/wh40k-7th-edition#3420]
When upgrading the windrider weapon in a Ynnari reborn warhost it says that all windriders need to have a minimum of one twin linked shuriken catapult.

**Comment by grimmjowespada** [comment]
Looking through all the errors, but looks like something similar is happening to all the Eldar Corsairs upgrades.

**Comment by DrTobogganMD** [comment]
You mean all the wind rider upgrades? Corsairs are not in the file

**Comment by grimmjowespada** [comment]
Sorry, about the cosairs; I had opened up an old roster. Yeah, if you select to upgrade the windrider's twin linked shuriken catapult to either a scatterlaser or shurisen cannon it says that they must have a minimum of one of the catapult.

**Comment by DrTobogganMD** [comment]
Gotcha. Simple max bug. I'll get it fixed shortly

**Comment by egbet** [comment]
After updating catz file 2/19, I am seeing this bug in Black Defender Windrider. Troop Windrider is ok. :) Could you please verify and open/re-open bug if needed?

![image](https://cloud.githubusercontent.com/assets/5524240/23106723/a57d2276-f6bf-11e6-98e4-8ffe9aa2ccaf.png)

**Comment by DrTobogganMD** [comment]
Good catch. I'll take care of it
