### ISSUE TITLE
Ynnari - Strike Forces - Strength from Death

### ISSUE THREAD

**Issue by egbet** [BSData/wh40k-7th-edition#3423]
I could be wrong but when I searched the eBook, I did not find a rule that provides Strength From Death for the new "Black" Strike Force units. Strength from Death is listed in the info of the unit (not in the individual model info).

Please let me know if I am wrong and where to find the rule... I would love these units to have this! :)

**Comment by DrTobogganMD** [comment]
Strength From Death is a rule that all units in the Ynnari faction get.  When the new Eldar "Black" units are taken in a Reborn Warhost or Ynnari formation, they are considered both Ynnari and Eldar faction - therefor they get Strength from Death. (Page 124 if you need source to show someone. See screencap below)

![image](https://cloud.githubusercontent.com/assets/16939161/23099124/10be1784-f625-11e6-8920-ab19d510b33e.png)

**Comment by egbet** [comment]
Thanks and sorry for bothering you. :(

**Comment by DrTobogganMD** [comment]
No bother at all, I'm glad for any bug reports on a new cat file like this! Thanks!
