### ISSUE TITLE
Ulthwe Strike Force missing from Craftworlds Cat

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3424]
**File:** Ynnari Aeldari - Supplement.catz

**BattleScribe version:** 2.00.11

**Platform:** Windows

**Dropbox:** No

**Description:** Whenever I select scatterlasers/shuriken cannons for windriders the list gives the incorrect error, "windriders must have 1 more selections of twin-linked shuriken catapult (minimum 1)."  It does this for both CAD and Ynnead's Net.

On another note, shouldn't Ulthwe Strike Force be in Ynnari Aeldari? If so, it's missing.

**Comment by GenWilhelm** [comment]
The windrider weapon issue has been fixed in the most recent release. Please update your data.

The Ulthwé Strike Force uses Eldar Craftworlds units so it should be in the Craftworlds catalogue. I'll get it in for next release.

**Comment by DrTobogganMD** [comment]
Windrider issue is fixed in most recent release.

Ulthwe Strike Force is an Eldar Detachment and would go in Craftworlds.  The only things that are of the Ynnari Faction are the formations listed in the supplement, and the Reborn Warhost detachment.
