### ISSUE TITLE
Eldar Craftworlds - Include Iyanden Supplement

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3428]
**File:** Eldar Craftworlds - Codex (2015).catz

**BattleScribe version:** 2.00.24

**Platform:** Android

**Dropbox:** No

**Description:** Eldar charicters do not have the option to select iyanden relics, this is now legal per most recent craftworld faq.

**Comment by Schterve** [comment]
Somewhat related to this issue, I have been looking through the various catalogues for the new Ulthwé Strike Force detachment, but haven't been able to locate it.

**Comment by DrTobogganMD** [comment]
It is a detachment in the eldar catalogue file as it is an eldar detachment.

**Comment by FarseerVeraenthis** [comment]
I've nearly managed to get back to working on this... so hopefully there will be some progress in the next couple of weeks...
