### ISSUE TITLE
Bug report: Ynnari Aeldari - Supplement.catz (Succubus)

### ISSUE THREAD

**Issue by ghost** [BSData/wh40k-7th-edition#3430]
File: Ynnari Aeldari - Supplement.catz

BattleScribe version: 2.00.11

Platform: Windows 10
Dropbox: No

Description: If you take a DE Succubus in a Ynnari Cad she can't take any of her ranged/melee options with the exception of the cult weapons. Missing Archite Glaive, Agoniser, Power Sword, Blast Pistol

**Comment by DrTobogganMD** [comment]
Did you select Pistol and Melee Weapon?

**Comment by DrTobogganMD** [comment]
![image](https://cloud.githubusercontent.com/assets/16939161/23106502/fedc7706-f6b3-11e6-84f9-5ecf84ad6888.png)

**Comment by ghost** [comment]
My bad :) 
Used to the way it's laid out on the DE dex, didn't think to look under pistol/melee for the options

**Comment by DrTobogganMD** [comment]
Np, I tried to keep things somewhat the same between all 3 but ended up changing some things to try and optimize it.  Keep the bug reports coming!
