### ISSUE TITLE
Ynnari HQ and LOW choices for Eldar

### ISSUE THREAD

**Issue by grimmjowespada** [BSData/wh40k-7th-edition#3431]
Yvraine and Visarch aren't selectable as HQ choices, nor the Yncarne as LOW, for a Craftworld, Dark Eldar, and Harlequin Combined Arms Detachment and Allied Detachment. Fracture of Biel-tan, page 114 I believe, states that they can be taken regardless of faction.

**Comment by DrTobogganMD** [comment]
Was fixed earlier today. Will be pushed out probably tonight. 

~Earl Bishop
