### ISSUE TITLE
Bug report: Ynnari Aeldari - Supplement.catz - Windriders without shuriken catapults

### ISSUE THREAD

**Issue by DavidTruby** [BSData/wh40k-7th-edition#3432]
When attempting to replace the Windrider bike weapons (i.e. giving them Scatter Lasers or Shuriken Cannons) the validation errors section says "Windrider must have 1 more selection of Twin-linked Shuriken Catapult (minimum 1)" for each Windrider whose weapon has been changed.

**Comment by DavidTruby** [comment]
I've also noticed that Farseer Skyrunners and Warlock Skyrunners have the option to replace their Eldar Jetbike shuriken catapult, which they shouldn't be allowed to do.

**Comment by DrTobogganMD** [comment]
Update data. Should be fixed in v2001 (except on black windriders. Still have to fix those)

**Comment by DavidTruby** [comment]
Ok apologies for not updating before posting, the website was down when I tried! Sorry to be a bother

**Comment by DrTobogganMD** [comment]
No issues!

**Comment by DrTobogganMD** [comment]
Duplicate of #3420

**Comment by DavidTruby** [comment]
My second comment is still the case though I think: I'm still allowed to change the weapons for Farseers and Warlocks on Eldar Jetbikes

**Comment by DrTobogganMD** [comment]
Hmm ok I'll check that out.

**Comment by DrTobogganMD** [comment]
Warlocks were fine - Autarch and Farseer had the options still though - fixed that.
