### ISSUE TITLE
Tau Empire - Wargear Selection Issues

### ISSUE THREAD

**Issue by Whiteshadezz** [BSData/wh40k-7th-edition#3434]
According to the codex I can select 3 items from the warrears list for XV8 Crisis Battlesuits and Crisis Bodyguards. This database says that I cannot have that many. Here are 2 pictures out of the codex, and a screen shot of the database error.
![screenshot_20170219-210333](https://cloud.githubusercontent.com/assets/25892985/23113412/c97c6e48-f6ec-11e6-84a7-fea8e05fcd3b.png)
![screenshot_20170219-205504](https://cloud.githubusercontent.com/assets/25892985/23113419/cfe78308-f6ec-11e6-8d38-e558a01226eb.png)
![screenshot_20170219-205139](https://cloud.githubusercontent.com/assets/25892985/23113421/d5995f24-f6ec-11e6-8dac-4688df42c8f5.png)

**Comment by GenWilhelm** [comment]
Have you made any selections of Twin-Linked weapons?
They count as two items as per the Ranged Weapons list.

**Comment by FarseerVeraenthis** [comment]
A screen grab of your wargear selection would be very helpful :smile:

**Comment by Whiteshadezz** [comment]
@genWilhelm that was the problem. I did not know about the twin-linked rule. Thanks for the eye opening comment.
