### ISSUE TITLE
Adepta Sororitas Kill Team Detachment missing Specialist options for Seraphim

### ISSUE THREAD

**Issue by foolsama** [BSData/wh40k-7th-edition#3441]
When using the Seraphim Squad in a Kill Team detachment, no Specialist selections are available, so list cannot be valid.

Kill Team detachments also missing option for Repressor tanks.

**Comment by GenWilhelm** [comment]
The Repressor has a combined armour value of 34, which is illegal in Kill Team.

**Comment by foolsama** [comment]
that explains that
