### ISSUE TITLE
Bug Report (Jetbike Seer Council in Reborn Warhost Profile Bug)

### ISSUE THREAD

**Issue by ghost** [BSData/wh40k-7th-edition#3444]
File: Ynnari Aeldari - Supplement.catz

BattleScribe version: 2.00.11

Platform: Windows 10
Dropbox: No

Description: If you take a Seer Council in a Reborn Warhost and take the formation-wide jetbikes upgrade, the profile for the Warlocks shows them as Toughness 1 instead of 4.

**Comment by DrTobogganMD** [comment]
I see no problem with this.  It lets me kill them much easier!
/jk

Fixing.
