### ISSUE TITLE
Codex: Space Wolves Enhancement Wolf Lord Krom

### ISSUE THREAD

**Issue by Gnofry** [BSData/wh40k-7th-edition#3446]
As far as I am seeing in the most recent data file, for some reason the Bolt Pistol in his shared entry has been unconstrained, allowing for 0-infinite Bolt Pistols to be chosen. Please add constraints back for added quality of life.

In addition, several entries, such as Wolf Scouts, Harold Deathwolf, The Deathpack Formation, and multiple Apocalypse formations are now showing up in all Forces under "Uncategorized". Please re-categorize.

**Comment by GenWilhelm** [comment]
I wasn't able to reproduce the "Uncategorised" part, but I did find that the Wolf Scouts, Land Speeder Squadron, and Harald Deathwolf entry links didn't have categories. However, there's nothing out of place with the Deathpack formation, or any of the Apocalypse battle formations from what I can see.

Are you able to provide some additional information such as the platform and version number you are seeing this on?

**Comment by GenWilhelm** [comment]
Okay so I updated my BattleScribe on Android to 2.00.25 and now I'm seeing the "Uncategorised" bug. I'll see if I can shift things around to get it back to normal.

Edit: also the case on windows after updating to 2.00.12
