### ISSUE TITLE
Chaos Space Marines - Issue Equipping Chaos Lord with an Artefact

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3447]
**File:** Chaos Space Marines - Codex.catz

**BattleScribe version:** 2.00.25

**Platform:** Android

**Dropbox:** No

**Description:** When a chaos lord is equipped with a chaos artefact, there is an error message saying it cannot be equipped with and artefact.

**Comment by cartag** [comment]
Not seeing any issues with equipping a lord, if there is a specific artefact causing issue please resubmit.
