### ISSUE TITLE
Ynnari - Black Guardian War Walkers

### ISSUE THREAD

**Issue by GenWilhelm** [BSData/wh40k-7th-edition#3448]
Black Guardian War Walkers are missing the power field wargear (identical to Craftworlds power field).

**Comment by DrTobogganMD** [comment]
Black Guardian War Walkers do not get access to a power field:

![image](https://cloud.githubusercontent.com/assets/16939161/23218999/770f17f2-f8e3-11e6-806a-48631aba5422.png)

**Comment by FarseerVeraenthis** [comment]
The power field is clearly listed in the wargear on that photo...

**Comment by DrTobogganMD** [comment]
Jesus i'm blind -.-  Fixing.
