### ISSUE TITLE
Astra Militarum - Many entries in 'Uncategorised'

### ISSUE THREAD

**Issue by IdleMuse** [BSData/wh40k-7th-edition#3449]
In the Astra Militarum main codex, many many many entries are now listed under 'Uncategorised' rather than their correct FoC slot.

To replicate:
- Create new CAD using main AM entry.
- Look in the Uncategorised tab.

**Comment by alphalas** [comment]
Android?

**Comment by DrTobogganMD** [comment]
This is a confirmed BS bug - Selection Entries that are not "Links" from Shared entries will appear if the Category doesn't exist in your chosen force (IE: Formations will appear in a CAD under Uncagegorised, and LOW in an Allied, etc).

Jon introduced it in his latest update.  ~~We're waiting on a response from him.~~ - Jon's fixing it soon^tm  In the mean time, Authors are working to convert selection entries to Links to fix this.

**Comment by IdleMuse** [comment]
Thanks for the explanation!
