### ISSUE TITLE
Couple of Blood Angels issues/quality of life changes

### ISSUE THREAD

**Issue by nottsknight** [BSData/wh40k-7th-edition#3451]
- [x] Camo cloaks on Scouts should appear in the entry's list of wargear descriptions
- [x] Cluster mines on Scout Bikers should appear in the entry's list of wargear descriptions

**Comment by GenWilhelm** [comment]
I can't find anything that says a model with a camo cloak gains stealth, do you have a page reference for that?

Likewise with Fyrestorm, do you know where it says that it replaces the models weapon?

**Comment by nottsknight** [comment]
My bad with camo cloaks, I've always taken it to be Stealth. Likewise with Fyrestorm, that was an assumption I've always made but I guess if it's not explicitly stated then it's good as is.

**Comment by nottsknight** [comment]
Removed the unnecessary points.
