### ISSUE TITLE
Chaos Space Marines - 1kSons Issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3455]
**File:** Chaos Space Marines - Codex.catz

**BattleScribe version:** 2.00.25

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** Thousand sons grand coven  lacks armorarmory of the legion  slot

**Comment by cartag** [comment]
Add "Thousand Sons" under Force Options.
