### ISSUE TITLE
Tau - Only Drones have supporting fire, roster view shows it attached to whole squad

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3472]
**File:** Tau - Codex (2015).catz

**BattleScribe version:** 2.00.12

**Platform:** Windows

**Dropbox:** No

**Description:** For the Tau. The Piranha fire stream wing shows that they have supporting fire. This is also true for just adding a single regular unit as well. *Only the drones attached have it* and in the print out it shows the whole unit.

**Comment by jamie4red** [comment]
A part of what I said did not show up due the the twin < < > >. The attached drones do have it and in the print out it shows the whole unit

**Comment by amis92** [comment]
There, I've changed your `<<...>>` into markdown's italics (`*text*`).
