### ISSUE TITLE
CSM - Artefacts

### ISSUE THREAD

**Issue by radionausea** [BSData/wh40k-7th-edition#3474]
**File/Catalogue:** CSM v2012

**BattleScribe version:** 2.00.16

**Platform:** Android

**Dropbox:** No

**Description:** Chaos Lord has too many selections from chaos weapon artefacts (maximum 0)"
The Chaos Lord has 1 artefact weapon, no other artefacts. The error disappears if I make any change to the roster and reappears if I make any edits.

**Comment by Kohato** [comment]
...  Seriously?

**Comment by radionausea** [comment]
Argh.
"Chaos Lord has too many selections from chaos weapon artefacts (maximum 0)"
The Chaos Lord has 1 artefact weapon, no other artefacts. The error disappears if I make any change to the roster and reappears if I make any edits.

**Comment by radionausea** [comment]
Lost the post.
CSM v2012/Android/no dropbox

**Comment by cartag** [comment]
I am completely unable to duplicate this. Can you give me some more info with what you're selecting, what else the Chaos Lord has, etc?

**Comment by cartag** [comment]
What the hell... it was working just fine yesterday and now it's not working... sonofa...

**Comment by Drachnyen** [comment]
BS app was updated to 2.00.16

It was also working for me before this update

**Comment by cartag** [comment]
Okay, so it's not my fault. Got it. I'll try to get it up tonight.

**Comment by radionausea** [comment]
It's bizarre! Although I had the issue before updating to .16 and after.
The same thing with "swap bolters for close combat weapons"

**Comment by Drachnyen** [comment]
👍

**Comment by Drachnyen** [comment]
Just another note, seems the "too many selections from legacies of ruin" issue is also back since the new release of BS

**Comment by FarseerVeraenthis** [comment]
Is this still an issue?? We're now on BS Version 2.00.31 on Android...

**Comment by Crowbar90** [comment]
Yes, I just got the same error on 2.00.31 with latest data.

**Comment by radionausea** [comment]
This is still an issue

On 21 Mar 2017 20:55, "Francesco Venturoli" <notifications@github.com>
wrote:

Yes, I just got the same error on 2.00.31 with latest data.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/BSData/wh40k/issues/3474#issuecomment-288215617>, or mute
the thread

**Comment by radionausea** [comment]
This is still an issue though.

I just created a new Death Guard Vectorium and I still have the same error
message.

**Comment by FarseerVeraenthis** [comment]
It's not been released yet, or its not been picked up by appspot...

**Comment by alphalas** [comment]
It takes time - slow down.

**Comment by Drachnyen** [comment]
Hello,

Just got the BS 200.19 update and the "too many selections from chaos artefact" is still there 


![img_1676](https://cloud.githubusercontent.com/assets/16340056/24681851/ee106f6c-1964-11e7-8424-7feddb6aadf5.PNG)
