### ISSUE TITLE
Renegades & Heretics - Platoon special weapons validation issue - (maximum 0)

### ISSUE THREAD

**Issue by radionausea** [BSData/wh40k-7th-edition#3480]
**File/Catalogue:** Renegades and Heretics

**BattleScribe version:** 2.00.16

**Platform:** Android

**Dropbox:** No

**Description:** Detailed issue description.

Infantry platoons aren't able to select special weapons without an error saying maximum number is 0

**Comment by GenWilhelm** [comment]
Is the BattleScribe version accurate? The current Android version is 2.00.26.

**Comment by radionausea** [comment]
I have .26

This issue seems to be in a lot of catalogues since the battlescribe update

(A separate issue: Covenant of Nurgle doesn't allow plague zombies to be
selected as troops anymore, they're hidden)

**Comment by GenWilhelm** [comment]
>Covenant of Nurgle doesn't allow plague zombies to be selected as troops anymore, they're hidden

There's now a separate Command Squad for if you want an Arch Demagogue to be your Warlord. I'm guessing you made the roster before that change, so now it works a little differently.

**Comment by radionausea** [comment]
I'm using the Renegade Command Squad (Warlord) entry. It was a new roster
created today. It is working now, but not working with any of my
'favourited' squads, which are also post the change to have a separate
(warlord)squad

**Comment by FarseerVeraenthis** [comment]
Is this still an issue?? We're now on Battlescribe Version 2.00.31...

**Comment by radionausea** [comment]
No, this seems to have resolved.

**Comment by FarseerVeraenthis** [comment]
Yay! I love it when things fix themselves!!
