### ISSUE TITLE
Deathwatch - Veteran with Heavy Weapon Bugged

### ISSUE THREAD

**Issue by candidgamera** [BSData/wh40k-7th-edition#3481]
**File/Catalogue:** Deathwatch Codex (2016) v2011

**BattleScribe version:** 2.00.13

**Platform:** Windows 7

**Dropbox:** No

**Description:** Trying to create a Black Spear Strike Force with several veterans squads, with heavy weapons. When I try to assign a heavy weapon to one of the veterans, I get a validation error : "Veteran with Heavy Weapon has 1 too many selections from Heavy Weapons (maximum 0)" Even stranger, if I repeatedly click the same radio button for a given Heavy Weapon (for example, the Frag Cannon) the number of validation errors reported can change.  I've got twelve Vets with Frag Cannons in my roster, and the number of reported validation errors varies between 8 and 12.

**Comment by candidgamera** [comment]
Well, I guess something was broken about my Battlescribe updates, because when I forced it to check, it updated to codex v 2029, and seems okay now, though  I am having to rebuild some things. Please disregard the bug report, but it is frustrating having to rebuild all my rosters from scratch every time an update rolls out..

**Comment by FarseerVeraenthis** [comment]
I'm glad to hear that it fixed itself :+1:
Hopefully the format of the CAT won't change much from now on so you shouldn't have to rebuild again, it should only be minor changes... he says...
Thanks for the report anyhow!! :smile:
