### ISSUE TITLE
skitarii - elite secutarii hoplites alpha weapon selection

### ISSUE THREAD

**Issue by laurent-conte** [BSData/wh40k-7th-edition#3482]
**File/Catalogue:**  skitarii /elites (show forgeworld)

**BattleScribe version:** 2.00.13

**Platform:** Windows/Android

**Dropbox:No

**Description: the alpha hoplite has "galvanic caster" as ranged weapon, and do not have "Arc lance" as melee weapon. As far as I understand this: "The Hoplite Alpha may take items from the Ranged Weapons, Melee Weapons, Special Issue Wargear and Relics of Mars lists (see Codex: Adeptus Mechanicus – Skitarii) "
It means that the alpha is by default equipped with Arc lance but can change his weapons (like it is for rangers and vanguards).
Besides, galvanic caster is not part of the ranged weapons available in the skitarii codex (I wish it was :p).

I guess the profile of the Pelstat Alpha was copy/paste for the hoplite?

**Comment by Thairne** [comment]
I should remember to add more "closes" to my commits...
