### ISSUE TITLE
[Anon] Bug report: Adeptus Custodes Dataslate.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3483]
**File:** Adeptus Custodes Dataslate.catz

**BattleScribe version:** 2.00.16

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** When attempting to create a Custodies allied attachment...  I can create the allied and attach it to my combined arms force but If I select the Elites tab the info is blank...   I have deleted and reloaded the data files for both 40k and Custodies, no joy...   also BattleScribe is showing two errors for the allied force indicating that for the custodies I must select one HQ and a second error stating that I must select one troop choice...   neither is listed as a option in the allied detachment...   Thanks. Ed

**Comment by alphalas** [comment]
They can only be used as a formation detachment, not an allied detachment
