### ISSUE TITLE
Add Raven Guard data from Operation Shadowtalon supplement

### ISSUE THREAD

**Issue by nattymac** [BSData/wh40k-7th-edition#3487]
**BattleScribe version:** 2.00.

**Platform:** All

**Dropbox:** Yes/No

**Description:** Need to add character and formation data from the Operation Shadowtalon (War Zone: Damocles) as options for Raven Guard:
Shadow Captain Solaq - Infantry (Character); weapons; warlord trait: Angel of Death; chapter relic: The Raven Helm; 130 points.

Sternguard Squad Amerex, 165 points
Vanguard Squad Davros, 185 points
Land Speeder Darkwind, 75 points
Shadow Force Solaq formation

Note: manually entering the unit composition and wargear for SS Amerex and VS Davros it is not possible to arrive at the specified point values above.

**Comment by FarseerVeraenthis** [comment]
They are already available.
I just looked on Android, Space Marines, Formation Detachment, Raven Guard Chapter Tactics = Formation: Shadow Force Solaq is available.

Please try again, make sure you have selected Raven Guard Chapter Tactics!!

**Comment by nattymac** [comment]
"Shadow Force" is available, but "Shadow Force Solaq" isn't. Not a big deal, but if you try to build the component army list entries using the app, the points don't add up correctly. (I.e., Land Speeder Darkwind only adds up to 65 points)

What needs to get added completely is Shadow Captain Solaq, with his wargear and unique chapter relic. He should be an option when building a captain/choosing a company leader, along with the rules for his chapter relic (the Raven Helm).
