### ISSUE TITLE
cult mechanicus - holy requisitioneer formation missing

### ISSUE THREAD

**Issue by laurent-conte** [BSData/wh40k-7th-edition#3488]
**File/Catalogue:**  cult mechanicus /formations

**BattleScribe version:** 2.00.26

**Platform:** Windows/Android

**Dropbox:** No

**Description:** the formation 'holy requisitioneer' doesn't appear on the formation list

**Comment by laurent-conte** [comment]
ho... cybernetica neither.

**Comment by Thairne** [comment]
Works on Desktop.

**Comment by Thairne** [comment]
![grafik](https://cloud.githubusercontent.com/assets/8590840/23544457/6406051a-fff7-11e6-9df6-a80bc04f8136.png)

**Comment by FarseerVeraenthis** [comment]
I just updated and Cult Mech is v2012 on Android for me, and neither of these formations show there...

In the screenshot, your CAT is v2015 - Perhaps we need a release??

**Comment by Thairne** [comment]
What? A release? That is HERESY!
Let's see if this fixed it.

**Comment by laurent-conte** [comment]
I updated to last BS, I erased old data, still stay as "v2012", this is the right link?: http://battlescribedata.appspot.com/repos/wh40k/index.bsi

**Comment by FarseerVeraenthis** [comment]
Yup, that's the right link. The release will take a few hours to push through appspot so wait a while and try again :-)

**Comment by laurent-conte** [comment]
just find out in the version of data i have, they actually show up in "uncategorized"

**Comment by Thairne** [comment]
that should be fixed then.

**Comment by laurent-conte** [comment]
did one last update, now it s on right place! thanks for all your works guys!
