### ISSUE TITLE
Contemptor Pattern Dreadnought and Contemptor-Mortis Pattern Dreadnought missing from Codex Space Marines

### ISSUE THREAD

**Issue by battlebrother** [BSData/wh40k-7th-edition#349]
Hi,
just started using BattleScribe and loving it, but I've noticed that for Codex Space Marines the options for the Forge World Contemptor Pattern Dreadnought and Contemptor-Mortis Pattern Dreadnought are missing from the Elites section.

As far as I'm aware the latest versions of their rules are pgs 178 & 179 of Imperial Armour Volume 2 - Second Edition - War Machines of the Adeptus Astartes from earlier this year.

**Comment by Thairne** [comment]
Really seems to be missing, will take a look at it later today.

**Comment by battlebrother** [comment]
Cheers. I'd have had a go myself but I'm not confident enough using the editors yet!

**Comment by Thairne** [comment]
I lack the rules for the Contemptor and Mortis Contemptor, but afaik the Mortis is exclusive to DA and successor chapters, ain't it?
For the Contemptor, are the PDF rules close to the current ones?

**Comment by battlebrother** [comment]
The normal Mortis is DA exclusive, but the Contemptor-Mortis isn't.

Which PDF are you working from? I can supply the rules if needed, though it'll take me some time to type them up :)

**Comment by Thairne** [comment]
http://www.forgeworld.co.uk/Downloads/Product/PDF/c/Contemptor.pdf

Here's the one I was refering to :)

Edit: Nevermind, Blood Angels DO have a Contemptor Mortis. Unless those rules are outdated, I can just copy them over to SM, DA and if appropriate SW.

**Comment by battlebrother** [comment]
That PDF is outdated, and unfortunately the BA and SW ones are unique to their chapters. CSM and CDA share the same ones though. If you bash me your e-mail address I can send you the rules there? Don't want to just post them on here in case that isn't allowed :)

**Comment by Thairne** [comment]
Already have the foundation set from the BA one, should be quick work after you give me the gist at Archilleos@gmx.de ;)

**Comment by Thairne** [comment]
Added a crapload of Dreads to the DA catalogue. Will add them to other catalogues after verifying they are correctly introduced.

**Comment by senpai514** [comment]
@Thairne  if you would, Allow me to take care of this I was already in the works to start this portion of my updates this week before this had been reported Piece of cake for me as I have IA2 Second edition.

**Comment by Thairne** [comment]
Got send the rules and already did them in the DA catalogue. Should I revert my commit? Also I'd better wait with redoing the data structure if you're working on the catalogue too ;)

**Comment by senpai514** [comment]
Oh I'm talking about codex space marines dark angels your fine to take over the work there.

**Comment by Thairne** [comment]
Alrighty then ;) You could try and copy them over from the DA catalogue, might save you some work.
