### ISSUE TITLE
Add Raven Guard data from Operation Shadowtalon supplement

### ISSUE THREAD

**Issue by nattymac** [BSData/wh40k-7th-edition#3490]
**File/Catalogue:** 

**BattleScribe version:** 2.00.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** 

Follow up from issue #3487 - closed by @FarseerVeraenthis; not resolved.

What needs to get added completely is Shadow Captain Solaq, with his wargear, leader/warlord rules and unique chapter relic (the Raven Helm). He should be a HQ option selectable when creating/choosing a formation leader, along with the existing choices: "Captain, "Chaplain," and "Shadow Captain Shrike."

Formation "Shadow Force" is available under Raven Guard chapter rules, but "Shadow Force Solaq" isn't. Not a big deal, but if you try to build the component army list entries using the app, the points don't add up correctly. (I.e., Land Speeder Darkwind only adds up to 65 points)

/////Original issue message: Need to add character and formation data from the Operation Shadowtalon (War Zone: Damocles) as options for Raven Guard:
Shadow Captain Solaq - Infantry (Character); weapons; warlord trait: Angel of Death; chapter relic: The Raven Helm; 130 points.

Sternguard Squad Amerex, 165 points
Vanguard Squad Davros, 185 points
Land Speeder Darkwind, 75 points
Shadow Force Solaq formation

Note: manually entering the unit composition and wargear for SS Amerex and VS Davros it is not possible to arrive at the specified point values above./////

**Comment by DrTobogganMD** [comment]
It is indeed there. As stated in the "Errors" you will need to select chapter tactics.  Upon choosing Raven Guard, the formation is revealed.

**Comment by DrTobogganMD** [comment]
![image](https://cloud.githubusercontent.com/assets/16939161/23554930/9668e14a-ffec-11e6-862f-4df089b96b89.png)

**Comment by nattymac** [comment]
Ok, apparently I'm screwing something up because I still don't see them. I'll check it out in the desktop version when I have a chance.
![img_4379](https://cloud.githubusercontent.com/assets/26149626/23558004/e9fbacee-ffe6-11e6-8c7c-c0f8fab1cbfe.PNG)
![img_4380](https://cloud.githubusercontent.com/assets/26149626/23558006/e9fdb1f6-ffe6-11e6-88bf-86bca3533d0c.PNG)
![img_4381](https://cloud.githubusercontent.com/assets/26149626/23558005/e9fd4dec-ffe6-11e6-93f8-da087e2a74bf.PNG)

**Comment by DrTobogganMD** [comment]
You're looking in a Talon Strike Force.  Shadow Force Solaq is not a valid choice in a Talon Strike Force.

**Comment by nattymac** [comment]
Thanks--now I feel like an ass. I found them in the formations list.

**Comment by DrTobogganMD** [comment]
No problems :)
