### ISSUE TITLE
Space Wolves roster issue

### ISSUE THREAD

**Issue by IronWulfen88** [BSData/wh40k-7th-edition#3492]
**File/Catalogue:** 

**BattleScribe version:** 2.00.26

**Platform:** Android

**Dropbox:** Yes/No

**Description:** every time I load a space Wolves roster thus box pops up.
![screenshot_20170303-140038](https://cloud.githubusercontent.com/assets/22039355/23565146/51829ee4-001a-11e7-8c91-ab1e5e1d9941.png)

**Comment by GenWilhelm** [comment]
Does it happen on specific roster(s) or all of them?
Does it happen when you start a new roster?
Have you purged and re-downloaded your data files?

**Comment by IronWulfen88** [comment]
It occurs on all my rosters that are space wolves but none of the others. started happening after that last data update I did. I shall try purging and redownloading

**Comment by IronWulfen88** [comment]
I just purged all my data and redownloaded the same box keeps coming up. Though now it seems to be happening to all my lists.

**Comment by cartag** [comment]
Try a new roster for Galactic Puppies and see if it happens. If you're loading  a roster from an older data file it may give errors.

**Comment by IronWulfen88** [comment]
I just purged all my data and redownloaded the same box keeps coming up. Though now it seems to be happening to all my lists.

**Comment by IronWulfen88** [comment]
I tried making a new list after purging my old data and downloading new. the same box still shows up.

**Comment by IronWulfen88** [comment]
something strange is going on now. its only showing up with space wolves lists again and now I can load any space wolves lists except in low memory mode

**Comment by Gnofry** [comment]
Confirming I receive the same errors when creating a new roster with the v2030 Space Wolves Catalog on Android but not Windows.

**Comment by IronWulfen88** [comment]
mine doesnt do it anymnore and I am on version 2.00.28 for android

**Comment by FarseerVeraenthis** [comment]
has this resolved itself??

**Comment by FarseerVeraenthis** [comment]
no further input.
