### ISSUE TITLE
[Anon] Bug report: Chaos Marines/Demons

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3498]
**File:** Cult Mechanicus Codex 2015.catz

**BattleScribe version:** 2.00.27

**Platform:** Android

**Dropbox:** Yes

**Description:** When I take a khorne Lord it says I cannot take any artifact weapons. It gives me the errors message "chaos Lord has too many artifact weapons maximum0. Is there something that I kissed. He only has 1 relic as per the new FAQ. And it gives the same message for all of the artifact weapons
Thank you 
John ontto

**Comment by Thairne** [comment]
I'm not sure this is Cult Mech... Are you talking about Khorne Demonkin? CSM? Chaos Demons?

**Comment by alphalas** [comment]
no responce
