### ISSUE TITLE
Horus Heresy Force Orgs

### ISSUE THREAD

**Issue by Sandy756X** [BSData/wh40k-7th-edition#35]
Hello again,

I guess I'm asking for permission to add the "Age of Darkness" and other Force Org charts that exist in HH3: Extermination (and earlier books).  

My focus is really the HH and if nobody objects, I will be updating things accordingly.  

I also have a full Horus Heresy catalogue, built from the ground up, including the HH3: Extermination units.  Will I step on people's toes if I upload that to replace the existing one?  I need to clean it up to match the current standards first.

**Comment by amis92** [comment]
As per FOC, I see no problem (yay for next Force Types). But that's connected with #34 too.

If it's just better (or rather _will_ be) than what we have currently, of course. We strive to provide the best, not the ones we are used to. :)

**Comment by Sandy756X** [comment]
Hey there,

I'll hop on adding the FOC from the HH books then.

As far as the 30k catalogue goes, it is better (if I say so myself) but more importantly includes all the additions from the latest book that will be released on 01May14.  

Once I finish cleaning it up I will add it as well.  Does that go for any Catalogue that I have another version of?  I'm quite fond of my Dark Angels catalogue, I'll assess the differences between the two shortly.

**Comment by Jonskichov** [comment]
Should this issue be closed in favour of #40?
