### ISSUE TITLE
Dark Angels: Adding Belial

### ISSUE THREAD

**Issue by nillim** [BSData/wh40k-7th-edition#350]
Adding Belial to your roster does not change the status of Terminators from Elite to Troops as he should.

**Comment by Thairne** [comment]
With my limited knowledge (and checking how Space Marine.catz does it) you can and should simply select the Terminator (Troop) Option in your rooster when building the list.
The Chapter Master on a bike that unlocks Bikers as troops does not work differently, as does the Master of the Forge.
Someone correct me if there is an option to switch around the category of a model/unit ;)

There seems to be a workaround here (and the confirmation for not being able to switch the category at that time):
http://forum.battlescribe.net/viewtopic.php?f=8&t=585

I'll see if I can get it done when I get around to it.

**Comment by Thairne** [comment]
The current implementation works as-is. DW Troops cannot be taken without either Azrael or Belial: Switching the category around is not a available function at this time.
