### ISSUE TITLE
Dark Angels - Legion Sicaran & Contemptor MIA

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3502]
**File:** Dark Angels - Codex (2015).catz

**BattleScribe version:** 2.00.27

**Platform:** Android

**Dropbox:** Yes

**Description:** Legion sicaran and contemptor along with some other forgeworld items are no longer displaying even with forgeworld options activated.

**Comment by Thairne** [comment]
They got moved to uncategorized...
*le sigh*

**Comment by Thairne** [comment]
https://github.com/BSData/wh40k/commit/2519cf9881ff0598adce83392a2ece1327b4e3c3
