### ISSUE TITLE
Space Marine Captain Cannot Take Melee Hand Relics

### ISSUE THREAD

**Issue by rberrill** [BSData/wh40k-7th-edition#3503]
**File/Catalogue:** Space Marines

**BattleScribe version:** 2.00.

**Platform:** iOS/Mac

**Dropbox:** No

**Description:** 

I was attempting to built a Space Marine Captain, and in the past I've always been able to build him with Bolt Pistol hand, Thunder hammer, Melee Hand, The Shield Eternal.

When I went to build a list this morning I'm getting this when I try to add a relic:

Power Armor cannot have any selections of Chapter Relics - Melee Weapons (hidden)

I have attached the data file
[SpaceMarineCaptainError.rosz.txt](https://github.com/BSData/wh40k/files/821805/SpaceMarineCaptainError.rosz.txt)

**Comment by DrTobogganMD** [comment]
Odd, I get no error when loading your roster file:

![image](https://cloud.githubusercontent.com/assets/16939161/23619939/eb933d30-025a-11e7-82da-9f6c02fb1a3c.png)

What version of BS are you on?  Also - Thanks for including a roster file. I can't tell you how much that helps troubleshooting.

**Comment by rberrill** [comment]
I'm on v 2.00.14.71, let me reload my data file and see if it makes a difference.  Thanks for checking it.

**Comment by DrTobogganMD** [comment]
Fuck, I was hoping .14 didn't break things.  Let me know if reloading helped.

**Comment by DrTobogganMD** [comment]
![image](https://cloud.githubusercontent.com/assets/16939161/23620675/67b50478-025d-11e7-97a9-745ec1749599.png)

Nope, still fine in .14 desktop it seems.  Let me know if reloading helped.

**Comment by rberrill** [comment]
I just reloaded it, I was on v2028 of the space marine, pulled the most recent down from GitHub (which is still v2028, I saw you were on 2029 in your screen and wanted to make sure that's not a difference)  It works after the reload.  Guess we can just chalk this up to it caching some strange data in the background or something.  Thanks for looking into it.

**Comment by DrTobogganMD** [comment]
v2029 is my working revision. I'm adding Bobby G and the start of the Victrix Strike Force that I have leaks for, as well as a few bugfixes.  Nothing in it has changed regarding relics or the captain.  I'm guessing it was just an odd data bug if the reload fixed it.
