### ISSUE TITLE
Catalogue workers

### ISSUE THREAD

**Issue by senpai514** [BSData/wh40k-7th-edition#351]
**[MOD EDIT]:** _This is now part of wiki https://github.com/BSData/wh40k/wiki/Catalogue-Keepers - the version here is not current._

I know there is only a few of us compared to the number of army catalogues and we all volunteer to help maintain files when we have the available moment and from what I have seen most of the major contributors are here and tracking daily I thought it might be nice to keep track of who works on a particular catalogue as their primary armies and have "claimed" it so to speak.  This could help to prevent someone different from working on the same file as you and possibly create commit errors if changes post at the same time (has happened to me a couple times) and allow you to update add or edit the way you have been doing a particular catalogue.  As these are more often than not the armies we each play we would know them the best.  This way we can give that person the chance to make the necessary changes 

So if you guys are onboard add in below what your primary armies are that you look after

| Catalogue | Author |
| --- | --- |
| Adepta Sororitas | Kangodo |
| Astra Militarum - codex |  |
| Astra Militarum - FW - Armoured Battle Group |  |
| Astra Militarum - FW - Death Korp of Krieg Assault Brigade |  |
| Astra Militarum - FW - Death Korp of Krieg Siege Regiment |  |
| Astra Militarum - FW - Elysian Detachment D-99 |  |
| Astra Militarum - FW - Elysian |  |
| Blood Angels | Kangodo |
| Chaos Demons | NebSeele |
| Chaos Space Marines - Codex | NebSeele |
| Chaos Space Marines - Black Legion | NebSeele |
| Chaos Space Marines - Crimson Slaughter | NebSeele |
| Dark Angels | Thairne |
| Dark Eldar | Toreador13 |
| Dark Eldar - Haemonculus Covens |  |
| Eldar - codex | capitaladot |
| Eldar - FW - Corsairs | capitaladot |
| Eldar - Iyanden |  |
| Fortifications and Stronghold assault | Kangodo |
| Grey Knights | amis92 |
| Harlequin | Kangodo |
| Imperial Knights | Senpai514 |
| Inquisition | Senpai514 |
| Legion of the Damned | Senpai514 |
| Militarum Tempestus |  |
| Necrons - codex | Kangodo |
| Necrons - FW - Dark Harvest | Kangodo |
| Orks - codex | Kangodo |
| Orks - FW - dread mob |  |
| Renegades & Heretics |  |
| Renagades & Heretics - FW - defenders of vraks |  |
| Renagades & Heretics - FW - Servants of Decay |  |
| Renagades & Heretics - FW - servants of Slaughter |  |
| Space Marines - codex | Senpai514 |
| Space Marines - FW - Siege Assault Vanguard | Senpai514 |
| Space Marines - Clan Raukaan | Senpai514 |
| Space Marines - Sentinels of Terra | Senpai514 |
| Space Wolves |  |
| Tau - codex | amis92 |
| Tau - Farsight Enclaves | amis92 |
| Tyranids | Randobar |
| Tyrants Legion - FW - Defenders of Badab |  |

**Comment by NebSeele** [comment]
I'm currently focused on trying to get the CSM files up to date so they have the battle formations, shared profiles etc. I can keep an eye on the daemons one as well. 

I'm not so familiar with the imperium, especially their FW and the newer stuff to be able to contribute.

**Comment by ghost** [comment]
I don't know how to do any changes or anything including how to report a
bug like in the space marines its not listing hull points for some of the
vehicles. I'd fix it myself except I don't know how to.

On Mon, Sep 15, 2014 at 7:04 PM, NebSeele notifications@github.com wrote:

> I'm currently focused on trying to get the CSM files up to date so they
> have the battle formations, shared profiles etc. I can keep an eye on the
> daemons one as well.
> 
> I'm not so familiar with the imperium, especially their FW and the newer
> stuff to be able to contribute.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/BSData/wh40k/issues/351#issuecomment-55682021.

## 

If at first you don't succeed, call in an air strike.

**Comment by ghost** [comment]
nevermind looks like someone else noticed and fixed already today

On Mon, Sep 15, 2014 at 7:07 PM, Jimmy Shelton sprints54@gmail.com wrote:

> I don't know how to do any changes or anything including how to report a
> bug like in the space marines its not listing hull points for some of the
> vehicles. I'd fix it myself except I don't know how to.
> 
> On Mon, Sep 15, 2014 at 7:04 PM, NebSeele notifications@github.com
> wrote:
> 
> > I'm currently focused on trying to get the CSM files up to date so they
> > have the battle formations, shared profiles etc. I can keep an eye on the
> > daemons one as well.
> > 
> > I'm not so familiar with the imperium, especially their FW and the newer
> > stuff to be able to contribute.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/BSData/wh40k/issues/351#issuecomment-55682021.
> 
> ## 
> 
> If at first you don't succeed, call in an air strike.

## 

If at first you don't succeed, call in an air strike.

**Comment by senpai514** [comment]
@Pohok I have already fixed missing hull points for the razorback, stormtalon and stormraven

@NebSeele Im glad your watching the chaos stuff last few fixes I had to get before you joined us. I don't mind it as I have copies of all the rulebooks in pdf or ebook formats. you working on the supplements too?

**Comment by ghost** [comment]
is there a guide that will teach me how to fix stuff that way I can just do
it when I notice somethings missing? or do you want me to just send a
message saying what's wrong?

On Mon, Sep 15, 2014 at 7:15 PM, Thommy notifications@github.com wrote:

> @Pohok https://github.com/Pohok I have already fixed missing hull
> points for the razorback, stormtalon and stormraven
> 
> @NebSeele https://github.com/NebSeele Im glad your watching the chaos
> stuff last few fixes I had to get before you joined us. I don't mind it as
> I have copies of all the rulebooks in pdf or ebook formats. you working on
> the supplements too?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/BSData/wh40k/issues/351#issuecomment-55682738.

## 

If at first you don't succeed, call in an air strike.

**Comment by senpai514** [comment]
@Pohok there is some good getting started info on the main page https://github.com/BSData/wh40k if you scroll down to the bottom. Of course don't be afraid to ask for help if you need it

**Comment by NebSeele** [comment]
@Senpai I am also going to include the supplements in the list for bug fixes and additions. I'll most likely add the formations to them once I have the vanilla codex done.

**Comment by Thairne** [comment]
Chalk up Dark Angels for me, I'm currently working on redoing the entire redundant data structure in the profiles. A commit with a conflict would be devastating ;)

**Comment by ghost** [comment]
I've marked everything I built and/or actively maintain. The files marked with an asterisk\* are not particularly important to me - I only made them since they were related to the other stuff - so I'll continue to look after them, but equally I won't complain if someone else takes ownership.

**Comment by amis92** [comment]
I'm Tau author. I've added myself :)

EDIT: Actually I've done a table format :)

**Comment by Thairne** [comment]
We really need to get some load of Khambatta... :P
I've just installed and configured BS at my workplace _cough cough_ should help me get done with my DA sooner than later, so I can take over some of the minor dexes later.

**Comment by senpai514** [comment]
I'll be back up for @khambatta with the other codex space marines based catalogues (sentinels & raukaan) and Legion of the Damned. I'll grab Imperial Knights too while I'm at it just finished building my Lancer to team up with Gerantius.

**Comment by Randobar** [comment]
I´m looking for Tyranid Bugs and suggestions.
Not that often but i think they need some love.

**Comment by Senpai** [comment]
Psst. @Senpai is not the same as @Senpai514. :)

**Comment by Kangodo** [comment]
I've taken a look at some of the datafiles.
And how would you like it if we assign stuff to authors when people open an issue?
Because with a lot of the recent changes the files are getting more complicated by the day, to the point where I am often afraid to change anything because it might break something.

An example would be #395 : The fix is easy, but @khambatta probably had a good reason to do it like that and I don't feel comfortable changing stuff at this point.

**Comment by ghost** [comment]
The thing to watch out for is if you fix a mistake, look for other instances of it. For example, the Sentinals of Terra and Clan Raukaan are both built from the same source file, so a bug in one is likely to show up in the other. Likewise with formations and units copied into them.

I am worried about making changes when the author might be working on the file at the same time.

**Comment by Toreador13** [comment]
Anyone else working on the Dark Eldar file? I have gotten about 1/3 of the way through it so far. Hoping to have something up tonight. At least the basics. Can work on formations and such later.

**Comment by senpai514** [comment]
I haven't seen the codex yet.

**Comment by Toreador13** [comment]
If no-one else speaks up, you should probably put me down for it ;)

**Comment by Toreador13** [comment]
Quick question, but is there anywhere we keep a standard? I am curious how people have been labeling formations. In the catalogue I was almost to the point of labeling them Formation: to keep them straight. I noticed some other people were doing "formation". Is there a standard way we should do things like that? I looked, and nothing is in the 40k Wiki, but maybe we could put some of the standards there so people could glance quickly at them while they are working if we don't have some other place yet.

**Comment by NebSeele** [comment]
I can't remember which post it was (and am unable to find atm), but a post on standards was brought up recently (and I think it was said that a universal standard is impossible for a few reasons).

As for formations, if these are the ones in the codex, then they'd be classed as formations (accessible via formation detachment in the roster editor). Apocalypse formations are Battle Formations to keep them separate for the meta's that forbid apoc formations in standard games.

**Comment by Toreador13** [comment]
Yep. I just noticed that one of the marine supplements someone had put quotes around the formations in the list so they stood out in the catalogue. Might just be a preference, but I was thinking about doing that in the name of the formation. Formation: Carnival of Pain  just to make the catalogue easier to view, not necessarily for the users

**Comment by ghost** [comment]
I use "quote marks" for formations and 'apostrophes' for aopc battle formations. It puts them all together in the catalogue editor and it distinguishes things that share a name, like the two different versions of Green Tide.

You might want to mark Forge World units with [FW] or (FW), 'cos some places still exclude them.

**Comment by Toreador13** [comment]
That is what I must be seeing. FW should probably always be marked just for lack of confusion. I do agree with that. Even for places that do use them people are confused when making lists, and marking them with FW makes them stand out. the quotes and tics make sense. I may start off doing Formation: and Battle Formation: but will see about feedback. Haemonculus Covens have a bunch.

**Comment by ghost** [comment]
My pull for Eldar Corsairs was accepted, so please list me there.

**Comment by ghost** [comment]
I can also take Eldar if Magic8ball is no longer involved.

**Comment by ghost** [comment]
Perhaps asking Jon to add a unit type label in the interface would help? Alternatively, what about asking hin to make Formation a new unit type?

**Comment by ghost** [comment]
I strongly disagree with the "FW marking" and the 5 clicks it takes to get FW units to show up in the Space Marine file.

I woukd propose instead that pull requests in the future be rejected unless each new unit lists the book it comes from. Then, perhaps, a more sensible "disable FW" entry could be added to "(No category)" to hide those units from those bothered by their inclusion.

**Comment by amis92** [comment]
@capitaladot I don't understand what you mean by "unit type label" and "making formation new unit type"? What is "unit type" you refer to?

Your proposal to reject pull requests in case they don't contain some information would be correct, but it's not. We crave for more workforce, and anything we get from outside is a bonus. It's all free will, and we're not popular enough to reject meaningful additions. We all do it for free, as good as we can. If you want something better, do it yourself. If someone does something, and it's correct enough, we accept it.

@all

I do not like hiding FW, but I do see a point in it - SM is a mess with FW units. I'll link you all again to my BattleScribe UserVoice request to make Book field more meaningful. Imagine you could check what books to use for a given force, and only units from that book would show up. http://battlescribe.uservoice.com/forums/55066-general/suggestions/6312936-enhance-the-role-of-book-field

**Comment by Thairne** [comment]
I kind of agree with FW. I choose the other approach - display until hidden, for the very same old reason - keep things as is and give the user new options. But, after all, Senpai is the master of the cataloque and has the last word. Maybe as a compromise a "show all" check would help?

**Comment by senpai514** [comment]
Codex: Space Marines is unique as it can make 18 different armies with army wide rules and bonuses that apply to themselves each separately via the implementation of the Chapter Tactic rule when they redid the codex last year. And because of that with the mainstreaming of FW models becoming more popular for general use created a HUGE amount of variety for making an army.  For this particular catalogue I believe this current setup will work best for the current features we have within Battlescribe.

Having to make additional clicks and selections is something you have to do in other army builder programs so nothing really specific to us (except we have all the models available to choose already while last I checked they still don't.)  ;)

The hiding is used two-fold: it was the best way to help manage units and characters and units that are chapter tactic specific that are both codex and FW based. Codex hq's only need their Chapter Tactic selected (which Must be done anyway) to become visible (makes sense enough to only show what models you can legally use, cant run a salamander in an ultramarine army so no need to see him). FW HQ also have the show FW hq in addition to the chapter tactic. Since there are almost 50 separate choices for HQ's combined I saw this as the best way to manage the vast number of selections. 
As for the rest of the models I decided to follow the same pattern that was used to manage the hq's and chapter tactic rules so that a single system was being used to manage the "clutter" of force types between FW models and Chapter Tactic specific units which I still have a bit to do and add in for the different armies.

**Comment by senpai514** [comment]
@khambatta  just wondering if you have seen IA4 Second Edition yet

I noticed that while I was updating Solomon lok for Inquisition that D-99 can not take any LOW as per pg 95. I have updated the catalogue accordingly.

**Comment by ghost** [comment]
@senpai514 the D-99 list is from IA4se: they cannot take Lords of War if they are the Primary Detachment. That's why each LOW has a modifier attached, setting Max=0 if the force has either 1x Warlord, or 1x Primary Detachment.

_If the D-99 is the primary, no other detachment in your army can take an LOW either, but there's no way to make that happen._

**Comment by ghost** [comment]
Note for all - Fighter Aces got an update in "Shield of Baal: Leviathan". Now 35pts & available to any flyer or flying monstrous creature, any army. I do not know if that includes or excludes named/unique FMCs; the rule just says "any".

**Comment by senpai514** [comment]
Ahh I see tricky GW wording writers. My bad sorry. It seems after re-reading the book that the writers were still in the mindset of when it just used to be primary det and allied det before the intro of the CAD. But who knows with GW anyways lol

I'm still waiting to find a copy of shield of Baal to download for my library

**Comment by ghost** [comment]
I've going to step down at this point. All the best :)

**Comment by Toreador13** [comment]
Sad to see you go! You did a huge amount of work!

**Comment by amis92** [comment]
**khambatta** - we'll miss you! Thank you for all the work you contributed.

**Comment by Kangodo** [comment]
We surely will, good luck and thanks for all the work!

**Comment by Kangodo** [comment]
A small update: I will not work on the "Necrons - FW - Dark Harvest" for now since it's such a big mess since the Necron Codex got released.
Updates will happen when FW decides to bring out a massive FAQ.

**Comment by axisofentropy** [comment]
I'm all over the Adeptus Mechanicus Skitarii. You may assign me future issues.

**Comment by NebSeele** [comment]
Add the Khorne Daemonkin to the list of Chaos catalogues. I've working on an initial work on the codex, pending the full release this weekend.

**Comment by senpai514** [comment]
@amis92 for some reason I'm unable to edit original post to add in the new codex to the list

**Comment by amis92** [comment]
I don't know why. However seeing as this isn't really active issue (not an issue at all, actually), I will close it and move contents to Wiki - it's more fitting for such static content.

Anyone can edit wiki, so. I'll add Khorne Daemonkin on-the-air while at it.

**Comment by amis92** [comment]
Okay, moved: https://github.com/BSData/wh40k/wiki/Catalogue-Keepers

Feel free to edit it.
