### ISSUE TITLE
Chaos Daemons Bloodthristers

### ISSUE THREAD

**Issue by fejjn** [BSData/wh40k-7th-edition#3510]
**File/Catalogue:** 
Chaos Daemons v2027
**BattleScribe version:** 2.00.
v2.00.13.70
**Platform:** Windows/iOS/Android/Mac/Linux
Windows
**Dropbox:** Yes/No
No
**Description:** Detailed issue description.
When a Wrath of Khorne Bloodthrister(might be all 3 Bloodthirsters) takes "Armour of Scorn" or "The Crimson Crown" i get a warning that; "1 too many selections from Hellforged Artifacts maximum 0" - when it in fact can take it.

**Comment by fejjn** [comment]
Seems to work in 2.00.14..

**Comment by FarseerVeraenthis** [comment]
User reports this issue can be closed as it works in the latest version of the software.
