### ISSUE TITLE
New Secutarii Hoplites and Peltasts rules

### ISSUE THREAD

**Issue by DedusJovus** [BSData/wh40k-7th-edition#3511]
**File/Catalogue:** Skitarii - Codex.catz

**BattleScribe version:** 2.00.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** I just wanted to point out that the Secutarii Hoplites and Peltasts got their official rules in the latest Horus Heresy book which differ from those in the pdf on FW site (and currently in BS data) and should be changed accordingly. Just in case you missed them. Thank you for your hard work.

**Comment by Thairne** [comment]
Inferno contains the rules for 30k.
The PDF, which btw is still on the site, is for the 40k rules.
