### ISSUE TITLE
Change of priest placement.

### ISSUE THREAD

**Issue by ghost** [BSData/wh40k-7th-edition#3512]
I hope i'm writing in the right forum, but if i can make  a suggestion:
The ministorum priest is used interchangeably like a commisar for astra militarum
 Could you add the priest as tick box like the commisar in the unit selections?
It would make it much easier to get a good overwiev on the squads as they are always placed in ones.

Also, the catachan ambush patrol formation from apocalypse 2:nd edition is missing.

Thanks!

**Comment by alphalas** [comment]
The priest is a independent character and as such can be attached  to any squad,  not an assigned squad like the commissar.

**Comment by ghost** [comment]
Yes that is completly true, but the priest is as far as i know never played independantly, he is attached to a squad to give them fearless.

That is why it would be so much easier to have a selection for him in the squad meny.

Right now the used method is to select the priest in "no force org", and pray you remember which squad he was supposed to go, which i personaly always forget. Not really optimal.

**Comment by DrTobogganMD** [comment]
How players play him, and how his rules are written are, sadly, not always the same.  

In the same vein of you not remembering what squad you put him in, if we add a checkbox like you describe, just as many others will begin to think the Priest is an upgrade and not a separate unit choice. 

As for the Ambush Patrol, Apoc 2nd edition is from 2011, 5th edition 40k.  It is not present in the latest version written for 6th edition.  It was also a Battle Formation, not usable outside of an Apocalypse detachment.
