### ISSUE TITLE
Space Marines - Tactical marines chainswords

### ISSUE THREAD

**Issue by GenWilhelm** [BSData/wh40k-7th-edition#3518]
**File/Catalogue:** Space Marines: Codex (2015) v2031

**BattleScribe version:** 2.00.14

**Platform:** Windows

**Dropbox:** Yes

**Description:** Space Marines in Tactical squads should be able to swap their boltgun for a chainsword. Currently only Carcharodons have the option.

**Comment by DrTobogganMD** [comment]
Wat u smokin willis?

![image](https://cloud.githubusercontent.com/assets/16939161/23807779/9e064dca-058c-11e7-94b1-655533a828fc.png)
