### ISSUE TITLE
[Anon] Bug report: Fallen Angels - Supplement.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3519]
**File:** Fallen Angels - Supplement.catz

**BattleScribe version:** 2.00.28

**Platform:** Android

**Dropbox:** No

**Description:** Plasma guns and meltaguns are listed as 5 points for Fallen w/ special weapons instead of 15 and 10, respectively.

**Comment by GenWilhelm** [comment]
Closed by f228ff1e2156a00c88921b6ae93373c8682a623f
