### ISSUE TITLE
Castellans of the Imperium Implementation

### ISSUE THREAD

**Issue by alphalas** [BSData/wh40k-7th-edition#3525]
The Following factions need to Implemented for Castellans of the Imperium:

- [x] Assassins
- [x] Astra Militarum
- [x] Astra Telepathica
- [x] Adepta Sororitas
- [x] Inquisition
- [x] Imperial Knights
- [x] Cult Mech (enginseer/servitors) - Thairne: Use the AM Enginseer instead.
- [x] Militarum Tempestus
- [ ] Space Marines

**Comment by Thairne** [comment]
IK and Cult already had them for Grand Convocation.

**Comment by FarseerVeraenthis** [comment]
Am I supposed to be doing Space Marines? @Kohato was working in there last...

**Comment by DrTobogganMD** [comment]
Nah, I am - i'm just lazy as shit.  I'll work on it today.

**Comment by DrTobogganMD** [comment]
Done like Steak!
