### ISSUE TITLE
Where is the 40k 1.15x data? 

### ISSUE THREAD

**Issue by merlinbk** [BSData/wh40k-7th-edition#3528]
**File/Catalogue:** 

**BattleScribe version:** 2.00.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

**Comment by cartag** [comment]
Side note, if you are wanting to use 1.X data with 2.X BS, you're gonna have a bad time.

**Comment by alphalas** [comment]
Also, just to reiterate, we do not update the 1.15 data - so there's nothing new in it

**Comment by merlinbk** [comment]
I found it, thanks. 
https://github.com/BSData/wh40k/releases/tag/v4.18.7
