### ISSUE TITLE
Cult Mechanicus: Eradication Cohort missing

### ISSUE THREAD

**Issue by Bparks1983** [BSData/wh40k-7th-edition#3530]
File/Catalogue:  Cult Mechanicus (2015) v2015

BattleScribe version:  2.00.28

Platform:  Android

Dropbox:  No

Description:  The Cult Mechanicus formation part of the Eradication Cohort (EC) is missing.  You're able to successfully select the Force Org for the EC but when you enter the Formation (Eradication Cohort), there is nothing to select at all.  The Skitarii portion still shows properly.

**Comment by Thairne** [comment]
Done
