### ISSUE TITLE
company champion loadout issue

### ISSUE THREAD

**Issue by IronWulfen88** [BSData/wh40k-7th-edition#3531]
**File/Catalogue:** 

**BattleScribe version:** 2.00.28

**Platform:** Android

**Dropbox:** Yes
**Description:** the option for the combat shield is missing from the command squad

**Comment by FarseerVeraenthis** [comment]
Which catalogue/army?

**Comment by DrTobogganMD** [comment]
That'd be a Veteran Company Champion.  I'll take a look.

**Comment by IronWulfen88** [comment]
ive been playing around with lists ususing the chapter tactics of imperial fists and slamanders to see what kinds of lists I can make. there is the option to take a company champion in a command squad but not the option to give him a combat shield and power sword like it says in the codex. im using the standard space marine catalogue.
