### ISSUE TITLE
SM Codex - Pedro Kantor is hidden

### ISSUE THREAD

**Issue by Granitz79** [BSData/wh40k-7th-edition#3532]
**File/Catalogue:** Space marines Codex v2033

**BattleScribe version:** 2.00.

**Platform:** iOS

**Dropbox:** Yes/No

**Description:** Pedro Kantor cannot be selected as a HQ choice for Crimson Fist Chapter Tactics. On an old roster I had, BS gave me an error saying "No selections of Pedro Kantor allowed (hidden)"

**Comment by FarseerVeraenthis** [comment]
Just to confirm, this is an error message that is displaying when you open an old roster, yes?

Argh, I just looked and I can confirm he is missing on Android, it looks like the characters show/hide related to Chapter Tactics needs reviewing...

**Comment by Granitz79** [comment]
Correct. Also cannot find him on any new roster I create.

**Comment by DrTobogganMD** [comment]
Hah, I wonder if I took that off when I was fixing chapter tactics of others.  I'll fix it today.
