### ISSUE TITLE
Deathwatch - Typos

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3533]
**File:** Deathwatch - Codex.catz

**BattleScribe version:** 2.00.18

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** Text errors: the Relic of the Vigilant The Tomb of Ectoclades should be The Tome of Ectoclades.

Text errors: the listing to select a Combi-Melta instead says Comb-Melta.

**Comment by FarseerVeraenthis** [comment]
what version is your data??
these typos are not present in v2029, which I just downloaded from appspot...
