### ISSUE TITLE
[Join Request] Warhammer 40k

### ISSUE THREAD

**Issue by Crowbar90** [BSData/wh40k-7th-edition#3534]
**File/Catalogue:** 

**BattleScribe version:** 2.00.15 (Win/Mac/Lin) / 2.00.29 (Android)

**Platform:** Windows/Android/Mac/Linux

**Dropbox:** Yes

**Description:** I would like to help in the development, I can fix smaller issues (stuff like typos or wrong cactegories) and I'm learning more about Battlescribe data files every day, so hopefully I will be able to help with bigger problems in the future!

**Comment by amis92** [comment]
Hello, @Crowbar90. Please accept the invitation in the email or on the [BSData organization webpage](https://github.com/BSData). Welcome aboard!

Don't forget to read through [Wiki pages](https://github.com/BSData/bsdata/wiki), there are some useful guides, especially [Developer Guide](https://github.com/BSData/bsdata/wiki/Developer-Guide).

Also join our team in Gitter chat room (GitHub login): [![Join the chat at https://gitter.im/BSData/wh40k](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/BSData/wh40k?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

As that is a very busy repository please make sure to carefully follow guidelines from wikis, check out our [Catalogue Keepers list](https://github.com/BSData/wh40k/wiki/Catalogue-Keepers) and actively follow conversation on Gitter and in issues.

Cheers!
