### ISSUE TITLE
Cult Mechanicus - Ordinator Stats missing & Atrapos MIA

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3537]
**File:** Cult Mechanicus Codex 2015.catz

**BattleScribe version:** 2.00.29

**Platform:** Android

**Dropbox:** No

**Description:** Ordinators stats are not showing unlike previous version for cult mechanicus when viewing the stata
Atrapos no longer LOW for cult mechanicus and cannot be selected

**Comment by Thairne** [comment]
Atrapos never was a LOW for Cult, as neither was any other Knight.
Atrapos is available in an Oathsworn Detachment.
Profiles for the Ulators also do show.
Either it's a BS bug or you're doing something wrong.. in any case, closed.
