### ISSUE TITLE
Chaos Space Marines - Warlord Selection Option Requested

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3540]
**File:** Chaos Space Marines - Codex.catz

**BattleScribe version:** 2.00.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** I cannot select magnus the red as my warlord. He is in the formation "lord of the legion" and I am using a CSM Thousand Sons Grand Coven detatchment.

**Comment by cartag** [comment]
The Warlord selection box isn't always in all HQ choices in the CSM file, it's strictly cosmetic. There is no difference other than it just having the word "Warlord" on the roster. 

That being said, I can add it if it's that important.
