### ISSUE TITLE
Deathwatch - Errors in Mission Tactics

### ISSUE THREAD

**Issue by FarseerVeraenthis** [BSData/wh40k-7th-edition#3544]
**File/Catalogue: Deathwatch, v2029** 

**BattleScribe version:** 2.00.15

**Platform:** Windows

**Description:** Deathwatch Mission Tactics in the No Force Org slot are incorrect. They currently reference re-roll "To Wound" when it should be re-roll "To Hit" rolls of a one.
Also there is a typo, it's Venator, not Vanator.

**Comment by Crowbar90** [comment]
The Mission Tactics entry incorrectly links to Furor/Venator/etc. Doctrines. I'm currently adding the entries for the various Tactics and fixing links and typos.
