### ISSUE TITLE
Gue'vesa in Tau Adds 1 Extra point 

### ISSUE THREAD

**Issue by LockeWatts** [BSData/wh40k-7th-edition#3547]
**File/Catalogue:** Tau Empire: Codex (2015) v2010

**BattleScribe version:** 2.00.14

**Platform:** All

**Dropbox:** No

**Description:** Add a Gue'vesa squad to a roster. It will list them at 4 pts per model correctly, and count correctly, but for some reason the unit itself costs 4x+1 points.

**Comment by GenWilhelm** [comment]
Imperial Armour 3 Second Edition: The Taros Campaign p231 they are listed as 25pts for a unit of 6, with additional models for 4pts each.

Is there another, more recent, publication that gives different values?

**Comment by alphalas** [comment]
I think anon just isn't use to FW having built-in points above the model cost
