### ISSUE TITLE
Blood Angels Formations lacks the Blood Angel Carmine Host formation from the Blood Angels Start Collecting box

### ISSUE THREAD

**Issue by direhippo** [BSData/wh40k-7th-edition#3549]
**File/Catalogue:** 

**BattleScribe version:** 2.00.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

**Comment by FarseerVeraenthis** [comment]
Please describe the formation, either using words or by posting a photo of the rules from the box...
Otherwise we don't know what to implement :smile:

**Comment by direhippo** [comment]
Certainly! ->
Blood Angels Start Collecting Box->

Blood Angels Carmine Host

Formation:
1 Captain
1 Tactical Squad
1 Baal Predator

Restrictions:
The Captain must be equipped with Terminator armour.

Special Rules
*Honour the Primarch:* Once per game, at the start of the turn, the Captain
can call upon his battle-brothers to remember the glory of Sanguinius and
emulate his greatness in the crucible of battle. Until the beginning of the
next turn, the Captain and any units from the Carmine Host that are within
12" of him have Feel No Pain and It Will Not Die special rules.
