### ISSUE TITLE
Space Marines - Infernum Pattern Razorback missing

### ISSUE THREAD

**Issue by battlebrother** [BSData/wh40k-7th-edition#355]
Hi guys,
The Infernum Pattern Razorback (Multi-melta instead of usual armament) was introduced as an alternative to any unit that can take a Razorback in CSM, CBA CSW CDA, and the Forge World Equivalents.

Rules are in Imperial Armour 2 2E, page 187

**Comment by senpai514** [comment]
It is already on the action list of everything else I have been working on for updating FW

**Comment by battlebrother** [comment]
Good stuff. I'll try not to post anything more relating to IA2 2E then, I just have a few things that are in it so it's close to my heart :)

**Comment by Thairne** [comment]
Might aswell post em, so I can get around to adding it to DA once Senpai is done with them in SM ;)

Edit: Woops, multiple asignees are impossible... ehe... hehehe... _blushes_

**Comment by senpai514** [comment]
all I had left from IA2 is the razorback, Lucius drop pod, and dreadnoughts
