### ISSUE TITLE
Ynnari Aeldari - Dark Reaper Exarch missing Starshot missiles

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3552]
**File:** Ynnari Aeldari - Supplement.catz

**BattleScribe version:** 2.00.29

**Platform:** Android

**Dropbox:** No

**Description:** dark reaper exarch should be able to choose starship missile for 8 points.

**Comment by FarseerVeraenthis** [comment]
He can take Starshot missiles...
On Windows it is a couple of levels down, on Android you just need to tap the Reaper Missile Launcher and the option to select Starshot missiles is right there.
