### ISSUE TITLE
Castellans Detachment not allowing Combined Arms addition

### ISSUE THREAD

**Issue by foolsama** [BSData/wh40k-7th-edition#3555]
I've created a list with the new Castellans Detachment (Thank you so much for putting that in!!). When i then add a Combined Arms Detachment validation errors presented show the Castellans Detachment then has a maximum of 0 in each Force Org slot. If I de-select a unit for its Force Org Slot (for instance, unchecking the Troops box for a squad), it still shows I need 4 troops.
![example roster](https://cloud.githubusercontent.com/assets/25935714/24081864/2dfa7238-0c92-11e7-84bf-7b1411d1e71e.png)
![capture](https://cloud.githubusercontent.com/assets/25935714/24081868/34d54330-0c92-11e7-8155-c59301609be7.PNG)

**Comment by FarseerVeraenthis** [comment]
Yeah, you probably can't combine a Castellans detachment with a Combined Arms Detachment in the same roster because of the way the FoC formations have been validated...
They are a major pain in the ass!!
You need to keep the CAD completely separate from the Castellans Detachment.

**Comment by alphalas** [comment]
There's a constraint bug in Sisters - i'll get right on it.
