### ISSUE TITLE
Deathwatch Forgeworld Options

### ISSUE THREAD

**Issue by ludichris78** [BSData/wh40k-7th-edition#3559]
**File/Catalogue:** 

**BattleScribe version:** 2.00.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

**Comment by ludichris78** [comment]
Forgeworld has stated that there are several units also available to the Deathwatch, including the Caestus Ram, and all Contemptor Deadnought variants.

**Comment by alphalas** [comment]
If you're referring to the picture that was circulating about six months ago, that was never officially confirmed  by forge world. As of right now, deathwatch are specifically by themselves, no Forge World options
