### ISSUE TITLE
Scouts: Heavy weapons cost extra

### ISSUE THREAD

**Issue by amagura** [BSData/wh40k-7th-edition#3562]
**File/Catalogue:** Dark Angels: Codex (2015) v2012; Space Marines: Codex (2015) v2035

**BattleScribe version:** 2.00.29

**Platform:** Android

**Dropbox:**  No

**Description:** 11 extra points are charged to access heavy weapons for scout units: instead of 15 pts for a missile launcher, it costs me 25.  The same thing can be seen using the vanilla Space Marine data, though for some reason it costs them 26 instead of 25.  Please remove the 11 point penalty for taking a heavy weapon: this penalty does not exist in the codices.

**Comment by amagura** [comment]
Sorry, I misspoke, it's 26 points for both vanilla Marines and Dark Angels

**Comment by francoisbeaulieu** [comment]
That's correct: 11 points for the scout himself + 15 for the missile launcher = 26 points. You can remove one of the other scouts to regain the 11 points.

**Comment by amagura** [comment]
Ah, I get it now: 11 points for another model.  Kk, soz about any confusion or frustration caused.
