### ISSUE TITLE
Space Marines - Emperor's Champion Points Cost is Hilarious

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3565]
**File:** Space Marines - Codex (2015).catz

**BattleScribe version:** 2.15.72

**Platform:** Windows

**Dropbox:** No

**Description:** Points value of the Black Templar's Emperor's Champion is incorrect. 

Current data file displays as 407 Points. When it should be 140.

**Comment by FarseerVeraenthis** [comment]
What File Version are you looking at?
I just opened a brand new roster on Windows and the points is correctly 140pts for the Emperor's Champion...
