### ISSUE TITLE
Space Marines - Combat Doctrines Rule showing erroneously for SM Detachments

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3567]
**File:** Space Marines - Codex (2015).catz

**BattleScribe version:** 2.00.30

**Platform:** Android

**Dropbox:** No

**Description:** Black Templars are receiving combat doctrines by default (they shouldn't be). This error is new to a recent update.

**Comment by FarseerVeraenthis** [comment]
This appears to be linked to the Detachment, I just pulled an empty CAD, followed by an empty Allied Detachment, and both had Combat Doctrines already in the view roster screen...!
