### ISSUE TITLE
Blood Angels issues

### ISSUE THREAD

**Issue by IronWulfen88** [BSData/wh40k-7th-edition#3569]
**File/Catalogue:** 

**BattleScribe version:** 2.00.28

**Platform:** Android

**Dropbox:** Yes

**Description:** Im working with the Angels Blade Strike Force set up and the options to turn the terminator captain into Karlaen are not present(Giving the captain the hammer of baal and such. Also an issue popped up with the furioso dreadnought when I gave it the frag cannon arm and replaced the stormbolter on the other with a heavy flamer. it says I have one too many selections of frag cannon and that the minimum is zero

**Comment by GenWilhelm** [comment]
The Angel's Blade Strike Force doesn't name Karlaen as one of the available choices, and I can't see anything from his dataslate that allows him to replace a Captain in a Formation. A Terminator Captain does have the option to upgrade his Thunder Hammer to the Hammer of Baal however.

I've redone the constraints on the Furioso Dreadnought's power fist weapons, and it seems to have fixed that issue.
