### ISSUE TITLE
Codex Space Marine Command Squad

### ISSUE THREAD

**Issue by AstartesMkIII** [BSData/wh40k-7th-edition#357]
Command Squad Veterans don't have an option to select any Special Weapons - i.e. aplasma Guns and Melta Guns etc. 
They have the ability to do this since the FAQ for Codex Space Marines 2014. 
Can you rectify this please? 
Thanks.

**Comment by senpai514** [comment]
some changes that had previously fixed this solution were somehow accidently reversed I am actually in the process of those fixes right now already
