### ISSUE TITLE
Space marines..Error for too many selections for spec. Weapons.

### ISSUE THREAD

**Issue by frohawk8337** [BSData/wh40k-7th-edition#3570]
**File/Catalogue:** 
Space Marines: Codex (2015) v2035 by Earl Bishop (Kohato)

**BattleScribe version:** 2.00.31

**Platform:** Android

**Dropbox:** Yes

**Description:** 
For space marines, I noticed that for full squads of terminators and tactical squads it stats that there are too many selections of special weapons.  It appears that the Sergeant is not couneed toward the total number of marines in a given unit causing an error.

**Comment by DrTobogganMD** [comment]
Please read your codex. 10 model tactical units get 1 heavy and 1 special. 

Terminators should allow two specials for ten models though, that one is also erroring?

**Comment by DrTobogganMD** [comment]
Actually 2035 sounds old. I just committed 2038. Have you updated data recently? It might have been a similar bug that has been fixed.

**Comment by frohawk8337** [comment]
1. Did read the codex...oddly enough the error is gone. I will figure out how I broke it.
2.  Yes that one I have a sergeant, 7 terminators, and 2 special weapons. Screen attached. Max should be 2.





Fro

Sent from Yahoo Mail on Android 
 
  On Tue, Mar 21, 2017 at 10:51 PM, Earl Bishop<notifications@github.com> wrote:   
Please read your codex. 10 model tactical units get 1 heavy and 1 special.

Terminators should allow two specials for ten models though, that one is also erroring?

**Comment by DrTobogganMD** [comment]
Just committed and pushed.  Terminator issue should be resolved with the next release (sometime later today)
