### ISSUE TITLE
Space marines forge world hq options for detachments/formations \request

### ISSUE THREAD

**Issue by frohawk8337** [BSData/wh40k-7th-edition#3572]
**File/Catalogue:** 
Space Marines: Codex (2015) v2035 by Earl Bishop (Kohato)
**BattleScribe version:** 2.00.31

**Platform:** Android

**Dropbox:** no

**Description:** Detailed issue description.

When selecting forgeworld/apocalypse options  (non force org) for formations and detachments none of the special captains or units pop up. For example flame blade strike force detachment the for the salamanders.  I cannot select harath shen nor Pell as mir'San as a captain in either the core selection or the command selection.

**Comment by DrTobogganMD** [comment]
That's because they're not valid choices.  Read your supplement again.

**Comment by frohawk8337** [comment]
I have and also checked a few forums.  Majority of what I have found suggests fw models are legal in formations and detachments.  Ultimately, and naturally it would be up to the players to decide in most cases, but would also be a nice feature.

Sent from Yahoo Mail on Android 
 
  On Tue, Mar 21, 2017 at 9:49 PM, Earl Bishop<notifications@github.com> wrote:   
That's because they're not valid choices. Read your supplement again.

**Comment by alphalas** [comment]
When we write cats we use rules as written. Rules as written, forge world options are not allowed in codex formations/detachments unless explicitly stated in the forge world unit entry

**Comment by frohawk8337** [comment]
Nah, I understand where you are coming from. GW rules can be a bit dicey. I was using this reference though, forgeworld errata 6th edition V2 (I know we are 7th, technically and we know they will never change it again) on badab characters, 
"...As with the special characters presented in Codex: Space Marines, may be included as part of any detachment with the same chapter tactic..."
Ultimately, your call. I can work around it either way. Love the app and the cats. Keep up the good work and thanks for the fast support.
Fro

Sent from Yahoo Mail on Android 
 
  On Tue, Mar 21, 2017 at 9:57 PM, alphalas<notifications@github.com> wrote:   
When we write cats we use rules as written. Rules as written, forge world options are not allowed in codex formations/detachments unless explicitly stated in the forge world unit entry

**Comment by DrTobogganMD** [comment]
Yea, Badab is the bane of my existence.  Even if that were the case - The AoD detachments state exactly what units are allowed.  I imagine FW will update eventually to allow, but till then we can't add it. Sorry.

It's a similar case to using Bobby G in a Castellens Detachment.  He's legal in all imperium armies, but he's not a valid choice for a Castellens.
