### ISSUE TITLE
Blood Angels Formations missing

### ISSUE THREAD

**Issue by jcwhumes** [BSData/wh40k-7th-edition#3573]
**File/Catalogue:** Blood Angels codex 2014 v2002

**BattleScribe version:** 2.00.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** No

**Description:** Detailed issue description. 

Leaders of the Angelic Host, Rapid Assault force and Fire support force all seem to be missing as formations from the Blood angels codex (Angel's Blade supplement).

They are available as part of an Angel's Blade Strike Force (decurion style detachment), but not available individually under the formations tab.

**Comment by GenWilhelm** [comment]
Which pages are their datasheets on?

The only reference to them that I can see is under Command and Auxiliary choices for the Angel's Blade Strike Force.

**Comment by DrTobogganMD** [comment]
Just because they are choices for a meta-detachment doesn't mean they are formations.  As is the case here, these are not formations.
