### ISSUE TITLE
Multiple Autarchs

### ISSUE THREAD

**Issue by rmld** [BSData/wh40k-7th-edition#3580]
**File/Catalogue:** Ynnari

**BattleScribe version:** 2.00.3q

**Platform:** Windows and Android (possibly others)

**Dropbox:** No

**Description:**

Attempting to write list with multiple Autarchs. Error reads: "All Autarchs must have same nun we of ___" Items range from Masks to Bikes and weapons. Program also tries to double-load one of the Autarchs, creating errors of "Autarch has too many from option ___"

The Codeces in use (Craftworld, Gathering Storm II, etc) do not support requirements of identical loadouts.

**Comment by rmld** [comment]
Sorry...version is 2.00.31

**Comment by DrTobogganMD** [comment]
Because i'm dumb and made those collective for some reason.  Fixing

**Comment by FarseerVeraenthis** [comment]
is this related to #3579 ??

**Comment by DrTobogganMD** [comment]
Maybe? I don't touch Corsairs.
