### ISSUE TITLE
Dark Angels - Space Marine HQ Command Tanks Missing

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3585]
**File:** Dark Angels - Codex (2015).catz

**BattleScribe version:** 2.00.15

**Platform:** Mac

**Dropbox:** No

**Description:** The Space Marine Hq Command Tanks should be an HQ option for Dark Angels.  Thanks for all the hard work on the updates.

**Comment by FarseerVeraenthis** [comment]
~~Not true. These tanks are Faction Space Marines,  not Faction Dark Angels, therefore they're not able to be used in a Dark Angels army.~~
Edited: I should have found a more complete datasheet and read all of it...!

**Comment by DrTobogganMD** [comment]
http://www.belloflostsouls.net/wp-content/uploads/2015/06/marinecommandtanks-02.jpg
They are Dark Angels when you choose to make them Dark Angels.

**Comment by FarseerVeraenthis** [comment]
Botherations!!

**Comment by Thairne** [comment]
Most likely a remnant of the category switcheroo a while ago.

**Comment by Thairne** [comment]
as a non-standard codex unit they are available if you choose to show FW entries.
