### ISSUE TITLE
Point cost error for tactical squad special and heavy weapons - Sentinels of Terra.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#359]
**File:** Space Marines - Supplement - Sentinels of Terra.catz

**BattleScribe version:** 1.14.07

**Platform:** Android

**Dropbox:** Yes

**Description:** The Tactical Squad for both Special weapons and Heavy weapons point costs are all inconsistent with those point values listed in the Space Marine Codex. This appears to be the case with every weapon listed. On a side not the Space Marine battlescribe file it does not list the Tactical Squads with have frag and krack grenades.

**Comment by ghost** [comment]
The points for the heavy/special weapons are correct in the Sentinels of Terra file - no action required there.
