### ISSUE TITLE
Forgeworld Mastodon model missing (at least I cantfind it for the Space Marines)

### ISSUE THREAD

**Issue by rsochia** [BSData/wh40k-7th-edition#3593]
**File/Catalogue:** 2033

**BattleScribe version:** 2.00.15.72

**Platform:** Windows

**Dropbox:** Yes

**Description:**

Cannot find the forgeworld mastodon model in the Space Marines. According to the rules on their website SM can take it as a lord of war choice.
https://www.forgeworld.co.uk/resources/PDF/Datasheets//Mastodon-Rules.pdf

**Comment by DrTobogganMD** [comment]
That'd be because it's probably not there.  I'll get it added.
