### ISSUE TITLE
Skitarii - Dominus Maniple Formation from Start Collecting Missing

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3596]
**File:** Skitarii - Codex.catz

**BattleScribe version:** 2.15.72

**Platform:** Windows

**Dropbox:** No

**Description:** It is missing the detachment Dominus Maniple from the skitarii start collecting box

**Comment by FarseerVeraenthis** [comment]
Please post details of the formation and we'll get it sorted.

**Comment by Thairne** [comment]
![grafik](https://cloud.githubusercontent.com/assets/8590840/24396620/184d2642-13a4-11e7-978f-2b2a54f7a165.png)
