### ISSUE TITLE
Space Marines HQ Command Tanks errors and inconsistencies

### ISSUE THREAD

**Issue by Crowbar90** [BSData/wh40k-7th-edition#3597]
Currenty the entry exists in five different catalogs. The issue is that the entry is treated in different ways, leading to inconsistencies and some errors.

- [x] Blood Angels - Codex (2014).cat
  - [x] Missing wargear entry: Grav-amp
  - [x] Missing wargear entry: Searchlight
  - [x] Missing wargear entry: Smoke Launchers
  - [x] Missing weapon: Grav-cannon
  - [x] Missing weapon: Twin-Linked Lascannon
  - [x] Missing weapon: Twin-Linked Plasma Gun
  - [x] Missing rule: Power of the Machine Spirit
  - [x] Typo: "friendky" instead of "friendly" in Data Augurs rule
  - [x] Typo: missing space between "within" and "12"" in Tactical Authority rule
  - [x] Servo-Skull Hub shown as wargear entry instead of rule
  - [x] Orbital Array shown as wargear entry instead of rule  
- [x] Dark Angels - Codex (2015).cat
  - [x] Unit not available outside of FW (this can be a specific choice, but it would be best if it were consistent with other catalogs)
  - [x] Rhino Primaris links to Razorback profile, Razorback is shown in the report
  - [x] Missing wargear entry: Grav-amp
  - [x] Aquila Aegis Field shown as rule instead of wargear entry
  - [x] Missing rule: Twin-Linked
- [x] Space Marines - Codex (2015).cat
  - [x] Separate entries for transports
  - [x] Rhino Primaris incorrectly shown as transporting 10 models (should be 6)
  - [x] Missing weapon: Twin-Linked Plasma Gun
  - [x] Servo-Skull Hub shown as wargear entry instead of rule
  - [x] Orbital Array shown as wargear entry instead of rule  
- [x] Space Marines - FW - Siege Assault Vanguard.cat
  - [x] Missing rule text: Assault Vehicle
  - [x] Missing rule text: Data Augurs
  - [x] Missing rule text: Orbital
  - [x] Missing rule text: Orbital Array
  - [x] Missing rule text: Power of the Machine Spirit
  - [x] Missing rule text: Servo-skull Hub
  - [x] Missing rule text: Tactical Authority
- [x] Space Wolves - Codex.cat
  - [x] Missing weapon: Twin-Linked Lascannon
  - [x] Missing weapon: Twin-Linked Plasma Gun
  - [x] Servo-Skull Hub shown as wargear entry instead of rule
  - [x] Orbital Array shown as wargear entry instead of rule  

This is all I have noted. Since the selection is available for many factions, maybe it would be a good idea to put it into the GST, this would also solve all inconsistencies between different files.

**Comment by Crowbar90** [comment]
The selection entry also has different names depending on the catalog.

If it's possible, it would be a good idea to note which rules and wargear belong to any of the two vehicles. It would make it much easier to understand and reference correctly during games.

**Comment by DrTobogganMD** [comment]
You can't hide entries based on Catalog chosen. We do not want to put them in the the GST.
