### ISSUE TITLE
Iyanden Troops issue

### ISSUE THREAD

**Issue by JoeOfDoom** [BSData/wh40k-7th-edition#36]
Hi,

Currently if I create a roster using the Iyanden file it doesn't require me to take a spirit seer to take wraith guard as troops. I own the physical book for Iyanden, and it doesn't have anything in it that allows wraithguard/wraithblades to be used as troops without paying the spirit seer tax.

As much as I wish they were automatically troops, they aren't per the physical book. Maybe the digital version is different?

**Comment by Gary-B2** [comment]
Enforced the Rule now also in the Eldar Codex.
