### ISSUE TITLE
Cybernetica datasmith not requiring a protection field

### ISSUE THREAD

**Issue by SSSlippy** [BSData/wh40k-7th-edition#3611]
**File/Catalogue:** Updated 3/30 not sure version #

**BattleScribe version:** 2.00.15

**Platform:** Windows

**Dropbox:** No

**Description:** Cybernetica datasmith not requiring a protection field.  Since it always has a refractor field by default it should not have the option for none and default to refractor field.  Same thing applies to HQ tech-priest dominus(this one has a check for it though)

**Comment by Thairne** [comment]
Done

**Comment by DedusJovus** [comment]
Hi. You made a mistake here. Now the datasmith can't choose other protection fields (conversion, stasis), which he should be able to because he has them as options. Tech-priest dominus works normally, though.

**Comment by Thairne** [comment]
That's a bug in Battlescribe.
The default is set, however BS does not use it. All I can do is require a selection for the Cybernetica Datasmith.
