### ISSUE TITLE
[Anon] Bug report: Adeptus Custodes Dataslate.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3613]
**File:** Adeptus Custodes Dataslate.catz

**BattleScribe version:** 2.15.72

**Platform:** Mac

**Dropbox:** No

**Description:** can we get Forge World options using the data from Inferno/30k (i.e. the Transports and Dreads)?

**Comment by alphalas** [comment]
No - that is 30k - this is 40k. We do not mix (as FW have specified you should not.)
