### ISSUE TITLE
Chaos Space Marines - Burning Brand of Skalanthrax Category Incorrect?

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3620]
**File:** Chaos Space Marines - Codex.catz

**BattleScribe version:** 2.00.32

**Platform:** Android

**Dropbox:** No

**Description:** Burning brand of skalanthrax apears under close combat weapon options on the dark apostle, isnt it a flamer?
Codex: Chaos Space Marines,  page 69

**Comment by cartag** [comment]
This was done for ease of use, it was the easiest way to let it default to Bolt Pistol and Power Maul. 

It's being adjusted to show no default weapons but listing the Chaos Artefacts separately.
