### ISSUE TITLE
Castellans of the Imperium - selection limits with non-Castellans of the Imperium deteachments included

### ISSUE THREAD

**Issue by FusionHS** [BSData/wh40k-7th-edition#3623]
**File/Catalogue:** All Castellans of the Imperium detachments
**BattleScribe version:** 2.00.32

**Platform:** Android

**Dropbox:** No

**Description:** including a separate detachment to Castellans of the Imperium, like for adding Space Marine Formations, results in some kind of conflict on the unit role selection, for example
[List name] (Warhammer 40,000 7th Edition v2036) has (X>0) too many selections of [type:HQ/Elite/Heavy Support](maximum 0)

Seems to be fine with troops though

**Comment by DrTobogganMD** [comment]
Are all of your detachments castelans?

**Comment by GenWilhelm** [comment]
He said he's using a separate Detachment, so I would assume not.

Sororitas had the same issue a couple weeks ago, which was fixed by slightly tweaking the Castellans implementation in that catalogue.

**Comment by FusionHS** [comment]
As GenWilhelm said, I've added an extra detachment to use formations, the moment that detachment is added the issue starts

**Comment by DrTobogganMD** [comment]
Could you attach your roster file that gives the error.  Castellans is not a perfect implementation so it will be easier to pinpoint the issue.

**Comment by FusionHS** [comment]
Sorry, live in a different timezone i guess. I assume it's fixed and you no longer want the file? I'll attach files in future on new issues

**Comment by DrTobogganMD** [comment]
Righto, found the issue.
