### ISSUE TITLE
Chaos Space Marines - Chaos Lord w/ Mark of Nurgle can't find his Blight Grenades

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3634]
**File:** Chaos Space Marines - Codex.catz

**BattleScribe version:** 2.00.15

**Platform:** Mac

**Dropbox:** No

**Description:** Chaos lord is missing blight grenades option. I've selected a Death Guard combined arms detachment. My chaos lord has a Mark of Nurgle but has no option to select blight grenades. (Chaos Sorcerer can select this option though)

**Comment by FarseerVeraenthis** [comment]
What file version are you on??
I just checked using version 2015 and they are listed at the bottom of the options along with the other "Special Issue Wargear" such as Melta Bombs and the Sigil of Corruption.

**Comment by FarseerVeraenthis** [comment]
Bother, I just updated my data to Version 2022 and checked again.
They are not un-hiding properly...

**Comment by cartag** [comment]
It was part of my fixing cult troops unlocking how they should. Got it fixed, uploading shortly.
