### ISSUE TITLE
Infernum Pattern Razorback Missing from Space Marine transport options

### ISSUE THREAD

**Issue by KennyRMoffat** [BSData/wh40k-7th-edition#3638]
**File/Catalogue:**  Codex Space Marines

**BattleScribe version:** 2.00.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** The entry for the infernum pattern Razorback is missing from the options in the space marine codex files. It is there for Blood angels and space wolves but not the regular codex army.

**Comment by alphalas** [comment]
Make sure you have show Forge world checked

**Comment by KennyRMoffat** [comment]
With that on it does appear as a fast attack option but not as a dedicated transport as it does with the Blood angels and space wolves files

**Comment by DrTobogganMD** [comment]
IA2 2e has it listed as a valid Dedicated transport, but not as a FA choice.  I'll swap it up.
