### ISSUE TITLE
Tau army coalition command assisted by amis

### ISSUE THREAD

**Issue by rookiemaisey** [BSData/wh40k-7th-edition#3639]
**File/Catalogue:**

**BattleScribe version:** 2.00.

**Platform:** Windows/iOS/Android/Mac/Linux
iOS 
**Dropbox:** Yes/No
No
**Description:** Detailed issue description.
Hi I'm unable to find the units for the coalition command from the tau army. 
Could I have a datalink or instructions on how to find these units in particular 
Thanks

**Comment by DrTobogganMD** [comment]
That is the name of a box of models, not a formation.  You'd just add a commander with a shield drone, and an ethereal ...

**Comment by rookiemaisey** [comment]
Hi earl, I'm aware it's a box and not a formation but I can't find the battle suit xv85 or the xv86 in the system. Could you help me with this please.

Sent from my iPhone

On 8 Apr 2017, at 10:20 am, Earl Bishop <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #3639<https://github.com/BSData/wh40k/issues/3639>.

**Comment by DrTobogganMD** [comment]
You'd make a CAD for Tau and add a commander, and an ethereal.  If you're looking for data files because you don't have any loaded, then you'd want to check here: http://battlescribedata.appspot.com/#/repos

https://battlescribe.net/?tab=help also has info on loading data.
