### ISSUE TITLE
FW Questoris Knight Magaera rules available

### ISSUE THREAD

**Issue by Viper666-Qc** [BSData/wh40k-7th-edition#364]
The rules for the new Questoris Knight Magaera are available for IK and Imperium factions (as LOW)

http://www.forgeworld.co.uk/Downloads/Product/PDF/M/Magaera.pdf

**Comment by amis92** [comment]
Also, I think it's closed by khambatta now, from 8302fe14228bb2317679b46d56fd1c5d83913505, isn't it?

**Comment by ghost** [comment]
I've added this knight to all the files I usually work on; I dunno about the others.

**Comment by Thairne** [comment]
Added to Dark Angels.

**Comment by senpai514** [comment]
Ill get the rest of the imperium done overnight while at work and upload when I get back home (no internet at work)
