### ISSUE TITLE
Tau army xv85 and xv86 

### ISSUE THREAD

**Issue by rookiemaisey** [BSData/wh40k-7th-edition#3640]
**File/Catalogue:**

**BattleScribe version:** 2.00.

**Platform:** Windows/iOS/Android/Mac/Linux
iOS 
**Dropbox:** Yes/No
No
**Description:** Detailed issue description.
Hi I'm unable to find the units for the battle suits xv85 and xv86 from the tau army. 
Could I have a datalink or instructions on how to find these units in particular 
Thanks

**Comment by alphalas** [comment]
They are options in the crisis commander unit - the FW iridium armor one is no more, but the marker suit and SMS suit are still viable.

**Comment by alphalas** [comment]
![img_0765](https://cloud.githubusercontent.com/assets/15703066/24824880/0ec99768-1be2-11e7-8059-1d43f24704db.PNG)
![img_0763](https://cloud.githubusercontent.com/assets/15703066/24824873/d7202b1a-1be1-11e7-8de3-21b14a19e8d5.PNG)
![img_0764](https://cloud.githubusercontent.com/assets/15703066/24824872/d71f510e-1be1-11e7-8acd-06ebee2ee4b0.PNG)

**Comment by rookiemaisey** [comment]
Hi Jon, this is the most helpful advice I've gotten so far, thank you, but the suits I'm after is the xv85 and the xv86, which from what I'm reading is different again from the three suits available here. I have all my other units in battlescribe already.

Sent from my iPhone

On 8 Apr 2017, at 10:30 am, Jon Kissinger <notifications@github.com<mailto:notifications@github.com>> wrote:


[img_0763]<https://cloud.githubusercontent.com/assets/15703066/24824873/d7202b1a-1be1-11e7-8de3-21b14a19e8d5.PNG>
[img_0764]<https://cloud.githubusercontent.com/assets/15703066/24824872/d71f510e-1be1-11e7-8acd-06ebee2ee4b0.PNG>

**Comment by alphalas** [comment]
The 86 is the coldstar - you gotta pick that at the very beginning. 
![img_0766](https://cloud.githubusercontent.com/assets/15703066/24828128/920541b2-1c24-11e7-95d9-8da29c6ac0a7.PNG)
![img_0765](https://cloud.githubusercontent.com/assets/15703066/24828129/921aff02-1c24-11e7-8bb9-aeea692bbe64.PNG)

The 85 is a FW suit that doesn't have rules anymore in ia3se - it was replaced by the 8-02.

**Comment by rookiemaisey** [comment]
Thanks Jon. That's exactly what I was after.

Sent from my iPhone

On 8 Apr 2017, at 6:29 pm, Jon Kissinger <notifications@github.com<mailto:notifications@github.com>> wrote:


The 86 is the coldstar - you gotta pick that at the very beginning.
[img_0766]<https://cloud.githubusercontent.com/assets/15703066/24828128/920541b2-1c24-11e7-95d9-8da29c6ac0a7.PNG>
[img_0765]<https://cloud.githubusercontent.com/assets/15703066/24828129/921aff02-1c24-11e7-8bb9-aeea692bbe64.PNG>

The 85 is a FW suit that doesn't have rules anymore in ia3se - it was replaced by the 8-02.
