### ISSUE TITLE
Eldar Craftworlds - Error when selecting 2 x Shuriken Cannons on Vyper

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3653]
**File:** Eldar Craftworlds - Codex (2015).catz

**BattleScribe version:** 2.00.13

**Platform:** Linux

**Dropbox:** No

**Description:** The Vyper Fast Attack unit in Eldar Craftworlds throws an error message when changing the secondary weapon to a cannon without also changing the turret weapon, it says "too many selections of shuriken cannon (maximum 1)".  having 2 cannons on a vyper is perfectly valid.

**Comment by FarseerVeraenthis** [comment]
What file version are you using?
Using file v2021 on Android, I just opened a brand new CAD, loaded a Vyper with 2 x cannons and I don't have an error...
The same thing when adding a Craftworld Warhost.
I'll check on Windows tonight, but I suggest you update your data :smile:

**Comment by GenWilhelm** [comment]
Works in Craftworlds, but throws an error in Ynnari (the Falcon had the same issue in Ynnari a little while ago). Perhaps Anon is using the Ynnari catalogue instead of Craftworlds?

**Comment by FarseerVeraenthis** [comment]
oh yes, I had forgotten about the Ynnari...
@GenWilhelm if you've got access to a data editor you can have a poke, otherwise I'll have a look this evening when I get in from work :+1:
