### ISSUE TITLE
Blood Angels Assault Squads

### ISSUE THREAD

**Issue by hateWRAITH** [BSData/wh40k-7th-edition#3656]
Hi, there is  a mistake with the points cost and options for this unit (Blood Angels Assault Squad), base cost per Marine in the Blood Angels Codex is actually 17pts (Instead of 14pts), and may exchange between Jump Packs, Rhino & Drop Pod for free.

This seemed to be the only way to contact any of you guys who do a fantastic job creating the content.

Thanks, & Thankyou in advance.

**Comment by alphalas** [comment]
Actually, you're looking at an old version. In the red thirst edition of the blood angels codex, they changed it to remove the jump pack and cost from the base Marine and remove the discounts on transports

**Comment by alphalas** [comment]
![img_0412](https://cloud.githubusercontent.com/assets/15703066/24909222/06a0e49a-1e91-11e7-921b-cdbd2d1e7a6b.PNG)

**Comment by hateWRAITH** [comment]
Ah, I am extremely sorry, however, I cannot seem to be able to take an Eviscerator for every 5 models in the unit as described by your above screenshot.
