### ISSUE TITLE
Blood Angels Assault Squad

### ISSUE THREAD

**Issue by hateWRAITH** [BSData/wh40k-7th-edition#3657]
The option for 1 Eviscerator for every 5 models is missing.

![06a0e49a-1e91-11e7-921b-cdbd2d1e7a6b](https://cloud.githubusercontent.com/assets/27284010/24909668/2ba33a1e-1f08-11e7-97f0-556bd7ede75f.PNG)

Thanks.

**Comment by alphalas** [comment]
#3633 it's been resolved, just not released yet.

**Comment by hateWRAITH** [comment]
Thankyou.
