### ISSUE TITLE
Interrogator Chaplain can no longer take a storm shield

### ISSUE THREAD

**Issue by amagura** [BSData/wh40k-7th-edition#3660]
**File/Catalogue:** Dark Angels: Codex (2015) v2015

**BattleScribe version:** 2.00.32

**Platform:** Android

**Dropbox:** No

**Description:** the Interrogator Chaplain should be able to take a storm shield, but for whatever reason, is no longer able to: I checked the latest Rules Errata on GW and none of the FAQs specify that the Interrogator Chaplain may not take a storm shield; could you please fix this?

**Comment by FarseerVeraenthis** [comment]
Only an interrogator chaplain in Terminator Armour has the option to take a storm shield, but yes, it is missing from battlescribe at present

**Comment by amagura** [comment]
@FarseerVeraenthis I'd imagine that would be a given, but yes: terminator armor required.

**Comment by alphalas** [comment]
@amagura you'd be surprised

**Comment by alphalas** [comment]
@amagura I just double-checked - a terminator may replace his power weapon with a storm shield. The Interrogator-chaplain does not have a power weapon to replace with a storm shield.

**Comment by amagura** [comment]
@alphalas I was under the impression that once in Terminator armor, the Interrogator Chaplain could take any items in the Terminator gear and special gear lists, which includes (I believe) the storm shield.

**Comment by alphalas** [comment]
![img_0777](https://cloud.githubusercontent.com/assets/15703066/24964279/d92c16f4-1f6e-11e7-9dfa-a1784b3f5b16.PNG)
Clearly states which weapon they must replace

**Comment by amagura** [comment]
@alphalas what constitutes a power weapon?

**Comment by Crowbar90** [comment]
As the rulebook states, a power weapon is a power sword, power axe, power maul or power lance. A crozius is another weapon which happens to have the same profile as a power maul, but it is not a power maul.

**Comment by amagura** [comment]
@Crowbar90  Ah, okay, I thought that the corzius might be concerned one because of the energy field it has, but that makes sense.

**Comment by amagura** [comment]
@alphalas Could the Interrogator Chaplain pay for a powerfist and then for a storm shield?

**Comment by alphalas** [comment]
No because it specifically says power weapon - power fist =/= power weapon

**Comment by amagura** [comment]
@alphalas how do base terminators with power fists take storm shields then?

**Comment by amagura** [comment]
@alphalas at any rate, it seems odd that a power fist, that has the word "power" in its name does not count as a power weapon when it most certainly is, at least in the fluff.

**Comment by alphalas** [comment]
![img_0793](https://cloud.githubusercontent.com/assets/15703066/25074184/887098d6-22c3-11e7-908a-d29507542e5c.PNG)
That's how vanilla terminators do it

**Comment by alphalas** [comment]
And that difference comes from GW adding support for power axes and power mauls having unique profiles- before then it was power sword or power fist, now we have this.
![img_0794](https://cloud.githubusercontent.com/assets/15703066/25074213/23a78b3e-22c4-11e7-8ac2-ebfd9a276909.PNG)
Which still very clearly marks PW as completely separate from PF.
