### ISSUE TITLE
Tech-Priest Dominus requiring special issue wargear

### ISSUE THREAD

**Issue by SSSlippy** [BSData/wh40k-7th-edition#3663]
**File/Catalogue:** Cult Mechanicus v2018

**BattleScribe version:** 2.00.15

**Platform:** Windows

**Dropbox:** No

**Description:** Is requiring special issue wargear as part of list validation.  Special issue wargear is optional.

**Comment by Thairne** [comment]
The special issue wargear is the protection field. It has a default, which due to a BS bug, is not being selected.
