### ISSUE TITLE
Dark Angels - Several Options Missing

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3665]
**File:** Dark Angels - Codex (2015).catz

**BattleScribe version:** 2.00.32

**Platform:** Android

**Dropbox:** No

**Description:** There are several errors in the dark angels character options. Company masters are unable to take bikes, interrogator chaplains are unable to take bikes and their right hands have had all option stripped. The only remaining options are none and crozius, for the terminator armor option.

**Comment by Thairne** [comment]
Company masters cannot take bikes. That one is reserved to Sammael.

Int Chaps in TDA can "exchange their power weapon" of which they have none. A Crozius is not a listed power weapon.
