### ISSUE TITLE
Adding the Mortis Dreadnought

### ISSUE THREAD

**Issue by amagura** [BSData/wh40k-7th-edition#3670]
**File/Catalogue:** Dark Angels: Codex (2015) v2015

**BattleScribe version:** 2.00.33

**Platform:** Android

**Dropbox:** No

**Description:** Is there any chance y'all could add the Mortis Dreadnought from the Imperial Armoury Volume 2 book?

**Comment by FarseerVeraenthis** [comment]
The contemptor pattern mortis dreadnought I'd already available, you need to open the forgeworld option and select "show all" - it is then available under the elites section :+1:

**Comment by alphalas** [comment]
I think he was referring to the boxdread mortis @farseerveraenthis

**Comment by Thairne** [comment]
what the heck is a boxdread mortis?
The normal one? That is in there too. Same condition.
