### ISSUE TITLE
[Anon] Bug report: Sisters of Silence Dataslate.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3671]
**File:** Sisters of Silence Dataslate.catz

**BattleScribe version:** 2.00.19

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** The wicthseekers do not pay an additional 2 points for the flamers. The points are included in the higher unit cost

**Comment by cartag** [comment]
Duplicate of #3667
