### ISSUE TITLE
Issue with Skitarii Codex

### ISSUE THREAD

**Issue by ThorOfAsgard** [BSData/wh40k-7th-edition#3673]
**File/Catalogue:** 

**BattleScribe version:** 2.00.

**Platform:**Android

**Description:** Arcana Mechanicum from Belisarius Cawl not free with War Convocation formation.

**Comment by Thairne** [comment]
I've thought about it for a bit.
Technically, it IS possible to implement it. BUT it would neither be a clean implementation nor work in every case, so I'd rather not.
Problem is that BS does not yet support the structure and modifications Fall of Cadia brought... we can only jump through so many loops to make it work.

The Arcana Mechanicum are available for so many armies that we decided to put them into the main game data file. Now every army can access them without implementing them itself. However I cannot reliably modify points cost based on detachment if the info is not there in the first place - that info comes from another, "lower on the ladder" place.
So unfortunately, there is not MUCH I can do it - you'll have to compensate for that for now.

**Comment by ThorOfAsgard** [comment]
Thanks for the response, I'm glad it wasn't just me. 👍
