### ISSUE TITLE
Adepta Sororitas - special weapon options don't replace basic sisters

### ISSUE THREAD

**Issue by thekaioshinde** [BSData/wh40k-7th-edition#3674]
**File/Catalogue:** Adepta Sororitas.catz

**BattleScribe version:** 2.00.16

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** No

**Description:** From the codex and any army list I've seen it's my understanding that a normal Sisters squad starts with 4 basic sisters and 1 superior and you can replace the weapon loudout of one of them with a special or heavy weapon and of one more with a special weapon.

In the current implementation I apparently can only add new sisters with special or heavy weapons. The 4 basic ones the squad starts with can't be edited or removed. It should be possible to make 5 model squads with special weapons.

Also, for the Castellans of the Imperium detachment the rule that the minimum 2 HQ choices have to be from two different army lists doesn't seem to be enforced. I can just add 2 Sororitas HQs and the list gets marked as valid.

**Comment by francoisbeaulieu** [comment]
For the battle sister squad, I'm not having the issues you are describing with the latest datafiles and BattleScribe for iOS. Once I add the special sisters, I can remove three of the normal ones and the roster still validates. Did you try updating?

For the Castellans, the rule says the detachment as a whole must contain units from at least two factions. It says nothing about the HQs needing to be from different factions. The former is indeed not implemented. That would probably be a complex one to implement in BattleScribe.

**Comment by thekaioshinde** [comment]
Ah, I found the button for removing a sister. I didn't expect it to be in a different area of the UI than the rest of the unit options. I'm new to Battlescribe.

And right, it was generally units from 2 factions and not HQs, I'm just always using HQs to fulfill that rule since it's the easiest and often most useful way, my bad. It would be cool if it could be implemented, but it's not a hard rule to remember at least.

Thanks for clearing those up, closing the issue.

**Comment by francoisbeaulieu** [comment]
My pleasure; we've all been there.
