### ISSUE TITLE
[Anon] Bug report: Necrons - FW - Dark Harvest.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3676]
**File:** Necrons - FW - Dark Harvest.catz

**BattleScribe version:** 2.00.10

**Platform:** Mac

**Dropbox:** No

**Description:** Any update for 7th coming for this file? I hope so!

**Comment by DrTobogganMD** [comment]
You'd have to ask FW about that. As much as people think so, we don't control the publications.
