### ISSUE TITLE
Enhancements:  codex INQ - Henchman warband

### ISSUE THREAD

**Issue by Viper666-Qc** [BSData/wh40k-7th-edition#368]
In the Inquisitorial Henchman Warband unit, Could it be possible to regroup multiple models choice into one entry (as seen in the AS Codex conclave) because it looks very unappealing since each unit model wargear and rules are displayed (only the acolytes can be customized after all)

**Comment by Kangodo** [comment]
Don't forget the Ministorum Priest and Servitors with Heavy Weapons!
But it's a good idea and I changed it.
I just had to click on collective, which basically means "each model must have this entry".
