### ISSUE TITLE
Chaos Space Marines - Chaos Sorcerer missing Disc of Tzeentch Option

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3684]
**File:** Chaos Space Marines - Codex.catz

**BattleScribe version:** 2.00.33

**Platform:** Android

**Dropbox:** Yes

**Description:** Chaos sorcerer no longer has the disc of tzeench option under mounts/jump pack/bikes which should be there for 30 points

**Comment by DrTobogganMD** [comment]
Conditional to hide/show the Disk is linked to the wrong UID, Cartag can fix that in a jiffy :)
