### ISSUE TITLE
Deathwatch - Strategium Command Team Transport Option Missing

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3688]
**File:** Deathwatch - Codex.catz

**BattleScribe version:** 2.00.16

**Platform:** Mac

**Dropbox:** No

**Description:** Deathwatch Strategium Command Team has no dedicated transport option.

(should have all available from veteran squad, like other DW kill team formations)

**Comment by FarseerVeraenthis** [comment]
The transport options are available within the kill team options.
