### ISSUE TITLE
Chaos Space Marines - Impossible to Implement modifier missing

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3692]
**File:** Chaos Space Marines - Codex.catz

**BattleScribe version:** 2.00.33

**Platform:** Android

**Dropbox:** Yes

**Description:** Sigil of corruption modifier does not get applied when calculating invulnerable saves

**Comment by cartag** [comment]
It only does currently in certain circumstances. There are too many permutations of armour and artefacts to have them all programmed in. Trust me, I've tried. If I can find a way that doesn't allow the file to a crawl, I'll implement it.
