### ISSUE TITLE
Chaos Space Marines - Impossible to Implement modifier missing

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3693]
**File:** Chaos Space Marines - Codex.catz

**BattleScribe version:** 2.00.33

**Platform:** Android

**Dropbox:** Yes

**Description:** Mark of tzeentch invulnerable modifier is not being applied when no save already exists (should create a 6++ save but doesn't) appears to modify if invulnerable save is already there however.

**Comment by cartag** [comment]
It only does currently in certain circumstances. There are too many permutations of armour and artefacts to have them all programmed in. Trust me, I've tried. If I can find a way that doesn't allow the file to a crawl, I'll implement it.
