### ISSUE TITLE
Bug report strange message box

### ISSUE THREAD

**Issue by IronWulfen88** [BSData/wh40k-7th-edition#3697]
**File/Catalogue:** 

**BattleScribe version:** 2.00.32

**Platform:** Android

**Dropbox:** Yes

**Description:** Detailed issue description.this box keeps appearing when I open any of my lists no matter which faction
![screenshot_20170423-200746](https://cloud.githubusercontent.com/assets/22039355/25318769/2e5fed42-2863-11e7-959b-a1b0228f0c22.png)

**Comment by DrTobogganMD** [comment]
When was the last time you updated data? Did you purge/reload source files?

**Comment by IronWulfen88** [comment]
Happened four days ago after my latest data update. I'll try purging then re-download the data
