### ISSUE TITLE
Wraithseer D-Cannon cost.

### ISSUE THREAD

**Issue by Nick-Kinsella** [BSData/wh40k-7th-edition#3699]
**File/Catalogue:** Eldar Craftworlds: Codex (2015) v2021

**BattleScribe version:** v2.00.33

**Platform:** Android

**Description:** 
In Imperial Armour Volume Eleven - The Doom of Mymeara p185 lists the Wraithseer's D-Cannon as costing 40 points. The current datafile lists the D-Cannon cost as 60 points. Which is correct?

Apologies in advance if there's been an FAQ I'm not aware of. Thanks for your time.

**Comment by GenWilhelm** [comment]
Are you looking at the most recent edition? Second edition has the Wraithseer listed on page 213.

**Comment by Nick-Kinsella** [comment]
Oh dear. That may be where I'm going wrong. Apologies.
