### ISSUE TITLE
[Anon] Bug report: Chaos Space Marines - Codex (2015).catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3701]
**File:** Chaos Space Marines - Codex (2015).catz

**BattleScribe version:** 2.00.33

**Platform:** Android

**Dropbox:** No

**Description:** The marks of chaos (nurgle, khorne, slaanesh, and tzeentch) are not showing up for any of the available units(tested on the chaos Lord, sorcerer, Marines, raptors, and terminators). This is within the black crusade detachment. Unsure if this user error or if there is another component that I am missing, but many other options will appear properly.

**Comment by GenWilhelm** [comment]
Select "Force Options" under Uncategorised.
