### ISSUE TITLE
8th edition "early" suggestion: wound counter for every multi-wound unit

### ISSUE THREAD

**Issue by Viper666-Qc** [BSData/wh40k-7th-edition#3703]
Ok I maybe a bit early on this but think with many 10+ wounds unit profiles coming in 8th, it would be a great thing for each unit to have a Wound counter bar next to their profile so we could keep track of their wounds easily (without the need to keep a ton of wound dice or tokens on the table) and check their effects.

**Comment by Thairne** [comment]
Wrong target, dude ;)
We maintain the data.
What you want is a new feature in BS - these need to be suggested [here](https://battlescribe.uservoice.com/forums/55066-general) so Jon can see them, plan them and implement them as he sees fit.

**Comment by amis92** [comment]
To be exact, that's the first hit when you search for "wound" https://battlescribe.uservoice.com/forums/55066-general?query=wound

It's **declined** so no hopes for that, I think :<
