### ISSUE TITLE
Data has disappeared

### ISSUE THREAD

**Issue by giantnerd14** [BSData/wh40k-7th-edition#3716]
**File/Catalogue:** 

**BattleScribe version:** 2.00.17.74

**Platform:** Windows

**Dropbox:** Yes

**Description:** This repository has vanished from the appspot website and no longer uploads to Battlescribe.

**Comment by GenWilhelm** [comment]
It does that occasionally when the repo gets a lot of traffic, looks like it's back up now though. We don't deal with the website directly, however - it has a separate repo over at [BSData/bsdata](https://github.com/BSData/bsdata).
