### ISSUE TITLE
[Anon] Bug report: Tyrant's Legion - FW - Defenders of Badab.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3718]
**File:** Tyrant's Legion - FW - Defenders of Badab.catz

**BattleScribe version:** 2.00.23

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Using the Tyrant's Legion in a combined arms detachment gives an extreme exams of error messages that don't make sense. This includes a requirement for a Thunderhawk Gunship and Mælstorm Fleet units.

**Comment by FarseerVeraenthis** [comment]
Confirmed. This CAT is not supported at present...
