### ISSUE TITLE
AHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH! Guardsman Marbo

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3719]
**File:** Astra Militarum - Codex.catz

**BattleScribe version:** 2.00.17

**Platform:** Windows

**Dropbox:** No

**Description:** Update the IG file to include marbo in the elite slot
ahhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh

**Comment by FarseerVeraenthis** [comment]
No.

**Comment by alphalas** [comment]
Don't listen to him - it'll go up eventually
