### ISSUE TITLE
8th edition repo switch

### ISSUE THREAD

**Issue by amis92** [BSData/wh40k-7th-edition#3721]
## [Countdown to freeze (0600 UTC)](https://www.timeanddate.com/countdown/retirement?iso=20170616T08&p0=262&msg=Freezing+wh40k+repo&font=slab#)

added note by @alphalas:
### if you want to help write/validate/use new catalogues, head to #3737 and join us at https://gitter.im/BSData/wh40k to discuss

---

**The following approach was chosen** (see full description below). The steps will be as follows:
1. A day before launch I'll let you all know - at that point development will be freezed, repo will be locked from commits.
1. I'll clean things up (i.e. reset revisions to 0, fix naming, fields like author URL etc to point to GitHub).
1. This (old) repo will be renamed to `wh40k-7ed`.
1. I will create the new repository for 8th ed called `wh40k` - same as current (the name will now not collide) and give write access only to myself.
1. Then I shall move the cleaned up 8th prep branch content (to the new repo).
1. At midnight June 17th I shall turn the switch (create an initial release for 8th ed) so that our dear users have first-day access to new edition* *(actually I'll do that a good few hours earlier to give AppSpot time to update, check if all is well and still have time to fix things if they do not work as expected - so these activities will commence just after I finish up cleaning; so in reality the files will probably be available publicly Friday evening)*

*\* subject to prior availability of leaked point costs* ;)

---

Dear maintainers @BSData/data-authors-gw

As you must know, the 8th edition of 40k is upon us in little more than 2 weeks. The changes already announced are so drastic that many of you have already suggested to start from scratch - and that is what we'll do. Actually, some works have already started on [40k8prep](https://github.com/BSData/wh40k-7th-edition/tree/40k8eprep) branch.

There have been discussions as to **how this start-over should be processed**. Two concepts have shaped:
1. clone the current state to a repo named `wh40k-7th` or similar, and continue work on 8th here.
2. rename this one to `wh40k-7th` and then create a new repo called `wh40k`  (same as this one).

Both have their advantages and disadvantages. The main concern however is that **the end-users should have a natural upgrade experience** - meaning that they should receive new files after clicking/tapping "update data" and not have to enter new repo urls.

The way BS and AppSpot webapp handle end-user data acquisition, that goal is achieved using both approaches. The second one has more compelling advantages though.
* One example is that current clean clone of this repo is a massive 224MB (166MB compressed download). Continuing work here will have that bloat - or if we hard-reset repo to initial state, all issue mentions and disussions become useless - and these won't be transferred on clone. The second approach leaves these things in place, albeit under different URL, and makes us have clean issue account and clean history and a whole lot less to worry about. 
* From admin perspective it also allows me to easily re-arrange contribution/membership and only make the most (or should I say *actually*) active core a part of new organization team with write access to new repo, and add the less active ones as outside collaborators.

**The second approach was therefore chosen.**

---

A note: As a result of this switch, the users that already have 7th ed data downloaded will not have it removed. Those who update from the same appspot link will receive 8th ed data side by side as another game system. Those who have not had any data will only get 8th ed after switch.

**Comment by USSX-Hares** [comment]
@amis92, do you need any help with developing 8th ed. armies? Have some battlescribe experience, could help a lot.
Upd: indices and core rules have leaked today in a good resolution

**Comment by alphalas** [comment]
Join us on gitter

**Comment by USSX-Hares** [comment]
@alphalas Battlescribe/Battlescribe?

**Comment by alphalas** [comment]
https://gitter.im/BSData/wh40k

**Comment by MrRta1910** [comment]
I'm here if any help needed

**Comment by axisofentropy** [comment]
I strongly agree with the second approach including a new `Initial Commit`.  If you want, you can "replay" all the commits just to the `40k8eprep` branch, or just to the new files. That would preserve that history and authorship information. If that sounds valuable, I can help with the `git` wrangling.

Or just copy the latest version of the files into the Initial Commit. That's fine too.

**Comment by amis92** [comment]
@axisofentropy I've thought about that "authorship" thing, it may indeed be nice to have that information. However commit history is linked to this repo (i.e. commit messages contain issue numbers which won't align with new repo), so I think **we should just invite file authors to commit their files** into the new repo when the time comes. Git history will be available (at least for some time) in this repository (albeit under different name).

**Comment by axisofentropy** [comment]
On 06/12/2017 10:10 AM, Amadeusz Sadowski wrote:
>  I think we
> should just invite file authors to commit their files into the new repo
> when the time comes.

I like this idea!

**Comment by ghost** [comment]
Interested in helping with SM (BT specifically) and Orks cats

**Comment by amis92** [comment]
@GitArdnutz please follow the bold tip in this issue's header.

**Comment by amis92** [comment]
Done. New repo: https://github.com/BSData/wh40k
