### ISSUE TITLE
[V8] Incorrect values and missing information in Xenos Index - T'au Empire

### ISSUE THREAD

**Issue by Alvirulan** [BSData/wh40k-7th-edition#3729]
**File/Catalogue:**  Xenos Index - T'au Empire v1

**BattleScribe version:** 2.01.00.83.ALPHA

**Platform:** Windows

**Dropbox:** No

**Description:** 
By opening the T'au Empire catalogue with the Data Editor, I noticed a few things:
- In "Shared Selection Entries", XV104 Riptide Battlesuit model points are incorrect : it should be 209pts instead of 204pts
- In "Shared Selection Entries/Pathfinder Team/Pathfinders", the Pathfinder, Pathfinder Shas'ui and Pathfinder w/ Special Weapon entries do not have an Info link (called Pathfinder for example). The related Shared Profiles is therefore missing for Pathfinder in order to provide their stats lines.
- In "Shared Selection Entries/Kroot Carnivores/Kroot", the entry is linked to the wrong weapon. It should be "Kroot rifle" instead of "Kroot gun".
- In "Shared Profiles", Stealth Shas'ui is missing his "Ld" value. Should be 7.
- In "Shared Profiles", Ethereal is missing his "Ld" value. Should be 9.
- In "Shared Selection Entries/Pathfinder Team/Pathfinders", the Pathfinder w/ Special Weapon entry has no link to Pathfinder Special Weapons "Shared Selection Entry Group" and is also missing his model points.

**Comment by GenWilhelm** [comment]
@bitjump

**Comment by ghost** [comment]
Waiting to be granted push access by @amis92. Had most of these fixed locally for a little while - good spot on the missing Ld and Kroot rifle, though.

**Comment by Alvirulan** [comment]
@Bitjump Sorry for bothering with stuff you already worked on ;) I updated my ticket with other things I noticed. Let me know if it's worth it.

**Comment by ghost** [comment]
@Alvirulan No problem at all. Got it all fixed, will push as soon as possible.
