### ISSUE TITLE
Bug Report: Codes Inquisition

### ISSUE THREAD

**Issue by Thurrstymc** [BSData/wh40k-7th-edition#3730]
**File/Catalogue:** 

**BattleScribe version:** 2.00.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** "Allied Detachment must have 1 more selection from troops, minimum 1." There is no option to select any troops.

**Comment by DrTobogganMD** [comment]
Perhaps you should read the codex before making lists. Hint: There are no troops in the inquisition.

**Comment by Thurrstymc** [comment]
Ya I know that all ready. Just wondering if there was a way to bypass the error that shows up.

**Comment by alphalas** [comment]
Don't use an illegal detachment for Inq?

**Comment by Thurrstymc** [comment]
Ah. Just found it. It's a "special form of allied detachment" called an Inqusitorial Detachment. Thanks anyways tho. Cheers

**Comment by alphalas** [comment]
Mmmmhm.
