### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by zkillz** [BSData/wh40k-7th-edition#3732]
**File/Catalogue:**  any 8th ed

**BattleScribe version:** 2.00.

**Platform:** Windows/Android/Linux

**Dropbox:** Yes

**Description:** got a hold of the books last night eager to assist in anyway with getting the data files updated. I've been a database developer for a couple years but haven't tried doing any datascribe editing yet so might need a bit of help getting up and running.

**Comment by amis92** [comment]
Hello, invitation is here: https://github.com/BSData/wh40k/invitations
