### ISSUE TITLE
[V8] Tau Empire missing entries

### ISSUE THREAD

**Issue by Alvirulan** [BSData/wh40k-7th-edition#3734]
**File/Catalogue:** Tau Empire

**BattleScribe version:** 2.01.00.83 ALPHA

**Platform:** Windows

**Dropbox:** No

**Description:** 
- Strike Team and Breacher Team are missing the Bounding Knife Ritual rule.
- TX4 Piranha is missing its stats values line

**Comment by ghost** [comment]
Fixed by eeeb75f.
