### ISSUE TITLE
Using 8th data branch?

### ISSUE THREAD

**Issue by darkestvisions** [BSData/wh40k-7th-edition#3736]
Less of an issue and more of a question (sorry - didn't know where to ask!)

Is it possible to use the in-progress 8th data files in Battlescribe? Would be keen to start using/testing these.

**Comment by FarseerVeraenthis** [comment]
Yes it is possible to use them, but they should be considered alpha status since we're still confirming the exact setup of the files... 
As such, if you build a list one day, and we make a change, you may have to completely rebuild it the next day.

**Comment by alphalas** [comment]
Yeah you can - the smaller imperial cats are done, so you could use those (sos, custodes, assassins); the rest are all still in progress. All you need to do is download a zip of the branch, and then import all the files into BattleScribe
