### ISSUE TITLE
Tyranid cat changes

### ISSUE THREAD

**Issue by Entropy86** [BSData/wh40k-7th-edition#3738]
**Tyranids:** 

**BattleScribe version:** 2.01.

**Platform:** Windows

**Dropbox:** No

**Description:** 
@GenWilhelm 
Hormagants abilities are missing
tervigon stinger salvo price not included
genestealer price wrong
gargoyle abilities missing
spore mines stats missing
biovore stats, instinctive behaviour missing

That's what I found from a quick once over. Nice work on getting it done so fast.

**Comment by LumberingTroll** [comment]
Here is what I found as well, merged from the issue I created. 

 **Homagaunts** - No Characteristic profiles, Missing Instinctive Behaviour, Bounding Leap, and Hungering Swarm
**Termagaunts** - No Characteristic profiles
**Gargoyles** - No Characteristic profiles Missing Instinctive Behaviour, Hail of Living Ammunition
**Carnifex** - No Characteristic profiles 
**Biovores** - No Characteristic profiles Missing Instinctive Behaviour
**Spore Mines** - No Characteristic profiles
**Lictor**  - No Characteristic profiles
**Hive Guard** - No Characteristic profiles 

There also doesn't seem to be any place that tracks keywords.

**Comment by GenWilhelm** [comment]
Thanks for all of those, guys!
If I missed any, or if you find any more, just open up a new issue and tag me.
