### ISSUE TITLE
Tyranid Profiles

### ISSUE THREAD

**Issue by LumberingTroll** [BSData/wh40k-7th-edition#3739]
**File/Catalogue:** 
wh40k 8th

**BattleScribe version:** 2.01.

**Platform:** Windows

**Description:** 
 **Homagaunts** - No Characteristic profiles, Missing Instinctive Behaviour, Bounding Leap, and Hungering Swarm
**Termagaunts** - No Characteristic profiles
**Gargoyles** - No Characteristic profiles Missing Instinctive Behaviour, Hail of Living Ammunition
**Carnifex** - No Characteristic profiles 
**Biovores** - No Characteristic profiles Missing Instinctive Behaviour
**Spore Mines** - No Characteristic profiles
**Lictor**  - No Characteristic profiles
**Hive Guard** - No Characteristic profiles 

There also doesn't seem to be any place that tracks keywords.

**Comment by LumberingTroll** [comment]
Merging with related issue.

**Comment by amis92** [comment]
Copied by OP to #3738
