### ISSUE TITLE
8th Ork stompa wounds

### ISSUE THREAD

**Issue by GrimDeath58** [BSData/wh40k-7th-edition#3741]
**File/Catalogue:** 
40k8th
**BattleScribe version:** 2.00.
2.01
**Platform:** Windows/iOS/Android/Mac/Linux
windows
**Dropbox:** Yes/No
no
**Description:** Detailed issue description.

preview, view roster,  and printout shows 18 wounds, wound track is correct starting at 40

**Comment by tag8833** [comment]
Fixed.
