### ISSUE TITLE
Drukhari errror reporting

### ISSUE THREAD

**Issue by Penallegion** [BSData/wh40k-7th-edition#3742]
**File/Catalogue:** 
Drukhari V5

1. Drazhar doesn't register as character ? Bold 
2. no description Murderous assault
3. no description eternal warrior
4. overlord rule: mispelled Model
5. Haemonculus: insensible to pain missing / 5++
6. Haemonculus: Master of pain : mispelled, and not targeting Prophets of flesh, but Coven Keyword
7. Haemonculus: no Statline
8. Succubus: no statline/ options no statlines
9. ichor injector mispelling: Remaining
10. Kabalites missing the Power from pain ability
11. wracks missing the Power from pain ability and insensible to pain
12. Hekatrix:  missing statline
13. Wyches/hekatrix: missing Darklight grenades
14. Beasmaster: no description on beastmaster/ not possible to equip 2 power sword, maybe just checkbox ? validation error for Beastmaster makes 1 BEAST outside Force organisation
15. Grotesque: no statline nor any abilities Power from pain/insensible to pain 

i will continue reading and submitting, the validation rules looks good so far   :)

**Comment by Toreador13** [comment]
Thanks! I need more eyes. Mine are blurry from knocking the files out. I need to change all abilities from rules to profiles also (as a note to self). I have a few here and there I did that way.

**Comment by Penallegion** [comment]
No problem i will work on it again tomorrow, i am just checking the obvious for starters, will go in depth with points and so on, later :) but it's looking good mate :) keep it up
Yeah the typing without copy paste can be a bitch ;)

**Comment by Toreador13** [comment]
Errors fixed in version 6.
