### ISSUE TITLE
T'au Empire v1 Issue with two HQ Commanders/Crisis Suits and Drones

### ISSUE THREAD

**Issue by T6Ted** [BSData/wh40k-7th-edition#3743]
Warhammer 40,000 8th Edition v4/T'au Empire v1

BattleScribe version: 2.01.

Windows

Dropbox: No

Description: When you have two commanders and or Crisis suits in your list adding a drone to one will add the drone to both commanders.

**Comment by ghost** [comment]
Can you confirm if this happens with all Drone types or just Markerlight Drones?

**Comment by ghost** [comment]
I added a fix that works on my end. Could you test and tell me if you're still seeing the issue?

**Comment by T6Ted** [comment]
Looks to be just marker drones. I will update and test shortly.

**Comment by T6Ted** [comment]
Looks to be fixed.

**Comment by ghost** [comment]
Fixed by 20efc13.
