### ISSUE TITLE
T'au Empire v1 8th Prep - Stormsurge Points Incorrect

### ISSUE THREAD

**Issue by T6Ted** [BSData/wh40k-7th-edition#3744]
**File/Catalogue:** 
40k8th, T'au Empire v1
**BattleScribe version:**
2.01
**Platform:** 
Windows
**Dropbox:** Yes/No
No
**Description:** 
Stormsurge is pointed at 150. Should be 180 base.

**Comment by ghost** [comment]
Fixed by 5c3c4a4
