### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by joeqastus** [BSData/wh40k-7th-edition#3746]
**File/Catalogue:** 
Warhammer40K

GreyKnights or Deathwatch

**BattleScribe version:** 2.00.

**Platform:** Windows/Android/Mac

**Dropbox:** No

**Description:**
I just want to help getting GreyKnights and Deathwatch done.

**Comment by amis92** [comment]
Please join discussion on https://gitter.im/BSData/wh40k (follow it closely, it's very busy and we don't want conflicts) and start your work on a fork then do a pull request. If it's good I'll give you write access. Be communicative!

Cheers
