### ISSUE TITLE
Harlequin File 1st pass

### ISSUE THREAD

**Issue by Toreador13** [BSData/wh40k-7th-edition#3757]
Shuriken cannon misspell - Shurkien on skyweavers
Shadoseer Psyker - misspell
Neuro Disruptor - misspell against in description.
Shield from Harm - misspell against in description

Most everything else looks good. Didn't check points or anything. 

Most of us have moved all abilities from rules in to Profiles > Ability

**Comment by USSX-Hares** [comment]
@Toreador13, should I made them abilities? Sounds not so difficult.

**Comment by USSX-Hares** [comment]
@Toreador13, please, verify.

**Comment by Toreador13** [comment]
I think the standard they are shooting for is all abilities as a profile. A few army wide large rules make more sense as a rule as it becomes a summary.

**Comment by USSX-Hares** [comment]
Ok, I'll change abilities to the profiles, but not today. I'll contact after fix.

**Comment by USSX-Hares** [comment]
@Toreador13, transferred.
