### ISSUE TITLE
Adeptus Mechanicus 

### ISSUE THREAD

**Issue by Toreador13** [BSData/wh40k-7th-edition#3760]
Just a comment, but would Canticles be better served as a rule so it only shows in a summary at the bottom instead in the profile ability field. It's hard to read in the profile field. It can be made more readable by doing HTML code like this for an ordered list. 

Either way it would make it look like this. 
![image](https://user-images.githubusercontent.com/6875311/26846714-3b794b52-4ac0-11e7-9cea-12460b388e3a.png)

```
<ol>
<li> <b>Incantation of the Iron Soul</b> You can re-roll failed Morale tests for affected units.</li>  
<li> <b>Litany of the Electromancer</b> Roll a D6 for each enemy unit that is within 1" of any affected units; on a roll of 6, the unit being rolled for suffers D3 mortal wounds.</li>   
<li> <b>Chant of the Remorseless Fist</b> You can re-roll any failed hit rolls of 1 for affected units in the Fight phase.</li>   
<li> <b>Shroudpsalm</b> Affected units gain the bonus to their armour saving throws as if they were in cover. Units already in cover are unaffected.</li>   
<li> <b>Invocation of Machine Might</b> Affected units have +1 Strength. </li>  
<li> <b>Benediction of the Omnissiah</b> You can re-roll failed hit rolls of 1 for affected units in the shooting phase</li> 
</ol>

**Comment by Toreador13** [comment]
Not sure if Tekton also was working on this file, but I am unable to add him to this enhancement.

**Comment by tekton** [comment]
That's a good idea; if @Thairne doesn't get to it I'll take a crack later.

**Comment by DrTobogganMD** [comment]
I like it and approve.

Though I'd suggest leaving Canticles as an ability too - just note" This unit has Canticles" or something.

**Comment by Toreador13** [comment]
Good idea on keeping a profile. Probably just have it say see the rule. I will do that on the Drukhari for Combat Drugs and Power from Pain.

**Comment by amis92** [comment]
Just as a reminder, it might backfire on us at some point. Using HTML here isn't officially supported and there were plans to support Markdown at some point.

It also doesn't work on export to anything other than HTML:

![image](https://user-images.githubusercontent.com/2671396/26864770-3296d776-4b5a-11e7-89f8-553a5467aeb5.png)

![image](https://user-images.githubusercontent.com/2671396/26864785-4228bc68-4b5a-11e7-908b-8babb46dc622.png)

I don't think it's a good idea.

**Comment by tekton** [comment]
The rule part is the main thing; thanks for the heads up and clarification on the html exporting/formatting

**Comment by Thairne** [comment]
So.. No rule, no html, simply shorten text.

**Comment by amis92** [comment]
Oh, I just pointed out that part about html formatting. Having profile say "see Canticles rule" is fine by me.

**Comment by Toreador13** [comment]
This is quite interesting because I did this with my Drukhari file, and I don't have that issue. It shows up correct in Plain Text 
![image](https://user-images.githubusercontent.com/6875311/26891914-4566918a-4b7c-11e7-8b71-cdbfbd662f76.png)

and BBCode for me. 
![image](https://user-images.githubusercontent.com/6875311/26891950-628d6aae-4b7c-11e7-8878-7f54832ba993.png)

I actually see no problems  in any of the formats. I wonder why it shows in yours?

**Comment by Toreador13** [comment]
I think the rule is ok in the description, you can just do it in plain txt. I don't think anyone means to not actually have the rule, just how to present or format it. Having it in rules is nice because of the summary, but also making it an ability to make it consistent, but having that reference the rule that is also in battlescribe. Is that correct?

**Comment by Thairne** [comment]
So.. Now you do want it to be as it was....?

**Comment by Toreador13** [comment]
If you look at Drukhari, the combat drugs and power from pain are probably a good way to do it. Make an ability profile to just say "See Rule", and then do a rule for those which you can do as a Rule for the army. That way when you view the roster or print it that big bulk of text isn't repeated on every profile, it's just a summary in the rules section. Not sure if I am clear or not, but the Drukhari file will show you what I mean. 

HTML at this point is not supported, and Markup is in the plans, so at some point we could use formatting that would look a lot better, but not now.

**Comment by Jonskichov** [comment]
HTML output is escaped in 2.01.01: https://github.com/BattleScribe/Desktop-Alphas/issues/133#issuecomment-307643637
