### ISSUE TITLE
40K V8 detachments bug

### ISSUE THREAD

**Issue by wismeril** [BSData/wh40k-7th-edition#3763]
**BattleScribe version:** 2.00.

**Description:** 
Impossible to mix Imperium faction units in one detachment

All fortifications need to go in a dedicated catalogue, to be taken only in force org "Fotification network"

**Comment by amis92** [comment]
Imperium factions can be mixed. You just need to add nested force (with the same force type as parent) with the catalogue you want to mix in.

**Comment by wismeril** [comment]
Ok 
I see it

For fortifications, i've that there are in adeptus ministorum now. 
But it still have some sister of battle uncategorized with it

**Comment by amis92** [comment]
If you want, please open a separate bug for fortifications and maybe expand a little on the topic - where are things that shouldn't be there, and where should they be. I'll close that as pertaining to detachments only. Cheers!
