### ISSUE TITLE
Adeptus Mechanicus 8th edition

### ISSUE THREAD

**Issue by GrimDeath58** [BSData/wh40k-7th-edition#3764]
**File/Catalogue:**  
Adeptus Mechanicus 8th edition

**BattleScribe version:** 
v2.01.00.87

**Platform:** 
Windows

**Dropbox:**
No

**Description:**

Onager Dunecrawler
	Twin heavy phosphor blaster, weapon stats are missing from preview and and roster printout.
	Taking the pintle Cognis heavy stubber option with the Neutron laser/Cognis heavy stubber gives a invalidation. It should not.

Kastelan Robot
	Taking the arm Heavy Phosphor blaster option with the top Heavy Phosphor blaster invalidates and states too many max(1). 3 is possible.
	Main armament option(Heavy Phosphor blaster) should be two, and the cost is listed for one.(15x2=30)

Cybernetica Datasmith
	When taking more than one in a detachment, roster is invalid, showing a max=1, I can't find that it is limited to one. Restriction should be removed.

**Comment by tekton** [comment]
Are you sure these are still happening? I wasn't able to replicate any of those after the pull requests and other work done this morning.

**Comment by GrimDeath58** [comment]
Yeah, they are fixed. I must have load the wrong files. Sorry.
