### ISSUE TITLE
Ork Runtherd Typo: 8th ed.

### ISSUE THREAD

**Issue by tag8833** [BSData/wh40k-7th-edition#3768]
The number of models in a Ork Runtherd on the dataslate differs from the number on the points list.  On the dataslate it is 1 model.  On the points list it is 1-3.  

Clearly one of those is a typo.  I determined that the path of least resistance was to accede to the least restrictive rule.  AKA making the unit 1-3 runtherds.  

I don't have a good solution to this problem, but expect it to come up frequently, so I'm creating this issue to facilitate discussion of it.  If anyone has an alternative solution they think would appease people, I'll be glad to implement it.  

Would it work better if I added a rule explaining this typo?

**Comment by amis92** [comment]
Shouldn't it be in #3748 ?

**Comment by tag8833** [comment]
Merged into #3748.

Also add the "Typo" ability to explain the issue.
