### ISSUE TITLE
Orks issues

### ISSUE THREAD

**Issue by ghost** [BSData/wh40k-7th-edition#3769]
**File/Catalogue:** Orks v1

**BattleScribe version:** 2.01.

**Platform:** Windows

**Dropbox:** No

**Description:** Minor errors in Orks 8th Ed v1 file.

Attached txt file is a version of the Orks.cat that fixes all these issues except for adding keywords.
[Orks.cat.txt](https://github.com/BSData/wh40k/files/1057250/Orks.cat.txt)

### Supersonic
- Remove "instead"

### Open-topped
- Typo "sam" should be "same"

### Grabba Klaw (on Battlewagon)
- Name should be "Grabbin' klaw" not "Grabba Klaw"

### Wrecking Ball
- Name should be "Wreckin' ball" not "Wrecking Ball"

### Power Klaw
- Add text to Ability "when attacking with this weapon"

### Kombi-weapon
- Missing "when using both profiles, -1 to hit roll"

### Kustom Mega-Blasta (on Deffkopta)
- Remove "after shots have been resolved"

### Burna bomb
- Missing "each burna bomb can only be used once per battle"

### Boom bomb
- Missing "each boom bomb can only be used once per battle"

### Skorcha Missile
- Should be "Skorcha missiles" not "Skorcha Missile"

### Wazbom Mega-Kannons
- Profile name should be "Wazbom mega-kannon" not "Wazbom Mega-Kannons"
- Main gun options should be "2x" not "2 " to match format of other multiple weapon entries

### Kannon
- Kannon (Shell) type should be "Heavy 1" not "1"

### Bubblechukka
- Typo "Strenght" should be "Strength"

### Warboss
- Attack Squig - should be "can make" not "makes" as using the Attack Squig is optional

### Warboss on Bike
- Should be W7 not W6

### Weirdboy
- Typo on "Waagh! Energy" should be "Waaagh! Energy"
- Number Weirdboy psychic powers to match D3 roll - 1. 'Eadbanger, 2. Warpath, 3. Da Jump
- Da Jump - range should be 6" not 9"

### Big Mek in MA
- Tellyport Blasta and Kustom Force Field should be 'may take either'
- Tellyport Blasta should be 11pts

### Big Mek on Bike
- Should not have access to Grot Oiler
- Should not have Big Mekaniak rule - Big Biker Mekaniak rule is slightly different
- Should have Big Biker Mekaniak rule: "At the end of your Movement phase, if it didn't move more than 5", this model can repair a single friendly [CLAN] VEHICLE (other than models that can FLY) within 1". That model regains D3 wounds lost earlier in the battle. A vehicle can only be repaired once each turn."

### Ghazghkull Thraka
- Missing Prophet of Gork and Mork rule (4+ invul)

### Boss Zagstruk
- BS should be 5+, not 4+
- Missing Drill Boss rule (friendly units of GOFF STORMBOYZ within 6" of Boss Zagstruk automatically pass Morale tests)
- Da Vulcha's Klaws has an extra profile copied and pasted from Da Rippa

### Boss Snikrot
- Terrifying Killer rule - should be "Morale" not "moral"

### Mek
- Should be 22pts base not 55pts

### Mad Dok Grotsnik
- Missing Slugga

### Runtherd
- Should be a 1-model unit (assumed change per the Datasheet description "is a single model", no mechanism for taking additional models and presence of CHARACTER keyword)
- Grot Lash and Squig Hound should be 'may take either'
- Melee weapon should default to grot prod

### Tankbustas
- Bomb Squig should be '2 per 5 models'
- Tankbusta w/ Pistols should be '1 per 5 models (excluding Bomb Squigs) only'

### Nobz
- Missing option to replace Choppa with Power Stabba (M/M/U/-2/1/-) @ 3pts or Killsaw @28pts
- Missing Keepin' Order rule (Roll a D6 for each model that flees from a [CLAN] unit that is within 3" of any friendly [CLAN] unit with this ability. On a 6, that model doesn't flee.)

### Nobz on Bikes
- Missing Keepin' Order rule (Roll a D6 for each model that flees from a [CLAN] unit that is within 3" of any friendly [CLAN] unit with this ability. On a 6, that model doesn't flee.)

### Meganobz
- Missing Keepin' Order rule (Roll a D6 for each model that flees from a [CLAN] unit that is within 3" of any friendly [CLAN] unit with this ability. On a 6, that model doesn't flee.)

### Kommandos
- Kommando should be 9pts not 6pts

### Boyz
- Ork Boy should be Strength 4 not Strength 5

### Deffkoptas
- Unit limit should be 5, not 3 (PL adds up correctly though) - assumed change per the dataslate

### Warbikers
- 10-12 Warbikers should be PL 17 not PL 13

### Wartrakk
- Base equipment should be Twin big shoota @ 14pts, not big shoota @ 6pts
- Missing Outriders rule (During deployment, you can set up a unit of Wartrakks on the army's flanks instead of on the battlefield. At the end of any of your Movement phases, the Wartrakks can race in to encircle the foe - set them up so that each model is touching a battlefield edge and is more than 9" away from any enemy models.)

### Skorcha Buggy
- Unit name should be "Skorchas" not "Skorcha Buggy"
- 2-3 Skorchas should be 10 PL not 4 PL
- 4-5 Skorchas should be 16 PL not 4 PL
- Vehicles should be added as a collective, not individual models
- Missing Outriders rule (During deployment, you can set up a unit of Skorchas on the army's flanks instead of on the battlefield. At the end of any of your Movement phases, the Skorchas can race in to encircle the foe - set them up so that each model is touching a battlefield edge and is more than 9" away from any enemy models.)

### Warbuggies
- Missing Outriders rule (During deployment, you can set up a unit of Warbuggies on the army's flanks instead of on the battlefield. At the end of any of your Movement phases, the Warbuggies can race in to encircle the foe - set them up so that each model is touching a battlefield edge and is more than 9" away from any enemy models.)

### Burna-bommer
- Wound Track 1 - max move should be 50" not 60"
- Wound Track 2 - max move should be 30" not 40"

### Blitza-bommer
- Wound Track 1 - max move should be 50" not 60"
- Wound Track 2 - max move should be 30" not 40"

### Battlewagon
- Grabba Klaw should be 0-1 option only
- 'Ard case should set T to 8 (can do this with a modifier & condition on Battlewagon unit profile)
- 'Ard case should hide Open-topped rule (can do this with a modifier & condition on Open-topped info link)

### Deff Dreads
- Explodes rule should be within 3" not within 6" (different from other Explodes rules)

### Killa Kans
- Killa Kan profile should be Killa Kans 6"/5+/4+/5/5/5/3/6/3+ not Deff Dread profile
- 4-6 Killa Kans should be 19 PL not 16 PL
- Explodes rule typo "suffer" should be "suffers" and "wounds" should be "wound"
- Explodes rule should not refer to embarked models
- Should not have 'Ere We Go! rule

### Morkanaut
- Wound Track 1 char. 3 should be 4 not 6
- Wound Track 2 char. 3 should be 3 not 5
- Wound Track 3 char. 2 should be 5+ not 4+
- Wound Track 3 char. 3 should be 2 not 4

### Gorkanaut
- Wound Track 3 char. 2 should be 5+ not 4+

### Flash Gitz
- Kaptin missing option to take choppa or slugga in addition to normal equipment

### Stompa
- Should be 40 Wounds not 18
- Should be 8 Ld not 7
- Missing option to take up to 2 additional super-rokkits for free

**Comment by tag8833** [comment]
Thanks so much for all the feedback.   A couple items that I intentionally didn't address:

**Kustom Mega-Blasta (on Deffkopta)**
Remove "after shots have been resolved"
_- On the weapon profile list it has that.  hmmm.  Keeping it for right now, because it is a linked entry, and I don't want to make a duplicate.  I'll add it to the list of known bugs._

**Runherd:**
Melee weapon should default to grot prod
_- I don't see that on his dataslate._

**Skorcha Buggy**
Unit name should be "Skorchas" not "Skorcha Buggy"
_-I renamed it so that I could keep track of the difference between Skorcha wargear, and the Skorcha buggy.  It gets real confusing in the data file if I don't keep them separate._

Let me know if you disagree with any of that.

**Comment by ghost** [comment]
KMB - on reflection it doesn't matter as it's a single shot weapon.

Runtherd - don't know what I was thinking there. Clearly the default should be grabba stikk.

Skorcha - fair enough. The main useability issue is probably to use a collective weapon profile for the Skorcha weapon so you can increment the count rather than adding a bunch of separate, identical, non-modifiable models.
