### ISSUE TITLE
Chaos Daemon issues

### ISSUE THREAD

**Issue by hobodabobo** [BSData/wh40k-7th-edition#377]
Since the issue with the deleted data was taken care of, the FW blight drones and the gargantuan daemon lords have gone missing. Also, the point issue with the different marks on the furies was fixed, but the initial point cost was changed from 35 to 30 pts. And from what I can tell in the FAQ, the Exalted Flamer herald choice cannot take any rewards. Thanks for the help fellas!

**Comment by NebSeele** [comment]
I will fix up this issues as soon as I have power again.
