### ISSUE TITLE
T'au Stealth suits incorrect points

### ISSUE THREAD

**Issue by Gue-vesa** [BSData/wh40k-7th-edition#3771]
**File/Catalogue:**  T'au  Empire v1

**BattleScribe version:** 2.01.00

**Platform:** Windows
**Dropbox:** No

**Description:**  The stealth suits are costed as 35 points with a burst cannon this is 5 points too high.

**Comment by JohnPublic** [comment]
I would like to add that there is currently no way to replace a Shas'ui with a Shas'vre without adding a model to the unit, should be able to take 2 Shas'ui and 1 Shas'vre.

**Comment by ghost** [comment]
@JohnPublic You can currently do this - simply add a Shas'vre and remove a Shas'ui from the unit.

**Comment by ghost** [comment]
Fixed by 84df2e3
