### ISSUE TITLE
Drukhari

### ISSUE THREAD

**Issue by Examinus88** [BSData/wh40k-7th-edition#3772]
**File/Catalogue:** drukhari v7
**BattleScribe version:** 2.00.
**Platform:** Windows/
**Dropbox:** Yes/
**Description:** 
Incorrect points for:

- [x] blast pistol: 10 not 15
- [x] sybarite (kabalite warriors) 7 not 18
- [x] hekatrix & wyches 9 not 20
- [x] phantasm grenade launcher 3 not 10

- [x] voidraven missiles not selectable for voidraven bomber (has incorrect shatterfield missiles).

typo:
- [x] heatlance description, ratget >target.

**Comment by Penallegion** [comment]
Hi just found a little more, havent reached points yet but will help you out on that in the weekend :)

- [x] Beatsmaster: Beasts clawed fiends and Khymerae missing point value
- [x] Kabalite Trueborn: maybe make 4 Kabalite trueborn standard, and keep add button?
- [x] Dracon: Powersword not multiple option but checkbox
- [x] Reavers: missing Powerlevel (5), Missing Bladevanes in profile (no stats), Grav Talon/cluster caltrops 
       shouldn’t equip on Champion but on Stock Reaver, 
- [x] Cronos: missing Powerlevel (5), missing insensible to pain, Missin Explode, Missing Spirit Probe
- [x] Talos: Missing Insensible to Pain, 
- [x] Ravager: Missing Statline, missing Explodes, 
- [x] Razorwing jetfighter: make the missile a static weapon choice with the profiles for the 3 different 
       missile types, its not a weapon upgrade but a fire mode.
- [x] Voidraven is just called Void raven, no Bomber ;) Missiles is a weapon option not on voidraven Stock, 
- [x] Wyches/hekatrix: missing Grenades not showing on profile/no description
- [x] Master of pain must target Keyword <COVEN> NOT Prophets of flesh
- [x] Drazhar/Urien doesn't register as character ? Bold

**Comment by Penallegion** [comment]
If i can make a sugestion more, make checkboxes in the List and don't close ticket, that way the submitter can follow the process and you have all your tickets in on place?

Points for whyches should be 9 not 10 nor 20 ???

**Comment by Examinus88** [comment]
correct on wyches. I edited in the original post.

**Comment by Toreador13** [comment]
I am unsure of the meaning of Drazhar/Urien doesn't register as character ? He is marked as a character, could you elaborate?

**Comment by Penallegion** [comment]
Yeah if you go in the armybuilder and choose HQ 
Archon, succubus and Lellith is Bold writing where as Drazhar and Urien is plain

**Comment by amis92** [comment]
That's only a hint that (bolded) items have modifiable choices in them. Drazhar and Urien would then be plain because you cannot customize any of them in any way.

**Comment by Penallegion** [comment]
Hmm might be a platform problem it works fine on phone. 
Think you can just ignore that one. Sorry for wasting your time

**Comment by Penallegion** [comment]
Oh crap what Amid said then

**Comment by Toreador13** [comment]
@amis92 , Now I never knew that before, and it doesn't look like it is showing on my version either....
Not a problem @Penallegion , we both just learned something.

**Comment by Toreador13** [comment]
I made a simple mod to the Trueborn, but will probably keep the logic for them as they are a lot more configurable than a typical unit. Everything else should be fixed, but won't be uploaded until later tonight. Thanks guys!

**Comment by Penallegion** [comment]
Awesome job @Toreador13

**Comment by Examinus88** [comment]
Cool, keep up the good work and I'll keep testing.

**Comment by Examinus88** [comment]
great fixes! Last thing is something i put down wrong. voidraven missiles is a single weapon option with 2 firing profiles.

**Comment by ghost** [comment]
Kabalite Warriors are missing their profile-stats/characteristics (m ws bs s t etc.).

**Comment by Penallegion** [comment]
- [x] Talos: Points are wrong, it's adding the 88 point for Talos with the 126 point for kittet Talos = 214 point.

- [x] Lellith Power from pain is named read the rules, Lelith No text on Combat drugs.

- [x] Voidraven Missiles are still wrong, with the fire modes.

**Comment by Toreador13** [comment]
V9 release is up with fixes.

**Comment by ghost** [comment]
Found one.

- [x] Kabalite Warrior Sybarite: No option for Phantasm Grenade Launcher

**Comment by Penallegion** [comment]
![skaermbillede 2017-06-10 13 46 25](https://user-images.githubusercontent.com/25779557/27002459-4ed7b41a-4de3-11e7-8a63-7879ebdcac2c.png)
Think this is what we are looking for with the voidraven

**Comment by Penallegion** [comment]
![unavngivet](https://user-images.githubusercontent.com/25779557/27002769-e0e44f52-4de9-11e7-97ec-23df67513f6e.png)
- [x] Talos is still stil double count on the points

**Comment by Penallegion** [comment]
![skaermbillede 2017-06-10 14 40 42](https://user-images.githubusercontent.com/25779557/27002816-d215b276-4dea-11e7-8933-896fac571356.png)
Talos should look like this for correct point addition

**Comment by ghost** [comment]
Great work so far!
Heres another thing I found:
Theres no warning when adding too many wracks with special weapons to a wrack unit.

**Comment by Penallegion** [comment]
- [x] Drazhar should be pointed to 132 point, so when Demiklaives is added he is 140 points... his entry is including wargear in index.

- [x] Razorwing jetfighter is 115 points not 130

- [x] Urien rakarth should be priced 107 so when ichor injector is added he is at 112 as per index

- [x] Nightfiend in Mandrake selection is 19 point like the rest of the squad

- [x] Impaler is 5 point not 15 (i am not sure impaler should count towards Lellith point limit as she is including wargear in the Index ????)

**Comment by Toreador13** [comment]
Looks like some of my previous fixes didn't make it through, not sure why. 

Fixed misspelling of disintegrator cannon and all the updates above. Will push it out tonight. Will be changing () back to <> now that HTML is escaped correctly. 

Could someone check the wrack special weapon issue? I could not not get a warning for too many special weapon wracks. Anyone else?

**Comment by FarseerVeraenthis** [comment]
On Version 9 the Wrack issue is present.

**Comment by Toreador13** [comment]
Odd, I get a warning. v!0 uploaded. 
![image](https://user-images.githubusercontent.com/6875311/27061730-e20a6c04-4fab-11e7-8481-86a9969bca42.png)

**Comment by FarseerVeraenthis** [comment]
Sorry, that wasn't great from me, I did get a validation warning, same as your screen shot, should've read the question properly first! I'll try version 10 later :smile:

**Comment by Toreador13** [comment]
Not a problem, I just want to make sure what I am seeing is the same, otherwise I have no way to know how to fix it! Good to know it's not an issue though.

**Comment by ghost** [comment]
The too-many-special-weapon-wracks warning appears for me in v10 now.  :thumbsup:

**Comment by FarseerVeraenthis** [comment]
I think you're there, apart from perhaps setting the minimum for Kabalite Warriors and Wyches one higher so you don't get an error as soon as you add them to the list...
Once all three Aeldari lists are done @USSX-Hares can start working his merging magic...

**Comment by Toreador13** [comment]
Are they going to be merged together? I thought they had it set up so sub forces could be chosen and it all worked as one.

**Comment by FarseerVeraenthis** [comment]
Oh, only to create the Ynnarii CAT, they will stay separate for the individual forces...!

**Comment by FarseerVeraenthis** [comment]
@Toreador13 I made a couple of minor tweaks to your units. Basically, if you set a default option for a SEG, once the mandatory models have been selected BS will fill that unit to the minimum constraint with the default models. This removes the error when adding any unit previously, because, e.g. Wyches will now come with 4 Wyches and a Hekatrix as standard. You can still choose to remove one of them but you don't get an error just by adding the squad now :smile:

**Comment by Toreador13** [comment]
Yeah, I think that is just a preference. I prefer the other way, since in most of those units special weapons are chosen over base units. I typically rather add to than take away. But, that is just preference.
