### ISSUE TITLE
T'au Vespid Stingwing incorrect warning

### ISSUE THREAD

**Issue by Alvirulan** [BSData/wh40k-7th-edition#3774]
Whenever you create a Vespid Stingwing unit of more than 4 members but less than 8, there is a warning stating that "Vespid Stingwings must have X more selections from Vespid Stingwings (minimum 8)" (where X is the number required to reach 8 members).
You should be authorized to have 5,6 or 7 members in the unit.

**Comment by ghost** [comment]
Fixed by 84df2e3
