### ISSUE TITLE
Ad Mech Power Levels incomplete

### ISSUE THREAD

**Issue by tag8833** [BSData/wh40k-7th-edition#3777]
Electropriests (both types), Breachers, Destroyers, and Kastalan Robots are missing base PL.  Looks like most units don't go up in PL as you add models.

**Comment by GrimDeath58** [comment]
Works in mine.

**Comment by tag8833** [comment]
Here is a screen shot.
![admech](https://user-images.githubusercontent.com/17749311/26909500-e11e36ba-4bc6-11e7-973f-2958964040a5.png)

**Comment by GrimDeath58** [comment]
delete the .cat file in the folder, reload the new one. the new one reads v1, wont overwrite the old cause it reads v2

**Comment by tag8833** [comment]
Pretty sure I just did.  I'll redownload.

**Comment by GrimDeath58** [comment]
![untitled](https://user-images.githubusercontent.com/12993251/26909716-95fe7b18-4bd0-11e7-8606-a6ab31a78fc9.jpg)

**Comment by tag8833** [comment]
Blew away my data directory.  Downloaded new data files.   Same problem.   

Here is the inside of the data file where the PL are missing.
![admech](https://user-images.githubusercontent.com/17749311/26909752-792e200e-4bc8-11e7-94fc-8281d42f3ee9.png)

It looks to me like you may not have committed your changes to the wh40k-40k8eprep branch.

**Comment by GrimDeath58** [comment]
i am not the editor. Just proofreading. The version I have works. I don't know why yours does not.

**Comment by tag8833** [comment]
Oh.  As soon as I posted that I realized PL do show on that unit.  IT starts at 0, and is modified by a repeat condition, but your condition doesn't work because it is in "Parent".  You've got to change it to "
![admech](https://user-images.githubusercontent.com/17749311/26909823-f80987f6-4bc8-11e7-99d3-2431af2b896d.png)

That will make them look right in the roster.   Also explains why it looks right to some people and not to others.  

The downside of having 0 on the entry, and then adding them via repeater like this is that it shows 0 on the selection list.

I'm using BS v2.01.00.84

**Comment by tag8833** [comment]
The plot thickens a bit.  I updated to BS 2.01.00.87

Now the PL shows in my roster, though still not in my unit selections, but I noticed that it also is incremented for every instance of that unit in the roster.  Here is a example.   

![admech](https://user-images.githubusercontent.com/17749311/26910281-7ad916d6-4bcb-11e7-89f9-68e4a2dab5d8.png)

**Comment by Thairne** [comment]
I'm aware of that.
Not figured out a solution to that yet.
