### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by McChew** [BSData/wh40k-7th-edition#3779]
**File/Catalogue:** wh40k

**BattleScribe version:** 2.01.

**Platform:** Windows/Android
**Dropbox:** Yes

**Description:** I would like to help update catalogues for 8th edition.

**Comment by amis92** [comment]
Please join discussion on https://gitter.im/BSData/wh40k (follow it closely, it's very busy and we don't want conflicts) and start your work on a fork then do a pull request. If it's good I'll give you write access. Be communicative!
Cheers
