### ISSUE TITLE
Adeptus Ministorum Points cost

### ISSUE THREAD

**Issue by flakpanda** [BSData/wh40k-7th-edition#3781]
Geminae Superia for Celestine only add 50 points, not 50 points per model. Also, Celestine is 100 points. She is listed at 150.

**Comment by ThomasEll** [comment]
Incorrect, if you look at the data sheet for Celestine you have the option of taking either one or two Geminae Superia. Each one costs 50 points.

**Comment by CloverFox** [comment]
unable to re-produce this, works as @ThomasEll states, which version of the datafiles are you running and are you running from a blank state or editing an existing roster? if its the latter try a new roster or remove celestine and re-add her.
