### ISSUE TITLE
8E Space Marines permits invalid weapon combinations

### ISSUE THREAD

**Issue by ninchistudios** [BSData/wh40k-7th-edition#3782]
**File/Catalogue:**  Space Marines v1 commit 6328e1
**BattleScribe version:** 2.01
**Platform:** Mac
**Dropbox:** No
**Description:** 
Add a HQ > Captain. Give it Relic Blade and Storm Shield. Validation says this is correct, but it is not a valid option by the Index. 
The problem seems to come because the validation is a simple count ( == 2) across all weapons, but it possibly needs to be broken down into left hand/right hand options (or weapon 1 / weapon 2 etc).
Similar issue appears on other units incl Terminator and Cataphractii Captains, so it's possibly a widespread issue with how weapon options have been configured across the file.

**Comment by flakpanda** [comment]
Solution found. Will comb through next time I work on catalog.

**Comment by ninchistudios** [comment]
@flakpanda sorry I don't mean to be a pain but this is still broken in commit 38a17e5.

Captain currently permits having a pistol and a combi-weapon. I know you want to make it easier on mobile but the current structure doesn't match the weapons options guidelines here https://github.com/BSData/wh40k/issues/3791

**Comment by flakpanda** [comment]
Duplicate issue in #3797
