### ISSUE TITLE
Tyranids 8th

### ISSUE THREAD

**Issue by Nighttail** [BSData/wh40k-7th-edition#3784]
**File/Catalogue:** Tyranids v1

**BattleScribe version:** 2.01.

**Platform:** Windows 10

**Dropbox:** No

**Description:** Issues I found in the Tyranid file.

**Hive Tyrant:** 2x Monstrous Scything Talons display as 20.5 points instead of 41 points under "Weapons" (actual point value still correct though).
**Broodlord:** Says Leadership 1 instead of 10.
**Tyranid Prime:** Gives an error when selecting two pairs of Scything Talons.
**Tyranid Warriors:** Gives an error when selecting two pairs of Scything Talons.
**Tyranid Shrikes:** Gives an error when selecting two pairs of Scything Talons.

**Comment by Entropy86** [comment]
The hive tyrant is correct, as you have 2 pairs at 20.5 points each to make the required 41pts.
I thought the dual scything talons wasn't allowed but re-reading it you can do it, so yeah that needs changing.
@GenWilhelm
