### ISSUE TITLE
V8 Space marines

### ISSUE THREAD

**Issue by wismeril** [BSData/wh40k-7th-edition#3785]
**File/Catalogue:** Space marines 

**BattleScribe version:** 2.01.

**Platform:** Windows

**Description:**
Lightning claw damage is noted 31 -> 1 
Cost of lightning claws si 9/13 
When you add a 2nd lightning claw, the cost is not comptabilised

**Comment by flakpanda** [comment]
Please be more specific. Like which unit? Which models in that unit?

**Comment by wismeril** [comment]
Sorry, i forgot it.
On capitain and capitain on bike

**Comment by Entropy86** [comment]
Also in assault terminator squads, you can't mix and match hammers and claws, picking one adds it to all the other models.

**Comment by Requiet** [comment]
Rhinos have no options, supposed to be allowed a Hunter Killer and additional stormbolter

**Comment by Requiet** [comment]
Biker Squads - The first unit that appears is a Scout Biker Sergeant. Missing its profile. Should be a regular space marine sergeant.
Unyielding Ancient rule (Venerable Dread) - On a six that wound is -not- lost. Currently says the wound is lost if your roll the 6

**Comment by flakpanda** [comment]
All Fixed
