### ISSUE TITLE
8th Edition CSM Issues

### ISSUE THREAD

**Issue by thejughead** [BSData/wh40k-7th-edition#3789]
**File/Catalogue:** Chaos Space Marines

**BattleScribe version:** 2.00.

**Platform:** iOS/

**Dropbox:** No

**Description:** 

1. Missing Dedicated Transport entry for Rhino.
2. Land Raider does not account for LasCannons point cost.
3. Missing Noxious Blight Bringer entry.

**Comment by cartag** [comment]
1. Rhino as DT is in latest version, uploading soon.
2. Corrected.
3. Noxious Blightbringer is in Death Guard CAT, not CSM file.
