### ISSUE TITLE
V8 SM Landspeeder Missing Assault Cannon

### ISSUE THREAD

**Issue by tuiscon** [BSData/wh40k-7th-edition#3796]
**File/Catalogue:** Space Marines.cat
**BattleScribe version:** 2.01
**Description:** Landspeeder Missing Assault Cannon as weapon choice

**Comment by flakpanda** [comment]
<img width="973" alt="screen shot 2017-06-09 at 2 17 11 am" src="https://user-images.githubusercontent.com/19719565/26965053-cb8c08c4-4cb9-11e7-9bb0-e5d15689553b.png">
It is not missing it as an option.

**Comment by tuiscon** [comment]
My test rooster had  a wrong version apparently.
Sorry for that
