### ISSUE TITLE
Tyranids- Carnifex Monster Scytals

### ISSUE THREAD

**Issue by hatchetboy** [BSData/wh40k-7th-edition#3799]
The Carnifex Monsterous Scything Talons are coming in at 41 points for 2 pairs, which is the cost for a Hive Tyrant.  The Carnifex ones should cost 20 for 2 pairs (and 14 for one pair, which is currently correct)

**Comment by GenWilhelm** [comment]
Fixed in dc1a37647f727bfff9a96d6ec9ca4410cafee494.
