### ISSUE TITLE
8th Ed Harlequins issues

### ISSUE THREAD

**Issue by Mad-Spy** [BSData/wh40k-7th-edition#3803]
Harlequins.cat

BattleScribe version: 2.01.00.87

Platform: Windows

**Dropbox:** Yes/No

Description: Additional issues found over and above those listed in #3783 

- Rising Crescendo is misspelled in Shared Rules.

- Shadowseer - Psyker: missing the word "the" in its description, [It knows "Smite" power and].

- Troupe default weapons do not work. The Troupe is added to the roster with no defaults. The implementation seems a bit clunky with increments of max/min selections for each model. Perhaps it could be done in the style of the Skyweavers where each model is an individual as per the screenshots below?
![image](https://user-images.githubusercontent.com/29306451/26978566-dea2099e-4d23-11e7-8d81-be891c2c7e57.png)
![image](https://user-images.githubusercontent.com/29306451/26978693-5757a790-4d24-11e7-8b02-484038f26da0.png)

- The Troupe has a pts value for some reason, which I think is why there's a decrement of points in the entry. Probably can lose both to tidy this up?

- Is it neater to give the Players a individual PL of 1 and the Troupe a PL of 2 (to get the minimum 7) rather than doing the 5 PL decrement and the repeating increment per model?

- Skyweaver PL increments seem overcomplicated. The below does the same job and doesn't require the odd-looking decrement.
![image](https://user-images.githubusercontent.com/29306451/26979587-3b11165e-4d27-11e7-9ce7-bdff20a8a752.png)

- For consistency with other cats (and the rule book), invulnerable saves should probably not be included in the "Save" field. This applies to all models.

**Comment by USSX-Hares** [comment]
@ilaunchbury next time, please, set up assignee or mention (it's hard to monitor everywhere)
1. Rising Crescendo - Fixed
2. Shadowseer - Psyker - Fixed
3. There is no way Troupe can be done same way as Skyweavers - unit size can be too large, and manually set up all the 12 models (and it looks very terrible while printed). Default wargear fixed.
4. It was done for default wargear price to be included in entry selection tab
5. Same as above + Increments/Decrements are set up for easier size management
6. Same as above
7. I had asked, and was answered: https://gitter.im/BSData/wh40k?at=592eff5300efc2bb3ec2bd2b; If required, they will be removed

**Comment by Mad-Spy** [comment]
Sorry, couldn't work out how to set assignee. Will make sure to add a mention in future. 

1. Thanks
2. Thanks.
3. I don't agree with this. Every other large size unit (Marines, etc.) where models are individually equipped is done the way I suggested, with each model individually listed, so that you (and your opponent in match play) know which specific model has which equipment. That's why you need it printed out that way as well.
4. If you fix 3, then this can go away.
5. On reflection, I think your way is better here.
6. I'm not sure how your way makes for "easier size management", but as the result is the same, I'm not going to argue it.
7. I can't find any other cat where the invulnerable save is listed in the stat line.

**Comment by alphalas** [comment]
I'm with @ilaunchbury on 3 - there are enough permutations that his suggestion has merit

**Comment by USSX-Hares** [comment]
@alphalas @ilaunchbury, ok, I'll remake troupe today or tomorrow.
@alphalas, what with inv saves?

**Comment by alphalas** [comment]
We I personally have just been typing out the ability texts that say invuln, not put in profile

**Comment by USSX-Hares** [comment]
Ok.

**Comment by USSX-Hares** [comment]
Troupe fixed.

**Comment by FarseerVeraenthis** [comment]
These all look good to me, I think this issue can be closed.

**Comment by USSX-Hares** [comment]
@FarseerVeraenthis, don't fix inv saves yet.

**Comment by FarseerVeraenthis** [comment]
Invulnerable saves have been removed from profiles, so this can be closed and Ynnari can begin :smile:
