### ISSUE TITLE
8th Edition CSM Issues

### ISSUE THREAD

**Issue by thejughead** [BSData/wh40k-7th-edition#3805]
**File/Catalogue:Chaos Space Marines.cat 

**BattleScribe version:** 2.01.00

**Platform:** Mac

**Dropbox:** No

**Description:** 

Cultist only shows cost of Champion, 5 pts.

<img width="1440" alt="screen shot 2017-06-09 at 2 34 04 pm" src="https://user-images.githubusercontent.com/9107917/26989800-70b55db0-4d22-11e7-9131-5b544fd070b0.png">

Rhino should default to Combi Bolter.

<img width="1440" alt="screen shot 2017-06-09 at 2 10 44 pm" src="https://user-images.githubusercontent.com/9107917/26990726-b1fcd746-4d25-11e7-9c40-27ca63a3f01a.png">

Terminators taking both claws should be 13 for the pair not 17.

<img width="1440" alt="screen shot 2017-06-09 at 3 19 15 pm" src="https://user-images.githubusercontent.com/9107917/26991115-266e5bee-4d27-11e7-84f1-2358de1a5ec2.png">

**Comment by cartag** [comment]
Fixed
Rhinos have a combi-bolter stock, and can additionally take weapons from the combi-weapons list. What you included is the option from the list.
Terminators were set up fine until GST was altered. Changing to not rely on GST.
