### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by gptaylor717** [BSData/wh40k-7th-edition#3809]
**File/Catalogue:** 

**BattleScribe version:** 2.00.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes

**Description:** Looking to join with help on the dev side of 40k for Battlescribe.

Expertise in Java, XLM and other languages.

Thanks.

**Comment by alphalas** [comment]
https://gitter.im/BSData/wh40k join the conversation there - @amis92 will be around to grant your join

**Comment by amis92** [comment]
Invited: https://github.com/BSData/wh40k/invitations

Please take a look at [announcements](https://github.com/BSData/wh40k/issues?q=is%3Aissue+is%3Aopen+label%3Aannouncement).
