### ISSUE TITLE
Yet another new FW Knight to be added: Acheron

### ISSUE THREAD

**Issue by Thairne** [BSData/wh40k-7th-edition#381]
http://www.forgeworld.co.uk/Downloads/Product/PDF/A/Acheron.pdf

**Comment by Kangodo** [comment]
Thanks! I will add them to BA tomorrow.

**Comment by senpai514** [comment]
Already done for all armies!

**Comment by senpai514** [comment]
Figured I would get the jump on this and get it knocked out early. Was creating the commit and starting the sync when @Thairne created issue. I added in each extra piece to mirror the other Cerastus Knight for each catalogue for rules and hide entries

**Comment by Thairne** [comment]
Damn... and I thought I was quick on the roll... Kudos! :P
