### ISSUE TITLE
Feature request: Picking psychic powers

### ISSUE THREAD

**Issue by nottsknight** [BSData/wh40k-7th-edition#3810]
The new rules allow all psykers to choose the power or powers they know instead of rolling randomly. Might it be a good idea to add psychic powers as a new type of 'wargear,' and allow psychic units to select their power(s) from within the list?

**Comment by tekton** [comment]
I did that for Grey Knights the other night- it's not too hard to add, but does look a little weird, imo. There's already some built in support to the Alpha Builds for "Psychic Ability" when filling out profiles, too.

**Comment by flakpanda** [comment]
This should be handled on a cat by cat basis. Implementing this is easy. Create a new entry within the psyker with selectable powers. I have this for SM Libbies.

**Comment by amis92** [comment]
This issue was moved to BSData/wh40k#4
