### ISSUE TITLE
AdMech Typos

### ISSUE THREAD

**Issue by GenWilhelm** [BSData/wh40k-7th-edition#3813]
Did a quick pass on AdMech for any obvious typos, here's what I found:

- Tech-Priest Dominus, Eradication Ray: "Ap"
- Kataphron Breacher, Hydraulic claw: "substract"
- Kastelan Robots, Battle Protocols (second half): "invulerable"x2, "pahse", "e ach"
- Cybernetica Datasmith, Power Fist: "substract"
- Skitarii Vanguards, Rad-saturation: "oof"
- Sicarian Infiltrators, Neurostatic Aura: "substract"
- Ironstrider Balistarii, Twin Cogcnis Autocannon: "nmay", "firin", "suvstract"
- Ironstrider Balistarii, Twin Cognis Lascannon: "nmay", "firin", "suvstract"
- Sydonian Dragoons, Incense Cloud: "substract"
- Broad Spectrum Data-tether, Broad Spectrum Data-tether: "diration"
- Onager Dunecrawler, Daedalus missile launcher: "Substract"
- Onager Dunecrawler, Gatling rocket launcher: "Substract"
- Onager Dunecrawler, Twin Icarus autocannon: "Substract"
- Onager Dunecrawler, Smoke Launchers: "Shootiung", "substract"
- Cognis heavy stubber, Cognis heavy stubber: "substract"
- Chordclaw, Chordclaw: "awound"
- Adeptus Mechanicus Special Weapons, Transuranic arquebus: "ma ytarget", "Eaech", "makle"

**Comment by Thairne** [comment]
Altermative covfefe. I'm just following his example, how dare you?!
