### ISSUE TITLE
Adeptus Ministorum Typos

### ISSUE THREAD

**Issue by GenWilhelm** [BSData/wh40k-7th-edition#3814]
Did a quick pass on Adeptus Ministorum for any obvious typos, here's what I found:

- Uriah Jacobus, The Banner of Sanctity: "Jacobusadd"
- Seraphim Squad, Sky Strike: "Seraphi", "insead", "placig"
- Celestine, Saint Celestine: "Amour"
- Celestine, [Armour] of Saint Katherine: "Futhermore"
- Celestine, Miraculous Intervention: "geminae", "cound"
- Celestine, Healing Tears: "Celesting"
- Celestine, Beacon of Faith: "Millitarum"
- Imagifier, Simulacrum Imperialis: "peroform"
- Hospitaller, Healer: "attemt"
- Shield of Faith: "psykic"x4

**Comment by CloverFox** [comment]
fixed in 0a97b0a65d660c86a1c640b272290484f8ce1a9d
