### ISSUE TITLE
Chaos Demons minor issues.

### ISSUE THREAD

**Issue by tag8833** [BSData/wh40k-7th-edition#3815]
Chaos Demons

2.01.00.87

Windows

- [x] Seekers have the Unstopable Ferocity rule (khorne).
- [ ] Exalted Chariot has the wrong WS in its 1st wound chart.  
- [x] Phlegm bombardment on the Soul Grinder has the wrong Strength.
- [x] Kairos Fateweaver has The Two Heads of Fate which looks to be out of date.
- [x] Great Unclean one profile needs a * for BS.

**Comment by cartag** [comment]
Exalted chariot has WS of 2+ on first row, that is accurate.
Others have been updated.

**Comment by tag8833** [comment]
My mistake.  I must have looked at WS.  

That was all I noticed on my 1st pass.  Good work.
