### ISSUE TITLE
Multiple Factions in Detachments

### ISSUE THREAD

**Issue by CrusherJoe** [BSData/wh40k-7th-edition#3816]
Similar to how you could make a formation consisting of multiple "factions" in the Castellans of the Imperium formation in the twilight of 7th Edition, the only requirement for making a Battle-Forged army is that all units in the detachment share one Faction Keyword. I've tried to create a detachment with "mixed" sub-factions that share the Imperium Keyword, but I don't see a way to do it. 

I know implementing the Castellans formation was a big deal -- is there a plan to implement this sort of mixed factions detachments? Or am I just lame and have missed the existing implementation?

**Comment by cartag** [comment]
It's already been implemented, invisibly. After you add the first faction, make sure the one you just added is highlighted, then add another. It will be indented as a sub faction.

**Comment by CrusherJoe** [comment]
BRILLIANT! Thank you!
