### ISSUE TITLE
Blood Angels - Please report all issues here

### ISSUE THREAD

**Issue by GenWilhelm** [BSData/wh40k-7th-edition#3820]
Did a quick pass on Blood Angels for any obvious typos, here's what I found:

- Assault Squad, Combat Squads: "Beofre", "eache"
- Scout Squad, Concealed Positions: "zine"
- Stormraven Gunship, Airborne: "chargd"
- Stormraven Gunship, Supersonic: "miodel", "tp"
- Astorath, Mass of Doom: "friendy", "Troes"
- Teleport Homer: "eneemy", "hoìmer"

**Comment by Examinus88** [comment]
found some more for **blood angels**.

- [x] bolt pistol entry is linked to every **death company** entry in the unit.
- [x] **lightning claws** have 31 damage listed in profile.

**Comment by dennywright** [comment]
Scout Squad: Adding Camo cloak, Astartes shotgun, combat knife or boltgun to one model adds it to all models. Sniper rifle and Heavy Weapons only add to current model. Works correctly in vanilla Space Marines. Thanks for the work.

**Comment by Crowbar90** [comment]
Sorry for the delay, I'm fixing it all now.

**Comment by dennywright** [comment]
Is there any way to share the entries from Space Marines? I looks like the Dark Angels cat just copied them over. Did you copy over an earlier version or roll your own? Curious.

**Comment by alphalas** [comment]
Unfortunately not unless half of the marine cat gets put into GST - cross-cat sharing isn't a thing

**Comment by dennywright** [comment]
That's what I figured. Thanks

**Comment by Examinus88** [comment]
Assault marines are missing point for the regular marines.

**Comment by Examinus88** [comment]
Sry can't edit post on mobile but also found the jump pack option for multiple death company units is linked.

**Comment by Crowbar90** [comment]
I'll fix the jump pack tomorrow. I'm not sure about what you mean in the other comment though, can you please try to word it differently?

**Comment by Examinus88** [comment]
Only the wargear on assault marines has a points value, the Base models are missing points. Hope that clears it up

**Comment by Crowbar90** [comment]
Oh yes, sorry but I was pretty sleepy and didn't understand it last night. Working on it right now.

**Comment by amis92** [comment]
Looks like all got fixed, closing as resolved before freeze.

**Comment by barjed** [comment]
Assault Squad is still priced incorrectly. The 'Space Marine w/ Flamer' is equal to the cost of the weapon only but the Jump Pack option treats it as an actual space marine. This leads to inflated costs when Jump Packs are taken for a unit equipped with Flamers.

In addition, selecting the Blood Angles chapter in the Force Organization hides all named Blood Angel characters.

Moreover the double Lightning Claw load-out on a Captain is priced incorrectly (should be much lower).
