### ISSUE TITLE
PSA: How to port these files to BS, Pre-Release. Includes iOS

### ISSUE THREAD

**Issue by alphalas** [BSData/wh40k-7th-edition#3823]
First, go to https://github.com/BSData/wh40k

you will then see something that will look like this.
![image](https://user-images.githubusercontent.com/15703066/27007184-03351126-4e18-11e7-80ff-4f622305153c.png)

You will need to click the green button, and save the zip to a location on your local pc.
![image](https://user-images.githubusercontent.com/15703066/27007195-3a4cfc3c-4e18-11e7-8ec1-f1cf62a0051b.png)

Once you have the zip opened and unpacked, you will (1), click manage data on battlescribe, and (2) import from file all the (3) .cat files and the .gst file. 
![image](https://user-images.githubusercontent.com/15703066/27007212-b65e5230-4e18-11e7-92d8-49ede9ebb468.png)

You now can use all the data from the 8e branch to create rosters; however, if data is updated you will need to manually re-download the data because BS can't automatically pull it down.

To use the data on iOS, you need to have Dropbox synced to your BattleScribe, using the DB functionality built into BS. once you have that, open the app on iOS. Make sure it is also connected to your Dropbox, then hit the Menu Button (1), hit Manage Data (2), and then hit sync from Dropbox. (3)

![image](https://user-images.githubusercontent.com/15703066/27007279-8a4cf590-4e1b-11e7-9f27-9aefda9017c7.png)

All the glorious 8e data will now be accessible on your iOS device.

**Comment by CloverFox** [comment]
on android you can add the files to (your phones location)\Internal shared storage\Android\data\net.battlescribe.mobile.rostereditor\files\data\\(new folder)

**Comment by efalsken** [comment]
Please note: If you do these things, note that you will be "disconnected" from the mainstream release and you will not get future bug fixes until you delete the data files manually and add them by the normal index url.

**Comment by francoisbeaulieu** [comment]
The BS desktop app for Mac OSX doesn't seem to have dropbox integration. What is the folder I have to move the data files to on my dropbox for the data to be available to the iOS app?

**Comment by amis92** [comment]
No longer necessary

**Comment by alphalas** [comment]
reopened so i don't have to keep searching for it.

**Comment by FarseerVeraenthis** [comment]
@alphalas does this need to go on the wiki??

**Comment by alphalas** [comment]
Naw it can stay here I think - it's not something we really *should* have to reference that often.
