### ISSUE TITLE
Grey Knights - Dreadnaught & Venerable Dreadnaught Upgrades

### ISSUE THREAD

**Issue by nairul** [BSData/wh40k-7th-edition#3824]
**File/Catalogue:** Grey Knights.cat

**BattleScribe version:** 2.01.

**Platform:** Windows/

**Dropbox:** 

**Description:** 
Dreadnaught incorrectly allows upgrade to "Dreadnaught Combat Weapon (flamer) (49 points)"

The upgrade should read: "Dreadnaught Combat Weapon (Heavy Flamer) (57 points)"

**Comment by tekton** [comment]
Thanks- I kept feeling like there was something missing/wrong from/with the Dreadnaught...

**Comment by tekton** [comment]
Should be good now
