### ISSUE TITLE
8th Edition CSM issues

### ISSUE THREAD

**Issue by skonk** [BSData/wh40k-7th-edition#3829]
The following are issues in the DG and TS cats:
- [x] Blight Launcher is showing no points cost as an upgrade on Plague Marines; should be 14 points each.
- [x] Havoc Launcher upgrades are showing no points cost; should be 11 points each.
- [x] Combi-bolter upgrade shows as no cost on most vehicles (e.g. Land Raider); should be 3 points.
Note: combi-bolter as an upgrade to a hell brute powefist is showing the correct 2 points cost.

This is something I noticed in the CSM cat but likely exists in the DG and TS cats too if for items that are shared:
- [x] CSM Raptors - Special Weapon upgrade for the unit is set to a single radio button; but the rules state 2 models in the unit can take special weapons. They either switch out their Bolt Pistol/Chain Sword for Plasma Pistol/Chain Sword or they can replace their Bolt Pistol/Chain Sword for a single Special weapon (meaning each model exchanges both the pistol and sword for a single special, but up to 2 models can do this so 2 special weapons per unit).
- [x] Chaos Lord (all variants) - Seems to throw an error when you try to do any combination of Pistol + Power Weapon, Power Weapon + Combi Weapon or Pistol + Combi Weapon. The default pistol can be replaced with other pistols, melee weapons or combi weapons and the default Chain Sword can be replaced with Pistols or other Melee Weapons. Most legal setups are throwing validation errors unless they include the Chain Sword as the melee weapon.
- [x] Chaos Chosen - no Heavy or Special weapon upgrade option. One model per unit may replace his Boltgun with 1 item from Special or Heavy weapons. This is in addition to the the 4 models that can take the various other upgrades.
- [x] Chaos Chosen - when adding additional weapon loadouts; the default loadouts do not get removed automatically so it throws an error. The default loadouts can be removed manually to remove the errors but I'm not sure if this was your intended behaviour.
- [x] Khorne Berzerkers - Adding 2 units of berzerkers and modifying the second unit's "Swap Chainsword for Chainaxe" option, seem to add/remove them to the first unit also. Procedure to repeat issue: add unit of berserkers, increase number to 9 (+champ for 10) and swap 9 chainswords for chain axes. Then try to set the second unit up to be the same, changing the chainaxe property also changes the first units.

**Comment by cartag** [comment]
I can't set it to decrement certain ones if another option is taken, it's simply not doable. I may have to just rework how weapon selections are done in Chosen instead.
