### ISSUE TITLE
DA: Deathwing Terminators invalid weapon options

### ISSUE THREAD

**Issue by ninchistudios** [BSData/wh40k-7th-edition#3830]
File/Catalogue: Dark Angels v2
BattleScribe version: v2.01.00.87
Platform: Mac
Dropbox:No
Description: Deathwing Terminators permit invalid weapon combos, e.g. Lightning Claws (Pair) plus Assault Cannon. Which would admittedly be awesome.
@Thairne

**Comment by Thairne** [comment]
While admittedly stupid, the rules allow it.

You can replace all your weapons with Lightning Claws.
Then you take an item from the terminator heavy weapons list.
We can pretty much assume you will need to replace your Storm bolter, but that restriction just is not there.

Its basically the same as an Int Chap that has a SB, Crozius and can take a power fist without replacing anything, growing a third arm.

**Comment by ninchistudios** [comment]
The rules only allow it according to a RAW interpretation (FAQd as invalid previously) that takes operation order into account, and ignores that the second operation causes you to break the first.  You're also forcing players to pay for options that are clearly not RAI, thus the cat is broken for 99% of players.

**Comment by alphalas** [comment]
One thing you have to get use to around here - We BS data devs follow RAW strictly. RAI is not a thing here

**Comment by ninchistudios** [comment]
I have no issue with RAW, but where RAW is ambiguous and the chosen interpretation relies on an assumption about operation order, which isn't referenced in the rules, and results in a cat that is clearly broken, why be bloody-minded about it?

**Comment by alphalas** [comment]
Discredited in a FAQ for a previous edition. This is 8e, not 7e.

**Comment by Thairne** [comment]
https://github.com/BSData/wh40k/issues/3748
