### ISSUE TITLE
java.io.IOException: Unable to create directory: Can't change data location

### ISSUE THREAD

**Issue by Takao-7** [BSData/wh40k-7th-edition#3831]
**BattleScribe version:** 2.01.00
**Platform:** Mac
**Dropbox:** No
**Description:** 
I have installed Battlescribe "pro" on my MacBook Air and recently installed MacOs on my desktop computer ("Hackintosh"). I used the MacBook Airs Time Machine Backup on the Hackintosh.
The problem is, that I can't change Battlescribes Data location. Its set the location, where the Battlescribe repositories are on my Macbook, on an SD card.
When I try to change the location on my Hackintosh, then I get the error massage:

> Details:
> 
> java.io.IOException: Unable to create directory /Volumes/64gb SD/MEGA/Battlescribe/data
> 	at org.apache.commons.io.FileUtils.forceMkdir(FileUtils.java:2384)
> 	at net.battlescribe.a.c.b.a(BattleScribe:89)
> 	at net.battlescribe.a.c.G(BattleScribe:224)
> 	at net.battlescribe.a.c.A(BattleScribe:230)
> 	at net.battlescribe.a.a.a(BattleScribe:1158)
> 	at net.battlescribe.a.a.a(BattleScribe:1143)
> 	at net.battlescribe.desktop.d.d.a(BattleScribe:1085)
> 	at net.battlescribe.desktop.a.b$4.a(BattleScribe:342)
> 	at net.battlescribe.desktop.a.b$4.doInBackground(BattleScribe:336)
> 	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at javax.swing.SwingWorker.run(SwingWorker.java:334)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:748)

The location is NOT changed. Battlescribe is creating a "settings" folder in the new location with "settings.xml" file with the following content:

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<configuration battleScribeVersion="2.01" xmlns="http://www.battlescribe.net/schema/configSchema">
  <settings/>
  <dataIndexUrls/>
  <favouriteSets/>
</configuration>
```

I have reinstalled Battlescribe: No effect.

Also, on both Macs, I have the problem, that when opening Battlescribe, its always minimised in the bottom left corner.

**Comment by amis92** [comment]
Thank you for the report, however this repo is not the correct one to open the issue like that (BattleScribe bug). Please open the issue over on https://github.com/BattleScribe/Desktop-Alphas/issues
