### ISSUE TITLE
Craftworld Feedback

### ISSUE THREAD

**Issue by tag8833** [BSData/wh40k-7th-edition#3835]
I validated the Craftworld file.  Looks good.  

A few little issues.

- [x] Farseer Smite should be 0-1
- [x] Spiritseer & Warlock & Warlock Conclave Should be able to select psychic powers
- [x] Storm Guardians start with no models selected.  Probably missing a default selection.
- [x] Falcon should have a default heavy weapon, and should only be able to select 1 heavy weapon.

**Comment by USSX-Hares** [comment]
Falcons fixed
