### ISSUE TITLE
More Craftworld feedback

### ISSUE THREAD

**Issue by Owlsbane** [BSData/wh40k-7th-edition#3836]
Craftworld v7
2.01.01
Windows
Dropbox: No

- [x] Ancient Doom has 'SLANNESH' at the end of the paragraph.
- [x] Eldrad Ulthran's Psyker ability has 'three psychic powersin'.
- [x] Illic Nightspear, in his Voidbringer profile it misses 'an' in between 'can target enemy CHARACTER'.
- [x] Illic Nightspear, Appear Unbidden ability has 'walking the winding pathe', should be 'paths'. Also, it says 'set them up' but of course Illic is Unique ;)
- [x] Jain Zar Blade of Destruction has 're-roll failed hit rolls', should be 'wound rolls'.
- [x] Jain Zar Banshee Mask has 'fight first on the', should be 'fight first in the'.
- [x] Karandras, Master of Stealth has 'away from enemy models.', should be 'away from any enemy'.
- [x] Fuegan, misses the Melta Bomb profile.
- [x] Melta Bomb has a range of 4" and no Ability, but it should have a range of 6" and the following ability: "You can re-roll failed wound rolls for this weapon when targeting a VEHICLE."
- [x] Fuegan, Assured Destruction has 'this unit make', 'should be 'this unit makes'.
- [x] Fuegan, Unflinching Focus has 'friendly FIRE DRAGON', should be 'friendly FIRE DRAGONS'.
- [x] Baharroth, you need to add the Hawk's Talon manually, it should be standard gear.
- [x] Forceshield says 'This model has a 4+ Save', it should be 'a 4+ invulnerable Save'.
- [x] Autarch The Path of Command is missing 'of this model.' at the end of its description.
- [x] Avatar of Khaine's Khaine Awakened has 'not take Moreale test', should be 'Morale tests'.
- [x] Autarch Skyrunner's Laser Lance (melee) has 'If the bearercharged', misses a space.
- [x] Smite description has 'the closet visible enemy', should be 'closest'.
- [x] Warlock Conclave's Psyker (Conclave) has 'if it has 7-10 modelsit can' and 'but untis within 6" will'.
- [x] Storm Guardians have a 3+ save, but it should be 5+.
- [x] Spirit Stones has 'suffered and unsaved', should be 'an unsaved'.
- [x] Star Engines has 'ad 2D6', should be 'add 2D6'.
- [x] Wave Serpent's Serpent Shield has 'is reduced by,', should be 'is reduced by 1,' and 'discharge ots serpent', should be 'discharge its'.
- [x] Warp Spiders have 2W and 2A, it should be 1W and 1A.
- [x] Warp Jump Generator has 'and it can FLY', should be 'and they can FLY'.
- [x] Warwalker throws a validation error, says number of Heavy weapons is maximum 1, should be maximum 2.
- [x] Crack Shot has 'ranged weapons', should be 'ranged weapon'. <-- In the index it is "weapons", technically he has two - a fusion gun AND melta bombs...
- [x] Inescapable Accuracy has 'ranged wepaon', should be 'ranged weapon'.
- [x] Explodes (War Walker) has 'to 0 woundsm', should be 'to 0 wounds'.
- [x] Falcon shows no validation error when taking more than one Heavy Weapon.
- [x] Airborne has 'by untis that', should be 'by units that'.
- [x] Mindschock Pod has 'any Hemloack', should be 'any Hemlock'.
- [x] Scattershield has '5+ invulnderable', should be '5+ invulnerable'.
- [x] Catastrophic Collapse has 'On a 9 it', should be 'On a 6 it'.
- [x] Unstoppable Revenant has 'during this turn', should be 'during its turn'
- [x] Shining Spear Exarch misses cost for model, it's 24 points short.

@FarseerVeraenthis Nice work, mostly just typo's, hardly anything major.

**Comment by FarseerVeraenthis** [comment]
Thanks for your help, I'm glad there's nothing major :+1:

**Comment by USSX-Hares** [comment]
Fix all for Falcons, Serpents, War Walkers. @FarseerVeraenthis had changed the mechanism of Heavy Weapons list and do not changed then its dependencies.
