### ISSUE TITLE
Space Wolf Feedback

### ISSUE THREAD

**Issue by tag8833** [BSData/wh40k-7th-edition#3837]
There are a number of items I found.  Most of them are suggestions to make the UI work better for the end user.

- [x] Wolf Lord / WGBL / Lone Wolf / WG Ranged Weapon selections is unwieldy.  I would make a "Shared Selection Entry group" that links to all of the options for ranged weapons.  That way it can be a radio selector like the melee weapons.
- [x] Dreadnought.  If you take Great Wolf Claw you also get either a storm bolter or Heavy flamer.  
- [x] Wolf Lord on Thunderwolf has a Stormshield listed as wargear.  I don't see it on his datasheet.
- [x] Wolf Lord, Wolf Lord on Bike, and Wolf Lord in Termie armor has no default wargear.
- [x] Wolf Lord Jump packs should be 0-1
- [x] Rune priest and Wolf Priest: it would be nice to group ranged weapons.
- [x] Wolf Priest on Bike should default to have a bolt pistol.
- [x] Blood Claw with special weapon probably doesn't need a Chainsword option.
- [x] Wolf Guard Pack Leader, Thunder Wolf Cav:  Chainsword is on the melee weapon list.  You should make that the default selection, and remove the other one.  They should have Frag and Krak grenades.  
- [x] Grey Hunters and Swiftclaws should probably be setup like Blood Claws.  Grey Hunter with special weapon.  Grey hunter with Banner.  Etc.
- [x] ‏Iron Priest.  Tempest Hammer can't be free.
- [x] Wolf Scout with heavy weapon probably doesn't need a boltgun option.  It would be nice if it were a list.
- [x] Wulfen pack leader only need 1 launcher.
- [ ] Wolf Guard, they probably all need to take jump packs. Not just one.
- [x] Swiftclaw Wolf Guard bike leader needs default wargear (bolt pistol)
- [x] Long Fangs, it would be nice if the boltgun were on the radio list.

**Comment by Ragnar69** [comment]
- [x] Frost Claws on Wulfen are costed at 0 points, correct is 15
- [x] Grey Hunters (Blood Claws) should be allowed to have 2 special weapons when the unit has 10 (15) models (including WG pack leader)
- [x] Chain Swords on Grey Hunters don't work at all. The field seems to be connected to all GH units and also seems to affect the number of GHs in the unit
- [x] WG pack leaders on Grey Hunters are costed 13 points, should be 14

**Comment by ghost** [comment]
- [x] Storm Shields on Thunderwolf Cavalry should be 15 points, not 5 (see page 217 'Other Wargear' in the book)

**Comment by al3ar** [comment]
- [x] stormwolf twin helfrost cannon should be 30pts
- [x] Not only SW, predator have "Predator AC" 49pts, not usual AC.

**Comment by ThatIrishSOB** [comment]
The following units appear to be missing their stat lines.
Bjorn The Fell-Handed
Canis Wolfborn
Murderfang

Land Raider Crusader's PL is 9 instead 17
Rhino is missing it's PL of 4
