### ISSUE TITLE
Dark Angels Typos

### ISSUE THREAD

**Issue by GenWilhelm** [BSData/wh40k-7th-edition#3838]
- Jump Pack: "moel", "thi", "assult"
- Smoke Launchers: "Shootiung", "substract"
- Azrael, Lion's Wrath: "substract"
- Belial, Parrying blade: "substract"
- Raven Sword: "preceeding"
- Asmodai, Exemplar of Hate: "firiendly"
- Ravenwing Dark Shroud, Icon of old Caliban: "substract"
- Ravenwing Dark Talon, Hover jet: "hover.Its"
- Ravenwing Dark Talon, Rift cannon: "table.If"
- Narthecium: "singel", "I fthe", "ect."
- Company Heroes: "seperate"
- Astartes Banner: "succuming"
- Command Squad Bodyguard: "charater", "unt"
- Biker Bodyguard: "charater", "unt"
- Concealed Positions: "deploymeny"x2
- Omniscope: "Centurian"
- Open Topped: "passangers"
- Servo-skull Hub: "youe"
- Aura of Dread: "substract"
- Hard to hit: "substract"

**Comment by Thairne** [comment]
to be fair, "substrahieren" is subtract in German. That explains all those extra 's' :P
