### ISSUE TITLE
Deathwatch Typos

### ISSUE THREAD

**Issue by GenWilhelm** [BSData/wh40k-7th-edition#3839]
Did a quick pass on Deathwatch for any obvious typos, here's what I found:

- Jump Pack: "moel", "thi", "assult"
- Corvus Blackstar, Supersonic: "fowards"
- Auspex Array: "emey"
- Special Issue Ammunition (profile): "issu"
- Special Issue Ammunition (rule): "Drgonfire"
- Frag Assault Launchers: "emeny", "motal"

**Comment by tag8833** [comment]
Fixed via #3852
