### ISSUE TITLE
Drukhari Typos

### ISSUE THREAD

**Issue by GenWilhelm** [BSData/wh40k-7th-edition#3841]
Did a quick pass on Drukhari for any obvious typos, here's what I found:
- Raider, Explodes: "fom"
- Ravager, Explodes: "fom"
- Razorwing Jetfighter, Explodes: "fom"
- Reavers, Grav-Talon: "withink"
- Venom, Explodes: "fom"
- Cronos, Explodes: "fom"
- Cronos, Spirit Vortex: "weaon"
- Talos, Explodes: "fom"
- Voidraven, Crash and Burn: "fom"
- Archite glaive: "atacking"
- Dark Lance: "equipeed"

**Comment by Toreador13** [comment]
All fixed in version 10.

**Comment by FarseerVeraenthis** [comment]
@Toreador13 Please upload Version 10 to Github :smile:

**Comment by Toreador13** [comment]
I have to wait until I get home. Github doesn't like my work's proxy much at all.

**Comment by FarseerVeraenthis** [comment]
They all look fixed to me, can this be closed now?
