### ISSUE TITLE
Grey Knights Brotherhood Ancient Wargear

### ISSUE THREAD

**Issue by Delfury** [BSData/wh40k-7th-edition#3845]
File/Catalogue: 40k8eprep

BattleScribe version: 2.01.

Platform: Windows

Dropbox: No

Description: The brotherhood ancient is showing default 2x Falchions, when this should only be 1 Falchion.  Note that this is technically an optional upgrade.  Also note that this is correctly generating a validation error that the brotherhood ancient has too many Falchions.

**Comment by tekton** [comment]
There were a few other issues with him, too. All taken care of now!
