### ISSUE TITLE
Deathwatch Kill Team 8th

### ISSUE THREAD

**Issue by darkestvisions** [BSData/wh40k-7th-edition#3846]
Some issues with the Deathwatch Kill Team unit;

1. Vanguard Veterans don't have option for pair of lightning claws (13pts instead of 2x9pts)

2. Terminator - cannot select both "Heavy Flamer" and "Power Fist & Meltagun" which are from separate wargear choices

3. Veterans - no options for Combi- weapons can be added

**Comment by Beanithpie** [comment]
Adding to **darkestvisions's** 3. The Deathwatch Equipment List has two sub headings.

- The first subheading contains all the close combat weapons from which **Up to two items can be chosen from the following list**
- The second subheading contains all the guns from which **One weapon can be chosen from the following list**

That would be mean the DW can still be equipped just like in 7th ed with Boltguns and Chainswords, plasma guns and power fists, combi-weapons and stormshields (which cost 15 points compared to 5 points for other space marines), etc. Unlike 7th ed, they can now have bolt pistols.

Also 4. Up to 4 Veterans can replace their boltgun  with Deathwatch Heavy Weapons

**Comment by Beanithpie** [comment]
~~5. Chaplin - No option to add Jump pack~~

**Comment by FarseerVeraenthis** [comment]
"DEATHWATCH Librarians and Chaplains may not be equipped with jump packs." <-- per the Deathwatch wargear section of the index.

**Comment by tag8833** [comment]
I'm fixing this and not quite sure how to do it right.
![image](https://user-images.githubusercontent.com/17749311/27040697-64cef3d0-4f57-11e7-8209-64955f6233e9.png)
Here is the list:
![image](https://user-images.githubusercontent.com/17749311/27040655-46314ea0-4f57-11e7-9e32-d1a69343d722.png)

So does that mean they can replace their bolter with a Combi-flamer and a Lightning Claw?  they just can't take 2 Combi-Flamers or a Combi-flamer and a bolter?

**Comment by flakpanda** [comment]
@tag8833 look at SM sgt equipment shared list entry. it is similar.

**Comment by tag8833** [comment]
@flakpanda Does your method work within the constraint of the list here?   It says "One weapon can be chosen from the following list, so does that mean, if I can't choose a meltagun AND a Plasmagun?

**Comment by tag8833** [comment]
Pending a misunderstanding on the limitations of wargear this is fixed via #3852
