### ISSUE TITLE
8th ed Adeptus Ministorum bugs

### ISSUE THREAD

**Issue by rberrill** [BSData/wh40k-7th-edition#3854]
**File/Catalogue:** Adeptus Ministorum revision 18

**BattleScribe version:** 2.00.

**Platform:** Mac

**Dropbox:** Yes

**Description:** Detailed issue description.

The Seraphim superior should be able to swap a bolt pistol for a chainsword or a power weapon, and swap the other bolt pistol for another pistol.

Steps to Repeat:

Add a seraphim squad
Click on seraphim superior to try to select wargear
No options are present

[sob-test.rosz.txt](https://github.com/BSData/wh40k/files/1069268/sob-test.rosz.txt)

**Comment by CrusherJoe** [comment]
@rberrill You beat me to it -- I noticed this (late) last night and was going to report it this morning.

**Comment by Toreador13** [comment]
I'll just add this here. 

Ministorum Priest no profile. 
Uriah Jacobus no profile. 
Sister Repentia profile no M value.

**Comment by FarseerVeraenthis** [comment]
#3877 is related to this issue

**Comment by FarseerVeraenthis** [comment]
#3875 is related to this issue

**Comment by CrusherJoe** [comment]
@alphalas -- Not sure if the latest update to the Adeptus Ministorum cat was supposed to fix this or not, but I just downloaded the update uploaded 3 hours ago and this issue is still present.

**Comment by alphalas** [comment]
@crusherjoe join us on gitter - discussion should be carried out there

**Comment by CloverFox** [comment]
all fixed in 53f678dde4dcb04d59f849d00da787a2dcf8cbc9
