### ISSUE TITLE
8th Ed Craftworld Issues

### ISSUE THREAD

**Issue by tylker14** [BSData/wh40k-7th-edition#3855]
**File/Catalogue:** craftworlds.cat

**BattleScribe version:** 2.00.

**Platform:** Windows

**Dropbox:** Yes/No

**Description:**  

The point cost of weapons does not scale with the amount of aspect warriors there are in a squad. The default amount for however many weapons there are stays that cost no matter if you increase or decrease the amount of models with that weapon.

**Comment by FarseerVeraenthis** [comment]
Do you have an example?
I'm on file version Rev 9 and they seem to scale perfectly well to me...

**Comment by tylker14** [comment]
When I increase a squad of dark reapers to 5 for example the price of 5 weapons is the same as 3

**Comment by FarseerVeraenthis** [comment]
As I asked, which file version are you on?
This works fine for me on Rev 9...

**Comment by tylker14** [comment]
seems to be working now, sorry for the confusion

**Comment by FarseerVeraenthis** [comment]
no problems, I was just working on the file so perhaps you had an old version that was bugged... Dark Reapers were one of the last units I completed as well so who knows :smile:
I'm glad it's fixed now!!
