### ISSUE TITLE
Craftworlds feedback

### ISSUE THREAD

**Issue by Mad-Spy** [BSData/wh40k-7th-edition#3862]
@USSX-Hares

Craftworlds.cat v9

**BattleScribe version:** 2.01.00

**Platform:** Windows

**Dropbox:** No

**Description:** 

- [x] Illic Nightspear: Misspelling of "targetting" in Voidbringer's description.
- [x] Jain Zar: Should read "Jain Zar always **fights** first" in Banshee mask Description.
- [x] Maugan Ra: Should read "for Maugan Ra's **ranged** weapon" in Harvester description.
- [x] Spiritseer: Missing **<CRAFTWORLD> Spirit Host** tags from Spirit Mark ability in Roster Editor. I think "Spirit Host" needs to come out of <> in the Description.
- [x] Spiritseer: Missing Smite Psychic power.
- [x] All Warlock types: Missing Smite Psychic power. Deliberately left out in favour of Destructor? However, rule book does state that they know Smite.
- [x] Warlock Conclave: Consider changing value to explicitly 3 PL per model to remove need for 
increment?
- [x] Warlock Skyrunner Conclave: Consider changing value to explicitly 5 PL per model to remove need for increment?
- [x] Fire Dragon Exarch: mispelling of "automatically" in Dragon's Breath Flamer description.
- [x] Striking Scorpions: "If this model has mandiblasters" is redundant in the Mandiblasters description. I guess this is there because of the Autarch, but given that the rule will only appear if you give an Autarch Mandiblasters, this text can be removed.
- [x] Striking Scorpions: Master of Stealth should read "of any of your Movement **phases**". This is misspelled in the rule book.
- [x] Vehicle Equipment: Crystal **targeting** matrix is misspelled in name and description.
- [x] Explodes (Hover Tank) "ability" is visible on the profile for Hover Tanks, which is not the case for Vypers or War Walkers. Either way of showing it is fine, but it should be consistent.
- [x] Vaul's Wrath Support Battery: **targeting** is misspelled in the Guardian Crew ability.
- [x] Vaul's Wrath Support Battery: should be "add 2 to  **its** wound rolls" in Vibro Cannon description.
- [x] War Walkers: Missing Power Field ability.
- [x] Wraithlords: Issue described in #3863 is not happening in latest revision, but changing Shuriken Catapult for Flamer removes the catapult from other Wraithlords in the detachment.
- [x] Wings of Khaine ability: Should read "on the spot **up to** 90 **d**egrees" and "pivot **it** a further 90 **d**egrees" 
- [x] Hemlock Wraithfighter has no Psychic Power options; it should know Smite and 1 power from Runes of Battle.

**Comment by USSX-Hares** [comment]
@FarseerVeraenthis, FYI

**Comment by tylker14** [comment]
Also, the weapon cost does not scale when adding or removing models with swooping hawks, banshees, scorpions, warp spiders, wraithguard, wraithblades, dire avengers, and shining spears

**Comment by Mad-Spy** [comment]
@tylker14 , the cost for Aspect Warrior squads appears to be working ok for me on Windows. What platform are you using?

**Comment by FarseerVeraenthis** [comment]
looks like the copy and paste fairy was not happy with me last night... I'll try to get these fixed as quickly as I can...

**Comment by tylker14** [comment]
@ilaunchbury, I'm also on Windows, the default price is correct and the cost for the models changes when you add more or take any away; however, for me the total cost of the weapons is the same no matter if there are 5 or 10

**Comment by Mad-Spy** [comment]
@tylker14, I'm unable to replicate it on BS 2.01.00.87 with Craftworlds v9.
What you're describing is that the highlighted value in the screenshots below is not changing for you?
![image](https://user-images.githubusercontent.com/29306451/27089661-f5bb3fec-5052-11e7-98ad-dee8a08d7bc5.png)

![image](https://user-images.githubusercontent.com/29306451/27089681-04a2e834-5053-11e7-9bda-fff79d353a38.png)

**Comment by tylker14** [comment]
Yes, it may just be me but it's happened multiple times

**Comment by tylker14** [comment]
@ilaunchbury, Would there be some reason that adding an exarch messes it up because I usually do that

**Comment by Mad-Spy** [comment]
No, that seems to work fine for me as well.

**Comment by tylker14** [comment]
@ilaunchbury, I'll try them all again to see if it was a battlescribe error

**Comment by tylker14** [comment]
![image](https://user-images.githubusercontent.com/29387013/27100980-f9e5274a-504d-11e7-8f70-8df4f06cc534.png)

@ilaunchbury This is what I was referring to, It happens quite often for me at least. This is on v10

**Comment by tylker14** [comment]
@ilaunchbury It only seems to happen if Craftworlds is taken as a "child force"

**Comment by amis92** [comment]
I can replicate on v2.01.01.88 (Desktop + Android). Opening issue over on battlescribe alphas.
