### ISSUE TITLE
Craftworlds v9 Wraithlord

### ISSUE THREAD

**Issue by MaestroQuark** [BSData/wh40k-7th-edition#3863]
**File/Catalogue:** Craftworlds v9

**BattleScribe version:** 2.01.00.87

**Platform:** Windows

**Dropbox:** No

**Description:** 

- [x] Wraithlord: having two Wraithlords in the detachment is messing with Support Weapon options.  Editing one Wraithlord's Support Weapons affects the other Wraithlord as well.

**Comment by USSX-Hares** [comment]
@MaestroQuark, Reproduced. Have no idea why it's happening.

**Comment by FarseerVeraenthis** [comment]
I think Shuriken Catapult is "collective".
As such, a new entry will need to be made for the shuriken catapult that is not collective, and then the Wraithlord weapons will need to be re-linked to that entry.

**Comment by FarseerVeraenthis** [comment]
covered in #3862
