### ISSUE TITLE
Grey Knights Techmarine

### ISSUE THREAD

**Issue by Delfury** [BSData/wh40k-7th-edition#3864]
File/Catalogue: 40k8eprep

BattleScribe version: 2.01.

Platform: Windows

Dropbox: No

The Grey Knights Techmarine costs 58 points, but already includes his servo harness without paying for it. Should cost 40 points more (12+12+9+7), 98 points in total.

**Comment by tekton** [comment]
Turns out Techmarines are listed on the page with other GK units and his base is actually 91 points :(

**Comment by tekton** [comment]
Should be good now

**Comment by Delfury** [comment]
Wow, what a rip-off.  Thanks for the correction!
