### ISSUE TITLE
Grey Knights Issues

### ISSUE THREAD

**Issue by nairul** [BSData/wh40k-7th-edition#3868]
- [x] Purgator Justicar incorrectly costs 28 points. He should cost the same as a Purgator @ 21 points per model.
- [x] Purifiers incorrectly cost 21 points per model. They should cost 28 points per model (including storm bolter).
- [x] Interceptor incorrectly costs 21 points per model. They should cost 25 points per model (including Storm Bolter)
- [x] Nemesis Dreadknight "may take up to two **different** weapons from the following: Heavy Incinerator, Gatling Psilencer, Heavy Psycannon"

**Comment by tekton** [comment]
I'll take care of this tonight, I thought I already fixed those but I'll get it pushed up.

**Comment by nairul** [comment]
Maybe they are already fixed... I last updated my data files yesterday. Anyways, thanks for all your help!

**Comment by tekton** [comment]
No worries- I actually just figured out what happened on all of those; same basic bug. Just need to finish the Dreadknight- I actually thought there would be MORE problems with that one, heh

**Comment by tekton** [comment]
Thank you @nairul for being another set of eyes; nice to know someone else plays on the side of Purity!
