### ISSUE TITLE
Celestine Geminae Points not displaying correctly

### ISSUE THREAD

**Issue by flakpanda** [BSData/wh40k-7th-edition#3877]
Don't know why, but the Geminae for Celestine don't update properly on desktop. 
On android I noticed this as well if I select one first, then select two it stays at 50 pts. But when selecting two outright on android it adds the points in correctly.
<img width="1497" alt="screen shot 2017-06-14 at 1 01 09 am" src="https://user-images.githubusercontent.com/19719565/27117680-3aba8a18-509d-11e7-97d7-b29d487da5ac.png">

**Comment by amis92** [comment]
@flakpanda could that be the same issue as https://github.com/BattleScribe/Desktop-Alphas/issues/166 ? Only happens in nested forces?
