### ISSUE TITLE
Missing Runes of Battle descriptions

### ISSUE THREAD

**Issue by Mad-Spy** [BSData/wh40k-7th-edition#3878]
@FarseerVeraenthis 

Craftwords.cat v11

**BattleScribe version:** 2.01.00.87

**Platform:** Windows

**Dropbox:** No

**Description:** 

- [x] Conceal/Reveal has its entry as a Rule rather than a "Psychic Power" type Profile.
- [x] Embolden/Horrify and Enhance/Drain do not have Profile entries at all, so they have no rules.

**Comment by FarseerVeraenthis** [comment]
damn those pesky psychic powers!!

**Comment by FarseerVeraenthis** [comment]
closed with commit 3d785b5
