### ISSUE TITLE
Grey Knights Typos

### ISSUE THREAD

**Issue by GenWilhelm** [BSData/wh40k-7th-edition#3881]
Did a quick pass on Grey Knights for any obvious typos, here's what I found:
- [x] Categories: "Dreadnaught"x2
- [x] - Nemesis Daemon Greathammer: "hitt"
- [x] - Lord Kaldor Draigo, Psyker: "Santic"
- [x] - Brother Captain Stern, Psyker: "Santic"
- [x] - Grand Master, Psyker: "Santic"
- [x] - Grand Master Voldus, Psyker: "Santic"
- [x] - Nemesis Dreadknight, Force Shielding: "invulnurable"
- [x] - Stormraven Gunship, Transport: "Dreadnaught"
- [x] - Shared Selection Entries: "Dreadnaught"x2
- [x] - Shared Selection Entry Groups: "Dreadnaught"x2
- [x] - [Dreadnought] Left Arm: "Dreadnaught"x2
- [x] - Shared Selection Entry Groups: "Santic"x3
- [x] - Psychic Locus: "withing"
- [x] - Rites of Banishment: "unles"
- [x] - Frag Assault Launchers: "emeny"
- [x] - Mindlock: "imporve", "Balistic"
- [x] - Nemesis Daemon Hammer: "hitt"
- [x] - Shared Profiles: "Dreadnaught"x2
- [x] - Multi-melta: "inflicinting"
- [x] - Purge Soul: "Santic"
- [x] - Gate of Infinity: "Santic"
- [x] - Hammerhand: "Santic"
- [x] - Shared Profiles: "Santic"x3
- [x] - Psyker ([Sanctic] 1): "Santic"
- [x] - Psyker ([Sanctic] 2): "Santic"
- [x] - Psyker ([Sanctic] 1 Squad): "Santic"

**Comment by tekton** [comment]
Will get this done in the morning (PDT) since I spent the night painting Grey Knights and terrain

**Comment by tekton** [comment]
Should be good now
