### ISSUE TITLE
Orks Typos

### ISSUE THREAD

**Issue by GenWilhelm** [BSData/wh40k-7th-edition#3885]
Did a quick pass on Orks for any obvious typos, here's what I found:
- Burna-bommer, Burna Bomb: "mdoel"
- Blitza-bommer, Boom Bomb: "mdoel"
- Grot Gunner, Grot Krew: "Gunnders"
- Zzap gun: "Strenght"
- 'Ere We Go!: "re-rol"
- Supersonic: "fowards"

**Comment by tag8833** [comment]
All fixed.
