### ISSUE TITLE
[Join Request] Astra Militarum 8. Edition

### ISSUE THREAD

**Issue by Takao-7** [BSData/wh40k-7th-edition#3898]
I would like to help creating the Astra Militarum files because I play them myself (Renagades, but the FW rules for them aren't released yet...).

**Comment by alphalas** [comment]
Join us on Gitter - I'm the AM keeper

**Comment by Takao-7** [comment]
Where is the link to Gitter?
I can't find it.

**Comment by alphalas** [comment]
#3721

**Comment by Takao-7** [comment]
I joined Gitter and fixed the following bugs from #3895:
- Hot Shot Las Pistol should cost 1 point
- I would love an option to inculde the list of Orders with the roster.
- Lord Commisar, Tempestor Prime, Commisar: Chainsword has no profile. In fact no items on the Melee weapons list has a profile.
- Hot Shot Lasgun and Hot Shot Las Pistol profile incomplete. S3 Ap-2 D1
- MT Scions - They can take 2 special weapons for every 5 models in the unit.
- Taurox Prime has the wrong BS in it's damage table. It should be 1 better. Starts at 3+.
- Bullgryns are missing some options. They should be able to take a Grenadier Gauntlet & Bruteshield or a Power Maul and Slabshield. Also, it's not an ordianry Power Maul. It is a bullgryn maul.
- Ratlings should be grouped. They have no options. Make their sniper rifle collective.

I also added the chainsword to the "Melee Weapons" group, because basically any model that has access to it, has a chainsword.

Can I just those commit those changes?

**Comment by amis92** [comment]
@Le-Sir please do commit them on your fork and make a pull request.

**Comment by Takao-7** [comment]
When I make push request with the app, I get an authentication error.

**Comment by alphalas** [comment]
Please don't submit changes to AM

**Comment by amis92** [comment]
@Le-Sir you've probably cloned this repo and made the change there. You should fork the repo first, and then do the change on your fork. You can read on forking by googling "GitHub help fork" or similar, they have quite good help.

That's for future, seems @alphalas is still busy with it and merging XML is nightmare not worth the effort, so he'll just copy your fixes over manually.

**Comment by Takao-7** [comment]
Yes, that exactly what I did -.-
I forked it know.

@alphalas I will wait for making changes until you are finishing with the refactoring.

**Comment by alphalas** [comment]
Well I plan on fixing the issues during the refactoring- if you wanna help upload your file on Dropbox or Gitter and send me a link

**Comment by Takao-7** [comment]
Great, the changes are gone because I might have messed up some things while I was trying to get back to the original version.
There are a lot of things that should be refactored and in my changes I did this, so making changes on two files simultaneously would mean that in the end you have to somehow merge them, which would take again a lot of time.
