### ISSUE TITLE
Issue: Tau Empire Pulse Blast Cannon Profiles

### ISSUE THREAD

**Issue by T6Ted** [BSData/wh40k-7th-edition#3899]
**File/Catalogue:** Tau Empire

**BattleScribe version:** 2.01.

**Platform:** Windows

**Dropbox:** No

**Description:** Pulse Blast Cannon Weapon profiles are out of order. 

![image](https://user-images.githubusercontent.com/29199579/27179300-f48fb982-519b-11e7-9896-f7c6bf5bb43e.png)

**Comment by amis92** [comment]
Same with Pulse Blaster, I'm still exploring options how to fix it nicely.
