### ISSUE TITLE
Tau Strike Team Unit Size Issue

### ISSUE THREAD

**Issue by T6Ted** [BSData/wh40k-7th-edition#3900]
**File/Catalogue:** Tau Empire

**BattleScribe version:** 2.01.

**Platform:** Windows

**Dropbox:** No

**Description:** When you have 2 units of strike teams in the list changing one unit size changes both.

**Comment by amis92** [comment]
@T6Ted does that happen only when the Tau force is a child of another force? If so, it might be the same BattleScribe bug as there https://github.com/BattleScribe/Desktop-Alphas/issues/166
