### ISSUE TITLE
Deathwatch Kill Team is missing Watch Sergeant A:3, Ld:9, access to Xenophase Blade

### ISSUE THREAD

**Issue by Delfury** [BSData/wh40k-7th-edition#3903]
Deathwatch Kill Team is missing Watch Sergeant A:3, Ld:9, access to Xenophase Blade

**Comment by tag8833** [comment]
Looks good to me:
![image](https://user-images.githubusercontent.com/17749311/27185512-3250368e-51ab-11e7-90fe-36c62bc7f4d4.png)

However, I did notice that the boltgun wasn't the default selections, so I fixed that.

**Comment by Delfury** [comment]
My bad :(
