### ISSUE TITLE
Grey Knights: Attributes missing from Brotherhood Ancient.

### ISSUE THREAD

**Issue by LuisMars** [BSData/wh40k-7th-edition#3906]
**File/Catalogue:** Imperium - Grey Knights v5

**BattleScribe version:** 2.01.01

**Platform:** Windows

**Dropbox:** No

**Description:** As the title says, the attributes for the Brotherhood Ancient are empty.

**Comment by tekton** [comment]
That's weird, I actually have a printed once I made with his stats, but you're right it's not there now 😭

**Comment by tekton** [comment]
Iz fxd
