### ISSUE TITLE
Drukhari Issues

### ISSUE THREAD

**Issue by Mad-Spy** [BSData/wh40k-7th-edition#3908]
@Toreador13 

**File/Catalogue:** Drukhari v10

**BattleScribe version:** 2.01.02.89

**Platform:** Windows

**Dropbox:** No

**Description:** 

- [x] Phantasm Grenade Launcher: should be "subtract 1 from **its** Leadership" in the description.
- [ ] Haemonculus: Haemonculus tools and Splinter Pistol should not be optional.
- [x] Crucible of **Malediction** is misspelled.
- [x] Crucible of Malediction: should be "unleash **its** contents" in the description.
- [x] Liquifier gun: should be "hits **its** target" in the description.
- [x] Flesh Gauntlet: should be "suffers a mortal **wound**" in the description
- [x] Lelith Hesperax: The implementation of Lelith's weapons is odd. It would seem better to give her a fixed Penetrating Blade, then an option for the second blade/Impaler (which should be costed as it's optional). I assume that only default wargear is included in her points cost, not optional. 
![image](https://user-images.githubusercontent.com/29306451/27188769-2adc7408-51e7-11e7-83f8-cc38b23e6b0a.png)
- [ ] Archon: Members is misspelled as Memebers in Court of the Archon.
- [ ] Succubus: Needs Splinter pistol set as default ranged weapon.
- [ ] Succubus: Missing "Lightning Dodge" and "No Escape" abilities.
- [ ] Kabalite Warriors: PL increments are incorrect. As I understand it, PL should increase once minimum is exceeded, not when maximum is reached. i.e. 1 Sybarite + 4 Warriors is 3 PL, 1 Sybarite + 5 Warriors should be 5 PL.
- [ ] Wracks: Should Acothyst's Haemonculus tools be 0-1 as he has to swap them for his Weapons of Torture option as per RAW?  As the Acothyst has no ranged weapon, how can he swap it for Tools of Torment which is required RAW? I suggest RAI is that he swaps Haemonculus tools for one of the other options. Would need adding to #3748.
- [ ] Wyches: Unit size should be 5-20, not 5-15.
- [ ] Beastmaster: Adding Khymerae pairs does not increment PL.
- [ ] Beastmaster: The Khymerae have a 5+ inv save, but the Beastmaster does not gain it, The way this is currently implemented makes it look as if he does when you add them as his free unit. Not sure how/whether this can be fixed.
- [ ] Grotesques: Grotesque with Weapons of Torture needn't have weapon options other than Weapons of Torture. He can't replace his Monstrous Cleaver with both a Liquifier Gun and a Weapon of Torture at the same time.
- [ ] Hekatrix Bloodbrides: Same PL increment issue as with Kabalite Warriors.
- [ ] Incubi: Klaivex should have Klaive as default weapon.
- [ ] Incubi: Incubi Model entry should be Max 9 Selections in Parent (currently 10 which causes a validation error).
- [ ] Mandrakes: Should be 9 PL at 6+ models, not 10.
- [ ] Mandrakes: Should be "any of **your** Movement Phases" in From Out of the Shadows description. Also a missing whitespace in "at least **9"away** from".
- [ ] Sslyth: Shardcarbine should be one word.
- [ ] Sslyth: Sslyth who are included in the Court of the Archon have the same problem as with Khymerae for the Beastmaster, in that the way rules are grouped implies that the Archon (and any other models in the "unit") get a 5+ save.
- [ ] Reaver: Individual Reaver upgrades should be max 1 per parent. Also, conceivably any Reaver can take them, so they should be included on the Special Weapons Reavers as well. This is likely to need major rework.

- [ ] Dark Lance: It would seem neater to use a modifier to change the weapon type if it's equipped on a relevant vehicle rather than relying on the ability text.
![image](https://user-images.githubusercontent.com/29306451/27202479-b721b0cc-5219-11e7-9888-b6878335817c.png)

**Comment by Toreador13** [comment]
I am very unsure that the Impaler would cost more than the penetrating blade, or that a model that includes points costs for all wargear would then have a further points cost. 

It is somewhat clunky, but all the different ways I tried were not either intuitive or worse in layout to me.

**Comment by amis92** [comment]
@Toreador13 maybe add it to #3748 ?

**Comment by Toreador13** [comment]
![image](https://user-images.githubusercontent.com/6875311/27194401-0fd2555c-51c8-11e7-83cf-4a3123ef4a1c.png) Haemonculus tools and Splinter Pistol are only optional because Tools of Torture and Weapons of Torture require you to give them up.

**Comment by Toreador13** [comment]
All corrections are in V12 which will release tonight.

**Comment by Mad-Spy** [comment]
Sorry, missed that rule.

I have a suggestion on how to make the Haemonculus weapon options look tidier by putting the default weapon options into a selection group with the other options of the same type.

![image](https://user-images.githubusercontent.com/29306451/27199350-997e2566-520d-11e7-98f8-b10a9f0a3dd5.png)
![image](https://user-images.githubusercontent.com/29306451/27199375-adb3865c-520d-11e7-8020-6a058457ceef.png)

It makes it a bit more obvious that it's a choice to switch from the default weapons to one of the options.

Alternatively, you can add the default options into the actual selection groups and hide them when they're not applicable, which looks even neater, but means that you can't pre-select the defaults because each model which uses the list has a different default.

**Comment by Mad-Spy** [comment]
In terms of Lelith, I guess we'll have to wait for GW to FAQ whether or not the Impaler is extra. I haven't been able to find any other "points including wargear" model which has weapon options, so you may well be right.

**Comment by Toreador13** [comment]
I did change the weapon options to have you have it for the haemonculus. I like the look, but it works clunky since you have to go back and deselect. 

I also missed that rule the first several times. SO much to go over in so many places. Information overload!

**Comment by Mad-Spy** [comment]
@Toreador13, I was in the process of adding more issues to the bottom of the list in the opening comment. Do you want to reopen this issue (as I now can't do so), or for me to start a new one?

**Comment by Toreador13** [comment]
Add more here. I am going through right now and removing all it's. Late night typing really hurts the brain.
