### ISSUE TITLE
Grey Knights: Missing everything in Super-Heavy Detachment +3CP.

### ISSUE THREAD

**Issue by akillthegod** [BSData/wh40k-7th-edition#3915]
File/Catalogue: Imperium - Grey Knights v5

BattleScribe version: 2.01.02.89

Platform: Windows

Dropbox: No

Description: No anything in "Aviable Entries" in (Super-Heavy Detachment +3CP)

**Comment by akillthegod** [comment]
![pic](https://user-images.githubusercontent.com/17516150/27204337-e8f5983a-526d-11e7-8de3-cdd61420ea7d.png)

**Comment by GenWilhelm** [comment]
Are Grey Knights supposed to have access to any Lords of War?

**Comment by akillthegod** [comment]
My mistake. W8 for codexs
