### ISSUE TITLE
Chaos Space Marines - Havoc Missile Launcher no points cost

### ISSUE THREAD

**Issue by waynemichel** [BSData/wh40k-7th-edition#3918]
**File/Catalogue:** 

**BattleScribe version:** 2.01.02

**Platform:** Mac

**Dropbox:** Yes

**Description:** Rhino Havoc Missile Launcher shows no cost. Should be 11 points

**Comment by cartag** [comment]
It's showing properly on all of them. Redownload the data. 
![image](https://user-images.githubusercontent.com/4388344/27209156-594d6ffc-5207-11e7-9d74-947f4241e31a.png)
