### ISSUE TITLE
Dark Angels: Adding Land Speeder to Ravenwing Squadron

### ISSUE THREAD

**Issue by nillim** [BSData/wh40k-7th-edition#392]
When I add Landspeeder (2x multi-melta) to my Ravenwing Squadron the point cost is 130 instead of the correct value of 80.
From what I can see is that the Base cost of the Land Speeder is calculated twice, once upon selecting the speeder, second on selecting weapons.

**Comment by Thairne** [comment]
Did you update your files?
This should be fixed for a while already.. I cannot reproduce this with the current version, neither with the FA one nor the Troops one.
If you did update this should be fixed with the next release.
