### ISSUE TITLE
Blood Angels issues

### ISSUE THREAD

**Issue by barjed** [BSData/wh40k-7th-edition#3926]
**Imperium - Blood Angels v8** 

**BattleScribe version:** 2.01.

**Platform:** Windows/

**Dropbox:** No

**Description:** Assault Squad is priced incorrectly. The 'Space Marine w/ Flamer' is equal to the cost of the weapon only but the Jump Pack option treats it as an actual space marine. This leads to inflated costs when Jump Packs are taken for a unit equipped with Flamers. Either make the Flamer option a weapon only or include the cost of the marine in it.

In addition, selecting the Blood Angles chapter in the Force Organization hides all named Blood Angel characters.

Moreover the double Lightning Claw load-out on a Captain is priced incorrectly.

**Comment by Crowbar90** [comment]
Chapter selection works fine on my system. Blood Angels shows all Blood Angels characters, Flesh Tearers shows Gabriel Seth and Other doesn't show any special characters.

I fixed the cost for twin Lightning Claws, the only inconvenience is that the equipment must be selected twice to update the cost. For instance, if you select the first Lightning Claw it will appear as costing 9 points, while the second one will cost 6.5 points. To update the cost of the first one, you have to select it again.

**Comment by barjed** [comment]
On my side, the repro steps for the vanishing named characters are:

1. Select a Blood Angels v8 and a Vanguard Detachment and create a new roster.
2. Double click on the Select Chapter option.
3. Notice that the HQ list has no named characters.
4. Change the Select Chapter option to Other.
5. Notice that the named characters are back.

**Comment by Crowbar90** [comment]
I'm sorry but this doesn't happen on my systems, it keep working like it should. Please check you're running the latest version of BattleScribe and wait for the next repo update (which will remove the [Alpha] tag). If it still keeps doing that after the update, I'll look into it again.
