### ISSUE TITLE
DarkAngels - Interrogator Chaplain on Bike no profile

### ISSUE THREAD

**Issue by mlatewoo** [BSData/wh40k-7th-edition#3927]
**File/Catalogue:** Dark Angels 8th ed Cat

**BattleScribe version:** v2.01.02.89

**Platform:** Windows

**Dropbox:** No

**Description:** The Interrogator Chaplain on Bike does not show a profile line (M,WS,BS etc)

**Comment by amis92** [comment]
Please repost the issue in new repository: https://github.com/BSData/wh40k
