### ISSUE TITLE
Enginseer Missing

### ISSUE THREAD

**Issue by Noctis1** [BSData/wh40k-7th-edition#3932]
**File/Catalogue:Cult Mechanicus and Skitarii** 

**BattleScribe version:** 2.00.

**Platform:** Windows

**Dropbox:**No

**Description:**In both catalogues the Enginseer is missing from the HQ slot entirely. This includes the Enginseer Congregation, Grand Convication and CAD. If everyone is too busy to work on this could someone point me towards tutorial or something so i can try and resolve this issue for myself. I am using the the latest catalogues for both armies.

**Comment by Thairne** [comment]
While we dont maintain 7th anymore, if I remember right Enginseer was NOT an HQ in 7th. Neither was he in the Index Imperium, but exclusively AM.
So I don't know why you'D expect the Enginseer to be AdMech when he is in fact Guard?

**Comment by Noctis1** [comment]
The Enginseer is included in the Imperial Agents Codex as a Cult Mechanicus HQ which is where the Enginseer Congregation is. In addition the Grand Convocation lists the Enginseer and sevitors as HQ choices.

**Comment by DrTobogganMD** [comment]
As was stated, we do not maintain 7th edition anymore.  Feel free to modify your local data.  As we will not be updating this repo, your updated version will never change.
