### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by amis92** [BSData/wh40k-7th-edition#3935]
Data Developers - Please use this issue to push new releases if doing so via comment.

# Explainer

- Create an issue comment that starts with `/release` on the first line.
- Second (non-empty) line will be used as a release title/name.
- All following lines will be interpreted as a release description/body.
- Description (even if empty) will always be appended with a comparison link to the previous release, unless there is no previous release.

# How to

Add a comment with one of the following to push a release:

### For a standard release:
*given latest release v2.2.2, will create a release v2.2.3 (increases patch)*
> /release
>
> This is title of v2.3.0

### For a Chapter Approved/Big FAQ initial releases (game-wide updates):
*given latest release v2.2.2, will create a release v2.3.0 (increases minor, resets patch)*
> /release bump=minor
>
> This is title of v2.3.0

### For a new game edition:
*given latest release v2.2.2, will create a release v3.0.0 (increases major, resets minor and patch)*
> /release bump=major
>
> This is title of v3.0.0

**For this repository Major version shouldn't ever be bumped!**

**Comment by amis92** [comment]
/release tag=v7.0.0

---
[Workflow run](https://github.com/BSData/chatops/actions/runs/149841251)
**Error**: Cannot create a release without a name, please provide release name in a line after command.

**Comment by amis92** [comment]
/release tag=v7.0.0

Author updates, new version scheme, Astra Militarum new ID (sorry!)

Astra Militarum ID was re-generated because it conflicts with 8th edition.
Author contacts were removed, author URLs now direct to the Discord of BSData developers.

---
[Workflow run](https://github.com/BSData/chatops/actions/runs/149842636)
Created release:
[v7.0.0](https://github.com/BSData/wh40k-7th-edition/releases/tag/v7.0.0)
**Author updates, new version scheme, Astra Militarum new ID (sorry!)**

**Comment by DrTobogganMD** [comment]
/release

FW Chapter Fixes.

Fixed Space Marine Forgeworld Chapter selection being hidden.

---
[Workflow run](https://github.com/BSData/chatops/actions/runs/151457373)
Created release:
[v7.0.1](https://github.com/BSData/wh40k-7th-edition/releases/tag/v7.0.1)
**FW Chapter Fixes.**
