### ISSUE TITLE
Chaos Space Marines Formations

### ISSUE THREAD

**Issue by MagicMarkerz** [BSData/wh40k-7th-edition#394]
I've spent the past couple hours dabbling with it to make sure this was an actual bug, so I apologize if I missed something (probably got so wrapped up in finding it that I couldn't see the simple answer, if it's not a bug), however, as it stands, I do not see any ability to implement any of the formations for the Chaos Space Marines, specifically the Helbrute focused ones.

I think this is weird, because I took a look at the code that's listed (at least, I'm pretty sure it's the code), and I found the entries for them in there (I checked for the Mayhem Pack in specific), there just doesn't seem to be option to actually select this formation.

I apologize if this is user error and not actually a bug, but I simply cannot seem to find this.

**Comment by NebSeele** [comment]
It is a bug and design flaw (on my part) in the flagging system for the formations. I Had set them to show when the "Show Dataslates" option was tagged in the "Non Codex options" entry at the top. 

Formation detachments do not display the tab so in a pure Formation only list it will be a problem. In a Combined Arms or apocalypse list it'll display the Non Codex Options flag (of course it won't show the formations, it requires the detachment for that to work).

In the case of the Apocalypse Formations, they can only be seen in an Apoc detachment as they are Battle Formations.

I'll take the hide tag off the formations in the next update (I'm working on profile additions and consolidations so I'll most likely look at the formations themselves).

**Comment by MagicMarkerz** [comment]
Okay, cool, thank you very much for all your hard work!
