### ISSUE TITLE
Codex: Dark Eldar (2014)

### ISSUE THREAD

**Issue by Kangodo** [BSData/wh40k-7th-edition#397]
Thank you for the great work @Toreador13 

I've taken a look at it and have some points of feedback:
-The new Codices make it very easy to work with shared entry groups for most stuff like the Relics, Arcane Wargear and others. You could make your job a lot easier if you made a shared entry group and just linked to it. Especially with all those profiles!
-Archon has Huskblade for 0 points, this should be for free.
-Arcane Wargear (Archon) is missing its Webway Portal.

-The Detachment was lacking its mandatory HQ, but I fixed that.

I also told people in the dakka-thread to look for errors, which I will report in this issue.

**Comment by Toreador13** [comment]
Thanks. I started doing shared entry groups for some things, but ran into a few of the groups having differences, so I just did a quick copy and paste on a lot of them, then added and deleted what I needed. I hope to run back through it and clean some of that up.

I ran across these issues and fixed them also.
Fixed Reavers not grouping
Fixed Beastmasters razorwing having a minimum of 1
Fixed Razorwing Jetfighter not being FA
Fixed Solarite Blaster Weapon cost
Fixed Archon Huskblade cost
Fixed mandatory Archon in detachment
Fixed soulfright rule missing from Phantasm Grenade Launcher
Fixed soulfright rule missing from Torment Grenade Launcher
Added profiles for Artifacts of Cruelty
Fixed missing Webway Portal from Archane Wargear
Fixed missing Webway Portal from Succubus
Added Plasma grenade and Haywire grenade profiles

Fixed Scourge points
Fixed Scourge w / weapon points  
Fixed Scourge Solarite points  
Fixed Trueborn squad size. Min is 0 because can be all special, heavy or leader. 
Fixed Scourge Solarite weapon options.

**Comment by Kangodo** [comment]
I'll just report whatever they tell me and we could have a new release on Monday or so.
It's better to have them wait an additional day or two and wait for some more feedback.
- Scourges are wrong points (should be 16 each) 
- Trueborn should be min size 1 with 4 special and one heavy weapon. I believe right now it keeps the base 3 trueborn with splinter rifles, and doesn't let you modify or remove them. 

I would also take a look at the Solarite from Scourges, his weapons are really weird at the moment.
And the Scourge with special/Heavy weapon doesn't seem to be costed correctly.

**Comment by Toreador13** [comment]
I agree. It will be nice to get a shakeout from people. Easier for a large group to find issues, than one person. Some of the things are also a result of 2 in the morning catalogue making, so some can turn out wonky as I try to figure out how to make things work within our framework. Updated all bugs fixed above and it has been synced. I figured next time someone does a release all these fixes can go. Monday sounds like a good time, we can then close this issue thread then also.

**Comment by amis92** [comment]
@Toreador13 why oh why did you use underscores in file name? I mean it's no real problem, but I thought we agreed to comply with [Convention](https://github.com/BSData/bsdata/wiki/Catalogue-Naming-Convention). Anway good job on getting it out so fast.

**Comment by Toreador13** [comment]
We should see if we can make that a program change. It did it auto, and it was too late when I noticed. Was a bit busy getting it made ;)

**Comment by amis92** [comment]
Also while we are here @Toreador13 please make use of mentioning functionality and be more descriptive when you close issues. I do understand there are a bit many now, but we need to keep some level of consistency and keep with guidelines. May I guide you: https://github.com/BSData/bsdata/wiki/Developer-Guide#development-cycle
It be bullet no7, and also look here: https://github.com/BSData/bsdata/wiki/Simple:-Issues#mentions

cheers and still thumbs up for the huge amount of work!

**Comment by Toreador13** [comment]
Thanks, I was wondering how to do mentions and couldn't find it or figure it out, thanks!  I have been developing in a vacuum doing all the Battlescribe files, and when you are the person it's a lot different than being back over here in the 40K repo. I have been wanting to get back over here and pick up some of the old catalogues I originally had put together, but this is the first chance. Thanks, and it's a bit of a learning curve. Do we have a standard on releases? How often is too often? I have been pushing out quite a few releases as I try to balance fixing things and working in real life. But curious what you all think. Also, when do we remove an old file and move it to 6th ed? Another question, that I just notices is that a lot of our notes are over in BSdata, but they are very 40K specific. Should we move that stuff to the 40k repo?  That was one reason I wasn't finding much.

**Comment by amis92** [comment]
I don't really understand your second sentence about vacuum etc.
- About **releases** there was a discussion here: https://github.com/BSData/catalogue-development/issues/1.
- In the Space Wolves issue it was suggested to leave **old Codex** for a month, however whoever has it will still have it, and people who just downloaded data on fresh installation, probably won't want old file, so **no real reason to leave it** even for a day. Moving it simply means cut and paste into wh40k-old repository :)
- BSData wiki was meant as main wiki for organisation. Which stuff is 40k specific, may I ask? Also the general discussions now shall take place over on first link (catalogue-development) and the main generic wiki will be moved there finally ;)
