### ISSUE TITLE
Latest Randomhit Data

### ISSUE THREAD

**Issue by Jonskichov** [BSData/wh40k-7th-edition#4]
I was looking at this thread on Randomhit: http://catalogue.randomhit.org/viewtopic.php?f=5&t=383

I don't know if the data files in the zip are the most up to date, but the file naming convention is nice. Should we refresh to this set of data? @amis92 Would it overwrite anything you've done?

**Comment by amis92** [comment]
Well it might. Last time I checked they didn't update Tau since ... few releases on my part. Will go thgough some time this week.

**Comment by Jonskichov** [comment]
OK so I assume you have copies of your tau stuff :)

If I refresh from this set and you appropriately rename your files, we could do a refresh followed by you updating your tau files :)

Sound good?

**Comment by amis92** [comment]
Nah. I checked. Just leave Tau, I'll update naming appropriately. Those are two revs back. At weekend I'll revise randomhit as it seems mistakes happen (which version is newer).

Still, besides Tau, update if you feel like it. Magc8ball made good job.

Pozdrawiam,
Amadeusz Sadowski

wysłane z Lumii 820

-----Wiadomość oryginalna-----
Od: "Jon Taylor" notifications@github.com
Wysłano: ‎2014-‎04-‎09 04:29
Do: "BSData/wh40k" wh40k@noreply.github.com
DW: "Amadeusz Sadowski" amis.tau.92@gmail.com
Temat: Re: [wh40k] Latest Randomhit Data (#4)

OK so I assume you have copies of your tau stuff :)
If I refresh from this set and you appropriately rename your files, we could do a refresh followed by you updating your tau files :)
Sound good?

**Comment by Jonskichov** [comment]
Haha said I'd refresh, then just sorta wondered off... Looks like you've done it. Thanks!
