### ISSUE TITLE
Dark_Eldar_Codex_(2014).catz

### ISSUE THREAD

**Issue by drewmbailey** [BSData/wh40k-7th-edition#401]
Incubi should be 20 points rather than 22. I also noticed that in my epub version of the rules the artifacts of cruelty are listed as "one of each" of the items,  meaning that you should be able to take multiple on a single character. It sounds like this is worded differently in the print version.

**Comment by Kangodo** [comment]
The incubi is reported before, so that will be fixed.
My epub clearly says "A model may take **one** of the following" in the Wargear-section.
