### ISSUE TITLE
Bug Report: SW. Murderfang cannot be warlord. 

### ISSUE THREAD

**Issue by gwarsh41** [BSData/wh40k-7th-edition#428]
The BRB states that you must have the Character special rule to be a warlord. Murderfang does not have this rule. Currently the desktop app allows you to choose him as your warlord.

**Comment by Kangodo** [comment]
UNIT TYPE:
Vehicle (Walker, Character)

Murderfang is a character and can be Warlord. 

Ps. Even a non-character can be the warlord if you have no characters.

**Comment by ghost** [comment]
In 7th ed, they've removed the requirement for it to be the HQ choice with the highest leadership; it just has to be a "character" (unless you don't have any), which is shown on the unit type. That means you can choose Murderfang, a squad sergeant, Grimnar... or a Cyberwolf!
