### ISSUE TITLE
Deathwing entries

### ISSUE THREAD

**Issue by AstartesMkIII** [BSData/wh40k-7th-edition#431]
Hi,
I was building a Deathwing army list and I noticed there are no entries for the unit leaders..? 
Deathwing terminators and Deathwing Knights have no entries for the unit leaders/sergeants. 
Can you fix this please? :)

**Comment by Thairne** [comment]
The Knightmaster and the DW Sergeant are in tehe unit as a separate entry.
Or did you happen to load an "older" List in which they may have been removed? If thats the case, try to re-add the unit and they should appear.

**Comment by AstartesMkIII** [comment]
Hi, there is literally no entry for the Knightmaster or the DW sgt. 
When I try to create each unit it just says '4x Knights' or '4x DW terminators'..?

**Comment by Thairne** [comment]
That's weird. It should look like this:

![unbenannt](https://cloud.githubusercontent.com/assets/8590840/4605713/7436c800-51f5-11e4-8225-992cfca665b8.jpg)

Just created this from the current version of the files..

**Comment by AstartesMkIII** [comment]
It looks like this..

**Comment by Thairne** [comment]
Uhm yeah... As you can see, Knight Master (51pts) is there as is the DWT Sgt (44 pts).
So where exactly are you missing them?
