### ISSUE TITLE
Bug report: Dark_Eldar_Codex_(2014).catz 

### ISSUE THREAD

**Issue by Hypnothotep** [BSData/wh40k-7th-edition#433]
File: Dark_Eldar_Codex_(2014).catz
BattleScribe version: 1.14.07
Platform: Windows
Dropbox: No

Description:
Dark eldar Venom have Deep Strike special rule
Dark eldar Ravager can't take Splinter Racks (because it's not a transport)

**Comment by new-neon** [comment]
"Dark eldar Venom have Deep Strike special rule" - fixed at revision 8
"Dark eldar Ravager can't take Splinter Racks (because it's not a transport)" - In the codex there is no prohibition on set Splinter Racks to Ravager.
