### ISSUE TITLE
Found in Battlescribe Bug Report: Eldar Warp Hunter

### ISSUE THREAD

**Issue by Thairne** [BSData/wh40k-7th-edition#438]
"Change the value in points

The page contains relevant at the moment rules on Warp Hunter:
http://www.forgeworld.co.uk/Downloads/Product/PDF/W/Warp-Hunter.pdf"

**Comment by Viper666-Qc** [comment]
Those experimental rules are outdated...   The current rules for the warp hunter are found in the Imperial Armour Apocalypse 2013 edition.
