### ISSUE TITLE
SM Chaplain Crozius Arcanum exchange?

### ISSUE THREAD

**Issue by Stegadons** [BSData/wh40k-7th-edition#44]
I started to wonder if it should be legally possible for Chaplain to exchange Crozius Arcanum for item from Ranged Weapons or Chapter Relics list (in RAW I suppose it is possible, because Crozius is close combat weapon)

**Comment by hisop** [comment]
It is in raw acceptable to exchange it as it is a weapon however not very fluffy, i just wish power mauls had better stats.

**Comment by amis92** [comment]
How is status on that? @Stegadons , anyone? I think if it's RAW acceptable, it should be available in catalogue

**Comment by Kangodo** [comment]
It's legal, they can exchange a "melee weapon" or a "weapon". So no restriction, not even in the FAQ.
Note: BA specifically says bolter/bolt pistol instead of "weapon".

**Comment by Kangodo** [comment]
I've moved the Crozius Arcanam to the weapons-list and told people to pick two from that list.
Guess that solves this issue?
