### ISSUE TITLE
Imperial Knights Adamantine Lance Formation not allowing list to be saved

### ISSUE THREAD

**Issue by Steague** [BSData/wh40k-7th-edition#441]
Steps to reproduce:

1) Create an Imperial Knights Formation detachment
2) Add 3 knights as you wish
3) Save your list

The following error occurs: "Selection must have a category that exists" x3

The reason this happens is explained here: http://forum.battlescribe.net/viewtopic.php?f=8&t=807

The reason is that "Other" is not a valid type of unit category with formations. Setting the category for formation-chosen-knights to "No Category" allows the user to bypass the error message.

This is a known issue with BattleScribe.

**Comment by Kangodo** [comment]
This is fixed in 247782ae6397b9ce7cd6713e3a0274e8fe2e0aac
