### ISSUE TITLE
Dark Eldar codex 2014

### ISSUE THREAD

**Issue by TheBadGuy** [BSData/wh40k-7th-edition#445]
Archon can select multiple artifacts of cruelty not just one

**Comment by Kangodo** [comment]
No, it clearly says "**one** of the following"

**Comment by TheBadGuy** [comment]
Oh... oops
the entry for Archon was a little unclear.  It should've read ....can take items from melee weapons and arcane wargear. May also take one artifact of cruelty. ...
that hurts :(
