### ISSUE TITLE
"Show FW models" scheme fails to show some units.

### ISSUE THREAD

**Issue by ghost** [BSData/wh40k-7th-edition#447]
Example: 
- create Codex: Space Marines Roster in Desktop application (does not present in Android app).
- Add "Show FW models" entry to roster, 
- select Fast Attack radio button

Result: Caestus Assault Ram does not display.

Is this scheme really necessary to cater to the Forge World averse? It makes making rosters a chore for those of us who aren't prudes about Forge World.

**Comment by Toreador13** [comment]
I could not recreate this issue. Using desktop version. All three FW options show correctly when I click both. IMO it has nothing to do with being prudes. It's messy and confusing in a lot of lists, and because of the chaos of FW rules, it makes it nice to filter those out for those who don't use them, which is most likely a majority of users, especially new or young users with no access or familiarity to FW.

**Comment by NebSeele** [comment]
as much as imperials are not my strength, I did try to replicate the bug with the Caestus Assault Ram  listed above and could not replicate the bug myself. A little more information might be able to help us, such as if it happens on other catalogues with the Hidden tags used and Battlescribe version used.

As far as the "Show FW" scheme, it helps keep the initial catalogue options down for those who may not be familiar with FW rules/starting new. They may not want all the options presented when they're still learning, especially if they themselves don't have the means to run a FW army properly. It also makes it easier for us to maintain the catalogues (I think).

**Comment by senpai514** [comment]
the FW being filtered isn't related to players being prude or adverse to allowing FW units. I did it to help unclutter each force type so all users weren't flooded with tons of options for models that many don't have or will ever. HQ's alone had over 40 different choices between codex and FW before I created the FW scheme for this catalogue as it is simpler to start with the basic codex choices and then allow the end user to add in the options that he or she may want depending on what models they might have.

**Comment by Kangodo** [comment]
I cannot reproduce this either with the latest data/Battlescribe.

This change has nothing to do with FW-averse or prudeness, the reasons can be read in #376
In short: We had 45 Forge World entries which made list-building really annoying.
(22 HQ, 6 Elites, 3 Fast Attack and 14 Heavy Support.)
It was even more confusing on mobile devices where people had to keep scrolling through a lot of units they did not even own.
Hiding FW is the best way to counter this spam.
