### ISSUE TITLE
Melts bombs on Dark Angels HQ 

### ISSUE THREAD

**Issue by jfrey89** [BSData/wh40k-7th-edition#451]
I do not see the option to take melta bombs on Dark Angels HQ choices such as the Company Master or Interrogator Chaplain.

**Comment by Thairne** [comment]
True, they were missing. Will be fixed with the next release.

**Comment by amis92** [comment]
@Thairne I ask you, please do mention `closes #123/fix #234/ #345` appropriate issues in your commit descriptions, it provides an easy way of better documentation when we need to backtrack some changes or bugs etc, track progress and so on. Of course it's better that you fix things and not mention them than you not doing anything, so feel free to just help make files better if you don't feel a need to mention things. Cheers!

**Comment by Thairne** [comment]
Of course, I will remember to include that in the commits in the future, sorry!
