### ISSUE TITLE
BUG: Haemonculus Covens 

### ISSUE THREAD

**Issue by oldalder** [BSData/wh40k-7th-edition#457]
Haemonculus Covens: Selecting a raider as a dedicated transport (for wracks or grotesques) prevents you from saving the roster. When you try you get the following error message: 

“Your roster is not valid. You cannot save until the following errors are fixed:

> Selection must have a category that exists" 

Also Aberration does not have basic wargear for grotesques i.e. close combat weapon and flesh gauntlet. Aberration should also have the option to swap close combat weapon for liquefier gun for 15pts.  This issue is also present in the normal Dark Eldar codex.

**Comment by mrmagoo73** [comment]
Having the same issue with Venoms on Wracks.

Thank you

**Comment by mrmagoo73** [comment]
The formations are also doing the Same thing.  Particularly the Dark Artisan Formation.

**Comment by Toreador13** [comment]
Fixed in v6
