### ISSUE TITLE
Bug report: Codex Dark Angels - Terminator Wargear

### ISSUE THREAD

**Issue by Randobar** [BSData/wh40k-7th-edition#458]
There is currently no Option to replace the StormBolter and PowerSword of the Terminator Sergeant with a Pair of lightning claws or TH/SS although the codes allwos any model including the sergeant to do this change. All Weapons on any Model are replacable not only Bolter and Fist.

**Comment by Thairne** [comment]
Unfortunately thats not the case.
The FAQ states that "any model may replace his Storm Bolter and Powerfist...." The DWT Srg however has no Powerfist to swap out, therefore he doesn't meet the requirements and cannot swap out any weapons, as stupid as it is...

**Comment by Randobar** [comment]
Thanks for the clarrification and sorry for the issue, did not know that. But i´m also no regular DA player.

**Comment by Thairne** [comment]
It's fine. Just come back and report issues you find, we like feedback of any kind!
