### ISSUE TITLE
Eldar Warp hunter

### ISSUE THREAD

**Issue by Hypnothotep** [BSData/wh40k-7th-edition#461]
In Eldar army list provided outdated information about the Eldar Warp Hunter.
Please, change the cost of the tank and its equipment to conform with the latest rules from Forge world:
http://www.forgeworld.co.uk/Downloads/Product/PDF/W/Warp-Hunter.pdf

**Comment by amis92** [comment]
Isn't Warp Hunter actual rules in IA: Doom of Mymeara? Those you've linked are experimental.

**Comment by Thairne** [comment]
As already said in this issue:
https://github.com/BSData/wh40k/issues/438

The experimental rules are outdated and the actual rules are in IA: Apocalypse 2013.
