### ISSUE TITLE
Several Codices: New FAQ's

### ISSUE THREAD

**Issue by Kangodo** [BSData/wh40k-7th-edition#468]
This is to inform everyone that we have some new FAQ's.
Especially the Space Wolves will notice this.
-BRB
-Chaos Daemons
-Dark Eldar
-Imperial Knights
-Space Wolves
-Tau Empire

I tried to do Space Wolves myself and Blood Claw, CCW, Murderfang (finally fixed) are easy to do, but due to the wording I can't find out what group are the Terminator Weapons.
So I will leave it all to the original author since it's 5 minutes of work.

**Comment by ghost** [comment]
Space Wolves updated. Ugh.

**Comment by amis92** [comment]
Tau just got FAQ answer, nothing to change.

**Comment by NebSeele** [comment]
Daemons had a special rule inserted, otherwise nothing new there. Updated in any case

**Comment by Kangodo** [comment]
Seems everything is updated!
