### ISSUE TITLE
Space marine vehicle weapons

### ISSUE THREAD

**Issue by ghost** [BSData/wh40k-7th-edition#475]
it doesn't allow any weapons to be selected for landraiders other then a multi melta and doesn't show any weapons in the weapons profiles. Also hunter, stalker, whirlwind are missing weapons/weapon profiles

**Comment by senpai514** [comment]
@Pohok the only weapons that can be selected is the multimelta and storm bolter from the vehicle equipment list. otherwise i'll get the profiles fixed and added to all of these.

**Comment by ghost** [comment]
Sorry it been awhile since I used a landraider didn't realize each raider was a different set up. Just getting back into the game after years. But the profiles for the weapons for them are missing for the landraiders, hunter, stalker, whirlwind

**Comment by senpai514** [comment]
not missing anymore all are fixed up

**Comment by amis92** [comment]
@senpai514 please mention issue from commit message next time you close some. https://github.com/BSData/bsdata/wiki/Simple:-Issues#mentions
