### ISSUE TITLE
[Anon] Bug report: Renegades & Heretics - FW - Servants of Slaughter.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#486]
**File:** Renegades & Heretics - FW - Servants of Slaughter.catz

**BattleScribe version:** 1.14.07

**Platform:** Windows

**Dropbox:** No

**Description:** 1) Need Militia Training option in Renegade Infantry Platoons (+10 points)
2) Confused about Warlord Options, but this is probably FW's bad rules writing: BRB clearly states that your warlord cannot be chosen from an allied detachment. However, if you take a Demagogue Devotion in an allied detachment, IA:13 pg 152 states that the Demagogue must be your warlord. Confusing?

**Comment by ghost** [comment]
On Militia Training, @HoboDaveGoBOOM fixed this yesterday, with #478. You'll see it in the next release.
If you can't take a warlord in that detachment then you can't take a Demagogue Devotion. I'll add warnings for allied detachments to remind people.
