### ISSUE TITLE
Options Disappearing on iOS

### ISSUE THREAD

**Issue by MrRta1910** [BSData/wh40k-7th-edition#5]
Replace both weapon options disappear once a choice is made my units have multiple options in it

**Comment by Jonskichov** [comment]
@MrRta1910 Is this on iOS? There's a bug currently where some options disappear after selection... My bad.

There's already a fix and it's being approved by Apple at the moment. It should be out in the next few days.

**Comment by MrRta1910** [comment]
Yes on ios same with tempus and marines

**Comment by Jonskichov** [comment]
@MrRta1910 OK we'll see how it looks when the iOS update comes through. That should solve this issue.

**Comment by starcrycloud** [comment]
Hope this gets fixed:) it also happens with grey knights

**Comment by MrRta1910** [comment]
It is happening to quite a few army's I have tested

**Comment by greepa99** [comment]
With the Tau list you can't seen to be able to give the basic commander his 4pieces of war gear

**Comment by Jonskichov** [comment]
Still waiting  on Apple to approve the fix. Expecting it to be available today or tomorrow, but you never can tell...

**Comment by greepa99** [comment]
Thanks for the update

**Comment by Jonskichov** [comment]
Well waddaya know, it just got approved! Might take a while to filter down but the fix is now in the iTunes store.

I'd appreciate it if you could let me know here if your problems are resolved :)

**Comment by greepa99** [comment]
Hi John 

Have low loaded update all seems fine now 

Thanks

**Comment by amis92** [comment]
So I guess it's done. Closing.
