### ISSUE TITLE
Dark Eldar Vehicle Equipment Options

### ISSUE THREAD

**Issue by avmarchenko** [BSData/wh40k-7th-edition#502]
Dark Eldar vehicles do not have all vehicle equipment available. Specifically, the Venom cannot take any item (or items) from the Dark Eldar Vehicle Equipment list (pg 87, 2014 codex).

**Comment by Toreador13** [comment]
I checked the entries, and the Venom can take what it is suppose to. As per the Dark Eldar Vehicle Equipment list, the only things that a Venom can take are Chain-snares and Grisly trophies. All other entries are annotated with a (4) May not be taken by Venoms. Pg 87, 2014 Codex.

**Comment by avmarchenko** [comment]
My mistake. Thanks for clearing that up. Just one other question, the Ravager gets no benefit from taking splinter racks correct?

**Comment by ghost** [comment]
Not to sound like a dick but I'm sure the codex would tell you.....

**Comment by Toreador13** [comment]
That is one of those oddities. The Ravager can take splinter racks, but has no way to get splinter weapons. We left it on the list as you can buy it, but there is absolutely no point. So you are correct Alexvmarch.
