### ISSUE TITLE
Data file issues?

### ISSUE THREAD

**Issue by BjornFellhanded** [BSData/wh40k-7th-edition#512]
All of a sudden I'm getting this long error string in my BattleScribe use. I have both upgraded to the current version of Battlescribe for the desktop 1.14.07b, as well as deleting all my DataFiles and redownloading them fresh from appspot.  This error occurs on opening an already created list:

Details:
There were some problems with your data files. If you continue, this may lead to crashes or other strange behaviour.

> SW with Armored Company - 1830pts: Some selections have been removed from your roster because they no longer exist in the data file(s). If you save your roster, these changes will become permanent.
> Power Armour: Power Armour was removed from your roster because the entry does not exist in the catalogue file.
> Frag & Krak Grenades: Frag & Krak Grenades was removed from your roster because the entry does not exist in the catalogue file.
> Bolt Pistol: Bolt Pistol was removed from your roster because the entry does not exist in the catalogue file.
> Storm Shield: Storm Shield was removed from your roster because the entry does not exist in the catalogue file.
> Thunderwolf: Thunderwolf was removed from your roster because the entry does not exist in the catalogue file.
> 2x Fenrisian Wolf (16pts): Fenrisian Wolf was removed from your roster because the entry does not exist in the catalogue file.
> Thunder Hammer: Thunder Hammer was removed from your roster because the entry does not exist in the catalogue file.
> Runic Armour: Runic Armour was removed from your roster because the entry does not exist in the catalogue file.
> Servo-arm: Servo-arm was removed from your roster because the entry does not exist in the catalogue file.
> Frag & Krak Grenades: Frag & Krak Grenades was removed from your roster because the entry does not exist in the catalogue file.
> Frag & Krak Grenades: Frag & Krak Grenades was removed from your roster because the entry does not exist in the catalogue file.
> Power Armour: Power Armour was removed from your roster because the entry does not exist in the catalogue file.
> Thunderwolf: Thunderwolf was removed from your roster because the entry does not exist in the catalogue file.
> Frag & Krak Grenades: Frag & Krak Grenades was removed from your roster because the entry does not exist in the catalogue file.
> Power Armour: Power Armour was removed from your roster because the entry does not exist in the catalogue file.
> Thunderwolf: Thunderwolf was removed from your roster because the entry does not exist in the catalogue file.
> Frag & Krak Grenades: Frag & Krak Grenades was removed from your roster because the entry does not exist in the catalogue file.
> Power Armour: Power Armour was removed from your roster because the entry does not exist in the catalogue file.
> Thunderwolf: Thunderwolf was removed from your roster because the entry does not exist in the catalogue file.
> Frag & Krak Grenades: Frag & Krak Grenades was removed from your roster because the entry does not exist in the catalogue file.
> Power Armour: Power Armour was removed from your roster because the entry does not exist in the catalogue file.
> Thunderwolf: Thunderwolf was removed from your roster because the entry does not exist in the catalogue file.
> Searchlight: Searchlight was removed from your roster because the entry does not exist in the catalogue file.
> Searchlight: Searchlight was removed from your roster because the entry does not exist in the catalogue file.
>     at gui.rostereditor.RosterEditorFrame.a(Unknown Source)
>     at gui.rostereditor.RosterEditorFrame.a(Unknown Source)
>     at gui.rostereditor.RosterEditorFrame.i(Unknown Source)
>     at gui.rostereditor.RosterEditorFrame$11.actionPerformed(Unknown Source)
>     at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
>     at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2341)
>     at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
>     at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
>     at ch.randelshofer.quaqua.QuaquaButtonListener.mouseReleased(QuaquaButtonListener.java:110)
>     at java.awt.Component.processMouseEvent(Component.java:6516)
>     at javax.swing.JComponent.processMouseEvent(JComponent.java:3320)
>     at java.awt.Component.processEvent(Component.java:6281)
>     at java.awt.Container.processEvent(Container.java:2229)
>     at java.awt.Component.dispatchEventImpl(Component.java:4872)
>     at java.awt.Container.dispatchEventImpl(Container.java:2287)
>     at java.awt.Component.dispatchEvent(Component.java:4698)
>     at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
>     at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)
>     at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
>     at java.awt.Container.dispatchEventImpl(Container.java:2273)
>     at java.awt.Window.dispatchEventImpl(Window.java:2719)
>     at java.awt.Component.dispatchEvent(Component.java:4698)
>     at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:735)
>     at java.awt.EventQueue.access$200(EventQueue.java:103)
>     at java.awt.EventQueue$3.run(EventQueue.java:694)
>     at java.awt.EventQueue$3.run(EventQueue.java:692)
>     at java.security.AccessController.doPrivileged(Native Method)
>     at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
>     at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
>     at java.awt.EventQueue$4.run(EventQueue.java:708)
>     at java.awt.EventQueue$4.run(EventQueue.java:706)
>     at java.security.AccessController.doPrivileged(Native Method)
>     at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
>     at java.awt.EventQueue.dispatchEvent(EventQueue.java:705)
>     at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
>     at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
>     at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
>     at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
>     at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
>     at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

**Comment by ghost** [comment]
The file size was causing issues, particularly for mobile devices, so it was rebuilt using shared entries for the wargear.

**Comment by BjornFellhanded** [comment]
Thanks!  The warning you get is dire.  I plunged ahead and saw you just need to check off no point items now.  Is there a way to make those standard (i.e. you don't have to manually check them off)?

**Comment by ghost** [comment]
Once you've updated your roster the first time, you shouldn't need to do it again.

Sorry for the trouble! It was either that or remove the apocalypse formations.

**Comment by BjornFellhanded** [comment]
Thanks for the info!  I appreciate the hard work going into these, and the care for balance with mobile devices.
