### ISSUE TITLE
Chaos Space Marines - Terminator Heavy Weapons errors

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#530]
**File:** Chaos Space Marines - Codex.catz

**BattleScribe version:** 1.14.07

**Platform:** Windows

**Dropbox:** Yes

**Description:** Terminator Heavy weapon options are completely broken. eg:
Heavy weapon options are selectable without having the required number of models
Heavy weapon option selectable twice for each terminator - but have no sub-option to specify which heavy weapon you're actually selecting
Heavy weapons options also listed as unit level upgrades - enabling you to pay the points, but with no way of taking 2 of the same heavy weapon (10 man squad).
Terminator Champion has an option to select a heavy weapon (though again with no sub-options). Selecting this triggers validation for other terminators with multiple heavy weapons selected. (Validation for the champion with a heavy weapon always (rightly) fails.)

**Comment by NebSeele** [comment]
Moved the Heavy weapons selection to the unit itself. Awaiting further testing though to see if this resolves the issues.

**Comment by NebSeele** [comment]
nothing further has been reported about this issue. Closing
