### ISSUE TITLE
Chaos Space Marines - Marked Icon Selection

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#531]
**File:** Chaos Space Marines - Codex.catz

**BattleScribe version:** 1.14.07

**Platform:** Windows

**Dropbox:** Yes

**Description:** Marked icons are available for units without checking if the have the required mark. eg Icon of excess can be selected for Chaos Space Marines without the mark of Slaanesh.

**Comment by NebSeele** [comment]
I've looked at the bug. I've spent some time thinking how to tackle this bug. In the end, I've decided to move Marks and the Icons into shared entries, with local Entry groups linking to the shared entries. For now the mark changes will be limited to those that can take the icons.

I'll also be fixing up some cost issues on the icons at the same time. These changes will be also made to Black Legion and Crimson Slaughter.
