### ISSUE TITLE
Chaos Space Marines - Abaddon

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#533]
**File:** Chaos Space Marines - Codex.catz

**BattleScribe version:** 1.14.07

**Platform:** Windows

**Dropbox:** Yes

**Description:** Abaddon should be a prerequisite for selecting 'Chosen (troops)'

**Comment by NebSeele** [comment]
He was, but the modifier wasn't working correctly. Should be fixed in the next upload.
