### ISSUE TITLE
BUG: Haemonculus Covens Formations

### ISSUE THREAD

**Issue by oldalder** [BSData/wh40k-7th-edition#538]
Formation Grotesquerie: when you select Urian Rakarth as the haemoculus, you get an error message: Formation: Grotesqurie must have 1 or more selections of Haemonculus (minimum 1) set minSelections to 1

Formation Dark Artisan: when you try to save a roster with this foramation you get the following error message: 

> Selection must have a category that exists  
> Selection must have a category that exists  
> I’m guessing that this refers to the cronos and talos

You also get the above error message (> selection must have category that exists) when you try to save a Scalpel formation, Corpsethief Claw formation, Covenite Fleshcorpse formation and Scarlet Epicureans Formation.

**Comment by Toreador13** [comment]
Fixed in version 9.

**Comment by oldalder** [comment]
much appriciated :)
