### ISSUE TITLE
[Anon] Bug report: Codex Tau - kroot carnivore 

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#540]
**File:** Warhammer40K.gstz

**BattleScribe version:** 1.14.07

**Platform:** Windows

**Dropbox:** Yes

**Description:** In the kroot carnivore entry there when you select sniper rounds the program does not always add the extra ten points. Specifically as soon as you go over 3 units the program does not add the points and erases the points for the previous units.

**Comment by amis92** [comment]
Looks like a BattleScribe bug to me. I can't check though, I've installed the 1.15 beta. Can someone confirm it's a BS bug? @Jonskichov ?

**Comment by Kangodo** [comment]
I've tested a dozen different combinations and I cannot replicate this, point-cost is correct in all my testing.
