### ISSUE TITLE
[Anon] Bug report: Tyranids

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#542]
**File:** Warhammer40K.gstz

**BattleScribe version:** 1.14.07

**Platform:** Android

**Dropbox:** No

**Description:** Manufactorum Genestealers formation does not list "hit and run" special rule when viewing any list.

**Comment by Lynkon** [comment]
That should read "... when viewing ARMY list."

**Comment by arnestig** [comment]
This has been fixed in fae4808. Will someone close this one?

**Comment by amis92** [comment]
@arnestig to close issue directly from commit: https://help.github.com/articles/closing-issues-via-commit-messages/
