### ISSUE TITLE
Tau + Farsight Enclave

### ISSUE THREAD

**Issue by Jery77** [BSData/wh40k-7th-edition#543]
Hammerhead Gunship can only have Ion cannon, Railgun and Railgun with submunitions as primary weapon system, all others are mistake.

**Comment by thejughead** [comment]
All other option are from Imperial Armor 3 second edition

**Comment by Jery77** [comment]
then they need to be labeled with [FW]

**Comment by amis92** [comment]
I think it's racism, but what can I say. -.-
