### ISSUE TITLE
[Anon] Bug report: Space Marines - Supplement - Sentinels of Terra & Clan Raukaan

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#548]
**File:** Space Marines - Supplement - Sentinels of Terra.catz

**BattleScribe version:** 1.15.00

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** When starting a roster and selecting HQ. App drops out. Every other category works

**Comment by ghost** [comment]
I don't have any Apples to check this on. Sounds like a Battlescribe bug though; there's nothing particularly special about the file. Could someone have a look at this & maybe see if the same thing happens with Clan Raukaan?

**Comment by senpai514** [comment]
Yes the mobile device does crash for both supplements.

**Comment by ghost** [comment]
Ran them both through @amis92's BSReshaper to see if this is anything to do with the blank page field or category id issues that we were having before. There are also a bunch of units in the Shared Entry section that don't need to be; I moved them in one file, to allow a side-by-side comparison, in case they are relevant.

Something else that comes to mind regarding the HQ options: the Techmarines have incremental modifiers defining how many you can take, depending on the number of HQ choices that've been selected, but I can't see anything wrong with the way that has been set up.

**Comment by Lynkon** [comment]
I have this same issue with version 1.15.00 on Android. When selecting HQ on Sentinels of Terra as either CAD or Allied causes Battlescribe to crash.

**Comment by Lynkon** [comment]
This applies to new and previously created rosters. Does not occur with SM codex.

**Comment by ghost** [comment]
Hi @Lynkon - Whatever the issue is, it won't affect the regular SM catz, as these supplements are not related; they were built from the same source file as the Siege Assault Vanguard.

I'm afraid I'm at a dead loss here. There's nothing in these that's really any different from other catalogues.

**Comment by ghost** [comment]
Checked out the other forums & it looks like the developer is casting an eye over it to see if he can find anything.

**Comment by ptrMaglorTheRum** [comment]
Something tha can be related.
Roster editor v1.15.00

If i use the sentinels of terra, in any combination when creating new roster (combined arms, allied detachment ecc ecc)
The roster editor freeze for a moment, and nothing appears in the main window.
If i create a combined arms with codex marine, is all ok, if i use a allied detachment with sentinels, the same problem appears, but roster editor don't give exception or error signals.

But after i try to load the sentinels codex, i have to restart the editor, or it is stuck with errors.

**Comment by TDog117** [comment]
I too am having this self same issue.

**Comment by amis92** [comment]
Looks like it still happens on Android on 1.15.01, as per #564.

**Comment by Jonskichov** [comment]
Can you check if the response at this following link sounds like what you're getting?

http://battlescribe.uservoice.com/forums/55066-general/suggestions/6756037-suplement-clan-rakuaan-is-not-working-completly-br

**Comment by Jonskichov** [comment]
Note this will still be an issue on iOS until 1.15.02 is approved.

**Comment by ptrMaglorTheRum** [comment]
Sentinels of terra seems to open and work now.
I try to see if something nasty happens but for now seems resolved.

**Comment by amis92** [comment]
@Jonskichov good job, thanks!
