### ISSUE TITLE
Bug Report: Space Wolves Codex

### ISSUE THREAD

**Issue by LineR32** [BSData/wh40k-7th-edition#560]
I'm unable to create a list in Battlescribe v1.15.00 (Android) for Space Wolves. I select the space wolves catalogue but it gets stuck trying to load it and then takes me back to the rosters page after a few seconds and updates the data.

The same thing happens if I try adding them as an allied detachment to another army.

**Comment by amis92** [comment]
@LineR32 An update is available, is your issue resolved?

**Comment by LineR32** [comment]
I'm still getting the same problem with the BS update.

**Comment by amis92** [comment]
Maybe try battlescribe.uservoice.com - here we can't fix it.

**Comment by Kangodo** [comment]
@LineR32 How is the problem now?
Did you perhaps test it on a computer, it could be that the file is too big to handle for your phone.
