### ISSUE TITLE
Codex Dark Angels: Bike and Jump Pack missing from Special Issue Wargear option 

### ISSUE THREAD

**Issue by jj10566** [BSData/wh40k-7th-edition#561]
Just started using Battlescribe and I am really loving it.  I noticed that the jump pack and bike options are missing when trying to add an interrogator-chaplain / chaplain.  I suspect this is missing for the special issue wargear section in general

**Comment by Thairne** [comment]
Those options are under power armour.
This is done this way since the options are different between Power and Terminator Armour. Select the node and scroll down - e voila, Bikes and Jump Packs
