### ISSUE TITLE
Codex Dark Angels:Ravenwing Command Squad 

### ISSUE THREAD

**Issue by jj10566** [BSData/wh40k-7th-edition#562]
Ravenwing Command Squad should have the option to include up to 2 more Black Knights (to a total of 5) at 40pts each, as per FAQ

**Comment by Thairne** [comment]
Well, they already can, for quite some time now.
Any steps to reproduce where you cannot increase the number of BKs?

**Comment by jj10566** [comment]
my apologies,  i wasn't familiar with the interface well enough

**Comment by Thairne** [comment]
No worries :)
