### ISSUE TITLE
Is Tyranid file complete?

### ISSUE THREAD

**Issue by nasilnik** [BSData/wh40k-7th-edition#572]
Thanks for the speedy addition of the Tyrannocyte, Maleceptor and Toxicrene. I notice the latest update says it now includes formation from Shield of Baal: Leviathan - I've updated data, installed the newest version etc. and I still can't see all new items. I don't know if that's because the new Shield of Baal doesn't have the rules in, or if they're just missing.

In addition Zoanthropes are still limited at units of 3 and do not include the Neurothope upgrade. Mucolid spores and Sporocysts are missing. 

Are these updates that I should be seeing, or have they just been missed? If needed rules are available free from Black Library website?

**Comment by amis92** [comment]
Indeed, the Shield of Baal is done, however not yet released. I'm releasing it now :)

**Comment by Tyran272** [comment]
There is an error, the Mucolid appears as a Fast Attack choice, while actually it is a Troop choice.

**Comment by Randobar** [comment]
Fixed that yesterday
