### ISSUE TITLE
[Anon] Tyranid Mucolids should be Troops

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#574]
**File:** Tyranids - Codex.catz

**BattleScribe version:** 1.15.00

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** It's a mistake in the table organization force. The new unit, micolid spore cluster is a troop unit, no a fast atack unit. And it appers as fast attack instead off a troop unit

**Comment by Randobar** [comment]
my fault. will fix it
