### ISSUE TITLE
Adding CSM faction file

### ISSUE THREAD

**Issue by ansacs** [BSData/wh40k-7th-edition#575]
Okay, I am trying to add a new file to make use of the 7ed faction system for the CSM faction. GitHub tells me I don't have permission every time I try to submit it though. Any advise?

**Comment by efalsken** [comment]
You have to click the fork button, then make the change to your copy of the files and submit it as a pull request. https://help.github.com/articles/fork-a-repo/

If you describe what you mean about "factions", maybe someone can help you make the change.

**Comment by NebSeele** [comment]
Yeah, if you make a branch you can then make a pull request (with the changes detailed) then you should be able to make changes. Alternatively you can make a join request.

I do have to ask though what changes were you looking to make? Atm I'm (slowly, personal circumstances have made it hard to) revamping all the csm catalogues. As it stands the csm file should be pretty good to use for 7th. If you can define what you mean by faction for the purpose of the catalogues, it should help in making alterations. (Rules wise, faction == army)

**Comment by NebSeele** [comment]
Nothing new has come of this, so I'm gonna close.
