### ISSUE TITLE
Eldar - add Warlord choice

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#580]
**File:** Eldar - Codex.catz

**BattleScribe version:** 1.15.02

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** there is no option to select an autarch as my warlord for my eldar detatchments im not sure if it is the same for all hq choices

**Comment by ghost** [comment]
This would be an enhancement; the Eldar file does not yet support the Warlord designation feature. I will get to it over the holidays.
