### ISSUE TITLE
Belakor for 40K Chaos SM

### ISSUE THREAD

**Issue by arkanost** [BSData/wh40k-7th-edition#585]
Belakor is not available for the Chaos SM Codex. Per the dataslate, Belakor may be an HQ choice for both Chaos Daemons and Chaos SM.

**Comment by NebSeele** [comment]
there is an option called "Expanded options". Add it and it'll give you a couple of extra options. One of them is Show Dataslates, which'll show up Be'lakor and Cypher. The expanded options should also show Forgeworld as well.
