### ISSUE TITLE
Inquisition - Acolyte Henchmen Too many required Weapon Options 

### ISSUE THREAD

**Issue by Xianator** [BSData/wh40k-7th-edition#589]
When selecting an Acolyte henchman, they do not have a laspistol and chainsword as default items.

Acolytes with special weapon seem to require the laspistol and chainsword of an acolyte, plus two additional acolyte weapons.  The whole implementation of 'Acolyte' and 'Acolyte with special weapon' seems a bit redundant as there is no unit in the codex called "Acolyte with Special Weapon" - maybe it is easier to code them that way?

As it stands an 'Acolyte with special weapon' has too many 'required' weapons in the existing roster version.

**Comment by Kangodo** [comment]
I fixed this, it looks really weird indeed.

**Comment by Xianator** [comment]
Thanks for looking into this.  Things look a lot better.
