### ISSUE TITLE
Dark Angel - Can't edit sergeant of Deathwing terminator

### ISSUE THREAD

**Issue by LMA1980** [BSData/wh40k-7th-edition#591]
About a year ago we could edit it. Is there any reason why we can't any more?

**Comment by Thairne** [comment]
The FAQ prohibits it.
He does not have a Power Fist to swap out, so he cannot take any other wargear.

http://www.blacklibrary.com/Downloads/Product/PDF/Warhammer-40k/7th-faq/Dark_Angels_v1.1_Oct14.pdf

**Comment by LMA1980** [comment]
I was thinking he can swap is power sword for another power weapon?

**Comment by Thairne** [comment]
Nope, that option is nowhere to be found. He is unfortunately just stuck with the sword...

**Comment by LMA1980** [comment]
And for those that like to add fluff to their list can't rename the
sergeant but I guess we are a very limited number. Thanks for the precision.

**Comment by senpai514** [comment]
You can name and save models / units with the pro version of battlescribe.
That's what I have done for my 2nd company Ultramarines.

**Comment by LMA1980** [comment]
I will have to double check since I do have the pro version on both my
desktop and mobile.

Le Wed Dec 10 2014 at 6:46:13 PM, Thommy notifications@github.com a
écrit :

> You can name and save models / units with the pro version of battlescribe.
> That's what I have done for my 2nd company Ultramarines.
> 
> On Wednesday, December 10, 2014, Marc-André Landry <
> notifications@github.com>
> wrote:
> 
> > And for those that like to add fluff to their list can't rename the
> > sergeant but I guess we are a very limited number. Thanks for the
> > precision.
> > 
> > On Mon, Dec 8, 2014 at 3:01 AM, Thairne <notifications@github.com
