### ISSUE TITLE
Enhancement: Fighter Aces for all codice

### ISSUE THREAD

**Issue by Viper666-Qc** [BSData/wh40k-7th-edition#593]
With the new Death from the Skies rules found in SoB: Leviathan,  Fighter Aces is now available for every Flyer and FMC for 35pts in every codex (but not for super-heavy flyers and gargantuan creatures) 
- [x] Adepta Sororitas
- [x] Astra Militarum - codex
- [x] Astra Militarum - FW - Armoured Battle Group
- [x] Astra Militarum - FW - Death Korp of Krieg Assault Brigade
- [x] Astra Militarum - FW - Death Korp of Krieg Siege Regiment
- [x] Astra Militarum - FW - Elysian Detachment D-99
- [x] Astra Militarum - FW - Elysian
- [x] Blood Angels
- [x] Chaos Daemons
- [x] Chaos Space Marines - Codex
- [x] Chaos Space Marines - Black Legion
- [x] Chaos Space Marines - Crimson Slaughter
- [x] Dark Angels
- [x] Dark Eldar
- [x] Dark Eldar - Haemonculus Covens
- [x] Eldar Craftworlds - codex
- [x] Eldar - FW - Corsairs
- [x] Grey Knights
- [x] Harlequins (no flyers)
- [x] Inquisition
- [x] Militarum Tempestus
- [x] Necrons - codex
- [x] Necrons - FW - Dark Harvest
- [x] Orks - codex
- [x] Orks - FW - dread mob
- [x] Renegades & Heretics 
- [x] Renagades & Heretics - FW - defenders of vraks
- [x] Renagades & Heretics - FW - Servants of Decay
- [x] Renagades & Heretics - FW - servants of Slaughter
- [x] Space Marines - codex
- [x] Space Marines - FW - Siege Assault Vanguard
- [x] Space Marines - Clan Raukaan
- [x] Space Marines - Sentinels of Terra
- [x] Space Wolves
- [x] Tau - codex
- [x] Tau - Farsight Enclaves
- [x] Tyranids
- [x] Tyrants Legion - FW - Defenders of Badab

**Comment by Kangodo** [comment]
Blood Angels are done!
Maybe we could do with a list so we can check the armies that are done? But I do not know how to make that.

**Comment by NebSeele** [comment]
I have added Aces to all CSM flyers (and Daemon Princes/Be'lakor as well) barring the Dreadclaw and Kharybdis (on virtue of being drop pods and not dedicated flyers).

 I've also added them to the (as I remember) known Flying Monstrous Creatures in the Daemon codex. Admittedly I'd need to double check what are FMC's in the Daemon codex.

**Comment by senpai514** [comment]
**EDIT** _Moved catalogue/progress list into OP_ - amis92

**Comment by Thairne** [comment]
Anyone mind informing me about the rules? I'd add them happily to the DA Codex, but I don't intend on getting the SoB:Leviathan as a DA Player ;)

**Comment by Viper666-Qc** [comment]
FIGHTER ACES
Fighter Aces are upgrades for Flyers in Warhammer 40,000. In any mission that has the Fighter Aces special rule, immediately after rolling for Warlord Traits, each player can select one model with the Flyer or Flying Monstrous Creature type, and upgrade that model to be a Fighter Ace. Roll on the appropriate table for the Faction the chosen model belongs to in order to determine the special rule the Fighter Ace receives.

Using Fighter Aces in Other Missions
If you wish you can upgrade any model to a Fighter Ace in missions that do not have the Fighter Aces special rule. Using a Fighter Ace in such a mission follows exactly the same rules as for a mission that has the Fighter Ace special rule, except that the upgrade increases the points cost of the upgraded model by +35 points.

**Comment by efalsken** [comment]
Done for Tau + FSE.

**Comment by ImmobileForce** [comment]
Quick question.  Can Fighter Ace be taken by super-heavy flyers?  I've read through the Leviathan book and it says Flyers and FMCs, so I'm not sure if it includes all flyers

**Comment by senpai514** [comment]
Only those specified

**Comment by ImmobileForce** [comment]
Ok thanks, looks like I'll have to go back and remove it from a few entries

**Comment by ImmobileForce** [comment]
Because the Haemonculus Covens doesn't contain any flyers, I'd say that this Issue is resolved.
