### ISSUE TITLE
Bug report: Space Marines - Codex.catz

### ISSUE THREAD

**Issue by ddarz** [BSData/wh40k-7th-edition#597]
Hello,

There seems to be a bug with the chapter tactics and FW options for double CADs
If two or more options for chapter tactics are chosen and the Show FW is enabled, only the second CAD will get the options.

Reproduced by:
Making a new roster consisting of 2 Space marine codex CADs
1.Choosing chapter tactics and show FW on the first - no FW units show.
2. Choosing chapter tactics and show FW on the second CAD - the FW units for both CTs show for that CAD alone.

Cheers!

**Comment by senpai514** [comment]
ok I think I know how to fix, but will take me a bit since there is a lot to do to enact the fixes.
