### ISSUE TITLE
Blood Angels(2014) Devastator squad weapons, Sgt weapon choices, Capt artificer armour

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#599]
**File:** Blood Angels - Codex (2014).catz

**BattleScribe version:** 1.15.02

**Platform:** Android

**Dropbox:** No

**Description:** I know it's early days but there are errors in the new codex file for Blood angels. Devastators need to select up to 4 heavy weapons of heavy weapons, sergeant needs to be able to select multiple of some weapons ranged and melee same in other units sergeants. 
Captain needs option of artificer armour too.

**Comment by Kangodo** [comment]
> sergeant needs to be able to select multiple of some weapons ranged and melee same in other units sergeants.

What do you mean by that?
The rest is fixed btw, thank you!
