### ISSUE TITLE
[Anon] Tau  - add Kroot Anghkor Prok

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#602]
**File:** Tau - Codex.catz

**BattleScribe version:** 1.15.02

**Platform:** Windows

**Dropbox:** No

**Description:** This is not exactly a bug but i don't know how else will post this. I know that many player's have Anghkor Prok model and i have the rules for that model is this possible to add this rules to the Battlescribe?
http://trobarts.customer.netspace.net.au/anghkor-prok.pdf

**Comment by amis92** [comment]
Yeah, good idea. Only how do we mark him as? [Legacy] or [Old GW datasheet] ?

**Comment by Viper666-Qc** [comment]
Could the same be done for the Old GW datasheet rules for the Zealots in the Adepta Sororitas army?

**Comment by amis92** [comment]
That'd make a new issue :)

**Comment by efalsken** [comment]
Done.
