### ISSUE TITLE
Chaos Daemons (40K)  -  Daemon Princes psychic levels

### ISSUE THREAD

**Issue by lacyj3** [BSData/wh40k-7th-edition#608]
In the last build I have been unable to add Psychic Levels to my daemon Princes (non-khorne).

I tried CSM DP's and they still work.

**Comment by NebSeele** [comment]
might I ask what device you are using this catalogue on? the Mastery Levels are there in the catalogue on my Laptop and work correctly in Battlescribe as well. 

Edit: Lablelled as vague and question for now. I cannot duplicate the bug on PC hardware so I need more information.

**Comment by lacyj3** [comment]
I was using an Ipad2.

**Comment by NebSeele** [comment]
I've checked my own iPad to see if the issue can be duplicated, it's all working as intended here. 

Granted, Battlescribe Mobile isn't exactly friendly for single option choices such as Psyker mastery so it could be how BS Mobile is seeing the catalogue and how it operates (you need to select the radio button).

**Comment by NebSeele** [comment]
I haven't heard anything on this issue, so I'm gonna close it. any changes is likely to cause more bugs and as far as I know, it's a core layout issue, not a catalogue bug. 

If any further issues come from the Daemon DP's, feel free to re-open.
