### ISSUE TITLE
[Warhammer40k: Renegades and Heretics, Incorrect point costs

### ISSUE THREAD

**Issue by Sheeshmode** [BSData/wh40k-7th-edition#610]
The point costs of special and heavy weapons for the Renegades and Heretics Command squad are wrong. Autocannon is something around 30 - 45 points, the plasma gun is 25, the melta gun is 20, the flamer is 15.

Perhaps I have misinterpreted the layout, but would the original creator of the catalogue explain why the points are set up as they are?

I will continue reading through the catalogue to identify further discrepancies.

**Comment by ghost** [comment]
The values include 10pts for each disciple - you're not just paying for the upgrade, but the model carrying it, too.

**Comment by Sheeshmode** [comment]
That is not how the names were defined in the catalogue. They were named
based on weapons. Not Disciple with X, X being a given equipment such as a
special weapon, an icon, a banner, or as part of a heavy weapon team.

**Comment by Sheeshmode** [comment]
Furthermore, they are labelled as upgrades. Not units.

**Comment by Kangodo** [comment]
They are now named "Disciple w/ Flamer", etc and are labeled as models.
I think that is good enough?
