### ISSUE TITLE
Bug Report: Codex Space Marines - Terminator Chaplain equipment issue remains

### ISSUE THREAD

**Issue by Captain-Joystick** [BSData/wh40k-7th-edition#615]
Took a look at v103 and it seems it a still impossible to have a chaplain in terminator or armour without generating equipment errors.

The new weapon option on the crozius arm: 'none' is still regarded as a weapon, and this still triggers the 'too many weapons on crozius arm (max 0)' prompt, and worse still, is treated as a valid weapon choice when using regular power armour.

**Comment by Kangodo** [comment]
His PA-Crozius Arm also has an entry for 'None'.
I don't think he should have that.

Wouldn't it be easier to make a separate entry for a Chaplain and a Chaplain (Terminator)?
Or at least group the weapon-options in a sub-entry below their Armour-selection?

**Comment by senpai514** [comment]
I've been thinking on this some and I have a couple ideas on how to fix
this. It will be the start of my codex entry reviews to ensure accuracy and
to line up entry details in line with what I've done with for everything
else.

There are some units that are still wrong and out of date with the codex
update the other year.
