### ISSUE TITLE
[BUG] Black Legion (Latest BS and latest file)

### ISSUE THREAD

**Issue by Kangodo** [BSData/wh40k-7th-edition#621]
From Dakkadakka:

There is an error entry stating that the Black Legion codex supplement needs to add 1 weapon to hull mounted such by such not stating who or what needs it, even if you have NO VEHICLES in your entire army. The chaos Artifacts for the Black Legion also seem to be rather buggy and take up weapon slots / wargear slots for no apparent reason sometimes, and sometimes the complete opposite taking up none at all.

**Comment by NebSeele** [comment]
I will have the bug for the hull mounted weapon done in the next patch, as I found which vehicle had the problem.

As for the artifacts: I'll see what I can do in restructuring them to work in a similar manner to how Vanilla and Crimson Slaughters work.

As an aside, I'm adding the artifacts to the vanilla file as a temporary measure for the delays in the PoP, so I'll actually be putting the artifacts in, and in their correct spot too. It should allow for BL (and CS) lists to be built with FW/LoW options

(contributors note: tbh I'm considering duplicating and re-keygenning the csm catalogues once everything is done so everything is the same, though considering the lack of codex changing options, and the robustness of BS now idk why there needs to be 3 csm files now anyways)
