### ISSUE TITLE
Imperial Knights bug

### ISSUE THREAD

**Issue by lacyj3** [BSData/wh40k-7th-edition#622]
I may not be loading the formation correctly as a point on this bug report. 

If you make a knight your Warlord (when you have 3+) his stats are not showing his boosted skills.  He should be getting the Seneshal benefits. +1 BS/WS and +1 ++ Save, etc. 

If it matters I'm using two Forgeworld knights and a regular knight making my FW knight the Warlord.

**Comment by Kangodo** [comment]
You are right, every profile could use a modifier that increases the stats when they have the Warlord-option selected.
We could link the Senechal-shield to the Warlord-entry, that would be simple.
But it would require a modifier for every Knight.

**Comment by senpai514** [comment]
@Kangodo it would require a series of modifiers as the warlord would only gain that rank if there are a total of 3 knights. If a user only had 1 or 2 then they do not automatically gain that rank.

**Comment by Thairne** [comment]
Couldn't we just add an 0/1 entry labeled "Warlord" or "Seneschal" that hides the old profile and shows the new, like Space Marine Veteran Sergeants do?

**Comment by Kangodo** [comment]
@senpai514 
That is true, but let's be realistic: An army with less than three Knights can only nominate one as a Warlord if you have no other character available.
The amount of modifiers we need are just insane and we would need that for every entry.

I made some changes which really help players in their list building and profiles.
The only issue is that it upgrades a Warlord-Knight to a Seneschal when you only field one.

Maybe you could try it out and see how you both feel about the change?

**Comment by senpai514** [comment]
I think the easiest thing to do is just make sure all knights have the
knightly rank entry group and ranks can be set on demand by the user.

**Comment by Kangodo** [comment]
That might be simpler, though it could be confusing to people that don't know about the rule.

In another note: FW-Knights need +1 max modifiers for each Knight, not just Errant and Paladin.

**Comment by senpai514** [comment]
You mean for the opening allowance to be able to take a FW knight?

**Comment by Kangodo** [comment]
Yes, the wording is: "you may not have more Cerastus Knight-Acherons in your army than you have Knights of other kinds."
There should be an easier way than 6 modifiers on each FW-Knight, right?

**Comment by senpai514** [comment]
All we need is just the modifiers targeting the paladin and
errant/gerantius since there there has to be at least one of the codex
knights to begin with.

Since there are only 3 knights in any given detachment you will only ever
have one of any specific FW knight. ie you can never have 2 Acherons in the
same det.

As long as there is a paladin or errant that allows you take one each of
the other types of knights until you reach your max level of 3.

**Comment by senpai514** [comment]
Initial issue will be irrelevant for new codex no longer knightly ranks
