### ISSUE TITLE
officio assassinorum Missing formation

### ISSUE THREAD

**Issue by lacyj3** [BSData/wh40k-7th-edition#630]
Unless I'm not seeing it the Assassin formation that allows you to take all 4 is not included.  

"Assassinorum Execution Force"

**Comment by Kangodo** [comment]
Did you select 'Formation' as your Detachment type?
Because it's in there, even the Apocalypse-formation.

**Comment by lacyj3** [comment]
Thank you!

I had it selected wrong.
