### ISSUE TITLE
Bug report: Space Marines - Codex.catz 

### ISSUE THREAD

**Issue by gbruckner** [BSData/wh40k-7th-edition#634]
Tried to submit a file update through website (http://battlescribedata.appspot.com/#/repo/wh40k) but always ends in error "There was an error submitting your file. Please try again later.", so I try here. (or maybe its just me doing something wrong there as its my first time trying to submit updates)

-) For the predator there are profile links missing for the weapons it can choose.
-) Same goes for the Librarian with his Terminator Armour Ranged Weapons.
-) Also for Terminator Squad all profile links for their heavy weapons are missing - Storm Bolter is missing completely.

AFAIK this was all working in the past?

Kind regards!

**Comment by senpai514** [comment]
ill take care of the profile links.
