### ISSUE TITLE
Bug Report: Codex Space Marines - FW chapter masters and Honour Guard

### ISSUE THREAD

**Issue by ddarz** [BSData/wh40k-7th-edition#643]
Greetings,

It seems there is a bug with most FW chapter masters and other characters who, by the rules, can have an honour guard. Battlescribe throws up an error that a chapter master or Calgar are required.

Reproducible by choosing any FW chapter master or character (e.g. Lias Issodon, Sevrin Loth, etc.)

Cheers!

**Comment by senpai514** [comment]
Yes I am working on the modifiers for honor guards and for the command squad allowances.
