### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by TheDood101** [BSData/wh40k-7th-edition#647]
Can I please be added as an admin or dev so that I add the repo?

**Comment by amis92** [comment]
Um, you mean add the repo as in create new repo for some new system, or add commits to this repo (wh40k)?

**Comment by amis92** [comment]
@TheDood101 hey there, an answer please?

**Comment by amis92** [comment]
@TheDood101 I need your reaction here. If you still want to, re-apply please. I'm cleaning up organisation now, I hope you understand.
