### ISSUE TITLE
Necron Relic Limit

### ISSUE THREAD

**Issue by Ackoogin** [BSData/wh40k-7th-edition#650]
Should the Mephrit Necron Relic choices be mutually exclusive? 
"Characters with the Necrons Faction that are part of a Detachment or Formation presented in this book can select **an item** from the Relics of the War in Heaven list at the points cost shown."

**Comment by Kangodo** [comment]
I don't think so.
There is nothing that limits it to only one Relic per model.
And nobody at the big rules-fora interpreted it like that.
YMDC from Dakkadakka is usually the one I tend to follow.

When in doubt, like often with Relics, I leave it to the users themselves.
A user can always limit themselves to a single Relic per model.
But most users cannot change the file themselves to allow multiple.

**Comment by Ackoogin** [comment]
I would argue that "an item" is clearly only one, however leaving it to the users is entirely reasonable.
