### ISSUE TITLE
Khorne Berzerker profiles- supplements

### ISSUE THREAD

**Issue by Fenrisulfur** [BSData/wh40k-7th-edition#656]
The profiles for the Berzerkers are incorrect in both the Black Legion and Crimson Slaughtet supplements. The Champion should have 2 base attacks and 9 leadership and the normal Berzerkers should have an 8 leadership.

**Comment by Fenrisulfur** [comment]
Is this something that is being worked on?

**Comment by amis92** [comment]
Seems like **NebSeele** fixed it. The fix will be available in next update. You can follow updates on Twitter or Facebook: https://twitter.com/BSData https://www.facebook.com/BattleScribeData or RSS: http://battlescribedata.appspot.com/repos/feeds/wh40k.atom
