### ISSUE TITLE
Bugs and enhancement: Tyranid Codex

### ISSUE THREAD

**Issue by Viper666-Qc** [BSData/wh40k-7th-edition#664]
I got latest desktop version of Battlescribe and data files (2015-01-16)

Zoanthrope Brood: Actually, you can select a Neurothrope without the minimum 3 Zoanthropes and you don't get any error.

Malanthrope: In the Roster View, the "Spore Cloud" rule isn't listed with the other rules.

**Comment by Randobar** [comment]
Please keep dont mix seperate issues into one entry.

Solved the Spore Cloud thing, but will need to see how to handle the Neurothrope. Wanted for some time, but had no good idea how to do it in Battlescribe.
