### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by jujubeenuk** [BSData/wh40k-7th-edition#665]
working on bug fixes for CSM and necrons, streamlining file

**Comment by Kangodo** [comment]
Not sure if the Necrons are needed now ;)
They will have a new Codex in two weeks and I will redo everything.
But extra help is always welcome!

**Comment by jujubeenuk** [comment]
I know they are getting a new codes. Just waiting for it to drop myself. Im more than willing to help however I can.

**Comment by amis92** [comment]
Welcome then! `<yoda>` To accept your invitation don't forget! `</yoda>`
