### ISSUE TITLE
CM/Captain w/ bike not affecting correct detachment

### ISSUE THREAD

**Issue by athelred** [BSData/wh40k-7th-edition#672]
When an army list contains multiple detachments, the toggle that turns on bikes as troops for the SM CAD does not function as expected.

Steps to reproduce
1. Create a new roster.
2. Add two Space Marine CADs to the roster.
3. In the first CAD add a Chapter Master to the roster
4. Select the bike option for the Chapter Master.

The bike as troops option will not be enabled for the first CAD.   It will be enabled for the second CAD.  Adding a Chapter Master with bike to the second CAD works as expected.

It looks like it always applies the toggles to the last detachment, even if the last detachment is not affected by it.  If instead you add SM CAD + BA CAD you see no effect from adding the bike option.

This may be something you have to pass on to the Battle scribe dev.

**Comment by amis92** [comment]
We're not exactly associated with him, battlescribe asks to report its bugs on http://battlescribe.uservoice.com/ :) Go ahead, looks like datafiles are ok.

**Comment by senpai514** [comment]
I should be able to fix this. It is the same as the chapter tactic mechanics I had to sort out between detachments.
