### ISSUE TITLE
Bug: Space Marines

### ISSUE THREAD

**Issue by lacyj3** [BSData/wh40k-7th-edition#675]
Honor Guard is not showing their stats. 

Generic chapter master that takes the Armor of Idominutus doesn't delete the basic power armor or let you take the power armor off.   Causes his Save to be shown incorrectly.   He appears as 3+ when he should be a 2+. 

I had FW enabled if that matters.

**Comment by lacyj3** [comment]
Also,  Tactical Squad with sergeant.  

sergeant has Bolter and Power Glove
tacticals have Plasma cannon 

Army report shows Thunderhammers as a weapon in the squad when no TH selected.

**Comment by lacyj3** [comment]
Storm Eagle gunship with Melta, twin linked las cannons and Vengence launcher. 

It's not showing the Melta or las cannon weapon stats.

**Comment by senpai514** [comment]
If you find several errors/bugs please report them seperate. It is easier to track and fix and close issues that way instead of having a bunch of things all jumbled together in one.

Thanks

**Comment by lacyj3** [comment]
Ipad
