### ISSUE TITLE
Space Marines tactical squads

### ISSUE THREAD

**Issue by lacyj3** [BSData/wh40k-7th-edition#679]
Also,  Tactical Squad with sergeant.  

sergeant has Bolter and Power Fist. 
tacticals have Plasma cannon 

Army report shows Thunderhammers as a weapon in the squad when no TH selected.

**Comment by lacyj3** [comment]
Ipad

**Comment by senpai514** [comment]
could you explain a little further what the problem is? This does not tell me what is happening when something is done.

**Comment by lacyj3** [comment]
Thunder hammer is listed in the weapons section below/with Bolter, power fist etc.    even though no one in my squad has a TH.
