### ISSUE TITLE
Space Marine chapter tactics

### ISSUE THREAD

**Issue by lacyj3** [BSData/wh40k-7th-edition#680]
Unsure if this is a bug.

Choose chapter tactic Ultramarines and Crusaders are showing under Troops.  Those are Black Templar? They shouldn't appear selectable.

**Comment by senpai514** [comment]
What platform are you using BS on?

**Comment by lacyj3** [comment]
iPad and battleforged.

**Comment by senpai514** [comment]
Ive noticed that apple mobile version of the app still shows all hidden entries that you can't see in the desktop version. That is an apple app issue that doesn't let some rules and modifiers do what we want them to.
