### ISSUE TITLE
Land Raider Achilles

### ISSUE THREAD

**Issue by ghost** [BSData/wh40k-7th-edition#693]
Hello, the Land Raider Achilles according to Imperial Armor and the ForgeWorld Model has Multi-Melta side sponsons, not the Las-cannon sponsons that are showing up in the repository.  Can this be fixed?
Thank you!

**Comment by ghost** [comment]
Hello, does this being closed mean that if I update my data that this will be fixed now?

**Comment by senpai514** [comment]
Not just yet. Once the next general release is done it will be available in
user programs.

**Comment by Kangodo** [comment]
No, it means we internally fixed it.
You have to wait for the "end-user" release, which will probably be Sunday with all the Necron changes.

**Comment by ghost** [comment]
Actually I just updated my data and it is fixed.  Maybe another repository fixed it in the meantime.  Thanks for all that you.
