### ISSUE TITLE
Codex Dark Angels: Terminator Librarian Deathwing CS Issue

### ISSUE THREAD

**Issue by EClaus-doom** [BSData/wh40k-7th-edition#695]
The codex appears to allow for a Librarian in Terminator armor to take a Deathwing command squad, however, in battle scribe I get an error saying that I am not allowed to take one.  The rule states that you can take a Deathwing Command Squad for any HQ choice in Termi armor.  It states in the error that there is no max increment of 1 even though it lists terminator armor as a condition.

Here is the rule for easy reference found on Pg. 95 of the DA codex

For each HQ choice in your army equipped with Terminator armour (including Belial, but not other Deatlmin.,. Command
Squads) you may include a Deathwing Command Squad. These selections do not use  up  a Force Organisation  slot.

**Comment by Thairne** [comment]
Yeah, that's an issue I've run into. It is a bug within Battlescribe..
Reason is that Librarians are now a "Shared Entry" so i can use it in both the regular roster and the Conclave Formation.
The DWCS has a modifier that increases its max selections if a Librarian is taken - yet this modifier just doesn't apply for whatever reasons. You can actually see the modifier in the error message.

Edit: By playing around with different modifiers I managed to circumvent the issue.
