### ISSUE TITLE
Space Marine Honor Guard

### ISSUE THREAD

**Issue by lacyj3** [BSData/wh40k-7th-edition#698]
Just noticed the Chapter Champion's stat block is not listed at all.   

Relic and power weapon stats not listed either. 

Ipad.

**Comment by senpai514** [comment]
Honor guard were just updated earlier today and are pending general release.

**Comment by senpai514** [comment]
Release is now gone out I see data should be ready for updating

**Comment by senpai514** [comment]
What version of the space marine catalogue is it. Current should be v107

**Comment by lacyj3** [comment]
Hum......v105.   I just updated it as well.

**Comment by lacyj3** [comment]
Okay...updated again.....107 this time loaded and fixed issues.
