### ISSUE TITLE
Codex: Necron (2015) - WIP

### ISSUE THREAD

**Issue by Kangodo** [BSData/wh40k-7th-edition#705]
I received an ePub today, so I will start to work on it.

First I will make the entry-groups for the wargear and such, change rules and profiles.
After that I will change all the entries.
Then I will add in Formations and the Decurion-Detachment (which will probably be made a Formation).
Last thing will be the FW-entries to see how they need changing.

**Comment by jujubeenuk** [comment]
I started working on it last night as well. About half way done both the main codex.

**Comment by amis92** [comment]
Guys, collaborate. I mean, if you both edit it and then push, it's not going to end well.

Also per the Decurion Detachment, won't it fit in as nested Force Type? I don't know details, but let's try not to double up our work. If that detachment consists of some formations, make it so with nested types. The limits would then have to be set up on entries (or more likely links to shared entries), I guess. Again, please think it thoroughly. We don't have to rush it! :) 

Cheers and thanks for your commitment.

**Comment by jujubeenuk** [comment]
I'll hold off pushing mine until Kangodo updates his and then make any updates I see to his.

**Comment by Kangodo** [comment]
Yeah, I was unaware that you were already working on it.
It's nearly impossible to have two people working on something at the exact same time.
Though my work will be done quite quickly, the last week I made a lot of notes in order to plan this Codex.

@amis92 
It actually works different as anything before, but I managed to make it work.
The .GST now has Core, Command and Auxiliary-categories.
That is quite important because rumours are that more armies will have things like that.

As on the details: A Decurion works with Formations instead of Units.
You need one 'Core-Formation', 0-1 'Command-Formations' per Core and 1-10 'Auxiliary-Formations' per Core.
It's the first Force Type that has modifiers on the Categories.

**Comment by jujubeenuk** [comment]
I was starting with making sure all models and options were correct first then working on formations. But if you have formations built then I'll hold off until you get the first one posted.

**Comment by Kangodo** [comment]
I uploaded Reclamation and Judicator, so you can test it out.
The Force Type I made seems to be working perfectly.

**Comment by Kangodo** [comment]
Everything is done now.
I would really like to upload this as soon as possible, that gives me some time this weekend to fix bugs.

**Comment by jujubeenuk** [comment]
looks like it's working to me.

**Comment by Kangodo** [comment]
Good, I uploaded it so we can get some feedback in the coming day.
This thread can be closed now.
