### ISSUE TITLE
[Anon] Bug report: Tyranid Fighter Ace

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#712]
**File:** Tau - Supplement - Farsight Enclaves.catz

**BattleScribe version:** 1.15.05

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Tyranids hive fleet detachment hive tyrant doesn't have fighter ace upgrade option.

**Comment by Kangodo** [comment]
Double: #593
