### ISSUE TITLE
Space Marine Stormraven gunship 

### ISSUE THREAD

**Issue by lacyj3** [BSData/wh40k-7th-edition#718]
iPad

Taking multimelta, assault cannons and hurricane bolters.  

Hurricane bolters and Skystrike missiles not listing  their stats.  They show on the listed equipment but not showing their stats.

**Comment by lacyj3** [comment]
Also, in the Storm Wing formation.  The Stormraven is not getting 'Staffing Run' added to it.

**Comment by senpai514** [comment]
The formation has the rule data lattice listed, that is what grants the
stormraven strafing run
