### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by tehohn** [BSData/wh40k-7th-edition#72]
I can't seem to get the cat files to work in BS, the program just tells me they are corrupted. All other files are in catz format, which these files are not. not sure what I am doing wrong, so hope I can sort it out by joining.

**Comment by amis92** [comment]
Please elaborate more. Tell us what system you're on, where have you taken these files from, even BS version might be useful.

I'd gladly add you, but first let's resolve problems - we want no problems in the repo ;) Joining is equal to giving you sir push ability, which in turn means you could put some thrash up.

So, I'm ready to help. Some screenshots could be useful too (you can just drop pics in comment).

**Comment by Joshua137** [comment]
Mr. Sadowski:

I surely am cognizant of the potential damage any blunders I make could cause. Rest assured, I would not push anything to the server without being sure I knew what I was doing. 

I am using Windows 7, BattleScribe 1.14.02b, and I am indeed using the 7th edition catalog.

I guess my main question is where to put the formation in question.(Storm Wing)

Initially, I had made a separate catalog. Upon reviewing the info you sent me, it occurred to me that maybe it should go in the Space Marine catalog, although that made me a bit uncomfortable. I am trying to read the dataslate rules in light of 7th edition changes.

 As for the catalog itself, I just copy-pasted the unit data from the Space Marine Codex, added special rules, adjusted unit minimums/maximums.

When I get back home, perhaps I'll just mail you the .catz file

Joshua Johnson

**Comment by amis92** [comment]
Um, wait, I'm schizophrenic, or you are using two accounts concurrently?

If so, your account @Joshua137 is now part of BSData organisation.

Our rule for Dataslates is to include them in appropriate catalogues - which here, I guess, makes it only into Codex: Space Marines, and additionally, the units are stripped of Chapter Tactics. If we were to create cats for each new thing GW throws out, we'd surely drown :)

So, if that's not a big problem for you, maybe just clone repo and change the Space Marine cat (add the formation). I joked a little - fortunately git is stupid enough to make serious damage really hard to do - we can easily revert any change to previous version. Don't worry, upload what you've got!

**Comment by Joshua137** [comment]
Mr. Sadowski:
I believe I am just Joshua137.
I am attaching the variant of the Space Marines Codex with the Storm Wing added. It is classified as a formation. You have to add a Formation detachment with Codex: Space Marines to your list for it to show up. Right now, it is requiring you to select an additional Chapter Tactics to avoid error. I am not sure how to get around that. I am not familiar enough with GitHub to feel comfortable with uploading it myself. I do appreciate all the time you have spent helping me. This all started because I wanted to add the Storm Wing to my list. I had no idea of what was involved. I definitely do not feel comfortable mucking about in someone else's hard work.

Date: Sun, 8 Jun 2014 08:41:39 -0700

**Comment by amis92** [comment]
Well then you've replied in wrong issue, sir ;D

@tehohn may I please ask once again:

Please elaborate more. Tell us what system you're on, where have you taken these files from, even BS version might be useful.

I'd gladly add you, but first let's resolve problems - we want no problems in the repo ;) Joining is equal to giving you sir push ability, which in turn means you could put some thrash up.

So, I'm ready to help. Some screenshots could be useful too (you can just drop pics in comment).

**Comment by amis92** [comment]
Oh, and, @Joshua137 , attachments don't work on GitHub. Try out the new branch method I described earlier. As for Chapter Tactics, they'll probably need a modifier depending on force type.

**Comment by Joshua137** [comment]
What a rookie mistake!  I have just been replying to the emails, I had no idea I was actually posting on the issue thingee.
I will adjust my approach accordingly

Date: Sun, 8 Jun 2014 13:33:22 -0700

**Comment by tehohn** [comment]
... ok, I think I may have posted this in the wrong place, there seems to be more then one discussion going on here.

I finally got it sorted though, stupid sod that I am.
I noticed all other BS files I have are .catz, so I saved the cat file as .catz and tried to open it, that is probably why I got a "file corrupted" error the first time around. Then I tried again and got a "game system not found error", doh. so i get a hold of Warhammer40K.gst and now it works.

Thanx for replying in any case and the codex file is much more complete then the last one I had, so thanx again :)

I do have one other question though, is it possible to add this as a repository? So I won't have to manually update the files. I've tried adding links to the site but none of them works. I can't find a .bsi link anywhere.

**Comment by amis92** [comment]
@tehohn, well actually _your_ topic was _the_ topic, Joshua just missed his replies to another issue :)

As for links, look at http://battlescribedata.appspot.com/#/repos where you'll find .bsi.

So, am I to add you, or not? I mean, I guess not, as using auto-update isn't best practice when working as datafile developer. Just asking to be sure :)

**Comment by tehohn** [comment]
Thanx for the link, I found the .bsi
I guess for now I'm just a user, but if I start meddling with the files and have something to contribute, I'll let you guys know.
