### ISSUE TITLE
Quantum Shielding rule in C:N 2015

### ISSUE THREAD

**Issue by ninchistudios** [BSData/wh40k-7th-edition#728]
Rule as per v2 datafile is _"Quantum Shielding: +2 AV on Front and Side until the vehicle suffers a Penetrating hit."_ which is consistent with the old Quantum Shielding rule.

The rule in the 2015 codex puts the front/side AV to a fixed 13 rather than +2: _"A vehicle equipped with active quantum shielding counts all of its Front and Side Armour Values as 13."_  

While this may not be of practical difference at the moment, as all QS vehicles are 11/11/11, it may come into play if QS vs Lance weapons is FAQed or new GW/FW vehicles are released with QS and AVs other than 11.

**Comment by Kangodo** [comment]
You are right, I forgot to change the wording.
I also turned it into a Wargear-profile instead of a rule.
