### ISSUE TITLE
Dark Angels Fire Raptor Gunship

### ISSUE THREAD

**Issue by dbriscoe** [BSData/wh40k-7th-edition#729]
Hi Folks,

The experimental rules for the Dark Angels Fire Raptor Gunship are incorrect compared to current stats/costs at Forgeworld. Battle scribe lists cost as 225 and no option to add ceramics armour for 20pts.

Thanks ;0)

**Comment by senpai514** [comment]
the experimental rules are no longer used. The current datasheet for the
Fire Raptor is in IA 2 second edition.

**Comment by dbriscoe** [comment]
Many thanks! Any ideas why they left it on the website?

**Comment by amis92** [comment]
To be honest, Forge World isn't the best maintainer when it comes to these pdfs. ;)
