### ISSUE TITLE
Space Marine Deathstorm Drop Pod

### ISSUE THREAD

**Issue by lacyj3** [BSData/wh40k-7th-edition#736]
You have it at +25 points to make it Drop assault.

To make sure we are looking at the same thing.

http://www.forgeworld.co.uk/Downloads/Product/PDF/i/IA2update28AUG.pdf

IMPERIAL ARMOUR VOLUME 2
SPACE MARINES AND FORCES OF THE INQUISITION
RULES UPDATE (Version 1.3)

At the very beginning of the document it states:  Special note should be made of the Deathstorm Drop Pod, (formerly the Deathwind Drop Pod) and the inclusion of the Lucius Pattern Dreadnought Drop Pod as the rules for these have changed substantially from those previously published. Please refer to the relevant codex for any pertinant special rules or weapon profiles.

**Comment by senpai514** [comment]
That's an old pdf and no longer relevant as it's from the first edition of
IA2

All current rules are now found in Imperial Armour Volume 2 Second Edition

**Comment by lacyj3** [comment]
Do you have the link to the latest pdf update?

**Comment by Thairne** [comment]
"All current rules are now found in Imperial Armour Volume 2 Second Edition"

There are no rules in PDF, you'll have to get the book.
