### ISSUE TITLE
[Anon] Tyranids - 2,3rd dataslates, Valedor - missing

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#74]
The formations from the 2nd and 3rd dataslates and Valedor are missing.

**Comment by Randobar** [comment]
I added all formations from 2nd and 3rd Slate.

Will add Valedor Tyranid ones today. But because of #131 it is not usable yet. 

And i cannot submit it using the http://battlescribedata.appspot.com/ page.

**Comment by Randobar** [comment]
Also added the Valedor Tyranid Formations.

Will now solve #131 for the Tyranids.

**Comment by amis92** [comment]
@Randobar please try to share the file using means like Dropbox/Onedrive etc, and give us a link here.

For future work, you might be interested in [Getting started](https://github.com/BSData/bsdata/wiki#getting-started) as a member of this organisation?

As to why the site upload didn't work, I don't know.
