### ISSUE TITLE
Astra militarum tank commander

### ISSUE THREAD

**Issue by mykey84** [BSData/wh40k-7th-edition#745]
Astra militarum codex states a tank commander can choose any leman russ tank. In battlescribe there is only the option for a battle cannon tank which cant be changed, can you help me out?

**Comment by Kangodo** [comment]
I can pick 7 different tanks in my Battlescribe.
What platform are you using and such?

I did notice it has a default selection of Battle Tank for the Squadron, which I removed because it makes it easier to build a list.

**Comment by mykey84** [comment]
I am using the I pad version, it does not allow any changes in the main weapon or tank type.

**Comment by ghost** [comment]
Same for iPhone

**Comment by amis92** [comment]
Not an issue; just click on the dot to select the option you want. _(@khambatta)_
