### ISSUE TITLE
neurothrope upgrade is the wrong point value 

### ISSUE THREAD

**Issue by Getimma** [BSData/wh40k-7th-edition#758]
Battlescribe The upgrade to turn a zoanthrope into a neurothrope reads 75 points but should be 25 according to the shield of baal leviathan campaign supplement book

**Comment by amis92** [comment]
Isn't it just a model with included cost of upgrade? We often do that trick to:
1. Compress output;
2. Simplify internal conditions and modifiers.

**Comment by Randobar** [comment]
otherwise it would show the group consisting of 3 zoanthrope and 1 neurothrope, and it would be more troubling to get the size limitations working. but feel free to improve if someone has a nice way to do.

**Comment by Getimma** [comment]
Sense you can only take one neurothope per brood would it be possible to make it just a twenty five point upgrade for the brood in a similar fashion to the regeneration upgrade for other units? Not worry about the size limitation as much

**Comment by amis92** [comment]
Of course it would be possible, but at the same time it'd break the current lists and be a step back. Current state is out default policy for such upgrades which are essentially just other models altogether. We strive to provide homogenous feel of the repository, and unnecessary outbreaks are just that, unnecessary. I hope you understand. :)
