### ISSUE TITLE
Codex: Space Marine and Supplements need Correction for MKV Mortis Pattern Dreadnought 

### ISSUE THREAD

**Issue by TDog117** [BSData/wh40k-7th-edition#760]
Hey guys, I ended up getting in an argument with a friend of mine regarding the use of the MKV Mortis Pattern Dreadnought in a non DA army, so I got some clarification from FW and according to them:

In Imperial Armour 2, second edition, the entry for the MKV Mortis Pattern Dreadnought states that it is an Elites choice for - Codex Dark Angels.  It can then be taken as a Heavy support choice for - Codex Space Marines, or Tyrants Legion list as part of the Astral Claws. Any of which may take one per detachment.

Right now in BattleScribe, it's listed in the Elites section.

If someone knows who is updating the SM codex and the 2 supplements for it (Clan RauKaan and Sentinels of Terra), you mind letting them know about this ?

**Comment by senpai514** [comment]
The entry in the book does not say anything about being a heavy support choice as far as I could see.

**Comment by TDog117** [comment]
Like I said, this was the reply I got directly from Forgeworld regarding the Mark V Mortis Dreadnought.

"In Imperial Armour 2, second edition, the entry for the MKV Mortis Pattern Dreadnought states that it is an Elites choice for - Codex Dark Angels.  It can then be taken as a Heavy support choice for - Codex Space Marines, or Tyrants Legion list as part of the Astral Claws."

Quoting IA V2 2ed (Pg 171)

"A Mark V Mortis Dreadnought is an Elites choice for a Codex: Dark Angels army. It may also be taken in a Codex: Space Marines army, a Tyrant's Legion army where it may be selected as an Astral Claws Chapter Support choice as detailed in Imperial Armour Nine: The Badab War - Part One or a Space Marine Siege Assault Vanguard army as described in Imperial Armour Ten: The Badab War - Part Two, any of which may take one per detachment."

**Comment by senpai514** [comment]
Ahh ok I see. FW should really add this errata to their IA2 FAQ & errata to
make it official and to make the change in rules available to everyone in
an official format.

**Comment by TDog117** [comment]
You would think so.
But it is my understanding that I am such a rare breed to field the Mk V Mortis that I guess that none ever questioned it's placement in a codex outside of Dark Angels...

It wasn't till I used it in a game where the battle report was posted online that more than one person questioned my ability to take it, which spawned me asking FW to clarify.

**Comment by senpai514** [comment]
I know quite a few folks that have played one, myself included. And the
allowable armies paragraph does get a little long winded and a little
confusing if you rush read it, can be easy to miss things.

Originally it was DA only until the 2nd edition book opened it up to other
armies as a one per detachment only, so some folks might still be thinking
it was still DA only.
