### ISSUE TITLE
[Anon] Eldar - 2nd Lynx warning

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#761]
**File:** Eldar - Codex.catz

**BattleScribe version:** 1.15.06

**Platform:** Android

**Dropbox:** No

**Description:** Every time I attempt to add a second lynx super heavy vehicle when I've more than one lord of war slot, the app tells me I've got one too many selections.

I don't know of.any reason why I can't have two lynx in an army when I have 2+ lord of war slots available

**Comment by thefbgnome** [comment]
This also happens on 2nd Revanent Titan
