### ISSUE TITLE
Black Legion CSM

### ISSUE THREAD

**Issue by thejughead** [BSData/wh40k-7th-edition#765]
I see the Hand of Darkness for 35 points, but my digital copy says 50.  Was there an FAQ?

**Comment by NebSeele** [comment]
I have fixed the cost issue in the CSM core cat. I will have the Black legion cat fixed when I get the final version of it completed. (I'm hoping for today, but sometime over the weekend should be the timeframe, includes the Crimson Slaughter as well.)

**Comment by thejughead** [comment]
Also, a sorcerer should have access to the Hand of Darkness Relic.  Excellent work by the way.

**Comment by NebSeele** [comment]
Hand of darkness should be on the sorc, in the CSM core file and the Black Legion file that is pending a Pull Request. I'll close this once the pull request is done.
