### ISSUE TITLE
Gargantuan Squiggoth incorrect points and updgrades 

### ISSUE THREAD

**Issue by ub3rb3n** [BSData/wh40k-7th-edition#766]
Hello,

Would you be able to update the gargantuan squiggoth points according to IA:8 base cost is 600 PCs and then he has a bunch of upgrades.

Thanks,

Ben

**Comment by Kangodo** [comment]
The latest rules for the Gargantuan Squiggoth are found in Warhammer: Apocalypse from 2013.
They have a base cost of 525 and less upgrades.
