### ISSUE TITLE
Bug report: Space Marines - Codex.cat

### ISSUE THREAD

**Issue by Quinantine** [BSData/wh40k-7th-edition#77]
If you add more than one Land Raider to the roster you get the error "You can have at most 1x Land Raider in you Roster"

**Comment by peterlyberth** [comment]
The problem seems to persist.
I can not however pinpoint why.

**Comment by amis92** [comment]
I found it, probably. For some reason there are modifiers on links to Land Raider dedicated transport option in Terminator Squad/ Terminator Assault Squad. They set maxInRoster to 1. I know not any rule saying anything like that.

Oh damn, didn't see you made fresh issue (#217)
