### ISSUE TITLE
Apoc Formations for CSM, CD, R&H

### ISSUE THREAD

**Issue by amis92** [BSData/wh40k-7th-edition#771]
From #462 - just one last point left:
- [x] Add Apocalypse Battle Formations

**Comment by NebSeele** [comment]
I will be tackling this some time during the week, as well as the BL and CS overrides (had a few serious crashes that caused issues during the BL/CS updates which made it hard to continue at that time). 

Outside of the Legionnaire Warband "formation" then the Battle Formations for chaos will be done. for all files. Legionnaire Warband will get its own issue once this update's done.
