### ISSUE TITLE
Ork - Gargantuan Squiggoth points cost

### ISSUE THREAD

**Issue by ub3rb3n** [BSData/wh40k-7th-edition#774]
Hello, would you be able to update the point cost for a gargantuan squiggoth, the point cost is currently 525 which according to IA 8 it is different and has a bunch of warhead, thanks

Ben

**Comment by Kangodo** [comment]
But Apocalypse has it as 525 and contains the latest rules for the Gargantuan Squiggoth.
Unless there is a Second Edition I don't know about?

**Comment by ub3rb3n** [comment]
Is it the 40k apocalypse or forge world one, sorry having trouble locating it. Either way it also has not upgrades to it :) thanks.

**Comment by Kangodo** [comment]
The 40k Apocalypse book, it has the latest rules/upgrades for the Squiggoth.
Dakkadakka has this useful list: http://www.dakkadakka.com/wiki/en/Forge_World_and_Apocalypse_Rules_Index

**Comment by HeWhoWatches** [comment]
Good find Kangodo, we should probably add that link somewhere. How about the links section here?: https://github.com/BSData/wh40k

**Comment by amis92** [comment]
That'd fit into our wiki https://github.com/BSData/wh40k/wiki

**Comment by amis92** [comment]
Um, are we done? Or do we lack some upgrades?

**Comment by Kangodo** [comment]
No, everything is done now.
It was the second issue on this in a week so I let it open for a day.
