### ISSUE TITLE
First Birthday

### ISSUE THREAD

**Issue by amis92** [BSData/wh40k-7th-edition#780]
I'd like to hereby thank all @BSData/data-authors-gw for your effort, contribution of your valuable time and any help and attention you gave to this project.

It's exactly one year since @Jonskichov created wh40k repo.

In the name of all @BSData owners and admins
Thank you very much

**Comment by Randobar** [comment]
Just a year? feels like much more to me. Gratz to all for this great work.

**Comment by amis92** [comment]
Statistics are amazing, too. Soon we'll breach magic barrier of 1k commits and 100 releases. We've had 26 contributors and uncounted number of anonymous commits.

The repo has nearly 10k views made by 2k unique visitors.

Through this busy year including reveal of 7th edition, we changed circa 2 million lines of the valuable XML datafiles.

And what a time it was! This is 780th issue opened here, and we currently have only 30 left open. :) For issue stats, look here. http://www.issuestats.com/github/BSData/wh40k

It's an amazing job we've all done. Together, for it is our passion for hobby that drives us.

**Comment by Kangodo** [comment]
Happy birthday and good work from everyone!

Those 2k unique visitors, are those the people using the .bsi from us?
Closing issues within 18 hours is really amazing, my old CS-job would be jealous of that!

**Comment by amis92** [comment]
@Kangodo about 2k visitors:
Nope. To have such data, I'd need access to the AppSpot website itself, to which I believe access have only @Jonskichov and @dattanchu (not sure).

I've made quite a mistake: That 2k is last 2 weeks only! See here: https://github.com/BSData/wh40k/graphs/traffic

Aren't we popular?! :D
