### ISSUE TITLE
Blood Angels: Codex (2014) Adeptus Astartes Storm Wing

### ISSUE THREAD

**Issue by Flashpoint-** [BSData/wh40k-7th-edition#787]
Blood Angels: Codex (2014) v12 2014) v12.catz

BattleScribe version: 1.15.06

Platform: Android

Dropbox: Yes

Description: 
Adeptus Astartes Storm Wing formation, can you guys add this to the Blood Angels formations, or as death from the skies data sheet, to make it easier for the other armies who can use the formation as well thanks.

**Comment by senpai514** [comment]
You have to use the standard codex-space marine catalogue to take any of
the other formations.

**Comment by Flashpoint-** [comment]
Yes I found it thank you. but it's kinda ugly & hard to find for new users to add it to their armies ?

**Comment by Flashpoint-** [comment]
Yes I found it thank you. but it's kinda ugly & hard to find for new users to add it to their armies ?

**Comment by amis92** [comment]
@Flashpoint- We know and we feel you. However as easy as one-time addition would be, we'd have a uge problem with each fix. The fix'd need to be applied to every copy of said formation (which would basically mean circa 10 catalogues I guess). For now, it's a no-no.
