### ISSUE TITLE
Orks eavy armor for boyz

### ISSUE THREAD

**Issue by rickdofro** [BSData/wh40k-7th-edition#790]
Hi guys,

Just wanted to let you know that the eavy armour option for ork boys is 0 points at the moment.

Thanks!

**Comment by HeWhoWatches** [comment]
Please could you supply a little more information? I have tested on 1.15.06 on Android and the points for 'eavy armour are shown correctly. What version and OS are you using, and what steps can we use to try and reproduce the problem? The version will be listed in the "About" section, as hopefully will be the version number of the Orks data file you're using (mine shows as "Orks: Codex (2014) v42").

**Comment by rickdofro** [comment]
Sorry my bad, even though i thought i had updated i apparently still had the older version. it's working fine in the new one.

Thanks for answering and thanks for all the work on this repository in general :)

It's great

**Comment by HeWhoWatches** [comment]
No probs, thanks for replying so quickly! I'll close the bug report now.
