### ISSUE TITLE
ERROR Fortifications and Stronghold Assault

### ISSUE THREAD

**Issue by Jaystar007** [BSData/wh40k-7th-edition#798]
In BattleScribe one must buy a fortification to use Battlefield debris (such as a comms relay), but Battlefield Debris can be purchased and used separately without purchasing a fortification as per the book rules.

In the book Stronghold Assault on pg. 19 under Battlefield Debris states that, "The following list summarizes the rules for battlefield debris that can be purchased as and upgrade to a fortification, or as fortifications in their own right."

The points costs can be found on page 18

**Comment by HeWhoWatches** [comment]
Ah, OK, I think this is a case of misleading wording. When it says "battlefield debris that can be purchased as an upgrade to a fortification, or as fortifications in their own right", I believe what is meant is "here are the rules for battlefield debris, which apply to fortifications that already include sections classed as debris, and apply to any fortification upgrades that are classed as debris". An example would be the aegis defence line, the dataslate for which specifies it is of the type battlefield debris. If an aegis defence line is taken, then it uses the ”Defence Lines" rules from the battlefield debris section.

I would prefer it if you could take some items on their own (anti air guns for example), but I don't think it's allowed.

That said, I'd like to hear other people's reading of that section before we close the bug in case the majority read it differently than I do.

**Comment by Jaystar007** [comment]
After posting here I had started having some doubts so I brought it up on the theDarkCity.net forums.  

http://www.thedarkcity.net/t11841-can-i-take-a-comes-relay-by-its-self#132916

Someone else posted about this months ago.
http://www.thedarkcity.net/t11111-want-a-cheap-quadgun-or-comms-relay

**Comment by HeWhoWatches** [comment]
Good finds! ;) OK if I close this one?

**Comment by amis92** [comment]
Seems like it's now clear. Thanks for those links!

**Comment by Jaystar007** [comment]
Sure.  Thanks.

**Comment by Kangodo** [comment]
Aah, purchasing Comms Relays on their own!
That has been discussed to death on dakkadakka and the general conclusion was always that you can't do it.
Closing now.
