### ISSUE TITLE
Necron Forgeworld Tesseract Ark IA-12

### ISSUE THREAD

**Issue by lacyj3** [BSData/wh40k-7th-edition#805]
Tesseract Ark IA-12

It uses the generic description of the Quantum Shielding referring to AV-13 while the T Ark is base AV-12 with +2 from Quantum Shielding making it AV-14 with shields.

**Comment by Kangodo** [comment]
Sadly the book refers to the Codex for Quantum Shielding.
Old Quantum Shielding gave a +2.
New Quantum Shielding sets it to AV13.
Yes, that is a nerf and yes, I want FW to fix it.
But for now the Tesseract Ark is nerfed to AV13.

**Comment by lacyj3** [comment]
Well,  that stinks!
