### ISSUE TITLE
Necron ghost ark

### ISSUE THREAD

**Issue by lacyj3** [BSData/wh40k-7th-edition#808]
Ipad

Within the description of the repair ability there are typos. It has symbols at different points in the wording.

**Comment by amis92** [comment]
Can you specify what symbols are they? Or for example provide us a screenshot? (You can add it directly to comment here)

**Comment by lacyj3** [comment]
Viewing army list in HTML.
![necron ghost ark error](https://cloud.githubusercontent.com/assets/9757195/6707215/2ba3e00c-cd3b-11e4-86bd-590d96ac6699.jpg)

**Comment by lacyj3** [comment]
Created army list using my iphone 5S and view HTML file in Windows using Chrome Browser.

**Comment by amis92** [comment]
Thank you very much. If there are any more typos, please make further comments.

**Comment by Kangodo** [comment]
That was a weird one, it worked correctly for quite some time.
I had this some time ago too where all the "-s where changed to something like quote& in another file.
