### ISSUE TITLE
[Eldar Codex] Missing Weapon option for Scorpion Exarch

### ISSUE THREAD

**Issue by Morg-** [BSData/wh40k-7th-edition#81]
Currently no free option on the exarch, he does have the option to keep standard scorpion equipment for free though.

**Comment by hisop** [comment]
could you elaborate as far as i can tell he has no options that are free apart from to exchange nothing?

**Comment by Morg-** [comment]
[image: Images intégrées 1]

As far as I know, it's possible to simply upgrade a Striking Scorpion to
Exarch, keeping a scropion chainsword and shuriken pistol, for 0 points.

I am left with two choices, either taking a weapon I didn't plan on taking
or save my list and keep it invalid.

**Comment by hisop** [comment]
i see what you mean you are exactly right just give me a sec :P

**Comment by hisop** [comment]
Done Thanks for letting us know.

**Comment by Morg-** [comment]
Thanks for being reactive. What's your trade ?

**Comment by hisop** [comment]
I'm a software engineer if that's what you mean.

**Comment by Morg-** [comment]
Yes that's exactly what I meant :)

What's your specialty ?

I'm a back end specialist with full-stack skills.

2014-06-17 18:47 GMT+02:00 hisop notifications@github.com:

**Comment by hisop** [comment]
The same for me though I'm fairly back end focused :p I work in java mostly with good experience in c based languages, you?

**Comment by Morg-** [comment]
PostgreSQL, linux, C, Python, PHP and of course H5/JS/CSS3 .

So how did you end up making BattleScribe ? It must really be a "fun"
project, right ? It doesn't really pay for your investment does it ?

2014-06-18 15:06 GMT+02:00 hisop notifications@github.com:

**Comment by hisop** [comment]
I just make data files for Battlescribe and other changes for this project rather than the program itself :p. Mostly just because I found Battlescribe useful for when I'm out but it kept missing things like forge world or errors so I started making my own then stumbled onto this group project and that's where I'm up to :p
