### ISSUE TITLE
Codex : Chaos Space Marines - minimum cultists with heavy weapon selected

### ISSUE THREAD

**Issue by NicHughes** [BSData/wh40k-7th-edition#814]
I am finding that the data file imposes a minimum of 10 cultists which does not include the heavy weapon cultist - so if I select a heavy weapon I have an effective minimum of 11.

The wording of the codex is that for every 10 models in the unit one may replace its autopistol with a heavy weapon - leaving a squad with 10 members and still with the heavy weapon.

**Comment by NebSeele** [comment]
Might I ask which version you are using? If it's the most recent version, then with the Cultists in Total at 9 + the champion (who's mandatory anyways), you should be able to select a single Heavy Weapons Cultist which'll deduct from the minimum autogun/autopistol count already. 

If it is the more recent versions, the actual figure to go off here for unit size is the Cultists in total. The rest is for unit and weapon profile purposes only, which was not possible under the first layout.

**Comment by Tompa83** [comment]
I have the same issue, battlescribe 1.15.07

10 cultists (50 points) should allow for one flamer (5 points), making the total 55, but it forces me to add a heavy weapon cultist for an additional 4 points, making the squad 11 members and the point total 59. It will not allow me to reduce the "Cultist in total" number to below the starting value of 9 to compensate for this.

**Comment by senpai514** [comment]
I tested and encountered the same problem. It needs to be set so that you
can decrease the number of cultists in the squad when you hit the cultist
with heavy weapon choice.

**Comment by NicHughes** [comment]
Hi, I am using 1.15.06 of battlescribe and refreshed the data files to re-check before I raised the issue. The data file for CSM is v137.

What I am seeing is exactly as described by Tompa83 and senpai514

**Comment by NebSeele** [comment]
I see what everyone means now. I hadn't fixed the costings up on the Heavy Weapon Cultists when I moved the unit costs from the weapons back to the models in total.

I'll look at the profiles sometime later today when I have more time to make such alterations. I'll see if I can streamline the processes further. If nothing else I should be able to take the model tax off of the Heavy Weapon Cultist.

**Comment by NebSeele** [comment]
I've renamed the entries to "Cultists in Unit", "Autopistol loadout", Autogun Upgrade" and "Heavy Weapon Upgrade". I have removed the model cost tax from the heavy weapon, so the costs should be corrected now. I will have the fix uploaded soon.
