### ISSUE TITLE
Adeptus Mechanicus Skitarii

### ISSUE THREAD

**Issue by axisofentropy** [BSData/wh40k-7th-edition#819]
I wanted to experiement with potential builds, so I created a catalogue file for the new Skitarii based upon the White Dwarf pages: https://github.com/axisofentropy/wh40k/tree/skitarii_2015

Is there anything preventing us from publishing catalogue files for units that are not yet released?  If not, we could merge this branch, or even merge with the master branch.  Of course you can't make a valid detachment with these rules so far.

**Comment by Kangodo** [comment]
Well, we could merge it now, work on the data and release it next weekend!

**Comment by axisofentropy** [comment]
Ok it's pushed!  I'd appreciate any feedback.  Lots of Links leveraged.

**Comment by senpai514** [comment]
holy links within links batman!

**Comment by amis92** [comment]
@axisofentropy do you think we can push it? Or do you want to touch it up? We haven't made release since about a week, so.

**Comment by axisofentropy** [comment]
@amis92 It's pushed to the master branch and it's entirely complete for just those four units, but nobody can make a valid detachment with just those four.  So it's up to you if you want to release the file that completely describes an incomplete codex.  It might be good news for the project.

We should see more info this week so it's possible I'll get enough to finish, but the complete release will prolly happen closer to the likely Codex release date of April 11th.

**Comment by amis92** [comment]
No worries. I asked more along the lines - won't it break future releases (as we did with Space Wolves).  New Release was pushed yesterday, anyway, ppl can use it from now on (and find bugs :) ).
