### ISSUE TITLE
Codex: Space Marines Librarian options missing

### ISSUE THREAD

**Issue by AveryKess** [BSData/wh40k-7th-edition#823]
Options to take Jump Pack or Bike are missing

**Comment by senpai514** [comment]
They are there under the selection for Power Armour then under Equipment as they are only available if the librarian is equipped with power armour

**Comment by AveryKess** [comment]
ok, so it isn't exactly parallel to the Chaplain's entry

**Comment by senpai514** [comment]
Yeah I'm going to be fine tuning and trying to get everything identical as
I have the availability to simplify.
