### ISSUE TITLE
Chaos Space Marines: Legionnaire Warband

### ISSUE THREAD

**Issue by NebSeele** [BSData/wh40k-7th-edition#829]
The Legionnaire Warband Battle Formation is missing from the catalogue.

There is no simple fix to this issue within battlescribe on the base catalogue editor. The requirements for the "formation" are 1 HQ, 3 Troop units and 2 Elite units, with any Fast Attack, Heavy Support or HQ's in addition, with the only restriction being that they must all have the Vets of the Long War rule. 

Since there is no arbitary unit required for the formation, this comes off more as a detachment, which obviously wasn't around when Apoc 2013 was released. In between the Apoc book and Pandorax, all other formations at least had one arbitary requirement that limited the formation, so this is the last formation to add for chaos.

Would it be possible to add the Legionnaire Warband as a detachment instead of trying to work out some way to treat the thing as a battle formation through the use of modifiers?

**Comment by amis92** [comment]
Well, I can see it implemented as an entry with groups named 'HQ' etc, containing links to appropriate entries. For the limit "only units with VotLW" you _could_ get crazy and try to implement it by

> adding a modifier
> which would increase minSelection of VotLW upgrade
> on each unit
> on condition this unit's direct parent is the Legionnaire Warband entry

Seems crazy and I don't feel it's such an often-used entry to assert total correctness (which means I feel we can get lazy here and not implement it), but if you want, well, that's the way I see it done well.

**Comment by NebSeele** [comment]
I have an idea on how to do this now. I had to look at the Decurion stuff while working on Daemonkin to work it out but I should be able to fix this once the Khorne Daemonkin book is down to fine-tuning.

**Comment by amis92** [comment]
Yeah, but there is difference between Decurion and Warband. Decurion is a detachment, and Warband is Apoc Battle Formation. Which means, to keep consistency, it should probably be done as I suggested.

Lately I've seen some Facebook thread where guy asked about best roster builder. BattleScribe was the most popular, but the biggest problem people mentioned multiple times was inconsistency. That one time _guy with special wepon_ is counted as a model, other times as an upgrade and doesn't count towards limit, and so on.

I want to keep the bar high. :)

**Comment by amis92** [comment]
Now I read again, I may have misunderstood. So you probably didn't mean to implement it Decurion-like way.

**Comment by NebSeele** [comment]
I worded it wrongly partly because I was under time restrictions due to RL committments, so my apologies there. 

What I meant was the usage of the units in the shared entries section of the catalogue editor, then creating the main "Legionnaire Warband" Formation. Use the Entry Group options inside the entries as the dividers for HQ, Troop etc, then linking the individual units across.

The reason I used Decurion as the example was because I was looking at how the necron file/decurion detachment worked as a basis for the Bloodhost Detachment. I actually feel a bit stupid after looking at it now because I was approaching this Battle Formation wrongly the whole time.

Either way, once Khorne Daemonkin is done I will be re-tweaking some spots and then finishing off the Warband.

**Comment by amis92** [comment]
It's 3 months since opened.

**Comment by pretzalcohuatl** [comment]
maybe I'll get to it tomorrow?

**Comment by amis92** [comment]
That'd be awesome, methinks.

**Comment by cartag** [comment]
My thoughts on this: why not just add a checkbox like the one to show/hide FW models.

**Comment by NebSeele** [comment]
We need to get the Battle Formation into the catalogue first.

Alot of the issue of implementing this is largely due to my lack of catalogue layout knowledge at the time (retaining the original backend layout whilst expanding on it), which I only learned the streamlined and more effecient methods by writing the Khorne Daemonkin file, and looking at the other codices around the time, especially the Necron catalogue. 

Whilst I have been trying to convert the entries to shared entries to eliminate duplication and to better facilitate the slot only restriction requirements of the Warband (over actual unit restrictions), I haven't had too much time to do such a change, much less the change that requires MORE work than the original overhaul to begin with. 

As you (cartag) are planning on converting the entries over to match the Khorne Daemonkin layout (as mentioned in #1387), hopefully the issue can be closed soon. 
I admittedly didn't think it would take this long after the original overhaul (or even the time creep of the original overhaul to begin with) to really see any progress on this issue. 

As for the checkbox: I  was thinking about it as I have a local meta that does allow for the Battle Formations in standard games, however it's a bit hairy as they are Apocalypse based formations. 

Edit: slight changes to sentences.

**Comment by NebSeele** [comment]
Ok, the entry that'll be used for the Battle Formation has been added, as well as the links for all non-special character HQ's and all Codex related entries for each slot have been added. So.. in saying that:

Should the special characters be added for options sake?
Should Forgeworld units be added to the formation knowing that the book has its own separate rules from FW for many of the same items?

**Comment by hisop** [comment]
@cartag @amis92 is this finished then? (been trying to trim down the bug backlog)
