### ISSUE TITLE
Necron Nightmare Shroud and Phase Shifter on Command Barge

### ISSUE THREAD

**Issue by lacyj3** [BSData/wh40k-7th-edition#830]
Iphone

Overlord on a Command Barge w/Gauss cannons

Took "Nightmare Shroud" and phase shifter

Overlord save showing 3+ without 4++:  Should be 2+/4++

**Comment by Kangodo** [comment]
Correct, I added this to the (Over)lord and forgot the CCB.
Will correct this when I can.

**Comment by Kangodo** [comment]
Thank you for doing this, I am finishing my internship so stuff like bsdata is on a low at the moment.
