### ISSUE TITLE
Codex: Khorne Daemonkin

### ISSUE THREAD

**Issue by NebSeele** [BSData/wh40k-7th-edition#831]
Placeholder for Daemonkin of Khorne.

I have begun work on the catalogue, I will work on it between now and saturday. The basic structure is already complete. I'll aim to have at least the unit entries done by the codex launch.

**Comment by amis92** [comment]
No need to hurry. We don't really have any obligations :D

**Comment by senpai514** [comment]
Will still be done way before the other builder as they have to wait before
publishing

**Comment by NebSeele** [comment]
I have released the earliest usable version of the catalogue. It has basic entries to make a CAD, however it's lacking the in-depth profiles and rules, as well as the formations outside of Slaughtercult. This means that the Bloodhost Detachment cannot be made yet.

I will continue to work on it over the weekend.

**Comment by NebSeele** [comment]
Formations are now added, the profiles from in the book (and the rules have well) are also in. Links and entries do need to be tidies up, as well as the war machine auxillary needs to be done, but the catalogue should be usable. Expect bugs.

As for the Blood Host detachment: I am going to need someone who knows their way around the Game System Editor to implement it. I tried to get it working but was having issues with the editor not accepting modifiers, keeping it in line with already existing categories etc... In this case it's better to leave well enough alone

**Comment by amis92** [comment]
@NebSeele what exactly have you had problems with? You mean GST editor failed to behave correctly, or you weren't sure how to get these things correctly?

**Comment by NebSeele** [comment]
a lil bit of both. How to correctly make sure the Blood Host's Core/Command/Aux worked as intended and the GST giving out errors when trying to add modifiers about "must have parent" if the Decurion ones are used/linked to the Blood Host entries

**Comment by NebSeele** [comment]
No longer needed at this point. Closing
