### ISSUE TITLE
Page Breaks when printing

### ISSUE THREAD

**Issue by lacyj3** [BSData/wh40k-7th-edition#832]
Can we have Page breaks when printing?

That way it doesn't split a unit/rules from one page to the other?

As a select able option as it would use more paper technically?

**Comment by amis92** [comment]
Unfortunately this is a request for BattleScribe authors, which are distinct from BSData (our organisation) - we're unaffiliated.

However such requests have their place: http://battlescribe.uservoice.com/forums/55066-general

Actually, I think I saw similar request: http://battlescribe.uservoice.com/forums/55066-general/suggestions/3251997-allow-profile-rules-to-be-printed-on-separate-pa

If it's not, just share this idea there.
