### ISSUE TITLE
Imperial Armour Vraks

### ISSUE THREAD

**Issue by ansacs** [BSData/wh40k-7th-edition#833]
These are the files to add the Vraks Detachments, Renegades and Heretics Army List, and Death Korps of Krieg Siege List. Feel free to change, add, or whatever you want with these files.

https://www.dropbox.com/sh/q9x7ezzzlljrhgy/AACPm2p91rcxdR1rU9yX0Qm-a?dl=0

**Comment by amis92** [comment]
I don't know much about these lists, can someone else take a look here?

**Comment by NebSeele** [comment]
I'll have a look at the Vraks renegades files in short order, just trying to get Khorne Daemonkin running smoothly first.

**Comment by amis92** [comment]
Thanks :)

**Comment by Valathor** [comment]
Any news? I am really interested! :)

**Comment by NebSeele** [comment]
I will take a look into the Vraks files over the weekend. While Khorne Daemonkin still needs work it doesn't seem to have any critical (at the time of posting) issues with it. Allows me to go over the other chaos files and see if they are in order.

**Comment by Valathor** [comment]
Thanks! :D

**Comment by NebSeele** [comment]
The renegades of Vraks catalogue looks good to go (being mostly based off the IA:13 catalogue and army lists helps). I cannot say with the DKoK catalogue, but it looks largely complete at a glance.

I will put the detachments into the main catalogue, and upload the Renegades under Renegades and Heretics: Renegades of Vraks (saved as the .cat file in addition). Should be up shortly.

**Comment by amis92** [comment]
Hey @NebSeele look at #929 - khambatta sent me some files. Take a look and make your judgement which files are better. Also it seems he fixed some bugs in DKoK and the detachments too.
