### ISSUE TITLE
FW: Experimental Rules for the Xiphon Pattern Interceptor

### ISSUE THREAD

**Issue by Thairne** [BSData/wh40k-7th-edition#834]
To be found here:

www.forgeworld.co.uk/Downloads/Product/PDF/X/Xiphon_40K.pdf
- [x] Dark Angels
- [x] Space Marines
- [x] Space Wolves
- [x] Blood Angels
- [x] Grey Knights

**Comment by senpai514** [comment]
Dont forget your Fighter Ace entry as well.

**Comment by senpai514** [comment]
@amis92 last one for Grey Knights is all yours, one of your catalogues. ;)
