### ISSUE TITLE
daemonkin cultists 

### ISSUE THREAD

**Issue by thraxdown** [BSData/wh40k-7th-edition#848]
a minimum squad of cultists is 58. I think the 5 point champion tax is added in to the unit cost.

**Comment by NebSeele** [comment]
The champion taxes aren't accounted for in some entries. I'll be getting onto them.

**Comment by thejughead** [comment]
Are you adding the Blood Host detachment as an army type? Also, the Daemon Prince has no gifts that can be added.

**Comment by thejughead** [comment]
Never mind I read your notes.  I want my Umpa loompa NOW! :)

**Comment by NebSeele** [comment]
I've made the correct change to champion cultists cost, should have it up soon.
