### ISSUE TITLE
[Anon] Militarum Tempestus troop choice wrong point cost

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#85]
The troop choice in the Militarum Tempestus codex is innacurate on battlescribe. It shows 82 points, but it should be 70 points (according to the codex). Thank you!

**Comment by ghost** [comment]
This looks to be a bug in Battlescribe. When you select the unit, it shows 70 points (4x12, +22)... @Jonskichov Any ideas?
