### ISSUE TITLE
[Codex Daemonkin] Chaos Bikers missing from CAD

### ISSUE THREAD

**Issue by thejughead** [BSData/wh40k-7th-edition#864]
Chaos Bikers missing from Fast Attack slot in the  CAD.

**Comment by NebSeele** [comment]
Am I able to find out the catalogue you are using? just for validity sake (it works on my end, however I did a bugfix a few days ago that may not have hit public release).

**Comment by thejughead** [comment]
Version 9 .  I just updated the files, but it hasn't moved from that version all week. :(

**Comment by NebSeele** [comment]
Version 9 seems to be the general release which a few bugs have come in for. I missed the last general release by half a day when I put out version 11 with the fix in the first place (and just released version 12). 

Thanks for supplying the catalogue version though, considering this is still an early stage catalogue release (and considering I was out to get it up asap as well), there is always going to be bugs. 

The version number helps with fixing bugs and identifying bugs, hence why I tend to ask, so again thanks :)
