### ISSUE TITLE
Bug - Khorne Daemonkind Slaughtercult incorrect minimums

### ISSUE THREAD

**Issue by zev-reetu83** [BSData/wh40k-7th-edition#868]
Currently, a Slaughtercult requires 2 cultist units. In the codex however, a Slaughtercult can have 0-2 units of cultists

**Comment by NebSeele** [comment]
Is it possible to get the version of the catalogue you are using? I did an update to the internal Github that actually corrected this bug so I am just curious if the bug is still present in the Daemonkin file.

**Comment by chamberlin-dev** [comment]
This is Zev, newer account. I'm not really sure what you mean as I'm brand new to scribe, but I'm using v.9 for Daemonkind if that helps?

**Comment by NebSeele** [comment]
Yeah, that does help. The main appspot page for bsdata had a general release prior to my fixes for Daemonkin. The version that the github contributors would have access to is version 11. I'll put a note in the next upload to close the issue, as I'll double check the slaughtercult entry for more bugs.
