### ISSUE TITLE
Bug Report:  Chaos Space Marines Elite Terminators

### ISSUE THREAD

**Issue by lacyj3** [BSData/wh40k-7th-edition#883]
ipad/iphone

Elite Terminators

Mark of Nurgle, combi-melta and power fist.

Save shows 2+ without the 5++ on the stat line.

**Comment by NebSeele** [comment]
The profile for the terminators were originally written without the invunerable save in the profile. I'll have it fixed in the next update.

**Comment by lacyj3** [comment]
This one is the Chaos Marine book......not Daemonkin for the record.   Unless both had the problem.

**Comment by NebSeele** [comment]
Daemonkin should have the 5++ as I put the invunerable saves in the profile when the wargear/special rule awarding it is standard to the model/unit. The CSM book not having doesn't surprise me and I probably would be expecting more from the older, largely un-altered entries in that book.

**Comment by lacyj3** [comment]
I've considering editing these too....to make them more Verbose/Descriptive for my personal use.  For special rules, adding the Blood Tithe, etc.
