### ISSUE TITLE
Bug report: Chaos - Khorne Daemonkin.catz Herald

### ISSUE THREAD

**Issue by lacyj3** [BSData/wh40k-7th-edition#884]
iphone

Herald 

Weapon options missing.

**Comment by NebSeele** [comment]
Herald should have the weapon options, so it's strange that  it does not. I can confirm there were weapon options available, if at least on the desktop and the catalogue editor.

**Comment by lacyj3** [comment]
This was my mistake.....they are there.  Apologies.
 Close this one.
