### ISSUE TITLE
Codex: Khorne Daemonkin Version 14 

### ISSUE THREAD

**Issue by thejughead** [BSData/wh40k-7th-edition#886]
Herald has no gift options (i.e. Juggernaught)

Possessed have no Rhino option

Blood Throne has the option to take a Juggernaught mount from gifts.

HQ options should have a "Warlord" designation.

Great job so far!

**Comment by thejughead** [comment]
Forgot to add:

Taking anything other than a Hellblade on a Herald produces an error.

**Comment by thejughead** [comment]
Lastly,

The formation listing is missing Lord of Slaughter and War Engine formations.

Again thanks, it is coming along.

**Comment by thejughead** [comment]
Sorry for the spam, I'm putting them in as I see them :)

Herald cannot take Kor'lath or Goredrinker

**Comment by NebSeele** [comment]
I fixed the herald taking the juggernaut bug in an internal version. While I have added them as such in a fix, I'm actually hesitant to call the Lords of Slaughter and War Engines as viable formations as the codex doesn't list them outside the detachment. Should have the rest fixed.

**Comment by thejughead** [comment]
True no dtaaslate for them. Also, same error for a lord taking any artefact says its 1 too many.

**Comment by NebSeele** [comment]
Is that error for taking multiple artefacts or just the one?
