### ISSUE TITLE
Imperial Knights Detachment List Error

### ISSUE THREAD

**Issue by Flashpoint-** [BSData/wh40k-7th-edition#887]
Hello,
Found Error in Imperial knight list building.
You may take one of each individual Cerastus Knights types without the need of a Plaladin, Errant or Character Knights type. Same with the Questoris Knights individual types.
You may not have 2 of the same individual type of Cerastus or Questoris Knights in the Primary Knight detachment basically.
Then be aware of the army wide part of the rules you can have 2 of the same Cerastus or Questoris individual type Knights in an army not a single detachment, but must add a Paladin, Errant or Character Knight type per multipule duplicating individual Cerastus or Questoris Knights types in the army.
The Rule is :
Using the Cerastus Knight-Acheron in your army in games of Warhammer 40,000 Codex:  Imperial Knights:  Cerastus Knight-Acherons may be chosen as part of a  Codex: Imperial Knights  army as you would other types of Knight. However, owing to their rarity in the 41st Millennium, you may not have more Cerastus Knight-Acherons in your army than you have Knights of other kinds.

**Comment by senpai514** [comment]
Hmmm. Let me look into this a little.

**Comment by Flashpoint-** [comment]
Follow up trying to make it easier to understand the Cerastus Knight Rules of how many per detachment / Army
If you read each individual type of Cerastus Knight rules. It spells out the full name of the Knight, it doesn't say Cerastus type or class it's specific to each individual knight full name. Allowing you to have more than one Cerastus knight in your first detachment, you can not repeat the same individual Type / Class / Full Named Cerastus knight in your first detachment.
Then the army wide rule kicks in when using more than one detachment of Cerastus Knights in your army list. Only then can you repeat full named Cerastus Knights only but only after putting a different Class / Type / Full named Knight per repeated Cerastus Knights.
hope that helps ?

**Comment by Kangodo** [comment]
Yup, we were talking about that too in #622 
Perhaps it might just be wiser to remove the maximum until we have a good solution and for the moment add a Rule to it.
I prefer to 'forget' a limitation over having a limitation that is incorrect.

**Comment by senpai514** [comment]
I am waiting on a response from FW for a few questions on the knights in relation to the new codex where this particular issue will really be relevant due to the larger knight detachment size.

**Comment by senpai514** [comment]
At this time FW knights only have a mix in force of 2 limit since that is the highest any one can be fielded in a household detachment. Players should have the datasheets and know the proper quantities and limits for items fielded.  Should be good to go when I finish the Release within the day.
