### ISSUE TITLE
Bug report: Chaos - Khorne Daemonkin.catz  "Chaos Lord"

### ISSUE THREAD

**Issue by lacyj3** [BSData/wh40k-7th-edition#888]
Ipad/iphone

At work....no codex in front of me......think these are correct.

Mark of Khorne missing.

Blood for the Blood God! missing

Sigil of Corruption not showing the 4++ on the stat line

**Comment by NebSeele** [comment]
Will have fixed in the next update, though not sure how to apply the Sigil's upgrade as the core profile is usually fixed (can use modifiers but those are last on the things that need to be done atm).

**Comment by lacyj3** [comment]
V 17

Chaos Lord is still missing a lot of his special rules.
