### ISSUE TITLE
Bug report: Chaos - Khorne Daemonkin.catz "Chaos Terminators"

### ISSUE THREAD

**Issue by lacyj3** [BSData/wh40k-7th-edition#889]
ipad/iphone

The Combi-weapons on the standard terminators.  You can select the Combi-Weapon for 5pts, but can't select the specific weapon afterwards.

Of note:  The Terminator Champion works correctly.  Its the regular guys that don't have that last step.

**Comment by NebSeele** [comment]
I haven't fully worked the profile linkings (to which this falls under) as the focus has been on major bug fixes that come up here. I will fix it sometime in the next couple of days.
