### ISSUE TITLE
Bug report: Chaos - Khorne Daemonkin.catz "Daemon Prince"

### ISSUE THREAD

**Issue by lacyj3** [BSData/wh40k-7th-edition#890]
ipad/iphone

The Blood-forged Armour if chosen is not updating his Armor Save.    The 5++ is there but not the 3+

Should he also have the "Mark of Khorne"?  (Codex not in front of me)  He is daemon of Khorne for sure, but mark as well?

**Comment by NebSeele** [comment]
The Daemon Prince has always been Daemon of Khorne only, even in the CSM codex. 

 With profiles, a modifier can possibly be done later down the track, however the profile itself usually displayed is the models base profile (before purchases) and doesn't at present, cover the upgrades.

 It'll be some time before I get to the armour updatings.
