### ISSUE TITLE
Chaos Daemonkin Khorne - Typos

### ISSUE THREAD

**Issue by lacyj3** [BSData/wh40k-7th-edition#891]
Typos showing up when viewing roster thru HTML.

Section Rules: Blood for the Blood God!

â€¢ A unit containing this rule either being completely destroyed, or completely destroying an enemy unit.
â€¢ A Character with this rule is either slain, or slays an enemy character in a challenge.

**Comment by NebSeele** [comment]
If it's on a smartphone, it's likely that the app isn't rendering the dot point correctly. Really can't do much about that except remove the dot points.
