### ISSUE TITLE
Chaos Daemonkin Khorne - Fearless 

### ISSUE THREAD

**Issue by lacyj3** [BSData/wh40k-7th-edition#892]
No longer suffer Instability.  

Add Fearless to Daemons or is that part of the "Daemon of Khorne" rule?

Add to the DoK rule or as a special rule to daemons.

**Comment by NebSeele** [comment]
Will have that fixed in the next update.

**Comment by NebSeele** [comment]
Just checking through it now, all the Codex: Daemon units have Fearless in addition to DoK in their profile, I am not sure why it's not coming up. Which units don't have Fearless but are meant to?
