### ISSUE TITLE
Bug #672 has been marked as fixed, but is still broken

### ISSUE THREAD

**Issue by athelred** [BSData/wh40k-7th-edition#900]
Bug #672 has been marked as fixed, but is still broken in current versions of the files.  I have included the text of the bug below for reference.  I am sure there is a way to reopen bugs, but I'l be darned if I can find it.

When an army list contains multiple detachments, the toggle that turns on bikes as troops for the SM CAD does not function as expected.

Steps to reproduce

Create a new roster.
Add two Space Marine CADs to the roster.
In the first CAD add a Chapter Master to the roster
Select the bike option for the Chapter Master.
The bike as troops option will not be enabled for the first CAD. It will be enabled for the second CAD. Adding a Chapter Master with bike to the second CAD works as expected.

It looks like it always applies the toggles to the last detachment, even if the last detachment is not affected by it. If instead you add SM CAD + BA CAD you see no effect from adding the bike option

**Comment by senpai514** [comment]
its actually only partially broken (yeah weird right). I did some playing around and learned some interesting tidbits on how the reactions have been going.  For whatever reason modifiers for PARENT FORCE appear to work wrong but that is only on the first time it is selected in a roster and this also applies to chapter tactics selections. When a selection is made to show something that was hidden before at first it only shows to a second CAD if the user has one up at the same time, but if that same roster is saved and reloaded then the shown options appear correctly in the appropriate force.

Some workarounds the user can do is:
first build roster with only the one CAD and then after edit forces and add the second CAD.
save roster and then immediately reload

either way it appears that its is not a catalogue issue but how battlescribe initially reacts to hide/show options. There is nothing further I can do at my level.

@amis92 maybe @Jonskichov knows why this is happening?

**Comment by amis92** [comment]
Yeah.. I have no idea. Posibbly worth opening bug suggestion on [BatleScribe's UserVoice](http://battlescribe.uservoice.com/).

**Comment by senpai514** [comment]
http://battlescribe.uservoice.com/forums/55066-general/suggestions/7899348-modifier-issues-with-show-items-in-parent-forces

Posted this a few days back.  Do you want to leave this open or close it. The issue can be worked around to prevent any errors.

**Comment by amis92** [comment]
Closing because it's BattleScribe bug and now deprecated by new SM catalogue.
