### ISSUE TITLE
Receiving errors when attempting to create a new Skitarii list

### ISSUE THREAD

**Issue by Steague** [BSData/wh40k-7th-edition#908]
Using BattleScribe v1.15.05

Steps to reproduce:
Create a New Roster with Skitarii Maniple as your detachment type and use the Skitarii: Codex (2015) as the source.

Result:
A BattleScribe error window pops up with the following error:

Details:
There were some problems with your data files. If you continue, this may lead to crashes or other strange behaviour.

> Skitarii: Codex (2015) v5: The catalogue data file is invalid:
> model.catalogue.Condition@36fa3bb0: Condition must have a child that exists
> model.catalogue.Condition@d8e2489: Condition must have a child that exists
> model.catalogue.Condition@2b0ce330: Condition must have a child that exists
> model.catalogue.Condition@7b558cdf: Condition must have a child that exists
> model.catalogue.Condition@a8b5622: Condition must have a child that exists
> model.catalogue.Condition@2a65a5a7: Condition must have a child that exists
>     at gui.rostereditor.g.f(Unknown Source)
>     at gui.rostereditor.g.b(Unknown Source)
>     at gui.rostereditor.g.b(Unknown Source)
>     at gui.rostereditor.g$2.actionPerformed(Unknown Source) **CLIPPED STACK**

**Comment by axisofentropy** [comment]
Wow what platform and battlescribe version?

**Comment by Steague** [comment]
Battlescribe version is in the initial report. This is on a Windows 8.1 64bit machine.

This is also from the master branch, not from the release.

**Comment by axisofentropy** [comment]
Can you reproduce it with v1.15.07?

**Comment by Steague** [comment]
Unable to repro in BattleScribe v1.15.07.
