### ISSUE TITLE
Khorne Demonkin - Axe of Blind Fury

### ISSUE THREAD

**Issue by mattFllr** [BSData/wh40k-7th-edition#914]
Hi,

For some reason I'm no longer able to give my herald an Axe of Blind Fury. Has it been removed?

Thanks.

**Comment by Skulltaker** [comment]
Axe of Blind Fury is a relic from Codex: Chaos Space Marines, and was never available to a herald.

The Axe of Khorne is not available to Heralds in Codex: Khorne Daemonkin.

**Comment by NebSeele** [comment]
Heralds cannot take from Melee weapons and the axe of blind fury is CSM, not Khorne Daemonkin (as skulltaker has said), so there is no bug here to speak of.

**Comment by mattFllr** [comment]
My axe naming was off, I meant Kor'Lath, the Axe of Ruin, an artefact of slaughter available to Heralds of Khorne Daemonkin.

**Comment by NebSeele** [comment]
Ahh, understand you now. 

I just double checked the codex on Kor'lath  and it's actually only allowed on Lords and Daemon Princes only. I had it on the Herald but removed it just shortly while fixing the other issues (that and I think it was reported along with Goredrinker to be an issue as well). So yeah, can't help there :(
