### ISSUE TITLE
Skitarii v5 Battle Maniple

### ISSUE THREAD

**Issue by prof-nobody** [BSData/wh40k-7th-edition#915]
With the Vanguard or Rangers when you increase the size of the unit to 10 character when you try to assign them 3 special weapons it presents an error.
![image](https://cloud.githubusercontent.com/assets/11951094/7147978/b461be66-e2c4-11e4-82cc-764f97c49006.png)

You should be allowed if there are 10 models to assign three special weapons.

**Comment by Thairne** [comment]
This works in the current files... Considering the error you get, this seems to be a lil' feth up in the data files.
If not already released, it will be fixed soon.
