### ISSUE TITLE
Bug report: Blood Angels - Codex (2014).catz

### ISSUE THREAD

**Issue by Silver3ullet** [BSData/wh40k-7th-edition#920]
File: Blood Angels - Codex (2014).catz

BattleScribe version: 1.15.07

Platform: Android

Description: Furioso Dreadnought do not have access to Blood talons

**Comment by Kangodo** [comment]
They do have them, it's the 'melee weapon' section and it's at Power Fists at default.
Could you recheck? Because my HTC doesn't have any issue with it.

**Comment by Silver3ullet** [comment]
Apologies,  found them now after data update.
