### ISSUE TITLE
Tau - Warzone: Damocles Formations

### ISSUE THREAD

**Issue by amis92** [BSData/wh40k-7th-edition#936]
- [x] Shadowsun's Firstrike Assault Hunter Cadre
- [x] Piranha Firestream Squadron
- [x] Ethereal Council
- [x] Hunter Cadre
- [x] Drone-Net VX1-0
- [x] Hammerhead Interdiction Cadre
- [x] Paradox Squadron
- [x] Ranged Support Cadre

**Comment by amis92** [comment]
@efalsken dropped me a line, he probably will take care of it.

**Comment by efalsken** [comment]
Done.
