### ISSUE TITLE
Daemonkin of Khorne and tablets

### ISSUE THREAD

**Issue by lacyj3** [BSData/wh40k-7th-edition#938]
Are the updates flowing to iPads?

iPad still version 20 and there have been several updates.

**Comment by lacyj3** [comment]
.catz

**Comment by NebSeele** [comment]
The updates on the GitHub are usually internal updates prior to the general releases. I don't know when the next release will be published but it'll be either the end of this week or next week.

**Comment by amis92** [comment]
Actually, I've just made release. I think better have this off, on weekend we'll make one for eldar. :)
