### ISSUE TITLE
Eldar Craftworlds (2015)

### ISSUE THREAD

**Issue by amis92** [BSData/wh40k-7th-edition#946]
Seems like we have no-one doing it?

**Comment by Toreador13** [comment]
I don't think so. I wonder if it scared everyone off.... I can start if there is no one else on it.

**Comment by amis92** [comment]
How would we name it? Internally and file?
EDIT: `Eldar Craftworlds - Codex (2015)` I guess: http://www.games-workshop.com/en-PL/Codex-Craftworlds-ENG ?

**Comment by senpai514** [comment]
Codex: Eldar - Craftworlds?

**Comment by amis92** [comment]
They write it without dash. ie `Codex: Eldar Craftworlds`

**Comment by efalsken** [comment]
For file naming: `Eldar Craftworlds - Codex (2015)`.
For display: `Craftworlds: Codex Eldar (2015)`

**Comment by Toreador13** [comment]
I would agree with GW's prolific release schedule we should probably keep
release dates on things just to make it a little easier.

**Comment by efalsken** [comment]
Especially with all the renaming of codexes. We should use the Codex's real name, and not what we would have liked them to call it.

**Comment by Toreador13** [comment]
Agreed. This release schedule could just make things crazy. New Imperial Knight codex next week. 

Anyone know how we are going to treat the Iyanden supplement? It looks like it should be retired since it references Codex Eldar and not Codex Eldar Craftworlds. Nothing official, but it has been removed for purchase, and it doesn't really work with the new codex.

**Comment by efalsken** [comment]
Lets wait and leave both Codex Eldar and Supplement Iyanden for 60 days. (sunset period) and wait to see if GW releases an Errata for Iyanden.

**Comment by Toreador13** [comment]
I agree with that.

**Comment by amis92** [comment]
yeah.

Ok, I've copied the file, re-generated its id and saved under new name. I _may_ get hold on the Codex by the weekend, but if someone has time earlier, go ahead.

**Comment by amis92** [comment]
um... @efalsken I actually gave another display name, `Eldar Craftworlds - Codex`. We may change that however without any serious consequences. But I feel most people will be looking under Eldar, not under 'C' near Chaos.

**Comment by Toreador13** [comment]
I will attempt to start working on it tonight. A lot of changes scattered throughout everything. I know the formation is going to be a bear to work on.

**Comment by Lostsoul81** [comment]
So how would one go about making one I have the codex wouldn't mind doing it if I got a lil help to start on it

**Comment by josephking79** [comment]
Hi,

I've seen the hard work that has been put in and I'm keen to get the data into Battlescribe. I've always just used the repository at appspot and new files are usually added automatically when I update the data file through battlescribe on my phone. I don't know how to import the new craftworld data file from github. Please will you explain how to get it? I'm a complete noob, so step-by-step instructions would help immensely. Thanks in advance, Joe

**Comment by josephking79** [comment]
Also, when will this be updated on appspot?

**Comment by thefbgnome** [comment]
Will the Valedor Formations be added?

**Comment by efalsken** [comment]
I have the Valedor book and can work on it once the core is stable and working.

**Comment by Xathlak** [comment]
From what I've read valedor formations are Apocalypse formations. Apocalypse formations are separate from normal formations.

**Comment by efalsken** [comment]
Correct. So they should be added as Battle Formations (force type Apocalypse). I just got done doing the same for the Tau Damocles formations.

**Comment by senpai514** [comment]
@amis92 what do you want to do in regards to all the current open issues for the old eldar codex?

**Comment by Toreador13** [comment]
Also, a release needs to be done to push Craftworld Eldar out, does it not? Is it about time? We will move Eldar to an archive, so should those issue move with it, just in case someone does want to work on it? I am not sure if anyone still uses the old files. Do we just remove them all?

**Comment by amis92** [comment]
Well we keep oldies in another repo, https://github.com/BSData/wh40k-old/graphs/traffic. Quick look at stats show there is no movement, but none is expected. I'd say we need not to move the issues. Anyone willing to use old file has to cope with unfixed issues. We're not Microsoft to care about backward support. :) So, I'm just going to close all the old issues as deprecated.

Yep, we need to do the release, I don't know whether it's ready or not. If it is, push it.

**Comment by amis92** [comment]
Uhm... so, #580, #696, #752, #761, #859 - deprecated, closed.

**Comment by amis92** [comment]
What do we do with Corsairs bug reports? #618, #772, #773, #776

**Comment by amis92** [comment]
Also, how do we stand with #593 in Craftworlds?

**Comment by thefbgnome** [comment]
Thanx for a great job... there will probably be some bugs (fire dragons in Aspect Host formation is missing the ability to take wave serpents for instance) should we just post here or start a bug thread?

**Comment by amis92** [comment]
Just open new issues for anything you find.

**Comment by amis92** [comment]
I think this one can be closed?

**Comment by Toreador13** [comment]
I haven't looked at Fighter Aces and probably won't until after I get the rest of the bugs fixed in Craftworlds. I haven't really looked at the Fighter Aces bit, so not sure what it entails. 

We can close it.
