### ISSUE TITLE
Eldar Craftworlds catalog is invalid

### ISSUE THREAD

**Issue by samwcoulter** [BSData/wh40k-7th-edition#952]
Details:
There were some problems with your data files. If you continue, this may lead to crashes or other strange behaviour.

> Eldar Craftworlds: Codex (2015) v1: The catalogue data file is invalid:
> model.catalogue.Condition@19ca843e: Condition must have a child that exists
>     at gui.rostereditor.g.f(BattleScribe:232)
>     at gui.rostereditor.g.b(BattleScribe:510)
>     at gui.rostereditor.g.b(BattleScribe:45)
>     at gui.rostereditor.g$2.actionPerformed(BattleScribe:350)
>     at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
> _clipped out stack trace_

**Comment by josephking79** [comment]
How can I get this file into Battlescribe? I'm a complete noob by the way. I rely on files being on appspot. If they aren't on there then I don't know how to incorporate them into my version of BS. Help would  be very much appreciated!

**Comment by Toreador13** [comment]
New version, and also old version opened up for me on multiple computers and iphone. Not sure what the issue is. Make sure you have the newest Battlescribe. 

New release should also make this invalid when it is pushed.
