### ISSUE TITLE
Contemptor Mortis Dreadnought - Book Reference

### ISSUE THREAD

**Issue by Xianator** [BSData/wh40k-7th-edition#954]
Reference for this unit should be Imperial Armour Apocalypse (2013) Page 16.

Currently it credits Imperial Armour Aeronautica p38.

**Comment by senpai514** [comment]
what codex catalogue are you referring to? this unit is in several.

**Comment by senpai514** [comment]
OK found it in Dark Angels.

Unit reference is actually going to be Imperial Armour 2nd Edition pg 178
