### ISSUE TITLE
Feature request: Daemonkin of Khorne 'Add Forgeworld'

### ISSUE THREAD

**Issue by lacyj3** [BSData/wh40k-7th-edition#956]
Are you planning to add Forgeworld models to the list?

**Comment by amis92** [comment]
Which would need addition? They'd need to explicitly mention this codex, I think. And I haven't heard of an update to the rules.

**Comment by NebSeele** [comment]
Outside of Samus, yeah there's not much that can be done. The Daemonkin of Khorne is a "Daemonkin of Khorne" faction, not the Chaos Space Marines of Chaos Daemons faction. Even if there's some really obvious choices it's still not valid to put them in.

I am going to email Forgeworld on the matter, however as it stands there is nothing to add.

**Comment by NebSeele** [comment]
Based on an email I recieved from Forgeworld (which I emailed anyways, as I am repurposing parts of my army to Daemonkin), it's not feasible to put it into the catalogue as of yet.  The instant the FAQ hits that says what FW models are allowed in Codex: Khorne Daemonkin I will add them.

I am closing for now.
