### ISSUE TITLE
Eldar Craftworlds codex

### ISSUE THREAD

**Issue by Savoronedge** [BSData/wh40k-7th-edition#958]
The currently listed Eldar Craftworlds codex uploaded by Toreador13 would not open for me. I modified the 2013 codex through Battlescribe's catalog editor. Mine works with the roster editor and appears to be correct, though not smooth. would like to provide my rough version for review/repair.

**Comment by amis92** [comment]
Um... current revision number 3 works for me on desktop. There was one moment it was corrupted, but it's fixed now. Thank you for report.
