### ISSUE TITLE
Bug Report - Eldar Codex Craftworlds

### ISSUE THREAD

**Issue by questing-knight** [BSData/wh40k-7th-edition#964]
The hemlock wraithfighter is not selectable when making a list.  I checked the catz file and it looks like you have checked the hidden check box for this unit under the units shared entry.  Should be a quick fix for you :)

**Comment by questing-knight** [comment]
You also have to link spirit stones to the hemlock's profile as well as the vehicle upgrades group.

**Comment by questing-knight** [comment]
I have an updated catz with the above fixes if you want to save some time.

**Comment by Toreador13** [comment]
Confused by what you mean with the spirit stones? Could you clarify?
All fixes are in the new file, just hasn't been released from Github yet. Lot of little fixes.

**Comment by questing-knight** [comment]
Thanks!  The hemlock has the equivalent of spirit stones for free.  It
ignores crew shaken on 2+ and crew stunned on 4+, according to the codex.
I don't have it in front of me at the moment but I can send you a screen
shot from the codex this evening.

**Comment by Toreador13** [comment]
Ok, that makes more sense. It had it as a blank rule, I went ahead and linked it to the spirit stones rule. Thanks for all the help with the issues. I had made a few lists with it, and found a few issues, but it takes more eyes, and mine are getting really blurry!

**Comment by Toreador13** [comment]
Fixed in v7.0

**Comment by questing-knight** [comment]
Thanks!  I appreciate all your hard work :)
