### ISSUE TITLE
Bug Report: Codex Tyranid Endless Swarm

### ISSUE THREAD

**Issue by corbinb13** [BSData/wh40k-7th-edition#965]
The requirement for the formation is:
1 warrior unit
2 termaguant units
3 Hormagaunt units

NOT

1 warrior unit
3 termagaunt units
3 hormagaunt units

**Comment by corbinb13** [comment]
After posting this it's come to my knowledge that there is a disagreement between the e-book and the I- book editions. I'm not sure which one is more correct

**Comment by amis92** [comment]
No-one knowns, I guess.

**Comment by senpai514** [comment]
I'd be more inclined to go along with the ePub variant as that will be the format that is much more widely distributed than the interactive

**Comment by senpai514** [comment]
I'll work on this and some of the open things overnight and upload after work

**Comment by Randobar** [comment]
Quite sure it is 

1 warrior unit
3 termagaunt units
3 hormagaunt units

the ebook got an update shortly after release to fix this too.
