### ISSUE TITLE
Eldar Craftworlds - Profile/Rule bugs

### ISSUE THREAD

**Issue by TailssTF** [BSData/wh40k-7th-edition#974]
Laser Lance (Melee): strength should be +3/User (now User/+3)
Star Lance (Melee): strength should be +5/User (now just 8) and there is no more Impact special rule.
//Star Lance fixed in v8
Warp Spider Exarch and Swooping Hawk Exarch: Wounds should be 2 (now 1)

**Comment by Toreador13** [comment]
Fixed laser lance and exarchs in v9.0.
