### ISSUE TITLE
[FW] Eldar Corsairs

### ISSUE THREAD

**Issue by amis92** [BSData/wh40k-7th-edition#988]
We have following bugs reported:
- [x] #618:

> Unfortunately, I am unable to select a Venom as DT for bladesworn retinue or harlequins, possibly others.
- [ ] #772:

> Errata for Void Dreamer misses entry, Void Dreamer may take Webway Portal +35p
- [x] #773:

> Mistake in the Hornet Entry: 
> weapon point costs are adopted to actual Eldar Codex (IA point costs are exanged)!
> 
> This change makes sense, but only if the Wasp War Walker also got these adaptations (this entry got original IA point costs)
- [x] #776:

> Corsair Jetbikes Weapon Selektion: 
> If you like to Chose a Shurikencanon, it is not possible to deselect the twinlinked shurikencatapult. If you try to select 0, it. is Not possible to select less than 1. And general I would say 2x twinlinked shuriken catapult is double selected...

Also, how do we go with Eldar Craftworlds update: does it change Corsair list at all?

**Comment by senpai514** [comment]
Those issues that I had just put my name next to are done and waiting sync with an internet connection.

**Comment by senpai514** [comment]
772 will be only remaining issue as I don't know where that mentioned errata is or can be found.

As for the new codex and updates, since the codex has a new name then technically an errata is needed.

**Comment by amis92** [comment]
As the mentioned errata is not currently available, I'm closing the issue as unresolved.
