### ISSUE TITLE
New eldar, missing formations. 

### ISSUE THREAD

**Issue by Jbat360** [BSData/wh40k-7th-edition#991]
Whilst selecting a formation detachment,  it has some missing detachments. 

It's missing;

hero's of the craftworld 
Living legends 
Outcasts 
Engines of vaul 
Wraith constructs 

It also has an extra formation for "ghost warriors" which doesn't exist in the book. 
![20150511_125833](https://cloud.githubusercontent.com/assets/12393952/7564599/34849d5e-f7e0-11e4-8516-34056981b49c.jpg)
![screenshot_2015-05-11-12-58-12](https://cloud.githubusercontent.com/assets/12393952/7564614/644378da-f7e0-11e4-84d6-67fa1f45f353.png)

**Comment by Jbat360** [comment]
I hope I've done this correctly, I'm completely new to this.

**Comment by Savoronedge** [comment]
The choices listed in the report are Auxiliary or Command choices in the Craftworld Warhost. They are not Formations separate from the Warhost, though the items in the screenshot are. The Ghostwarriors formation is leftover from previous editions and should be removed.
