### ISSUE TITLE
Bug: Harlequins 'Solitaire'

### ISSUE THREAD

**Issue by lacyj3** [BSData/wh40k-7th-edition#995]
ipad

The Solitaire can take one item the Enigmas of the Black Library.  

I don't see the Crescendo Pistol as an option.

**Comment by Savoronedge** [comment]
Crescendo is Troupe Leader/Shadowseer only.

**Comment by lacyj3** [comment]
I can't see where it says that?

**Comment by lacyj3** [comment]
Also, Solitaire is Precision Strikes and not Precision Shots.  Just noticed that.

**Comment by Kangodo** [comment]
Where they show the point-cost.
Crescendo has a little 1 after it, which means it is Troupe Master and Shadowseer only.

You are correct about the Solitaire and his Strikes/Shots; changing it.

**Comment by lacyj3** [comment]
I have a digital edition Harlequin codex.  

![crescendo](https://cloud.githubusercontent.com/assets/9757195/7594668/3f59f79e-f8b0-11e4-9b53-9eeab589c956.jpg)

**Comment by lacyj3** [comment]
![solitare](https://cloud.githubusercontent.com/assets/9757195/7594694/7859ea68-f8b0-11e4-8b97-98040821ae97.jpg)

**Comment by lacyj3** [comment]
![troupe](https://cloud.githubusercontent.com/assets/9757195/7594714/988427d6-f8b0-11e4-97a4-5d4ca5e26e17.jpg)
