### ISSUE TITLE
Imperial Knights missing units

### ISSUE THREAD

**Issue by hobodabobo** [BSData/wh40k-7th-edition#999]
In the new Imperial Knights data file, the Exalted court formation is missing the Gallant and the Crusader. Formation is 5 knights of any type.

**Comment by azraelcow** [comment]
Petition to re-open.  The Gallant and Crusader entries in the seem to be marked as hidden.  Not sure if warrants a new ticket but the formation also has copies of the knight entries rather than links.

**Comment by senpai514** [comment]
The issue is fixed but a release hasn't been so e yet to push the changes
out to the public just yet.

**Comment by senpai514** [comment]
@azraelcow I just pushed a release out with all the new fixes so they will be available to download shortly
